### ISSUE TITLE
use Precision-Recall Curve in object detection Model

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/tensorboard#1027]
Hi Dears,
I've some question about usage this capability of PR_curve in object detection api.
I've trained ssd_mobile_coco on my own dataset , i want to calculate PR-curve for my model.
what do i do ? how do i use these scrips. who ones that worked with these , please write step by step for this working.

**Comment by chihuahua** [comment]
Hello! Do the code examples within this README help?
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/pr_curve/README.md

**Comment by MjdMahasneh** [comment]
@zeynali Hi there, Could you please update the status of this issue and share if you managed to solve it. many thanks

**Comment by keyongyu** [comment]
@chihuahua, Zeynail was asking pr_curve for object detection,  I think https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/pr_curve/README.md is helpless, which is just for classification,  have to manually code to determine if the object is detected according to the bbox IOU.

**Comment by anacej** [comment]
are there any updates on this matter?

**Comment by bileschi** [comment]
Closing as a support issue over 1 year old.  Please re-open and clarify if this is still an issue.  Thanks!
