### ISSUE TITLE
Tensorboard killed when loading multiple models from subdirectories

### ISSUE THREAD

**Issue by CermakM** [tensorflow/tensorboard#1059]
version info:
 -  TensorBoard version 1.5.1 (also tested on 1.6.0)
 - TensorFlow version 1.5.0
 - Fedora 26
 - Python version 3.6.3
 
When creating multiple sub directories under `LOGDIR` using Estimator API for training and evaluation and issuing `tensorboard` command to the parent `LOGDIR` directory, the tensorboard outputs multiple lines like these:
> Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.              
> Found more than one metagraph event per run. Overwriting the metagraph with the newest event.

and then just outputs
> Killed

Therefore, I am not able to visualize multiple runs with tensorboard. I am open to suggestions in case I was doing something wrong. I am doing something similar to [this tutorial](https://github.com/dandelionmane/tf-dev-summit-tensorboard-tutorial/blob/master/mnist.py), but with Estimator API.

FWIW: Running tensorboard for single run is no problem, it crashes like this only with multiple sub directories.

Any help on this issue is greatly appreciated.

**Comment by nfelt** [comment]
Hmm, is that "Killed" message logged by TensorBoard or is it coming from Bash or whatever shell you're using to invoke `tensorboard`?  If possible, could you paste in the exact command line you're running and the output you're seeing?

I suspect the "found more than one ..." messages might be red herrings; those shouldn't normally cause TensorBoard to crash.

**Comment by CermakM** [comment]
Hello @nfelt,
Thank you for the answer.

I have no idea why, but after re-installing the whole tensorflow along with the tensorboard it works like a charm. The messages above are still there but it does not crash anymore.

The messages were outputed to the Bash, the command used is/was 
`tensorboard --logdir $PARENT_LOGDIR`.

`PARENT_LOGDIR` contains multiple `MODEL{1..3}` sub directories. The structure is still the same so I have no idea what could have caused the crash before.

BTW: The prefix of the messages is/was
```bash
W0321 08:27:45.543546 Reloader tf_logging.py:121]
```

I guess you can close the issue. Thank you for the help and sorry I can not provide more info on this (but in the end, at least we have everything working :+1: )

**Comment by nfelt** [comment]
Well, I'm glad that you were able to resolve the issue, even if it's mysterious!

**Comment by tshrjn** [comment]
Hi I'm facing a similar issue.

I've 2 different subdirectories where I store tensorboard log.

I was able to use tensorboard for both of them till last week. But now for one of the directories: I get `[1]    146144 killed     tensorboard --logdir experiments --port 6006`

But I don't have this issue when using the other directory.

**Comment by wchargin** [comment]
Just to say it explicitly (don’t see it in this thread): the lone
message “Killed” is emitted by Bash when the foreground command is
killed with SIGKILL (9). In the absence of explicit SIGKILL, this often
indicates that the OS’s out-of-memory killer has killed the process.

Is the process killed only after a long time? Does TensorBoard exhibit
high memory usage before being killed? If you’re on Linux, could you run

```
dmesg | grep -i 'killed process'
```

to see whether any processes have recently been killed (assuming that
your box hasn’t been restarted since the incident occurred)?
