### ISSUE TITLE
tensorboard scalars Smoothed and value, what is smoothed ?

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorboard#1060]
Hi,  

I have a silly question: In tensorborad, I tried to visualize the loss as Scalar, in the image, there is Name, Scalar, Value..., what is exactly Smoothed, it changes with step, but the value doest not change, which is not reasonable for me? and I can not find any documentation for this....

Really need your help.

**Comment by nfelt** [comment]
The Smoothed column value represents the result of applying smoothing to that series of data, so the value should be near the Value column but typically will be slightly different (can be greater or less).  If you set Smoothing to 0 using the slider, the values should be identical.

If you're seeing varying Smoothed values across steps but the Value column is fixed, that's a known issue with smoothing of a constant plot: #786.
