### ISSUE TITLE
can we plot two scalars in a figure?

### ISSUE THREAD

**Issue by jhlf** [tensorflow/tensorboard#1069]
I want plot two scalars in a figure.

Usually, we plot a scalar in a figure through `f.summary.scalar('loss', loss)`. 

But I want plot `loss1` and `loss2` in  a figure.  How can we do it?

Thank you!

**Comment by nfelt** [comment]
Check out the new custom scalars plugin:
https://github.com/tensorflow/tensorboard/tree/1.6/tensorboard/plugins/custom_scalar

Basically, you can write a custom layout that tells TensorBoard to generate a chart that includes both loss1 and loss2 together for comparison.
