### ISSUE TITLE
Nondeterminism in text_plugin_test

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorboard#1072]
https://github.com/tensorflow/tensorboard/pull/1021 introduced a test regression, likely caused by the hash map dict.keys() method introducing nondeterministic order.

```
======================================================================
FAIL: testPluginTagsImpl (__main__.TextPluginTest)
testPluginTagsImpl (__main__.TextPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tensorboard/plugins/text/text_plugin_test.py", line 404, in testPluginTagsImpl
    }, self.plugin.tags_impl())
AssertionError: {'fry': ['message', 'vector'], 'leela': ['message', 'vector']} != {'fry': [u'vector', u'message'], 'leela': [u'vector', u'message']}
repr() of differing entries:
'fry': ['message', 'vector'] != [u'vector', u'message']
'leela': ['message', 'vector'] != [u'vector', u'message']
```

I'm going to workaround this internally. This test should be fixed.

However I suspect this might be the tip of the iceberg with the multiplexer and accumulator. I'd very much like for us to move in a direction where our serving endpoints are deterministic, and not impacted by underlying hashing algorithms. SQL should help.

**Comment by chihuahua** [comment]
Thanks for reporting!
