### ISSUE TITLE
Tensorboard take an TypeError after change tensorflow-cpu to tensorflow-gpu

### ISSUE THREAD

**Issue by Geek-Peng** [tensorflow/tensorboard#1094]
win 10
tensorflow-gpu 1.7
tensorboard 1.7
error messages are as follows：
Traceback (most recent call last):
File "e:\anaconda\lib\runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "e:\anaconda\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "E:\Anaconda\Scripts\tensorboard.exe_main.py", line 5, in
File "e:\anaconda\lib\site-packages\tensorboard\main.py", line 30, in
from tensorboard import default
File "e:\anaconda\lib\site-packages\tensorboard\default.py", line 35, in
from tensorboard.plugins.audio import audio_plugin
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 30, in
from tensorboard.plugins.audio import metadata
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\metadata.py", line 22, in
from tensorboard.plugins.audio import plugin_data_pb2
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\plugin_data_pb2.py", line 63, in
options=None, file=DESCRIPTOR),
TypeError: init() got an unexpected keyword argument 'file'

before i changed the version，tensorboard worked，i don't know whether the tensorboard arguments are different between cpu version and gpu version
I will appreciate for your help

OS Platform and Distribution ： windows 10 64
TensorFlow installed from： pip
TensorFlow version： tensorflow-gpu 1.7
CUDA/cuDNN version： cuda 9.0 cudnn9.0
python version ： 3.5.2
GPU： Gtx 950

**Comment by chihuahua** [comment]
Could you please file this issue [within the tensorflow repo](https://github.com/tensorflow/tensorflow/issues/new)? I would myself, but I don't know your python version.

Thank you very much for filing. I'm very curious about getting to the bottom of this. It seems like the GPU version of TensorFlow might have broken some behavior when it comes to protos.

**Comment by Geek-Peng** [comment]
@chihuahua  Oh sorry, I updated my post. Thanks...

**Comment by chihuahua** [comment]
I see. Could you please re-file the issue here? https://github.com/tensorflow/tensorflow/issues/new

**Comment by Geek-Peng** [comment]
@chihuahua  I have already raise my question there ，yesterday

**Comment by Geek-Peng** [comment]
#18167 @chihuahua

**Comment by chihuahua** [comment]
What is version of protobuf that you use? If you run `pip freeze | grep proto`, what is the output?

**Comment by chihuahua** [comment]
Maybe try running `pip install --upgrade protobuf` to upgrade the version of the `protobuf` module you use.

**Comment by Geek-Peng** [comment]
@chihuahua  Appreciated for your suggest.The version of protobuf is low,and i updated it. Now it works.

**Comment by chihuahua** [comment]
Cool beans. :)
