### ISSUE TITLE
Tensorboard keras debugger feature

### ISSUE THREAD

**Issue by JonathanCMitchell** [tensorflow/tensorboard#1097]
I am unable to use the latest Tensorboard debugging feature with keras. When following the documentation posted [here](https://www.tensorflow.org/programmers_guide/debugger) and elsewhere I was instructed to insert the code snippet below:
```
import keras
from tensorflow.python import debug as tf_debug
keras.backend.set_session(
    tf_debug.LocalCLIDebugWrapperSession(tf.Session()), "<USER>:7000")


<Model fit generator stuff here>
```

Then I run the command `tensorboard --logdir=/logs/ --reload_interval=1 --debugger_port 7000` in a terminal window.

Then I run the program containing the model file and the `fit_generator` and I get this error
```
2018-04-02 15:00:01.435906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "coco.py", line 505, in <module>
    layers='heads')
  File "/home/jon/Documents/Mask_RCNN/model.py", line 2296, in train
    tf_debug.LocalCLIDebugWrapperSession(tf.Session()), "jon:7000")
TypeError: set_session() takes 1 positional argument but 2 were given
```
When I simply ommit the second argument to tf_debug.LocalCLIDebugWrapperSession(), I get the terminal output of tfdgb and it doesn't forward the port to tensorboard. 

Is this a versioning issue? 
 ==== Versions === 
`Tensorboard v 1.7`
`Tensorflow v 1.4.0`
`Keras v 2.4.1`
`Python3.5`
`Ubuntu 16.04`

When I look at the keras.callbacks.py file it is clear that the function set_session only contains one argument. You can see that [here](https://github.com/keras-team/keras/blob/416783156c1b07f28131c493a55a93936b5fe163/keras/backend/tensorflow_backend.py#L208)

**Comment by caisq** [comment]
@JonathanCMitchell `LocalCLIDebugWrapperSession` you are using is for the command-line interface, not the graphical debugger plugin. Can you try using [TensorBoardDebugWrapperSession](https://www.tensorflow.org/api_docs/python/tfdbg/TensorBoardDebugWrapperSession) instead?

**Comment by nfelt** [comment]
@caisq Hmm should the example snippet be updated then?

https://github.com/tensorflow/tensorboard/blob/998adf23e39058e7e3aef452b6ed56a04f4fef8f/tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html#L74-L75

**Comment by JonathanCMitchell** [comment]
Even with the additional update. Now I have the following inserted into my code:
```
from tensorflow.python import debug as tf_debug
        keras.backend.set_session(tf_debug.TensorBoardDebugWrapperSession(tf.Session("http://jon:6006")))
```
I have changed the `"http://jon:6006"` portion to be:
`"jon:6006"`. I am able to see the tensorboard gui, but it simply shows the popup screen:
![debugger](https://user-images.githubusercontent.com/13068956/38902171-4114980a-4254-11e8-84a2-98de1a9cb46e.png)
under the url `localhost:6006/#debugger`

I also run:
```
 tensorboard --logdir=<PATHTOLOGS>/logs --reload_interval=1 --debugger_port 7000
```

But I still arrive at the same error, which is:

```
2018-04-17 15:27:21.190495: E tensorflow/core/common_runtime/session.cc:69] Not found: No session factory registered for the given session options: {target: "jon:6006" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.

```
I don't know what to set the `grpc_debug_server_addresses` to. 
My computers name is `jon`.
