### ISSUE TITLE
TensorBoard doesn't handle [space] in paths properly

### ISSUE THREAD

**Issue by jythomaskim** [tensorflow/tensorboard#1106]
- TensorBoard version: 1.6.0
 - TensorFlow version: 1.6.0
 - OS Platform and version: MacOS High Sierra 10.13.3
 - Python version: Python 3.6.1
 - Browser and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit) 
 
If the path includes a space (e.g. folder name with spaces in between), the full path is not recognized. TensorBoard seems to handle the path up to the first space. 

"tbsum" is the folder that contains the tf summary files/logs, and it's inside a folder called "asdf asdf"

I type the following in the Terminal:
```
$ tensorboard --logdir /Users/jythomaskim/Desktop/asdf asdf/tbsum
TensorBoard 1.6.0 at http://Joons-MacBook-Pro.local:6006 (Press CTRL+C to quit)
```
When I access the localhost:6006 through Chrome, I get this message at the end:
Log directory: /Users/jythomaskim/Desktop/asdf

However, if I rename the folder name to "asdfasdf" (removing the space) and type the following in the Terminal:
`$ tensorboard --logdir /Users/jythomaskim/Desktop/asdfasdf/tbsum`

and then access the localhost:6006 through Chrome, TensorBoard works fine.

**Comment by nfelt** [comment]
This isn't an issue with TensorBoard; your shell is splitting the path at the space into two separate arguments to the command.  You just need to escape the space or quote the filename.

Either of these should work:

```shell
$ tensorboard --logdir /Users/jythomaskim/Desktop/asdf\ asdf/tbsum
$ tensorboard --logdir '/Users/jythomaskim/Desktop/asdf asdf/tbsum'
```

**Comment by Chet-Sheng** [comment]
> This isn't an issue with TensorBoard; your shell is splitting the path at the space into two separate arguments to the command. You just need to escape the space or quote the filename.
> 
> Either of these should work:
> 
> ```shell
> $ tensorboard --logdir /Users/jythomaskim/Desktop/asdf\ asdf/tbsum
> $ tensorboard --logdir '/Users/jythomaskim/Desktop/asdf asdf/tbsum'
> ```

Hi nfelt, 
I had a similar experience, I created a log folder: ‘Log_2018-11-14_14:06:29’.
Then, I tried both `$ tensorboard --logdir 'Log_2018-11-14_14:06:29'` in parent folder of log and `$ tensorboard --logdir .` in the log folder.
TensorBoard didn't show me scalar and graph, but it managed to give the projection of embeddings.
Once I changed the name of folder to be 'log', everything works fine. 
So, may I know what is happening here and what is the standard of folder naming for tensorboard?
