### ISSUE TITLE
[Plugin question] Is there support for 2-way communication?

### ISSUE THREAD

**Issue by marcoancona** [tensorflow/tensorboard#1122]
We believe the all plugin ecosystem has enormous potential and we would like to contribute to it in the direction of Interpretable Deep Learning. 
I think it would be beneficial to integrate into Tensorboard attribution visualization to explain a network behavior (see, for example https://github.com/marcoancona/DeepExplain)
Ideally, one will be able to select input and target nodes to generate attributions for directly from Tensorboard, in the same way currently the Debugger plugin allows to inspect tensors. This, however, requires to generate ops and evaluate them on demand.

My technical question is the following: do plugin APIs allow a 2-way interaction (through grpc) with a running graph/session? I see this is somehow done in the Debugger plugin thanks for `tf_debug` but all other plugins seem to only allow "passive" visualization, don't they?

**Comment by bileschi** [comment]
Closing as a support issue over one year old.  Please re-open if this is still relevant.  Thanks!

**Comment by bileschi** [comment]
FYI: There is no currently supported standard for communication outside of a plugin, though there are a few locations which use ad hoc solutions, such as referenced by @chihuahua
