### ISSUE TITLE
TensorBoard Error: Your CPU supports instructions that this TensorFlow binary was not compiled to use:AVX2

### ISSUE THREAD

**Issue by kapurvish** [tensorflow/tensorboard#1133]
I have written a small code, that adds two tensors, and after running it, I want to see the graph on the tensorboard, but when i type the  command : tensorboard --logdir=" " , on the windows command prompt.
I am getting the message:  Your CPU supports instructions that this TensorFlow binary was not compiled to use:AVX2

When i opened the CHROME: localhost:6006, I was able to open, but there was no graph.

 - TensorBoard version 1.7.0 version
 - TensorFlow version 1.7.0
 - Windows 7 Enterprise Edition  
 - Python version 3.5

**Comment by kapurvish** [comment]
Is it a TensorBoard bug of GOOGLE??

**Comment by jart** [comment]
This is a harmless warning that comes from our TensorFlow dependency, which can be ignored, or you can build TensorFlow from source, so CPU computations go faster for your hardware.

**Comment by kapurvish** [comment]
If this is a warning, then why I am not able to see the graph, when I open in chrome browser : localhost:6006, I am not able to see the graph.
