### ISSUE TITLE
keras  and tfdebug trying in browser

### ISSUE THREAD

**Issue by dgiunchi** [tensorflow/tensorboard#1136]
I follow instruction as the first popup in tensorboard shows for keras.
I've just tried using keras and I have a problem, keras set_session accept only session parameter (not the second). So I can't use this line:

tfk.backend.set_session(tf_debug.LocalCLIDebugWrapperSession(tf.Session()), "computername:port")

I use 

- tensorboard  is 1.7
- tensorflow is 1.7
- keras is 2.1.5
- windows 10
- python 3.6.5

I tried also with tf.keras. Any suggestions?

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorboard) since it's not a bug or feature request. There's a larger community there with better searchability.

**Comment by nfelt** [comment]
Duplicate of #1097

@dgiunchi The code sample was incorrect, this has been fixed in #1100, see the PR there for the corrected code sample.
