### ISSUE TITLE
Experimental db: Histogram does not render properly when reading data from db

### ISSUE THREAD

**Issue by skambha** [tensorflow/tensorboard#1141]
Repro: 
- From the[ histogram tutorial](https://www.tensorflow.org/programmers_guide/tensorboard_histograms), generate the events file
- Load the file using the loader
- Use the db option and view it in Tensorboard
The histogram and the distributions do not show correct results 
-----
There are 3 issues:
1. The calculation of the histogram buckets is incorrect per the histogramProto defined in 	[summary.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/summary.proto)
2. The data is getting clobbered in MigrateHistogram when writing it to a Tensor. This results in incorrect data being stored in the db
3. Data does not get rendered properly in the Tensorboard UI. TensorBoard itself doesn't expect to get DBL_MIN as a bucket boundary

**Comment by skambha** [comment]
The issue is for code in contrib/tensorboard/db.  I have a fix and will open a PR soon.

**Comment by skambha** [comment]
Opened the PR:  https://github.com/tensorflow/tensorflow/pull/18627

**Comment by nfelt** [comment]
I think this is resolved since the PR was merged; please comment if that's not the case.
