### ISSUE TITLE
Customizing tensorboard to display how many epochs are finished

### ISSUE THREAD

**Issue by disha3** [tensorflow/tensorboard#1143]
I have tensorboard dashboard for my training, it has the weight and bias variation and step count, but now I want to display how many epochs are finished and the amount of data it is training on.

Can I show that information in the current run without losing the older information.

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorboard) since it's not a bug or feature request. There's a larger community there with better searchability.
