### ISSUE TITLE
When I used tensorboard as tensorboard --logdir=logs ,it told me that:

### ISSUE THREAD

**Issue by nichenghyx** [tensorflow/tensorboard#1146]
![image](https://user-images.githubusercontent.com/20518717/39005441-d63e4b58-4432-11e8-8645-e33977981ad3.png)

**Comment by jart** [comment]
Try running `pip install tb-nightly`. See also #1111. We'll have a patch release out soon.

**Comment by nfelt** [comment]
Duplicate of #1111
