### ISSUE TITLE
Package Installation Error 

### ISSUE THREAD

**Issue by akhilkathi97** [tensorflow/tensorboard#1164]
I was installing **face_recognition** package found on git hub.https://github.com/ageitgey/face_recognition. The installation wasn't successful. The error shown is as follows -
 **```tensorboard 1.6.0 has requirement bleach==1.5.0, but you'll have bleach 2.1.3 which is incompatible.
tensorboard 1.6.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.```**

**Comment by nfelt** [comment]
The bleach (and html5lib) dependencies have been eliminated in #1142, which should be in the next TensorBoard release.  In the mean time, you'd have to install tensorboard 1.6 and face_recognition in a separate virtualenv or somehow avoid installing them in an environment where you already have bleach 2.1.3.

**Comment by nfelt** [comment]
Duplicate of #427
