### ISSUE TITLE
How to check  my input data in tensorflow projector

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/tensorboard#1167]
- TensorFlow version if different from TensorBoard 1.7.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04) ubuntu 17.10
 - Python version (e.g. 2.7, 3.5) 3.6

in the below image, I can choose to show data in a 3-D image after dimensionality reduction. but I can only choose weight of NN layers, How do I show my input data in this page and use the different color for different category?

![image](https://user-images.githubusercontent.com/5325686/39562105-65fc0524-4edc-11e8-881a-7329170a31fd.png)

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorboard) since it is not a bug or feature request. There is also a larger community that reads questions there. If you think we've misinterpreted a bug, please comment again with a clear explanation.
