### ISSUE TITLE
Tensorboard 1.8 shows nothing in the browser

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorboard#1171]
- TensorBoard version (from pip package, also printed out when running `tensorboard`)
Tensorboard 1.8 installed via pip
 - TensorFlow version if different from TensorBoard
Tensorflow 1.8 with GPU installed via pip
 - OS Platform and version (e.g., Linux Ubuntu 16.04)
Linux Ubuntu 16.04 x86_64
 - Python version (e.g. 2.7, 3.5)
2.7.12
 - For browser-related issues:
   - Browser type and version (e.g. Chrome 64.0.3282.140)
     Chrome Version 66.0.3359.139 (Official Build) (64-bit)
   - Screenshot if it's a visual issue

I installed tensorboard 1.8 using pip on Linux Ubuntu 16.04 along with Tensorflow 1.8 with GPU. I've two event files created with previous version of Tensorflow as well as with Tensorflow 1.8. When I launch tensorboard with --logdir to any of the directories on my Linux system, and try to access it in the Chrome/Firefox browser on Windows 7, it shows nothing. If I hover my mouse over the browser tab, it shows Tensorboard which means the linux system is reachable and tensorboard server too, but nothing is shown further and the page shows "The connection was reset" after a few mins. 
This has been checked on different systems and the result is same. I've also tried stopping firewall on Linux system but no luck. It used to work with Tensorboard 1.5.

**Comment by jart** [comment]
This sounds like a network connectivity issue and most likely isn't related to TensorBoard. There are various troubleshooting steps you can try like pinging. You're using a recent version of Chrome. Try also seeing if there's anything in the debugger console. Will reopen on new information.

**Comment by npanpaliya** [comment]
I checked in debug console too. I see only one request going and response coming from tensorboard with 200 OK. And after that it just stops sending/receiving data. Ping does work. Is there any other way to troubleshoot at tensorboard side?

**Comment by jart** [comment]
If you view source, does it show what appears to be TensorBoard source code? Screenshots of Chrome debugger panels would be helpful. It might also be helpful to have a screenshot of the HTTP request / response headers, which you should be able to obtain in the Chrome debugger.

**Comment by jart** [comment]
I recommend contacting your system administrator.
