### ISSUE TITLE
Library to generate tensorboard-compatible events from other programs

### ISSUE THREAD

**Issue by vincent-grosbois** [tensorflow/tensorboard#1172]
Hi!
It seems that the way tensorboard works is by polling tfevents files for specific protobuf messages and then parsing and displaying them.
For now, these messages are generated by Tensorflow through the EventWriter tensorflow class.
Is there any simple way to generate these messages from another 3rd-party program?
As far as I know it's just a matter of having access to the *.proto file definition and writing the events to a file, then the tfevents file would be readable by tensorboard.
Is there any plan to provide to 3rd party programs the ability  to generate tensorboard events? It could take the form a (small) library for instance.
Thanks!

**Comment by jart** [comment]
It should be as simple as copying the .proto files over. [dmlc/tensorboard](https://github.com/dmlc/tensorboard/tree/master/tensorboard/src) that did something similar. We're currently working on a SQLite storage format so folks can write data to TensorBoard without needing to worry about protobuf. What are your thoughts on this [schema](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/tensorboard/db/schema.cc)?

**Comment by vincent-grosbois** [comment]
Hi!
it seems that the proto events themselves are encoded, cf https://github.com/tensorflow/tensorflow/blob/49c20c5814dd80f81ced493d362d374be9ab0b3e/tensorflow/core/lib/io/record_writer.cc#L95 .
I think the schema idea is great, but in our use-case we already have protobuf integration and no SQLite integration, so it seems more complex to integrate this than "just" generating raw events that are binary-compatible with tensorboard.
So I'm assuming that the "official" way for 3rd-parties to write tensorboard events would be to use this new schema?

**Comment by bileschi** [comment]
Writing the correct protos in the correct places is still the preferred way of producing data that is understandable by tensorboard.  Both local tensorboard and tensorboard.dev.

**Comment by bileschi** [comment]
That said, it might be nice to be able to write tensorboard compatible objects without importing all of tensorflow.  Please re-open if that is the core of this issue
