### ISSUE TITLE
--path_prefix startup URL omits trailing slash

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1176]
When I execute `tensorboard --logdir storage/logs --path_prefix /test`, I get this message: ```TensorBoard 1.8.0 at http://lcswillems-ubuntu:6006/test (Press CTRL+C to quit)```. But when I click on the link, I get `Not found` page.

I precise that when I execute `tensorboard --logdir storage/logs`, it is working.

I use Tensorboard 1.8.0.

**Comment by lcswillems** [comment]
I solved this by replacing `/test` by `/test/` in the command. But there is an issue with the description of the `--path_prefix` argument. It is written:
> A leading slash is required when specifying the path_prefix, however **trailing slashes can be omitted**.

**Comment by nfelt** [comment]
Hm, what happens if you run `tensorboard --logdir storage/logs --path_prefix /test` but then visit the URL with a trailing slash, i.e. `http://lcswillems-ubuntu:6006/test/`?  If that works then it's likely just an issue with the URL that's being printed out, not with TensorBoard's actual URL handling for the path prefix.

**Comment by lcswillems** [comment]
It is working if I go to `http://lcswillems-ubuntu:6006/test/`.

**Comment by nfelt** [comment]
Thanks for checking - in that case I think it's just the logic for printing the URL out that would need a fix.

**Comment by zhangchen-qinyinghua** [comment]
https://github.com/tensorflow/tensorboard/pull/1620

This mistake is in deed trival. Someone please just correct it.

**Comment by amanp592** [comment]
@nfelt @wchargin i fixed the ommiting trail slash bug please review this!!
