### ISSUE TITLE
Parameter for automatically taking a free port (Feature request)

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1177]
If I execute `tensorboard --logdir dir1` then `tensorboard --logdir dir2`, I will get an error because the port 6006 is already used. Is there a way to select automatically a free port without having to add `--port 6007`? It will be a really nice feature, because I often open a lot of tensorboard server and I can't remember how many I opened and with which ports.

**Comment by nfelt** [comment]
You can use `--port 0` which should dynamically select an unused port.

https://unix.stackexchange.com/a/180500

**Comment by lcswillems** [comment]
What does this code do?

**Comment by jart** [comment]
It runs TensorBoard, which prints the port number to stdout, and the script intercepts the port number via a UNIX FIFO immediately without needing a sleep loop, then sends an HTTP request to TensorBoard, then waits for it to shutdown.
