### ISSUE TITLE
TensorBoard tutorial with tf.keras

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorboard#1179]
There are currently end-to-end tutorials using `tf.keras` and TensorBoard - at least, none that I could see in the TensorFlow repo.☺

It would be a nice enhancement to expand the documentation - even just to include the flower [transfer learning example](https://www.tensorflow.org/tutorials/image_retraining), or the MNIST example shown at [2017 TensorFlow Dev Summit](https://github.com/decentralion/tf-dev-summit-tensorboard-tutorial).

**Comment by jart** [comment]
I agree and we'd welcome contributions doing just that.

**Comment by dynamicwebpaige** [comment]
Excellent! Have been working on a quickstart today for the [1D CNN with imdb](https://github.com/keras-team/keras/blob/master/examples/imdb_cnn.py) example in Keras' docs.

It would be interesting to explicitly show how TensorBoard visualizations change as you:

* add layers (same activation function)
* add layers (different activation function)
* increase number of epochs, histograms
* include `write_images`, `write_grad`, and `write_graph`

Any other ideas / wish list items? ☺

Also: right now, the only way I can get support for tf.keras is by importing as `tensorflow.python.keras`. [ref](https://github.com/tensorflow/tensorflow/issues/15736)

Thanks!
.pb

**Comment by deblauwetom** [comment]
A tutorial on how to use the tf.summary... stuff would indeed be very welcome. Now we see all the examples, but only thing we can do is import a keras Tensorboard callback. Then for example I see the Scalars tab, but not the graph tab, and not the images tab. And I gave the write_graph and write_images options but nothing is seen. So yeah, a tutorial on how to debug such things with keras would be very cool!

**Comment by GalOshri** [comment]
Hi all! We've started adding some new documentation for TensorBoard [here](https://github.com/tensorflow/tensorboard/tree/master/docs/r2). The [get started](https://github.com/tensorflow/tensorboard/blob/master/docs/r2/get_started.ipynb) tutorial shows how to use TensorBoard with the Keras callback as well as with the `tf.GradientTape()` approach. There is also the [scalars tutorial](https://github.com/tensorflow/tensorboard/blob/master/docs/r2/scalars_and_keras.ipynb). 

More documentation will be added over time (especially covering the other TensorBoard dashboards), but it would be great to get your thoughts on whether the items discussed here are now covered!

**Comment by ChanchalKumarMaji** [comment]
I was planning to work on this issue as a part of GSoC-2019. Can anyone help me ? What all things are needed to be added.

**Comment by GalOshri** [comment]
Thanks for volunteering! I think the existing tutorials (e.g. [get started](https://www.tensorflow.org/tensorboard/r2/get_started) and [scalars](https://www.tensorflow.org/tensorboard/r2/scalars_and_keras)) cover the main points raised in this issue. Is there anything specifically missing? Otherwise, @dynamicwebpaige, do you think we should close this issue?

**Comment by brunapinos** [comment]
Hi! Is there anything that can be added on this issue? I'm working with new tutorials for TensorBoard, and I think this issue is already finished.

**Comment by bileschi** [comment]
from: https://www.tensorflow.org/tensorboard/get_started

```
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])
```
