### ISSUE TITLE
How could I embed the summary op implementation of my custom plugin with tensorflow?

### ISSUE THREAD

**Issue by justfouw** [tensorflow/tensorboard#1213]
I have created one plugin for specific visualization purpose under the tips from [tensorboard-plugin-demo](https://github.com/tensorflow/tensorboard-plugin-example). For simple to say, the plugin name is "plugin_a", and the summary op is implemented in function "op" of summary.py. So I can use this op like `summary.op(tensor_name, tensor)`. And it works.

However, the common way of using summary op is "tf.summary",  such as 
```
tf.summary.scalar=...
tf.summary.image=...
```

So, how could I integrate this custom summary op in tensorflow?

**Comment by nfelt** [comment]
The `tf.summary` namespace is limited to the built-in ops that come with TensorFlow itself.  If you've developed your own custom plugin, that's great, but you'll need your own way to distribute the custom summary op code.  As you noted, functionally the summary ops should still work fine if they're located elsewhere in the code; they don't need to be in `tf.summary`.

**Comment by justfouw** [comment]
@nfelt Yes, this custom plugin works. My purpose is to keep the same use experience as other build-in summary ops. I have checked the image summary op and find its original implementation is in //tensorflow/core/kernels/summary_image_op.cc. So it may need lots of work to distribute this custom summary op.

**Comment by nfelt** [comment]
You shouldn't need to implement any C++ code to write your custom summary op.  Just build the op out of other python ops and use tf.summary.tensor_summary() to log whatever data you need, as shown in the example.

For distributing it, as I said, you'll need to distribute the custom code separately since TensorFlow's namespace is only for the built-in premade ops supported by TensorFlow.  But it's functionally the same user experience once you've imported your code; you use the op just like a built-in one but with a different name.

**Comment by patzm** [comment]
@justfouw what about creating a summary wrapper?

e.g. in `my_organization/summary.py`:
``` python
import tensorflow as tf

scalar = tf.summary.scalar
text = tf.summary.text
image = tf.summary.image
audio = tf.summary.audio
histogram = tf.summary.histogram

merge = tf.summary.merge
merge_all = tf.summary.merge_all


def plugin_a(tensor_name, tensor):
    pass
```
and then in `whatever_script.py`:
``` python
import numpy as np
import my_organization.summary

text_tensor = tf.constant('Hi!', dtype=tf.string)
img_tensor = tf.constant(np.random.rand((128, 128, 3)), dtype=tf.float32)
data_tensor_you_have = ...

my_organization.summary.text('text summary', text_tensor)
my_organization.summary.image('image summary, img_tensor)
my_organization.summary.plugin_a('whatever', data_tensor_you_have)
```

**Comment by justfouw** [comment]
@patzm Thanks for your advice!
@nfelt Frankly, We have one custom-tensorflow in my orignization. So I need to integrate this plugin into our custom-tensorflow. I decide to put `plugin_a` in `contrib` directory.
