### ISSUE TITLE
Tensorboard (Embeddings Projector) not working with large checkpoint files

### ISSUE THREAD

**Issue by Sakib-Ar-Rahman** [tensorflow/tensorboard#1214]
- TensorBoard version (from pip package, also printed out when running `tensorboard`): 1.7.0
 - TensorFlow version if different from TensorBoard: 1.7.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04): macOS High Sierra Version 10.13.3
 - Python version (e.g. 2.7, 3.5): 3.6.5
 - For browser-related issues:
   - Browser type and version (e.g. Chrome 64.0.3282.140): Version 66.0.3359.139 (Official Build) (64-bit)
 
I am facing a problem with large checkpoint files when trying to visualize embeddings on Tensorboard.  This becomes a problem because a lot of the embeddings I am dealing with have a high number of features. The error that I get when running Tensorboard is:

> Error fetching tensors
> /Users/sakibarrahman/knowtions/elpis/static/tf_logs/tests/tensorboard_tests/tensorboard_test_model.ckpt-1.data-00000-of-00001; Invalid argument

Console:

> http://localhost:6006/data/plugin/projector/tensor?run=.&name=tensorboard_test&num_rows=100000
> Failed to load resource: the server responded with a status of 400 (BAD REQUEST)

Below is a simple script that reproduces the problem. Tensorboard runs perfectly fine if I just reduce the number of embeddings or change the number of features in the embeddings. This script produces large checkpoints (over 2GB). If I reduce the number of samples or the number of features in the embeddings (e.g. n_samples = 50000), Tensorboard works fine. Is there a size limit on Tensorboard or any way to override it? I could not find any mention of size limits in the documentations.

```
import tensorflow as tf
import numpy as np
import os
from tensorflow.contrib.tensorboard.plugins import projector


name = "tensorboard_test"
LOG_DIR = os.path.join(os.getcwd(), "static/tf_logs/tests/tensorboard_tests")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

NAME_TO_VISUALISE_VARIABLE = name

n_samples = 482493
n_features = 1370

path_for_metadata = os.path.join(LOG_DIR, name + '_metadata.tsv')
with open(path_for_metadata, 'w') as f:
    for i in range(n_samples):
        f.write(f"{repr(i)}\n")
print("Metadata file created")
arr_embeds = np.random.rand(n_samples, n_features)

#  Set to a tf variable
embedding_ph = tf.placeholder(tf.float32, arr_embeds.shape, name='embedding_place_holder')
embedding_var = tf.Variable(tf.zeros(arr_embeds.shape), name=NAME_TO_VISUALISE_VARIABLE)
var_init = embedding_var.assign(embedding_ph)
summary_writer = tf.summary.FileWriter(LOG_DIR)

#  Create projector
config = projector.ProjectorConfig()

#  Add embedding to the projector
embedding = config.embeddings.add()
embedding.tensor_name = embedding_var.name
embedding.metadata_path = path_for_metadata 
projector.visualize_embeddings(summary_writer, config)

print("Saving Data")
# Save the data
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
sess.run(var_init, feed_dict={embedding_ph: arr_embeds})
saver = tf.train.Saver()
saver.save(sess, os.path.join(LOG_DIR, name + "_model.ckpt"), 1)
```

**Comment by warunapww** [comment]
The tensorboard is running fine for the provided code with TF 1.8
Python: 3.6
OS: CentOS 7.4

**Comment by hgadig** [comment]
@Sakib-Ar-Rahman  Does this issue exist with the latest tensorboard version ?
