### ISSUE TITLE
Smoothing produces weird plots

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1224]
When `smoothing` is not 0, this kind of wierd graphs appear:

![image](https://user-images.githubusercontent.com/5437552/40934025-6f9565ec-6801-11e8-918d-f8c03f0317b5.png)

**Comment by nfelt** [comment]
What kind of plot are you expecting?  Is the plot supposed to be a constant, i.e. a horizontal line?  If so, this is a duplicate of #786.

In general, a screenshot of what you expect / what it looks like when smoothing is 0 would be useful.

**Comment by lcswillems** [comment]
When smoothing is 0, the line is horizontal what is right. And yes, it is a duplicate. Sorry!

**Comment by nfelt** [comment]
Duplicate of #786 

No worries, thanks for reporting anyway.
