### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'train'

### ISSUE THREAD

**Issue by ZinedineCerise** [tensorflow/tensorboard#1254]
Hello !
I use Visual Studio, Python 3.6(64-bit) and i have installed tensorflow (1.8.0), tensorboard (1.9.0) and tflearn (0.3.2) on Windows 10.

I have seen a lot of issues resolved on the same subject, but none have been efficient to solve mine. 
I am training a neuronal network to make edge detection, which is more or less working, but I would like to monitor the training. 
I make it using tflearn.

The line for the training is the following :

model = tflearn.DNN(network, tensorboard_verbose=3, checkpoint_path='edge-classifier.tfl.ckpt',tensorboard_dir="logs",)

So now I should just get the 'logs' file which is in the same folder than my programm by using the command line (by the way, the file is correctly created in my folder by my programm): 

tensorboard --logdir=training:F:\Dev\Embryo\Version2\TrainingCellsV2\TrainingCellsV2\logs

as I have seen it in many issues resolution on GitHub or else.

But it always get me the same answer : 

![image](https://user-images.githubusercontent.com/40293173/41461937-7fb44680-7091-11e8-9266-38d4d585cb9a.png)

And in fact even if I just write the line : tensorboard 
in my windows Shell (opened in administrator mode)
I always got the same mistake : AttributeError: module 'tensorflow' has no attribute 'train'

But when I check with python I can clearly see that there ain't any problem with the attribute 'train' in tensorflow : 
![image](https://user-images.githubusercontent.com/40293173/41462171-3d5c18de-7092-11e8-8663-b48b3d5fcdaa.png)

So I really don't see what to do, please help me, I can't get away with this since two days haha !

**Comment by nfelt** [comment]
Can you provide the output of the following commands in the same window shell window?

```
> tensorboard
> python -c "import tensorflow as tf; print(tf.train)"
> pip list
```

**Comment by ZinedineCerise** [comment]
Yes, when I write the command 1 :

```
PS C:\Windows\system32> tensorboard
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tensorboard\main.py", line 30, in <module>
    from tensorboard import default
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tensorboard\default.py", line 36, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tensorboard\plugins\beholder\__init__.py", line 15, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\tensorboard\plugins\beholder\beholder.py", line 192, in <module>
    class BeholderHook(tf.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'train'
```

**Comment by ZinedineCerise** [comment]
When I write the line : > pip list
I got :
`PS C:\Windows\system32> pip list
Package        Version
-------------- -----------
absl-py        0.2.2
astor          0.6.2
bleach         1.5.0
gast           0.2.0
grpcio         1.12.0
html5lib       0.9999999
Markdown       2.6.11
numpy          1.14.3
Pillow         5.1.0
pip            10.0.1
protobuf       3.5.2.post1
setuptools     39.2.0
six            1.11.0
tensorboard    1.8.0
tensorflow-gpu 1.8.0
termcolor      1.1.0
Werkzeug       0.14.1
wheel          0.31.1
PS C:\Windows\system32>`

**Comment by ZinedineCerise** [comment]
And when I write : > python -c "import tensorflow as tf; print(tf.train)"

`python : Le terme «python» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou
programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès
est correct et réessayez.
Au caractère Ligne:1 : 2
+  python -c "import tensorflow as tf; print(tf.train)"
+  ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by nfelt** [comment]
So the last error in running the python command looks like the shell just can't find the python binary.  How did you launch python before?  Can you launch it in the same way?

Overall, I'm not sure we can be much help - this seems like an issue with how your python installation is providing the `tensorflow` package import.  You could try reinstalling, and maybe try using a virtualenv for installing tensorflow since that's generally recommended.

**Comment by ZinedineCerise** [comment]
When I write it in my Visual Studio Shell :

```
>>> import tensorflow as tf
>>> print(tf.train)
<module 'tensorflow.tools.api.generator.api.train' from 'C:\\Users\\bcerisier\\AppData\\Local\\Continuum\\miniconda3\\lib\\site-packages\\tensorflow\\tools\\api\\generator\\api\\train\\__init__.py'>
```

Yes but honnestly I don't understant, i've already unistall and reinstall everything... (I am already in a virtualenv with Virtual Studio isn't it  ?)

**Comment by nfelt** [comment]
So wherever you were trying to run the `tensorboard` command, there needs to be a working tensorflow installation active.  Typically that's achieved by using virtualenv.  Visual Studio might include one (I don't know if it does) but it sounded like you were running `tensorboard` from the regular windows shell, which I assume is different?

Earlier it appeared that running `python` produced an error about not finding the python binary.  The key to getting this working would be to getting `python` working at the same shell that you were running `tensorboard`, and then ensure that from python you can run `import tensorflow as tf; print(tf.train)` and get working output like in the Visual Studio shell.

Until at least that much is working, there's not much on the TensorBoard end we can help with.

**Comment by ZinedineCerise** [comment]
So yeah I eventually decided to install Microsoft Visual Studio Tools for AI and run TensorBoard From Visual Studio. 
Which works fine, I should have done it from the beginning, thanks for the advice !

**Comment by ZinedineCerise** [comment]
(Should I close the issue then ?)

**Comment by nfelt** [comment]
Great, glad you got it working!  I'll close the issue then.

**Comment by IsbatKhanPolok** [comment]
t
