### ISSUE TITLE
Option to Generate PID File

### ISSUE THREAD

**Issue by derenrich** [tensorflow/tensorboard#1265]
I'm building a tool that manages tensorboard sessions and it would be helpful if tensorboard could generate its own pid file. Would you accept a PR to add a flag that would create a pid file at launch?

**Comment by jart** [comment]
Have you considered using `start-stop-daemon --make-pidfile`?

If you're productionizing TensorBoard, please take into consideration that many plugins were written under the assumption that there's a certain degree of trust, due to its historical use cases.

**Comment by jart** [comment]
I'm open to doing this, but might I ask how you managed to get TensorBoard to run on RHEL6? Was TF statically compiled with a custom toolchain? Was libstdc++.so replaced on the system?

**Comment by derenrich** [comment]
we're currently using the conda distributed binaries which are custom built (it's a delicate and suboptimal situation). we have issues with LIBC otherwise.

**Comment by wchargin** [comment]
Closing per <https://github.com/tensorflow/tensorboard/pull/1267#issuecomment-745445901>.
