### ISSUE TITLE
Figure shrank when switching pages

### ISSUE THREAD

**Issue by Seraphli** [tensorflow/tensorboard#1274]
Switching pages back and forward will cause this bug. But after a while when it automatically update the graphs, these plots will restore to the normal size.

 - TensorBoard version: 1.8.0 
 - TensorFlow version: 1.8.0
 - OS Platform and version: Linux Ubuntu 16.04
 - Python version: 3.6.5
 - For browser-related issues:
   - Browser type and version: Chrome Version 65.0.3325.181
   - Screenshot:

![screenshot from 2018-07-10 15-58-03](https://user-images.githubusercontent.com/1586755/42497054-8d029058-845a-11e8-990e-df280af47468.png)

**Comment by stephanwlee** [comment]
Hi @Seraphli, were you able to reproduce this issue in more recent builds like TensorBoard 1.12?  I have created the master bug #1473 to track these issues. Please let us know if you still face the issue in that bug. Thanks!
