### ISSUE TITLE
How to enable fuzzy search on tensorboard embedding projector?

### ISSUE THREAD

**Issue by TopologyApplied** [tensorflow/tensorboard#1278]
The embedding projector of tensorboard as is shown at

https://projector.tensorflow.org

Currentlt can do EXACT MATCH to search a word, but we want regex/fuzzy match.

For example,  we want to find the word "programming", but we forgot how to spell it, all we remember is a regex "prog.*ing"

The current projector template could not find any match.

How to modify the template to enable such a fuzzy or regex matching?

**Comment by hgadig** [comment]
Please go through this [paper](https://arxiv.org/pdf/1611.05469v1.pdf) which has good information on Embedding projector. Also [this](https://github.com/tensorflow/tensorflow/issues/6322) issue has some pointers to good examples.

**Comment by wchargin** [comment]
You can click the “Enable/disable regex mode” button next to the
“Search” field to search with a regular expression:

![Screenshot of the projector with regex mode enabled](https://user-images.githubusercontent.com/4317806/53607325-1e787780-3b73-11e9-965b-a7144804e9a3.png)
