### ISSUE TITLE
tensorboard does not find profile, if logdir directs to a parent directory

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorboard#1290]
usually we can direct tensorboard to a parent directory to see multiple models. however, tensorboard does not find the profiling data (by capture_tpu_profile), if logdir directs to a parent directory

**Comment by nfelt** [comment]
cc @qiuminxu

**Comment by qiuminxu** [comment]
Nice suggestion. Will send a PR to fix this. Hi @nfelt, can you assign the issue to me?

**Comment by nfelt** [comment]
@qiuminxu Hmmm I tried but I'm not able to pick out your github handle in the issue dropdown box, I think it's because you're not a member of the Tensorflow github org. I'll follow up internally.

**Comment by qiuminxu** [comment]
This should already have been fixed by the following PR:
https://github.com/tensorflow/tensorboard/pull/1931
