### ISSUE TITLE
tensorboard profiler trace_viewer does not work on firefox

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorboard#1291]
i am using tensorboard profiler to profile tpus. on chrome everything works. on firefox 61, all tools works except trace_viewer which shows an empty pain after loading

**Comment by nfelt** [comment]
cc @qiuminxu

**Comment by qiuminxu** [comment]
hi @eyaler, thank you for using the tool. The trace viewer tool in profiler plugins calls [Chrome trace viewer](https://github.com/catapult-project/catapult/blob/master/tracing/README.md) to render the events timeline. Sorry, our trace viewer tool currently only supports Chrome.

**Comment by eyaler** [comment]
i see. can this be added to the relevant docs?

**Comment by qiuminxu** [comment]
We're adding this to the official [cloud tpu tool docs](https://cloud.google.com/tpu/docs/cloud-tpu-tools).  It should be updated in a few days.

**Comment by stephanwlee** [comment]
The issue is now addressed in the [new plugin](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras). Please give the new plugin a try. Thanks!
