### ISSUE TITLE
TensorBoard op_profile op_details card mis-align over the Op Table

### ISSUE THREAD

**Issue by qiuminxu** [tensorflow/tensorboard#1393]
In TensorBoard v1.11 (master), the profile plugin op_profile tool has a op_details card, which is placed under the sidebar. Due to recent global change in sidebar css (PR #1296 ), the card now miss align with the Op Table, rather than the left of the window. 

See the screenshot below:

![tensorboard-image](https://user-images.githubusercontent.com/3082188/44863439-fc3c8600-ac31-11e8-8419-1829eb61dd4f.png)

I defined the fixed position [here](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html) for tf-op-details, but now it won't move the card align to the very left of the window. 

Is there a easy fix to this? @stephanwlee since you made that change, probably you would have the best idea.

**Comment by stephanwlee** [comment]
It has been addressed by #1394. Thanks for raising the issue :)
