### ISSUE TITLE
How to use What-If tool in tensorboard？

### ISSUE THREAD

**Issue by wqw547243068** [tensorflow/tensorboard#1416]
I am very excited at the coming tool [What-If](https://pair-code.github.io/what-if-tool/index.html#features)，but got a little conconfued about how to try it in tensorboard，if anyone knows，please tell me，thanks！

**Comment by nfelt** [comment]
@jameswex might be able to fill you in.  The What-If tool should be available in the next release of TensorBoard.  There is a readme available at https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/README.md

Closing this issue though, since we ask that the issue tracker only be used for reporting bugs and feature requests.

**Comment by jameswex** [comment]
As of the next release of TensorBoard, you should be able to access the What-If Tool in the dashboards drop-down at the top-right of TensorBoard. Alternatively, you can build from HEAD on master branch, or use a nightly build to see it in TensorBoard. From there, the instructions at https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/README.md should clarify things. Basically you need a tfrecord file of Example protos and a tensorflow serving (github.com/tensorflow/serving) model server running your model, with your model using either the Classification or Regression API provided by tensorflow serving.

**Comment by jameswex** [comment]
Images as input is supported in the tool and we will put out a colab notebook showing an example soon.

For time series data, you could encode it using tf.SequenceExample protos, which are supported as an input example type in the tool.

**Comment by SameerSharma21** [comment]
Thanks James. We would be starting to use the tool. Will contact you again if stuck at some place.
Cheers!!
