### ISSUE TITLE
what if tools don't support exported model from estimator

### ISSUE THREAD

**Issue by AlphaSue** [tensorflow/tensorboard#1423]
When I use what-if tools, I have to specify if the model is regression or classify as how you define your exported model. However, when I exported my model fro estimator by using 
tf.estimator.LatestExporter or tf.estimator.FinalExporter, I cannot set my signature method as regression or classify. It can only be set with prediction, which don't works in what-if tools.

Can any body tell me a way to fix this problem or can what-if tools supports prediction method type?

**Comment by nfelt** [comment]
cc @jameswex

**Comment by jameswex** [comment]
Have you tried following these directions (https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators) for exporting estimator models for serving?

**Comment by jameswex** [comment]
Here is another resource for how to export an estimator for serving with a classification or regression signature, so the What-If Tool can query it: http://shzhangji.com/blog/2018/05/14/serve-tensorflow-estimator-with-savedmodel/
