### ISSUE TITLE
tensorboard Keras callback fails: can't find tensorflow

### ISSUE THREAD

**Issue by Khev** [tensorflow/tensorboard#1425]
For some reason Keras can't find the tensorflow module when I try and use tensorboard (Keras and tensorflow are working fine otherwise). I'm using python 2.7 on ubuntu, and have updated Keras and tensorflow. My apologies if I'm missing something obvious.

Thanks!

## INPUT
""
from keras.callbacks import TensorBoard

index = int(0.9*len(X))
x_train, y_train = X[:index],y[:index]
x_test, y_test = X[index:], y[index:]
input_dim = X.shape[1]
output_dim = 1

#Define model
model = Sequential()
model.add(Dense(100, input_dim=input_dim,activation = 'relu'))
model.add(Dense(100, activation = 'relu'))
model.add(Dense(output_dim,activation='linear'))
model.compile(optimizer='sgd', loss='mean_squared_error')

#Add in tensor board
tensorboard = TensorBoard(log_dir='./logs', histogram_freq=0,
                          write_graph=True, write_images=False)

model.fit(x_train,y_train,verbose=1,callbacks=[plot_losses])
""

## OUTPUT

ImportError                               Traceback (most recent call last)
<ipython-input-12-b1ca2cb55780> in <module>()
     16 #Add in tensor board
     17 tensorboard = TensorBoard(log_dir='./logs', histogram_freq=0,
---> 18                           write_graph=True, write_images=False)
     19 
     20 model.fit(x_train,y_train,verbose=1,callbacks=[plot_losses])

/home/kokeeffe/anaconda2/lib/python2.7/site-packages/keras/callbacks.pyc in __init__(self, log_dir, histogram_freq, batch_size, write_graph, write_grads, write_images, embeddings_freq, embeddings_layer_names, embeddings_metadata, embeddings_data)
    734             from tensorflow.contrib.tensorboard.plugins import projector
    735         except ImportError:
--> 736             raise ImportError('You need the TensorFlow module installed to use TensorBoard.')
    737 
    738         if K.backend() != 'tensorflow':

ImportError: You need the TensorFlow module installed to use TensorBoard.

**Comment by nfelt** [comment]
What exact version of tensorflow are you using?  Can you run `from tensorflow.contrib.tensorboard.plugins import projector` successfully from your python shell?

**Comment by Khev** [comment]
I'm running tensorflow version '1.10.1'

I cannot fun the above command, I get the following complaint


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-130f93094534> in <module>()
----> 1 from tensorflow.contrib.tensorboard.plugins import projector

/home/kokeeffe/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/__init__.py in <module>()
     23 
     24 # Add projects here, they will show up under tf.contrib.
---> 25 from tensorflow.contrib import batching
     26 from tensorflow.contrib import bayesflow
     27 from tensorflow.contrib import checkpoint

ImportError: cannot import name batching

**Comment by nfelt** [comment]
Hmm, that's odd - I don't have that error when I try with TF 1.10 on ubuntu.  At this point however it looks like it's not really a TensorBoard issue, it seems like something in your tensorflow.contrib import tree is broken - you could try asking on StackOverflow?  Or just reinstalling a fresh TensorFlow.

**Comment by Khev** [comment]
Hi Nick,

I will try a reinstall -- thanks for your help!

Best,
Kevin

*Kevin O'Keeffe*
Postdoctoral Fellow
MIT Senseable City Lab <http://senseable.mit.edu/>

www.kevokeeffe.com
