### ISSUE TITLE
**I used the MobileNet_v1_1.0_224 tensorflow model for object detection. Now, I have my custom frozen graph (.pb file) that I need to convert to tflite extension so that I can use my model for mobile devices.**

### ISSUE THREAD

**Issue by Elites2017** [tensorflow/tensorboard#1443]
When I tried to convert it with the toco tool with the following parameter for output node name as it comes with the model itself in the info file --output_node_names=MobileNetV1/Predictions/Reshape_1 I got the **ValueError: Invalid tensors 'input' were found.** How can I get / see the input and output node names in tensorboard graph like this in the pictures obtained while training?

![pic 1](https://user-images.githubusercontent.com/35799396/45597494-77a28380-b9f7-11e8-89d4-7888cbc1052a.PNG)
![pic 2](https://user-images.githubusercontent.com/35799396/45597495-783b1a00-b9f7-11e8-9e04-001ccb02070e.PNG)

_Originally posted by @Elites2017 in https://github.com/tensorflow/tensorboard/issues/1261#issuecomment-421774153_

**Comment by nfelt** [comment]
In TensorBoard, you can use the node name regex search within the graph dashboard (should be on the top of the left-hand toolbar) to find graph nodes by name.

FYI, in general we prefer to keep the issue tracker limited to actual bugs or feature requests in TensorBoard.  For usage questions, StackOverflow has a broader audience.

**Comment by Elites2017** [comment]
> 
> 
> In TensorBoard, you can use the node name regex search within the graph dashboard (should be on the top of the left-hand toolbar) to find graph nodes by name.
> 
> FYI, in general we prefer to keep the issue tracker limited to actual bugs or feature requests in TensorBoard. For usage questions, StackOverflow has a broader audience.

The problem is that I don't know the input and output name of those nodes which I need in order to convert my frozen graph (.pb file) into tensorflow lite (.tflite) and I don't know how to get or see them from such a complex graph

![complexgraph](https://user-images.githubusercontent.com/35799396/45889337-61773780-bdea-11e8-8e56-3d182bebefd6.PNG)

**Comment by nfelt** [comment]
This might be more of a question for toco/tflite folks - this issue tracker is only for TensorBoard and I don't know enough about toco or tflite to really help with that aspect of your problem.  It sounded from the error message you got that the tensor in question might actually be named "input" in which case the graph dashboard search feature could help you find it.  But beyond that, I'm not sure how TensorBoard can help here.

**Comment by Elites2017** [comment]
It's okay. I'm closing this.
