### ISSUE TITLE
What-If Tool: Failed to build and run the demo from code

### ISSUE THREAD

**Issue by deagarwa** [tensorflow/tensorboard#1458]
While trying to run the Binary classifier for UCI Census dataset salary prediction demo, Bazel build is getting failed consistently with the following error:

<<<<
bazel run tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo:demoserver
INFO: Analysed target //tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo:demoserver (0 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/xyz/tensorboard-master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/BUILD:24:1: Vulcanizing /tf-interactive-inference-dashboard/index.html failed (Exit 1)
Error: Could not find or load main class %1$tH:%1$tM:%1$tS.%1$tL
Caused by: java.lang.ClassNotFoundException: %1$tH:%1$tM:%1$tS.%1$tL
Target //tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo:demoserver failed to build
>>>

Please help for any work-arounds.

Thanks in advance
Deepika

**Comment by nfelt** [comment]
@deagarwa could you please fill out the issue template?  I.e. include your bazel version, OS version, etc.

cc @jameswex

**Comment by deagarwa** [comment]
Thanks for the reply. Here are the environment details:
Bazel version: bazel-0.17.1-windows-x86_64
OS: Windows 10
Msys2, MS Visual Studio 2018
Java: jre1.8.0_181

**Comment by deagarwa** [comment]
Here is the o/p with --verbose_failures:
**$ bazel run tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo:demoserver --verbose_failures**
INFO: Analysed target //tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo:demoserver (0 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/deepika.d.agarwal/desktop/what-if/tensorboard-master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/BUILD:24:1: Vulcanizing /tf-interactive-inference-dashboard/index.html failed (Exit 1): **Vulcanize.exe failed: error executing command
  cd C:/users/deepika.d.agarwal/_bazel_deepika.d.agarwal/e5sz7w63/execroot/org_tensorflow_tensorboard
bazel-out/host/bin/tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.exe** ADVANCED true true /tf-interactive-inference-dashboard/index.html /tf-interactive-inference-dashboard/demo.html bazel-out/x64_windows-fastbuild/bin/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/demoserver.html NO_REGEXS external/com_google_javascript_closure_library/closure/goog/base.js external/com_google_javascript_closure_......

**Comment by deagarwa** [comment]
While compiling tensorboard, I am getting the same error related to Valcanizing:
**$ bazel run //tensorboard -- --logdir ./my_logs**
INFO: Analysed target //tensorboard:tensorboard (80 packages loaded).
INFO: Found 1 target...
**ERROR: C:/users/deepika.d.agarwal/desktop/what-if/tensorboard-master/tensorboard/components/BUILD:40:1: Vulcanizing /trace_viewer.html failed (Exit 1)**
Error: Could not find or load main class %1$tH:%1$tM:%1$tS.%1$tL
Caused by: java.lang.ClassNotFoundException: %1$tH:%1$tM:%1$tS.%1$tL
Target //tensorboard:tensorboard failed to build

**Comment by nfelt** [comment]
Closing this in favor of the new issue #1466.  I'll take a look at it when I get a chance to see if I can reproduce it, but right now I'm not sure I have any idea what's happening.
