### ISSUE TITLE
Visualization of the confusion matrix 

### ISSUE THREAD

**Issue by Issam-Jmili** [tensorflow/tensorboard#1462]
Hi !!
I am new in IA field and even I do not have a deep knowledge in python. So I am looking for help and please it is emergency.
My OS is Ubuntu 18.04.1 LTS
Python 2.7
Tensorboard 1.11.0
Tensorflow  1.10.1

I did follow the tutoriel like bellow :

1. virtualenv tensorflow
2.    source ~/tensorflow/bin/activate
3.    cd ~/example_code
4.    curl -LO https://github.com/tensorflow/hub/raw/r0.1/examples/image_retraining/retrain.py
5.     python retrain.py --image_dir ~/flower_photos --print_misclassified_test_images
        --how_many_training_steps 100
it did work and it gave me : 

from /tmp/_retrain_checkpoint
INFO:tensorflow:Final test accuracy = 84.6% (N=26)
INFO:tensorflow:=== MISCLASSIFIED TEST IMAGES ===
INFO:tensorflow:              /home/issam/flower_photos/daisy/267148092_4bb874af58.jpg  tulips
INFO:tensorflow:        /home/issam/flower_photos/dandelion/19602790836_912d38aaa8.jpg  daisy
INFO:tensorflow:          /home/issam/flower_photos/roses/17554868955_35f48516cd_m.jpg  tulips
INFO:tensorflow:            /home/issam/flower_photos/roses/17040847367_b54d05bf52.jpg  tulips
INFO:tensorflow:Save final result to : /tmp/output_graph.pb

and in the end it shows :

INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
INFO:tensorflow:Froze 378 variables.
Converted 378 variables to const ops.

I did copy the matrix_confusion.py and matrix_confusion_test.py in the foldre where retrain.py is installed and I wrote :

python matrix_confusion.py

the terminal didnt show anything no the confusion matrix and either no error just it took few seconds and show me a new line to code an instruction as usual.

So how can I resolve thiiiiiiis and thanks !!!

![capture d ecran de 2018-09-26 22-04-43](https://user-images.githubusercontent.com/39202005/46109408-6405d280-c1d8-11e8-816f-d72c3b337cd1.png)

**Comment by nfelt** [comment]
Where are you getting confusion_matrix.py?  You would perhaps have better luck following up with wherever confusion_matrix.py comes from - from the screenshot you shared it's unclear if it's even intended to be run as a script (as opposed to being imported).  You could also ask on StackOverflow or other TensorFlow support for help using the image retraining example.

Other than that, I'm not sure how you're expecting TensorBoard to help here.  TensorBoard currently doesn't directly visualize confusion matrices.  There are existing feature requests for this, #227 and #368, but we're not likely to implement that in the immediate future.  So if that's your concern, I recommend following along on those issues.

**Comment by Issam-Jmili** [comment]
Like I said I am new in this field ... Anyway Thanks ^^

**Comment by nfelt** [comment]
I think your best bet is asking wherever you got confusion_matrix.py.  Without knowing where that code is from there's not much else I can suggest, but I hope that helps.
