### ISSUE TITLE
Add sequence example support to What-If Tool

### ISSUE THREAD

**Issue by jameswex** [tensorflow/tensorboard#1502]
Allow loading of sequence examples in what-if tool

- Need to correctly parse and update sequence examples in python
- Need UI control for setting of sequence example mode
- Need facets dive to gracefully handle data from sequence examples
- Need to ensure servo classification/regression APIs can handle sequence examples

**Comment by jameswex** [comment]
This work is complete, with the exception of adding better display of sequence example data in Facets Dive.

**Comment by nfelt** [comment]
@jameswex just checking, is this still incomplete?

**Comment by jameswex** [comment]
It can be closed in that SequenceExamples are supported for use, although they don't display in the most pleasing of ways. That being said, no one uses WIT with sequence examples that I am aware of.

**Comment by nfelt** [comment]
Okay, fine with leaving it open or closing - whatever is most useful to you, just going through older bugs to make sure they're all triaged appropriately.
