### ISSUE TITLE
Fault tolerant event purging support for multi-machine summaries

### ISSUE THREAD

**Issue by manzagop** [tensorflow/tensorboard#1519]
TensorBoard version: TOT (guessing that's 1.11.0)
Python version 2.7

I'm training on tpu and hitting trouble with valid events being purged. I believe the issue is both the coordinator and the worker write summaries, but only the coordinator writes session start events. These session starts are then used to incorreclty invalidate worker events.

Does this make sense?

Thanks.

**Comment by gowtham-kp** [comment]
@manzagop Did you solve the issue or are you still facing with the same issue. Thanks!

**Comment by manzagop** [comment]
I did not! Instead, I parse summaries myself (without TB) using tf.train.summary_iterator, which has the benefit of giving full freedom to analyze and plot things the way you want.

**Comment by sanatmpa1** [comment]
@manzagop,

We are checking to see if this is still an issue,Can you please try updating the `tensorboard` to latest stable version and let us know if the issue still persists? You can also take a look at this [link](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_other_methods) for your reference. Thanks!

**Comment by manzagop** [comment]
Hi @sanatmpa1 !
I'm no longer using the setup and cannot confirm whether the issue still happens.
If no one else chimes in, I'd be fine with closing.
Thank you!

**Comment by sanatmpa1** [comment]
@manzagop,

Thanks for the update, I am closing this issue now.
