### ISSUE TITLE
Let users to choose the time interval of reloading data

### ISSUE THREAD

**Issue by qixiuai** [tensorflow/tensorboard#1522]
Now Tensorboard reloads data every 30s. Is it possible to make the time interval selectable for users?

**Comment by RylanSchaeffer** [comment]
Bump. Would it also be possible to disable auto-reload using the `--reload_interval` flag?

**Comment by psybuzz** [comment]
Thanks for the report.  In newer versions of TensorBoard, the reload period on the frontend can be set to a custom # of seconds or disabled.  Closing this issue.

![image](https://user-images.githubusercontent.com/2322480/105568210-7fbc0d80-5cec-11eb-88ab-2ea4e0ec9399.png)
