### ISSUE TITLE
values render then shift after 20 seconds

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/tensorboard#1528]
For bug reports, please include the following:

 - TensorBoard version: 1.11.0
 - TensorFlow version if different from TensorBoard: 1.11.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04): gLinux
 - Python version (e.g. 2.7, 3.5): python 3.5.3

screencast of my issue: https://youtu.be/7uFs90vJpfM

Notice at :27 to :30 when all of the values suddenly shift (value_cost goes from 4 to 1, policy_accuracy lines invert).

I have some weird tf event logs (I doubt all my steps are monotonically increasing) but this bevahior seems quite wrong.

**Comment by nfelt** [comment]
@stephanwlee this looks maybe like the tag-filtering stale data bug (#1499).  @sethtroisi were you using TensorBoard internally or externally?

**Comment by stephanwlee** [comment]
@nfelt that's what I suspected too.

**Comment by sethtroisi** [comment]
I was using it externally (I installed it via pip)

**Comment by sethtroisi** [comment]
I experienced this again today and the value I saw was one from a different graph. which does sound like the tag filtering stale data bug, I'll close as a duplicate

**Comment by nfelt** [comment]
@sethtroisi This should be fixed in our 1.12 release out soon.
