### ISSUE TITLE
ImportError: No module named 'tensorboardX'

### ISSUE THREAD

**Issue by edtky** [tensorflow/tensorboard#1535]
I am getting the above error when on this line:
from tensorboardX import SummaryWriter

I have done the following:

$ pip install tensorboardX
$ pip freeze
tensorboard==1.11.0
tensorboardX==1.4
tensorflow==1.11.0

Linux version on my instance:
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5

**Comment by stephanwlee** [comment]
The same issue: https://github.com/lanpa/tensorboardX/issues/255

**Comment by nfelt** [comment]
Closing since `tensorboardX` is a separate project from tensorboard itself; please follow up with them on their repo (e.g. on the issue above).
