### ISSUE TITLE
Tensorboard not displaying first summary

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorboard#1575]
After some steps, Tensorboard stops visualizing the first summary.

After first summary:
![image](https://user-images.githubusercontent.com/1200058/47954557-8fc06900-df8b-11e8-934a-115822427f97.png)
After training some steps it is no longer possible to slide back far enough:
![image](https://user-images.githubusercontent.com/1200058/47954570-a9fa4700-df8b-11e8-8c26-c162f33e9d6d.png)

 - TensorBoard version: 1.11.0
 - OS Platform and version: Arch Linux
 - Python version: 3.6.6

**Comment by stephanwlee** [comment]
Hi @Hoeze, thanks for the issue.

Do you only see last 10 steps? If so, it might be related to https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/application.py#L63

**Comment by Hoeze** [comment]
@stephanwlee No, not the *last* ten step, but:
You are right that there are always exactly 10 viewable steps.

However, the bigger problem is that the *first* step is not viewable.
Nevertheless, this might be a side-effect of limiting the number of viewable training steps.

**Comment by nfelt** [comment]
The reservoir sampling to produce the 10 samples unfortunately will not necessarily preserve the 0th step (or for that matter, any step other than the last one, which is always sampled).

To work around this, you can pass a flag to increase the sampling count until everything is shown: `--samples_per_plugin=images=N` where N is at least as high as the number of steps you have.

**Comment by hgadig** [comment]
Closing this issue as there is an explanation given for the behavior and a workaround is provided by Nick as above.
