### ISSUE TITLE
Model comparison in What-If Tool

### ISSUE THREAD

**Issue by jameswex** [tensorflow/tensorboard#1592]
Allow model comparison between two models in WIT

- Ability to specify multiple models
- Display inference results for multiple models
- Add results from multiple models to Facets Dive display
- Add performance results display for second model, in a way where easily comparable to first model. For both regression and classification models.
- Add PD Plots display for second model alongside first model

**Comment by tolga-b** [comment]
I think we can close this as well after #1672.
