### ISSUE TITLE
Download PNG clipped

### ISSUE THREAD

**Issue by PositronEternal** [tensorflow/tensorboard#1598]
in tensorboard 1.12.0 the "download PNG" results in a file that is cut off like this:
![graph_run](https://user-images.githubusercontent.com/44821036/48098131-69940680-e1e1-11e8-9f3b-c7c572b19066.png)

This is in Chrome and Firefox browsers on Ubuntu 18.04
pip list:
absl-py (0.6.1)
apturl (0.5.2)
asn1crypto (0.24.0)
astor (0.7.1)
astroid (2.0.1)
audioread (2.1.6)
autopep8 (1.3.5)
Brlapi (0.6.6)
certifi (2018.4.16)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
command-not-found (0.3)
cryptography (2.1.4)
cupshelpers (1.0)
cycler (0.10.0)
defer (1.0.6)
distro-info (0.18)
flake8 (3.5.0)
gast (0.2.0)
grpcio (1.16.0)
h5py (2.8.0)
hdf5storage (0.1.15)
httplib2 (0.9.2)
idna (2.7)
isort (4.3.4)
jellyfish (0.5.6)
Keras-Applications (1.0.6)
Keras-Preprocessing (1.0.5)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.0.1)
language-selector (0.1)
launchpadlib (1.10.6)
lazr.restfulclient (0.13.5)
lazr.uri (1.0.3)
lazy-object-proxy (1.3.1)
louis (3.5.0)
macaroonbakery (1.1.3)
Mako (1.0.7)
Markdown (3.0.1)
MarkupSafe (1.0)
matplotlib (2.2.2)
mccabe (0.6.1)
munkres (1.0.12)
musicbrainzngs (0.6)
mutagen (1.38)
notify2 (0.3)
numpy (1.15.4)
oauth (1.0.1)
olefile (0.45.1)
opencv-python (3.4.2.17)
pep8 (1.7.1)
pexpect (4.2.1)
Pillow (5.1.0)
pip (9.0.1)
protobuf (3.6.1)
pyacoustid (1.1.5)
pycairo (1.16.2)
pycodestyle (2.4.0)
pycrypto (2.6.1)
pycups (1.9.73)
pyflakes (1.6.0)
pygobject (3.26.1)
pylint (2.0.1)
pymacaroons (0.13.0)
PyNaCl (1.1.2)
pyparsing (2.2.0)
PyQt5 (5.11.2)
PyQt5-sip (4.19.12)
pyRFC3339 (1.0)
python-apt (1.6.3)
python-dateutil (2.7.3)
python-debian (0.1.32)
pytz (2018.3)
pyxdg (0.25)
PyYAML (3.12)
reportlab (3.4.0)
requests (2.19.1)
requests-unixsocket (0.1.5)
rope (0.10.7)
scipy (1.1.0)
scour (0.36)
screen-resolution-extra (0.0.0)
SecretStorage (2.3.1)
setuptools (40.5.0)
simplejson (3.13.2)
six (1.11.0)
system-service (0.3)
systemd-python (234)
tensorboard (1.12.0)
tensorflow-gpu (1.12.0)
termcolor (1.1.0)
typed-ast (1.1.0)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
Unidecode (1.0.22)
urllib3 (1.23)
usb-creator (0.3.3)
vboxapi (1.0)
wadllib (1.3.2)
Werkzeug (0.14.1)
wheel (0.32.2)
wrapt (1.10.11)
xkit (0.0.0)
zope.interface (4.3.2)

**Comment by PositronEternal** [comment]
I noticed that the tf-graph-minimap is also clipped in an identical manner

**Comment by stephanwlee** [comment]
Hi @PositronEternal, thank you for reporting issue. Would it be possible to share the event file or a minimal reproducible example? Thanks!

**Comment by PositronEternal** [comment]
Certainly,
I've attached my event file.  I've also went through a few trouble-shooting
steps:
remove and reinstall tensorflow, repeated with older versions of tensorflow
one-by-one
reinstall nvidia driver 390 from the ubuntu repo
reinstall nvidia driver 960 from the drivers repo
run tensorboard from a downloaded virtual machine pre-configured with
tensorflow and firefox (older versions)
regenerate the event file

I'm taking my event file to campus with me to try this on another physical
machine that hasn't been updated lately.  The problem is bizarre, it used
to work fine a few months ago.
Thanks!
-John W.

**Comment by PositronEternal** [comment]
The same issue appears on all of my machines with the event file provided.
The bizarre name it gives the export may be insightful:
"graph_large_attrs_key=_too_large_attrs&limit_attr_size=1024&run=.png"
It seems not to be a problem with simpler graphs/events.
-John W

**Comment by stephanwlee** [comment]
Hi @PositronEternal, unfortunately I was not able to receive the event file. Can you please attach it from the GitHub issue instead of replying to the email, perhaps? Thanks

**Comment by PositronEternal** [comment]
It appears to only affect large graphs like mine...

[events.out.tfevents.1541593524.zip](https://github.com/tensorflow/tensorboard/files/2558951/events.out.tfevents.1541593524.zip)

**Comment by stephanwlee** [comment]
Thanks a lot for the event file. I was able to identify the problem!
