### ISSUE TITLE
Conflicting code comments regarding smoothing parameter

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorboard#1621]
There are two comments in the master branch regarding the length of the smoothing window:

1. "a weight of 1.0 means using 50% of the entire dataset as the window"
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/vz_line_chart/vz-line-chart.ts#L82

2.  "1.0 still means a window of the dataset's length"
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/vz_line_chart/vz-line-chart.ts#L92

Aren't these two conflicting?

**Comment by wchargin** [comment]
Hi @bersbersbers!

Yes, these look conflicting to me. Moreover, they’re both wrong, as the
smoothing code has changed over the years and that documentation and the
accompanying documentation above on `smoothingEnabled` haven’t been kept
up to date. The smoothing algorithm isn’t really a “simple moving
average” at all; the smoothing weight is used as an interpolation
parameter, not a proportion of the dataset.

You should think of `smoothingWeight` as a _qualitative_ parameter
between 0 and 1, where `0` means “very little smoothing, possibly none”
and 1 means “a whole ton of smoothing, possibly so much as to make the
entire plot a constant” (neither extreme a very useful value). It was a
mistake to ever specify what were at one point the exact implementation
details. I can remove these from the docs for you.
