### ISSUE TITLE
Data selector’s `storage-utils.ts` has implementation-defined encoding behavior

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1625]
ECMAScript specifies that the precise behavior of `toString` when called
with a radix other than 10 is implementation-defined. For instance, the
result of `1.9.toString(36)` in various browsers is:

  - In Chrome 70.0.3538.110: `"1.weeeeeeeee"`
  - In Chromium 55.0.2883.0: `"1.weeeeeeeee97cr6myavtv5cdi"`

Our tests need to run both in Chrome (for development) and Chromium
(which is what WebDriver uses), but currently we expect the output to be
exactly `"1.weeeeeeeee"`.

In addition to making these tests robust, we should consider whether it
is appropriate for a storage utils module to use implementation-specific
behavior at all. Presumably, the URLs in which the data is stored should
be portable across browsers, so we should use only a well-specified
encoding.

**Comment by wchargin** [comment]
Discussed offline. The purpose of this `toString(36)` was to save space
because we can potentially have a lot of IDs. If we really want to save
space, we should consider using an actual compression algorithm. For
example, the `lz-string` NPM module has `compressToEncodedURIComponent`,
which should be appropriate for our use case. This would almost
certainly get far better compression and would be general rather than
ad-hoc.

For instance, <https://prettier.io/playground/> uses this to serialize
their URL hashes:
<https://github.com/prettier/prettier/blob/6c482e2e6c4d771407302fcc999bb3e2b491cbd3/website/playground/urlHash.js>

In the meantime, the simplest fix is to just not compress these numbers:
store `n.toString()` instead of `n.toString(36)`. The semantics for
`n.toString()` (equivalently, `n.toString(10)`) _are_ well-defined.

**Comment by nfelt** [comment]
Isn't that code only intended for use with IDs, aka integers?  Of course you can't enforce that in the types, but the decodeIdArray() function only parses out integers anyway, and we could always add an explicit check on the encoding side if we wanted to enforce it.

**Comment by wchargin** [comment]
Closed by #1639.
