### ISSUE TITLE
Have long text in What-If Tool examples wrap

### ISSUE THREAD

**Issue by jameswex** [tensorflow/tensorboard#1630]
The vz-example-viewer for what-if tool doesn't do a great job when a feature contains a very long string. Perhaps in one of its modes, the input box for feature values should wrap to multiple lines when given long strings so they are easier to read without lots of scrolling inside the input element.

**Comment by jameswex** [comment]
As requested by @BeenKim perhaps can just have a tooltip with the full feature value popup on hover. Will investigate which provides better experience.

**Comment by tolga-b** [comment]
#2141 fixes this.
