### ISSUE TITLE
path_prefix no longer working in 1.12.0

### ISSUE THREAD

**Issue by gar1t** [tensorflow/tensorboard#1632]
When I run:

    tensorboard --path_prefix /tb/0/

TensorBoard starts with this message (as expected):

    TensorBoard 1.12.0 at http://localhost:6006/tb/0 (Press CTRL+C to quit)

But the URL `http://localhost:6006/tb/0` if 404ing. The URL `http://localhost:6006/tb/0/` (slash at end) loads the index page (200 response). The index page makes requests to `http://localhost:6006/` as the base URL (ignores path_prefix) resulting in 404s for all requested URLs.

Behavior for 1.11.0:

- The URL `http://localhost:6006/tb/0` (no slash) 404s - this is arguably an issue with the startup message from TensorBoard, which displays the base URL without a slash
- The URL `http://localhost:6006/tb/0/` (terminating slash) succeeds (200 response)
- Index page requests correctly use the prefix

It would appear the regression occurred after 1.11.0.

System info:

 - TensorBoard version: 1.12.0
 - OS Platform and version: Linux Ubuntu 16.04
 - Python version: 3.5.2

**Comment by wchargin** [comment]
Hi @gar1t! Thanks for reporting this issue.

This is being addressed in #1623, which should merge soon.

**Comment by wchargin** [comment]
I’ll keep this issue open as a tracker.

**Comment by wchargin** [comment]
This should be fixed now that #1623 has merged.
