### ISSUE TITLE
stop the _reload_forever thread explicitly

### ISSUE THREAD

**Issue by tjsongzw** [tensorflow/tensorboard#167]
Hi,

say I wish to make tensorboard as a service, which means I have a server receive `launching a tensorboard` request, then the server activates a tensorboard server in another thread/process, rather than launching it via `tensorboard` on cmdline as usual.

it is observed that `start_reloading_multiplexer` always has the  `_reload_forever` thread running in background, even if shutdown the tensorboard server. So I simply put a `threading.Event` var over `while` statement instead of `while True`, then the thread is somehow under control. Does it fit into the whole tensorboard scenario? or it is only a specific one for myself.

**Comment by dandelionmane** [comment]
From [the docs](https://docs.python.org/2/library/threading.html):
> Note Daemon threads are abruptly stopped at shutdown. Their resources (such as open files, database transactions, etc.) may not be released properly. If you want your threads to stop gracefully, make them non-daemonic and use a suitable signalling mechanism such as an Event.

It would be better to have the thread shutdown gracefully when TensorBoard starts. Do you want to send us a pull request to fix this? Also, ccing @jart

**Comment by zuston** [comment]
Any update on it? 
When main thread exit, reload thread will failed when resources not be release properly. It will exit with code 134.

I think it may should stop the reload thread explicitly.
