### ISSUE TITLE
RawEventFileLoader performance

### ISSUE THREAD

**Issue by abiro** [tensorflow/tensorboard#1676]
Hi,

I've noticed that `RawEventFiledLoader.Load` is pretty slow, because of the `inspect.getargspec` call inside the loop which is there for backwards compatibility: https://github.com/tensorflow/tensorboard/blob/712d00a6e6b9892a513b08735633d8f07a0c8d49/tensorboard/backend/event_processing/event_file_loader.py#L55

I've profiled [this script](https://gist.github.com/abiro/3fd8f66c4b266a08a9184c969b474584) on an event file with 1m+ scalars and the `RawEventFiledLoader.Load` method spent 85% of its time in the `inspect.getargspec` call ([profiler output](https://gist.githubusercontent.com/abiro/655a18025c4cf4b37515e26efd1964cc/raw/a23103c48f804a3cb37446121fd4c2e696685395/profile.txt)).

I think there is an easy fix by moving the compatibility check outside of the loop and dispatching different wrapper methods based on the result of the check. Would be happy to provide a PR, please let me know if you're open to it.

Best,
Agost

**Comment by nfelt** [comment]
Thanks, yes - this should be done outside the loop, I agree.  If you'd like to send a PR that would be welcome.

**Comment by abiro** [comment]
Thanks! Submitted PR in #1686
