### ISSUE TITLE
new version tensor board

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorboard#168]
When I install tensorflow compiled from source v1.2.0, it automaticly install tensorflow-tensorboard in pypi. This tensorboard seems to display nothing, and console display nothing.
However using (https://github.com/tensorflow/tensorboard) this one compiled from source is OK.
Is it a bug?

**Comment by dandelionmane** [comment]
Can you please tell us:
- when you say "console display nothing", do you mean the JavaScript console inside the browser, the terminal when you launch TensorBoard, or both?
- By "display nothing", do you mean it loads the UI but no data, or the UI doesn't load?
- What browser and operating system are you using?

**Comment by cxwx** [comment]
when you say "console display nothing", do you mean the JavaScript console inside the browser, the terminal when you launch TensorBoard, or both?
**_Both_**
By "display nothing", do you mean it loads the UI but no data, or the UI doesn't load?
UI seems loaded, but no data. with only a white board
What browser and operating system are you using?
**_ubuntu 16.04, the browser I have tried firefox and chrome_**

**Comment by dandelionmane** [comment]
@cxwx 
Can you please upload the event file you are using so we can try to debug
