### ISSUE TITLE
Arrows in graph plugin disappear after opening debug plugin

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#1693]
![image](https://user-images.githubusercontent.com/2547313/50013493-206c6a80-ff76-11e8-8743-ec3ea72c8506.png)

Repro step:
1. Open graph plugin: notice the arrows (they are there)
2. Open debugger plugin. It does not have to be active. Just open it from the inactive plugin dropdown
3. Open graph plugin again. Arrows should be gone.

Reproducible in 1.12 and 1.12.1

**Comment by manivaradarajan** [comment]
Does this happen outside the use of the debugger plugin?

**Comment by stephanwlee** [comment]
To convey more information, this has to do with SVG `<defs>`. AFAICT, they need to be globally unique. Sadly two plugins, sharing some code, uses the same def ids and graph plugin seems to lose ability to refer to the def it created. But if my assertion is correct, it is odd that Chrome (different browsers behave differently in my past experience) does not use the newer instance of the definition (which should be exactly the same) when rendering the SVG in the graph plugin.

**Comment by stephanwlee** [comment]
This bug is no longer reproducible under Polymer 2+ where we started to use ShadowDOM. With ShadowDOM, these svg defs are encapsulated inside shadow root and do not interfere with each other.
