### ISSUE TITLE
Bug : tensorboard start "os_error":"nodename nor servname provided, or not known"

### ISSUE THREAD

**Issue by llv22** [tensorflow/tensorboard#1697]
- TensorBoard version (from pip package, also printed out when running `tensorboard`)
 - TensorFlow version if different from TensorBoard
 - OS Platform and version macOS 10.13.6
 - Python version (e.g. 2.7, 3.5) 3.6.7
 - For browser-related issues:
   - Browser type and version : Chrome 71.0.3578.98 0
   - Screenshot if it's a visual issue

Seems that gRPC port can't be started on mac port
```bash
$ tensorboard --logdir /tmp/logdir --host localhost --port 50000 --debugger_port 80000
I1217 15:39:17.984184 140736092279680 debugger_plugin_loader.py:114] Starting Interactive Debugger Plugin at gRPC port -1
Creating InteractiveDebuggerPlugin at port 80000
E1217 15:39:18.003311000 123145361346560 server_chttp2.cc:40]          {"created":"@1545032358.003293000","description":"OS Error","errno":8,"file":"src/core/lib/iomgr/resolve_address_posix.cc","file_line":108,"os_error":"nodename nor servname provided, or not known","syscall":"getaddrinfo","target_address":"[::]:80000"}
TensorBoard 1.13.0a20181126 at http://localhost:50000 (Press CTRL+C to quit)
```

Then client tensorflow program can't connect to debugger port

**Comment by llv22** [comment]
already find the root cause

**Comment by wchargin** [comment]
For the benefit of others: the problem was probably that the debugger
port was specified as 80000, but TCP uses 16-bit port numbers, so port
numbers must be at most 65535.

**Comment by llv22** [comment]
> For the benefit of others: the problem was probably that the debugger
> port was specified as 80000, but TCP uses 16-bit port numbers, so port
> numbers must be at most 65535.

Yes, I check grpc's code, then find... thanks ^_^
