### ISSUE TITLE
Issue: Receiving the following error (404) when trying to run Tensorboard

### ISSUE THREAD

**Issue by txb287** [tensorflow/tensorboard#1715]
Using Pycharm: "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32

Microsoft Windows [Version 6.1.7601]

TensorFlow/TensorBoard: 1.11.0 

Issue: Receiving the following error when trying to run Tensorboard

(venv) C:\Users\txb287\PycharmProjects\example>tensorboard --logdir=%s
TensorBoard 1.11.0 at http://UM-8V4NV12:6006 (Press CTRL+C to quit)
W1221 13:36:14.739831 Thread-2 application.py:300] path /[[_traceDataUrl]] not found, sending 404
W1221 13:36:14.739831 2125764 application.py:300] path /[[_traceDataUrl]] not found, sending 404
W1221 13:36:21.252286 Thread-2 application.py:300] path /[[getImageSrc(feat.name)]] not found, sending 4
04
W1221 13:36:21.252286 2125764 application.py:300] path /[[getImageSrc(feat.name)]] not found, sending 40
4
W1221 13:36:21.253288 Thread-1 application.py:300] path /[[getCompareImageSrc(feat.name)]] not found, se
nding 404
W1221 13:36:21.253288 2123824 application.py:300] path /[[getCompareImageSrc(feat.name)]] not found, sen
ding 404
W1221 13:36:21.258294 Thread-3 application.py:300] path /[[getSeqImageSrc(seqfeat.name, seqNumber)]] not
 found, sending 404
W1221 13:36:21.258294 2119700 application.py:300] path /[[getSeqImageSrc(seqfeat.name, seqNumber)]] not
found, sending 404
W1221 13:36:21.259295 Thread-4 application.py:300] path /[[getCompareSeqImageSrc(seqfeat.name, seqNumber
)]] not found, sending 404
W1221 13:36:21.259295 2122896 application.py:300] path /[[getCompareSeqImageSrc(seqfeat.name, seqNumber)
]] not found, sending 404

![tensorboard](https://user-images.githubusercontent.com/43892987/50359101-82564280-0529-11e9-95e8-f303f7dfcbd7.jpg)

**Comment by wchargin** [comment]
Hi @txb287! It looks like you’re using Internet Explorer, and that the
Polymer data binding polyfills aren’t working. Could you please try
opening the same URL in Chrome or Firefox?

**Comment by sanatmpa1** [comment]
@txb287,

You can try out this [workaround](https://stackoverflow.com/a/66283064/11530462) or you can refer this [similar issue](https://github.com/tensorflow/tensorflow/issues/9976). Closing this as it's an issue with older tensorboard 1.1.0 and so please try with the latest stable version and reopen the issue if it's still valid. Thanks!
