### ISSUE TITLE
AttributeError: module 'tensorboard.util' has no attribute 'PersistentOpEvaluator'

### ISSUE THREAD

**Issue by DummyCo** [tensorflow/tensorboard#1724]
Getting next error on `tensorboard` launch attempt:

```
PS C:\Users\user> tensorboard
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\appdata\local\programs\python\python36\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorboard\main.py", line 45, in <module>
    from tensorboard import default
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorboard\default.py", line 38, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorboard\plugins\beholder\__init__.py", line 15, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorboard\plugins\beholder\beholder.py", line 25, in <module>
    from tensorboard.plugins.beholder import im_util
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorboard\plugins\beholder\im_util.py", line 89, in <module>
    class PNGDecoder(util.PersistentOpEvaluator):
AttributeError: module 'tensorboard.util' has no attribute 'PersistentOpEvaluator'
```
Version:

```
PS C:\Users\user> pip show tensorboard
Name: tensorboard
Version: 1.12.1
Summary: TensorBoard lets you watch Tensors Flow
Home-page: https://github.com/tensorflow/tensorboard
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\users\user\appdata\local\programs\python\python36\lib\site-packages
Requires: werkzeug, markdown, protobuf, six, numpy, grpcio, wheel
Required-by: tensorflow-gpu
```
 - Windows 10, 64
 - Python version 3.6

Thank you!

**Comment by npv14** [comment]
I solved this problem by trying to merge my tensorboard\plugins folder with https://github.com/tensorflow/tensorboard

**Comment by RiteshBM** [comment]
Same Issue , @npv14 's solution didn't work for me.

**Comment by eelcor** [comment]
Same issue here. Have been compiling Tensorflow 1.12 myself to work on a Xeon without AVX instructions (but with Cuda). Both compiled Tensorboard and pipped Tensorboard show the same behavior.

**Comment by kenpachiii** [comment]
I got it working with the following steps:

1. `pip uninstall tensorflow`
2. `pip uninstall tensorboard`
3. go to site-packages and remove tensorflow/tensorboard folders
4. Reinstalled tensorflow - `pip install [whatever wheel package]` 

You can find the wheel packages here for specific install types:
 https://www.tensorflow.org/install/pip

Note: I only stated the specific wheel package because that's what I did. 

I know this doesn't explain the 'why' of the issue but it got things going for me. Hope it helps!

**Comment by eelcor** [comment]
Wat version of python do you use?

I need to compile it manually due to the lack of avx instructions.

Kind regards,

Eelco

Op ma 31 dec. 2018 03:22 schreef RiteshBM <notifications@github.com:

**Comment by stephanwlee** [comment]
Hello everyone, thanks for reporting the issue. Which version of TensorFlow have you installed? 
This can happen if you have tb-nightly installed on your virtualenv then install tensorboard==1.12.x. 

Like @kenpachiii put, can you try to delete tensorboad directory in site-packages (Location in `pip show tensorboard`) then `pip install tensorboard==1.12`?

**Comment by komcat** [comment]
I got same issue. Here is how I fix it by delete tensorboard folder & tensorboard.dist.info and reinstall tensorboard with respective version according to tensorflow.

mine is running 
tf-gpu 1.10
win10
python 3.6.4

**Comment by lucventurini** [comment]
Another hack to solve it is to manually edit your $PYTHONPATH/tensorboard/plugins/beholder/im_util.py file, and change it on line 25 like this:

from 

'''
from tensorboard import util
'''

to

'''
from tensorboard import util
from tensorboard.util import op_evaluator
'''

**Comment by RengXian** [comment]
@lucventurini your solution pop out another error.

AttributeError: module ‘tensorboard' has no attribute 'lazy'

**Comment by wookayin** [comment]
@RengXian Make sure that you don't have tb-nightly installed in your env.

**Comment by RengXian** [comment]
@wookayin Thanks a lot! it works just by uninstall the tb-nightly.

**Comment by Hayashi-Yudai** [comment]
@kenpachiii, @stephanwlee Thanks a lot. I use anaconda (Python 3.6.7), and installed tensorflow with conda command. I found two versions of tensorboard (1.12 and 1.13) were installed. So I delete both and reinstalled 1.12. As a result, the problem was solved.

**Comment by hgadig** [comment]
@DummyCo  Hi, did you happen to resolve this ? Please keep us posted.

**Comment by DummyCo** [comment]
@hgadig yep seems like clean reinstallation of tf and tb resolved the problem, Thanks everyone for sharing 'n attempts!

**Comment by Nfreshbird** [comment]
thanks,it do work! use pip show tensorboard and then delete all  directories about tensorboard ,next reinstall  a lower version of tensorboard (mine is 1.12).

**Comment by Kushagra3911** [comment]
Just type `pip install tensorboard` in the terminal.
