### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vdsprakash** [tensorflow/tensorboard#1748]
unable to run the tensorboard

**Comment by manivaradarajan** [comment]
Thanks for the bug report.

Please supply the following information to help us debug this issue:

 - TensorBoard version (from pip package, also printed out when running `tensorboard`)
 - TensorFlow version if different from TensorBoard
 - OS Platform and version (e.g., Linux Ubuntu 16.04)
 - Python version (e.g. 2.7, 3.5)
 - For browser-related issues:
   - Browser type and version (e.g. Chrome 64.0.3282.140)
   - Screenshot if it's a visual issue

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
