### ISSUE TITLE
Show hovered / selected image at the front in Tensorboard projector

### ISSUE THREAD

**Issue by dzimmerer** [tensorflow/tensorboard#1749]
I have a lot of big images in the embedding projector, so a lot of images overlap and displaying a single image as a whole is quite hard. 

It would be quite great if the hovered/ selected image would be rendered at the front (alternatively changing the image size might work as well).

Thanks,

**Comment by manivaradarajan** [comment]
Thanks for the problem report. This is a very reasonable request, but it's not currently in our plans. If you would like to take a stab at it, we're happy to review the contribution.
