### ISSUE TITLE
Help needed adding 3rd party datatable/grid to new plugin

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#1754]
- TensorBoard version: 1.12.0
 - OS Platform and version: Linux Ubuntu 16.04
 
Nice to talk with you at our first SIG group online today
I was the guy asking about plugins and 3rd parties from a TB-programmer perspective.

I'm following up on one of my questions from today.  My goal is to embed any datatable/grid into the a new TB plugin I'm writing.  However, most of the polymer-compatible datatables I see do not support older versions of polymer.  Except this one - this one is simple enough it might work: 

https://www.webcomponents.org/element/Saulis/iron-data-table

My new plugin's html files imports these:
```
<link rel="import" href="bower_components/iron-ajax/iron-ajax.html" />
<link rel="import" href="bower_components/iron-data-table/iron-data-table.html">
```

But my `bazel build tensorboard` output says this: 
```
ERROR: /home/cvinson/cvinson-dev/gitlab/tensorflow-tensorboard/tensorboard/plugins/gpu_summary/tf_gpu_summary_board/BUILD:11:1: Checking webfiles //tensorboard/plugins/gpu_summary/tf_gpu_summary_board:tf_gpu_summary_board failed (Exit 1)
ERROR: tensorboard/plugins/gpu_summary/tf_gpu_summary_board/tf-gpu-summary-board.html: Referenced bower_components/iron-ajax/iron-ajax.html (/tf-gpu-summary-board/bower_components/iron-ajax/iron-ajax.html) without depending on a web_library() rule providing it
ERROR: tensorboard/plugins/gpu_summary/tf_gpu_summary_board/tf-gpu-summary-board.html: Referenced bower_components/iron-data-table/iron-data-table.html (/tf-gpu-summary-board/bower_components/iron-data-table/iron-data-table.html) without depending on a web_library() rule providing it
```
I have tried adding entries to `tf_web_library` and `tensorboard_webcomponent_library` to no avail.

Could you give some guidance on how to update the bazel BUILD files so I can see the datatable?

Thanks,
-Chris

PS--As I'm about to submit this, I see a reference to a datatable in `plugins/profile/google_chart/google-chart-loader.html`.  If TB has Google Charts wrapped as a web component already, that would be even better.  Any guidance on its reuse into new TB plugins would be appreciated.

**Comment by wchargin** [comment]
Hi @ceevee830! Good to hear from you.

The `tf_web_library` Bazel rule for the `tf-gpu-summary-board.html` file
will need to depend on a webfiles rule that provides `iron-data-table`.
You can see similar components’ dependencies in our repository. For
instance, `iron-dropdown` is provided here:

<https://github.com/tensorflow/tensorboard/blob/280c5cc4ec878429c53817c64aec5d74257b5813/third_party/polymer.bzl#L187-L202>

and used here:

<https://github.com/tensorflow/tensorboard/blob/280c5cc4ec878429c53817c64aec5d74257b5813/tensorboard/components/tf_data_selector/BUILD#L27>

It looks like `iron-data-table` itself only depends on Polymer elements from the standard library…

```
$ git -C iron-data-table grep 'import.*href="\.\.' ':(exclude)demo/' ':(exclude)test/'
data-table-column-filter.html:<link rel="import" href="../paper-input/paper-input.html">
data-table-column-sort.html:<link rel="import" href="../polymer/polymer.html">
data-table-column-sort.html:<link rel="import" href="../paper-icon-button/paper-icon-button.html">
data-table-icons.html:<link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html">
index.html:  <link rel="import" href="../iron-component-page/iron-component-page.html">
iron-data-table.html:<link rel="import" href="../polymer/polymer.html">
iron-data-table.html:<link rel="import" href="../iron-list/iron-list.html">
iron-data-table.html:<link rel="import" href="../iron-resizable-behavior/iron-resizable-behavior.html">
iron-data-table.html:<link rel="import" href="../paper-spinner/paper-spinner-lite.html">
```

…which is good, because it means that you don’t have to add a sprawling
tree of transitive deps.

Can you try this out and let us know if you have any problems?

**Comment by ceevee830** [comment]
Yes I got this working - thank you for your help, and pointer to iron_collapse as a guide.  I could only find one string for the `urls` array.  Is this ok?
Has TB team thought about adding 'Google Charts' to TB as a 3rd party?  

```  web_library_external(
      name = "org_polymer_iron_data_table",
      licenses = ["notice"],  # BSD-3-Clause
      sha256 = "d8002a8e080ba165a76bf96066670a161aa72f062614c09d796d3a85c09b5dc5",
      urls = [
          "https://github.com/Saulis/iron-data-table/archive/v1.0.7.tar.gz"
      ],
      strip_prefix = "iron-data-table-1.0.7",
      path = "/iron-data-table",
      srcs = [
          "iron-data-table.html",
          "data-table-column.html",
          "data-table-column-sort.html",
          "data-table-cell.html",
          "data-table-row.html",
          "data-table-checkbox.html",
          "data-table-row-detail.html",
          "data-table-templatizer-behavior.html",
          "data-table-icons.html",
          "data-table-column-filter.html",
          "default-styles.html",
          "array-datasource.js",
      ],
      deps = [
          "@org_polymer",
          "@org_polymer_paper_input",
          "@org_polymer_paper_icon_button",
          "@org_polymer_iron_iconset_svg",
          "@org_polymer_iron_resizable_behavior",
          "@org_polymer_iron_list",
          "@org_polymer_paper_spinner"
      ],
  )
```

**Comment by wchargin** [comment]
Great! Glad to hear it.

It looks like the license is Apache-2 and not BSD 3-Clause, so you might
want to update the comment. The license category is still “notice”.
(Also, given that this isn’t an official Polymer component AFAICT, the
`org_polymer_` prefix might be misleading.)

> I could only find one string for the `urls` array. Is this ok?

We always include the `mirror.bazel.build` URL even if the content
hasn’t actually been mirrored there. The backend will silently ignore
URLs that don’t resolve, and the Bazel mirror is typically substantially
faster than GitHub when it does have the files. I’ll get this file added
to the mirror for you. (But—yes, nothing will break if there is only one
URL.)

> Has TB team thought about adding 'Google Charts' to TB as a 3rd party?

There’s been some interest in it, and we appear to have vendored some
form of it in #1268. I don’t know of any further plans than that.

**Comment by wchargin** [comment]
Mirror is up:

```
$ curl --silent 'https://mirror.bazel.build/github.com/Saulis/iron-data-table/archive/v1.0.7.tar.gz' |
> shasum -a 256
d8002a8e080ba165a76bf96066670a161aa72f062614c09d796d3a85c09b5dc5  -
```

**Comment by ceevee830** [comment]
Perfect.  Thanks.
