### ISSUE TITLE
Tensorboard cant see tfevent file generated using  Intel AI academy Tensorflow scripts

### ISSUE THREAD

**Issue by dgunner01** [tensorflow/tensorboard#1756]
For bug reports, please include the following:

 - TensorBoard version 1.12.2)
 - TensorFlow version 1.12.0
 - OS Platform and version Microsoft Windows 10.0.17134.523
- Jupyter notebook server version 3.6.3
 - Python version (Intel Python 3.6.3 from Intel distribution)
 - Intel AI academy course Tensorflow101   -   - Screenshot if it's a visual issue
 

Please describe the bug as clearly as possible, and if possible provide a minimal example (code, data, and/or command line) to reproduce the issue.  

I execute the provided scripts in Intel AI Academy course Tensorflow101 Class1 using jupyter notebook.  One of the scripts generates a TFevent file in directory  tbout/basic_sys.  I can see the file.  From the Windows cmd I start tensorboard and it says to paste HTTP:/Gunners:6006 into a new browser window.

From jupyter notebook I start a new notebook and paste the above into the search line.  This is supposed to bring up a screen that enables analysis of the data.

Instead it shows the following screen
--------------------------------------------------------------------------------------------------------
TensorBoard

Inactive 

No dashboards are active for the current data set.
Probable causes: 
You haven’t written any data to your event files. 
TensorBoard can’t find your event files. 
If you’re new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial. 
If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub. 
Last reload: not yet loaded 
Data location: tbout/basic_ops 
_____________________________________________________-

There is a TFevent file in the directory

**Comment by wchargin** [comment]
Hi @dgunner01! Based on the error message, it looks like you invoked
TensorBoard with the logdir set to `tbout/basic_ops`, but you say that
you see the event file in `tbout/basic_sys`. Could you make sure that
the logdir that you’re passing is actually the directory that contains
the events file?

If this doesn’t work, we’ll need to see the script that you’re using to
generate the data.

**Comment by dgunner01** [comment]
I don't know how to make sure that the logdir is the correct one.  I explain.

I am working in Jupyter notebook.   The files for the notebook I am working with are located here.
My Documents/ deep learning/ Intel-TF101-Class1    according to Jupyter Notebook.

Windows says that the files are here - This PC\Documents\My Documents\deep learning\Intel-TF101-Class1.   I have tried different file settings for tensorboard and they did not help.


The Python script the notebook uses follows-

sess = tf.Session(graph=graph)
sess.run(init) # don't forget to run init for our Variable!

# Feed values for placeholders `a` and `b`
a_val, b_val = 8.0, 4.0
feed_dict = {a: a_val, b: b_val}
fetches = [inc_step, plus, minus, times, divided]
results = sess.run(fetches, feed_dict)

# Print all results
print("a: {} b: {}".format(a_val, b_val))
for i, result in enumerate(results):
    print("{}: {}".format(fetches[i].name[:-2], result))

writer = tf.summary.FileWriter('tbout/basic_ops', graph=graph)
writer.close()
sess.close() # clean up the session

_____________________________________________________________-
The script produces correct results and generates a TFevent file.
The lesson then says to  "Navigate to the notebook directory inside your console and type the following:"
$ tensorboard ---logdir=about/basic_sys.


The above command does not work, so I open a windows CMD window and type tensorboard  --logdir=about/basic_sys and tensorboard starts.  I paste  http//:Gunners:6006 into a notebook session as suggested and get the above message.

Let me know if this is the information you require.
Thanks for your help.

Don

**Comment by dgunner01** [comment]
William

Thanks for the reply and an apology for the directory confusion.  there are only one directory active now - tbout/ops.

in reply to your request here is the requested information.

Location of files
C:\Users\Don Gunning\Documents\My Documents\deep learning\Intel-TF101-Class1\tbout\basic_ops

in this directory there is a .ipnb_checkpoints folder and 4 files with names like events.out.tfevents.1547403230.GUNNERS


here is the tensorboard command line that I enter

C:\Users\Don Gunning>tensorboard --logdir=Documents\My%Documents\deep%learning\Intel-TF101-Class1\tbout\basic_ops

I enter the command you provided and got the following screen back from Microsoft edge location localhost:6006

TensorBoard



Inactive 






No dashboards are active for the current data set.
Probable causes: 
You haven’t written any data to your event files. 
TensorBoard can’t find your event files. 
If you’re new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial. 
If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub. 
Last reload: not yet loaded 
Data location: Documents\My%Documents\deep%learning\Intel-TF101-Class1\tbout\basic_ops 

End of screen data.

Note - tensorboard says to use http://GUNNERS:6006 to start the data analysis.  That command produces the same result.

Hope this helps

Again Thanks for the help.

Don

**Comment by wchargin** [comment]
> here is the tensorboard command line that I enter
> 
> C:\Users\Don Gunning>tensorboard --logdir=Documents\My%Documents\deep%learning\Intel-TF101-Class1\tbout\basic_ops

Where are these percent signs coming from?

Could you please `cd` into the `Intel-TF101-Class1` directory, so that your command prompt starts with


```
C:\Users\Don Gunning\Documents\My Documents\deep learning\Intel-TF101-Class1>
```

and then run

```
tensorboard --logdir=tbout
```

?

**Comment by dgunner01** [comment]
tensorboard aborts if there are spaces in the --logdir directory.  Replace spaces with % and tensorboard starts.

Here is the tensorboard CMD and startup result.

C:\Users\Don Gunning\Documents\My Documents\deep learning\Intel-TF101-Class1>tensorboard --logdir=tbout
W0117 08:17:17.482863 Reloader tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.482863 17240 tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.482863 Reloader tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
W0117 08:17:17.482863 17240 tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
W0117 08:17:17.536249 Reloader tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.536249 17240 tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.536249 Reloader tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
W0117 08:17:17.536249 17240 tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
W0117 08:17:17.567505 Reloader tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.567504 17240 tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0117 08:17:17.567505 Reloader tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
W0117 08:17:17.567504 17240 tf_logging.py:120] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.
TensorBoard 1.12.2 at http://Gunners:6006 (Press CTRL+C to quit)

End

When I enter http://localhost:6006 in a browser, I get a screen that looks like this

Tensorboard
Graphs

Inactive (a box appears here)

If I try to send the whole screen, gitbub aborts

Don

**Comment by wchargin** [comment]
> tensorboard aborts if there are spaces in the --logdir directory.

If you want to pass an argument to a program, and that argument has
spaces, then you will need to _quote_ the argument. Otherwise, it will
be interpreted as multiple arguments.

You can try this yourself by creating a Python file called `args.py`
with the following contents:

```python
import sys
for (i, arg) in enumerate(sys.argv):
  print("%s: %s" % (i, arg))
```

Then, try invoking it with different kinds of arguments:

![Screenshot of behavior of `args.py` with various arguments (explained below)](https://user-images.githubusercontent.com/4317806/51341481-3e7e2c80-1a46-11e9-8617-27d2183f628a.png)

Observe that if you write `--logdir=one two three` then this is
interpreted as three arguments, separated by spaces. This isn’t what you
want. Quoting the part of the argument that contains the spaces—or the
whole argument—yields the expected behavior.

> Replace spaces with % and tensorboard starts.

Sure, this will get the logdir to be interpreted as one argument, but
it’s no longer pointing to the right path! The actual path doesn’t have
any percent signs in it, so it’s no surprise that TensorBoard doesn’t
find any event files when it looks there.

> Here is the tensorboard CMD and startup result.

The output indicates that TensorBoard has indeed found your data. From
your description, it sounds like TensorBoard is properly displaying the
graph dashboard. Is this correct?

If not, please attach an image of what TensorBoard looks like. You can
learn how to take a screenshot here:

<https://www.take-a-screenshot.org/windows.html>

**Comment by dgunner01** [comment]
William
My apologies for not replying.  was away and had a Python issue that took time for me to fix.  will get back to the issue.

Your help is appreciated.  Don

**Comment by dgunner01** [comment]
William


There is not supposed to be any active file summaries, just a graph. When I click on the graph word, I get the grey quarter circle.


![image](https://user-images.githubusercontent.com/46654657/51929586-30bd9500-23be-11e9-9ca0-9b2a1c89a3f3.png)


 don

**Comment by stephanwlee** [comment]
@dgunner01 From the screenshot, it looks like you are using IE. TensorBoard does not support it. Can you please try it with Edge, Firefox, or Chrome? Thanks!

**Comment by dgunner01** [comment]
Yea.  It works just fine.  


William and Stephan
Thanks for all the help.  Muchly appreciated.   I can now get on with my learning.

Issue resolved.
