### ISSUE TITLE
Google Charts plugin availability

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#1763]
- TensorBoard version (1.12.2)
 - OS Platform and version (e.g., Linux Ubuntu 16.04)

So I'm really interested in using 'google charts' for some upcoming visualizations I'm working on for two reasons: 
  1) I've used google charts before in a Tomcat web server (ie, familiar), and 
  2) As expected, the iron-data-table compatible with Polymer1/TensorBoard is pretty rudimentary.

Bazel does not complain when I build tensorboard, but when I launch TB in a browser I see this in console (see `ReferenceError: google is not defined`):
```
paper-toolbar is deprecated. Please use app-layout instead! 10.110.40.143:6006:29936:196
ReferenceError: google is not defined [Learn More] 
  _loadPackagesDebounce/
  complete 
  a/this.boundComplete 
Reading graph pbtxt : 1 ms
```

Question: Is my configuration wonky?  If not, do you have a working example of google charts in TensorBoard?  If not, what do you recommend?

Source (as suggested by tensorboard/plugins/profile/google_chart/google-chart.html)
```
<link rel="import" href="../google-chart/google-chart.html">
<link rel="import" href="../google-chart/google-chart-loader.html">
<link rel="import" href="../google-chart/google-chart-styles.html">
<link rel="import" href="../google-chart/google-chart-demo.html">

<dom-module id="tf-gpu-summary-board">

    <google-chart
      type='pie'
      options='{"title": "Distribution of days in 2001Q1"}'
      cols='[{"label":"Month", "type":"string"}, {"label":"Days", "type":"number"}]'
      rows='[["Jan", 31],["Feb", 28],["Mar", 31]]'>
    </google-chart>

</dom-module>
```

BUILD (note how I'm attempting to use a library in a sibling plugin - is that ok?)
```
tf_web_library(
    name = "tf_gpu_summary_board",
    srcs = ["tf-gpu-summary-board.html"],
    path = "/tf-gpu-summary-board",
    visibility = ["//visibility:public"],
    deps = [
        "@iron_data_table",
        "@org_polymer_iron_collapse",
        "@org_polymer_iron_ajax",
        "@org_polymer_paper_progress",
        "@org_polymer_paper_button",
        "@org_polymer_webcomponentsjs",
        "//tensorboard/plugins/gpu_summary/tf_gpu_summary",
        "//tensorboard/plugins/gpu_summary/tf_gpu_summary_common",
        "//tensorboard/plugins/gpu_summary/tf_gpu_summary_info",
        "//tensorboard/plugins/profile/google_chart:google_chart",
        "//tensorboard/plugins/profile/google_chart:google_chart_demo",
        "//tensorboard/components/tf_imports:polymer",
     ],
)
```

Thanks!

**Comment by wchargin** [comment]
It looks like you must load <https://www.gstatic.com/charts/loader.js>
into the page for Google Charts to work. You should be able to vendor
that directly, or include it as a `<script>` element at runtime, like
the profile plugin does:

<https://github.com/tensorflow/tensorboard/blob/d285c7de73a09e9ece5a13368a58c00e1dcabda9/tensorboard/plugins/profile/google_chart/google-chart.html#L490-L495>

Evaluating that script will define the `google` property on the global
object.

> note how I'm attempting to use a library in a sibling plugin - is that
> ok?

This is supported; there’s no technical problem with doing it. It’s up
to you whether you feel that it’s appropriate for your use case: it
makes your code more brittle due to potential changes in the profile
plugin, and might also feel semantically wrong in some cases.

**Comment by wchargin** [comment]
> Would that be better if you move the Google Charts component to a
> centralized location for both profile and gpu summary plugin to use?

That would make sense if we wanted TensorBoard to commit to provide
Google Charts to plugins. We’re discussing this internally.

**Comment by ceevee830** [comment]
Hi William,

So I made a 3rd party google-charts plugin and I'm getting bazel compiler error.  I'm hoping you could identify the culprit.

third_party/polymer.bzl
```
  web_library_external(
      name = "tb_google_chart",
      licenses = ["notice"],  # Apache-2
      sha256 = "c355df65b3d095c02ffa10ec7d9b17a773dd4f87993058c6d691eb5413ca2ed3",
      urls = [
          "https://github.com/GoogleWebComponents/google-chart/archive/v2.zip"
      ],
      strip_prefix = "google-chart-2",
      path = "/tb-google-chart",
      srcs = [
            "google-chart-api.html",
            "google-chart-control.html",
            "google-chart-control.js",
            "google-chart-dashboard.html",
            "google-chart-dashboard.js",
            "google-chart-data.html",
            "google-chart-data.js",
            "google-chart-editor.html",
            "google-chart-editor.js",
            "google-chart.html",
            "google-chart.js",
            "google-chart-loader.html",
            "google-chart-loader.js",
            "google-chart-query.html",
            "google-chart-query.js",
            "index.html",          
      ],
      deps = [
          "@org_polymer",
          "@org_polymer_iron_ajax",
          "@org_polymer_iron_component_page",
          "@org_polymer_webcomponentsjs",
      ],
  )
```

my gpu_summary_board BUILD file
```
package(default_visibility = ["//tensorboard:internal"])

load("//tensorboard/defs:web.bzl", "tf_web_library")

licenses(["notice"])  # Apache 2.0

tf_web_library(
    name = "tf_gpu_summary_board",
    srcs = ["tf-gpu-summary-board.html"],
    path = "/tf-gpu-summary-board",
    visibility = ["//visibility:public"],
    deps = [
        "@tb_google_chart",
     ],
)
```
And my html code
```
<link rel="import" href="../tb-google-chart/google-chart.html">

<dom-module id="tf-gpu-summary-board">
    <template>
        <style></style>
        <span>top of google chart</span>
        <google-chart
          type='pie'
          options='{"title": "Distribution of days in 2001Q1"}'
          cols='[{"label":"Month", "type":"string"}, {"label":"Days", "type":"number"}]'
          rows='[["Jan", 31],["Feb", 28],["Mar", 31]]'>
        </google-chart>
        <span>bottom of google chart</span>

    </template>

  <script>
      Polymer({
        is: 'tf-gpu-summary-board',

        attached: function() {
          console.log('tf-gpu-summary-board: ')
          var url = "https://www.gstatic.com/charts/loader.js";
          var script = document.createElement('script');
          script.src = url;
          document.head.appendChild(script);
        },
        
      });
  </script>
</dom-module>
```
When I do a `bazel build tensorboard` I see this:
```
2019-01-17 16:11:17.728 SEVERE /google-chart/google-chart.html.js:5: ERROR - Variable GoogleChartElement declared more than once. First occurrence: /tb-google-chart/google-chart.js
  Polymer({
  ^^^^^^^^^

2019-01-17 16:11:17.729 SEVERE /tb-google-chart/google-chart-loader.js:91: ERROR - variable styleElement is undeclared
  styleElement = document.createElement('style');
  ^^^^^^^^^^^^

2019-01-17 16:11:17.729 SEVERE /tb-google-chart/google-chart.js:35: ERROR - variable GoogleChartLoader is undeclared
const loader = new GoogleChartLoader();
                   ^^^^^^^^^^^^^^^^^

```

Is it an include file ordering problem?

**Comment by wchargin** [comment]
Interesting. From the error logs, it appears that two webpaths are being
included: `/tb-google-chart/` (from your code) and `/google-chart/`
(from the profile plugin). It may well be a legitimate complaint of the
compiler that the `google-chart` Polymer element is being declared more
than once: I wouldn’t be surprised if this were to make Polymer angry.

The second error seems like a mostly harmless (but genuine) bug in
`google-chart-loader`. You can suppress it by using `jscomp-suppress`
when loading the library (which is fine to do when including third-party
code: see, e.g., #1732):

```html
<link rel="import" jscomp-suppress href="../tb-google-chart/google-chart.html">
```

(I suspect that this will suppress some errors as well, but I am not
sure which errors are fatal errors and which will be silently ignored.)

I’m not sure whether the third error will cause any problems: it
potentially could, if it were to impact the Closure compiler’s mangling.

For your testing and development purposes, a hacky solution that should
get you off the ground is to simply remove the profile plugin from the
list of plugins that TensorBoard builds: this should prevent the
duplication that causes the first error. The principled fix, as
@qiuminxu mentioned above, would be to extract and share the common
dependency so that it’s only included once.

I hope that this should unblock you in the short term—let me know
otherwise.

**Comment by ceevee830** [comment]
Getting closer but not there yet.  In the log file I see this!!!
`Google Charts v46.2 loaded with packages: corechart`

Old business
1) Adding the `jscomp-suppress` helped bazel build to reveal zero errors.  Three errors without that string, zero errors with it.
2) Instead of removing the profile plugin, I pointed the profile plugin to use `tb-google-charts`.  
plugins/google_chart/BUILD
```
# tf_web_library(
#     name = "google_chart",
#     srcs = [
#         "google-chart.html",
#         "google-chart-loader.html",
#         "google-chart-styles.html",
#     ],
#     path = "/google-chart",
#     visibility = ["//visibility:public"],
#     deps = [
#         "//tensorboard/components/tf_imports:polymer",
#         "@org_polymer_iron_ajax",
#     ],
# )

tf_web_library(
    name = "google_chart_demo",
    srcs = [
        "google-chart-demo.html",
    ],
    path = "/google-chart",
    visibility = ["//visibility:public"],
    deps = [
#        ":google_chart",
        "@tb_google_chart",       # <---- new TB google-chart plugin
    ],
)
```


Since we're not yet out of the woods, maybe I do need to hide it completely.  What is the best way to disable/hide/exclude/omit the profile plugin?
3) attached polymer: When I add this
```
        attached: function() {
          console.log('tf-gpu-summary-board: inside attached function');
          var url = "https://www.gstatic.com/charts/loader.js";
          var script = document.createElement('script');
          script.src = url;
          document.head.appendChild(script);
        },
```
I see this:
```
tf-gpu-summary-board: inside attached function
Error: Google Charts loader.js can only be loaded once. loader.js:
<anonymous>
https://www.gstatic.com/charts/loader.js:
<anonymous>
https://www.gstatic.com/charts/loader.js:
gpu_summary: Parsing graph.pbtxt : 2 ms
```
Soooo....  I'm commenting this out for now.  Maybe all those cleanup updates does not need that specific load anymore....


New business
4) The UI source code definition is this (see `<google-chart></google-chart>`):
```
<dom-module id="tf-gpu-summary-board">
    <template>
        <style></style>
        <span>top of google chart</span>
        <google-chart
          type='pie'
          options='{"title": "Distribution of days in 2001Q1"}'
          cols='[{"label":"Month", "type":"string"}, {"label":"Days", "type":"number"}]'
          rows='[["Jan", 31],["Feb", 28],["Mar", 31]]'>
        </google-chart>
        <span>bottom of google chart</span>

    </template>

  <script>
      Polymer({
        is: 'tf-gpu-summary-board',

        // attached: function() {
        //   console.log('tf-gpu-summary-board: inside attached function');
        //   var url = "https://www.gstatic.com/charts/loader.js";
        //   var script = document.createElement('script');
        //   script.src = url;
        //   document.head.appendChild(script);
        // },
        
      });
  </script>
</dom-module>
```
I see this:
```
top of google chart
Loading chart...
bottom of google chart
```

So close!  Thoughts on how to see the pie chart?
I see that 'corechart' is loaded.  Does 'corechart' exclude pie chart?

**Comment by ceevee830** [comment]
William, I got it!  I found the google charts for polymer version 1.x and used that.  Now I see the pie charts in my panel.  Now I'm able to load and see the pie charts.  Next step is to convert the pie chart to a data table, and load dynamic data into it.  Closing.  THANKS for your help - I'm getting much better at configuring TB now.

**Comment by wchargin** [comment]
> William, I got it! I found the google charts for polymer version 1.x
> and used that. Now I see the pie charts in my panel. Now I'm able to
> load and see the pie charts. Next step is to convert the pie chart to
> a data table, and load dynamic data into it. Closing.

Excellent!
 
> THANKS for your help - I'm getting much better at configuring TB now.

You’re quite welcome—glad to hear it. :-)
