### ISSUE TITLE
[win7-64bit,Anaconda,tensorflow 1.2.0,chrome]Tensorboard : No scalar data was found

### ISSUE THREAD

**Issue by cnzjhdx** [tensorflow/tensorboard#177]
I can't see any data. It turned out to be : No scalar

was found

when I run the tensorboard ,there is no error or warning

Environment info

Windows 7 64-bit
Anaconda Python 3.5
Tensoflow installed from binary pip package
tensorflow version:1.2.0
Browser: Chrome 58

About the code

I just run the example code mnist_with_summries.py

it is in D:\Anaconda\Lib\site-packages\tensorflow\examples\tutorials\mnist\mnist_with_summaries.py

What have you tried?

I can see a log file called events.out.tfevents.* in the folder I set. The file is about 16Mb big.

I call tensorboard --logdir=/tmp/tensorflow/mnist/logs/mnist_with_summaries --debug and I can verify the log dir is correct.

On the browser I can't see any data or graph is shown.

If I call tensorboard --inspect --logdir=/tmp/tensorflow/mnist/logs/mnist_with_summaries It shows how the tfevent file contains.

**Comment by dandelionmane** [comment]
Is there any feedback in either:
- the terminal output
- the browser console

**Comment by GreenWindTaker** [comment]
I have same issues, and I solve it like this:

my conda enviroment is install at C drive, and tensorboard log is in D drive.
before activate conda env or after, move drive to D

ex) conda env name : tensroflow
C:\Users\AAA> D:
D:> activate tensorflow
(tensorflow) D:>tensorboard --logdir=(uer log directory in D drive)

then, TensorBoard work. I hope you solve this trouble. with my suggestion.

**Comment by fesayumi** [comment]
worked

**Comment by nfelt** [comment]
It sounds like maybe this issue was related to #52 which was fixed recently, but at any point with no response from the OP in half a year I'm closing this as obsolete.
