### ISSUE TITLE
custom_scalars only update when refreshing browser page.

### ISSUE THREAD

**Issue by GJBoth** [tensorflow/tensorboard#1774]
- TensorBoard version:TensorBoard 1.12.0
 - OS Platform and version: OS X. 10.13.6
 - Python version: 3.6.6
 - Browser type and version: Chrome 71.0.3578.98

I've run into a peculiar problem using the custom_scalars tab: it only updates the data if I refresh the page; not automatically or when using the reload button in tensorboard. I also use some scalars, which do update automatically. I'm using custom_scalars to plot the component of a vector and I've structured my program in OOP way:
```
    def tensorboard_setup(self, path):
        self.writer = tf.summary.FileWriter(path)
        self.writer.add_graph(self.sess.graph)

        # Custom scalar layout
        coeff_list = tf.unstack(self.coeffs, axis=0)
        for index, value in enumerate(coeff_list):
            tf.summary.scalar('Coefficient_'+str(index), tf.squeeze(value))

        self.layout_summary = custom_scalar_pb(
            layout_pb2.Layout(category=[
                layout_pb2.Category(
                    title='Coefficients',
                    chart=[
                        layout_pb2.Chart(
                            title='Weights vector',
                            multiline=layout_pb2.MultilineChartContent(
                                tag=[r'Coefficient_*']))])]))
        self.writer.add_summary(self.layout_summary)

        self.merged_summary = tf.summary.merge_all()
```
I  update the scalars in my training loop by:

```
summary = self.sess.run(self.merged_summary)
self.writer.add_summary(summary, it)
```

As the custom_scalar does update using page refresh, writing the data doesn't seem the problem to me.... Any idea how to fix this?

**Comment by nfelt** [comment]
Hmm, the reload button may be broken in some way.  Thanks for the report, we'll take a look.
