### ISSUE TITLE
Hparams help links to GitHub should open in new tabs

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1837]
When TensorBoard runs inside an iframe context, links to GitHub
documentation need to open in new tabs. See:
<https://github.com/tensorflow/tensorboard/pull/1836#issuecomment-462995092>

@erzel, could you take care of this, please?

**Comment by erzel** [comment]
Sure.

**Comment by wchargin** [comment]
Fixed by #2508.
