### ISSUE TITLE
Handling multiple hdfs logdir

### ISSUE THREAD

**Issue by vincent-grosbois** [tensorflow/tensorboard#1840]
I want to launch tensorboard with several input directory. As per the doc, I'm launching a command like this (on 1.12):

> tensorboard --logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1

However it seems that tensorboard is failing to correctly parse this string as 2 different paths, and is parsing this as a full string. For instance with the --inspect command I get:

>tensorboard --inspect --logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1
>No event files found within logdir a:hdfs://root/user/path2,b:hdfs://root/user/path1

It seems that the logic for splitting the logdir into several folders is not working.... Am I doing something wrong or is there a bug ?
All I could find in the source code is the method _parse_event_files_spec_ but I can't find out that it is actually, also I feel like this method indeed will not be able to split between group name when they have a specification ("hdfs://")

Can anybody confirm that my use case should be working/ not working?

**Comment by wchargin** [comment]
Hi @vincent-grosbois! Thanks for the report. Yes, you found the right
method (`parse_event_files_spec`).

Are you perchance using Windows? On Windows, `a:hdfs://foo/bar` is
interpreted as a path referencing file `hdfs://foo/bar` on drive `A:`
(much like `C:\foo\bar`), which takes precedence over a named URL
reference. It should suffice to change the run names to anything other
than single letters should work, so that there’s no ambiguity as to
whether they represent run names or drive names.

**Comment by vincent-grosbois** [comment]
Hi!
thanks for the quick reply! Unfortunately I am on linux...
I am unable to check the source code right now, but I feel like parse_event_files_spec is *not* called from regular tensorboard main() or inspect() method.
Also by reading the code, it seemes that after the split by comma, there were only 2 cases:
either there is a protocol (such as hdfs) and no name
or there is no protocol and a name for the dir
In my example both folders have a protocol and a name, so I'm not 100% sure that this case is covered by the code

**Comment by wchargin** [comment]
> I feel like parse_event_files_spec is _not_ called from regular
> tensorboard main() or inspect() method.

`parse_event_files_spec` is definitely called from `main`, though it is
not called by the `--inspect` code path. (That’s probably a bug; I’ll
open an issue for it.)

I’m not able to reproduce your problem on Linux. Please fill out the
information in the issue template to help us diagnose the problem.

Are you able to successfully read event files if you only use one logdir
specification rather than two? What about if the specifications are not
explicitly named?

> Also by reading the code, it seemes that after the split by comma,
> there were only 2 cases: either there is a protocol (such as hdfs) and
> no name or there is no protocol and a name for the dir In my example
> both folders have a protocol and a name

In your example, the initial specifications do _not_ have protocols,
because they do not match the URI pattern (`a:hdfs://foo/bar` does not
match `[a-zA-Z][0-9a-zA-Z.]*://`, because of the second colon). They
_do_ have names, which are stripped.

<https://github.com/tensorflow/tensorboard/blob/57ff0f64dfe613ea4f2608ce52581c2b5e5fdbcd/tensorboard/backend/application.py#L341-L357>

> so I'm not 100% sure that this case is covered by the code

It is covered by both the code (as explained above) and the tests (see
test case `testRunNameWithGCSPath` in `application_test.py`).

**Comment by vincent-grosbois** [comment]
Hi @wchargin thanks again for the answer
unfortunately I'm not at work now so I don't have HDFS access and I can't really answer your question (I will try tomorrow).

However I still believe there is an issue in the snippet you posted.
Here's a minimal example using this code:
i```
mport re
import os

def split_logdir(logdir):
  files = {}
  uri_pattern = re.compile('[a-zA-Z][0-9a-zA-Z.]*://.*')
  for specification in logdir.split(','):
    # Check if the spec contains group. A spec start with xyz:// is regarded as
    # URI path spec instead of group spec. If the spec looks like /foo:bar/baz,
    # then we assume it's a path with a colon. If the spec looks like
    # [a-zA-z]:\foo then we assume its a Windows path and not a single letter
    # group
    if (uri_pattern.match(specification) is None and ':' in specification and
        specification[0] != '/' and not os.path.splitdrive(specification)[0]):
      # We split at most once so run_name:/path:with/a/colon will work.
      run_name, _, path = specification.partition(':')
    else:
      run_name = None
      path = specification
    if uri_pattern.match(path) is None:
      path = os.path.realpath(os.path.expanduser(path))
    files[path] = run_name
  return files


print(split_logdir("hdfs://root/user/path2,hdfs://root/user/path1"))
# > {'hdfs://root/user/path2': None, 'hdfs://root/user/path1': None} --> OK

print(split_logdir("a:hdfs://root/user/path2,b:hdfs://root/user/path1"))
# > {'A:\\hdfs:\\root\\user\\path2': None, 'B:\\hdfs:\\root\\user\\path1': None} --> not OK
# expected (?) : {'hdfs://root/user/path2': 'a', 'hdfs://root/user/path1': 'b'}
```

First example (without naming the dirs) seems to work fine AFAIK.
Second example is failing to strip the name of the dirs from the paths, and produces incorrect paths AFAIK.

Also note that, since I'm now on windows, I also get inconsistent separators for folders. I believe they should be converted to '\' in both examples. But I don't really care about this as I'm working on linux usually and I assume that windows will still be able to understand paths with '/' in them.

**Comment by vincent-grosbois** [comment]
Apologies, I think I just understood the "windows drive" prefix thing now.
Indeed if my logdir string is "aa:hdfs://root/user/path2,bb:hdfs://root/user/path1" it will correctly parse it on windows as 2 paths with 2 names.
So my message above is moot (regardless of the backslash issue).
I will try to post more detail from a linux machine tomorrow

**Comment by wchargin** [comment]
I cannot reproduce this on Linux:

```
$ cat test.py
import re
import os


def split_logdir(logdir):
  files = {}
  uri_pattern = re.compile('[a-zA-Z][0-9a-zA-Z.]*://.*')
  for specification in logdir.split(','):
    # Check if the spec contains group. A spec start with xyz:// is regarded as
    # URI path spec instead of group spec. If the spec looks like /foo:bar/baz,
    # then we assume it's a path with a colon. If the spec looks like
    # [a-zA-z]:\foo then we assume its a Windows path and not a single letter
    # group
    if (uri_pattern.match(specification) is None and ':' in specification and
        specification[0] != '/' and not os.path.splitdrive(specification)[0]):
      # We split at most once so run_name:/path:with/a/colon will work.
      run_name, _, path = specification.partition(':')
    else:
      run_name = None
      path = specification
    if uri_pattern.match(path) is None:
      path = os.path.realpath(os.path.expanduser(path))
    files[path] = run_name
  return files


print(split_logdir("hdfs://root/user/path2,hdfs://root/user/path1"))
print(split_logdir("a:hdfs://root/user/path2,b:hdfs://root/user/path1"))

$ python test.py
{'hdfs://root/user/path2': None, 'hdfs://root/user/path1': None}
{'hdfs://root/user/path2': 'a', 'hdfs://root/user/path1': 'b'}
```

However, on Windows, I get almost exactly the output that you list (up
to capitalization):

```
$ awk '1; /import os/ { print "import ntpath"; print "os.path = ntpath"; }' test.py >test_nt.py

$ python test_nt.py
{'hdfs://root/user/path2': None, 'hdfs://root/user/path1': None}
{'a:hdfs:\\root\\user\\path2': None, 'b:hdfs:\\root\\user\\path1': None}
```

> since I'm now on windows

Please see my original comment. This is expected.

**Comment by vincent-grosbois** [comment]
Indeed ! I figured it out in my message above but too late :) 
I will retry tomorrow on a linux machine with HDFS

**Comment by vincent-grosbois** [comment]
Hi again!
now I realize that on linux, the tensorboard command with logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1 *is* actually working... it just takes a while to load in the UI and before it has loaded, it is displaying that no data can be found at path "a:hdfs://root/user/path2,b:hdfs://root/user/path1" which seemed weird...

So I think this ticket can be closed :)
However I still believe there is an issue with the inspect command as it will not properly inspect both directory but is trying to parse the logdir as a single directory, which doesn't help for debugging

**Comment by wchargin** [comment]
> now I realize that on linux, the tensorboard command with
> logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1 _is_ actually
> working

Okay, great. Glad that you’ve figured it out.

> However I still believe there is an issue with the inspect command as
> it will not properly inspect both directory but is trying to parse the
> logdir as a single directory, which doesn't help for debugging

Yes; see <https://github.com/tensorflow/tensorboard/issues/1844>.

**Comment by zuston** [comment]
> I want to launch tensorboard with several input directory. As per the doc, I'm launching a command like this (on 1.12):
> 
> > tensorboard --logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1
> 
> However it seems that tensorboard is failing to correctly parse this string as 2 different paths, and is parsing this as a full string. For instance with the --inspect command I get:
> 
> > tensorboard --inspect --logdir=a:hdfs://root/user/path2,b:hdfs://root/user/path1
> > No event files found within logdir a:hdfs://root/user/path2,b:hdfs://root/user/path1
> 
> It seems that the logic for splitting the logdir into several folders is not working.... Am I doing something wrong or is there a bug ?
> All I could find in the source code is the method _parse_event_files_spec_ but I can't find out that it is actually, also I feel like this method indeed will not be able to split between group name when they have a specification ("hdfs://")
> 
> Can anybody confirm that my use case should be working/ not working?

Hey, I find that tensorboard can't load the file from hdfs, there is no error output. But when i get hdfs files into local file, it works. So the data is valid. Do you have some ideas on it?
My running command is : tensorboard --logdir hdfs://namenode/xxxx/
Looking forward to your reply!
