### ISSUE TITLE
TensorBoard won’t start with tf-nightly-2.0-preview as of 2019-02-12

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1841]
Repro steps and traceback:

    $ cd "$(mktemp -d)"
    $ virtualenv -q ./ve/ && . ./ve/bin/activate
    (ve) $ pip install -q tf-nightly-2.0-preview
    (ve) $ tensorboard --logdir ./logs
    Traceback (most recent call last):
      File "/tmp/tmp.HYWA9X7Xun/ve/bin/tensorboard", line 6, in <module>
        from tensorboard.main import run_main
      File "/tmp/tmp.HYWA9X7Xun/ve/local/lib/python2.7/site-packages/tensorboard/main.py", line 49, in <module>
        from tensorboard import default
      File "/tmp/tmp.HYWA9X7Xun/ve/local/lib/python2.7/site-packages/tensorboard/default.py", line 36, in <module>
        from tensorboard.plugins.beholder import beholder_plugin
      File "/tmp/tmp.HYWA9X7Xun/ve/local/lib/python2.7/site-packages/tensorboard/plugins/beholder/__init__.py", line 15, in <module>
        from tensorboard.plugins.beholder.beholder import Beholder
      File "/tmp/tmp.HYWA9X7Xun/ve/local/lib/python2.7/site-packages/tensorboard/plugins/beholder/beholder.py", line 199, in <module>
        class BeholderHook(tf.estimator.SessionRunHook):
    AttributeError: 'module' object has no attribute 'estimator'

Same behavior in Python 2 and Python 3.

The `estimator` attribute on `tensorflow` was removed in:

    tf-nightly-2.0-preview==2.0.0.dev20190212

(Ideally, failure of a single plugin to load shouldn’t crash all of
TensorBoard…)

**Comment by nfelt** [comment]
This is a known transient failure in the tf nightly 2.0 preview build that's being fixed.

BeholderHook is only used on the writing side so it shouldn't really be in the loading path for TensorBoard at all.  We might be able to break that dependency with some tweaks.

**Comment by nfelt** [comment]
I guess this is because the `plugins/beholder/__init__.py` explicitly re-exports `Beholder` and `BeholderHook` from `plugins/beholder/beholder.py`.  We could move them into a new submodule like `api.py` and then get people to use them from there, which is more like the other plugins which have dedicated summary submodules.  This would technically be a breaking change, but it doesn't seem like a big deal.

**Comment by wchargin** [comment]
Fixed in `tensorflow-estimator-2.0-preview==1.14.0.dev2019021314`. The
repro steps listed above now successfully launch TensorBoard.
