### ISSUE TITLE
Move Jupyter/Colab extension to base `tensorboard`

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1857]
Jupyter users currently have to use `%load_ext tensorboard.notebook` to
load the TensorBoard extensions. The `.notebook` feels redundant; of
course we’re in a notebook. It could just be `%load_ext tensorboard`.

The root `tensorboard/__init__.py` could implement the requisite entry
point to lazily load the actual notebook implementation:

```python
def load_ipython_extension(ipython):
  from tensorboard import notebook  # pylint: disable=g-import-not-at-top
  return notebook.load_ipython_extension(ipython)
```

**Comment by manivaradarajan** [comment]
Isn't this trivial? Why would you not do it?

**Comment by wchargin** [comment]
Yes, it’s pretty much trivial. I opened an issue to see if anyone had
objections. It appears that there are none, so I’ll go ahead and do it.

**Comment by wchargin** [comment]
Unfortunately, I think that this is blocked on #1989.
