### ISSUE TITLE
jQuery / Bootstrap / Datatables

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#1864]
- TensorBoard version v1.14.0
 - OS Platform and version (Ubuntu 16.04)

The leading UI framework on the market today (to my liking) is the triumvirate of jQuery / Bootstrap / DataTables.  These provide programmers a rapid path to full-featured lightweight user interface solutions.  Here is a quick zero-configuration example of what I'm looking for: https://datatables.net/examples/basic_init/zero_configuration.html

In absence of integration of these into TensorBoard, I've successfully added Google Charts v1.0 in TensorBoard v1.14.  See issue 1754.  However, there are many **many** deficiencies with Google Charts v1.x that has reignited my desire to get the triumvirate into TensorBoard.  Other polymer-compatible datatable solutions that I have tried are incomplete or incompatible with TensorBoard.

Here's what I've done to try and get jQuery/Bootstrap/Datatables into TB:
* Included the CSS and JS payload for these three into my plugin's HTML file.
* Added these into my plugin's Bazel BUILD file.
* Bazel compiles fine
* But at runtime, I see `ReferenceError: jQuery is not defined`

In my travels, I have not seen any mention of these plugins used in any Polymer.  In fact, I think people have made WebUI libraries that are compatible with Polymer yet their functionalities are stark subsets of the ones I'm looking for.

Question: In your experience, has anyone successfully integrated these (or **any**) jQuery plugins into TensorBoard?

If no potential solution exists:
* A list and description of the existing and available UI elements in polymer.bzl would be helpful (ie, could there be something similar already inside TensorBoard?)
* A recommendation to a similar polymer-compatible datatable (searchable, sortable, pagination)

**Comment by ceevee830** [comment]
BTW, I'm Chris from nVidia who attends the SIG TensorBoard meetings.

**Comment by wchargin** [comment]
Hi Chris! Sorry about the delay—we’ve been heavily focused on the
upcoming TensorFlow Dev Summit and are a bit starved for bandwidth.

> In my travels, I have not seen any mention of these plugins used in
> any Polymer. In fact, I think people have made WebUI libraries that
> are compatible with Polymer yet their functionalities are stark
> subsets of the ones I'm looking for.
> 
> Question: In your experience, has anyone successfully integrated these
> (or **any**) jQuery plugins into TensorBoard?

I _think_ that it should be possible, though there might be some
problems with Bootstrap’s CSS interfering with Polymer’s “shadow DOM”.
No, I don’t know of any efforts to do this (successful or unsuccessful).

The scripting error that you mention is surprising to me. How are you
including the CSS and JS payloads? (As `<script>contents</script>`? As
`<script src>` pointing to a CDN? As `<script src>` pointing to local
JavaScript files built with Bazel?) Failing all else, the existing
Google Charts loader dynamically adds a `script` tag to the document;
you could perhaps do that and then wait for its `onload`.

**Comment by ceevee830** [comment]
OK - thanks...   I'll try those out.  The smallest building block needed is to allow for jQuery inside Polymer/TensorBoard so I'll try that first.  If successful, then I'll try bootstrap/datatables .  

Do you happen to have a 'hello world' for jQuery inside current version of TensorBoard?

**Comment by wchargin** [comment]
> Do you happen to have a 'hello world' for jQuery inside current
> version of TensorBoard?

Nope, I do not.

**Comment by ceevee830** [comment]
OK

**Comment by ceevee830** [comment]
Closing....
