### ISSUE TITLE
Tensorboard debugger not working 

### ISSUE THREAD

**Issue by yjjung123** [tensorflow/tensorboard#1868]
I followed the video (https://www.youtube.com/watch?v=XcHWLsVmHvk) to debug my model. 
when I executed tensorboard and it said below (looks like no issue)
"~/anaconda3/envs/tf_cpu_1902/bin/tensorboard --logdir=log_1k --host=localhost --port=8080 --debugger_port=7000
I0220 20:02:47.860546 139665244317504 debugger_plugin_loader.py:114] Starting Interactive Debugger Plugin at gRPC port -1
Creating InteractiveDebuggerPlugin at port 7000
TensorBoard 1.12.2 at http://localhost:8080 (Press CTRL+C to quit)"

but after checking "http://localhost:8080" and found the page shows a popup saying "Debugger is waiting for Session.run() connections ...." when I run the model. error occurred. 

78 ops no flops stats due to incomplete shapes.
E0220 20:03:44.434587047    6193 http_proxy.cc:62]           **'**https' scheme not supported in proxy URI****
Traceback (most recent call last):
  File "1dcnn_2dinput.py", line 356, in <module>
    _, step_loss, m = sess.run([train, loss, merge], feed_dict={X: trainX[mini_batch], Y: trainY[mini_batch], keep_prob: 0.9})
TypeError: 'FailedPreconditionError' object is not iterable

I know that Tensorboard debugger connection is local connection but is it related with firewall of our company? What can I do to fix this problem? 

 - TensorBoard version (from pip package, also printed out when running `tensorboard`)
   : 1.12.2
 - TensorFlow version if different from TensorBoard
   : 1.12.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04)
   : Ubuntu 14.04 
 - Python version (e.g. 2.7, 3.5) : 3.6 on Anaconda
 - For browser-related issues: 
   - Browser type and version (e.g. Chrome 64.0.3282.140)
   - Screenshot if it's a visual issue
 
Thanks.

**Comment by caisq** [comment]
@yjjung123 Can you show the code you use to wrap tf.Session?

**Comment by yjjung123** [comment]
Thanks for response. wrapper code added like below. 

with tf.Session() as sess:

    writer = tf.summary.FileWriter('./log_1k/', sess.graph)
    init = tf.global_variables_initializer()
    sess.run(init)

    **sess = tf_debug.TensorBoardDebugWrapperSession(sess, "localhost:7000")**
        -> if remove this, no issue. 
    
    .....

    # Training step

    mini_batch = random.sample(range(train_data_size), train_batch_size)
    _, step_loss, m = sess.run([train, loss, merge], feed_dict={X: trainX[mini_batch], Y: trainY[mini_batch], keep_prob: 0.9})    <--- error occurred at this line

**Comment by caisq** [comment]
@yjjung123 Your wrapping code looks correct. 

I can't reproduce your error on my end. The error message "'**https' scheme not supported in proxy URI**" looks weird. The debugging channel uses grpc, not https. I wonder if you have any special proxy settings enabled on your machine?

**Comment by yjjung123** [comment]
Thanks for your support, I found some proxy setting is invalid. 

no_proxy=xxx.xxx.xxx.xxx, localhost (had space, so localhost was not excluded for proxy) 
removed space and now it works, thanks.

**Comment by caisq** [comment]
@yjjung123 Glad you solve the problem.
