### ISSUE TITLE
1.13.1 cherry-pick tracking

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#1906]
Below PRs should be CPed into 1.13.1 release.

- https://github.com/tensorflow/tensorboard/pull/1898
- https://github.com/tensorflow/tensorboard/pull/1900
- https://github.com/tensorflow/tensorboard/pull/1914
- https://github.com/tensorflow/tensorboard/pull/1922
- https://github.com/tensorflow/tensorboard/pull/1945

**Comment by nfelt** [comment]
Obsolete.
