### ISSUE TITLE
profile/dynamic plugins should work in Colab

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1913]
The profile dashboard currently does not work in Colab, because the
trace viewer is embedded via an iframe, which cannot traverse Colab’s
service worker tunnel for security reasons (service workers never proxy
iframe content).

Ideally, the profile dashboard should work in Colab, which we could by
including the trace viewer directly rather than using an iframe.\* At
minimum, we should display a helpful error instead of just failing to
load the content.

\* @stephanwlee says that this is not trivial, because even though the
trace viewer uses web components as well, it’s built via a different
mechanism that’s specific to Chrome, and so we’d need some translation
layer for the dependency structure (possibly manual).

Edit: 2019-06-27
Dynamic plugins also employ iframe to render the plugin content which
is not compatible with Colab. We have plans to use new Colab's API,
`proxyPort`, to mitigate the issue but it is not ready for consumption yet.

**Comment by wchargin** [comment]
Now that #1914 has merged, I’m demoting this to a feature request.

**Comment by stephanwlee** [comment]
Retroactively cleaning issues. 

#2798 should fix the issue and the fix should be available in tb-nightly (not 2.0.1).
