### ISSUE TITLE
Tensorboard server freezing

### ISSUE THREAD

**Issue by evictor** [tensorflow/tensorboard#1915]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.4 LTS (Xenial Xerus) Linux a1006d7babbc 4.15.0-1037-azure #39-Ubuntu SMP Tue Jan 15 10:24:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- TensorFlow installed from (source or binary): Docker base image tensorflow/tensorflow:1.9.0-py3
- TensorFlow version (use command below): 1.9.0
- Python version: 3.5.2
- CUDA/cuDNN version: N/A
- GPU model and memory: none

**Describe the current behavior**

After several hours of running Tensorboard server will stop responding to requests. It is running in a Docker container and has been put on its own VM after narrowing the problem down to Tensorboard. It will eventually cause a seizure of the VM itself, which will then have to be restarted.

**WORTH NOTING:** The Tensorboard logs are stored in Azure File Storage and mounted via CIFS. Then that mounted dir is mounted in Tensorboard Docker container using Docker volume mount. The Tensorboard log dir has ~460 subdirs and a total of ~45,000 event files amounting to about 100 MB. There is also a subdir of archived logs (i.e. in several dozen *.tgz files) amounting to 2 GB, but Tensorboard should in theory not be reading or messing with those huge files (right?).

**Describe the expected behavior**

Tensorboard should be able to run ad infinitum without seizing up its host.

**Other info / logs**

I know this is a nebulous ticket with many variables. Please let me know what information I can possibly provide, especially if you can direct me to install special debug versions, etc. as needed so I can collect logs from Tensorboard itself.

**Comment by nfelt** [comment]
May be related to #766.

**Comment by jhagege** [comment]
> Thanks, I am now running with `--verbosity 1`. I found several of these in system serial log:
> 
> ```
> [246558.494090] Out of memory: Kill process 5165 (tensorboard) score 918 or sacrifice child
> [246558.538030] Killed process 5165 (tensorboard) total-vm:9122176kB, anon-rss:7482400kB, file-rss:0kB, shmem-rss:0kB
> ```
> 
> I would like to reiterate that I have TB log dir set to an SMB (CIFS) mounted disk. I wonder if that has anything to do with a potential leak? Pure conjecture but maybe TB is attempting to read, acquire file lock, etc. and failing exceptionally if the CIFS mount is sporadically unreadable or lagging?
> 
> I also noticed that it sometimes has persistent locks on files/folders as I am unable to "archive" them (I zip them and store them elsewhere, then try to remove the folder with TB logs from mounted disk but it reveals a lock).

@evictor did you find a solution to this issue ? 
We encountered a "Bad file descriptor" when SummaryWriter is writing directly on a NAS (NFS) mounted folder, which seem to happen only when we are working on 4xGPU or 8xGPU machine.

**Comment by evictor** [comment]
Running Tensorboard from latest release of Tensorflow seemed to help! In fact I will close this now as I am no longer having that issue...
