### ISSUE TITLE
Invalid format string in tensorboard 1.13.0

### ISSUE THREAD

**Issue by BelieveOP5** [tensorflow/tensorboard#1917]
![image](https://user-images.githubusercontent.com/16416594/53538502-e0fef480-3b48-11e9-8436-9622fc6bfe80.png)

- TensorBoard version 1.13.0
 - TensorFlow version 1.13.1
 - OS Platform and version Windows 10 v1809
 - Python version 3.6.6

**Comment by nfelt** [comment]
Duplicate of #1895

**Comment by nfelt** [comment]
Please see #1895; this will be fixed in the next release.

**Comment by BelieveOP5** [comment]
> 
> 
> Please see #1895; this will be fixed in the next release.

thanks, i find it.
