### ISSUE TITLE
Feature request: Stateful version of contrib.summary.always_record_summaries

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorboard#1923]
Originally posted at https://github.com/tensorflow/tensorflow/issues/25981. 

**System information**

* TensorFlow version: 1.13.0-dev20190219'
* Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When using summaries in the V2 system, summaries are meant to be written in a context manager created by `summary.always_record_summaries()` or `record_summaries_every_n_global_steps`:

```python
from tensorflow.contrib import summary
...
with summary.always_record_summaries():
    summary.scalar(...)
```

I think it would be useful to have a non-context version of these functions as well. Something like

```python
summary.do_always_record_summaries(True)
summary.scalar(...)  # This will write to the event file
```

This is analogous to how summary writers have both a `as_default()` method for creating a context manager and a `set_as_default` for changing global state.

**Will this change the current api? How?**

The`contrib.summary` module (which I believe is slated to become the main `summary` module in 2.0) will have new methods added.

**Who will benefit with this feature?**

People who are interactively using TensorFlow (especially in eager mode) from a REPL or notebook for small-scale experiments or learning TensorFlow. It's (IMO) useful to write summaries in a quick one-off fashion for immediate visualization in tensorboard. It's tedious on the REPL to make sure all those calls are wrapped in a wordy and easy-to-forget `with summary.always_record_summaries(): ...`

**Comment by nfelt** [comment]
FYI, in TF 2.0 summary writing will be on by default, so there won't be any need to wrap code in a REPL in the `with summary.always_record_summaries()` context manager just to have the default behavior be to write summaries.

Also in TF 2.0 this is more concise; it's just `with summary.record_if(True)` (or False to turn it off, since it's on by default).

Given that, do you still see the need for an equivalent to `.do_always_record_summaries()`?  It's something we might consider but in general the non-context-manager versions leak global state in ways that can end up being surprising so my default instinct is that they should be used sparingly.

**Comment by malmaud** [comment]
I see, thanks. 

Ya, I guess not in that case. Maybe there's something to be said for consistency if file writers maintain a `set_as_default` method, but it certainly doesn't take on the same urgency if writing is on by default.

It does seem that on nightlies, `tensorflow.enable_v2_behavior` doesn't turn on writing by default, so maybe that could be changed at some point.

**Comment by nfelt** [comment]
Hmm, you mean the `tf-nightly` nightlies or the `tf-nightly-2.0-preview` package?

Writing is only on by default via the V2 APIs, which are in `tf.summary` in the 2.0 package and `tf.compat.v2.summary` in both packages.  I believe that should work regardless of the enable_v2_behavior() setting.

**Comment by malmaud** [comment]
Ah, you're right. I'll close this then in light of writing being on by default in 2.0. Thanks for talking it through with me!

**Comment by nfelt** [comment]
Sure, no problem!
