### ISSUE TITLE
Can we add some docs for module tf.summary?

### ISSUE THREAD

**Issue by Shashankjain12** [tensorflow/tensorboard#1950]
As i am working on tensorboard so i decided to work on writing the summary but after looking at the docs i am not able to find a proper docs for tf.summary which includes several methods for interactive visualisation of tensorflow graphs but after looking at the docs i did not find anything useful.
We can add some notebooks for the example purpose of explaining these functions and write some more examples explaining the stuff.
If you won't mind will i work on writing some notebooks as an example purpose or creation of certaion documentation explaining those stuffs?

**Comment by wchargin** [comment]
You can find the docs for `tf.summary` in TensorFlow 1.13 (latest stable
release) here:
<https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/summary>

Docs for `tf.summary` aren’t yet included in the TensorFlow 2.0 preview
documentation—this is a known issue. They will absolutely be there in
the final version.

As mentioned in #1951, we do have notebooks for examples. We’re actively
working on writing these: cf. #1870, #1876, #1926, #1927, and #1928 for
some recent additions.
