### ISSUE TITLE
Adding Notebooks simplifying implementation of tensorboard

### ISSUE THREAD

**Issue by Shashankjain12** [tensorflow/tensorboard#1951]
Reading certain tensorboard docs is cumbersome sometime as i had seen that tensorboard does not contains any jupyter notebooks explaining implementation of tensorboard can we add some notebooks simplifying the hard task for proper understanding it's implementation?
I will be happy to work with this issue can you assign me this issue considering adding of notebooks for implementation of tensorboard with short 2-3 examples?

**Comment by wchargin** [comment]
Hi @Shashankjain12! We do in fact have Jupyter notebooks as part of our
documentation. They’re currently under `./docs/r2` in this repository:
<https://github.com/tensorflow/tensorboard/tree/b0d4a2cf29adb5816739fdbfb53589e32d48ae2a/docs/r2>

For instance, here is our “Getting started” notebook:
<https://github.com/tensorflow/tensorboard/blob/b0d4a2cf29adb5816739fdbfb53589e32d48ae2a/docs/r2/get_started.ipynb>

If you click the “Run in Google Colab” link on that notebook, you can
run the notebook in your browser without needing a local Python setup at
all. Or, you can download the notebook and run it in your own Jupyter
installation.
