### ISSUE TITLE
tf-web-test reports success when there is a failure

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#1960]
Repro case:

1. Add below code to tensorboard/plugins/graph/tf_graph_common/test/parser-test.ts
```ts
  it('fails', () => {
    const pbtxt = tf.graph.test.util.stringToArrayBuffer(``);
    return tf.graph.parser.parseGraphPbTxt(pbtxt)
        .then(() => assert.fail('Should NOT resolve'));
  })
```
2. [Optional] Confirm that it fails when run with `bazel run tensorboard/plugins/graph/tf_graph_common/test:test_web_library`
3. Run `bazel test tensorboard/plugins/graph/tf_graph_common/...`
4. Expected failure but it passes.

**Comment by erzel** [comment]
So I've figured this out. This happens because the Mocha reports some tests passing in the document title before it runs all the tests and the driver test doesn't wait for Mocha to finish. I have a fix and will send a PR for this soon.

**Comment by wchargin** [comment]
Ugh…that’s frustrating. Thanks, Erez.
