### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by IamWangYunKai** [tensorflow/tensorboard#1976]
When I updated tensorboard from 1.12 to 1.13.1(because of svg export problem) and updated numpy to 1.16.2, I found my tensorboard didn's work. I reinstalled tensorflow and tensorboard but it still didn't work.
My system: Win7, python version:3.6.5(in Anaconda3).
**Error code:**
`bash
$ tensorboard --logdir=.
TensorBoard 1.13.1 at http://Myname:6006 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "f:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "f:\anaconda3\lib\site-packages\tensorboard\main.py", line 57, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "f:\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "f:\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "f:\anaconda3\lib\site-packages\tensorboard\program.py", line 228, in main
    self._register_info(server)
  File "f:\anaconda3\lib\site-packages\tensorboard\program.py", line 274, in _register_info
    manager.write_info_file(info)
  File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 269, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS
  File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 51, in <lambda>
    (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
OSError: [Errno 22] Invalid argument
`
Does anyone have same issue or any idea how to solve it?

**Comment by IamWangYunKai** [comment]
I rollbacked tensorboard to 1.12 version, and it worked again. I think this may be a bug in the latest version

**Comment by hgadig** [comment]
Can you provide a minimal example (code, data, and/or command line) to reproduce the issue. Thanks!

**Comment by wchargin** [comment]
Hi @IamWangYunKai! Thanks for the report. This is [Python bug #29097],
which was introduced in Python 3.6, and which I believe has been fixed
as of Python 3.6.7 via 6ea8a3a0ebf840ca57b6dba9cad26fbb0ddaa5d4.

Could you please upgrading to Python≥3.6.7 and TensorBoard 1.13.1, and
let us know whether this resolves the issue for you?

[Python bug #29097]: https://bugs.python.org/issue29097

**Comment by IamWangYunKai** [comment]
> Hi @IamWangYunKai! Thanks for the report. This is [Python bug #29097](https://bugs.python.org/issue29097),
> which was introduced in Python 3.6, and which I believe has been fixed
> as of Python 3.6.7 via 6ea8a3a0ebf840ca57b6dba9cad26fbb0ddaa5d4.
> 
> Could you please upgrading to Python≥3.6.7 and TensorBoard 1.13.1, and
> let us know whether this resolves the issue for you?

Yes, it works ! Thank you very much~

**Comment by wchargin** [comment]
Great; glad to hear it! Thanks for confirming.

I’ll keep this issue open until we decide whether we want to patch this
for 3.6.0–3.6.6 anyway by avoiding use of `fromtimestamp`.

**Comment by deva-gopalani** [comment]
> I rollbacked tensorboard to 1.12 version, and it worked again. I think this may be a bug in the latest version

How can I rollback to the previous version of tensorboard? Can you please tell me the command?

**Comment by wchargin** [comment]
@deva-gopalani: `pip install tensorboard==1.12.2`

**Comment by sunnydreamfly** [comment]
@wchargin  @IamWangYunKai Tks

**Comment by yinjiangjin** [comment]
> Could you please upgrading to Python≥3.6.7 and TensorBoard 1.13.1, and
let us know whether this resolves the issue for you?

I suffer from the same problem due to I installed Python 3.6.2.  How can I upgrade to the 3.6.7 version of Python? Can you please tell me the command?

**Comment by wchargin** [comment]
@yinjiangjin: You can install Python 3.6.8 (the latest version in the
3.6.x series) from the Python website:

<https://www.python.org/downloads/release/python-368/>

Select the appropriate binary for your operating system from the “Files”
section at the bottom of the page.

**Comment by yinjiangjin** [comment]
> @yinjiangjin: You can install Python 3.6.8 (the latest version in the
> 3.6.x series) from the Python website:
> 
> https://www.python.org/downloads/release/python-368/
> 
> Select the appropriate binary for your operating system from the “Files”
> section at the bottom of the page.


> @yinjiangjin: You can install Python 3.6.8 (the latest version in the
> 3.6.x series) from the Python website:
> 
> https://www.python.org/downloads/release/python-368/
> 
> Select the appropriate binary for your operating system from the “Files”
> section at the bottom of the page.

Thank you very much

**Comment by yinjiangjin** [comment]
> @yinjiangjin: You can install Python 3.6.8 (the latest version in the
> 3.6.x series) from the Python website:
> 
> https://www.python.org/downloads/release/python-368/
> 
> Select the appropriate binary for your operating system from the “Files”
> section at the bottom of the page.

Thank you very much

**Comment by yinjiangjin** [comment]
@wchargin Thank you very much.

**Comment by wchargin** [comment]
Sure thing.

**Comment by wchargin** [comment]
Given the number of people who have commented in this thread, I do think
that we should release a patch release of TensorBoard to work around the
bug in early versions of Python 3.6. Tracking this in #2017.

**Comment by luckygl** [comment]
I have a same problem . And I have Upgrade Python to Version 3.6.7,the issue still exists
Error:
D:\Users\Administrator\AppData\Local\Programs\Python\Python36>python -V
Python 3.6.7

D:\Users\Administrator\AppData\Local\Programs\Python\Python36>tensorboard --logdir='D:\Users\Administrator\PycharmProjects\DeepLearning\NNmodel\TensorflowBase\logs\'
d:\users\administrator\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.d
type(float).type`.
  from ._conv import register_converters as _register_converters
TensorBoard 1.13.1 at http://YH-201610241148:6006 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\Administrator\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\main.py", line 57, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "d:\users\administrator\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "d:\users\administrator\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\program.py", line 228, in main
    self._register_info(server)
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\program.py", line 274, in _register_info
    manager.write_info_file(info)
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\manager.py", line 269, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorboard\manager.py", line 51, in <lambda>
    (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
OSError: [Errno 22] Invalid argument

**Comment by Ownmarc** [comment]
Hello, same error with python 3.6.8 : 

D:\emoji_game>tensorboard --logdir D:/emoji_game/log
TensorBoard 1.13.1 at http://DESKTOP-D08275B:6006 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "c:\users\marcp\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\marcp\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marcp\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\main.py", line 57, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "c:\users\marcp\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "c:\users\marcp\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\program.py", line 228, in main
    self._register_info(server)
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\program.py", line 274, in _register_info
    manager.write_info_file(info)
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\manager.py", line 269, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS
  File "c:\users\marcp\anaconda3\lib\site-packages\tensorboard\manager.py", line 51, in <lambda>
    (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
OSError: [Errno 22] Invalid argument

**Comment by Ownmarc** [comment]
@luckygl make sure you re-installed tensorflow in your new python 3.6.7 env

**Comment by wchargin** [comment]
TensorBoard 1.14.0 was released with the fix, and should work even on
old (broken) versions of Python. :+1:

**Comment by saugatapaul1010** [comment]
This error occurs when tensorboard tries to write to the directory ./logs/<built-in function time> using the CVWriter object. In Windows, folder name can't contain special characters and hence you get this error. Here's a genuine fix to the problem.

1. Locate to the file "./anaconda3/lib/site-packages/tensorflow/python/keras/callbacks.py".
2. Navigate to "class TensorBoard(Callback)"
3. Modify the path to the FileWriter object. (Should be around line 200)

Change this: 

        if self.write_graph:
            self.writer = tf.summary.FileWriter(self.log_dir),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(self.log_dir)

To this:

        if self.write_graph:
            self.writer = tf.summary.FileWriter(self.log_dir.replace(" ","-").replace("<","(").replace(">",")"),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(self.log_dir.replace(" ","-").replace("<","(").replace(">",")"))

You have to append ".replace(" ","-").replace("<","(").replace(">",")")" to log_dir. This will avoid adding special characters while creating the log directory. You may or may not chose to replace the blanks.

**Comment by saugatapaul1010** [comment]
> When I updated tensorboard from 1.12 to 1.13.1(because of svg export problem) and updated numpy to 1.16.2, I found my tensorboard didn's work. I reinstalled tensorflow and tensorboard but it still didn't work.
> My system: Win7, python version:3.6.5(in Anaconda3).
> **Error code:**
> 
> ```
> $ tensorboard --logdir=.
> TensorBoard 1.13.1 at http://Myname:6006 (Press CTRL+C to quit)
> Traceback (most recent call last):
>   File "f:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "f:\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "F:\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 9, in <module>
>   File "f:\anaconda3\lib\site-packages\tensorboard\main.py", line 57, in run_main
>     app.run(tensorboard.main, flags_parser=tensorboard.configure)
>   File "f:\anaconda3\lib\site-packages\absl\app.py", line 300, in run
>     _run_main(main, args)
>   File "f:\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "f:\anaconda3\lib\site-packages\tensorboard\program.py", line 228, in main
>     self._register_info(server)
>   File "f:\anaconda3\lib\site-packages\tensorboard\program.py", line 274, in _register_info
>     manager.write_info_file(info)
>   File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 269, in write_info_file
>     payload = "%s\n" % _info_to_string(tensorboard_info)
>   File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in _info_to_string
>     for k in _TENSORBOARD_INFO_FIELDS
>   File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 129, in <dictcomp>
>     for k in _TENSORBOARD_INFO_FIELDS
>   File "f:\anaconda3\lib\site-packages\tensorboard\manager.py", line 51, in <lambda>
>     (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
> OSError: [Errno 22] Invalid argument
> ```
> 
> Does anyone have same issue or any idea how to solve it?



This error occurs when tensorboard tries to write to the directory ./logs/<built-in function time> using the CVWriter object. In Windows, folder name can't contain special characters and hence you get this error. Here's a genuine fix to the problem.

1. Locate to the file "./anaconda3/lib/site-packages/tensorflow/python/keras/callbacks.py".
2. Navigate to "class TensorBoard(Callback)"
3. Modify the path to the FileWriter object. (Should be around line 200)

Change this: 

        if self.write_graph:
            self.writer = tf.summary.FileWriter(self.log_dir),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(self.log_dir)

To this:

        if self.write_graph:
            self.writer = tf.summary.FileWriter(self.log_dir.replace(" ","-").replace("<","(").replace(">",")"),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(self.log_dir.replace(" ","-").replace("<","(").replace(">",")"))

You have to append ".replace(" ","-").replace("<","(").replace(">",")")" to log_dir. This will avoid adding special characters while creating the log directory. You may or may not chose to replace the blanks.

**Comment by wchargin** [comment]
@saugatapaul1010: Thanks for sharing, though that looks like a different
error. This thread is about pre-epoch timestamps, not special characters
in file names.

You’re correct that you can’t have `<>`s in file names on Windows and
will need to escape them.
