### ISSUE TITLE
After reloading `tensorboard` module, public APIs are broken

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#1989]
The public APIs `notebook`, `program`, and `summary` are exposed from
the `tensorboard` module as `LazyModule`s. If the `tensorboard` module
is reloaded after one of these modules has been dereferenced, then
attempting to dereference that module again will blow the stack on a
recursion error.

In a Python 2 virtualenv:

```
$ python2
Python 2.7.14+ (default, Dec  5 2017, 15:17:02) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorboard
>>> tensorboard.program.TensorBoard
<class 'tensorboard.program.TensorBoard'>
>>> import imp  # Python 2
>>> imp.reload(tensorboard)
<module 'tensorboard' from '<snip>'>
>>> tensorboard.program.TensorBoard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  <snip>
  File "<snip>/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
RuntimeError: maximum recursion depth exceeded
```

Or in a Python 3 virtualenv:

```
$ python3
Python 3.6.5 (default, Mar 31 2018, 05:34:57) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorboard
>>> tensorboard.program.TensorBoard
<class 'tensorboard.program.TensorBoard'>
>>> import importlib  # Python 3
>>> importlib.reload(tensorboard)
<module 'tensorboard' from '<snip>'>
>>> tensorboard.program.TensorBoard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  <snip>
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded
```

Note that using the IPython directive `%reload_ext EXTENSION` will
reload the module specified by `EXTENSION`, so this precludes us from
exposing `%load_ext tensorboard`. (Reloading a module directly via
`imp`/`importlib` may not be super common, but using `%reload_ext` is.)

As I understand it, the execution flow is:

  - `tensorboard` is initialized. `tensorboard.program` is a LazyModule.
  - `tensorboard.program` is forced, importing the `program` module for
    the first time, which effects the following:
      - `sys.modules["tensorboard.program"]` is initialized to an empty
        module object.
      - The `program` module is initialized.
      - The `program` attribute on the `tensorboard` module object is
        set to the `program` module object.
  - `tensorboard` is reloaded. `tensorboard.program` is reset to a lazy
    module.
  - `tensorboard.program` is forced, importing the `program` module.
    Because this module already exists in `sys.modules`, it is not
    reinitialized, _and_ the `program` attribute on the `tensorboard`
    module object is not affected. Thus, the LazyModule initializer
    resolves to the lazy module itself, hitting a recursion error.

I believe that it should suffice to change

```py
  import tensorboard.program as module  # pylint: disable=g-import-not-at-top
  return module
```

to

```py
  return importlib.import_module("tensorboard.program")
```

with the caveat that this would require changes in the Google-internal
sync process (and I’m not exactly thrilled about these changes:
rewriting `import` syntax forms is one thing, but rewriting function
calls that happen to be of the form `importlib.import_module` is in
principle neither sound nor complete…—but, if it’s the only thing that
works, then so be it).

cc resident module spelunking expert @nfelt for confirmation

**Comment by nfelt** [comment]
It probably would also suffice to do `import tensorboard.program; return tensorboard.program` if the rewriting of `importlib.import_module()` is a big concern for you.

It's not for me, since we already do lots of regex replacements aren't as robust as you're talking about, and also because I still don't see any fundamental difference between the rewriting robustness of import vs import_module.  Regexes aren't ever going to enable completely syntax-aware python code transformation; it's easy enough to construct e.g.

```python
msg = """
Unable to
import tensorboard.com
branded tshirts due to high tariffs.
"""
```

**Comment by wchargin** [comment]
Using `import a.b; return a.b` doesn’t seem to work in my testing, and
it’s not clear to me why it should; could you elaborate? It seems to me
that the desired semantics are “ensure that this module is imported,
then return its value under `sys.modules`”, which is what importlib
does (if I understand correctly), but not what any `import` form does.

> Regexes aren't ever going to enable completely syntax-aware python
> code transformation

Indeed, and I’m willing to concede this, as noted.

**Comment by nfelt** [comment]
Yeah, you're right.  I keep managing to forget that `a.b` is an actual attribute reference, despite having this hammered into me over and over by the sharp edges of python's import system :/

It would work to query sys.modules directly, but then you need to regex replace that as well as the import statement whereas import_module() is at least just one line.
