### ISSUE TITLE
Tensorflow doesn't detect beholder results from keras

### ISSUE THREAD

**Issue by yfarjoun** [tensorflow/tensorboard#1994]
Posted here as well: https://stackoverflow.com/questions/54991524

I'm having trouble getting tensorboard to "see" the beholder files when working via Keras. The files 

     config.pkl      frame.summary       section-info.pkl

appear in the log directory and the training is much slowed down (indicating that beholder is spending the end of each batch writing to disk, as requested) but when I look in the tensorboard page, I am told that "No Beholder data was found." 

I suspect that I'm doing something wrong, but I cannot find any examples of using beholder via Keras, so it's difficult to figure out what it is.

Hoping for some assistance...

Thanks

**Comment by hgadig** [comment]
@yfarjoun  Could you confirm if you are trying with Tensorboard 2.0 ?

**Comment by yfarjoun** [comment]
Ah, no I've been using an older version of tensorboard. sorry for the trouble.

**Comment by yfarjoun** [comment]
So, I'm have more time to investigate this now, and I'm confused about your comment @Harshini-Gadige. I only see versions up to 1.13.1 on conda and 1.14 in github. Can you clarify your question:

   >confirm if you are trying with Tensorboard 2.0

Regarding your other questions:
not sure how to create a minimal example, but so I'll add the relevant pieces:

``` 
# call back class:

class BeholderCB(keras.callbacks.Callback):

    def __init__(self,logdir):
        super(BeholderCB, self).__init__()
        self.beholder=Beholder(logdir=logdir)
        self.session=K.get_session()

    def on_epoch_end(self, epoch, logs=None):
        super(BeholderCB, self).on_epoch_end(epoch, logs)
        self.beholder.update(session=self.session)

# in training:
beholder = BeholderCB(logdir='./logs/')

#model is a keras model (using TF)
model.fit(.... , callbacks=[beholder])
```
- TensorBoard 1.11.0 
- Both mac OSX (on CPU) and "Amazon" linux 
- Python 2.7

**Comment by yfarjoun** [comment]
the one comment I should probably make is that my data isn't shaped like images. its shape is 
samplesx200x6 (can be thought of as single channel image, or a 6 channel "strip")

**Comment by yfarjoun** [comment]
I think that the problem is that I didn't tell Beholder which tensors to show (the `update` function didn't have either of the optional arguments) When trying to do this I found that I do not know how to get the TF tensors from the Keras framework....

Any hints in that regard would be very apprecaited.

**Comment by yfarjoun** [comment]
I upgraded tensorflow to 1.12.0 and now I see the beholder images!
