### ISSUE TITLE
platform: do a better detection of TF2

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#1996]
Even if a user is using tf-nightly-2.0-preview or 2.0 symbols are present, user may want to use the v1 behavior by explicitly calling `tf.compat.v1.disable_v2_behavior` or set `TF2_BEHAVIOR=0`. 

We should try to respect the intent.

**Comment by shashvatshahi1998** [comment]
@stephanwlee ya thats true,  on my own do that. So whats the point f this issue and how can I contribute in it?

**Comment by nfelt** [comment]
Can we just do

```python
from tensorflow.python import tf2
tf2.enabled()
```

I know it's not a public API, but this is only for tests and only for interim functionality, and that symbol is clearly the correct definition of whether TF2 is enabled.  I think between using an undocumented API or an undocumented env var, if the latter is more comprehensive, there's no reason not to use it.  (It also has the benefit that if were to be moved/removed the tests would break and alert us, vs the env var which if changed would just appear to be unset.)

**Comment by wchargin** [comment]
> It also has the benefit that if were to be moved/removed the tests
> would break and alert us, vs the env var which if changed would just
> appear to be unset.

Okay, that’s pretty convincing. I’ll update #2217 accordingly.
