### ISSUE TITLE
Tensorboard is not showing the last checkpoint's evaluation result

### ISSUE THREAD

**Issue by bibererik** [tensorflow/tensorboard#1997]
I trained some object detection models with custom data for 4K steps using TensorFlow Object Detection API, and evaluated them during the training. Evaluation is done for all checkpoints, I watched the results on the console.

However, I can't see the last two checkpoints' evaluation results on Tensorboard for some raeson. It shows the evaluation result of 3K steps, and nothing after that. I can see that evaluation is completed on the console, and also in the folder.

There are no error messages on the console when I start Tensorboard. I can see that training results are uploaded completely to Tensorboard, the only missing thing is the last evaluation results.

I tried evaluating the latest checkpoints again, but nothing changed. At the end of the evaluation I receive a message saying that metrics are recorded to summary...

The training checkpoints are saved in every 10 minutes, and evaluation takes 12 minutes. But even in this case, I expect the latest checkpoint's evaluation results to be there.

When I try to download the csv file from Tensorboard I also can't see the last two checkpoints' evaluations.

What could be the reason?

```
I0311 16:57:21.281645 MainThread program.py:165] Not bringing up TensorBoard, but inspecting event files.
I0311 16:57:21.281645 140028330256128 program.py:165] Not bringing up TensorBoard, but inspecting event files.
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
./CN_flow1_95/eval
./CN_flow1_95/train

These tags are in ./CN_flow1_95/eval:
audio -
histograms -
images
   image-0
   image-1
   image-2
   image-3
   image-4
   image-5
   image-6
   image-7
   image-8
   image-9
scalars
   Losses/Loss/BoxClassifierLoss/classification_loss
   Losses/Loss/BoxClassifierLoss/localization_loss
   Losses/Loss/RPNLoss/localization_loss
   Losses/Loss/RPNLoss/objectness_loss
   PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'cyclist'
   PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'motorcyclist'
   PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'pedestrian'
   PascalBoxes_Precision/mAP@0.5IOU
tensor -
======================================================================

Event statistics for ./CN_flow1_95/eval:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms -
images
   first_step           0
   last_step            4112
   max_step             4112
   min_step             0
   num_steps            7
   outoforder_steps     []
scalars
   first_step           0
   last_step            4112
   max_step             4112
   min_step             0
   num_steps            7
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

These tags are in ./CN_flow1_95/train:
audio -
histograms
   ModelVars/...
images -
scalars
   Losses/TotalLoss
   Losses/clone_0/Loss/BoxClassifierLoss/classification_loss
   Losses/clone_0/Loss/BoxClassifierLoss/localization_loss
   Losses/clone_0/Loss/RPNLoss/localization_loss
   Losses/clone_0/Loss/RPNLoss/objectness_loss
   Losses/clone_1/Loss/BoxClassifierLoss/classification_loss
   Losses/clone_1/Loss/BoxClassifierLoss/localization_loss
   Losses/clone_1/Loss/RPNLoss/localization_loss
   Losses/clone_1/Loss/RPNLoss/objectness_loss
   Losses/clone_2/Loss/BoxClassifierLoss/classification_loss
   Losses/clone_2/Loss/BoxClassifierLoss/localization_loss
   Losses/clone_2/Loss/RPNLoss/localization_loss
   Losses/clone_2/Loss/RPNLoss/objectness_loss
   batch/fraction_of_150_full
   clone_0/Losses/clone_0//clone_loss
   global_step/sec
   queue/prefetch_queue/fraction_of_5_full
tensor -
======================================================================

Event statistics for ./CN_flow1_95/train:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           0
   last_step            4110
   max_step             4110
   min_step             0
   num_steps            28
   outoforder_steps     []
images -
scalars
   first_step           0
   last_step            4110
   max_step             4110
   min_step             0
   num_steps            54
   outoforder_steps     []
sessionlog:checkpoint
   first_step           1
   last_step            4111
   max_step             4111
   min_step             1
   num_steps            7
   outoforder_steps     []
sessionlog:start
   outoforder_steps     []
   steps                [0, 4110]
sessionlog:stop
   outoforder_steps     []
   steps                [0, 0]
tensor -
======================================================================
```

**Comment by wchargin** [comment]
Hi @bibererik! Thanks for the report.

From the output of `tensorboard --inspect` that you posted, it looks
like TensorBoard is able to read 4111 steps of scalar summaries, so
correspondingly there should be 4111 steps’ worth of data in the
TensorBoard UI. Once the last data is emitted, it may take TensorBoard
up to 40 seconds to show the changes in the UI (10 seconds for the
backend to pick up the changes, plus 30 seconds for the frontend to
autoreload). Are you sure that you’ve waited long enough and that
TensorBoard isn’t still loading the data?

If there still seems to be a problem, could you please attach a
complete, self-contained Python script that we can use to reproduce the
problem and/or the problematic log files? Please also specify the
versions of TensorBoard and TensorFlow that you’re using, as requested
in the issue template.

**Comment by bibererik** [comment]
I am using Tensorflow 1.10.0. I am sure that I waited enough. I also did these:

re-evaluate the last checkpoints 
re-evaluate only one checkpoint
restore the parameters and train extra for 2 steps, and re-evaluate the latest checkpoint
run tensorboard on another computer

The only complete evaluation summary is the classification loss, other 3 losses are also not complete, as well as the mAP curves

I can see that the event file is modified at 11.10 am, but on tensorboard I can see the time until 11.00 am

This is the case for all other models, not only for one independent from the  num_steps

I tried changing the frequency of storing checkpoints to 13 minutes as evaluation takes 12 minutes. It seems like working for now. 

But for me, it doesn't make much sense as the lat check points are evaluated and not overlooked by the evalution process.

**Comment by wchargin** [comment]
Summary data is read from event files, not checkpoints.

Please provide a repro script of sample data, and please provide us with
the remaining information in the issue template (Tensor*Board* version,
OS version, Python version, browser version). There’s nothing that we
can do for you otherwise.

**Comment by bibererik** [comment]
I know summary data is read from the event files. Aren't the event files created based on checkpoints? What I mean is that if all the checkpoints are processed by the evaluation, then they must be in the event files, so that Tensorboard can read it

Unfortunately I can't share sample data, I am not allowed to. The only scripts that I am using for this process is that https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/eval.py and https://github.com/tensorflow/models/blob/master/research/object_detection/legacy/train.py.

TensorBoard: 1.10.0
OS: ubuntu 16.04 LTS
Python: 3.5
Browser: Mozilla 65.0.1

**Comment by hgadig** [comment]
For further assistance, please post in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorboard).

**Comment by adragoset** [comment]
So this is a bug in tensorboard after a certain number of event files are created it just stops looking at them and displaying the results.

**Comment by jasonheidermeiers** [comment]
@Harshini-Gadige at this point I should be use to TensorFloor people being useless incompetents, but in fact they never stop surprising me instead! 

Closing an issue after telling people to go search for help on StackOverflow? For real? 

Lol! You really nailed it, good job! XD

**Comment by Annieliaquat** [comment]
> I trained some object detection models with custom data for 4K steps using TensorFlow Object Detection API, and evaluated them during the training. Evaluation is done for all checkpoints, I watched the results on the console.
> 
> However, I can't see the last two checkpoints' evaluation results on Tensorboard for some raeson. It shows the evaluation result of 3K steps, and nothing after that. I can see that evaluation is completed on the console, and also in the folder.
> 
> There are no error messages on the console when I start Tensorboard. I can see that training results are uploaded completely to Tensorboard, the only missing thing is the last evaluation results.
> 
> I tried evaluating the latest checkpoints again, but nothing changed. At the end of the evaluation I receive a message saying that metrics are recorded to summary...
> 
> The training checkpoints are saved in every 10 minutes, and evaluation takes 12 minutes. But even in this case, I expect the latest checkpoint's evaluation results to be there.
> 
> When I try to download the csv file from Tensorboard I also can't see the last two checkpoints' evaluations.
> 
> What could be the reason?
> 
> ```
> I0311 16:57:21.281645 MainThread program.py:165] Not bringing up TensorBoard, but inspecting event files.
> I0311 16:57:21.281645 140028330256128 program.py:165] Not bringing up TensorBoard, but inspecting event files.
> ======================================================================
> Processing event files... (this can take a few minutes)
> ======================================================================
> 
> Found event files in:
> ./CN_flow1_95/eval
> ./CN_flow1_95/train
> 
> These tags are in ./CN_flow1_95/eval:
> audio -
> histograms -
> images
>    image-0
>    image-1
>    image-2
>    image-3
>    image-4
>    image-5
>    image-6
>    image-7
>    image-8
>    image-9
> scalars
>    Losses/Loss/BoxClassifierLoss/classification_loss
>    Losses/Loss/BoxClassifierLoss/localization_loss
>    Losses/Loss/RPNLoss/localization_loss
>    Losses/Loss/RPNLoss/objectness_loss
>    PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'cyclist'
>    PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'motorcyclist'
>    PascalBoxes_PerformanceByCategory/AP@0.5IOU/b'pedestrian'
>    PascalBoxes_Precision/mAP@0.5IOU
> tensor -
> ======================================================================
> 
> Event statistics for ./CN_flow1_95/eval:
> audio -
> graph
>    first_step           0
>    last_step            0
>    max_step             0
>    min_step             0
>    num_steps            1
>    outoforder_steps     []
> histograms -
> images
>    first_step           0
>    last_step            4112
>    max_step             4112
>    min_step             0
>    num_steps            7
>    outoforder_steps     []
> scalars
>    first_step           0
>    last_step            4112
>    max_step             4112
>    min_step             0
>    num_steps            7
>    outoforder_steps     []
> sessionlog:checkpoint -
> sessionlog:start -
> sessionlog:stop -
> tensor -
> ======================================================================
> 
> These tags are in ./CN_flow1_95/train:
> audio -
> histograms
>    ModelVars/...
> images -
> scalars
>    Losses/TotalLoss
>    Losses/clone_0/Loss/BoxClassifierLoss/classification_loss
>    Losses/clone_0/Loss/BoxClassifierLoss/localization_loss
>    Losses/clone_0/Loss/RPNLoss/localization_loss
>    Losses/clone_0/Loss/RPNLoss/objectness_loss
>    Losses/clone_1/Loss/BoxClassifierLoss/classification_loss
>    Losses/clone_1/Loss/BoxClassifierLoss/localization_loss
>    Losses/clone_1/Loss/RPNLoss/localization_loss
>    Losses/clone_1/Loss/RPNLoss/objectness_loss
>    Losses/clone_2/Loss/BoxClassifierLoss/classification_loss
>    Losses/clone_2/Loss/BoxClassifierLoss/localization_loss
>    Losses/clone_2/Loss/RPNLoss/localization_loss
>    Losses/clone_2/Loss/RPNLoss/objectness_loss
>    batch/fraction_of_150_full
>    clone_0/Losses/clone_0//clone_loss
>    global_step/sec
>    queue/prefetch_queue/fraction_of_5_full
> tensor -
> ======================================================================
> 
> Event statistics for ./CN_flow1_95/train:
> audio -
> graph
>    first_step           0
>    last_step            0
>    max_step             0
>    min_step             0
>    num_steps            1
>    outoforder_steps     []
> histograms
>    first_step           0
>    last_step            4110
>    max_step             4110
>    min_step             0
>    num_steps            28
>    outoforder_steps     []
> images -
> scalars
>    first_step           0
>    last_step            4110
>    max_step             4110
>    min_step             0
>    num_steps            54
>    outoforder_steps     []
> sessionlog:checkpoint
>    first_step           1
>    last_step            4111
>    max_step             4111
>    min_step             1
>    num_steps            7
>    outoforder_steps     []
> sessionlog:start
>    outoforder_steps     []
>    steps                [0, 4110]
> sessionlog:stop
>    outoforder_steps     []
>    steps                [0, 0]
> tensor -
> ======================================================================
> ```

Can please help me.. My evaluation result in tensorboard is just showing one dot for mAP. it is not showing a complete graph. Can you please tell me why. 
![image](https://user-images.githubusercontent.com/43025113/204315087-ce51a242-111a-4320-96a4-119c6a26db35.png)
