### ISSUE TITLE
AttributeError: module 'tensorboard.util' has no attribute 'Retrier'

### ISSUE THREAD

**Issue by Owenscu** [tensorflow/tensorboard#2019]
- TensorBoard version 1.8.0
 - TensorFlow version 1.8.0
 - OS Platform and version (e.g., Linux Ubuntu 18.04)
 - Python version (e.g.3.6)
AttributeError: module 'tensorboard.util' has no attribute 'Retrier'

**Comment by hgadig** [comment]
This can happen when multiple versions of tensorboard are installed. Please try the following.

1) Uninstall tb-nightly(if it is installed in your virtual environment).
2) Go to site-packages and remove tensorflow/tensorboard folders. Then do pip install tensorboard

**Comment by shashvatshahi1998** [comment]
You can also go by this:

1) pip uninstall tensorflow
2) pip uninstall tensorboard
3) conda show OR pip show --> have a look at which other tensorflow related packages you have installed and remove them.
4) Go to site-packages and remove tensorflow/tensorboard folders (look for any folder in your filesystem related to a tensorflow / tensorboard installation)
5) conda clean --all (not sure if this is necessary, but it was one of my steps and might be relevant)
6) Reinstall tensorflow and tensorboard. Preferably use conda as it is faster by several orders of magnitude

You may refer #1724 , as old by @hgadig
