### ISSUE TITLE
Consider adding __version__ for consistency with TensorFlow and PEP 396

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2020]
TensorFlow has a top-level `__version__`, but TensorBoard does not:

```
>>> import tensorflow
>>> tensorflow.__version__
'2.0.0-dev20190318'
>>> import tensorboard
>>> tensorboard.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```

TensorBoard does have a `tensorboard.version` submodule, though this
needs to be explicitly imported, unlike TensorFlow’s corresponding
module (`__import__("tensorflow").version` works).

[PEP 396] permits third-party modules, like TensorBoard, to include a
`__version__` attribute. It might be nice, for consistency with other
projects in this area, to alias `__version__` to `version.VERSION`.

cc @martinwicke 

[PEP 396]: https://www.python.org/dev/peps/pep-0396/

**Comment by shashvatshahi1998** [comment]
You can try this:
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorboard import version
>>> print(version.VERSION)
1.13.1
Mostly when you download TensorFlow , TensorBoard is also automatically downloaded. So in most of the cases their version is same. But both of them are independent of each other, so it should not be possible that the two packages affect each other in any way.

**Comment by wchargin** [comment]
> ```python
> from tensorboard import version
> ```

Yes, I know—this is the `tensorboard.version` submodule that I refer to
in the issue above.

This issue is about _additionally_ supporting a top-level `__version__`
attribute in the same way that TensorFlow does, for consistency with
other packages in the TensorFlow family.

**Comment by shashvatshahi1998** [comment]
from tensorflow.python import pywrap_tensorflow
from tensorflow.python.util.tf_export import tf_export

__version__ = pywrap_tensorflow.__version__
__git_version__ = pywrap_tensorflow.__git_version__
__compiler_version__ = pywrap_tensorflow.__compiler_version__
__cxx11_abi_flag__ = pywrap_tensorflow.__cxx11_abi_flag__
__monolithic_build__ = pywrap_tensorflow.__monolithic_build__

VERSION = __version__
tf_export(
    "version.VERSION",
    "__version__",
    v1=["version.VERSION", "VERSION", "__version__"]).export_constant(
        __name__, "VERSION")

Can't we do something like this in TensorBoard's version.py
