### ISSUE TITLE
Tensorboard ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by RacingDawn** [tensorflow/tensorboard#2030]
1. Firstly i started the tensorboard on the docker, and the nodeport is 8600.
![image](https://user-images.githubusercontent.com/13477849/54667847-66623d00-4b28-11e9-8d49-e356d32ead34.png)
2. I visited the `hostname -i`:8600 by the chrome at the first time, i got the information:
![image](https://user-images.githubusercontent.com/13477849/54667171-af18f680-4b26-11e9-89a1-4d2bd909038f.png)
3. I got the figure eventually when i refreshed the webpage.
![image](https://user-images.githubusercontent.com/13477849/54667261-df609500-4b26-11e9-9fb0-baeebca6b995.png)

So why the result is ERR_CONNECTION_REFUSED when i visited at the first time.
The chrome version is  71.0.3578.98
The docker version is 
![image](https://user-images.githubusercontent.com/13477849/54667431-4d0cc100-4b27-11e9-8d46-ab3ec28f631d.png)
The tensorflow version is 1.1.0
Python is pythonenv and the version is 2.7

**Comment by hgadig** [comment]
Could you please try either of the following resolutions and please keep us posted.

1) Try changing the log directory to the base directory of your project.
2) Upgrading Tensorboard to the latest version

**Comment by shashvatshahi1998** [comment]
Best way to run TensorBoard which I use frequently is first run your model in one tab of your terminal, then open a new tab in terminal and type tensorboard --logdir=path/to/log-directory --DEBUG(this path is the same path which you have created or referenced in your model) . This debug in the end is very important, most of the time it is the root cause of all the errors raised

**Comment by RacingDawn** [comment]
> Could you please try either of the following resolutions and please keep us posted.
> 
> 1. Try changing the log directory to the base directory of your project.
> 2. Upgrading Tensorflow/Tensorboard to the latest version.

Thank you. The reason for this may be that I ran ternsorborad in docker, and the server was not ready when i visited the ip:port.
So i change the way that starting tensorboard on the machine to validate it. The err_connection_refused only appears before the server started. Otherwise, it doesn't appear no more.

**Comment by RacingDawn** [comment]
> Best way to run TensorBoard which I use frequently is first run your model in one tab of your terminal, then open a new tab in terminal and type tensorboard --logdir=path/to/log-directory --DEBUG(this path is the same path which you have created or referenced in your model) . This debug in the end is very important, most of the time it is the root cause of all the errors raised

Thank you. Indeed, the way is very useful.
