### ISSUE TITLE
Tests failing on master since tf-nightly-2.0-preview-20190319

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2035]
`__import__("tensorflow").io.TFRecordCompressionType` was removed; this breaks `//tensorboard/plugins/interactive_inference:interactive_inference_plugin_test`.

**Comment by wchargin** [comment]
This failure was not caught on our CI for a few days because the test
target was always cached until #2024 happened to change one of its
dependencies. This is systemic—perhaps we should set up our test status
caches to be keyed against the TensorFlow package versions, and add a
daily build against master at 05:00 PT to prime the caches each day so
that it’s not a pain in terms of added latency?

The [presubmit build for #2024][build] was green because it ran only
once, on 2019-03-18, using `tf-nightly-2.0-preview-2.0.0.dev20190318`,
which genuinely is still green. After merging into `master`, the
post-submit build was run on the new package, which failed.

[build]: https://travis-ci.com/tensorflow/tensorboard/jobs/185875646

**Comment by nfelt** [comment]
For the record, I agree that we should avoid caching test status across TF package versions.  Maybe worth opening a separate issue for that?
