### ISSUE TITLE
Hparams tab not showing up in Tensorboard

### ISSUE THREAD

**Issue by philippHRO** [tensorflow/tensorboard#2038]
I run the notebook `hyperparameter_tuning_with_hparams`.
Everything works fine, but when I start tensorboard, the HParams tab isn't showing up.

I tried to start tensorboard from the command line, too.
`tensorboard --logdir="C:\python_code\tensorboard_notebooks\logs\hparam_tuning"`
The tab is not showing up.

Here is what I see in jupyter notebook:
![grafik](https://user-images.githubusercontent.com/23098362/54823272-a13eaf00-4ca7-11e9-9298-0113b73d5160.png)

And here is tensorboard opened via commandline:
![grafik](https://user-images.githubusercontent.com/23098362/54823417-0eeadb00-4ca8-11e9-80a7-8ab7c7a1610b.png)

These are the relevant packages installed in the conda env I use as kernel in jupyter notebook:
```
tb-nightly                1.14.0a20190313
tensorboard               1.13.1
tensorflow-estimator-2-0-preview 1.14.0.dev2019031400
tf-nightly-2-0-preview    2.0.0.dev20190313

on Windows10 x64, conda 4.6.8, Python 3.6.8
```

**Comment by wchargin** [comment]
Hi @philippHRO! It looks like you have two concurrent versions of
TensorBoard installed. TensorBoard 1.13.1 does not include the hparams
dashboard, while TensorBoard 1.14.0a20190313 does. Could you please
uninstall both of these packages and then reinstall the same version of
`tb-nightly`? (Because of how Pip works, simply uninstalling
`tensorboard` may corrupt your installation.)

**Comment by philippHRO** [comment]
That worked, when I open TB via Console.
But now I keep getting this, when I try to open TB in notebook via %tensorboard --logdir="logs".
I opened a new issue (#2057 ). Meanwhile, I updated tf-nightly and tb to their newest versions.

**Comment by hgadig** [comment]
Thanks for opening the new issue. Closing this.

**Comment by rickwierenga** [comment]
I'm experiencing the same issue on Google Colab. Uploading scalars works, and I can see the HParams tab in the inline version, but not on tensorboard.dev.

You can view this in the official TensorBoard tutorial: https://colab.research.google.com/drive/1-WfOnkxdN36gbH5q2Lw063TeY62KChTM. This Colab is a copy in which I added this line:

```
!tensorboard dev upload --logdir logs/hparam_tuning
```
