### ISSUE TITLE
Incorrect epoch number in TensorBoard callback when using batch-level metrics

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorboard#2042]
I am re-reporting https://github.com/tensorflow/tensorflow/issues/26873 here as requested.

----------------------

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, see below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): `tensorflow==1.13.1` and `tf-nightly==1.14.1.dev20190318` (`v1.12.0-10310-g3db23915df 1.14.1-dev20190318`)
- Python version: 3.7.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
When collecting batch-level metrics, epochs are incorrectly numbered with the current `_samples_seen`

**Describe the expected behavior**
When collecting batch-level metrics, epochs should be numbered with the epoch number

**Code to reproduce the issue**
```
from tensorflow import keras


class MyTensorBoard1(keras.callbacks.TensorBoard):
    def _write_custom_summaries(self, step, logs=None):
        print(logs, "at step =", step, "with regular callback")


class MyTensorBoard2(keras.callbacks.TensorBoard):
    def _write_custom_summaries(self, step, logs=None):
        print(logs, "at step =", step, "with per-batch callback")


layer = keras.layers.Input(shape=(1,))
model = keras.models.Model(inputs=layer, outputs=layer)
model.compile(optimizer='adam', loss='mse')
Callback1 = MyTensorBoard1()
Callback2 = MyTensorBoard2(update_freq='batch')
model.fit(x=list(range(6)), y=list(range(6)), epochs=10, callbacks=[Callback1, Callback2])
```

To run this code in current nightly, remove `Callback1` and focus on output of first epoch. Notice `at step = 6` in first epoch:

```
Epoch 1/10
{'batch_loss': 0.0} at step = 0 with per-batch callback
{'epoch_loss': 0.0} at step = 6 with per-batch callback
6/6 [==============================] - 0s 15ms/sample - loss: 0.0000e+00
```

**Other info / logs**
In my opinion, the bug is here:
https://github.com/tensorflow/tensorflow/blob/6612da89516247503f03ef76e974b51a434fb52e/tensorflow/python/keras/callbacks.py#L1158

and still here:
https://github.com/tensorflow/tensorflow/blob/c66b603990b9404dc1eb57de9d595aa0ffc8197f/tensorflow/python/keras/callbacks.py#L1288

In `on_epoch_end`, `step` should always be set to `epoch`.

----------------------

To explicitly include a thought of mine:

My reporting this issue is based on the expectation that `epoch_` metrics should behave the same regardless of how often `batch_` metrics are written, such that `epoch_` metrics are always comparable across runs with different `update_freq`. 

Of course, if `batch_` and `epoch_` metrics are assumed to be interpreted in conjunction for one run, there is a need to know how to interleave the two, in which case I understand the current behavior somewhat. (But then, why does `on_batch_end` use `self._total_batches_seen`, while `on_epoch_end` uses `self._samples_seen`?) In that case, however, TensorBoard should have an option to ignore the x values from summaries - this is the issue I have referenced above this comment.

**Comment by hgadig** [comment]
Apologies for the miscommunication about this issue whether to post it in tensorflow or tensorboard repo.
I had a chat with the team and was asked to retain this issue in the tensorflow core repository as it is related to TBcallback in TensorFlow.
