### ISSUE TITLE
Q: How to generate static demo of what-if-tool?

### ISSUE THREAD

**Issue by QuadTriangle** [tensorflow/tensorboard#2049]
[sorry for asking a noob question]

Let's say I have this 
https://colab.research.google.com/github/pair-code/what-if-tool/blob/master/WIT_Age_Regression.ipynb
notebook?

Now, I want to generate a static page like
https://pair-code.github.io/what-if-tool/age.html

How can I do it?

**Comment by hgadig** [comment]
For creating a standalone what-if-tool web page(like you mentioned), you'll probably want to add a build target like this one: https://github.com/tensorflow/tensorboard/blob/cf76398963491f01ac92731a8bdafb01e3162228/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/BUILD#L109-L123

**Comment by QuadTriangle** [comment]
so, I will have to write javascript every time
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-age-demo.html#L37-L317

I thought there was a way to export output from notebook.

You can close the issue if there is no any automatic way.

**Comment by hgadig** [comment]
@jameswex  Could you please suggest if there is any alternate for the above ?

**Comment by jameswex** [comment]
I'm not aware of a way to export the results of a notebook that shows the what-if tool to a static web page where the tool would be usable as it is in the notebook.

You can think of the what-if tool itself as an html element that shows the tool, and takes as input a set of examples, and sends out events when it needs some new data (like model inference results on some of those examples), then consumes the responses from those events to update the visualization.

In notebook mode, there is python code that handles this data wrangling along with the marshalling of the data between the JS in the notebook and the python running the notebook kernel and doing the model inferences.

For a standalone web demo of the tool, you need a JS version of thise data wrangling, as can be seen in the tf-interactive-inference-age-demo.html and associated build rule (pointed out in the first response from @hgadig, which powers the web demo https://pair-code.github.io/what-if-tool/age.html). Or have your own web server on the backend that handles the model inference and data wrangling, as the TensorBoard web server does for using the What-If Tool inside of TensorBoard, as seen in files like interactive_inference_plugin.py in the code repo.

Please feel free to reach out with more questions about this process.
