### ISSUE TITLE
Eager graph fails to display (Failed Normalizing names)

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2062]
Code to reproduce:

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function


import shutil

import tensorflow as tf


if tf.version.VERSION.startswith('1.'):
  tf.compat.v1.enable_eager_execution()
  tf = tf.compat.v2


LOGDIR = './logs'


def main():
  shutil.rmtree(LOGDIR, ignore_errors=True)
  model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,)),
  ])
  model.compile(loss='mse', optimizer='adagrad')
  callback = tf.keras.callbacks.TensorBoard(LOGDIR)
  model.fit(x=[[0]], y=[[0]], callbacks=[callback])


if __name__ == '__main__':
  main()
```

Expected behavior: Running this and then `tensorboard --logdir ./logs`
provides a graph visualizer that shows the Keras implementation graph.

Actual behavior: On versions of TensorFlow from 2019-03-23 onward, the
“Default” graph in the graph visualizer gives the error, “Graph: Failed
Normalizing names”.

![Screenshot of error](https://user-images.githubusercontent.com/4317806/55033543-a74acd80-4fd0-11e9-884c-48f7362eb189.png)

The stack trace in the JS console is:

```
(index):10466 TypeError: d.list.shape.map is not a function
    at d ((index):10270)
    at new <anonymous> ((index):10276)
    at d ((index):10286)
    at (index):10285
    at arrayEach ((index):80)
    at Function.forEach ((index):242)
    at a ((index):10285)
    at arrayEach ((index):80)
    at Function.forEach ((index):242)
    at (index):10286
```

(On all versions, the `batch_1` graph gives the error, [“Error: The
graph is empty. \[…\]”][1], and the Keras conceptual graph works fine.)

The problem appears to be due to a change in the emitted graphs, not a
change in TensorBoard; the above-described behavior occurs independent
of the TensorBoard version.

[1]: https://github.com/tensorflow/tensorboard/blob/6de38d858b4ec19ed5e4088e863a8eba737292e1/tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts#L193-L197

The behavior is the same under tf-nightly and tf-nightly-2.0-preview
(but removing the `enable_eager_execution()` call causes the code to
work fine in tf-nightly).

cc @stephanwlee; not sure whether this is a TensorBoard error or a
TensorFlow problem.

**Comment by wchargin** [comment]
Previous “Normalizing names” issues: #375, #702.

**Comment by stephanwlee** [comment]
Got some time to look into this and it looks like the newer version of the TF started to populate attributes that it previously did not.

First few lines that I got
```diff
--- a/dir/Downloads/old.pbtxt
+++ b/dir/Downloads/new.pbtxt
@@ -4830,6 +4830,15 @@ library {
     node_def {
       name: "has_invalid_dims/ExpandDims/dim"
       op: "Const"
+      attr {
+        key: "_output_shapes"
+        value {
+          list {
+            shape {
+            }
+          }
+        }
+      }
       attr {
         key: "dtype"
         value {
@@ -4865,10 +4874,37 @@ library {
           type: DT_INT32
         }
       }
+      attr {
+        key: "_output_shapes"
+        value {
+          list {
+            shape {
+              dim {
+                size: 1
+              }
+              dim {
+                size: 1
+              }
+            }
+          }
+        }
+      }
     }
     node_def {
       name: "has_invalid_dims/ones_like/Shape"
       op: "Const"
+      attr {
+        key: "_output_shapes"
+        value {
+          list {
+            shape {
+              dim {
+                size: 2
```

and my initial thinking is that something is missing here: https://github.com/tensorflow/tensorboard/blob/37c5b50108be97e7bc48ef9d646cb8b52302d472/tensorboard/plugins/graph/tf_graph_common/parser.ts#L161-L175

Now the question is, were there truly no instance of FunctionLibrary with the shape attribute before? Why does it blow up now? I will try to read more about FunctionLibrary and see how this parser is supposed to behave.
