### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'estimator'

### ISSUE THREAD

**Issue by ectg** [tensorflow/tensorboard#2067]
Hi,

I get the following error when I run tensorboard:

> class BeholderHook(tf.estimator.SessionRunHook):
> AttributeError: module 'tensorflow' has no attribute 'estimator'

Here is the setup info:

> Windows 10
> Python 3.6.8
> conda 4.6.8
> tensorboard               1.13.1                 
> tensorflow-base           1.13.1        
> tensorflow-estimator      1.13.0          
> tensorflow-gpu            1.13.1

Does anyone know how to fix this? I have tried most of the solutions on stackexchange, but nothing has worked so far.

**Comment by shashvatshahi1998** [comment]
I guess reinstall everything with higher versions.

**Comment by hgadig** [comment]
Hi, please follow the following steps and retry.

1) Uninstall tensorflow, tensorboard
2) Uninstall tb-nightly(if it is installed)
3)Use pip freeze | grep tensorflow  to check if tensorflow-estimator package has been installed. If so, uninstall it.
4) Go to site-packages and remove all tensorflow folders related to tensorflow, tensorboard, tensorflow-estimator etc
5) Reinstall the latest versions of tensorflow and tensorboard

**Comment by hgadig** [comment]
Closing the issue. Please keep us posted(by providing more details) if the above solution didn't work.
Thanks!
