### ISSUE TITLE
Errors occur when the time zone is not Greenwich

### ISSUE THREAD

**Issue by zpcl412** [tensorflow/tensorboard#2069]
\tensorboard\manage.py
line 47 to 53 like
`_type_timestamp = _FieldType(
    serialized_type=int,  # seconds since epoch
    runtime_type=datetime.datetime,  # microseconds component ignored
    serialize=lambda dt: int(
        (dt - datetime.datetime.fromtimestamp(0)).total_seconds()),
    deserialize=lambda n: datetime.datetime.fromtimestamp(n),
)`
should be changed into
`_type_timestamp = _FieldType(
    serialized_type=int,  # seconds since epoch
    runtime_type=datetime.datetime,  # microseconds component ignored
    serialize=lambda dt: int(
        (dt - datetime.datetime.utcfromtimestamp(0)).total_seconds()),
    deserialize=lambda n: datetime.datetime.fromtimestamp(n),
)`

**Comment by wchargin** [comment]
I’ve replaced this code in #2054 to avoid problems like this.

**Comment by zpcl412** [comment]
Hi，@wchargin.
I got it,. I'll have a try.Thanks
