### ISSUE TITLE
Witwidget problem with GPU

### ISSUE THREAD

**Issue by PaulDaoudi** [tensorflow/tensorboard#2070]
Hi, 

I am trying to apply the What If Tool on my model on Jupyter Notebook with the library wit widget.
However, it seems that I cannot use tensorflow-gpu with wit widget: this library automatically install another tensorflow which does not recognize any gpu.

Is there a way to use the What If Tool with tensorflow-gpu?

Thank you!

**Comment by wchargin** [comment]
cc @jameswex (noting that TensorBoard itself does _not_ depend on
TensorFlow for this reason)

**Comment by jameswex** [comment]
Out of curiosity, it possible to manually uninstall tensorflow (the non-gpu version) after pip installing witwidget, to use it with tensorflow-gpu?

Perhaps we should switch the witwidget package to not have dep on TF as you did with TensorBoard William.

**Comment by PaulDaoudi** [comment]
No it is not. I cannot import wit widget with only tensorflow-gpu, because it cannot import tensorflow-serving-api.
I also tried to install tensorflow-serving-api-gpu, but it still does not work.

**Comment by jameswex** [comment]
Here are builds of witwidget 1.0 pip files (both for py2 and py3) with the pip dependencies on tensorflow and tensorflow-serving-api removed. Could you try pip installing the right one for your python version, in your environment where you have tensorflow-gpu installed? You will also need to pip install tensorflow-serving-api-gpu, as you mentioned. Let me know if this pip package allows WIT to work as expected with your tensorflow-gpu installation. Thanks!

[witwidget-no-tf-deps.zip](https://github.com/tensorflow/tensorboard/files/3022749/witwidget-no-tf-deps.zip)

**Comment by PaulDaoudi** [comment]
It works!! Thank you very much.

Paul
