### ISSUE TITLE
third_party/clutz.bzl does not pass Skylint

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#2071]
Specifically, we violate depset-plus-depset
https://github.com/bazelbuild/bazel/blob/master/site/docs/skylark/skylint.md#using-the-operator--on-depset-deprecated-plus-depset

**Comment by wchargin** [comment]
Is this resolved by #2072?

**Comment by stephanwlee** [comment]
Yes, I must have not used the magic word :\
