### ISSUE TITLE
Tensorboard callback for embedding errors in kera

### ISSUE THREAD

**Issue by sdk21** [tensorflow/tensorboard#2074]
- TensorBoard version (from pip package, also printed out when running `tensorboard`) 1.13.1
 - TensorFlow version if different from TensorBoard 1.13.1
 - OS Platform and version (e.g., Linux Ubuntu 16.04) Mac OS 10.13.6
 - Python version (e.g. 2.7, 3.5) 2.7
 - For browser-related issues:
   - Browser type and version (e.g. Chrome 64.0.3282.140) chrome
   - Screenshot if it's a visual issue
 
Please describe the bug as clearly as possible, and if possible provide a minimal example (code, data, and/or command line) to reproduce the issue.  Thanks!

I have an embedding layer that I am trying to project using tensorboard

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16, input_length=20, name="embedding"))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16, activation=tf.nn.relu))
model.add(keras.layers.Dense(1, activation=tf.nn.sigmoid))

from tensorflow.python.keras.callbacks import TensorBoard,EarlyStopping

tensorboard = TensorBoard(log_dir='./graph',
                          embeddings_freq=10,
                          embeddings_layer_names=['embedding'],
                          embeddings_data= train_data)

history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=epochs,
                    batch_size=batch_size,
                    validation_data=(x_val, y_val),
                    callbacks=[tensorboard],
                    verbose=1)

I get the following error 
NotFoundError: Resource localhost/embedding_embedding_7/N10tensorflow3VarE does not exist.
	 [[node strided_slice_7/_assign (defined at <ipython-input-38-cf87f72e98e1>:7) ]]

**Comment by rmothukuru** [comment]
Hello sdk21,
When trying to reproduce your issue, we have observed that some variables like "vocab_size, train_data, partial_x_train, etc.." are missing. If possible for you, can you please share the code snippet where these variables are defined.

**Comment by sdk21** [comment]
partial_x_train is basically a numpy array with each element list of size 20.
array([[ 128,  459, 1129, ...,    0,    0,    0],
       [ 174,    1,  155, ...,    0,    0,    0],
       [ 338,  216, 2427, ...,    0,    0,    0],
       ...,
       [ 188,  146,   15, ...,    0,    0,    0],
       [ 253,   77, 1714, ...,    0,    0,    0],
       [ 319,   56,   90, ...,    0,    0,    0]], dtype=int32)

partial_y_train same as partial x train

vocab_size is 2500 which is size of one hot encoding input in embedding layer. 
Also, the model run fine without embedding callback. 
Let me know if you need more details.

**Comment by wchargin** [comment]
Hi @sdk21—please provide a self-contained Python file that we can run to
reproduce the problem.

**Comment by hgadig** [comment]
Closing as this issue is in "awaiting response" state for more than 3 days. Feel free to add your comments and we will reopen. Thanks!

**Comment by sdk21** [comment]
from __future__ import absolute_import, division, print_function
import tensorflow as tf
from tensorflow import keras
import numpy as np

print(tf.__version__)

imdb = keras.datasets.imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)
print("Training entries: {}, labels: {}".format(len(train_data), len(train_labels)))

#print(train_data[0])

len(train_data[0]), len(train_data[1])

# A dictionary mapping words to an integer index
word_index = imdb.get_word_index()

# The first indices are reserved
word_index = {k:(v+3) for k,v in word_index.items()} 
word_index["<PAD>"] = 0
word_index["<START>"] = 1
word_index["<UNK>"] = 2  # unknown
word_index["<UNUSED>"] = 3

reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

decode_review(train_data[0])

train_data = keras.preprocessing.sequence.pad_sequences(train_data,
                                                        value=word_index["<PAD>"],
                                                        padding='post',
                                                        maxlen=256)

test_data = keras.preprocessing.sequence.pad_sequences(test_data,
                                                       value=word_index["<PAD>"],
                                                       padding='post',
                                                       maxlen=256)

len(train_data[0]), len(train_data[1])

#print(train_data[0])

# input shape is the vocabulary count used for the movie reviews (10,000 words)
vocab_size = 10000

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16, activation=tf.nn.relu))
model.add(keras.layers.Dense(1, activation=tf.nn.sigmoid))

model.summary()

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['acc'])

x_val = train_data[:10000]
partial_x_train = train_data[10000:]

y_val = train_labels[:10000]
partial_y_train = train_labels[10000:]

## Tensorboard 
from tensorflow.python.keras.callbacks import TensorBoard

'''
class TensorboardWithSess(TensorBoard):
	"""docstring for TensorboardWithSess"""
	def __init__(self, **kwargs):
		from tensorflow.python.keras import backend as K
		self.sess = K.get_session()
		super(TensorboardWithSess, self).__init__()

tensorboard = TensorboardWithSess(log_dir='./graph',embeddings_freq=10,
									embeddings_layer_names=['embedding'],
									embeddings_data=partial_x_train)
'''

tensorboard = TensorBoard(log_dir='./graph',embeddings_freq=10,
									embeddings_layer_names=['embedding'],
									embeddings_data=partial_x_train)
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=40,
                    batch_size=512,
                    #validation_data=(x_val, y_val),
                    callbacks=[tensorboard],
                    verbose=1)

results = model.evaluate(test_data, test_labels)

print(results)

**Comment by rmothukuru** [comment]
@wchargin ,
Can you PTAL

**Comment by wchargin** [comment]
With a slight modification, the provided code works in the release
candidate for TensorFlow 1.14. The `embeddings_data=partial_x_train`
line needs to be changed to `embeddings_data=[partial_x_train]`:

![Screenshot of embeddings](https://user-images.githubusercontent.com/4317806/59127313-2edf8180-891c-11e9-92bf-d1860880340b.png)

If you’re still having the issue in 1.14 or nightly, let us know and we
can reopen this issue.
