### ISSUE TITLE
Add tensorboard embedding visualization in my own web application

### ISSUE THREAD

**Issue by krushika29** [tensorflow/tensorboard#2078]
Hello
I want to understand if it is possible to include the embedding projector visualization in my own web application, and if tensorboard library provides that support.

I understand that to visualize it, it opens a new session on port 6006 and the board displays. But for my use case I need only the embedding visualization to display from a python script.
Let me know if that is possible, and if yes, please provide some documentation on doing so.

Thanks in advance.

**Comment by hgadig** [comment]
Below ai blog link has more information about open sourcing Embedding Projector.
https://ai.googleblog.com/2016/12/open-sourcing-embedding-projector-tool.html

Below links have some example usage of Embedding projector.
https://stackoverflow.com/questions/40849116/how-to-use-tensorboard-embedding-projector
https://github.com/harveyslash/TSNE-Embedding-Visualisation

**Comment by amanp592** [comment]
@krushika29 Till date there is no support that you can use the embedding visualizer in your own web application, a standalone version of embedding visualizer is currently available at http://projector.tensorflow.org/ as mentioned by @hgadig but right now there is no such support to my knowledge, the tensorboard library also have no as such support till now!

**Comment by wchargin** [comment]
Hi @krushika29! There isn’t a way to do this out of the box, no.
Depending on how much effort you’re willing to invest, and what
functionality exactly you want, you may be able to make something work.
The projector is defined as a web library here—

https://github.com/tensorflow/tensorboard/blob/9270699784657b69a21f022dce98c439f7602d86/tensorboard/plugins/projector/vz_projector/BUILD#L8-L9

—which you can depend on if you’re developing a Bazel project yourself.
If you have questions about how the build rules work, feel free to ask.

**Comment by hgadig** [comment]
Closing as this issue is in "awaiting response" status for 3 days. Please take a look into the answers provided above and post your comments(if you still have queries on this). Thank you!

**Comment by krushika29** [comment]
@hgadig Thank you so much for all the links.
Specifically, a link you provided was helpful to me, and I have a few doubts regarding it. https://github.com/harveyslash/TSNE-Embedding-Visualisation

I am trying to replicate the above standalone embedding projector for my model.
I have already built a translation model, and I need this standalone embedding projector to visualize the word embeddings.

For this in the above project, I need to provide the following details in the configuration file (.json) file.
I am providing an example of the configuration file provided here for word2vec embeddings : https://github.com/tensorflow/embedding-projector-standalone

```
"embeddings": [
{
    "tensorName": "Word2Vec 10K",
    "tensorShape": [10000, 200],
    "tensorPath": "oss_data/word2vec_10000_200d_tensors.bytes",
    "metadataPath": "oss_data/word2vec_10000_200d_labels.tsv"
 }
```

I understand the parameters, `tensorShape`, `metadataPath`, but I am confused on what is the `tensorPath` as I have used OpenNMT-tf [http://opennmt.net/OpenNMT-tf/quickstart.html](OpenNMT-tf) for training my Transformer model on the text corpus.

Another hint, after training the model using OpenNMT-tf, a log directory is generated, and I use that log directory to open up the tensorboard and also visualize the embedding on the tensorboard, which means that all the information and parameters are present in the log directory which can help me use in the stand alone embedding projector as well.


Any help or lead on this would be really appreciated.

Thanks in advance !!

**Comment by peps0791** [comment]
Why not make use of the [tensorflow projector website](https://projector.tensorflow.org/) inside of an iFrame in you web app? 
You can create a shareable link with your own data and metadata with tensorflow projector and use that link inside an iframe in your own website. 
I tested this on the w3schools iframe tutorial page and seems to be working fine.

![Screenshot from 2019-07-01 14-34-14](https://user-images.githubusercontent.com/2004804/60468092-5e2c9a00-9c0d-11e9-9d9b-056c20a6e4ad.png)

**Comment by akdeepak** [comment]
> Hi @krushika29! There isn’t a way to do this out of the box, no.
> Depending on how much effort you’re willing to invest, and what
> functionality exactly you want, you may be able to make something work.
> The projector is defined as a web library here—
> 
> https://github.com/tensorflow/tensorboard/blob/9270699784657b69a21f022dce98c439f7602d86/tensorboard/plugins/projector/vz_projector/BUILD#L8-L9
> 
> —which you can depend on if you’re developing a Bazel project yourself.
> If you have questions about how the build rules work, feel free to ask.

Hi ,Yes I would like to undestand how the build rule works . can you please share the intricacies. Thanks in advance.

Kind regards
Deepak

**Comment by nadineshmo** [comment]
Has anyone been able to integrate the embedding projector into a web app since this issue was posted? I am also interested in this.

**Comment by 54321lalalalala** [comment]
Has there been any support added to integrate the embedding projector in a web app since this was posted, or has anyone done this successfully? 
@wchargin @thealphacod3r @akdeepak @krushika29

**Comment by chiranshu14** [comment]
@54321lalalalala  Did you find any way to integrate embedding projector in a web app?

**Comment by nadineshmo** [comment]
Not out of the box. I ended up copying/pasting/modifying the parts that I
needed.

**Comment by chiranshu14** [comment]
@krushika29 could you provide any reference to sources that you used to get it working?
Or maybe could you link your repo?

Thanks!

**Comment by muffpy** [comment]
@wchargin Hey! May I ask what a web library target really is? It seems to be defined [here](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/defs/web.bzl) but I'm not really familiar with Bazel rules.

My use case is adding the Embedding projector to one of the views in my web app with tensor and metadata inputs that change every day. Just unsure of the first part.
