### ISSUE TITLE
k-nearest-neighbors caching is broken (unsound)

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2082]
Missed this in my review of #1901. The cache key check is incorrect. The
code reads:

https://github.com/tensorflow/tensorboard/blob/9270699784657b69a21f022dce98c439f7602d86/tensorboard/plugins/projector/vz_projector/data.ts#L444-L447

where the `nNeighbors <= this.nearest.length` is intended to check
whether the cached KNN computation was computed with a value of
`nNeighbors` not smaller than the currently requested value. But in fact
`this.nearest.length` is the number of data points, not the number of
neighbors computed for each point.

To verify, add

```typescript
    console.log(
        `Found ${nNeighbors}-nearest: shape is ` +
        `(${this.nearest.length}, ${this.nearest[0].length})`
    );
```

below line 384 in `projectUmap`. Then, run UMAP, and subsequently re-run
UMAP with a higher value of *k*. The output is (e.g.)

```
Found 15-nearest: shape is (1024, 15)
Found 23-nearest: shape is (1024, 15)
```

which is wrong, because after attempting to find the 23-nearest
neighbors we only have 15 elements for each data point.

I’m not sure why this never hits a hard error anywhere in the
pipeline—implicit conversion of `undefined` to `0`/`NaN` somewhere?—but
it definitely causes observable effects. To observe, patch in #2080\* to
prevent t-SNE from running automatically when its tab is selected, then:

  - in one tab, load the projector page and run t-SNE with
    perplexity=100;

  - in another tab, load the projector page and run t-SNE with
    perplexity=8, then re-run it with perplexity=100.

These two tabs _should_ yield approximately the same projection, but
instead the projection in the first tab converges to a normal result
whereas the projection in the second tab diverges to points far apart
with little visible structure:

![Screenshot of t-SNE okay as described above](https://user-images.githubusercontent.com/4317806/55366553-1b3c1880-549e-11e9-9170-4178410f6a72.png)

![Screenshot of t-SNE diverged as described above](https://user-images.githubusercontent.com/4317806/55366552-1b3c1880-549e-11e9-89e0-e900d88347b2.png)

\* Tested at commit b0310cd76bd84038a72b1df40c4711a12b959951.

**Comment by wchargin** [comment]
Assigning @cannoneyed.

**Comment by shashvatshahi1998** [comment]
@wchargin can I work on this, just guide a little more about the issue.

**Comment by cannoneyed** [comment]
Hey @wchargin, now that everything is sorted on the rest of the UMAP end, I'm gonna take care of this. Hopefully I'll have a PR for you by EOD.
