### ISSUE TITLE
Bazel 0.22 build tensorboard failed

### ISSUE THREAD

**Issue by XFeiF** [tensorflow/tensorboard#2085]
## Bazel 0.22 build tensorboard failed
ubuntu 18.04  
python 3.6
tf-estimator-nightly 1.14.0.dev2019040201
tf-nightly           1.14.1.dev20190402
tb-nightly           1.14.0a20190319
> $ bazel build tensorboard
INFO: Invocation ID: 0c8e229f-c313-4eb2-8cdc-6c1a37a0a3a2
ERROR: While resolving toolchains for target //tensorboard:tensorboard: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):
File"/home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
_remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)
 File"/home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/io_bazel_rules_go/go/private/sdk.bzl", line 113, in _remote_sdk
ctx.download_and_extract(url = urls, stripPrefix = strip_pr..., ...)
java.io.IOException: Error downloading [https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz] to /home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/go_sdk/go1.11.2.linux-amd64.tar.gz: Network is unreachable (connect failed)
ERROR: Analysis of target '//tensorboard:tensorboard' failed; build aborted: invalid registered toolchain '@go_sdk//:go_android_386': no such package '@go_sdk//': Traceback (most recent call last):  File"/home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/io_bazel_rules_go/go/private/sdk.bzl", line 51
 _remote_sdk(ctx, [url.format(filename) for url...], <2 more arguments>)     File"/home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/io_bazel_rules_go/go/private/sdk.bzl", line 113, in _remote_sdk
                ctx.download_and_extract(url = urls, stripPrefix = strip_pr..., ...)
java.io.IOException: Error downloading [https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz] to /home/fei/.cache/bazel/_bazel_fei/6b1d92f0d28c807d38edad696c678fbd/external/go_sdk/go1.11.2.linux-amd64.tar.gz: Network is unreachable (connect failed)
INFO: Elapsed time: 12.815s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    Fetching @go_sdk; fetching 12s

I do not find any issue about my situation. What 's wrong with it?

**Comment by wchargin** [comment]
Hi @XFeiF! TensorBoard should work just fine with Bazel 0.22. It looks
like you had a network error: “Network is unreachable (connect failed)”.
Perhaps your internet was disconnected during the fetch phase?

In general, our minimum Bazel version is listed here:
https://github.com/tensorflow/tensorboard/blob/4c5e3f323beb1974473c1b32d5e6daff33c11ae6/WORKSPACE#L19

Currently, it’s at 0.22.0.

**Comment by XFeiF** [comment]
@wchargin Thanks. I've solved it!

**Comment by wchargin** [comment]
Great; glad to hear it.

**Comment by Red-4-Life** [comment]
> @wchargin Thanks. I've solved it!

Excuse me, I've met the same problem, but I'm sure my network is connected. I'm not sure if my network is blocked from this website or what. Could you tell me the way you solved this problem?
