### ISSUE TITLE
`tensorboard` should support `--version`

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2087]
When dealing with path issues, such as when users (mistakenly) have
multiple versions of TensorBoard installed or are trying to coordinate
modules from multiple sources (e.g., a virtualenv plus system site
packages), having `tensorboard --version` would be helpful. It’s also
useful as a minimal “is TensorBoard installed?” command that’s less
verbose than `tensorboard --helpshort` (131 lines) and more portable
than `which tensorboard` (it’s `where tensorboard` on Windows).

Plus, come on: everything supports `--version`. :-)

**Comment by amanp592** [comment]
@wchargin can you guide me on this I would love to work on this!!

**Comment by wchargin** [comment]
Hi @amanp592! Yes, this is probably a good starter issue.

You’ll want to define a new `--version` flag. There’s not a clearly
correct place for this flag to live, but it seems reasonable enough to
add it to `core_plugin.py`’s `define_flags` method. Then, in `fix_flags`
in the same file, you can print out the version and exit with success if
the `--version` flag was passed.

Let us know if you have questions.

**Comment by nfelt** [comment]
I think it might be a bit better to implement the version printing in `tensorboard.program.Tensorboard.main`, which is the way it works for `--inspect`:

https://github.com/tensorflow/tensorboard/blob/58df24b5aad3c828e8d87c3e8abbc507f8bc68b7/tensorboard/program.py#L219-L223

That seems slightly cleaner than just calling `sys.exit()` in the flag processing code itself since it keeps the functional behavior of main() all in one place and the flag processing just focused on flag processing.

**Comment by wchargin** [comment]
> I think it might be a bit better to implement the version printing in
> `tensorboard.program.Tensorboard.main`, which is the way it works for
> `--inspect`:

That’s also fine with me, given that `inspect` works that way already.

(For what it’s worth, IMHO this isn’t entirely satisfactory, either,
because really `main` should not depend on any plugin… and really it’s
questionable whether `core_plugin` should be a plugin at all.)

**Comment by nfelt** [comment]
Yes, I think the problem there is that we have been putting flags that really relate mostly to `program` itself into CorePlugin for lack of a better place.

**Comment by shashvatshahi1998** [comment]
@wchargin, @nfelt can you please tell me what else i have to add in this PR.

**Comment by nfelt** [comment]
Fixed by #2097.
