### ISSUE TITLE
What are the configuration parameters for the standalone-embedding proejctor?

### ISSUE THREAD

**Issue by krushika29** [tensorflow/tensorboard#2103]
Hello, I am trying to replicate the below standalone embedding projector for my model.
https://github.com/harveyslash/TSNE-Embedding-Visualisation

which was originally forked from [here](https://github.com/tensorflow/embedding-projector-standalone).

I have already built a translation model, and I need this standalone embedding projector to visualize the word embeddings.

For this in the above project, I need to provide the following details in the configuration file (.json) file.
I am providing an example of the configuration file provided [here](https://github.com/tensorflow/embedding-projector-standalone/blob/master/oss_data/oss_demo_projector_config.json) for word2vec embeddings : https://github.com/tensorflow/embedding-projector-standalone

```
"embeddings": [
{
    "tensorName": "Word2Vec 10K",
    "tensorShape": [10000, 200],
    "tensorPath": "oss_data/word2vec_10000_200d_tensors.bytes",
    "metadataPath": "oss_data/word2vec_10000_200d_labels.tsv"
 }
```

I understand the parameters, `tensorShape`, `metadataPath`, but I am confused on what is the tensorPath as I have used [OpenNMT-tf](http://opennmt.net/OpenNMT-tf/quickstart.html) for training my Transformer model on the text corpus.

Another hint, after training the model using OpenNMT-tf, a log directory is generated, and I use that log directory to open up the tensorboard and also visualize the embedding on the tensorboard, which means that all the information and parameters are present in the log directory which can help me use in the stand alone embedding projector as well.

Any help or lead on this would be really appreciated.

Thanks in advance !!

**Comment by krushika29** [comment]
Edit 1 : 
Updating the structure of my log directory `(log-dir)` obtained after training the model.This is the same directory which I use when I open tensorboard by using the command `tensorboard --logdir="log_dir"`

```
log_dir/
├── assets
├── avg
│   ├── checkpoint
│   ├── model.ckpt-10000.data-00000-of-00001
│   ├── model.ckpt-10000.index
│   └── model.ckpt-10000.meta
├── checkpoint
├── eval
│   ├── events.out.tfevents.1552864281.ip-172-31-15-220
│   ├── predictions.txt.1000
│   ├── predictions.txt.10000
│   ├── predictions.txt.2000
│   ├── predictions.txt.3000
│   ├── predictions.txt.4000
│   ├── predictions.txt.5000
│   ├── predictions.txt.6000
│   ├── predictions.txt.7000
│   ├── predictions.txt.8000
│   └── predictions.txt.9000
├── events.out.tfevents.1552861146.ip-172-31-15-220
├── export
│   └── latest
│       ├── 1552880367
│       │   ├── assets
│       │   │   ├── src-vocab-1.txt
│       │   │   └── tgt-vocab-1.txt
│       │   ├── saved_model.pb
│       │   └── variables
│       │       ├── variables.data-00000-of-00001
│       │       └── variables.index
├── graph.pbtxt
├── model.ckpt-10000.data-00000-of-00002
├── model.ckpt-10000.data-00001-of-00002
├── model.ckpt-10000.index
├── model.ckpt-10000.meta
├── model_description.py
├── projector_config.pbtxt
├── transformer_decoder_w_embs.txt
├── transformer_encoder_w_embs.txt

```

I am trying to figure out which file do I provide for the parameter `tensorpath` in the above mentioned `config.json` file

Thanks in advance !!

**Comment by gowtham-kp** [comment]
@krushika29 Are you still facing with the same issue or did you solve it?

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by luggie** [comment]
Still struggling with this. When the standalone is opened, I can easily load meta/tensors in TSV format but via the .json the latter needs to be in .bytes format that I can't generate. Even tough I was searching extensively, I couldn't find any help on this anywhere.

**Comment by ionutdicusor** [comment]
tensorPath.tsv
A 10
B 20
metadataPath.tsv(instead .byets)
Col1	Col2	Col3
Test1	A	10
Test2	B	20
