### ISSUE TITLE
 tensorboard logdir

### ISSUE THREAD

**Issue by madymnm** [tensorflow/tensorboard#2176]
I am trying to run Tensorboard but every time it askme to install logdir in folder where Python3.7 is installed.In the comand line when I run tensorboard --logdir mylogdir (as given example in the tensorboard --help).I am getting,
TensorBoard 1.13.1 at http://mayurbhavi-PC:6006 (Press CTRL+C to quit
and it stays until I press CTRL +C but then it gives following error
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FF909C23B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FF95C7D56FD  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF95F4B4034  Unknown               Unknown  Unknown
ntdll.dll          00007FF9600F3691  Unknown               Unknown  Unknown
Next time when I tried to run a tensorboard command via spyder or Jupyter notebook,I get same error to install the logdir first.
I tried to follow the instructions on tensorboard but I am not sure where I am going wrong.
Kindly help or comment.
Thanks

**Comment by wchargin** [comment]
> I am getting,
> TensorBoard 1.13.1 at http://mayurbhavi-PC:6006 (Press CTRL+C to quit

This is expected. It means that TensorBoard is running. You should visit
that URL in your web browser to open TensorBoard.

> ```
> forrtl: error (200): program aborting due to control-C event
> ```

This appears to be a known error on Windows with Scipy:
<https://stackoverflow.com/questions/15457786/ctrl-c-crashes-python-after-importing-scipy-stats>

It doesn’t look like there’s an easy fix, but if it only occurs when
you’re trying to quit TensorBoard anyway then I wouldn’t worry about it.
