### ISSUE TITLE
Tensorboard show only graph and nothing

### ISSUE THREAD

**Issue by HyunjiEllenPak** [tensorflow/tensorboard#2184]
HI, I have trouble with tensorboard showing.
I'm using those versions of modules below.

-tensorflow 1.12.0
-tensorflow-gpu 1.12.0
-tensorboard 1.12.0
-python 3.5
-window10
-crome browser: 73.0.3683.103

with these, when I tried to show the tensorboard in chrome using the code below, I failed to see the tensorboard results such as scalar, image, histogram, distribution and etc..

**tensorboard --logdir=/path/to/dir --host localhost --port 8088**
![image](https://user-images.githubusercontent.com/16814077/57127613-f81dc500-6dcb-11e9-939c-d7ef434f1503.png)

I can only show the graphs below.
![image](https://user-images.githubusercontent.com/16814077/57127557-be4cbe80-6dcb-11e9-858c-fdd17180f870.png)
![image](https://user-images.githubusercontent.com/16814077/57127623-02d85a00-6dcc-11e9-86b3-6f9e141e2730.png)

And I tried to do it without port number and with port#6006 also. but that showed me anything even the graph. it gave me the error below.
![image](https://user-images.githubusercontent.com/16814077/57127774-59459880-6dcc-11e9-86f1-7482f53bbec3.png)

I really wanna figure out the reason why I couldn't use tensorboard.
Actually,a month ago, I could see the tensorboard result, but suddenly, I can't see it now. How can I solve it?

**Comment by stephanwlee** [comment]
Hi @HyunjiEllenPak,

> Actually,a month ago, I could see the tensorboard result, but suddenly, I can't see it now. How can I solve it?

Dashboard activeness highly relates to type of data written out to an event file. Above, are you saying that TensorBoard has changed in behavior when using the same logdir? If so, it is a critical bug we'd like to address. Would you be able to provide us with an example we can work with? Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
