### ISSUE TITLE
HParams Table Download as csv/markdown/latex

### ISSUE THREAD

**Issue by eisenjulian** [tensorflow/tensorboard#2210]
For the new awesome HParam feature, it would be great to download the generated tables in some format that's helpful for including in papers or documentation. I've integrated the feature into my company's internally facing tensorboard and besides all the awesome feedback this question keeps popping up.

I might have some bandwidth to contribute to this if you think it's valuable. Thanks!

**Comment by nfelt** [comment]
Hi @eisenjulian - sorry for a very belated response, but I'm glad you like the HParams dashboard and if you (or anyone else) happens to still be interested in implementing a CSV download for the data I think that would be a nice addition.  There's some logic to download as CSV already for scalars, which I'd expect could be adapted for the HParams plugin.
