### ISSUE TITLE
Zoom charts by holding Shift

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorboard#2214]
Current versions of tensorboard support zooming of charts by mouswheel.
I find it rather annoying that when scrolling down the page I sometimes accidentally zoom out charts.

I propose to support zooming charts only when pressing `Ctrl` while scolling.

**Comment by stephanwlee** [comment]
Sounds easy and doable but I do not want to override browser default behavior. As such, I think `shift` + wheel makes more sense (shift + wheel horizontally scrolls)

**Comment by sleighsoft** [comment]
Sure

**Comment by wchargin** [comment]
I’ve also been annoyed by this when scrolling down the page and getting
my mouse “caught” in a chart. Not sure what the right solution is; maybe
Shift-scroll is fine. We might also want to have zoom functionality that
does not depend on the mouse, for accessibility reasons.
