### ISSUE TITLE
Getting a random value from a Domain

### ISSUE THREAD

**Issue by Neabfi** [tensorflow/tensorboard#2246]
It would be convenient to have a single method to get a random value from a Domain. It would make the code to do a random search shorter and prettier. 

Would that make sense? If yes, I can create a PR.
(cc @wchargin )

Examples:

```
class RealInterval(Domain):
  ...
  def rand(self):
    return random.randint(self.minvalue, self.maxvalue)
  ... 
```

```
class Discrete(Domain):
  ...
  def rand(self):
    return random.choice(self.values)
  ... 
```

**Comment by wchargin** [comment]
Hi @Neabfi! Thanks for the feedback. I considered this, and a [previous
draft of the APIs included `Domain.sample_uniform`][1]. I opted to cut
it for a few reasons, which all boil down to the following: while we
provide a vocabulary for describing domains, we don’t provide any actual
tuning algorithms (nor do we currently plan to), and I didn’t want to
give an impression to the contrary. That is, one might expect that if we
provide random sampling, which is basically a random-search tuner in all
but name, we must surely provide something more sophisticated (à la
Vizier), but this is not the case.

Note that you can write your own `sample_uniform`, as in [the demo][2]
(which is separate from the tutorial notebook), which streamlines the
rest of your model code. But I’m sympathetic to the point of view that
even this is boilerplate that the library should provide. I’ll bring
this up tomorrow and get some other opinions internally.

[1]: https://github.com/tensorflow/tensorboard/commit/b7fdbd67ea6cc6f3f5ba124d0ce28b97661ebf8e#diff-bb02e3aa0fe58a6bb391873a63f12c2bR129
[2]: https://github.com/tensorflow/tensorboard/blob/52a9d4075498381b10d92d85fedaf63c8bfe0c37/tensorboard/plugins/hparams/hparams_demo.py#L247-L265

**Comment by wchargin** [comment]
> I’ll bring this up tomorrow and get some other opinions internally.

This is fine with us. Sent #2259.

> If yes, I can create a PR.

Thank you for the offer—we appreciate it! In this case there were some
particular tests that I wanted to include, so I went ahead and created
the PR myself, but in general we’d be more than happy to accept your
contributions!
