### ISSUE TITLE
Wall times are all incorrect in the image dashboard. They all currently show "Jan 18 1970".

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#225]
![ddoh2acxlc1](https://user-images.githubusercontent.com/4221553/28150595-4dae81ba-674a-11e7-912b-69e79983dea4.png)

The issue stems from how we pass a timestamp (since the epoch) in seconds into the native Date constructor. That value should be in milliseconds instead.
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html#L287

This is broken for TensorBoard both within and outside of internal Google usage. Thank you to Ian Goodfellow for bringing this issue to my attention.

**Comment by wchargin** [comment]
Fixed by #226.
