### ISSUE TITLE
Documentation for Debugger Dashboard

### ISSUE THREAD

**Issue by brunapinos** [tensorflow/tensorboard#2282]
Hi! I'm Bruna, one of the GSoCers of TensorFlow, and the main goal of my project is to improve TensorBoard documentation.

I've seen that on [TensorBoard - TF 2.0 Alpha](https://www.tensorflow.org/tensorboard/r2/get_started) already has documentation of the main dashboards of TensorBoard, but it is still missing Debugger one. Searching any information about Debugger, I've found this [page](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/debugger/README.md).

I think it would be great to have this tutorial along with the others on TensorBoard page!

**Comment by stephanwlee** [comment]
Hi Bruna, welcome and thanks for helping us improve the documentation!

Unfortunately, the debugger is still very `tf.Session`-centric and is not so TF 2.0 friendly and, as a result, I don't think it is not yet so appropriate to create one for https://www.tensorflow.org/tensorboard/r2/get_started. 

Regardless, I think it is still a good idea to create a Colab tutorial for the plugin that show cases how it can be useful in TF 1.x (or TF 2.0 in a v1 mode).

**Comment by brunapinos** [comment]
Okay! I'll work in this tutorial. Thanks (:

**Comment by gowtham-kp** [comment]
Closing this issue as this has been resolved. Please add additional comments and we can reopen the issue again. Thanks!
