### ISSUE TITLE
profile: pod viewer tooltip position

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#2284]
The tooltip displayed when hovering on image of a pod not only is positioned suboptimally but also incorrectly positions with respect to the scroll position.

Before scroll:
![image](https://user-images.githubusercontent.com/2547313/58574100-15d82180-81f4-11e9-8683-14d7cbdc376d.png)

After scroll:
![image](https://user-images.githubusercontent.com/2547313/58574132-27212e00-81f4-11e9-9b5d-a85c47b00ff5.png)

Note that although I hovered on the same TPU at col 7 row 9, the tooltip is missing. If I scroll the page up a little while maintaining the cursor on the TPU, you will find the tooltip rendered above the viewport.

![image](https://user-images.githubusercontent.com/2547313/58574149-30aa9600-81f4-11e9-9ad9-9bba09062860.png)

**Comment by qiuminxu** [comment]
Sure, I will take a look on how to better position the tooltip. BTW, I've moved the folder and please use gs://cloud-tpu-tools/test in the future.
