### ISSUE TITLE
Image scroll slider: only 10 positions

### ISSUE THREAD

**Issue by Belerafon** [tensorflow/tensorboard#229]
When I use slider at Image tab to scroll my images it is not possible to show all saved images: only 10 steps works. I think it because slider to scroll images has only 10 fixed positions. It must be able to scroll over all saved data. May be additional buttons like "step forward" are needed.
![2017-07-15_20-59-16](https://user-images.githubusercontent.com/6260724/28241659-6614c364-69a1-11e7-8df8-a8931a9f2ad0.png)

**Comment by wchargin** [comment]
[As we describe in the README](https://github.com/tensorflow/tensorboard#is-my-data-being-downsampled-am-i-really-seeing-all-the-data), TensorBoard downsamples data to preserve memory usage. You should apply the following patch if you want TensorBoard to retain more images:
```diff
diff --git a/tensorboard/backend/application.py b/tensorboard/backend/application.py
index e6e9540..3a19903 100644
--- a/tensorboard/backend/application.py
+++ b/tensorboard/backend/application.py
@@ -45,7 +45,7 @@ from tensorboard.plugins.core import core_plugin
 
 DEFAULT_SIZE_GUIDANCE = {
     event_accumulator.COMPRESSED_HISTOGRAMS: 500,
-    event_accumulator.IMAGES: 10,
+    event_accumulator.IMAGES: 1000,
     event_accumulator.AUDIO: 10,
     event_accumulator.SCALARS: 1000,
     event_accumulator.HISTOGRAMS: 50,
```
