### ISSUE TITLE
Chrome M75 visual regression: double scrollbar on runs selector in sidebar

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2325]
Screenshot:

![Screenshot of double ](https://user-images.githubusercontent.com/4317806/59055099-f4a5af80-8849-11e9-9cf8-2740ac628105.png)

Have been noticing this since Chrome M75 yesterday. On M75, can repro on
both master and a commit from two months ago; on M74, cannot repro.

It’s both unsightly and really frustrating, because you feel like you
want to scroll down to the “Toggle All Runs” button, but scrolling down
doesn’t show the button.

**Comment by stephanwlee** [comment]
Fixed by #2333. 
(sorry, forgot to annotate the PR with the GitHub magic)
