### ISSUE TITLE
Tensorboard build fails on s390x 

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorboard#2344]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04 s390x**
Tensorboard version: 1.13.1
Bazel version (if compiling from source): **v0.24.1**
GCC/Compiler version (if compiling from source): **7.4.0 (Ubuntu 18.04)**
JAVA : ***openjdk version "1.8.0_212**"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Zero VM (build 25.212-b03, interpreted mode)

**Describe the problem**
Tensorboard build command fails with segmentation fault 

**Details:** 
Steps to reproduce:

```
git clone https://github.com/tensorflow/tensorboard.git
 cd tensorboard/
 git checkout 1.13.1
~/tensorboard# bazel build --host_javabase="@local_jdk//:jdk" --incompatible_disallow_filetype=false --incompatible_disallow_data_transition=false --sandbox_debug  //tensorboard
```
Execution failed with below error:
```
INFO: Analysed target //tensorboard:tensorboard (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Generating SOY v2 Java files @io_bazel_rules_closure//java/io/bazel/rules/closure/webfiles/server:listing_files [for host]:
ERROR: /root/.cache/bazel/_bazel_root/f30c2f544fac57d7cdae0aa9f6f05210/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/BUILD:57:1: Building Java resource jar failed (Segmentation fault): process-wrapper failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/f30c2f544fac57d7cdae0aa9f6f05210/sandbox/processwrapper-sandbox/63/execroot/org_tensorflow_tensorboard && \
  exec env - \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/104f262c5f85f241db495ba79b3dad36/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' external/bazel_tools/tools/jdk/singlejar/singlejar --normalize --dont_change_compression --exclude_build_data --output bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/liblisting.jar --sources bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/liblisting-class.jar --resources external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/listing.soy:io/bazel/rules/closure/webfiles/server/listing.soy) process-wrapper failed: error executing command
singlejar: src/tools/singlejar/output_jar.cc:608: write: Success
Target //tensorboard:tensorboard failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
Could you please provide some suggestions/inputs on this?

**Comment by Nayana-ibm** [comment]
@gunan @sjamesr Could you please provide inputs on this?

**Comment by Nayana-ibm** [comment]
@nfelt Could you please provide inputs on this?

**Comment by nfelt** [comment]
Hi @Nayana-ibm - sorry, but the s390x build isn't one of TF's officially supported ones and TensorBoard follows that precedent in terms of what we directly support.  I'm happy to leave the issue open but I honestly don't have any idea why it's segfaulting (and don't have a machine available to test).

That said, I'd be surprised if there is anything about TensorBoard that is inherently incompatible with s390x, so I'd expect you might be able to construct a minimal repro case that just uses rules_closure() and Bazel (no TensorBoard code) in which case you could follow up in one of those repositories for further advice.

**Comment by UsharaniPagadala** [comment]
@Nayana-ibm 

Closing this issue based on the @nfelt 's comment.Please feel free to reopen if this still persists.Thanks
