### ISSUE TITLE
tensor board does not load in safari

### ISSUE THREAD

**Issue by episodeyang** [tensorflow/tensorboard#236]
The same server loads in Chrome. 

In safari, the console prints:

```
TypeError: document.registerElement is not a function. (In 'document.registerElement("dom-module",a)', 'document.registerElement' is undefined)

and

TypeError: Polymer.Base._getExtendedPrototype is not a function. (In 'Polymer.Base._getExtendedPrototype(a.extends)', 'Polymer.Base._getExtendedPrototype' is undefined)

and

TypeError: this._desugarBehaviors is not a function. (In 'this._desugarBehaviors()', 'this._desugarBehaviors' is undefined)
```

**Comment by jart** [comment]
What version of TensorBoard are you using?

**Comment by episodeyang** [comment]
It would be nice if `tensorboard -v` gives the version. 

The version I'm using is compiled from source/master two days ago.

**Comment by episodeyang** [comment]
v0.1.2

**Comment by dandelionmane** [comment]
We don't officially support Safari - as mentioned in the README, Chrome and Firefox are the browsers that we target. 

That said, this might not be too complicated to fix. @jart do we want to try to keep this working? Maybe we are importing webcomponent.js when we should be importing webcomponent-lite or something like that?

**Comment by episodeyang** [comment]
@dandelionmane @jart Thanks for the quick reply! My friend was also trying to access this from an iPad Pro. It is not necessary to support the full functionality, but being able to show the plots would be good.

As of now, `tensorboard` does not work on either an OSX safari or iOS safari or webview.

**Comment by dandelionmane** [comment]
(random aside:) oh hey, you go to UChicago! I went there for undergrad. Also, escherpad looks pretty cool!

(on subject): The core team isn't prioritizing supporting Safari, however we will gladly accept pull requests that fix it 😸. Going to mark this issue "Contributions Welcome".

**Comment by episodeyang** [comment]
@dandelionmane Thanks ;-P I am graduating from my PhD soon, hopefully will land in the bay area.

**Comment by humphd** [comment]
Like @episodeyang, I hit this earlier in the summer, and I wanted to fix it (I had a similar issue in Firefox).  However, when I cloned and tested the current code on `master` today, I am no longer able to reproduce the issue in Safari (it works on Chrome, Firefox, and Safari for me).

TensorBoard running in Safari (macOS):

![tensorboard-safari-small](https://user-images.githubusercontent.com/427398/30130272-a29107dc-9316-11e7-9730-df46682639c2.png)

TensorBoard running on Safari (iOS):

![tensorboard-ios](https://user-images.githubusercontent.com/427398/30130330-c5a59846-9316-11e7-8bed-a153ddfb2c4b.png)

It looks like in the intervening period this has been fixed, perhaps by https://github.com/tensorflow/tensorboard/commit/6dee09c9a2a141160c1e96ba88d08ebb10316c6c#diff-369d1fc7cf91528eed5e141ac67ccffa?

At any rate, I think this is fixed, and can be closed now.

**Comment by episodeyang** [comment]
@dandelionmane @jart closed because this is not an issue anymore. We can reopen if it appears again.

Thanks for the fix, and happy tensorflowing :)

**Comment by cipri-tom** [comment]
Hi,
This is happening in Firefox :( (with the same errors). I can't tell the tensorboard version, but I am on docker tag [1.3.0-gpu-py3](https://hub.docker.com/r/tensorflow/tensorflow/tags/). It does work correctly in Chrome

**Comment by py2ai** [comment]
Just type this in Safari 
http://localhost:6006
