### ISSUE TITLE
Only receiving last step when calling EventAccumulator().Histograms()

### ISSUE THREAD

**Issue by khuesmann** [tensorflow/tensorboard#2361]
I faced a problem when reading histogram data from da log file.
When calling `EventAccumulator(...).Histograms(...)`, i'll only receive the last step's histogram. `EventAccumulator(...).CompressedHistograms(...)` returns all steps, but unfortunately the histograms are .... compressed...

Tensorflow Version: '1.13.1'

I have the following code to fetch histograms from a log file:
```
def read_tensorboard_histograms(path):
    event_acc = EventAccumulator(path)
    event_acc.Reload()
    tags = event_acc.Tags()
    for hist in tags['histograms']:
        h1 = event_acc.Histograms(hist)    
        h2 = event_acc.CompressedHistograms(hist)     
        # len(h1) == 1
        # len(h2) == true_step_count
```

The histogram's are created with following code:
```
...
summary = tf.Summary(value=[tf.Summary.Value(tag=tag, histo=hist)])
writer.add_summary(summary, step)
...
```

Histograms show up on the web interface. Am i able to recalculate the full data with the last step histogram and the compressed histograms?

Is this intended behaviour?

**EDIT**
Got it ... sorry ... this can be closed.
I have to change the size_guidance when creating the EventAccumulator:
```
event_acc = EventAccumulator(path, size_guidance={
        'histograms': 49,
    })
```

**Comment by wchargin** [comment]
Yep, the size guidance is the right thing to tune. Glad that you found a
solution!
