### ISSUE TITLE
PYYAML not found

### ISSUE THREAD

**Issue by vipulroxx** [tensorflow/tensorboard#2379]
Running ```.to_yaml()``` on mac is giving me this error :
```
Traceback (most recent call last):
  File "check-keras.py", line 197, in <module>
    yaml_string = model.to_yaml()
  File "/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/network.py", line 1560, in to_yaml
    'Requires yaml module installed (`pip install pyyaml`).')
ImportError: Requires yaml module installed (`pip install pyyaml`)
```
When I run pip install, it says that the package already exists.
```
Vipuls-MacBook-Air:Keras vipulsharma$ pip install pyyaml
Requirement already satisfied: pyyaml in /Users/vipulsharma/Library/Python/2.7/lib/python/site-packages (5.1.1)
```

How am I supposed to run it?

**Comment by vipulroxx** [comment]
So I figured in the above terminal output
``` File "/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/network.py", line 1560,``` 
This version of Python is different than the version here :
```Requirement already satisfied: pyyaml in /Users/vipulsharma/Library/Python/2.7/lib/python/site-packages (5.1.1)```.
So I tried installing yaml in 
```/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/```
 by doing a 
```pip install --target=/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/ pyyaml```. It installed yaml in  ```/Users/vipulsharma/Library/Python/3.7/lib/python/site-packages/```  successfully, but when I run my Python file it gives me the same error.

**Comment by wchargin** [comment]
Hi @vipulroxx! This looks like an issue with TensorFlow, not
TensorBoard. Please [open an issue over at the TensorFlow repository][1]
instead.

[1]: https://github.com/tensorflow/tensorflow/issues/new/choose
