### ISSUE TITLE
Modify Label Font in Projections?

### ISSUE THREAD

**Issue by AlliedToasters** [tensorflow/tensorboard#2391]
I'm visualizing some category embeddings using the projections feature. I would like to see the labels, but when I turn on "label by, label", I get labels that are too small to read:

![Screenshot from 2019-06-27 14-55-57](https://user-images.githubusercontent.com/27147422/60289078-fbc15a00-98eb-11e9-9037-34f9904b1953.png)

Is there any way to modify the font size on those labels so I can read them? If not, could we add this as a feature? Thanks!

**Comment by gowtham-kp** [comment]
Closing the issue due to the lack of recent activity. Please add additional comments and we can open the issue again. Thanks!

**Comment by nobuyukioishi** [comment]
I want to how to increase the font size.
