### ISSUE TITLE
Does hparams not return best model?

### ISSUE THREAD

**Issue by leedongjae0611** [tensorflow/tensorboard#2409]
Like GridSearchCV returns best model,
Can I find the best model without looking directly at the results stored on the tensorboard?

**Comment by wchargin** [comment]
Hi @leedongjae0611! The TensorBoard HParams dashboard doesn’t perform
the tuning for you. You can use it to visualize results from whatever
tuner you like. There isn’t a programmatic interface to select the best
model, no, because tuners (like `GridSearchCV`) usually provide that
already.
