### ISSUE TITLE
Tensorboard  in google cloud: Hyparams not showing

### ISSUE THREAD

**Issue by minnielxy** [tensorflow/tensorboard#2415]
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

## Issue description
The hyperparameter_tuning_with_hparams.ipynb runs perfectly fine in Colab. However, after I paste the code to the JupyterLab notebook on google cloud, the hyparams in tensorboard is not showing. 
![image](https://user-images.githubusercontent.com/49539430/60915581-feec0c80-a240-11e9-8253-547121b43af8.png)

**Comment by gowtham-kp** [comment]
@minnielxy Are the scalars and graphs showing?

**Comment by gowtham-kp** [comment]
Closing this issue as this has been in awaiting response for more than 7 days. Please add additional comments and we can reopen the issue again. Thanks!
