### ISSUE TITLE
Drop support for legacy text data format by TF 2.0

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2416]
TensorBoard’s text plugin primarily reads data from events files, like
most other plugins. But it also supports a legacy format that was used
prior to TensorFlow v1.3.0, in which text data is stored in a
`tensors.json` file inside the plugin assets directory.

The text summary TensorFlow op was changed to use the new form in
TensorFlow commit [1e8d1fe6c3], and the dead code path was removed
entirely in [f53579308d].

TensorFlow v1.3.0 was released on 2017-08-16, almost two years ago. We
should drop compatibility with this legacy format as part of the 2.0
release. In the unlikely event that people have critical old-style text
data that needs to be migrated, we can provide a simple data migration
tool.

[1e8d1fe6c3]: https://github.com/tensorflow/tensorflow/commit/1e8d1fe6c3c1221f16c05dd1883f893f291c94d2
[f53579308d]: https://github.com/tensorflow/tensorflow/commit/f53579308d996bbf069eba4ffab68fcc9f6e69f3

**Comment by nfelt** [comment]
+1 to this.  I added it to the 2.0 project tracker.
