### ISSUE TITLE
Image summary: adding more info to tags

### ISSUE THREAD

**Issue by graham63** [tensorflow/tensorboard#2418]
I would like to add more info to the images being displayed. For example, I would like to use a unique tag for all the mis-categorized images for the first epoch, then use the same tag if those images are mis-categorized in the second epoch, so they will be grouped together. I would also like to display info about what category the image belonged in vs what category the program placed it in. Is there any way to do something like this?

**Comment by stephanwlee** [comment]
@graham63 thanks for the issue. I might be mistaken but I believe all you are describing is mostly supported. 

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/summary/image

First off, the `name` parameter (tag) can have slashes to create a grouping of tags (e.g., `foo/bar/baz`) so in an epoch, you can write out images that have unique names but with some kind of grouping.

To group images across epochs, you can pass the parameter `step` (you can pass epoch number there).

Lastly, not sure how robust it is but you can put some info in the `description` parameter. 

Hope this helped.
