### ISSUE TITLE
tensorboard support multiple users at one time 

### ISSUE THREAD

**Issue by TK-blost** [tensorflow/tensorboard#243]
does tensorboard support multiple users for different dirs at one time? 
i have this demand,  is it vary difficult to achieve?

**Comment by weberxie** [comment]
I also have this need.Is there any plan in this area?

**Comment by weberxie** [comment]
sorry, https://github.com/tensorflow/tensorboard/issues/92 seems to be solving the problem.

**Comment by dandelionmane** [comment]
Closing as a duplicate of #92. You can make specific feature requests there :)

**Comment by kd303** [comment]
and 92 is closed, so is this issue :) 

Funny how things work. An actual design document from some aspects of #92 to open things up for community would be great! I wish someone takes up this project, where all interested parties can contribute.
