### ISSUE TITLE
Debugger double stamps when loaded with event files without scalars

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#2437]
Repro step: 
1. `tensorboard --logdir foobar_idontexist --debugger_port 6007`
2. open tensorboard
3. it should open the debugger plugin because it is the only active plugin
4. notice that in the DOM, the scaffold for scalar plugin contains tf_debugger_dashboard.

This is not working as intended and, thus, is a bug.

Note that this is _not_ reproducible for images dashboard (and potentially others).

**Comment by caisq** [comment]
@stephanwlee It turns out: even if tensorboard points to a non-empty logdir, the double stamping still happens if I navigate directly to the "host:port/#debugger" URL. It doesn't happen, if I navigate to the "host:port/#scalar" first and *then* navigate to "host:port/#debugger"

**Comment by stephanwlee** [comment]
I had some time to look into the issue and it is non-trivial to fix it.

Fact 1: after the dashboard registration change, most plugins are registered/make-known-to-tb from the plugins listing. There are few plugins that use the old mechanism and they are "debugger", "profile", "beholder", "whatif", "hparams". 

Fact 2: when plugins_listing request resolves successfully, it can changes `_dashboardData` and the order of the plugin shifts around (debugger gets pushed back while scalars appear at the start)

Fact 3: because we manually stamp/manipulate the DOM, even if Polymer changes dashboardDatum on dom-repeat, it is largely invisible to us.

Problem: at tensorboard start up, the debugger is stamped right away if it is the `activePlugin` as the first dashboard (dom-wise). After the plugins_listing resolve, the scalars become the first plugin and Polymer manipulates the DOM to insert items at the end then update the existing DOM nodes instead of prepending new items and appending new items (this happens because there is no notion of key to dom-repeat). In Polymer v1, the solution would be to use the ArrayUpdateHelper (which facilitates correct usage of Polymer array API ) but Polymer v2/v3 seem to have broken the support for splice events. 

There is no easy way forward but we do have plans to do redo the tf-tensorboard that will address this.

**Comment by caisq** [comment]
@stephanwlee Any ETA to the tf-tensorboard revision? If it's long (after the next release), I'll take some patching measures in the debugger pugin.

**Comment by stephanwlee** [comment]
> Any ETA to the tf-tensorboard revision 

I don't think we want to fix tf-tensorboard with Polymer. We can discuss offline.

**Comment by wchargin** [comment]
This would be fixed by reverting #2340, which was a quick fix for #2338.
If we revert #2340, we should also include a proper solution to #2338,
likely some easy way for plugins to declare that they exist but are
incompatible with some environment state (e.g., no TensorFlow installed,
or no debugger port flags given).

Such a fix might look like:

  - A plugin’s loader can raise a `base_plugin.NotSupportedError` with a
    message that will be captured by TensorBoard and displayed in a
    modal on the frontend.

  - A plugin’s loader can return an `UnsupportedPlugin(message)`, which
    is a valid implementation of `TBPlugin` that only shows the message
    provided at construction time, and whose implementation is provided
    by TensorBoard.

  - Something else?

**Comment by stephanwlee** [comment]
Debugger v1 is no longer shipped with TensorBoard and debugger v2 no longer has the flag.

While it is no possible to reproduce the bug due to change in the feature set, the plugin stamping code is now transferred to Angular where it is tested more and I believe the bug is fixed.
