### ISSUE TITLE
HParams Session Group Name.

### ISSUE THREAD

**Issue by Elysaveth** [tensorflow/tensorboard#2440]
When setting hyper parameter tuning, there is no way to pass a session group name.  following the folder name convention would be helpful to distinguish them.
<img width="1006" alt="HParams Table View" src="https://user-images.githubusercontent.com/48067332/61434444-d4f2b400-a8ea-11e9-9d7e-36b81a4eb164.png">

**Comment by wchargin** [comment]
Hi @Elysaveth! Thanks for the suggestion. We’d [discussed this a bit
before][1] and decided that it was a good idea, but I never got around
to implementing it. I’ll see if I can do that today.

[1]: https://github.com/tensorflow/tensorboard/issues/1998#issuecomment-490944873

**Comment by wchargin** [comment]
Implemented! You can now pass a string `trial_id` kwarg to either the
Keras callback or the direct summary writing functions; for instance:

```python
  hparams_callback = hp.KerasCallback(logdir, hparams, trial_id=trial_id)
```

(I also renamed the “Session Group Name.” column in your screenshot to
“Trial ID”, for clarity.)

This is in today’s nightly build of TensorBoard. If you’d like to try it
out, please first **uninstall** any existing versions of TensorBoard and
then install our nightly package:

```sh
pip uninstall -y tensorboard tb-nightly \
&& pip install 'tb-nightly==1.15.0a20190719'
```

Please feel free to provide feedback!
