### ISSUE TITLE
Tensorboard does not show real-time updates while training without Tensorflow installation.

### ISSUE THREAD

**Issue by AlirezaAlizadeh** [tensorflow/tensorboard#2441]
I have a PyTorch based model and I log some metrics using the `SummaryWriter` from `torch.utils.tensorboard`.

The problem is that if I don't install the Tensorflow, the Tensorboard does not show the updated logs although it refreshes the page (or graphs), and to see the updates, I have to kill and restart the Tensorboard.

The problem got fixed after I installed the Tensorflow.

P.S.
torch version: 1.1.0
tensorboard version: 1.14.0

**Comment by gowtham-kp** [comment]
@AlirezaAlizadeh A few of the packages of Tensorboard is dependent on Tensorflow. So, its necessary to install Tensorflow before running Tensorboard. Hope that helps. Thanks!

**Comment by AlirezaAlizadeh** [comment]
Thank you @gowtham-kp, 
However, seeing the basic metrics logs in Tensorboard on the fly, independent to the installation of Tensorflow, seems to be an essential feature. 
Would that make sense to include it in the future releases of Tensorboard?

**Comment by nfelt** [comment]
@AlirezaAlizadeh can you try uninstalling `tensorboard` and installing `tb-nightly`?  There was a [bug](https://github.com/pytorch/pytorch/issues/20477) in the non-TF reading logic used for pytorch support, and this was fixed in https://github.com/tensorflow/tensorboard/pull/2342 but the fix is only in our nightly releases.

**Comment by gowtham-kp** [comment]
@AlirezaAlizadeh Did you follow the instructions provided by @nfelt. Did it solve the issue?

**Comment by AlirezaAlizadeh** [comment]
@gowtham-kp Thanks for the instruction. However, I tested that and still, we have the same issue.

**Comment by nfelt** [comment]
@AlirezaAlizadeh can you provide a script to reproduce what you're seeing, and the exact version of `tb-nightly` that you were using?

**Comment by AlirezaAlizadeh** [comment]
@nfelt I retried with `tb-nightly-1.15.0a20190806` and the problem is solved with this version. 
unfortunately, I lost the info related to `tb-nightly` in y previous attempt.
Thanks for your consideration.
