### ISSUE TITLE
Inactive dashboards menu is unstyled

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2446]
On HEAD (192ab46d), but not in today’s nightly (1.15.0a20190718):

![Screenshot of inactive dashboards menu](https://user-images.githubusercontent.com/4317806/61502729-db843880-a989-11e9-81f1-89077f69088a.png)

Note the white (not orange) background and the lowercase selected plugin.

Probably related to Polymer 2 changes?

**Comment by stephanwlee** [comment]
Yup, it is Polymer 2 change. Couldn't exactly find the source of the visual regression at the time but I will soon be able to visit this.
