### ISSUE TITLE
Witwidget in JupyterLab

### ISSUE THREAD

**Issue by kouzant** [tensorflow/tensorboard#2454]
Hi there,

I'm experiencing some issues with JupyterLab and WIT visualization.

I have created an Anaconda environment with Python 3.7.3 and JupyterLab v1.0.2. I installed WIT widget as instructed in project's README https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/interactive_inference#how-do-i-enable-it-for-use-in-a-jupyterlab-or-cloud-ai-platform-notebook and run the demo `What_If_Tool_Notebook_Usage.ipynb` notebook. Problem is that the output of the last cell is `WitWidget(config={'model_type': 'classification', 'label_vocab': ['Under 50K', 'Over 50K'], 'are_sequence_exam…` instead of the visualization. I'm using Google Chrome v71.0

In my browser's console I get the following errors:
![Screenshot from 2019-07-23 14-58-45](https://user-images.githubusercontent.com/627083/61714350-e4df1d80-ad5a-11e9-994d-c1bc12048083.png)

I've tried the same with Jupyter Notebook and it works as expected. Is there any known issue with JupyterLab or am I missing something?

Thanks

**Comment by gowtham-kp** [comment]
@kouzant You need to install an other extension:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`
For more detailed information you can refer to the following [issue](https://github.com/jupyterlab/jupyterlab/issues/4855).

**Comment by kouzant** [comment]
I have it installed. In the logs I sent, the first error is that failed to activate `jupyter-widgets`
The extensions I have installed are the following
```
JupyterLab v1.0.2
Known labextensions:
   app dir: /opt/anaconda2/envs/jupyterlab/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.1  enabled  OK
        wit-widget v1.3.0  enabled  OK
```

**Comment by kouzant** [comment]
Sorry, I might have not made myself clear. I didn't mean I've solved my problem. Since the beginning I had installed `jupyter-widgets` but with no luck as you saw from the logs above. Have you managed to reproduce the problem?

**Comment by abhishek11097** [comment]
I am getting the same error and am unable to resolve with jupyter labextension install @jupyter-widgets/jupyterlab-manager. @gowtham-kp  please open the thread again

**Comment by jameswex** [comment]
Thanks, taking a look starting today.

**Comment by jameswex** [comment]
What version of ipywidgets is installed for you, out of curiosity. It must be >=7.5 to use with jupyterlab 1.x.

I just released wit-widget npm package 1.3.1 which updates a dependency version rule so that it might fix your problem. Please ensure you have ipywidgets 7.5 or greater, then install wit-widget 1.3.1 and see if that works. Thanks!

**Comment by kouzant** [comment]
Hi @jameswex I re-installed wit-widget and now it works! Thanks a lot!
I posted above the extensions I've installed https://github.com/tensorflow/tensorboard/issues/2454#issuecomment-514923179

**Comment by psybuzz** [comment]
Based on the last comment, it seems reinstalling the widget with the necessary extensions worked, so closing this issue.

For anyone else who may still be facing the issue, note that the What If Tool has moved into a separate repository, so please file an issue at https://github.com/PAIR-code/what-if-tool/issues/new for reporting issues.
