### ISSUE TITLE
Cannot import TensorBoardProgressWriter

### ISSUE THREAD

**Issue by zenetio** [tensorflow/tensorboard#2474]
I created a conda env where I am using python 3.6.8 and installed tensorboard 1.14.0. When I try to do "from tensorboard import TensorBoardProgressWriter", I receive an error message saying that cannot import TensorBoardProgressWriter.
I am trying to display the model usesd in TranferLearning CNTK example.
In fact the entire example works fine, but when I add the tensorboard code to save the model, I get the error.

**Comment by wchargin** [comment]
TensorBoard doesn’t provide anything called `TensorBoardProgressWriter`,
and never has. It looks like this is [provided by CNTK][cntk]; perhaps
you’re looking for

```python
from cntk.logging import TensorBoardProgressWriter
```

judging from [some examples online][ex]?

[cntk]: https://cntk.ai/pythondocs/cntk.logging.progress_print.html?highlight=tensorboard#cntk.logging.progress_print.TensorBoardProgressWriter
[ex]: https://github.com/Azure/ObjectDetectionUsingCntk/blob/9114d38f2fd7370ebb4c33268afa0d908f0116f6/helpers_cntk.py#L15

**Comment by zenetio** [comment]
You are right! Thanks for the tips.
