### ISSUE TITLE
_Rendezvous: <_Rendezvous of RPC that terminated with details Name resolution failure

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorboard#2477]
Yes i posted in Stackoverflow, will close this as soon as got an answer.
https://stackoverflow.com/questions/57274107/rendezvous-rendezvous-of-rpc-that-terminated-with-details-name-resolution

Versions

-python 2.7.16

-tensorboard: 1.13.1

-tensorflow: 1.13.1

code to reproduce:

```python
import tensorflow as tf
from tensorflow.python import debug as tf_debug

graph = tf.Graph()
with graph.as_default():
  inp = tf.placeholder(tf.float32,shape=(1))
  inp2 = tf.placeholder(tf.float32,shape=(1)) 
  var = tf.math.multiply(inp,inp2)

sess = tf.Session(graph=graph)
with sess.as_default():
  sess = tf_debug.TensorBoardDebugWrapperSession(sess,"localhost:6046")
  with tf.summary.FileWriter('/home/penalvad/stattus4/stattus4-audio-models/notebooks/',graph=graph,session=sess) as writer:
    tf.summary.initialize(graph=self.graph,session=sess)
    sess.run(var,feed_dict={inp:10.0,inp2:2.0})
```

```python
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Name resolution failure"
	debug_error_string = "{"created":"@1564495830.026710193","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1564495830.026708437","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3026,"grpc_status":14}]}"
```

So ... iam doing anything wrong or is this a bug ?
up: the error persists if i put the tensorboard wrapper before the default session context

**Comment by Uiuran** [comment]
is similar to bug above, but its name resolution error, what i have no ideia from where it does pop up

**Comment by caisq** [comment]
@Uiuran Two comments. 

1. The argument you passed to TensorBoardDebugWrapperSession shouldn't be an HTTP address, instead, it should be something like "localhost:6007", with the port being the argument you passed to the `--debugger_port` flag of tensorboard.

2. Make sure you start tensorboard first with the `--debugger_port` flag first, i.e., before you run your tensorflow process.

Please try those and let me know if you have any remaining issues.

**Comment by Uiuran** [comment]
after the removal of http:// the error change

```python
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1564497744.064023798","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Stream removed","grpc_status":2}"
>
```

**Comment by caisq** [comment]
@Uiuran Did you use the grpc port or the http port in the call to `TensorBoardDebugWrapperSession`? Make sure yo use the grpc port.

**Comment by Uiuran** [comment]
Yes i used localhost port 6046 (just edited the python code above). Stills:

```python
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1564499345.717665821","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1564499345.717652178","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1564499345.717553353","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1564499345.717486364","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:6046"}]}]}]}"
>
```
the command of tensorboard server starting, i think is nothing wrong:
tensorboard  --logdir ~/stattus4/stattus4-audio-models/notebooks/ --port 6006 --debugger_port 6064

**Comment by caisq** [comment]
Is it `6046` or `6064`? There may be a typo. Can you check? Also, as I said above, please make sure you start the tensorboard process first.

**Comment by Uiuran** [comment]
yes i made sure, and you are right, i just misstyped, sorry, but the main thing, in the beginning, is that i was using the wrong protocol, thank you, sorry for the stupid mistake
