### ISSUE TITLE
problem with chat bot, tflearn, tensorflow, numpy

### ISSUE THREAD

**Issue by F4azboi** [tensorflow/tensorboard#2497]
my errors are below, my code is - https://pastebin.com/UAACpEMy

C:/Users/iddos.DESKTOP-JTOR36M/AppData/Local/Programs/Python/Python36/python.exe c:/Users/iddos.DESKTOP-JTOR36M/Desktop/work/chatbot.py
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
WARNING: Logging before flag parsing goes to stderr.
W0805 11:08:00.529186 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\summarizer.py:9: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

W0805 11:08:00.530183 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py:25: The name tf.summary.FileWriter is deprecated. Please use
tf.compat.v1.summary.FileWriter instead.

W0805 11:08:00.550131 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\collections.py:13: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0805 11:08:00.565089 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\config.py:123: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

W0805 11:08:00.571074 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\config.py:129: The name tf.add_to_collection is deprecated. Please use tf.compat.v1.add_to_collection instead.

W0805 11:08:00.572072 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\config.py:131: The name tf.assign is deprecated. Please use tf.compat.v1.assign
instead.

W0805 11:08:00.578055 20496 deprecation_wrapper.py:119] From c:/Users/iddos.DESKTOP-JTOR36M/Desktop/work/chatbot.py:67: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

W0805 11:08:00.583042 20496 deprecation.py:506] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\initializations.py:174: calling TruncatedNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0805 11:08:00.635192 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\optimizers.py:238: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

W0805 11:08:00.646162 20496 deprecation.py:506] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\objectives.py:66: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-08-05 11:08:00.681585: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
W0805 11:08:00.730447 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\summaries.py:46: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0805 11:08:00.772335 20496 deprecation.py:323] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0805 11:08:00.935916 20496 deprecation_wrapper.py:119] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py:134: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0805 11:08:01.142364 20496 deprecation.py:323] From C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
---------------------------------
Run id: U1BJHT
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 26
Validation samples: 0
--
Traceback (most recent call last):
  File "c:/Users/iddos.DESKTOP-JTOR36M/Desktop/work/chatbot.py", line 78, in <module>
    model.load("model.tflearn")
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1278, in restore
    compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: C:\Users\iddos.DESKTOP-JTOR36M\Desktop\work\model.tflearn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/iddos.DESKTOP-JTOR36M/Desktop/work/chatbot.py", line 80, in <module>
    model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 216, in fit
    callbacks=callbacks)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 339, in fit
    show_metric)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 816, in _train
    tflearn.is_training(True, session=self.session)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\config.py", line 95, in is_training
    tf.get_collection('is_training_ops')[0].eval(session=session)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 731, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 5579, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\iddos.DESKTOP-JTOR36M\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by nfelt** [comment]
Sorry, but I don't see anything in your stacktrace to indicate that this is a TensorBoard-specific issue, and we only use this issue tracker for bugs or feature requests for TensorBoard.  If you're looking for general advice about getting this code to work, I'd recommend trying StackOverflow.
