### ISSUE TITLE
Polymer 2.0

### ISSUE THREAD

**Issue by BinhangYuan** [tensorflow/tensorboard#251]
Hi!
I am learning how the code is constructed. I think the html is applying the tool of Polymer. It seems like Polymer 2.0 is available, is there any plan to move from the current implementation to polymer 2.0?
Thanks!

**Comment by wchargin** [comment]
Correct: we use Polymer 1.x. We don't currently have any plans to switch to Polymer 2.0. (We may eventually be required to, but until then we'll be on 1.x.)

I'm closing this as it answers your direct question, but feel free to re-open if you have a followup.

**Comment by BinhangYuan** [comment]
Thanks for you reply!

**Comment by Khyta** [comment]
Hey!
Does tensorboard support polymer 3.x? Because I'm developing a TesorBoard plugin.
Thanks!

**Comment by stephanwlee** [comment]
@Khyta nope, not yet. We do intend to upgrade someday but we do not have a concrete plan around it.

**Comment by wchargin** [comment]
Resurrecting this issue for tracking purposes. We currently plan to
migrate to Polymer 2 by end of Q2 2019; after that, we might migrate to
Polymer 3.

**Comment by krish-penumarty** [comment]
@wchargin - Is there a reason to move to Polymer 2 rather than directly go to Polymer 3? Just wondering what the justification for that was?

**Comment by stephanwlee** [comment]
@krish-penumarty it is for less code change.

Polymer 1 -> Polymer 2: introduces Shadow DOM v1
Polymer 2 -> Polymer 3: remove HTML import and Vulcanization.

In order to go from Polymer 1 to Polymer 3, we'd have to change our code to make it Shadow DOM v1 compliant and remove HTML imports at the same time which would make the diff overwhelming.

**Comment by krish-penumarty** [comment]
@stephanwlee Thank you for sharing!

**Comment by psybuzz** [comment]
Closing this issue as TensorBoard's Polymer code migration to Polymer 3 is complete, tracked in https://github.com/tensorflow/tensorboard/issues/3887.
