### ISSUE TITLE
Change CI from tf-nightly-2.0-preview to just tf-nightly

### ISSUE THREAD

**Issue by nfelt** [tensorflow/tensorboard#2511]
Follow-up work from #2507: once `tf-nightly` uses the TF 2.0 API and behavior, we should switch to that instead of `tf-nightly-2.0-preview`

**Comment by wchargin** [comment]
Yes; thanks. My understanding is that there will be an intermediate
period where both work, so there won’t be a forced simultaneous rollout.

**Comment by nfelt** [comment]
Fixed by #2722
