### ISSUE TITLE
Dynamic projector plugin does not load in Firefox

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2536]
Can repro on HEAD (1c9412d1) and nightly (2019-08-09) with Firefox 68.

Selecting the “projector” tab renders an empty pane and an error in the
console:

> TypeError: error loading dynamically imported module

Intriguingly, this error has virtually no documentation on the internet.
Its Firefox-internal message ID is `JSMSG_DYNAMIC_IMPORT_FAILED`, and,
according to [the changeset that introduced it][cs] in January 2019, it
“covers all import() failures that don't throw a JS exception”. A web
search turns up no relevant discussion threads mentioning either the
error text or the error code, other than our own #2533.

[cs]: https://hg.mozilla.org/mozilla-central/rev/43a79c5e38f4

**Comment by wchargin** [comment]
This is looking to be a bit of a Heisenbug: I prepended a `debugger;`
statement to the iframe script contents (in `tf-tensorboard.html`), and
the bug still repros but only when the console is closed. If the console
is open, the module resolves correctly, but has the wrong behavior
because the `baseURI` setting did not propagate for some reason; there
isn’t even a `base` element in the frame’s `head`.

(Firefox source tree is still cloning…)

**Comment by wchargin** [comment]
The unique occurrence of `JSMSG_DYNAMIC_IMPORT_FAILED` is in the error
case of [`ScriptLoader::FinishDynamicImport`][fdi], which is itself only
called from other functions in that source file. I’m not familiar with
the Gecko codebase, but from what I can tell it looks like the
underlying cause of the error is squashed, and in a quick retrograde
analysis most of the possible failure conditions aren’t even accompanied
by a debug-log statement. The `TypeError` in the rejected promise also
doesn’t have any information other than the message.

The error also persists if I replace the imported module contents with a
simple `console.log('hello?');` and add `Access-Control-Allow-Origin: *`
as a response header.

[fdi]: https://phabricator.services.mozilla.com/source/mozilla-central/browse/default/dom/script/ScriptLoader.cpp;1ac73550a2e68cdb0f12ed6870e744673ae22351$1016

**Comment by wchargin** [comment]
Minimal repro:

```html
$ cat index.html
<!DOCTYPE html>
<meta charset="utf-8" />
<body>
  <script>
    const iframe = document.createElement("iframe");
    document.body.appendChild(iframe);
    const subdocument = iframe.contentDocument;
    const script = subdocument.createElement("script");
    script.textContent = "import('./mod.js')";
    subdocument.body.appendChild(script);
  </script>
</body>
```

```javascript
$ cat mod.js
console.log("hello from mod");
```

```sh
$ python3 -m http.server
```

Then visiting `index.html` gives the same “TypeError: error loading
dynamically imported module”, even though the network request for
`mod.js` succeeds with 200 and the right content, and even though adding
`import("./mod.js")` to the top of the `script` element in `index.html`
properly imports the module.

Replacing the relative path with `http://localhost:8000/mod.js` does not
solve the problem.

Again, using `script.textContent = "debugger; import('./mod.js')"` stops
the problem from occurring: after just pressing “Resume”, the import
completes and the module executes without error.

**Comment by wchargin** [comment]
Filed a Firefox bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1573262>

**Comment by ceevee830** [comment]
Hi @wchargin , 
We're seeing this issue crop in the field using Firefox browser:
Specific error message: "**Uncaught (in promise) TypeError: error loading dynamically imported module**"
Unconfirmed report is that this happens in Safari browser as well.

Synopsis:
- GRAPHS plugin works fine.
- DLPROF plugin is based on the `example_basic` plugin.

Can you give us a brief update on this issue's status?
Mozilla's bug has gone dormant: https://bugzilla.mozilla.org/show_bug.cgi?id=1573262

Any workaround would be appreciated.  Perhaps there is another plugin similar to example_basic that works in Firefox?  

![image](https://user-images.githubusercontent.com/5108675/98592063-05035a80-2286-11eb-9b6a-4a463d066ab2.png)

Thanks,
-Chris

**Comment by wchargin** [comment]
The projector plugin uses roughly the same setup as `example_basic`, and
it loads fine for me in latest TensorBoard and Firefox 82. Can you check
whether the projector plugin loads for you or if you see the same error?

You will need to be on TensorBoard 1.15.0 or higher to pick up #2540.

**Comment by wchargin** [comment]
If you can reproduce this with the projector plugin, could you please
file a new issue and fill out the template, including your versions of
both TensorBoard and Firefox?

**Comment by ceevee830** [comment]
Hi @wchargin How can I easily enable the projector plugin to see if it loads into TB as requested?  (I do not see it in my navbar or the droplist on the far-right on navbar.)

**Comment by wchargin** [comment]
The projector plugin is part of a standard TensorBoard installation, and
it should appear in the list of inactive plugins even if you’re pointing
at an empty log directory. Here’s its empty view in Chrome and Firefox:

![Screenshot of the projector plugin’s “No checkpoint was found” screen
in Chrome and Firefox, with a terminal running `tensorboard --logdir
/tmp/nothing/to/see/here`][ss]

[ss]: https://user-images.githubusercontent.com/4317806/98718440-4f96dc80-2343-11eb-88b9-895f78282ee1.png

**Comment by ceevee830** [comment]
Hi William,

I did a pip install on TB 1.15 and launched the server:
```
root@d5d64f5f97cf:/workspace# pip install tensorboard==1.15.0
Collecting tensorboard==1.15.0
  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 12.0 MB/s
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (3.13.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (0.35.1)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (1.17.3)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (1.13.0)
Requirement already satisfied: grpcio>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (1.32.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (1.0.1)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (0.10.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (50.3.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard==1.15.0) (3.2.2)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from markdown>=2.6.8->tensorboard==1.15.0) (2.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard==1.15.0) (3.2.0)
Installing collected packages: tensorboard
Successfully installed tensorboard-1.15.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
root@d5d64f5f97cf:/workspace#
root@d5d64f5f97cf:/workspace#
root@d5d64f5f97cf:/workspace#
root@d5d64f5f97cf:/workspace#
root@d5d64f5f97cf:/workspace# tens^C
root@d5d64f5f97cf:/workspace# tensorboard --logdir /tmp/gold_event_files/
2020-11-12 23:56:55.936980: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
TensorBoard 1.15.0 at http://d5d64f5f97cf:6006/ (Press CTRL+C to quit)
```

The I launched TB, l clicked on the PROJECTOR plugin and saw the same error in the browser console.
![image](https://user-images.githubusercontent.com/5108675/99011358-c4634580-2500-11eb-8982-d514dccfb2ac.png)

@wchargin Could you re-open this bug?  And provide or recommend a fix or workaround?  I'm about to head into a code freeze, and this problem is happening in the field.  I'd like to get a fix ASAP.  Thanks!

**Comment by ceevee830** [comment]
jsyk, the FF version I'm using is 82.0.3 (64-bit).

**Comment by stephanwlee** [comment]
I can reproduce this with the minimal repro.

In 1.15, we were creating an iframe plugin by injecting a script to an iframe.

https://github.com/tensorflow/tensorboard/blob/ab7f72a643fb8e9073f857a7d6579d016bbfd223/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L894-L912

This strategy used to work in Firefox 82- and it no longer works after 82+.

Repro:
```html
<!-- index.html -->
<body>
  <iframe></iframe>
  <script>
    (function(){
      const iframe = document.querySelector('iframe');
      const subdocument = iframe.contentDocument;
      const script = subdocument.createElement('script');
      const moduleString = JSON.stringify('/index.js');
      script.textContent = [
`setTimeout(() => {
  import(${moduleString})
    .then(
      () => void console.log('iframe loaded'),
      () => void console.log('iframe failed'),
    );
}, 0)`,
      ];
      subdocument.body.appendChild(script);
    })();
  </script>
  <script>
    (function(){
      setTimeout(() => {
        import('/index.js')
          .then(
            () => void console.log('setTimeout loaded'),
            () => void console.log('setTimeout failed'),
          );
      }, 1000);
    })();
  </script>
</body>
```

On your terminal:
```sh
# Inside the folder that has above index.html
$ touch index.js
$ python3 -m http.server 8000
```

You will notice that we get something like below in Firefox 82+.

![image](https://user-images.githubusercontent.com/2547313/99123265-b242df00-25b4-11eb-9e71-815fb175e755.png)

Now, on the remediation side, there is no few LOC solution; the proper solution will require us to do something akin to current solution which is introduced in TensorBoard 2.1+. This change requires backend to serve the plugin_entry.html which is not possible in 1.15 as is.

https://github.com/tensorflow/tensorboard/blob/66d10d7a89af00c1d62bbb1dddb7c57ee8a10dd1/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L864-L871
https://github.com/tensorflow/tensorboard/blob/4e2a918a0559514a633c3a29ac6238fed4b72ed5/tensorboard/webapp/plugins/plugins_component.ts#L213-L224

Unfortunately, we will not retroactively apply the patch to fix the Firefox issue so your best option would be to upgrade to TensorBoard 2.4+ (or at the very least, 2.1).

**Comment by ceevee830** [comment]
@stephanwlee , thanks for the repro details.  It sounds to me you're saying that my plugin, Google's own Projector plugin, and all those plugins in the world that used your example plugin as basis for their plugin are no longer compatible with TensorBoard v1.15?  And there is nothing you can do to mitigate this incompatibility? Please confirm I got that right.

**Comment by stephanwlee** [comment]
Yes, you are correct. Except for upgrading TensorBoard and using chromium
browser, there is no other way.
