### ISSUE TITLE
Can't reload data without TensorFlow installation

### ISSUE THREAD

**Issue by linshuliang** [tensorflow/tensorboard#2553]
I make use of tensorboardX to log data, without TensorFlow installation, TensorBoard run with the reduced feature set. The frontend webpage can't reload data to refresh.

## Enviroment setting
Machine : MacBook Pro 
Machine OS : macOS 10.14.6

Python Environment

```
conda create --name tensorboardX_tbnightly python=3.6
conda activate tensorboardX_tbnightly
conda install tensorboardX
conda install tb-nightly
```

The Version of tb-nightly is  1.15.0a20190814.

## My program to log data

```python
# coding=utf-8
import time
from tensorboardX import SummaryWriter

writer = SummaryWriter(logdir='./log/')

for i in range(6000):
    writer.add_scalar('y=2x', i * 2, i)
    time.sleep(0.1)
    print("step:", i)

writer.close()
```
## The command to launch tensorboard

```
tensorboard --logdir log --host 0.0.0.0 --port 6066 --reload_interval 5
```

I use **Chrome**,  the frontend webpage only display the data at the moment of launch, but do not reload data to refresh.

## Compromised Solution and Guess

The method I choose to fix this problem is to touch a `reload.sh`，and run `reload.sh` to refresh.

```
#!/bin/bash

set -x

while true
do
    gtimeout 30s tensorboard --logdir log --host 0.0.0.0 --port 6066 --reload_interval 5
    ps -ef | grep tensorboard | grep -v grep | awk '{print $2}' |  xargs kill -9
done
```

The solution I find is not users friendly. So I dig into the code of [class PyRecordReader_New](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py). I am not sure whether the bug locates here.

Look forward to your kind reply.

**Comment by stephanwlee** [comment]
Hey @linshuliang, thanks for opening an issue.

In my preliminary attempt to debug the issue, I was able to reproduce the issue.

Few things I tried:
- I did increase the verbosity in TensorBoard and it does seem to go through the reload routine.
- Was not able to reproduce the issue with tf 2.0 (TensorBoard is run in virtualenv _without_ tensorflow)

In virtualenv with tensorflow
```py
import time
import tensorflow as tf

writer = tf.summary.create_file_writer(logdir='./log/')

with writer.as_default():
  for i in range(6000):
    tf.summary.scalar('y=2x', i * 2, i)
    writer.flush()
    time.sleep(1)
    print("step:", i)
```
In virtualenv without tensorflow but just tb-nightly
```bash
$ tensorboard --logdir log
$ pip freeze
absl-py==0.7.1
enum34==1.1.6
futures==3.3.0
grpcio==1.22.0
Markdown==3.1.1
numpy==1.16.4
pkg-resources==0.0.0
protobuf==3.9.1
six==1.12.0
tb-nightly==1.15.0a20190815
tensorboardX==1.8
Werkzeug==0.15.5
```

@nfelt would you know how tensorboardX, which of course we do not maintain, differs from tf 2.0 when writing summaries?

**Comment by linshuliang** [comment]
It is not only a matter of writer, but also a matter of read.

**Comment by linshuliang** [comment]
I have found the bug in tensorboardX, It doesn't `writer.flush()`，so the RecordReader can't find the new data.

We just need to add a new API in tensorboardX , which do flush in fixed time.

Thanks.

**Comment by stephanwlee** [comment]
Ok, it sounds like the bug requires no action item on our part. If I understood you incorrectly, please feel free to reopen the issue, thanks!
