### ISSUE TITLE
Enable dynamic plugin in cloned TB 1.14

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#2554]
We have branched TB v1.14 and added our extensions to the GRAPHS plugin and added our new custom plugin.  This feature request is to try and get the new dynamic plugin working in our version of TB v1.14.  

From a previous issue, I understand that `The changes are fairly cross-cutting across core parts of TensorBoard—the plugin base BasePlugin and TBContext, the backend core routing
and serving logic, the frontend tf-tensorboard shell, etc.—so I can’t
just send you a file or two to add wholesale to your tree`

At this point we cannot clone TB nightly to get the dynamic plugin, and apparently it is not easy to back port the dynamic plugin into the most recent released version of TB 1.14.  @GalOshri What do you recommend?

**Comment by ceevee830** [comment]
Hi @GalOshri , is there anything actionable I can do this week?

**Comment by nfelt** [comment]
Hi Chris - the gist of the previous comment was that TB 1.14 wasn't meant to ship with stable support for dynamic plugins.  You're of course welcome to try to get it working, but our recommendation would be to update your branch to pull in the more recent changes.

Is there a reason that you can't work with TB nightly / HEAD?  There will also be a TB 1.15 release, the last in TF 1.x, in the new few weeks if that makes any difference.

**Comment by ceevee830** [comment]
Hi @nfelt, thanks.  Waiting for TB v1.15 is doable from our side.  Just to confirm: the dynamic plugin will be available in TB v1.15?  

Also, in my travels I have heard that jQuery is available in the dynamic plugin architecture.  I see references to jQuery but do not see any examples of jQuery.  Do you have an example I can view?

**Comment by nfelt** [comment]
The minimal support for dynamic plugins should all be there in 1.15, yes.

Dynamic plugins can essentially use any library because they're hosted in an iframe and you can control the source of the iframe: https://github.com/tensorflow/tensorboard/tree/master/tensorboard/examples/plugins/example_basic#frontend-how-the-plugin-visualizes-your-new-data

I don't believe we have an example using jQuery, but it wouldn't be any different from using jQuery in a regular context.

**Comment by ceevee830** [comment]
Hi @nfelt the example in `tensorboard/examples/plugins/example_basic` is a javascript file that creates the DOM on the fly.  Do you have any suggestions or guidance to enable jQuery using an HTML file?

**Comment by stephanwlee** [comment]
@ceevee830 we generally wanted to avoid preferring a library over another since it gives other impression that the dynamic plugin only supports that library. You should be able to use any conventional way of building JavaScript to embed jQuery to your liking. 

I would recommend you to use [jQuery from NPM](https://www.npmjs.com/package/jquery) and use [webpack](https://webpack.js.org/guides/getting-started/ to build

**Comment by ceevee830** [comment]
I'm asking how to get TB launch HTML files in the dynamic plugin, not the javascript file.  I did not mean to imply that I'm asking for a different library.

So I'm looking at the projector plugin, since [that points to an `index.js` file](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/tf_projector_plugin/index.js#L29), just like the example_basic plugin.  It is attempting to load an HTML file into an iFrame.  The name of the HTML it is loading is called `projector_binary.html`.  
1) Is this how I can get TB to launch an HTML file in the dynamic plugin?  And I can load jQuery from inside that HTML file?
2) I do not see `projector_binary.html` anywhere in the TB master branch.  Please advise.
3) Do you have a timeframe for when TB v1.15 will be released?

**Comment by wchargin** [comment]
An easy way to use standard HTML files without diving into the whole
Webpack and NPM ecosystem is to load the HTML file in an iframe, and
create the iframe inside the JS as in the projector examlpe that you
linked to.

The `projector_binary.html` file is generated dynamically by our build
system, and probably isn’t what you want to emulate. Instead, create a
normal `my_index.html` file in your plugin directory, and add a route in
your plugin to serve that as a static file, like this:
https://github.com/tensorflow/tensorboard/blob/87d2927da934f9926e3092de1f9aed3b620f69e7/tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py#L55-L61

TensorBoard 1.15 will be released after TensorFlow 1.15rc0 is released
and before TensorFlow 1.15 final is released. We’re not sure when that
will be.

**Comment by ceevee830** [comment]
Thanks William.  Getting closer, but not out of the woods.  
The paragraph above your code snippet says to serve up the html, but the code serves up the index.js.  So I ported references to the index.js to my_index.html, and changed the content_type accordingly.  
```  @wrappers.Request.application
  def _serve_js(self, request):
    del request  # unused
    filepath = os.path.join(os.path.dirname(__file__), "static", "my_index.html")
    with open(filepath) as infile:
      contents = infile.read()
    return werkzeug.Response(contents, content_type="text/html")
```
But this error message appears:
`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`
What am I missing?

**Comment by wchargin** [comment]
You’ll need one handler to serve your JS entry point, `index.js`. This
should serve as MIME type `application/javascript`, and the contents
should be an ES module that creates an iframe in the page, as in the
projector plugin entry point that you found.

You will need a separate handler to serve your HTML entry point,
`index.html`. This should serve as MIME type `text/html`, and the
contents can be anything that you like.

**Comment by rmothukuru** [comment]
@ceevee830 ,
Can you please respond to @wchargin's comment so that we can work towards closure of your issue. Thanks!

**Comment by ceevee830** [comment]
ping @wchargin @GalOshri

**Comment by wchargin** [comment]
### `example_plugin.py`

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

from tensorboard.plugins import base_plugin
import werkzeug


class ExamplePlugin(base_plugin.TBPlugin):
  plugin_name = "example"

  def __init__(self, context):
    self._multiplexer = context.multiplexer

  def is_active(self):
    return True

  def get_plugin_apps(self):
    return {
        "/index.js": self._serve_js,
        "/index.html": self._serve_index_html,
        "/jquery-3.4.1.dev.js": self._serve_jquery,
    }

  def frontend_metadata(self):
    return base_plugin.FrontendMetadata(es_module_path="/index.js")
  
  def _serve_static_file(self, filename, content_type):
    filepath = os.path.join(os.path.dirname(__file__), "static", filename)
    with open(filepath) as infile:
      contents = infile.read()
    return werkzeug.Response(contents, content_type=content_type)

  @werkzeug.Request.application
  def _serve_js(self, _unused_request):
    return self._serve_static_file("index.js", "application/javascript")

  @werkzeug.Request.application
  def _serve_index_html(self, _unused_request):
    return self._serve_static_file("index.html", "text/html")

  @werkzeug.Request.application
  def _serve_jquery(self, _unused_request):
    return self._serve_static_file(
        "jquery-3.4.1.dev.js",
        "application/javascript",
    )
```

### `static/index.js`

```javascript
export async function render() {
  // Bootstrap: main contents are in `index.html` and friends.
  const iframe = document.createElement("iframe");
  iframe.src = "./index.html";
  iframe.style.width = "100%";
  iframe.style.height = "100%";
  document.body.appendChild(iframe);
}
```

### `static/index.html`

```html
$ cat tensorboard_plugin_example/static/index.html
<!DOCTYPE html>
<html>
  <body>
    <script src="./jquery-3.4.1.dev.js"></script>

    <div id="target"></div>
    <script>
      $("body").prepend($("<h1>").text("Hello, JQuery!"));
      $("#target").text("Look at me go!");
    </script>
  </body>
</html>
```

### `static/jquery-3.4.1.dev.js`

(actual JQuery bundle)

**Comment by wchargin** [comment]
There are nicer ways to factor this, but this should get you started.

**Comment by ceevee830** [comment]
Great thanks.

**Comment by ceevee830** [comment]
Works great!  See two jQuery plugins below (DataTables and CanvasJS)

![image](https://user-images.githubusercontent.com/5108675/64283227-dcf2cb80-cf0b-11e9-85ea-153c57cedb3d.png)

**Comment by ceevee830** [comment]
I understand this will be available in TB v1.15.  Do you have a projected release date?  Ballpark date is ok.

**Comment by wchargin** [comment]
Very nice!

> I understand this will be available in TB v1.15. Do you have a
> projected release date? Ballpark date is ok.

I don’t; sorry. It looks like TensorFlow [has cut an `r1.15` release
branch][1], and that cherry-picks are still landing onto it. There
hasn’t been a release candidate yet; it’ll show up [on PyPI][2] when
it’s released. TensorBoard 1.15 will be released shortly thereafter.
That’s all I know.

[1]: https://github.com/tensorflow/tensorflow/tree/r1.15
[2]: https://pypi.org/project/tensorflow/#history

**Comment by wchargin** [comment]
Looks like this is working—thanks for checking back in!

**Comment by ceevee830** [comment]
Thanks for your help William!

**Comment by wchargin** [comment]
TensorFlow 1.15.0rc0 is out, so we’ll release TensorBoard 1.15 soon:
<https://pypi.org/project/tensorflow/1.15.0rc0/>
