### ISSUE TITLE
hparams plugin still depends on Tensorflow

### ISSUE THREAD

**Issue by thincal** [tensorflow/tensorboard#2562]
From `tensorboard/plugins/hparams/metrics.py`, it still uses the make_ndarray from tensorflow. But this function actually is provided by the `tensorboard/util/tensor_util.py` already.

**Comment by wchargin** [comment]
Hi @thincal! You’re right—it looks like that usage of `make_ndarray` is
the _only_ remaining dependency on TensorFlow. I’ll be happy to change
this over to `tensor_util` as you describe and drop the dependency on
TensorFlow.

Note that the writing APIs are already available without TensorFlow: you
can import `tensorboard.plugins.hparams.summary_v2` in your training
code without a TensorFlow dependency.

Thanks for bringing this to our attention!
