### ISSUE TITLE
The time to release TensorBoard 1.15

### ISSUE THREAD

**Issue by linshuliang** [tensorflow/tensorboard#2572]
May I ask a question?

When will the new version（TensorBoard 1.15） be released?

**Comment by stephanwlee** [comment]
@wchargin I believe you were working on this. What's the status?

**Comment by wchargin** [comment]
TensorBoard releases in lockstep with TensorFlow. Once a TensorFlow
release candidate is pushed, TensorBoard will push a full release, which
the TensorFlow release will depend on.

**Comment by wchargin** [comment]
TensorFlow 1.15.0rc0 is out, so we’ll release TensorBoard 1.15 soon:
<https://pypi.org/project/tensorflow/1.15.0rc0/>
