### ISSUE TITLE
How to store weights with plugin name in keras model ( in tf.layers model i was doing with summary but keras had callback for storing weight )

### ISSUE THREAD

**Issue by sahilpasricja** [tensorflow/tensorboard#2620]
System information

OS Platform and Distribution - Linux Ubuntu 18.04:
TensorFlow version (or github SHA if from source):1.14.0
In my existing model, i am using CNN model with tf.layers

```py
def mnist_cnn(inputs):

input_layer = tf.reshape(inputs, [-1, 28, 28, 3])

# Convolutional Layer #1
conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=32,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu,
      name="conv1",
)
  


# Pooling Layer #1
pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

# Convolutional Layer #2 and Pooling Layer #2
conv2 = tf.layers.conv2d(
      inputs=pool1,
      filters=64,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)

 **weights_1_array = np.zeros((786, 28, 28, 32))**
**conv_kernel_1 = tf.nn.conv2d(conv1, weights_1_array, [1, 4, 4, 1], padding='SAME')


**kernel = tf.get_collection(tf.GraphKeys.VARIABLES, 'conv1/kernel')[0]



pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)

# Dense Layer
pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])
dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
dropout = tf.layers.dropout(inputs=dense, rate=0.4)

# Logits Layer
outputs = tf.layers.dense(inputs=dropout, units=10)
```

### In TF layers model, the solution was 
And i used to write logs using summary

```py
tensor_summaries = list(
    map(
        lambda graph_node: tf.summary.tensor_summary(
            graph_node.name,
            graph.get_tensor_by_name(graph_node.name + ':0'),
            summary_metadata=tf.SummaryMetadata(
                display_name=graph_node.name,
                summary_description=description,
                plugin_data=tf.SummaryMetadata.PluginData(
                    plugin_name=PLUGIN_NAME)),
            collections=collections), tensor_ops))
```

Within this summary, there was a feature to write plugin name, this plugin name is then used by my custom tensor board to identify data from my plugin.

With tf keras , we have callbacks like save.model to store weight but that doesn't give an option to write plugin name this makes it impossible for tensorboard to identify data for my plugin,

Is there any way to write logs with plugin name using call back?

**Comment by stephanwlee** [comment]
I have roughly reformatted the issue.

Hi @sahilpasricja, thanks for raising the issue. It sounds like the question should be directed to the maintainer of Keras as getting the weight from the Keras Layers is a generic question. Would you be able to raise the issue to https://github.com/tensorflow/tensorflow? 

Also, for my information, would you be able to use checkpoint to get the weights? https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L791

**Comment by gowthamkpr** [comment]
@sahilpasricja I am closing this issue as it belongs to tensorflow.keras. Please raise the issue in https://github.com/tensorflow/tensorflow. Thanks!

**Comment by sahilpasricja** [comment]
@stephanwlee, @gowthamkpr   Thanks for the response.
Callback is a solution for storing weights but we need to add plugin name with these weights so that when tensorboard runs, the plugin I made can find its relevant data in logs using plugin name (refer to the summary function in my code above ).Call back is not at all an option unless it has a feature to store plugin name ( which as per my finding do not exist).

About this question not belonging here- I am not sure of that either but the solution is either 
1) Tensor flow having some method to store plugin name  for Keras OR
2) Tensor board having some new conventions to fetch data from logs without plugin name 

If 1st doesn't hold, then question belongs exactly here :).
If you also believe the same , please reopen this issue

**Comment by stephanwlee** [comment]
> new conventions to fetch data from logs without plugin name

May I ask what kind of convention you have in mind?

**Comment by sahilpasricja** [comment]
let's discuss in a very basic way.

The only way for tensorboard and tensroflow to communicate is through log data.
In my existing model, I used to store tensors with metadata as plugin name and then tensroboard reads data with given plugin_name and publishes it.

Now what I meant by convention is some other way that tensorboard has to do with without plugin name.
