### ISSUE TITLE
How to manually ftech weights from tensor in TF.Keras ( Same can be done in tf.layers model with help of (op:VariableV2)) 

### ISSUE THREAD

**Issue by sahilpasricja** [tensorflow/tensorboard#2621]
Hello, 
For my tensorboard plugin, i need to store weights with plugin name and then fetch this data using the plugin name while the tensor board is running, 

I was using TFconv model with tf.keras layers and to store weights, I used summary function where I was able to fetch the weights using the following line
tensor_ops = list(filter(lambda graph_node: graph_node.op == "VarHandleOp", graph.as_graph_def().node))
 

In TF.keras, VariableV2 doesn't exist any more, what is the alternative for that?

I need to fetch all weights from tf.default.graph

**Comment by stephanwlee** [comment]
Hi @sahilpasricja, that sounds like TensorFlow/Keras question. It would be great if you direct the question to https://github.com/tensorflow/tensorflow.
