### ISSUE TITLE
Re-enable mesh test 

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#2624]
In the latest TensorFlow, `@tf.function` broke due to missing symbols in gast.

TensorFlow describes its dependency on [gast with `>=0.2.0`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L57) and the new version 0.3.x removed symbols like `Str`, `Num`, etc... This breaks the autograph and below it will even break a simple function like below:
```py
import tensorflow as tf
@tf.function
def foo():
   return 1 + 2

foo()
```

(if you increase the verbosity, it will tell you that it is missing the symbol). 

Currently, the `//tensorboard/plugins/mesh:summary_v2_test` is the only one that uses `@tf.function` in TensorBoard and is impacted. 

We can re-enable the test when (1) tf pins the version of gast or (2) TF autograph uses the correct symbols from gast.

**Comment by nfelt** [comment]
I'm confused by this issue - the mesh summary_v2 tests aren't the only one using @tf.function, several others do as well:

https://github.com/tensorflow/tensorboard/blob/1b623e7c914558b0e521d946fccee2b8ebdb53b9/tensorboard/plugins/scalar/summary_test.py#L192
https://github.com/tensorflow/tensorboard/blob/1b623e7c914558b0e521d946fccee2b8ebdb53b9/tensorboard/plugins/histogram/summary_test.py#L218
https://github.com/tensorflow/tensorboard/blob/1b623e7c914558b0e521d946fccee2b8ebdb53b9/tensorboard/plugins/text/summary_test.py#L209

As far as I know the mesh summary test was basically copied from those, so it's surprising to me that it would break and not those ones.  What exactly was the failure mode?

**Comment by stephanwlee** [comment]
You are correct and autograph in those files indeed fails. Do note that even if autograph fails, it seems to run in some kind of fixture of graph mode / eager mode.

The type of error we are getting is unique to the mesh plugin and it is because of the conditional.
```
    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.     
```
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/mesh/summary_v2.py#L125

I tried to debug what kind of code is actually executed under such failure (because pure eager works) but I could not figure it out in an hour that I used to investigate.

**Comment by wchargin** [comment]
Test passes locally for me; tensorflow/tensorflow#32319 is closed.

**Comment by mihaimaruseac** [comment]
Is this stale now?

**Comment by wchargin** [comment]
The issue isn’t stale because the test is still disabled on our end, and
appears to [still be broken on CI][ci]. This is probably because our 1.x
nightlies are pinned to 2019-08-16, which doesn’t have the strict `gast`
dep, so we’re still pulling in `gast==0.3.2`. Explicitly pinning `gast`
in our Travis config will probably resolve the issue.

[ci]: https://travis-ci.com/tensorflow/tensorboard/jobs/245159449

**Comment by wchargin** [comment]
Actually, we could probably just change our `tf-nightly` pin to the
`tensorflow==1.15.0rc3` release, which does have the strict `gast` dep
([per Mihai’s comment][gast-1.15]).

[gast-1.15]: https://github.com/tensorflow/tensorflow/issues/32319#issuecomment-537568070

**Comment by mihaimaruseac** [comment]
Oh, in retrospect, we should have pinned our nightly dependency

**Comment by wchargin** [comment]
@mihaimaruseac Thanks for the ping! Fixed now.
