### ISSUE TITLE
Web tests are flaky when starting local server

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2643]
I’ve seen this spurious failure twice in the past two days, which is
also around the time that I upgraded to Bazel 0.29.1:

```
==================== Test output for //tensorboard/components/tf_storage/test:test_chromium:
<printenv output snipped>
2019/09/11 23:02:23 launching HTTP server at: HOSTNAME:38247
2019/09/11 23:02:23.193029 Listening on :33319
E
======================================================================
ERROR: test (tensorboard.functionaltests.wct_test_driver.WebComponentTesterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/HOMEDIR/.cache/bazel/_bazel_wchargin/52a95bbdd50941251730eb33b7476a66/sandbox/linux-sandbox/2414/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/components/tf_storage/test/test_chromium.runfiles/org_tensorflow_tensorboard/tensorboard/functionaltests/wct_test_driver.py", line 117, in setUp
    "Did not find listening-on line in output:\n%s" % full_output)
ValueError: Did not find listening-on line in output:
'Sep 11, 2019 11:02:25 PM io.bazel.rules.closure.webfiles.server.WebfilesServer run\n'
'SEVERE: Webfiles server died\n'
'java.net.BindException: Address already in use (Bind failed)\n'
'\tat java.base/java.net.PlainSocketImpl.socketBind(Native Method)\n'
'\tat java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)\n'
'\tat java.base/java.net.ServerSocket.bind(ServerSocket.java:381)\n'
'\tat java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)\n'
'\tat java.base/javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)\n'
'\tat io.bazel.rules.closure.webfiles.server.NetworkUtils.createServerSocket(NetworkUtils.java:51)\n'
'\tat io.bazel.rules.closure.webfiles.server.WebfilesServer.runForever(WebfilesServer.java:137)\n'
'\tat io.bazel.rules.closure.webfiles.server.WebfilesServer.run(WebfilesServer.java:125)\n'
'\tat io.bazel.rules.closure.webfiles.server.WebfilesServer.main(WebfilesServer.java:76)\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\tSuppressed: java.net.BindException: Address already in use (Bind failed)\n'
'\t\t... 9 more\n'
'\n'

----------------------------------------------------------------------
Ran 1 test in 0.698s

FAILED (errors=1)
```

I’m not sure why this would be failing to bind. I have lots of free
ports, and can easily run

```
for i in {1..1000}; do python3 -m http.server 0 & done
```

(use `kill %{1..1000}` to clean up after that).

Re-running the test by itself fixes the problem.

**Comment by wchargin** [comment]
Took a quick look at this—it seems plausible that the webfiles server is
giving up after exploring 10 ports, so when more than 10 tests are run
concurrently we hit problems:

https://github.com/bazelbuild/rules_closure/blob/9de67f151743d4d54963f3a8184259c8b5326677/java/io/bazel/rules/closure/webfiles/server/NetworkUtils.java#L34-L49

I’ll see if I can get it to always bind to port 0 instead. We don’t use
the servers for local testing enough for this to be a significant
inconvenience.

**Comment by akdeepak** [comment]
**I'm trying to build the source of  tensorboard by following below command** 
_bazel run tensorboard/plugins/projector/vz_projector:devserver_ 

It fails with the below exception:
INFO: Found 1 target...

[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //tensorboard/plugins/projector/vz_projector:devserver up-to-date:
[1 / 1] checking cached actions
  bazel-bin/tensorboard/plugins/projector/vz_projector/devserver.html
[1 / 1] checking cached actions
INFO: Elapsed time: 0.444s, Critical Path: 0.00s
[1 / 1] checking cached actions
INFO: 0 processes.
[1 / 1] checking cached actions
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorboard/plugins/projector/vz_projector/devserver
INFO: Build completed successfully, 1 total action
Feb 29, 2020 5:06:36 PM io.bazel.rules.closure.webfiles.server.WebfilesServer run
SEVERE: Webfiles server died
java.net.SocketException: Protocol family unavailable
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231)
	at io.bazel.rules.closure.webfiles.server.NetworkUtils.createServerSocket(NetworkUtils.java:51)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.runForever(WebfilesServer.java:137)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.run(WebfilesServer.java:125)
	at io.bazel.rules.closure.webfiles.server.WebfilesServer.main(WebfilesServer.java:76)

Kindly request to help here 

Thanks in advance

Deepak
