### ISSUE TITLE
Parsing event file spec in Windows

### ISSUE THREAD

**Issue by shakedel** [tensorflow/tensorboard#265]
In `backend.application.parse_event_files_spec` a log directory 'spec' is partitioned with respect to `:` (line 267) to allow the `run_name:path` expression. However, this handicaps Windows user with log directories residing on other drives, e.g. `D:\` as the path is split (without using the `run_name` exp). using `os.path.splitdrive` can solve this, but only if we limit the `run_name` to be longer than 1 letter.

**Comment by wchargin** [comment]
Thanks for your PR! Closing this issue as a duplicate of #52, but we'll of course still take a look at the PR.
