### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'npm':

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorboard#2673]
I already have npm installed. How to use the existing npm?

**Comment by yurivict** [comment]
Is there an easier way to install ```tensorboard``` than with bazel? I see that it only has platform-neutral files. What does it really install? I am trying to create a FreeBSD port for it, but the installation procedure is quite dense, bazel downloads even the whole TensorFlow tarball for some reason, and npm.

**Comment by rmothukuru** [comment]
@yurivict,
You can install Tensorboard using the command, `pip install tensorboard`. 
Can you please try that and let me know if that helps. Thanks!

**Comment by stephanwlee** [comment]
Yuri, I presume there is a special version of node too? 

I have not tried it myself but this might help you: https://bazelbuild.github.io/rules_nodejs/Built-ins.html

Specifically, you may be able to write one line below for freebsd and point to a tar.gz-ed node for it.
```
node_repositories(
    node_repositories = {
        "10.10.0-darwin_amd64": ("node-v10.10.0-darwin-x64.tar.gz", "node-v10.10.0-darwin-x64", "00b7a8426e076e9bf9d12ba2d571312e833fe962c70afafd10ad3682fdeeaa5e"),
        "10.10.0-linux_amd64": ("node-v10.10.0-linux-x64.tar.xz", "node-v10.10.0-linux-x64", "686d2c7b7698097e67bcd68edc3d6b5d28d81f62436c7cf9e7779d134ec262a9"),
        "10.10.0-windows_amd64": ("node-v10.10.0-win-x64.zip", "node-v10.10.0-win-x64", "70c46e6451798be9d052b700ce5dadccb75cf917f6bf0d6ed54344c856830cfb"),
    },
)
```

**Comment by UsharaniPagadala** [comment]
@yurivict 
Closing this issue based on the @stephanwlee 's comment. Please feel free to reopen if this still persists.
and also refer this [documentation](https://bazelbuild.github.io/rules_nodejs/). Thanks
