### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'estimator'

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorboard#2676]
I have py36-tensorflow-1.14.0 and py36-tensorflow-estimator-1.14.0_1 installed (both are latest versions), but tensorboard fails:

```
$ tensorboard < events.out.tfevents.1568855561.yv.noip.me
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 6, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python3.6/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/usr/local/lib/python3.6/site-packages/tensorboard/default.py", line 39, in <module>
    from tensorboard.plugins.beholder import beholder_plugin_loader
  File "/usr/local/lib/python3.6/site-packages/tensorboard/plugins/beholder/__init__.py", line 22, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "/usr/local/lib/python3.6/site-packages/tensorboard/plugins/beholder/beholder.py", line 199, in <module>
    class BeholderHook(tf.estimator.SessionRunHook):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'estimator'
```

tensorboard is of version 2.0.0, also the latest from PyPI.

So tensorboard is broken, fails to run.

**Comment by wchargin** [comment]
TensorBoard 2.0.0 requires TensorFlow 2.0.0 or a corresponding release
candidate. Please do the following:

 1. Uninstall **all** copies of `tensorflow`, `tensorflow-estimator`,
    `tensorboard`, and any corresponding nightly packages. (Or, just
    throw away your virtualenv and create a new one.)
 2. Install `tensorflow==2.0.0rc1`.
 3. Uninstall `tb-nightly`, which will have just been installed.
 4. Install `tensorboard==2.0.0`.

This sequence is ugly, yes. The uninstallations are necessary to prevent
Pip from corrupting your site packages directory. When TensorFlow 2.0.0
final is released, you’ll be able to just `pip install` it without
manually following steps (3) and (4).

In the future, please run [`diagnose_tensorboard.py`][1] as requested in
the issue template, and post the exact output here.

(Also, note that TensorBoard is invoked with `--logdir SOME_DIRECTORY`
rather than redirecting standard input.)

[1]: https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

**Comment by yurivict** [comment]
> TensorBoard 2.0.0 requires TensorFlow 2.0.0 or a corresponding release
candidate.

You need to keep releases of related software compatible. If TensorFlow is at one stable release number, you should keep TensorBoard's release compatible with the same TF release. Otherwise, how would users figure out what is compatible with what?

> Install tensorflow==2.0.0rc1.

I install from the FreeBSD package. It is currently at ```1.14.0```, which is a stable version. It is extremely difficult to build a new version of TF from scratch because Bazel doesn't work well outside of Google. (Bazel also fails to build TB from source.) In fact. Bazel doesn't work well outside of Google on any project.

In the light of the above, could you please tell me how can I follow your suggestion?

**Comment by wchargin** [comment]
> If TensorFlow is at one stable release number, you should keep
> TensorBoard's release compatible with the same TF release.

This is the case: TensorBoard 2.0 and TensorFlow 2.0 are compatible.

> Otherwise, how would users figure out what is compatible with what?

For any given minor series *x*.*y*, TensorBoard *x*.*y* is compatible
with TensorFlow *x*.*y*, and no other guarantees are made.

> It is extremely difficult to build a new version of TF from scratch

You don’t need to build TensorFlow from scratch. (I don’t usually—it
takes a long time.) Release candidate binaries are provided on PyPI.

We don’t control what packages are available in the FreeBSD
repositories, so I can’t advise you there.

> (Bazel also fails to build TB from source.) In fact. Bazel doesn't
> work well outside of Google on any project.

This is not true. I can build TensorBoard on my personal laptop just
fine. Also, all daily development of TensorBoard is done using public
Bazel binaries, building the public TensorBoard source tree, in exactly
the same way that is specified in the documentation on this repository.
We receive contributions from third-party contributors who successfully
use Bazel to build and test their code.

> In the light of the above, could you please tell me how can I follow
> your suggestion?

```
pip uninstall \
    tensorflow tf-nightly tf-nightly-2.0-preview tensorflow-estimator \
    tensorflow-estimator-nightly tensorflow-estimator-2.0-preview \
    tensorboard tb-nightly \
    &&
pip install --upgrade pip &&
pip install tensorflow==2.0.0rc1 &&
pip uninstall -y tb-nightly tensorboard &&
pip install tensorboard==2.0.0
```

**Comment by wchargin** [comment]
FreeBSD is not one of TensorFlow’s supported platforms:
<https://www.tensorflow.org/install#install-tensorflow>

We generally approve fixes for FreeBSD when provided by the community
(e.g., tensorflow/tensorflow#28689), but don’t test or build release
binaries for FreeBSD.

**Comment by yurivict** [comment]
> FreeBSD is not one of TensorFlow’s supported platforms:

This is lousy. Thousands of other projects build fine on FreeBSD, and TF doesn't because Bazel fails.

**Comment by wchargin** [comment]
Please feel free to send patches that improve support for FreeBSD. We’d
be happy to accept them, provided that they don’t complicate the overall
system too much. Bazel also has [“community support”][bcs] for FreeBSD,
so I suspect that they have a similar policy.

[bcs]: https://docs.bazel.build/versions/master/install.html#community-supported-packages
