### ISSUE TITLE
Page scrolls whilst zooming on graph.

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorboard#2677]
## Environment information (required)

TB - 1.14.0
TF - 1.14.0

Don't think it's a browser issue but this was on Chrome 76.0 (although i'm sue an update).

## Issue description

Related to #2214 in that it's great that graphs only zoom when you hold `alt` as I believe it is now. However I am finding that whilst holding `alt` and scrolling it both zooms the graph and scrolls the page. This means that in a couple of scroll wheel clicks my graph is off the screen and i'm zooming on a different graph instead. Do it fast enough and you've messed up the zoom on all the graphs below!

**Comment by stephanwlee** [comment]
It is a Chrome only issue (Chrome decided to take different interpretation of a spec for overall performance improvement of the web) and it should be addressed in TB nightly or TB 1.15. Would you please TB by doing `pip install -U tensorboard`?

**Comment by jubjamie** [comment]
I've pulled an update and this has fixed the issue. Cheers

**Comment by Melanol** [comment]
ALT+Scroll only scrolls the page for me. Chrome 103.0.5060.114 (Official Build) (64-bit), Ubuntu 20.04.4 LTS.

**Comment by bmd3k** [comment]
@Melanol , could you open a new issue and provide some more details in it? The issue template will have some instructions on what sort of information we would like to collect. Also, could you state which dashboard you are using (Time Series, Scalars, Graphs, other?).
