### ISSUE TITLE
How to merge multiple tensorboard outputs?

### ISSUE THREAD

**Issue by DrvoiDcy7** [tensorflow/tensorboard#2724]
Sometimes the training is extremely time-consuming and interrupts several times. There would be multiple tensorboard outputs if training is resumed from a checkpoint.

Is there any way to straightforwardly merge multiple tensorboard outputs into one?

**Comment by wchargin** [comment]
When you point TensorBoard at a directory, TensorBoard recursively
explores all descendant directories and reads all event files found
therein. If all your data is in one directory, you can just point
TensorBoard at that directory. Are you having trouble getting this to
work? If so, could you please post your logdir to this issue, or at
least describe its structure?

You might also try the new `--reload_multifile=true` option (requires
TensorBoard 1.15 or higher):
<https://github.com/tensorflow/tensorboard#tensorboard-is-showing-only-some-of-my-data-or-isnt-properly-updating>

**Comment by DrvoiDcy7** [comment]
@wchargin Thanks a lot! My original logdir was generated with timestamp, now it's fixed!

**Comment by wchargin** [comment]
Great; glad to hear it!
