### ISSUE TITLE
Debugging features in the graph dashboard are broken.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#274]
Internal debugging features are broken because the `_debuggerDataEnabled` property is [no longer passed to the graph dashboard](https://github.com/tensorflow/tensorboard/blob/530310dd26f8f14df7a49b6d8f286c3d63627e0d/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L366). With that property set to false, no debugging features appear.

A long term reality is that the debugger plugin has its own dashboard. For now, we can fix the breakage by having the graph dashboard rely on the `plugins_listing` route to determine whether there is debugging data to visualize. This means that debugging features appear in the graph if the backend (the debugger plugin) detects debugger-related events.

**Comment by caisq** [comment]
cc myself
