### ISSUE TITLE
Docs shouldn’t recommend installing nightly on top of stable

### ISSUE THREAD

**Issue by davidrichards10** [tensorflow/tensorboard#2748]
I am training a model in google colab and am trying to use tensorboard for visualization. This code below is what I used to install but when I run "  %tensorboard --logdir logs " I get the following errors before even running my model. This was working for me a couple days ago. Please help if you can.

    !pip install -q tf-nightly-gpu-2.0-preview
    %load_ext tensorboard

    %tensorboard --logdir logs

    ERROR: Failed to launch TensorBoard (exited with 1).
    Contents of stderr:
    Traceback (most recent call last):
      File "/usr/local/bin/tensorboard", line 10, in <module>
        sys.exit(run_main())
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 64, in run_main
        app.run(tensorboard.main, flags_parser=tensorboard.configure)
      File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
        _ run_main(main, args)
      File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
        sys.exit(main(argv))
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 220, in main
        server = self._make_server()
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 299, in 
    _make_server
        self.assets_zip_provider)
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 160, in 
    standard_tensorboard_wsgi
        flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 228, in 
    TensorBoardWSGIApp
        return TensorBoardWSGI(tbplugins, flags.path_prefix)
      File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 279, in 
    __init__
        raise ValueError('Duplicate plugins for name %s' % plugin.plugin_name)
    ValueError: Duplicate plugins for name projector

**Comment by wchargin** [comment]
Hi @davidrichards10! This happens when you have multiple copies of
TensorBoard installed in the same environment. Colab has `tensorboard`
installed by default; when you install `tf-nightly-gpu-2.0-preview`, you
also transitively install `tb-nightly`, which causes conflicts.

The solution is to uninstall **all** copies of TensorBoard and reinstall
just the one that you want:

```
!pip uninstall -q tensorboard tb-nightly
!pip install -q tb-nightly  # or tensorboard, but not both
```

I see that some of our docs and tutorials still suggest installing the
preview versions; we should remove these now that TensorFlow 2.0.0 and
TensorBoard 2.0.0 have been released. Thanks for the report!

**Comment by signalprime** [comment]
friends, none of this worked for me.. I mean, it was helpful but still no luck. Listing all pip installed packages for "tf" and "tensorflow" didn't reveal the problem.  However the error was indeed multiple installations of tensorboard. So what finally solved it was the following:

```
import pkg_resources
for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins'):
    print(entry_point.dist)
```
which returned:
tensorboard 2.2.2
tensorboard-plugin-wit 1.6.0.post3
tb-nightly 2.3.0a20200408

And removing "tb-nightly" and reinstalling tensorboard solved it finally.  Hopefully this helps someone else in the future.  Sending my best wishes to the team and community.
So

**Comment by ItamarRocha** [comment]
solved for me. Thanks.
