### ISSUE TITLE
Lagging metrics

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorboard#2754]
> Environment information (required)
> System: Windows 10, RAM 64 GB
> Environment: Python 3.7, TensorFlow-gpu
> GPU: GeForce RTX 1060 , CUDA 10.0, cudnn-10.0-windows10-x64-v7.4.2.24

If more than one metric is displayed on the board, then they lag behind by one era. Why?

```
class Evaluate(Callback):

    def on_epoch_end(self, epoch, logs=None):
        correct_prediction, max_list = evaluate(basemodel, epoch)      

        min_prediction = round(np.min(max_list), 4)
        mean_prediction = round(np.mean(max_list), 4)
        
        tf.summary.scalar('correct_prediction', data=correct_prediction, step=epoch)
        tf.summary.scalar('min_prediction', data=min_prediction, step=epoch)
        tf.summary.scalar('mean_prediction', data=mean_prediction, step=epoch)
```

![image](https://user-images.githubusercontent.com/26105224/66558063-5ebdc080-eb6c-11e9-8c83-435cd6476b81.png)

**Comment by sonfiree** [comment]
![image](https://user-images.githubusercontent.com/26105224/66558173-90cf2280-eb6c-11e9-98f0-5d3e2da36b06.png)

**Comment by sonfiree** [comment]
Try?
```
class Evaluate(Callback):

    def on_epoch_end(self, epoch, logs=None):
        correct_prediction, max_list = evaluate(basemodel, epoch)      

        min_prediction = round(np.min(max_list), 4)
        mean_prediction = round(np.mean(max_list), 4)
        
        tf.summary.scalar('correct_prediction', data=correct_prediction, step=epoch)
        tf.summary.scalar('min_prediction', data=min_prediction, step=epoch)
        tf.summary.scalar('mean_prediction', data=mean_prediction, step=epoch)
      
       tf.summary.flush()
```

**Comment by stephanwlee** [comment]
I believe so. Was that sufficient?

**Comment by sonfiree** [comment]
I came to version 1.4. Due to bugs in 2.0

**Comment by stephanwlee** [comment]
@sonfiree there is a v1 equivalent that you can try: https://www.tensorflow.org/api_docs/python/tf/compat/v1/summary/FileWriter#flush

**Comment by sonfiree** [comment]
It works better
https://github.com/lanpa/tensorboardX
