### ISSUE TITLE
doc: r1 overview's link to custom scalar is not useful

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#2814]
https://github.com/tensorflow/tensorboard/blob/master/docs/r1/overview.md#can-i-customize-which-lines-appear-in-a-plot for "custom scalar plugin" links to https://github.com/tensorflow/tensorboard/blob/master/docs/r1/tensorboard/plugins/custom_scalar which is does not exist.

**Comment by LexusH** [comment]
I'll look into fixing this link. Thank you for reporting this!
