### ISSUE TITLE
Putting two metrics in one graph has not been implemented yet?

### ISSUE THREAD

**Issue by Traeyee** [tensorflow/tensorboard#2831]
As far as I know, the only way to put two metrics in one graph is let them be in two different directories, but it's kind of unfriendly. 
For example, users often want to compare the inference curve line and label curve line to know whether the model has finely fitted to the data.

**Comment by nfelt** [comment]
You can try using the Custom Scalars dashboard for this purpose.  See readme here:
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/custom_scalar/README.md

**Comment by Traeyee** [comment]
> You can try using the Custom Scalars dashboard for this purpose. See readme here:
> https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/custom_scalar/README.md

Thanks, it perfectly solves my problem. But the little pity is that I couldn't find out anything about colouring different metrics
