### ISSUE TITLE
Can hparams tensorboard plugin be used without eager execution?

### ISSUE THREAD

**Issue by srivathsapv** [tensorflow/tensorboard#2850]
hparams tensorboard plugin is a wonderful tool to aggregate results of a set of hyperparam search experiments. But I'm currently not able to work with the plugin as I'm using `tensorflow==1.14.0`, and when I try to use it with keras, I get an error saying that the plugin works only if eager execution is enabled. Is there a way I can make this plugin work with tensorflow 1.x and/or without eager execution? Any help would be appreciated.

**Comment by moritzmeister** [comment]
I was using the plugin with TF1.x (1.14 and 1.15) and Keras for a while, not without eager execution though.
It was working with these imports:
```
__import__("tensorflow").compat.v1.enable_eager_execution()
import tensorflow.compat.v2 as tf
from tensorboard.plugins.hparams import api_pb2
from tensorboard.plugins.hparams import summary
from tensorboard.plugins.hparams import summary_v2
```

**Comment by AhmedFakhry47** [comment]
I think it's only available when eager execution is enabled .

**Comment by pindinagesh** [comment]
@srivathsapv 

Please take a look at the above comment from @moritzmeister and we recommend you to update your tensorboard to latest stable version and reopen this issue if the issue still persists. Thanks

**Comment by bileschi** [comment]
This minimal demo should work with tf `1.14.0`
https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/hparams/hparams_minimal_demo.py
