### ISSUE TITLE
What UI would you like to see for image/audio summaries?

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#296]
Both the image and audio summaries include a `batch_size`, which allows
you to record multiple images/clips at a single step. Currently, this
works by creating (say) three separate tags `foo/image/{0,1,2}`, and so
in TensorBoard you see three separate image/audio cards. Once we migrate
to tensor summaries (see below for more details), we'll instead store
your three images/clips as three entries in a single tensor in a single
tag instead of one entry each across three tags. This gives us more
flexibility in how we display your data in the UI.

One option is to retain a functionally equivalent view to what's
currently present: we could, on the client side, silently explode the
first dimension of the tensor, and yield three copies of the card.

Or, if you prefer, we could add a second slider below the existing step
slider, allowing you to change the sample that you're viewing. (I could
see how this could have both advantages and disadvantages for images: on
the one hand, you can quickly move back and forth to compare two
samples, but on the other hand you wouldn't have them available
side-by-side.) Such a slider could alternatively be at the
whole-dashboard level.

Perhaps for each tag we could have a similar slider that instead
controls the number of samples that are shown at any given time.

Here are some more details about what this "migration to tensor
summaries is" and why it's related. As we continue to make TensorBoard's
plugin system more and more well-defined, we're changing the format of
newly created image and audio summaries. Currently, image and audio
summaries each have a special field in [the `Summary.Value`
protobuf][1]. This privileges these summaries over other summaries, so
we'll shortly be migrating them to use the generic `tensor` field
instead, and—as mentioned above—storing all image/clips from one step
within one tensor. For comparison, we recently did this for the
histogram plugin; you can see the results in #246. Don't worry: your old
data will be compatible, and the old APIs will continue to work.

[1]: https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/core/framework/summary.proto#L119-L121

I'm open to suggestions—what do you think? (For now, I'll implement the
first option, retaining feature parity.)

**Comment by jlazarow** [comment]
Can you allow "arbitrary" tagging to the summaries outside of the actual summary name? I'd like to sometimes name the individual images and associate label information to them (perhaps there is already a way to do this?).

**Comment by wchargin** [comment]
@jlazarow: You're asking to be able to attach a name that differs across steps or across samples within a batch? While that's a reasonable thing to request, in this issue I'm trying more to explore better ways to display the image data that we already store, rather than changing the data format.

That said, it would be reasonably easy to create a plugin that does exactly what you want! If you duplicate verbatim the code for the image plugin, but change the summary `op` function so that the emitted tensor is of the form (say) `[width, height, png0, label0, png1, label1, …]` instead of just `[width, height, png0, png1, …]`, then you could very easily read out those strings on the backend, forward them to the frontend, and display them below the "step" slider. It's unlikely that this functionality could be merged into the main images plugin, unless you can devise a data format that's backward-compatible with the current summaries. (I guess you could do something hacky like the following: observe that every PNG starts with `\x89PNG`, and instead write labels as `b'\x89LBL%s' % actual_label`, so that the backend can unambiguously determine whether each string is a label or an image. This would work, but I'm still not sure that it's something that we'd want to support—feel free to open a separate issue.)

If you don't want to write a plugin, here is an approach that is not optimal for viewing, but does "get the data out there": use a separate text summary where you provide the image names. This can freely vary across steps and across samples (the latter because the text summary can accept vectors of strings in addition to single strings). You would have to manually cross-reference the text summaries with the image summaries.

(A very hacky "solution" is to use a `tf.py_func` to superimpose the text of your label onto the actual image using `PIL` or `matplotlib` or something. Last resort only.)

**Comment by rryan** [comment]
One thing we lost when you did away with the grid UI for audio summaries was the ability to easily compare two summaries with the same tag across different runs (which was previously easy as pie since they were all aligned horizontally). If your new UI had some nice way of grouping identical tag audio across runs that'd be nice.

**Comment by jlazarow** [comment]
@wchargin thanks for the response. While the plugin framework seems great, it seems a bit crazy to have to do that for every small complaint. I would be _okay_ with this if the data pipeline were more extensible and the UI configurability was easy (for a non TF developer) to template the polymer part to just display their particular needs. I guess I'm trying to use TensorBoard from an experimental/research aspect (perhaps wrongly?) which usually involves me trying to shove _a lot_ of metadata through to aid why the model is performing in a certain way. The issue is that the interface between TF and TB is just too rigid (it's already a hack to just change the _names_ of summaries without introducing a new op) and hard to justify the investment to majorly alter the behavior of TB (e.g. by writing _and_ maintaining a slew of plugins).

**Comment by wchargin** [comment]
@rryan: Fantastic—thank you for the detailed input.

> Ability to include [string tensor] text annotations would be amazing.

So far 2/2 people expressing support for this…noted!

We have some flexibility here, as we haven’t designed the audio tensor format yet. The current summary includes a bunch of global metadata: the sample rate, channel count, number of samples, and MIME type. All of this is junk: the only field among these that’s even used is the content type, but that is always `audio/wav`.[1] So, if we remove all these, then the tensor would look like a rank-1 string tensor of `[wav_data_0, wav_data_1, …]`. Perhaps we could instead use a rank-2 string tensor of the form `[[wav_data_0, wav_data_1, …], [markdown_metadata_0, markdown_metadata_1, …]]`, which would allow you to provide a transcript or any other information that you like. This could easily come from a string tensor.

[1]: TensorFlow only supports encoding WAV, sadly. If this changes in the future and we really want to add support for storing the content type in the summary, we could include this in the summary metadata instead of the summary value.

> spectrogram plot tool

An interesting idea: I can see how this would be indispensable. We’d have to design this carefully with performance in mind (where do we do the FFTs?). I’m going to punt on this for now, as it would be a major undertaking…

I don’t know what you mean by, "I'd ideally like my model to be able to write a webcomponent to the events file that TB would embed." Surely you don’t mean that you want your TensorFlow code to be emitting JavaScript and HTML source code to be injected into the TensorBoard dashboard?

> Audio summaries reload every 30 seconds by default, which is quite annoying!

I imagine that we can be more careful about not reloading the UI when the backing data doesn't change. I’ll take a look. (I’m assuming that you do want it to fetch new data, but you don’t want it to reset your playback position/checkpoint every 30s?)

> Download button (please keep it, but ideally the filename could be better than "individualAudio" with no extensions)

We don’t plan to remove this. Note that it’s provided by the native controls of the HTML `<audio>` element; after searching a bit, I don’t see a way to change the downloaded file name. However, I’m happy to add a link above (by the step counter, maybe) to download it, and with a user-created link it is easy to set the download name. This could replace the download button in the controls. Would you be interested in this?

> It probably makes sense to turn off repeat by default. I like it, but it can be annoying e.g. when you left one playing and change pages (it still plays on repeat).

I can easily change this, and I can also easily make it a dashboard-level global option. (I.e., a single checkbox “loop audio?” would appear above the runs selector.)

> Scrub through checkpoints -- this feature is awesome, please keep it!

Certainly.

> nice way of grouping identical tag audio across runs

Just to be sure—it should still be the case that all occurrences of a given tag are consecutive, right? The only change is that they might wrap across lines. (If this isn’t the case, I’ll fix it.) I’m surprised that this is very much worse than having them all in one row, so I just want to confirm.

One thing that you can do is search for the tag, which will remove all other tags (if you anchor it with `^tag_name$`). I appreciate that this is not as convenient.

> Let me know if you'd like to see our typical tensorboards (or just check out my experiments internally).

I downloaded one while looking into a YAQS question of yours, and my biggest impression was how huge the files were. How much trouble is caused by the fact that we only support WAV and not, say, Vorbis? Currently, TensorFlow only supports encoding WAV, but I don’t see why this should need to be the case. [Adding arguments `{"-f", StrCat(output_format_id)}` to `ffmpeg_lib.cc`](https://github.com/tensorflow/tensorflow/blob/359d6f9716c0bb9bd8201ce600da98b0481a8049/tensorflow/contrib/ffmpeg/default/ffmpeg_lib.cc#L41) should do it. Is this something that you would like to see?

**Comment by wchargin** [comment]
@jlazarow:

> it seems a bit crazy to have to do that for every small complaint

I hear you, and I agree that forking the whole dashboard to add label information is not a long-term solution.

Like I mentioned, the problem is really in getting the label information from your TensorFlow session to the outside world. I’ve continued to think about it, and it seems like we might do the following. Currently, the image summary emits a rank-1 string tensor of the form `[width_str, height_str, png_0, png_1, …]`, where the `png_i` are bytestrings with PNG-encoded image data and `width_str` and `height_str` are ASCII representations of the image width and height in decimal (e.g., `"123"`). We could backward-compatibly allow the operation to instead output a rank-2 string tensor of the form `[[width_str, height_str, png_0, png_1, …], [ignored, ignored, markdown_label_0, markdown_label_1, …]]`, where `[markdown_label_0, markdown_label_2, …]` is a string tensor provided to the summary. I’ll see what other people on the team think about this, and then we can consider implementing it.

> I guess I'm trying to use TensorBoard from an experimental/research aspect (perhaps wrongly?)

Not wrongly at all—our primary goal is to help researchers write visualizations tailored to their research.

> The issue is that the interface between TF and TB is just too rigid

It is. In particular, the requirement that all summary output be a tensor, not something more struct-like, is very restrictive. (Things like "the images plugin emits a tensor the first two values of which are the stringified versions of the image dimensions" are already too hacky for my tastes…)

> It's already a hack to just change the names of summaries without introducing a new op

Happily, our new APIs support `display_name` and also `summary_description` parameters. The images demo (`//tensorboard/plugins/image:images_demo`) includes code that demonstrates how to use these parameters. You can see example screenshots in this PR: https://github.com/tensorflow/tensorboard/pull/314. Hope this helps a bit. :-)

**Comment by rryan** [comment]
Thanks @wchargin! 

> We have some flexibility here, as we haven’t designed the audio tensor format yet. The current summary includes a bunch of global metadata: the sample rate, channel count, number of samples, and MIME type. All of this is junk: the only field among these that’s even used is the content type, but that is always audio/wav.[1] So, if we remove all these, then the tensor would look like a rank-1 string tensor of [wav_data_0, wav_data_1, …]. Perhaps we could instead use a rank-2 string tensor of the form [[wav_data_0, wav_data_1, …], [markdown_metadata_0, markdown_metadata_1, …]], which would allow you to provide a transcript or any other information that you like. This could easily come from a string tensor.

Yea, I'm the original author of audio summary support in TF/TB, so this is all my fault :). 

WAV is indeed a huge waste of space -- my team alone is spending many terabytes of space on storing our events files because of all the WAVs we produce across all our experiments (and I know audio summaries are a bit of a storage pain for a certain "ML dashboard")

I left mimetype in there as room for expansion basically, so we could eventually include a proper lossy or lossless codec at some point for compression (e.g. FLAC). Adding a dependency like libFLAC to TensorFlow was much harder than whipping up a WAV encoder by hand, so I went with that originally. 

Note tf.contrib.ffmpeg is an optional dependency, so you can't rely on FFMPEG being available (which would make this a lot easier, though security-wise it's not allowed for use internally without sandboxing).

As for codec, a lossless codec would be preferred (e.g. FLAC over Vorbis) so we know distortions in the audio came from our model, not the codec.

> An interesting idea: I can see how this would be indispensable. We’d have to design this carefully with performance in mind (where do we do the FFTs?). I’m going to punt on this for now, as it would be a major undertaking…

Yup, I wouldn't expect the TB team to maintain such a thing, even though I want it badly. Hence my desire to be able to write TB UI myself via plugins. (I haven't been keeping up with the current proposal for plugins though).

> I imagine that we can be more careful about not reloading the UI when the backing data doesn't change. I’ll take a look. (I’m assuming that you do want it to fetch new data, but you don’t want it to reset your playback position/checkpoint every 30s?)

Honestly I'd prefer all of TensorBoard to not refresh automatically by default (even if there is new data to be shown) but I may be weird. I'd rather choose when to check for new data via the refresh button. Having the pref option is fine, it's just slightly annoying the cookies don't transfer across different experiments.

> We don’t plan to remove this. Note that it’s provided by the native controls of the HTML <audio> element; after searching a bit, I don’t see a way to change the downloaded file name. However, I’m happy to add a link above (by the step counter, maybe) to download it, and with a user-created link it is easy to set the download name. This could replace the download button in the controls. Would you be interested in this?

Yea I think I looked into this at one point. It's a shame the audio widget's download button doesn't make this easy. Maybe disabling the download button and providing a download link is the best option? It's really not urgent.

> I can easily change this, and I can also easily make it a dashboard-level global option. (I.e., a single checkbox “loop audio?” would appear above the runs selector.)

:+1: I don't know if a preference option is really necessary. You can right-click any audio widget and hit "Repeat" to enable repeat mode.

> Just to be sure—it should still be the case that all occurrences of a given tag are consecutive, right? The only change is that they might wrap across lines. (If this isn’t the case, I’ll fix it.) I’m surprised that this is very much worse than having them all in one row, so I just want to confirm.

They are consecutive, but the line wrapping makes it harder than the grid layout since the first instance of the tag can occur at any column position (so you have to slow down and read). It'd be nice if there was a forced line wrap after the last run of every tag so the first run of every tag was always in the left-most column.

> I don’t know what you mean by, "I'd ideally like my model to be able to write a webcomponent to the events file that TB would embed." Surely you don’t mean that you want your TensorFlow code to be emitting JavaScript and HTML source code to be injected into the TensorBoard dashboard?

I do :) this to me is the ultimate in customizability for TensorBoard -- the ability to emit my own UI from my model for displaying that would have access to the TB API so it could request summaries across modalities (e.g. go grab some images, text and audio at different timesteps and then combine them in a task-appropriate way in the UI). 

This would also allow a library ecosystem of task-specific TB UIs to emerge too.

I was rambling about this to @dandelionmane a while back :).

**Comment by wchargin** [comment]
> Yea, I'm the original author of audio summary support in TF/TB, so this is all my fault :).

No worries :-). (All the summaries are like that, FWIW: histograms has stuff like `sum_squares`, and images has stuff like `colorspace`. It’s not causing any problems.)

> Note tf.contrib.ffmpeg is an optional dependency, so you can't rely on FFMPEG being available

I don’t follow this. Why can’t we just say that `tensorboard.plugins.audio.summary` requires FFMPEG (or `tf.contrib.ffmpeg`) if you want to use non-WAV summaries? This wouldn’t seem to hurt existing users or break API guarantees, right? (If we do use FFMPEG, we should also get FLAC for free—`-c:a flac` or something—right?)

> Honestly I'd prefer all of TensorBoard to not refresh automatically by default

Interesting. I haven’t heard this before. I’m afraid that there’s not too much that we can do about cookies not transferring, short of writing a Chrome extension or something…

> Maybe disabling the download button and providing a download link is the best option? It's really not urgent.

Acknowledged; thanks.

> I don't know if a preference option [for looping] is really necessary. 

The reason that I suspected that it might be useful is that it’s probably the case that you want all your summaries to loop or all not to. We recently made a similar change in the image dashboard per Ian’s suggestion: https://github.com/tensorflow/tensorboard/pull/261.

I’m happy to leave it out, though, and just disable looping by default. (It’s also trivial to change later, of course.)

> I haven't been keeping up with the current proposal for plugins though

It’s pretty much ready. External contributors are already writing plugins. The guide/example repo is here: https://github.com/tensorflow/tensorboard-plugin-example. You can copy-paste that repo and change the Python/JS to get yourself a brand new plugin.

> the ultimate in customizability for TensorBoard

To make things a bit more concrete, could you give an example of one such task-appropriate UI?

**Comment by jart** [comment]
I'm working on a new tensor sql storage layer right now. I can make FLAC happen for you. Could you share some ballpark estimates (or preferably measurements) of how you're doing audio? For example:

- Min/max/avg length of clips in seconds
- Min/max sampling rate
- Min/max channels
- dtypes you've used, e.g. float32, int16

Spectrograms is something that sounds cool. One way I could envision it working is the audio dashboard requests a PNG file from the backend, for each audio clip. TensorBoard then uses a TensorFlow graph to turn an audio file into a PNG file while serving. This way you get an instant visual idea of every audio clip being displayed on the page, before even listening. FFTs aren't the most expensive thing in the world and TensorFlow can run them on the GPU. So I think `tf.fft` absolutely deserves to be called the fastest fourier transform in the west.

**Comment by rryan** [comment]
> Spectrograms is something that sounds cool. One way I could envision it working is the audio dashboard requests a PNG file from the backend, for each audio clip. TensorBoard then uses a TensorFlow graph to turn an audio file into a PNG file while serving. This way you get an instant visual idea of every audio clip being displayed on the page, before even listening. FFTs aren't the most expensive thing in the world and TensorFlow can run them on the GPU. So I think tf.fft absolutely deserves to be called the fastest fourier transform in the west.

:) note that the recently added tf.contrib.signal has a ready-made STFT:
https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/signal/python/ops/spectral_ops.py#L35

**Comment by rryan** [comment]
> I'm working on a new tensor sql storage layer right now. I can make FLAC happen for you. Could you share some ballpark estimates (or preferably measurements) of how you're doing audio? For example:

Cool! Ballparks for now:

> Min/max/avg length of clips in seconds

min: 2 s, max: 20 s, avg: 5 s

> Min/max sampling rate

8 khz through 48 kHz, typically 16 or 24 kHz

> Min/max channels

Almost exclusively mono, but some folks on my broader team are working on multi-microphone audio use cases (mostly for denoising). The most they'd plausible work with is 16 channels.

> dtypes you've used, e.g. float32, int16

Almost exclusively float32 samples in the range [-1,1].

**Comment by rryan** [comment]
> It’s pretty much ready. External contributors are already writing plugins. The guide/example repo is here: https://github.com/tensorflow/tensorboard-plugin-example. You can copy-paste that repo and change the Python/JS to get yourself a brand new plugin.

Cool! I'll take a look.

**Comment by jlazarow-test** [comment]
@wchargin maybe unrelated, but wouldn't it be easier to have people write their own protobuf formats as part of the plugin process? e.g. you get prebuilt ones like "image" (only), "text" (only) and I can somehow compose these e.g. "image" and "text description" on the TF side into a "image_and_description" protobuf and then maybe I need to do a little work on the TB side to compose these from the UI point of view?

**Comment by wchargin** [comment]
@jlazarow / @jlazarow-test: I'm not sure what you mean by "write their own protobuf formats." Could you elaborate?

You can write an image(-only) summary and a text(-only) summary, but they'll not be associated with each other. If you wanted to write a single summary that contained both images and text, you could do so as long as you can combine the data into one tensor, but you'd need some plugin to be able to interpret that format.

**Comment by jlazarow** [comment]
I would prefer not to use TF ops for talking to TB (I'm still unsure of this design choice... perhaps it's for performance reasons about getting data out of the graph). From my (superficial) understanding of how TF gets data to TB, it is (eventually) by crafting protobuf instances and serializing them to the tfevents files on disk which then get handled/processed by the event accumulator code. What if I just designed my own .proto for the "high" level data I'd like to send e.g. consisting of its own fields like image tensors, labels, etc? I'd like to somehow teach TB (in my plugin) then how to render this (perhaps under a new section I define). Basically, I'm not a fan of these "distinct" TB views... almost always I want to view all my data in a coherent context (or have some way to reconstitute it in the UI).

**Comment by wchargin** [comment]
> From my (superficial) understanding of how TF gets data to TB, it is (eventually) by crafting protobuf instances and serializing them to the tfevents files on disk which then get handled/processed by the event accumulator code.

Correct.

> What if I just designed my own .proto for the "high" level data I'd like to send e.g. consisting of its own fields like image tensors, labels, etc? 

I see what you're asking. The problem is—how do we implement that? As you mentioned, we need to get data out of the graph, and the way that we do that is with an op that takes in the relevant tensor data and serializes it to a protobuf. So far, so good; this is compatible with your vision. Now, currently (moving forward) we use the `TensorSummary` op for everything, and this op accepts a single tensor and stores it into the `tensor` field of the protobuf. But if you want to do something else, which is your whole goal, then the op itself needs to know about your protobuf. You'd have to write a C++ "kernel" for the op that wired up the data to your protobuf.

For instance, [here's the kernel for the `TensorSummary` op.](https://github.com/tensorflow/tensorflow/blob/863d7e7f0202cf5b513f2e3e691e7686562c8d74/tensorflow/core/kernels/summary_tensor_op.cc#L38) If you wanted your `WidgetPlugin` to write a protobuf like
```proto
message WidgetSummaryData {
  string tag = 0;
  int32 widget_count = 1;
  bytes widget_factory_name = 2;
  repeated float production_status = 3;
}
```
then you would want a kernel to do something like this:
```cpp
void Compute(OpKernelContext* c) override {
  const Tensor& tag = c->input(0);
  const Tensor& widget_count = c->input(1);
  const Tensor& widget_factory_name = c->input(2);
  const Tensor& production_status = c->input(2);
  OP_REQUIRES(c, TensorShapeUtils::IsScalar(tag.shape()),
              errors::InvalidArgument("tag must be scalar"));
  OP_REQUIRES(c, TensorShapeUtils::IsScalar(widget_count.shape()),
              errors::InvalidArgument("widget_count must be scalar"));
  OP_REQUIRES(c, TensorShapeUtils::IsScalar(widget_factory_name.shape()),
              errors::InvalidArgument("widget_factory_name must be scalar"));
  OP_REQUIRES(c, TensorShapeUtils::IsVector(production_status.shape()),
              errors::InvalidArgument("production_status must be vector"));


  WidgetSummary s;
  s->set_tag(tag.scalar<string>()());
  s->set_widget_count(tag.widget_count<int32>()());
  s->set_widget_factory_name(tag.widget_count<string>()());
  for (int32 i = 0; i < production_status->NumElements(); i++) {
    s->add_production_status(production_status.flat<float>()(i));
  }

  Tensor* output = nullptr;
  OP_REQUIRES_OK(c, c->allocate_output(0, TensorShape({}), &output));
  CHECK(s.SerializeToString(&output->scalar<string>()()));
}
```
So now you have a C++ dependency in your project, which probably isn't what you want.

Furthermore, once you get that protobuf out of your op, you'd have a `WidgetSummary` protobuf and not a standard `Summary` protobuf. The file writer needs a `Summary` protobuf, because it writes [`Event`s](https://github.com/tensorflow/tensorflow/blob/863d7e7f0202cf5b513f2e3e691e7686562c8d74/tensorflow/core/util/event.proto), and [`Event`s contain `Summary`s](https://github.com/tensorflow/tensorflow/blob/863d7e7f0202cf5b513f2e3e691e7686562c8d74/tensorflow/core/util/event.proto#L29), not arbitrary protos.

So you'd have to change the core `Event` proto so that it can also contain something like a `bytes arbitrary_proto` content…but now you don't know how to decode it in TensorBoard (there are `WidgetSummary`s and `MacGuffinSummary`s; how do you tell them apart?)…so maybe you add some more metadata to the `Event` proto…

Do you see why this is kind of a hard problem? It's not that it's a _bad_ design, but it's pretty fundamentally different from what the rest of TensorBoard uses, and so it would be very tricky to integrate.

**Comment by jlazarow** [comment]
This is great info, thank you!

Yeah, I didn't realize it went that deep. I'll keep thinking about it, but it does seem like it's inevitable to lose relationships between summaries e.g. this is the set of images associated with this loss (as plotted on a graph).

**Comment by wchargin** [comment]
You’re welcome. Yep; the particular choice of proto runs all the way into TensorFlow core. I’m always open to hearing clever ways to work around this without making changes to our data format, though.

**Comment by wchargin** [comment]
Audio summaries with attached string-tensor labels are ready in #344 and #345; interested parties should feel free to comment.
