### ISSUE TITLE
no __main__ for tensorboard

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorboard#297]
In windows 10 x64
tensorflow-gpu 1.3.0rc1 with tensorboard 0.1.2

no __main__ for tensorboard

so we have to type "python -m tensorboard.main --logdir=mylog" in powershell

the system says tensorboard module cannot be executed directly

**Comment by wchargin** [comment]
With current versions of TensorBoard, running `tensorboard` at the
command line is sufficient. (Just verified on Windows 10 (64-bit).)

It’s true that `python -m tensorboard` does not work, but that’s not a
supported invocation on any platform.
