### ISSUE TITLE
Improve discoverability of dynamic plugins

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#2974]
[From a plugin developer on #2968:][quote]

> Dynamic plugins are exactly what I was looking for :)
> 
> I could probably have found that on my own by spending a little more
> time digging through the code rather than depending on the
> documentation, but FWIW, it would have been more discoverable with an
> explicit mention of the plugin framework in the main README.md or
> DEVELOPMENT.md.
>
> —@dproctor

We should do that. We should probably also update `ADDING_A_PLUGIN.md`,
which refers to a repository that is deprecated.

[quote]: https://github.com/tensorflow/tensorboard/issues/2968#issuecomment-558408443

**Comment by psybuzz** [comment]
Closing this since the main README now has a section:
https://github.com/tensorflow/tensorboard#can-i-make-my-own-plugin

And ADDING_A_PLUGIN.md no longer points to the deprecated repo
https://github.com/tensorflow/tensorboard/blob/master/ADDING_A_PLUGIN.md
