### ISSUE TITLE
Cant load logs from amazom s3

### ISSUE THREAD

**Issue by hadaev8** [tensorflow/tensorboard#2995]
Command i use:
`docker run -it --rm -e AWS_ACCESS_KEY_ID= -e AWS_SECRET_ACCESS_KEY= -e S3_REGION=us-east-1 -e S3_USE_HTTPS=1 -e S3_VERIFY_SSL=1 -p 9003:9003 tensorflow/tensorflow tensorboard --port=9003 --logdir= --samples_per_plugin images=100`

Error:
```
Exception name:
Error message: No response body.
6 response headers:
content-type : application/xml
date : Wed, 04 Dec 2019 10:52:39 GMT
server : AmazonS3
transfer-encoding : chunked
```

**Comment by rmothukuru** [comment]
@hadaev8,
Can you please specify the Version of Tensorflow and Tensorboard you are using. Thanks.

**Comment by hadaev8** [comment]
This one https://hub.docker.com/r/tensorflow/tensorflow/
Problem with big ammount of logs (1gb+), i made new folder and copied some logs, tensorboard work fine then.

**Comment by pindinagesh** [comment]
@hadaev8 

Closing this issue as it is resolved, please feel free to reopen if this still exist. Thanks
