### ISSUE TITLE
Feature Request: Add an optional command-line argument for a prefix URL

### ISSUE THREAD

**Issue by dandelionmane** [tensorflow/tensorboard#30]
(I've migrated this issue from https://github.com/tensorflow/tensorflow/issues/10655. It was originally posted by @mebersole. It had four thumbs up emoji there.)

> Would like to add a command-line argument that allows TensorBoard to run at a different URL location than the root domain.  So for example:
> * command-line: `--base_url runhere`
> * URL location: `http://<address>:6006/runhere/`
> 
> Motivation for request: There are locations where only minimal ports are open and it would be great to use nginx (or similar) to route TensorBoard through port 80.
>

**Comment by pbanavara** [comment]
I can take this up as I have some free time to look at this. This will be my first TensorFlow contribution. Please let me know if there are any specific criteria to submit a pull request.

**Comment by dandelionmane** [comment]
Looks like @haraldschilly is already working on this at https://github.com/tensorflow/tensorboard/pull/99. Maybe collaborate with them?

**Comment by haraldschilly** [comment]
Yes, I've a pull request, but it's incomplete (there was some refactoring going on, and now there is somewhere a detail missing, ...). So, @pbanavara ... tell me if you want to collaborate on this, it might not be hard to finish this.

Regarding criterias, I see a CI test and you need to get the google CLA.

**Comment by pbanavara** [comment]
@haraldschilly Absolutely. Thank you for providing access to your repo. Please give me some details on what files or commits to look at and I will help out. I have signed the Google CLA.

**Comment by haraldschilly** [comment]
@pbanavara well, I think you should do this:

1. look at [this diff between master/base and my base_url branch](https://github.com/tensorflow/tensorboard/compare/master...haraldschilly:base_url) 
2. There is a lot of overhead, but the basic idea is to have a `base_url` command line parameter (in `tensorboard/main.py`) and then siphon this into the WSGI application.
3. Look at `_clean_path` in `tensorboard/backend/application.py` ... it's just some minimal path fixture.

What's missing is to pass the tests (something is wrong with where base_url is passed around, happend after a merge with conflicts) and well, right now there is yet another merge conflict. So, maybe it's actually better if you understand what I did and then start from scratch with a new branch. 

Finally, we should also write a test. I can only speculate how to do this. My guess, adding a test case to `tensorboard/backend/application_test.py` (i.e. copying a test that also sets a command line parameter, and see if the server works)

**Comment by pbanavara** [comment]
Thank you Harald. I will definitely take it from where you left and try to
complete this. I will add a test as well. Let's see how this goes. At the
outset - what you have done seems correct. I will dig in more and find out.

Best,
Pradeep

**Comment by JGSweets** [comment]
@pbanavara any update?

**Comment by pbanavara** [comment]
Hey guys sorry I think I bit more than I could chew last couple of weeks. I will get around to this today and this week. Will keep you posted.

**Comment by JGSweets** [comment]
I was able to merge the newest master with @haraldschilly 's base_url branch, had to update clean path, but i was able to successfully change base_url.

Tests failed previously due to the restructuring of TensorBoardWSGIApp in applications, but not in the tests.

TensorBoardWSGIApp() takes exactly 5 arguments (4 given)

Haven't looked into creating new tests yet.

@pbanavara If you would like help lmk, I can share with you my branch.

**Comment by pbanavara** [comment]
Cool. If this works I'll add a new test to your branch. Please add me as a
collaborator on your branch. OR I can fork from your branch and ask for a
PR. Whichever is easier.

Best,
Pradeep

**Comment by JGSweets** [comment]
Invites sent. I was able to personally use the base_url and access it through the path.

My only concern is that this technique still allows one to access tensorboard when not using base_url path. i.e. I can still access tensorboard by visiting localhost:6006 as oppose to requiring localhost:6006/base_url

**Comment by pbanavara** [comment]
Cool. That's a valid issue. I'll try to fix that. If you specify a base_url
prefix, you shouldn't be able to start tensorboard at the root or any other
url prefix. Also there's an issue with slashes. If you access the url at

http://localhost:6006/base_url you get a 404 you should type
http://localhost:6006/base_url/

I'll fix these and add tests.

Best
Pradeep

**Comment by JGSweets** [comment]
@pbanavara hows it going?

**Comment by pbanavara** [comment]
@JGSweets I am not able to find why the server is starting on both root and the base_dir path. Perhaps something internal to the WSGI server.  One observation

In the TensorBoardWSGI class, the base_url parameter is assigned to the class's base_url but beyond that I don't see any other activity. While this seems to work, it's not clear to me how is the parameter used. So I'm unable to figure out why the server is starting at the root location as well. Is there any need to connect base_url with the data_applications dictionary ?

While specifying the path in the URL, you have to specify a trailing '/'. Again, I don't know why - I tried adding a '/' to the base_url parameter before the tb_app is constructed in the main.py class but that doesn't seem to work.

So I'm still working to figure out these issues.

**Comment by jart** [comment]
Is this as a result of patching #99? The implementation might need to be changed so that rather than modifying `_clean_path` it prefixes the prefix to each of the keys in the `data_applications` dictionary.

**Comment by JGSweets** [comment]
@jart @pbanavara originally I tried prefixing data_applications but was receiving a server error which would kill the apps. I'll try again and see if it was just a single occurrence.

**Comment by pbanavara** [comment]
@JGSweets yeah am trying to do the same. Will post here as soon as I figure out what's going on. Am changing the constructor of the TensorBoardWSGI class to prepend the base_dir prefix to all the data and plugin paths.

**Comment by pbanavara** [comment]
So I've added the base_url prefix to all the keys in the data_applications dict. Have removed the changes that @haraldschilly had put in the _clean_path method. No luck. Continuing to work on this.  
Here are my changes: in TensorBoardWSGI init
`self.data_applications = {
        # TODO(@chihuahua): Delete this RPC once we have skylark rules that
        # obviate the need for the frontend to determine which plugins are
        # active.
        self._base_url + DATA_PREFIX + PLUGINS_LISTING_ROUTE: self._serve_plugins_listing,
    }`
`for plugin in self._plugins:
      if plugin.plugin_name is None:
        raise ValueError('Plugin %s has no plugin_name' % plugin)
      if not _VALID_PLUGIN_RE.match(plugin.plugin_name):
        raise ValueError('Plugin %s has invalid name %r' % (plugin,
                                                            plugin.plugin_name))
      if plugin.plugin_name in plugin_names_encountered:
        raise ValueError('Duplicate plugins for name %s' % plugin.plugin_name)
      plugin_names_encountered.add(plugin.plugin_name)

      try:
        plugin_apps = plugin.get_plugin_apps()
      except Exception as e:  # pylint: disable=broad-except
        if type(plugin) is core_plugin.CorePlugin:  # pylint: disable=unidiomatic-typecheck
          raise
        tf.logging.warning('Plugin %s failed. Exception: %s',
                           plugin.plugin_name, str(e))
        continue
      for route, app in plugin_apps.items():
        if not route.startswith('/'):
          raise ValueError('Plugin named %r handles invalid route %r: '
                           'route does not start with a slash' %
                           (plugin.plugin_name, route))
        if type(plugin) is core_plugin.CorePlugin:  # pylint: disable=unidiomatic-typecheck
          path = route
        else:
          path = self._base_url + DATA_PREFIX + PLUGIN_PREFIX + '/' + plugin.plugin_name + route
        self.data_applications[path] = app`

**Comment by pbanavara** [comment]
Looks like I got some handle on the issue. The incoming request doesn't contain the full path when calling:

Here is my server start message
W0817 18:45:20.934437 MainThread main.py:217] URL:::: http://Pradeep-MBPro.local:6006/trial

This are the request objects when I call 
http://localhost:6006

```
E0817 18:45:32.227079 Thread-1 application.py:238] Request ::: <Request 'http://localhost:6006/data/runs' [GET]>
E0817 18:45:32.228430 Thread-3 application.py:238] Request ::: <Request 'http://localhost:6006/data/plugins_listing' [GET]>
```

Here are the request urls when I call
http://localhost:6006/trial
`E0817 18:46:14.884618 Thread-13 application.py:238] Request ::: <Request 'http://localhost:6006/trial' [GET]>`

 '/data/*' are missing

So clearly just '/trial' cannot be found in the data_applications dict and I get a 404.
Does anyone know how the /data/* entries are appended to the request URL in the environ object ?

`request = wrappers.Request(environ)`

**Comment by JGSweets** [comment]
if type(plugin) is core_plugin.CorePlugin:  # pylint: disable=unidiomatic-typecheck
          path = route
        else:
          

Add to route.

**Comment by JGSweets** [comment]
Also, be careful adding the prefix if it is just '/', you'll get paths like '//data'

**Comment by pbanavara** [comment]
Cool. Adding prefix to the route prevents the server from starting at the root when base_url is specified. The server doesn't start at the base_url location though. Still debugging that problem. Thanks for the tip @JGSweets

**Comment by mebersole** [comment]
Let me know when you are ready for testing. We have a number of setups we can use to hammer on it.

Thanks for the effort!

**Comment by JGSweets** [comment]
@mebersole will do, thanks!!

**Comment by pbanavara** [comment]
Hey guys, I seem to have gotten this working. There is a need to add a trailing slash for the path. for for instance:

http://localhost:6006/trial gives 404 whereas 
http://localhost:6006/trial/ seems to work

Any ideas on how to run unit tests locally ? Sorry to sound like a total noob but if I run bazel test I get a message that no test targets can be found. I'm running on MacOS Sierra 10.12.6

```
Pradeep-MBPro:tensorboard pbanavara$ pwd
/Users/pbanavara/dev/tensorboard
Pradeep-MBPro:tensorboard pbanavara$ bazel run tensorboard -- --logdir /tmp/tensorflow/mnist/logs/
INFO: Found 1 target...
Target //tensorboard:tensorboard up-to-date:
  bazel-bin/tensorboard/tensorboard
INFO: Elapsed time: 0.827s, Critical Path: 0.05s
```

**Comment by haraldschilly** [comment]
@pbanavara thank you for working on this! I'm also a bazel n00b, but more general, you can always look what the `.travis.yaml` file is doing for the continuous integration tests :-)

Turns out, in the main directory, you have to run `bazel test tensorboard/...` (the three dots seem to mean "look for everything")

**Comment by pbanavara** [comment]
@haraldschilly  Thank you. I have the tests working but it's failing on one. Will debug and commit.

**Comment by JGSweets** [comment]
@pbanavara which test?

**Comment by pbanavara** [comment]
Loading /data/plugin_listing
The /data/plugin_listing is not present in the data applications dict which
is why the test is failing. I'm figuring out why that is the case. Probably
something went wrong when I prepended base_url to the keys in the data
applications dict.

======================================================================
FAIL: testPluginsListing (__main__.TensorboardServerTest)
Test the format of the data/plugins_listing endpoint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/private/var/tmp/_bazel_pbanavara/47ed072113979254c899569f7883316f/bazel-sandbox/2686506477726509458/execroot/tensorboard/bazel-out/darwin_x86_64-fastbuild/bin/tensorboard/backend/application_test.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application_test.py",
line 104, in testPluginsListing
    parsed_object = self._get_json('/data/plugins_listing')
  File
"/private/var/tmp/_bazel_pbanavara/47ed072113979254c899569f7883316f/bazel-sandbox/2686506477726509458/execroot/tensorboard/bazel-out/darwin_x86_64-fastbuild/bin/tensorboard/backend/application_test.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application_test.py",
line 89, in _get_json
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 404

**Comment by JGSweets** [comment]
@pbanavara Can you commit to a branch in my repo or share? How did you setup the default for the base_url

**Comment by pbanavara** [comment]
@JGSweets I had made a mistake by not prefixing DATA_PREFIX with base_url. I fixed that and the plugin_listing test passes. The loader test fails, and am working on that.

**Comment by pbanavara** [comment]
@JGSweets The loader test is failing because of a locale issue. Nothing related to base_url. Can you please check at your end as well.

**Comment by JGSweets** [comment]
@pbanavara yes, I'll check it tomorrow. Thanks for the update!

**Comment by JGSweets** [comment]
@pbanavara sorry for the delay checking now, had to redeploy on a different computer

**Comment by JGSweets** [comment]
@pbanavara I'm trying to recreate your failed loader_test, but I have not encountered it yet.

When I ran the test, all tests passed.

![image](https://user-images.githubusercontent.com/7725753/29753170-0ae2a022-8b31-11e7-9942-d34f599d4f00.png)

**Comment by pbanavara** [comment]
Cool this must be some python version related locale issue on my end. You can probably submit a PR or I can do the same whichever is easier. Let me know.
		
		

		Get Outlook for iOS
	




On Mon, Aug 28, 2017 at 12:37 AM +0530, "JGSweets" <notifications@github.com> wrote:












@pbanavara I'm trying to recreate your failed loader_test, but I have not encountered it yet.


When I ran the test, all tests passed.

**Comment by JGSweets** [comment]
@pbanavara I made the PR for us, could you check to make sure you signed the CLA? It for some reason is saying that we don't have all signed authors.

**Comment by pbanavara** [comment]
@JGSweets I've signed my CLA on June 9th. Attaching the screenshot. Let me see what to troubleshoot. 

<img width="1440" alt="screen shot 2017-08-28 at 8 31 24 pm" src="https://user-images.githubusercontent.com/600054/29779471-3bff22a2-8c30-11e7-85fc-e06001287438.png">

**Comment by JGSweets** [comment]
@pbanavara Interesting, I have the same.

**Comment by JGSweets** [comment]
@jart the PR has been made https://github.com/tensorflow/tensorboard/pull/436

having issues with CLA despite signing and adding alternate emails.

**Comment by JGSweets** [comment]
@pbanavara I believe I solved the CLA issue, it should be ready for review

However, it is asking for you to confirm your acceptance of the PR

**Comment by pbanavara** [comment]
@JGSweets Done. I commented in the PR, so that should technically suffice for the PR approval.
