### ISSUE TITLE
Graph dashboard rendering broken when no data is loaded

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#3004]
When the graphs dashboard is selected when it has no data, it shows the
help message, but also jankily renders the graph controls and an empty
graph view:

![Screenshot of the graphs dashboard with no data][ss]

It’s supposed to only show the help text.

[ss]: https://user-images.githubusercontent.com/4317806/70343835-1d186180-180d-11ea-8d2a-60c34bbc88a4.png

**Comment by psybuzz** [comment]
cc @davidsoergel
