### ISSUE TITLE
[bug] Tensorboard causes other apps& daemons to crash.

### ISSUE THREAD

**Issue by Technologov** [tensorflow/tensorboard#3012]
```
TensorBoard 1.14 -- on Ubuntu 18.04 LTS. A production training server, so apps 
cannot be upgraded here.
It makes BOINC client (daemon) unresponsive and dead.
root@rampage-107:~# boinccmd --read_global_prefs_override
Operation failed: read() failed
...and after restaring Tensorboard -- boinc suddenly works again ! (for a few minutes... and fails again)
Problem is very much reproducible on my server.
---


steps to reproduce (BOINC side):
# apt-get install boinc-client
cd /var/lib/boinc-client/
boinccmd --project_attach http://www.worldcommunitygrid.org/  $KEY
boinccmd --set_network_mode always
boinccmd --set_run_mode always
boinccmd --set_gpu_mode never
root@rampage-107:~# boinccmd --read_global_prefs_override
root@rampage-107:~#

...
this is on a server that was running BOINC for an entire *month* with zero issues, 
before tensorflow and tensorboard were installed.
...
this server has enough RAM memory and disk space, so those issues can be ruled out:
root@rampage-107:~# uptime
 00:31:18 up 44 days,  2:37, 16 users,  load average: 57.85, 59.09, 57.01
root@rampage-107:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           125G         36G        882M        1.0G         88G         87G
Swap:          8.0G        100M        7.9G
root@rampage-107:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             63G     0   63G   0% /dev
tmpfs            13G  2.8M   13G   1% /run
/dev/sda2       916G  358G  512G  42% /
tmpfs            63G  100K   63G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/loop2       90M   90M     0 100% /snap/core/8039
tmpfs            13G     0   13G   0% /run/user/1000
/dev/loop0       90M   90M     0 100% /snap/core/8213
tmpfs            13G     0   13G   0% /run/user/0

```

**Comment by stephanwlee** [comment]
@Technologov, thanks for the issue. I am not aware of Boinc so I would greatly appreciate if you can bear with our ignorance.

What steps did you take to isolate the issue to TensorBoard? Perhaps set of commands you've used would be nice. TensorBoard is written Python so I am a bit surprised how it may interfere with something like Boinc. Also, wold it be possible to run TensorBoard from some other machine than the one you use for training? 

If you must run TensorBoard in your production training machine, you may want to consider running it in virtualenv without TensorFlow.

**Comment by Tilps** [comment]
We only recently migrated to this machine which runs boinc in the background, previously we experienced that tensorflow would fail with OOM errors when tensorboard had been running with uptime more than a few days, if we just restarted tensorflow it would crash relatively soon, but if we restart both tensorboard and tensorflow it would be stable for a few days again.  I've generally noticed that tensorboard virtual memory allocation gets extremely large over time.
On the new machine it seems that having boinc running in the background is more sensitive to things, but investigation has not been very deep so far.

Your suggestion of running tensorboard in a venv that doesn't have tensorflow installed sounds intriguing, I will see if I can set that up.

**Comment by Tilps** [comment]
Unfortunately tensorboard in venv without tensorflow loaded data exceptionally slowly, and eventually crashed out failing to parse something.  I'll continue investigating alternatives.

**Comment by Tilps** [comment]
Some deeper debugging with strace finds that boinc issues are unrelated to the prior issues we were having with tensorflow crashing out while tensorboard was using up all the ram.  Instead BOINC is searching for an x windows session, and when it finds port 6006 is open, but not responding in the way it would expect from an x windows session, it hangs.

**Comment by wchargin** [comment]
@Tilps: Thanks for investigating and checking back in! The memory issues
are a known issue generally (#766), unless you’re seeing differentially
high memory usage with BOINC in play. The X session sounds like a bug in
BOINC: it’s true X servers frequently use 60xx ports, but BOINC
shouldn’t be assuming that behavior just because one of those ports
happens to be open.

Perhaps as a workaround for the port issue you could ask TensorBoard to
run on a different port, by passing `--port 9009` or similar?

I’m going to close this as it doesn’t look like there’s anything
actionable on our side. Thanks again for the report, and feel free to
follow up if there’s more that we can do for you.
