### ISSUE TITLE
Support environment variable S3_ENDPOINT in tensorboard without tensorflow

### ISSUE THREAD

**Issue by lgeo3** [tensorflow/tensorboard#3014]
When using tensorboard with tensorflow installed, we are able to set the s3_endpoint using S3_ENDPOINT environment variable. It is particularly usefull when running a local s3 instance like minio.

But when using the tensorboard package (without tensorflow), it uses the boto3 client, and don't use the S3_ENDPOINT variable.

A simple modification would be to replace boto3.client/session call with the same call but with the parameter: endpoint_url=os.environ.get('S3_ENDPOINT', None)

What do you think ?

**Comment by stephanwlee** [comment]
That sounds reasonable. Would you like to propose the change via PR? 

@nfelt @orionr FYI

**Comment by thealphacod3r** [comment]
@lgeo3  Is this closed???

**Comment by lgeo3** [comment]
I didn't manage to do the pull request. So not closed, if someone could take care of it would be nice.

**Comment by thealphacod3r** [comment]
@lgeo3 Please give a look to this!

**Comment by lgeo3** [comment]
Seems good to me :+1:. Thanks.
