### ISSUE TITLE
pr_curve summaries are broken due to variable initialization issue.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#302]
pr_curve summaries are broken in TF nightly following 7/28/2017 because of tensorflow/tensorflow#11856.

**Comment by wchargin** [comment]
Not sure what the current status on this is, but—can you work around the issue within our repo (maybe by using `read_value`)? We don't want all our builds to be broken, so as far as I can see our options are (a) work around it (fine), (b) roll back the `pr_curve` plugin (not good), (c) disable the test (bad), or (d) pin an older TensorFlow nightly (very bad). Thoughts?

**Comment by wchargin** [comment]
Ah, he doth appear. Fantastic. :-)
