### ISSUE TITLE
Can I use witwidget in my own web application?

### ISSUE THREAD

**Issue by mengban** [tensorflow/tensorboard#3028]
As i know ,witwidget can be used in jupyter or colab. But can i use it in my own web application, or can i 
 use it as a plugin to display the analyse results in my web app?

**Comment by jameswex** [comment]
It is possible to build the What-If Tool into your own webapp if you write your own javascript to communicate with the WIT html element (named tf-interactive-inference-dashboard) to provide it with data, provide it with model results, and respond to its events. This is how our web demos of the What-If Tool work (like https://pair-code.github.io/what-if-tool/iris.html, with source code https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-iris-demo.html).

See all the code for those demos at https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo including the build files used to create the single html page with all dependencies built in (such as that iris.html demo).

**Comment by mengban** [comment]
> It is possible to build the What-If Tool into your own webapp if you write your own javascript to communicate with the WIT html element (named tf-interactive-inference-dashboard) to provide it with data, provide it with model results, and respond to its events. This is how our web demos of the What-If Tool work (like https://pair-code.github.io/what-if-tool/iris.html, with source code https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-iris-demo.html).
> 
> See all the code for those demos at https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo including the build files used to create the single html page with all dependencies built in (such as that iris.html demo).

Thanks for your reply.  But do I have to write my own js code? As I konw ,WIT can be used to analyse any kind of models(including TF model) by calling `set_custom_predict_fn` . And have tried to use WIT to analyse my own sklearn model in jupyter notebook, and it did work.  I can just use  WIT in jupyter as well as in official WEB Demo without writing any  js code. So what I want to know is that if it is possible for me to dispaly the model(Like TF model, sklearn model and etc.) analyse result in my web application just like in jupyter.  Perhaps I just need pass `config_builder` and my test data to BE from FE, and get the display content from BE?

**Comment by jameswex** [comment]
At this point, to run the What-If Tool in your own webapp you will need to write your own JS code to wrap the tf-interactive-inference-dashboard element and handle the communication between that element and the backend.
