### ISSUE TITLE
WTF havent you fixed this already!? 

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorboard#3035]
Docker and Tensorboard - not serving TB err_connection_reset

YOU KNOW ABOUT THIS FIX IT

..and yes i am exposing my ports blah blah blah:
```
docker run --rm -it --runtime=nvidia --user $(id -u):$(id -g) --group-add container_user --group-add sudo -v "${PWD}:/app" -p 8888:8888 -p 6006:6006 mycontainer

```

**Comment by wchargin** [comment]
Hi @joehoeller,

Please be polite. There’s no need to flame us.

You’ll need to be more precise about what problem you’re running into.
The standard TensorFlow Docker images work fine with TensorBoard for me.
Running

```
docker run --runtime=nvidia -p 8888:8888 -p 6006:6006 --rm \
    tensorflow/tensorflow:2.0.0-gpu-py3-jupyter
```

correctly boots up a Jupyter notebook instance with TensorFlow and
TensorBoard installed, and the `%tensorboard` notebook extensions work
as intended. And running

```
docker run --runtime=nvidia -p 6006:6006 --rm \
    tensorflow/tensorflow:2.0.0-gpu-py3 \
    tensorboard --bind_all --logdir dockerlogs
```

successfully launches TensorBoard on port 6006, which I can connect to
from my machine and from other machines on the network.

We don’t have access to your “`mycontainer`” image. Please follow the
instructions listed in the issue template and provide all of the
requested information, including a minimal code sample that reproduces
your problem. Then, we can re-open the issue.

**Comment by joehoeller** [comment]
I am using Docker Anaconda OpenCV and PyTorch
