### ISSUE TITLE
WIT can not display in jupyter

### ISSUE THREAD

**Issue by mengban** [tensorflow/tensorboard#3036]
My mac with python3.7:
jupyter --version 
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.10.1
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

and my remote host with python2.7:
jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 5.7.8
qtconsole        : 4.5.5
ipython          : 5.8.0
ipykernel        : 4.10.1
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

The same code works well in my mac, but when i open the the url of jupyter notebook in  remote host. The WIT doesn't display, And I have already enable nbextension by:

jupyter nbextension install --py witwidget --user
jupyter nbextension enable witwidget --user --py

The browser is Chrome 78.0.3904.108-64bit.
I don't konw what's wrong with me.

**Comment by jameswex** [comment]
Can you open up your chrome developer's console and paste in any error you are seeing in the console related to loading of witwidget or the what if tool? Thanks.

**Comment by mengban** [comment]
Thanks a lot. I have tried  a new remote machine and follow the instructions again. Anyway it worked well this time...
