### ISSUE TITLE
“Cycle in the workspace file” when building on macOS

### ISSUE THREAD

**Issue by mengban** [tensorflow/tensorboard#3043]
MacOS:10.15.1
TB version: clone from TB master just now
bazel version: 1.2.1
when i run 
` 
bazel run tensorboard  -- --logdir ../tmp
`
ERROR: Failed to load Starlark extension '@npm_bazel_typescript//:index.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @npm_bazel_typescript
This could either mean you have to add the '@npm_bazel_typescript' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.071s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by wchargin** [comment]
Hi @mengban! Thanks for the report. That’s interesting—I use Bazel 1.2.1
on Linux and haven’t run into this. I’ve asked the macOS users on our
team to comment; we’ll get back to you shortly.

(As a wild guess, you could try running `yarn` in the base directory of
the TensorBoard repository…? This shouldn’t be necessary in principle,
and it may or may not work.)

**Comment by wchargin** [comment]
We’re still looking into this, running into unrelated problems on the
macOS build relating to macOS security model and gRPC code generation.
We’ll update you when we have more information.

**Comment by bileschi** [comment]
Hi @mengban can I ask you for some more details?  Are you doing this operation in a virtual env?  What recipe did you follow to install the dependencies?  Did you follow the instructions at https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md ?

Finally, can you share your default python version?
`python --version`

I was able to build and run tensorboard on my machine (MacOS 10.14.6) (TB clone from TB just now) (bazel version 1.2.1) with the following commands

```
python3 -m venv ~/venv/py3venv
source ~/venv/py3venv/activate
pip install tf-nightly -r tensorboard/pip_package/requirements.txt -r tensorboard/pip_package/requirements_dev.txt
bazel run //tensorboard -- --logdir ~/logdir-root/getting-started/logs
```

**Comment by mengban** [comment]
Hi @bileschi  I just print my python version and it's python 3.7.0.
what i did is different from the instruction are:
1.  I run bazel not in virtual env
2. I didn't use tf-nightly but tf 1.14 in my installed python packages.
And I have  run TB successfully  strictly follow the instruction.
Thanks a lot.

**Comment by wchargin** [comment]
Great—glad to hear that you’ve gotten it working, and thanks for letting
us know!

**Comment by bileschi** [comment]
Thanks @mengban !   Best of luck with your project!
