### ISSUE TITLE
float32 parameters cannot be JSON serialised, looking for a workaround for using hparams.RealInterval

### ISSUE THREAD

**Issue by OscarVanL** [tensorflow/tensorboard#3057]
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

```
WARNING: Could not generate requirement for distribution -ensorflow-gpu 2.0.0 (c:\users\oscar\anaconda3\envs\______________\lib\site-packages): Parse error at "'-ensorfl'": Expected W:(abcd...)
INFO: installed: tensorboard==2.0.2
INFO: installed: tensorflow-gpu==2.0.0
INFO: installed: tensorflow-estimator==2.0.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.0.2'

--- check: tensorflow_python_version
2019-12-19 16:41:00.775261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
INFO: tensorflow.__version__: '2.0.0'
INFO: tensorflow.__git_version__: 'v2.0.0-rc2-26-g64c3d382ca'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\Oscar\\Anaconda3\\envs\\______________\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'Oscar-XPS-Laptop.lan'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\Oscar\AppData\Local\Temp\.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=9570149209514493, st_dev=2585985196, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1576773155, st_mtime=1576773155, st_ctime=1576764046)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\Oscar\\Anaconda3\\envs\\______________\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
WARNING: Could not generate requirement for distribution -ensorflow-gpu 2.0.0 (c:\users\oscar\anaconda3\envs\______________\lib\site-packages): Parse error at "'-ensorfl'": Expected W:(abcd...)
INFO: pip freeze --all:
absl-py==0.8.1
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
cachetools==3.1.1
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.1
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
gast==0.2.2
google-auth==1.8.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.25.0
h5py==2.10.0
idna==2.8
importlib-metadata==1.2.0
ipykernel==5.1.3
ipython==7.10.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==5.2.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
numpy==1.17.4
oauthlib==3.1.0
opt-einsum==3.1.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
pip==19.3.1
prometheus-client==0.7.1
prompt-toolkit==3.0.2
protobuf==3.11.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
Pygments==2.5.2
pyparsing==2.4.5
pyrsistent==0.15.6
python-dateutil==2.8.1
pytz==2019.3
pywin32==223
pywinpty==0.5.5
pyzmq==18.1.0
qtconsole==4.6.0
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
Send2Trash==1.5.0
setuptools==42.0.2.post20191203
six==1.13.0
tensorboard==2.0.2
tensorflow-estimator==2.0.1
tensorflow-gpu==2.0.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wheel==0.33.6
widgetsnbextension==3.5.1
wincertstore==0.2
wrapt==1.11.2
zipp==0.6.0




No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.
```
</details>

### Next steps

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):
  - Screenshot, if it’s a visual issue:

## Issue description

Hi, my issue relates to trying to use RealInterval values for HP Tuning. This requires you to convert it to a plain value so that it can be JSON serialised by TensorBoard for logging hparams. I used a method described in [this past issue](https://github.com/tensorflow/tensorboard/issues/2348) after experiencing issues following this [example notebook](https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams).

[This answer](https://github.com/tensorflow/tensorboard/issues/2348#issuecomment-504687606) suggests using .numpy() to get a float32 value of the RealInterval value. To be specific, I run `for dropout1 in tf.linspace(DROPOUT_1.domain.min_value, DROPOUT_1.domain.max_value, 5).numpy():` during optimization.

With the float32 value, when execution reaches the line `hp.hparams(hparams)` or the callback `hp.KerasCallback(log_dir, hparams)` I get this error: `TypeError: Object of type float32 is not JSON serializable`.

As a workaround, I could convert the float32 value to a String so that it can be serialized, then convert it back with `float(dropout1)` before using it as my dropout value. It's silly, and when I tried it my tensorboard console got spammed with `hparams_plugin.py:121] HParams error: Cannot use an interval filter for a value of type: <class 'str'>, Value: 0.1` errors and nothing shows on the HPARAMS tab.
![image](https://user-images.githubusercontent.com/7999692/71193345-e5380200-2281-11ea-93fe-ce4cf41f03d9.png)

![image](https://user-images.githubusercontent.com/7999692/71193317-d2bdc880-2281-11ea-9a0b-daff6b17d64c.png)

I could also try using an IntInterval and just divide the value by 10 when used as the dropout value and then hparams can log that without issue.

But this all seems a bit mad, surely there's a way to use RealIntervals without these odd workarounds?

**Comment by OscarVanL** [comment]
Nevermind, brain fart. (It's past 5pm so my brain has shut down). In the future, just run .item() on the np.float32 to get the proper Python type... Sigh...

**Comment by wchargin** [comment]
Hi @OscarVanL! Thanks for the report. This is a totally valid point:
you’re right that running `.item()` is sufficient, but it shouldn’t be
necessary. There’s a bit of a subtlety here: `np.float64` values are
JSON-serializable, but `np.float32` values aren’t. Numpy’s default
floating-point default is `float64`, while TensorFlow’s is `float32`.
So, confusingly, the default behaviors are different:

```python
>>> json.dumps(np.linspace(1.0, 2.0, 5)[0])
'1.0'
>>> json.dumps(tf.linspace(1.0, 2.0, 5).numpy()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

You can fix this on the TensorFlow side with an explicit cast…

```python
>>> json.dumps(tf.cast(tf.linspace(1.0, 2.0, 5), "float64").numpy()[0])
'1.0'
```

but clearly you shouldn’t need to do that, as it’s a widening conversion
that can’t possibly lose information. I’ll patch `hp.hparams` to perform
the cast for you.

Thanks for bringing this to our attention!

**Comment by OscarVanL** [comment]
Thanks for the explanation! Awesome :)
