### ISSUE TITLE
Bind the graph plugin's "selected run" to the URL hash

### ISSUE THREAD

**Issue by mantos730** [tensorflow/tensorboard#306]
Hi,

I've multiple runs in tensorboard, and the graph of these runs can be shown by click dropdown list.
I would like to ask is it possible to show graph of particular run directly (maybe given run name in URLs).

Or it always show the first run, and require user to pick up.

Thanks.

**Comment by wchargin** [comment]
@chihuahua what do you think?

**Comment by chihuahua** [comment]
To be clear, what we want here is for instance a URL parameter that specifies a run that the graph dashboard can use to load a particular graph?

That sounds potentially useful, although runs of the same model often use the same graph (It's just that different parts of the graph are executed.). @mantos730, I am curious why that feature would help you.

**Comment by mantos730** [comment]
Hi,
My colleagues and I put our event logs in same folder with different sub-folder name. So we can use one tensorboard URL to see each others information.
Some time I want to send a URL to my colleague to see a particular run. So I just wonder can I share a URL with some parameter to others, so that they don't need to find a run in dropdown list.

Thanks.

**Comment by wchargin** [comment]
Right: the request is for the graph dashboard's "selected run" parameter to be two-way-bound with the hash just as with the run selection state used by the other dashboards. Seems very reasonable to me.

@chihuahua `tf-storage` should have the relevant helpers to implement this
