### ISSUE TITLE
Tensorboard Embedding Projector Custom Search Bug

### ISSUE THREAD

**Issue by pujaarajan** [tensorflow/tensorboard#3069]
Context: I am using the online version of the Tensorboard Embedding Projector. I uploaded my own checkpoint and metadata TSVs with 681909 rows each. I clicked on the "CUSTOM" tab, and then found a bug when I tried to search.

Current Behavior/Bug: I am unable to click on the search bar that says "Search by". When I do click anywhere in the search bar, a drop down appears with the option "label". If I click label and try to search again, there is no difference. There is no error message.

Expected Behavior: I would be able to search, or be given an error message indicating why I'm unable to.

Note: Reposting from [here](https://github.com/tensorflow/tensorflow/issues/35105). Requested by @oanush.

**Comment by pindinagesh** [comment]
@pujaarajan 

I tried reproducing the above issue, i am able to search something in search bar and it's working fine. Please have a look at  attached screenshot below. Hope it helps. Thanks!

![Screenshot 2022-01-20 1 45 55 PM](https://user-images.githubusercontent.com/89831657/150300871-08207c43-b33c-416d-9693-e79401a941a5.png)
