### ISSUE TITLE
Modify TensorBoard to support plugin_data as an optional field.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#312]
After PR https://github.com/tensorflow/tensorflow/pull/11952 goes in, the `plugin_data` field will be optional instead of repeated (for the motivation on why we made this change, see the TensorFlow PR). 

After that change enters nightly TensorFlow (and TF r1.3), we should change this line in the event accumulator to read 1 single plugin data proto.
https://github.com/tensorflow/tensorboard/blob/da8db355b64a0954342a0af56fe6eaad2542a203/tensorboard/backend/event_processing/event_accumulator.py#L372

as well as a couple of other places such as this line in a test that indexes into plugin_data:
https://github.com/tensorflow/tensorboard/blob/cb929ed7653a3a58333c63ccaeab7a700c5448c6/tensorboard/plugins/histogram/summary_test.py#L81

Other than those lines, as @jart noticed, TensorBoard will still be able to read pre-existing protobufs that contain summaries, which is nice. We should also update TensorFlow master as well as internal logic to reflect this change.

**Comment by wchargin** [comment]
To be more robust, I think we should just say: "After that change enters nightly TensorFlow (and TF r1.3), run `git grep plugin_data` and update all occurrences accordingly", yes?

Updates to TensorFlow master are all handled in that TensorFlow PR, yes?

Updates to (Google-)internal logic should be handled at GitHub-to-Google import time, yes?

**Comment by wchargin** [comment]
(Perhaps I should clarify on the rationale: we should `grep` at the time we make the changes instead of having a pre-determined list so that uses introduces *after* we make this list—such as in #305—are not forgotten.)

**Comment by wchargin** [comment]
@chihuahua The TF pull request was merged into r1.3, but nightlies are cut from master, so today's nightly still has the field as repeated.

**Comment by chihuahua** [comment]
+1, tensorflow/tensorflow#12012 modifies master.
