### ISSUE TITLE
Is it possible to have a live stream to tensorboard.dev?

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorboard#3135]
I recently became aware of the [tensorboard.dev](https://tensorboard.dev/) product. From what I understand (`tensorboard dev upload --logdir logs`), it's only possible to upload a directory once.

I would like to know if it's possible to have a feature where we stream the logdir to tensorboard.dev. 

One of the potential applications is when you have a remote server on which you have a training going on, and you want to just monitor from time to time the training without necessarily connecting to the server (say on your phone, or for someone who doesn't have access to the server, or if connecting to the server requires some steps that you don't want to take each time, like a VPN setup.).

**Comment by wchargin** [comment]
Hi @zaccharieramzi! The uploader does stream logs to TensorBoard.dev
live. You’re correct that (currently) it’s not possible to append to an
existing experiment once you stop the uploader, but if you leave the
uploader running then any newly added logs under the specified logdir
should be uploaded.

I’ve just tested this with TensorFlow and TensorBoard 2.1.0, and it
seems to be working correctly. Can you give this a shot and let us know
if it’s working for you? If not, it might be a bug—we’ll take a look.

**Comment by zaccharieramzi** [comment]
Hi @wchargin ! Thanks for your quick answer.

Indeed I had not even tried, I just saw the commands and thought it was a one-shot upload. Just tested in 2.1 as well and everything seems to work fine. 

Maybe the docs could be a bit more explicit (don't know tbh)?

Anyway closing as this is clearly off topic and thanks.

**Comment by wchargin** [comment]
The command-line interface prints

> Upload started and will continue reading any new data as it's added to
> the logdir. To stop uploading, press Ctrl-C.

when started, but maybe it also merits a FAQ entry. Thanks for the
feedback, and glad that it seems to be working!

**Comment by zaccharieramzi** [comment]
Yes yes exactly I saw that with the command-line help, but I was referring to the website actually. You welcome!
