### ISSUE TITLE
High I\O when using tensorboard over sshfs

### ISSUE THREAD

**Issue by adizhol** [tensorflow/tensorboard#3177]
I'm not sure if this is a problem with my sshfs drivers, but I'm having about 30Mb/s upload and download once tensorboard is running.
I tried to check-off the "update-every-30s", but still the same.

using tensorboard 2.1

**Comment by gowthamkpr** [comment]
@adizhol Can you please elaborate the issue. What are you uploading/downloading?

**Comment by adizhol** [comment]
@gowthamkpr 
It's the tesnorboard backend doing network access over sshfs.
When monitoring the remote machine (where the logs are stored), I see the bandwidth usage.

**Comment by wchargin** [comment]
Hi @adizhol! The “update every 30s” checkbox affects how often the
frontend requests new data from the backend, but doesn’t affect how
often the backend reloads internally. The `--reload_interval` option
controls that, and defaults to 5 seconds.

Would it suffice for you to pass `--reload_interval 30` or similar to
your `tensorboard` invocation?

**Comment by adizhol** [comment]
@wchargin It worked. Thanks!

**Comment by wchargin** [comment]
Great! Glad to hear it, and thanks for letting us know.
