### ISSUE TITLE
can't assign to operator #tensorboard#pycharm

### ISSUE THREAD

**Issue by Gowrisankar97** [tensorflow/tensorboard#3199]
i am getting  cannot assign to operator  error while running tensorboard --logdir-tflogs in pycharm terminal as well as in  python console . i couldn't able to find the right solution ,anyone please help to resolve this issue

**Comment by wchargin** [comment]
Hi @Gowrisankar97! It sounds like you’re trying to execute the
TensorBoard command from a Python shell rather than a command line
shell. Can you make sure that you’re using a terminal and try again? If
you still run into problems, please post a screenshot showing the full
command that you tried to run.

**Comment by rmothukuru** [comment]
@Gowrisankar97,
Can you please respond to @wchargin's comment. Thanks!

**Comment by Gowrisankar97** [comment]
solved

**Comment by 123carmen** [comment]
please tell me how you solve this problem, i have the same problem.
![image](https://user-images.githubusercontent.com/52279017/142502222-867faac9-b0fa-4944-9207-a86ddccbd661.png)

**Comment by 123carmen** [comment]
thank you in advance, I installed tensorboard, tensorflow, tensorboardX,
and 
from tensorboardX import SummaryWriter
writer = SummaryWriter("./log/" + datetime.now().strftime("%Y%m%d-%H%M%S"))
writer.add_scalar("test accuracy", test_acc, epoch)
I have generated log/ events.
but i can not start this tensorboard web

please help me, thank you

**Comment by 123carmen** [comment]
i have used
tensorboard --logdir='log' --host 127.0.0.1
tensorboard --logdir=log --host 127.0.0.1
tensorboard --logdir=='log' --host 127.0.0.1
tensorboard --logdir="log" --host 127.0.0.1
tensorboard --logdir=log\ --host 127.0.0.1
tensorboard --logdir=.\log\ --host 127.0.0.1

**Comment by 123carmen** [comment]
I am sorry i fixed this. I post here, hope it will help others. 
here is the link i found useful, thank you this post
https://www.datacamp.com/community/tutorials/tensorboard-tutorial

![image](https://user-images.githubusercontent.com/52279017/142504396-6100eb3c-55b3-4222-97cc-39b537460d7e.png)
