### ISSUE TITLE
Bring tensorboard 2.1 to conda

### ISSUE THREAD

**Issue by cossio** [tensorflow/tensorboard#3208]
The tensorboard version available on conda is 2.0.0 (https://anaconda.org/anaconda/tensorboard). Please update the conda package to latest release, 2.1.

**Comment by stephanwlee** [comment]
@cossio we do not officially maintain anaconda packages.

The ownership model of anaconda is very unclear to me at the moment, but I will ask around whether anyone on the owner owns it (if anaconda has no concept of owner, which sounds very dangerous, feel free to upload on your own).

**Comment by stephanwlee** [comment]
Ok, I think I know very little about Anaconda and their philosophy but it looks like `anaconda` is the owner of that package (https://anaconda.org/anaconda). Please ask the owner of the distribution to make the update.
