### ISSUE TITLE
werkzeug 1.0.0 removed symbols

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#3229]
https://pypi.org/project/Werkzeug/1.0.0/ was release 2020-02-06 and it breaks our tests.

There are about 5 instances where we use `werkzeug.BaseResponse` (all in tests) but the API is now deprecated (`werkzeug.wrappers.BaseResponse` may be what we want).

Do note that this should impact CI, too, very soon (https://github.com/tensorflow/tensorboard/blob/38a326bd55b17d92bc60baf323b4e09c4a3f5f6f/tensorboard/pip_package/requirements.txt#L30)

**Comment by wchargin** [comment]
> ```
> werkzeug >= 0.11.15 
> ```

At some point we should probably go through and constrain these by major
version boundaries…
