### ISSUE TITLE
PROFILE-EMPTY files, blank Profiler

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorboard#3244]
Using latest `tf-nightly` per suggestion [here](https://github.com/tensorflow/tensorboard/issues/3117) to fix blank TensorBoard, but now the Profiler is blank (img below), and I have these:

![image](https://user-images.githubusercontent.com/16495490/74433312-98d00380-4e79-11ea-92fc-cd6b98c8407c.png)

Also tried `PROFILE (MOVED)`'s suggestion (below), and [Profiler APIs](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras#profiler_apis). Full code at bottom.

Any resolution?

<hr>

**Blank profiler**: 

![image](https://user-images.githubusercontent.com/16495490/74433663-480cda80-4e7a-11ea-996a-d02644d4a27e.png)

**PROFILE (MOVED)**

![image](https://user-images.githubusercontent.com/16495490/74433787-8904ef00-4e7a-11ea-8d13-72233776d90c.png)

Installing the latest suggested [tensorboard_plugin_profile](https://test.pypi.org/simple/tensorboard-plugin-profile/) (only `.tar.gz`, not `.whl`) via `pip install tar_gz_abspath` and rerunning `tensorboard --logdir=...` yields

![image](https://user-images.githubusercontent.com/16495490/74434255-7d65f800-4e7b-11ea-86b2-b0e203e2717c.png)

<hr>

**Full code**:

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import TensorBoard

def make_model(shape_in, shape_out, rbn_configs):
    ipt = Input(batch_shape=shape_in)
    out = LSTM(shape_out[-1], return_sequences=True)(ipt)
    model = Model(ipt, out)
    model.compile('adam', 'mse')
    return model

def make_data(shape_in, shape_out, n_batches=1):
    shape_in  = (n_batches*shape_in[0],  *shape_in[1:])
    shape_out = (n_batches*shape_out[0], *shape_out[1:]) 
    return np.random.randn(*shape_in), np.random.randn(*shape_out)

tb_logdir = r"tb_logs\tb_profiler\log_4\\"
tb_profiler = TensorBoard(log_dir=tb_logdir, profile_batch=2, 
                          write_graph=False, histogram_freq=1)
shape_in  = (32, 150, 500)
shape_out = (32, 150, 500)
X, Y = make_data(shape_in, shape_out, n_batches=5)
model = make_model(shape_in, shape_out)

model.fit(X, Y, callbacks=[tb_profiler]) 
# Profiler API code omitted, but results are same
```

**Comment by psybuzz** [comment]
Thanks for the report.  All versions of TensorBoard currently have a broken trace viewer on all updated browsers.  Chromium-based browsers used to work until M80 was recently released with a breaking change.

Some workarounds can be found in https://github.com/tensorflow/tensorboard/issues/3209#issuecomment-584292018

Please follow https://github.com/tensorflow/tensorboard/issues/3209 for updates.
