### ISSUE TITLE
Evaluate the TensorFlow object detection model

### ISSUE THREAD

**Issue by ighadahsh** [tensorflow/tensorboard#3259]
How can I evaluate my object detection model in a simple and understandable way, I used the TensorFlow's Object Detection API, but I didn’t understand the Tensorboard graphs. Can I evaluate it manually? 
Any help? :(

**Comment by rmothukuru** [comment]
@ighadahsh,
Can you please elaborate your requirement. Thanks!

**Comment by rmothukuru** [comment]
@ighadahsh,
Can you please provide more details about your requirement as stated in my previous comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
