### ISSUE TITLE
Want To Contribute to the team . New student to start contributing to the team

### ISSUE THREAD

**Issue by yvkrishna** [tensorflow/tensorboard#3322]
Hello ,
I am vedha krishna . I am a student working in deeplearning. I want to contribute to this team.
I have wrote machine learning codes in matlab and even presented a conference paper on this topic. I want to move to tensorflow. I have taken few courses in udacity and got familiar in codding with tensorflow. I am so much interested in contributing to this team. I do not have much experience in open course contributing so i need a help of the mentor who can help me in guiding for the initial days. I hope I would get a good support
Thank you.

**Comment by gowthamkpr** [comment]
@yvkrishna Thank you for your interest. But I am afraid to say that this is not the right place to post this question. There are many [Tensorflow communities](https://www.tensorflow.org/community)  where you can seek help from. 

Going to close this issue. I would recommend you to sign up for the community and start contributing. Thank you!
