### ISSUE TITLE
tensorboard server requirment

### ISSUE THREAD

**Issue by zouxinhua** [tensorflow/tensorboard#3341]
I hava  a requirment as below:
tensorboard support one graph instance in current version.

I want to deploy one tensorboard server supporting multi graph.

start: ./tensorboard --logdir root-path

many graph instance log in root-path,like root-path/A ,root-path/B, root-path/C

and I can visit graph by 
http://serverIP:port/experiment/A(B,C.....) or http://serverIP:port/A(B,C....)/

just like tensorboard.dev, but I want deploy in local envs.

can you give some solution ?

**Comment by ericdnielsen** [comment]
Locally, all runs stored under the same logdir will be loaded into the instance.  Within the graph plugin you can select the desired graph with the Run selector.

**Comment by rmothukuru** [comment]
@zouxinhua,
Cana you please respond to @ericdnielsen's comment. Thanks!

**Comment by zouxinhua** [comment]
@ericdnielsen @rmothukuru
