### ISSUE TITLE
link is not working

### ISSUE THREAD

**Issue by youyeg** [tensorflow/tensorboard#3342]
This link is in this page is not working:
the link: https://github.com/tensorflow/tensorboard/blob/master/docs/guide/summaries_and_tensorboard.md

the page:
https://github.com/tensorflow/tensorboard/blob/master/docs/r1/graphs.md

**Comment by ericdnielsen** [comment]
William, 

I looked around a little bit, the closest target page I could find was this:
https://github.com/tensorflow/tensorboard/blob/master/docs/r1/summaries.md

Can you confirm that's the correct destination for the link before I make a PR?

**Comment by wchargin** [comment]
Yep, that looks right to me; the link text is “TensorBoard: Visualizing
Learning”, which is the title of that page. Looks like there are two
such broken links in `graphs.md` and one in `histograms.md`.

A bunch of places still link to that article by its old TensorFlow.org
URL, <https://www.tensorflow.org/get_started/summaries_and_tensorboard>,
so it’d be great if we could get a redirect from there to the right
place, too. (There’s a redirects file internally that we could extend.)
