### ISSUE TITLE
Data does not display

### ISSUE THREAD

**Issue by sheromon** [tensorflow/tensorboard#3345]
In a particular environment, my scalar plots are not loading. Most of the webpage renders normally, including the background, the slider bars, and the tags (e.g. "AP_standard", "total_loss"), and the axes show up, but instead of scalar plots, there are blue spinning circles.

Using the browser developer tools, I can see that the HTTP GET requests succeed for "/", "index.js", "plugins_listing", "environment", "runs", "experiments", and "tags" but fail for "scalars?[object+Object]=". For the failures, the status code is 404 NOT FOUND and the response is `Not found: No scalar data for run=None, tag=None`. The response for "runs" was good, I believe: `{0: "."}`. However, the response for "tags" was like this:
```
Object
AP_agnostic: Object
description: ""
displayName: "AP_agnostic"
total_loss: Object
description: ""
displayName: "total_loss"
```
The params for the failed scalars request was this:
```
Query string
[object+Object]: ""
```

### Environment
I'm ssh-ing from a host machine to an instance using -L 6006:127.0.0.1:6006, running TensorBoard on the instance, and viewing it using a browser on the host machine. This has worked for me in a different environment.

Host OS: CentOS Linux release 7.4.1708 (Core)
Instance OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
Browser: FirefoxESR 52.5.1 (64-bit)

CUDA:
/usr/local/cuda/lib64/libcudadevrt.a
/usr/local/cuda/lib64/libcudart.so -> libcudart.so.10.1
/usr/local/cuda/lib64/libcudart.so.10.1 -> libcudart.so.10.1.168
/usr/local/cuda/lib64/libcudart.so.10.1.168
/usr/local/cuda/lib64/libcudart_static.a

TensorBoard version:
tensorboard --version
TensorFlow installation not found - running with reduced feature set.
2.1.0

**Comment by sheromon** [comment]
We just resolved my problem by installing the Chromium browser. I guess this is an incompatibility with this particular version of Firefox?

**Comment by rmothukuru** [comment]
@sheromon,
As the issue is resolved, can you please confirm if we can close this issue. Thanks!

**Comment by sheromon** [comment]
I was hoping someone could comment on what was happening and/or browser recommendations so that I can be more educated, but yes, it's resolved, and we can close it.
