### ISSUE TITLE
Request for an identity projection for low-dimensional embeddings

### ISSUE THREAD

**Issue by JerryLingjieMei** [tensorflow/tensorboard#3353]
Hi, I am working on a project related to concept embeddings. I need to visualize embedding A (i.e. object embeddings) based on the PCA of embedding B(i.e. concept embeddings). What I have done is to calculate the PCA transform of B, apply it onto A so that it becomes a 3D/ 2D tensor, and try to visualize it in tensorboard projector. However, the current version doesn't support identity projection - every projection methods is not identity. On the other hand, using a mesh to denote it will allow the use of metadata (labels) or label images. Is there a  solution to this.

**Comment by bileschi** [comment]
@dsmilkov, do you know if there is a way to operate the projector in a mode where the data has already been embedded in a 3 dimensional (or lower) space and the operator just wants to view that data?

**Comment by dsmilkov** [comment]
There isn't a way to choose the identity projection in the UI. If you don't mind a coordinate shift (i.e. your coordinates are not labeled), you can disable the `Sphereize data` checkbox, and the PCA projection we will do from 3D to 3D shouldn't distort your data.

**Comment by bileschi** [comment]
JerryLingjieMei@ if this answers your question can you close the issue?  Thanks
