### ISSUE TITLE
How to show the profile tab in tensorboard?

### ISSUE THREAD

**Issue by tomtang110** [tensorflow/tensorboard#3389]
## Environment:
chrome version: 80.0.3987.132
tensorflow version: 2.1.0
tensorboard version: 2.1.0

## issue:
I customised a model and use tf.summary to record data. But in the trace_on function, I found it can't activate the profile tab in tensorboard.

the code is shown below:
``` 
def call(self, inputs):
        global flag_kg,flag_trace
        data, flag = inputs
        if flag == 'rs':
            if flag_trace == 0:
                with train_summary_writer.as_default():
                    tf.summary.trace_on(True,True)
                    scores = self.call_rs(data)
                    tf.summary.trace_export('modelrs',0,train_log_dir)
                    flag_trace = 1
            else:
                scores = self.call_rs(data)
        if flag == 'kge':
            if flag_kg == 0:
                with train_summary_writer.as_default():
                    tf.summary.trace_on(True,True)
                    scores = self.call_kge(data)
                    tf.summary.trace_export('modelkg',0,train_log_dir)
                flag_kg = 1
            else:
                scores = self.call_kge(data)
        return scores
```
```
def train(args,data):

    n_user, n_item, n_entity, n_relation = data[0], data[1], data[2], data[3]
    train_data, eval_data, test_data = data[4], data[5], data[6]
    kg = data[7]
    model = MKR(args, n_user, n_item, n_entity, n_relation)
    for step in range(args.n_epochs):
        tf.summary.experimental.set_step(step)
        np.random.shuffle(train_data)
        start = 0
        while start < train_data.shape[0]:
            one_step_data = get_feed_dict_for_rs(train_data,start,start+args.batch_size)
            loss = model.train_rs((one_step_data[:-1],'rs'),(one_step_data[-1]).astype(np.float32))
            print('rs_loss: ',loss.numpy())
            start += args.batch_size

        tf.summary.scalar('rs_loss', loss, step=step)

        # if step % 4 == 0:
        #     tf.summary.histogram('embed:0', model.trainable_variables[0], step=step // 4 )
        # KGE training
        if step % args.kge_interval == 0:
            np.random.shuffle(kg)
            start = 0
            while start < kg.shape[0]:
                one_step_data = get_feed_dict_for_rs(kg,start,start+args.batch_size)
                loss = model.train_kge((one_step_data,'kge'))
                print('kg_loss: ',loss.numpy())
                start += args.batch_size
            tf.summary.scalar('kg_loss', loss, step=step)
```
```
with train_summary_writer.as_default():
    train(config,data)
```
The scalar and histogram tab could be seen but the profile tab is not activated. 
Could you help me deal with the problem?

![屏幕快照 2020-03-18 09 57 16](https://user-images.githubusercontent.com/33299522/76917598-e4ede800-68fe-11ea-8fc2-57037e4dd514.png)

**Comment by bileschi** [comment]
Hi!  The problem is probably either that the profile summaries are not being written, or the tensorboard is not seeing them.

Can you try following the advice in this codelab, https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras
including using the most recent versions of tensorflow & tensorboard (you may need to use tf-nightly until 2.2 is released)

**Comment by bileschi** [comment]
Following up here, were you able to follow the advice in the colab to get the profiler to show, or did it still not work? If you are still having a problem can you re-open this issue?  I was able to use the colab to see the profile plugin there, but there are many differences.

**Comment by rashidch** [comment]
Hey, I am having the same problem both on Windows 10 and Colab. Colab screen attached. 

![image](https://user-images.githubusercontent.com/8865579/100691964-cd8b5800-33c4-11eb-999c-39b1c6398c95.png)

**Comment by tylerdoll** [comment]
Did anyone ever figure this out? I am also having this issue.

**Comment by helinwang** [comment]
+1

**Comment by psybuzz** [comment]
I just checked the Colab tutorial and can also confirm that the Profiler plugin does not appear by default.  For those who need it, it is still usable when opening the "inactive" dropdown menu and selecting the dashboard from there.

![image](https://user-images.githubusercontent.com/2322480/106067526-b5c60c80-60b3-11eb-8aa2-d4ba4731d328.png)

Making the Profile plugin show up automatically when there is profiler data is something specific to that plugin.  Now that the plugin is a standalone Python package and has code in its own repo separate from TensorBoard, I think it's best to file an issue at: https://github.com/tensorflow/profiler

**Comment by helinwang** [comment]
I used TF estimator API with tf.estimator.ProfilerHook, and the profile tab never show up.
Turns out tf.estimator.ProfilerHook is *not* compatible with TensorBoard at all. I had to use chrome to load the timeline*.json instead: https://towardsdatascience.com/howto-profile-tensorflow-1a49fb18073d?gi=af9691f1f742

**Comment by tylerdoll** [comment]
> I just checked the Colab tutorial and can also confirm that the Profiler plugin does not appear by default.  For those who need it, it is still usable when opening the "inactive" dropdown menu and selecting the dashboard from there.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2322480/106067526-b5c60c80-60b3-11eb-8aa2-d4ba4731d328.png)
> 
> 
> 
> Making the Profile plugin show up automatically when there is profiler data is something specific to that plugin.  Now that the plugin is a standalone Python package and has code in its own repo separate from TensorBoard, I think it's best to file an issue at: https://github.com/tensorflow/profiler

So my issue is it doesn't even appear in the inactive tab. It doesn't appear anywhere, regardless if there's data or not.

**Comment by fantauzzi** [comment]
I had the same issue under Ubuntu 20.04 with TF and TB 2.4.1, resolved installed the Python package `tensorboard_plugin_profile`. There was no mention to that requriement in the documentation www.tensorflow.org/guide/profiler , I found it mentioned in the Colab tutorial/example https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

**Comment by tinyxuyan** [comment]
@tylerdoll Have you solved your issue? I can not show the profile tab in tensorboard, too. However, I have installed tensorboard_plugin_profile.
Detailed versions:
tensorflow-gpu: 2.3.1+nv
tensorboard:  2.2.0
tensorboard-plugin-profile: 2.2.0

**Comment by tylerdoll** [comment]
> @tylerdoll Have you solved your issue? I can not show the profile tab in tensorboard, too. However, I have installed tensorboard_plugin_profile.
> Detailed versions:
> tensorflow-gpu: 2.3.1+nv
> tensorboard: 2.2.0
> tensorboard-plugin-profile: 2.2.0

I have not. I ended up just standing up a different instance with the newer TF and am transferring logs between the two.
