### ISSUE TITLE
hparams parallel coordinate view should adjust width for number of axes

### ISSUE THREAD

**Issue by pyscorcher** [tensorflow/tensorboard#3414]
### Issue

If we have a large number of hparams and metrics (= a large number of axes) in the parallel coordinate view we obviously need a wide plot pane to show all the axes in a meaningful way. Note that here we have more than ten axes that are still very well visible.

![grafik](https://user-images.githubusercontent.com/59569502/77305160-d7b56c80-6cf5-11ea-9221-cf7ca2be195b.png)

But if you then disable some of them, the spacing between the remaining axes just gets stretched, and if there are sufficiently many they get stretched beyond a usable distance. Compared to the previoius screenshot we now only have five axes selected, but only three of them are visible. But as we saw there is room for at least ten of them.

![grafik](https://user-images.githubusercontent.com/59569502/77305100-bfdde880-6cf5-11ea-9e39-8c9ea51298a5.png)

### Suggestion
My suggestion is that that the spacing between the axes should remain constant no matter how many parameters there are. Optionally one could introduce a slider/spinbox to adjust the spacing to your needs.

To replicate this issue you can use following python code to generate a summary file (needs pytorch),

```
from torch.utils.tensorboard import SummaryWriter
tb = SummaryWriter()
tb.add_hparams({"hparam"+str(k): k for k in range(10)}, {"metric"+str(k): k for k in range(10)})
```

then start tensorboard with `tensorboard --logdir=runs` and open `localhost:6006` in your browser.

**Comment by dvirginz** [comment]
Any solution? it makes the parallel coordinates pretty much unusable...

![image](https://user-images.githubusercontent.com/31047807/118600125-3b7fdc00-b7b9-11eb-9b05-73a97b775d42.png)
