### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by DrawnWren** [tensorflow/tensorboard#3437]
Sorry, this isn't really a feature request. I am using tensorboard (and not tensorflow) in an academic paper and would like to provide proper citation. Should I use the tensorflow white paper citation or is there a more specific one for the tensorboard component?

**Comment by GalOshri** [comment]
Thank you for asking! I think citing the [TensorFlow white paper](http://download.tensorflow.org/paper/whitepaper2015.pdf) is the best approach.

In case it is useful to you and you haven't heard about it, [TensorBoard.dev](https://tensorboard.dev) enables you to share your experiment results more easily. This would let you include a link to the TensorBoard in your paper ([example link](https://tensorboard.dev/experiment/AdYd1TgeTlaLWXx6I8JUbA/#scalars)). It currently only includes the Scalars dashboard, but we are adding more capabilities. Feedback is very welcome :).
