### ISSUE TITLE
ValueError: Duplicate plugins for name projector

### ISSUE THREAD

**Issue by ZhaooweiZhong** [tensorflow/tensorboard#3443]
When I used the tensorbboard logdir command, I got the following error : 
"ValueError: Duplicate plugins for name projector". 

I tried to diagnose the cause of the error using diagnose_tensorboard.py, and got the following suggestions :

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version f96437fea2136ca3f0f574686f70b747e28c6327

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=16299, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: Could not generate requirement for distribution -ensorboard 2.1.1 (f:\anaconda3\lib\site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
INFO: installed: tensorboard==2.1.1
INFO: installed: tensorflow==2.1.0
INFO: installed: tensorflow-estimator==2.1.0

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "tensorboard.py", line 464, in main
    suggestions.extend(check())
  File "tensorboard.py", line 75, in wrapper
    result = fn()
  File "tensorboard.py", line 240, in tensorboard_python_version
    from tensorboard import version
ImportError: cannot import name 'version'

--- check: tensorflow_python_version
2020-03-30 11:54:19.727053: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
F:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.summary API due to missing TensorBoard installation.
INFO: tensorflow.__version__: '2.1.0'
INFO: tensorflow.__git_version__: 'v2.1.0-rc2-17-ge5bf8de410'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'F:\\Anaconda3\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'DESKTOP-L9KR3OA'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\bobbi\AppData\Local\Temp\.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=82472168176244921, st_dev=4274481677, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1584984303, st_mtime=1584984303, st_ctime=1584980530)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['F:\\Anaconda3\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
WARNING: Could not generate requirement for distribution -ensorboard 2.1.1 (f:\anaconda3\lib\site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
INFO: pip freeze --all:
absl-py==0.8.1
alabaster==0.7.10
altgraph==0.16.1
anaconda-client==1.6.14
anaconda-navigator==1.9.7
anaconda-project==0.8.2
arrow==0.15.5
asn1crypto==0.24.0
astor==0.8.0
astroid==2.0.4
astropy==3.0.2
attrs==18.1.0
av==7.0.1
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
baidu-aip==2.2.10.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
bokeh==0.12.16
bosonnlp==0.11.1
boto==2.48.0
Bottleneck==1.2.1
cachetools==4.0.0
catboost==0.11.0
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.4.0
comtypes==1.1.4
conda==4.7.12
conda-build==3.10.5
conda-package-handling==1.6.0
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.6.1
cycler==0.10.0
Cython==0.29.15
cytoolz==0.9.0.1
dask==0.17.5
datashape==0.5.4
decorator==4.3.0
decord==0.3.6
-e git+https://github.com/conansherry/detectron2@72c935d9aad8935406b1038af408aa06077d950a#egg=detectron2
distributed==1.21.8
docutils==0.14
entrypoints==0.2.3
enum34==1.1.9
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
future==0.18.2
# Editable install with no version control (fvcore==0.1)
-e f:\fvcore-master
gast==0.2.2
Geohash==1.0
gevent==1.3.0
glob2==0.6
google-auth==1.11.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
greenlet==0.4.13
grpcio==1.27.2
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
jieba==0.39
Jinja2==2.10
joblib==0.14.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
lightgbm==2.2.2
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
Markdown==3.1.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
menuinst==1.4.14
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
mkl-service==2.3.0
more-itertools==4.1.0
mpmath==1.0.0
msgpack-python==0.5.6
multipledispatch==0.5.0
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
network==0.1
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.7.0
numpy==1.18.1
numpydoc==0.8.0
oauthlib==3.1.0
odo==0.5.1
olefile==0.45.1
opencv-python==4.2.0
openpyxl==2.5.3
opt-einsum==3.1.0
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
pefile==2019.4.18
pep8==1.7.1
pickleshare==0.7.4
Pillow==7.0.0
pip==20.0.2
pkginfo==1.4.2
pluggy==0.6.0
ply==3.11
portalocker==1.5.2
prompt-toolkit==1.0.15
protobuf==3.10.1
psutil==5.4.5
py==1.5.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio==0.2.11
pycocotools==2.0
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.2
pydot==1.4.1
pyflakes==1.6.0
pygame==1.9.6
Pygments==2.2.0
PyInstaller==3.5
pylint==2.1.1
pyltp==0.2.1
pyodbc==4.0.23
PyOpenGL==3.1.1a1
PyOpenGL-accelerate==3.1.3b1
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
python-utils==2.3.0
pytz==2018.4
PyWavelets==0.5.2
pywin32==223
pywin32-ctypes==0.2.0
pywinpty==0.5.1
PyYAML==5.3
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
requests==2.23.0
requests-oauthlib==1.3.0
resample2d-cuda==0.0.0
rope==0.10.7
rsa==4.0
ruamel-yaml==0.15.35
scikit-image==0.16.2
scikit-learn==0.21.3
scipy==1.4.1
seaborn==0.8.1
Send2Trash==1.5.0
setuptools==45.2.0
simplegeneric==0.8.1
simplejson==3.17.0
singledispatch==3.4.0.3
six==1.14.0
slim==0.1
# Editable install with no version control (slowfast==1.0)
-e h:\graduation\slowfast-4\slowfast-master
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.7
statsmodels==0.9.0
sympy==1.1.1
synonyms==3.10.2
tables==3.4.3
tabulate==0.8.6
tblib==1.3.2
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post2
tensorboardX==2.0
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
torch==1.4.0
torchvision==0.5.0
tornado==5.0.2
tqdm==4.40.0
traitlets==4.3.2
traj-conv-cuda==0.0.0
typed-ast==1.1.0
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
utils==1.0.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wheel==0.31.1
widgetsnbextension==3.2.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wordcloud==1.5.0
wrapt==1.11.2
xgboost==0.81
xlrd==1.1.0
XlsxWriter==1.0.4
xlutils==2.0.0
xlwings==0.11.8
xlwt==1.3.0
yacs==0.1.6
youtube-dl==2020.2.16
zict==0.1.3

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

**System information** 
- OS Platform and Distribution : Windows-10-10.0.16299-SP0
- TensorFlow installed from source : - TensorFlow version: 
numpy                              1.18.1      
numpydoc                           0.8.0       
protobuf                           3.10.1      
tensorflow                         2.1.0       
tensorflow-estimator               2.1.0       
tensorflow-gpu-estimator           2.1.0
- Python version: 3.6.5
- CUDA/cuDNN version: 10.1
- GPU model and memory:NVIDA GeForce 940MX 2G

**Describe the current behavior**
At the beginning of using tensorboard, there will be a web link, but it will be blank after opening the link. At that time, the diagnosis result is to reinstall tensorflow tensorflow-gpu and others. After trying to reinstall tensorflow and other components, I got the error message "ValueError: Duplicate plugins for name projector" . The above results are obtained by diagnosis.
I'm sure there's no problem with the file I'm going to open using tensorboard, because it's already shown on another machine.

Thank you very much for your reply！

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version and Tensorboard Version. Also, please provide the information of the Browser you are using.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by stephanwlee** [comment]
@ZhaooweiZhong, thanks for the issue. This error can happen if there were different versions of TensorBoard installed. While `pip freeze` only reports the latest one installed, if you have installed previous one before which then got upgraded, the `lib` folder can contain artifacts from other versions.

Can you please try `pip uninstall tensorboard && pip install tensorboard`?

**Comment by rmothukuru** [comment]
@ZhaooweiZhong,
Can you please respond to @stephanwlee's comment above. Thanks!

**Comment by psybuzz** [comment]
Since the issue looks like a symptom of duplicate TensorBoard installations (https://github.com/tensorflow/tensorboard/issues/2748#issuecomment-539791539), the fix is to uninstall duplicate TensorBoard packages.

Please let us know if it doesn't work.

**Comment by kernelizd** [comment]
I have the same error.
Latest TF (2.3) and tensorboard.
I have tried uninstalling tensorboard to make sure there's no duplication installation as indicated by @stephanwlee 
yet, the problem persists. Please help because without this, the whole HParam plugin is useless.

**Comment by kernelizd** [comment]
I have same problem.
I did exactly what @stephanwlee said. Made sure there's one installation of tensorboard, yet the problem persists.
I have v2.3.

**Comment by GF-Huang** [comment]
This issue should  be re open.

**Comment by joyceerhl** [comment]
I just hit this exact error and couldn't start tensorboard at all as a result. I was able to get tensorboard working again by deleting site-packages and my Python installation, and then reinstalling everything. 

In retrospect based on https://github.com/tensorflow/tensorboard/issues/3536#issuecomment-619510769 I suspect deleting site-packages would've been enough. IME `pip uninstall tensorboard` can sometimes leave artifacts behind (possibly if you're running tensorboard at the time that you run the uninstall). If you then reinstall tensorboard, this ends up looking like duplicate installs of tensorboard. Hopefully this helps someone else.

**Comment by GF-Huang** [comment]
> I just hit this exact error and couldn't start tensorboard at all as a result. I was able to get tensorboard working again by deleting site-packages and my Python installation, and then reinstalling everything.
> 
> In retrospect based on [#3536 (comment)](https://github.com/tensorflow/tensorboard/issues/3536#issuecomment-619510769) I suspect deleting site-packages would've been enough. IME `pip uninstall tensorboard` can sometimes leave artifacts behind (possibly if you're running tensorboard at the time that you run the uninstall). If you then reinstall tensorboard, this ends up looking like duplicate installs of tensorboard. Hopefully this helps someone else.

What is site-packages? And how to do?

**Comment by joyceerhl** [comment]
@GF-Huang site-packages is a folder containing user-installed Python packages. I'm on Windows and running a user-level Python 3.8 (not system-wide), so the directory I removed was

>'C:\Users\<your username>\AppData\Local\Programs\Python\Python38\Lib\site-packages'

**Comment by GF-Huang** [comment]
Is it only delete the site-packages then reinstall the `tensorboard`? Or both `tensorflow`?

**Comment by GF-Huang** [comment]
> @GF-Huang site-packages is a folder containing user-installed Python packages. I'm on Windows and running a user-level Python 3.8 (not system-wide), so the directory I removed was
> 
> > 'C:\Users<your username>\AppData\Local\Programs\Python\Python38\Lib\site-packages'

Not work, I had delete site-packages of `tensorboard` and reinstall it.

**Comment by fachu000** [comment]
It seems that the problem is that when you install tf-nightly, the package tb-nightly is also installed. Then, both the packages tensorboard and tb-nightly contain a plugin with name 'projector'.

My work around: Replace the function `iter_entry_points` in "site-packages/pkg_resources/\_\_init\_\_.py" with the following:

````python
    def iter_entry_points(self, group, name=None):
        """Yield entry point objects from `group` matching `name`

        If `name` is None, yields all entry points in `group` from all
        distributions in the working set, otherwise only ones matching
        both `group` and `name` are yielded (in distribution order).
        """

        return (entry for dist in self
                for entry in dist.get_entry_map(group).values()
                if ((name is None) or (name == entry.name)) and (
                    entry.name != 'projector'
                    or entry.dist.project_name != 'tb-nightly'))

````

**Comment by JulesGM** [comment]
https://github.com/tensorflow/tensorboard/issues/3443#issuecomment-731567853 uninstalling tb-nightly, uninstalling tensorboard, and then reinstalling tensorboard worked for me

**Comment by dhavids** [comment]
> [#3443 (comment)](https://github.com/tensorflow/tensorboard/issues/3443#issuecomment-731567853) uninstalling tb-nightly, uninstalling tensorboard, and then reinstalling tensorboard worked for me

This worked for me.

**Comment by GF-Huang** [comment]
Issue still even `tf 2.4` released?

![image](https://user-images.githubusercontent.com/4510984/105324789-d5b68580-5c06-11eb-93c8-925682018486.png)

**Comment by GF-Huang** [comment]
`pip uninstall tb-nightly` works !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by XY-boy** [comment]
> [#3443 (comment)](https://github.com/tensorflow/tensorboard/issues/3443#issuecomment-731567853) uninstalling tb-nightly, uninstalling tensorboard, and then reinstalling tensorboard worked for me

thank you very much,it works for me!

**Comment by yecatstevir** [comment]
I did what @JulesGM said. This is what I used and it worked: !pip uninstall tb-nightly tensorboard && pip install tensorboard
