### ISSUE TITLE
No need to manually specify version in notebooks

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorboard#3451]
Since colab now by default imports tensorflow 2.x, there is no need to manually specify import version as below:
```try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
```

**Comment by wchargin** [comment]
Hi @ManishAradwad—thanks for the report! Good point. It looks like the
TensorFlow docs folks have [removed `%tensorflow_version` from the main
docs as well][1], so this change sounds good to me. Thanks for sending
us a PR—I’ll take a look.

[1]: http://github.com/tensorflow/docs/commit/cf2a57e77485c371f04cc486d9d1e632ef552739
