### ISSUE TITLE
Exponential smoothing depends on number of steps

### ISSUE THREAD

**Issue by PgLoLo** [tensorflow/tensorboard#3493]
I've just noticed that the curve of exponential smoothing depends on the number of steps. Consider this series of screenshots:
![image](https://user-images.githubusercontent.com/5480856/78695371-b0ba8580-7906-11ea-9375-79c93c8ba677.png)
![image](https://user-images.githubusercontent.com/5480856/78695382-b31cdf80-7906-11ea-8a5a-0069e7e232ab.png)
![image](https://user-images.githubusercontent.com/5480856/78695391-b57f3980-7906-11ea-836c-2cbf1043c7af.png)
![image](https://user-images.githubusercontent.com/5480856/78695400-b87a2a00-7906-11ea-9807-dee98513521c.png)
![image](https://user-images.githubusercontent.com/5480856/78695412-badc8400-7906-11ea-9274-44074274ed45.png)
![image](https://user-images.githubusercontent.com/5480856/78695428-c039ce80-7906-11ea-875e-09944fe66a53.png)

The training process is displayed with green colour, blue and red are static and added for comparison. Look. how the green exponential smoothing changes for points in the past while the number of iteration grows. Is that an expected behaviour?

**Comment by psybuzz** [comment]
Thanks for the report.  This does look like a case where the ideal, intended smoothing should not strongly affect points in the past.

There are already a couple open issues that track misleading smoothing behavior, so please follow / comment those reports for updates:
https://github.com/tensorflow/tensorboard/issues/786
https://github.com/tensorflow/tensorboard/issues/1127
