### ISSUE TITLE
I can't run Tensorboard in Ubuntu:  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by Anatolist** [tensorflow/tensorboard#3518]
Tensorflow and Tensorboard ver. 2.
ubuntu:16.04
Pre-trained model: ssd_mobilenet_v1_pets.config 
I have not written any custom code.

Hi everyone, a couple of days ago I ran Tensorboard in Ubuntu and I got results without any problem.
I used a pre-trained model and I want to put the results into Tensorboard.

I have a remote session and I  do the same yesterday,
from models / object_detection folder, I run the command:

` tensorboard --bind_all --port 6006 --logdir='training'`

but I received the errors:
`TensorBoard 2.0.2 at http://ubuntu:6006/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/main.py", line 66, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/program.py", line 267, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/program.py", line 283, in _run_serve_subcommand
    self._register_info(server)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/program.py", line 329, in _register_info
    manager.write_info_file(info)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/manager.py", line 267, in write_info_file
    payload = "%s\n" % _info_to_string(tensorboard_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/manager.py", line 126, in _info_to_string
    for k in _TENSORBOARD_INFO_FIELDS
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/manager.py", line 126, in <dictcomp>
    for k in _TENSORBOARD_INFO_FIELDS`
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

I uninstall and install the Tesnorboard but the same errors. I would appreciate any help.
Thank U

**Comment by gowthamkpr** [comment]
@Anatolist Try using python 3.x and let me know if the error still persists

**Comment by rithiksachdev** [comment]
![ss](https://user-images.githubusercontent.com/39690921/79252117-bd0e8780-7e9e-11ea-8673-17efe8daa8d5.png)

Hi @Anatolist, You can also use a virtual environment.

**Comment by Anatolist** [comment]
> @Anatolist his is caused by the default encoding difference between python 2.7 (ascii) and 3.x (utf-8). Try using python 3.x and let me know if the error still persists

Hi

**Comment by Anatolist** [comment]
hi @gowthamkpr  and @rithiksachdev ,
I have done exactly what you say and the problem is gone. I connect with web service Tensorboard but it doesn't  fetch any data yet. 
I still have the object_detection and the training folder at the previous folder of Tensorflow so I ran it from

**Comment by rithiksachdev** [comment]
Hi @Anatolist, I think you have missed something here as I cannot see any logs created by you and If that's the case then I will recommend that you should read this [article](https://www.tensorflow.org/tensorboard/get_started). You'll have to add tensorboard_callback in your model to be precise. Hope this solves your problem :+1:

**Comment by Anatolist** [comment]
Hi @rithiksachdev ,
You mean the logs of training, there are in the folder 

![image](https://user-images.githubusercontent.com/57349790/79264877-29808b00-7e8d-11ea-83ae-7aca33053a9d.png)

**Comment by rithiksachdev** [comment]
Hi @Anatolist, What is the tensorflow version that you are using? 
I am using a different version of ubuntu, therefore, I tried to find if this problem had occurred with someone else. I would suggest you follow this [comment](https://github.com/tensorflow/tensorflow/issues/35968#issuecomment-577329399) and let me know if this makes sense. The comment solves two types of errors so make changes only that apply to your machine type. The issue is with your tensorflow so my suggestion would be to uninstall and reinstall tensorflow, check if that solves your issue then it's great.

**Comment by Anatolist** [comment]
Hi @rithiksachdev, that comment was useful and I install the missing library.
And I also reinstall and downgrade my version of TensorFlow and tensorboard from 2.1.1 to 2.0.0

Now I have:  
TensorFlow              2.0.0
TensorFlow-estimator    2.0.1
tensorboard             2.0.2
I don t take any error while I am running from folder 
(ENV) anatoli@ubuntu:~/tensorflow/tensorflow/models/research/object_detection$
`tensorboard --bind_all --port 6006 --logdir=’training’`  response TensorBoard 2.0.2 at http://ubuntu:6006/ (Press CTRL+C to quit)


but the Tensorbord did not fetch any data. I am in a remote session but the web service open without data.

_No scalar data was found.
Probable causes:_

_You haven’t written any scalar data to your event files.
TensorBoard can’t find your event files.
If you’re new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial.

If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub._

**Comment by rithiksachdev** [comment]
Hi @Anatolist, I would suggest that if you could please run the diagnostics and post them here, We could understand the exact problem. You can also try removing the inverted comma with the correct path. ( You can use a `pwd` for this purpose. )

**Comment by Anatolist** [comment]
So, I think that I found something and I  resolve it. 

I installed the Tensorflow 2.0 python 3.5 in a virtual environment, in the folder TensorFlow-venv3, 
![image](https://user-images.githubusercontent.com/57349790/79340332-0c49cc00-7f22-11ea-9e9c-d18331c80842.png)

![image](https://user-images.githubusercontent.com/57349790/79340633-7d897f00-7f22-11ea-8e12-bc2d33321e3a.png)

But the object_detection API and the training folder are in a directory out of the virtual environment.
the are in path   
I ran the command from the virtual environment `(ENV) anatoli@ubuntu:~/tensorflow/tensorflow/models/research/object_detection$ tensorboard --bind_all --port 6006 --logdir=home/anatoli/tensorflow/tensorflow/models/research/object_detection/training$`
 and nothing displayed.

I ran the same command out of the virtual environment, not from ENV:

`anatoli@ubuntu:~/tensorflow/TensorFlow/models/research/object_detection$ tensorboard --bind_all --port 6006 --logdir=training`
and the  graphs and results appear on Tensorboard

**Comment by rithiksachdev** [comment]
Hi @Anatolist, I was asking you to run this [diagnose_tensorboard.py](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/tools/diagnose_tensorboard.py) file. We only need to specify the path from our working directory to the logs generated by tensorflow. If you face any error in your virtualenv then read the output and follow the directions. I hope this helps :smile:
