### ISSUE TITLE
A special error caused: tensorboard can not uninstall competely， and the tensorboard app occur in conda list but not in pip list

### ISSUE THREAD

**Issue by Joe-Wong-scnu** [tensorflow/tensorboard#3536]
A special error caused: tensorboard can not uninstall competely， and the tensorboard app occur in conda list but not in pip list。

running diagnose_tensorboard and show as follow：

### Diagnostics

<details>
<summary>Diagnostics output</summary>

--- check: autoidentify
INFO: diagnose_tensorboard.py version d515ab103e2b1cfcea2b096187741a0eeb8822ef

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=18362, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: Could not generate requirement for distribution -ensorboard 2.1.0 (.conda\envs\stan_env\lib\site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
INFO: installed: tensorflow-estimator==2.1.0

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 470, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 246, in tensorboard_python_version
    from tensorboard import version
ModuleNotFoundError: No module named 'tensorboard'

--- check: tensorflow_python_version
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING: Limited tf.summary API due to missing TensorBoard installation.
INFO: tensorflow.__version__: '2.1.0'
INFO: tensorflow.__git_version__: 'v2.1.0-rc2-17-ge5bf8de410'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:conda\\envs\\stan_env\\Scripts\\tensorboard.exe\r\nC:\\AppData\\Local\\Programs\\Python\\Python37\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'DESKTOP-2GJ5QFV'

--- check: stat_tensorboardinfo
INFO: directory: AppData\Local\Temp\.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=8444249301461442, st_dev=1980557575, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1587429003, st_mtime=1587429003, st_ctime=1587428730)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (0): []; bad_roots (0): []

--- check: full_pip_freeze
WARNING: Could not generate requirement for distribution -ensorboard 2.1.0 (.conda\envs\stan_env\lib\site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
INFO: pip freeze --all:
pip list: all the same as follow in conda list but tensorboard existed in the conda list specaially.
</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

conda list show tensorboard exist ：
# Name                    Version                   Build  Channel
...
sip                       4.19.8           py37h6538335_0    
six                       1.14.0                   py37_0    
sqlalchemy                1.3.12                   pypi_0    pypi
sqlite                    3.31.1               he774522_0    
statsmodels               0.10.1           py37h8c2d366_0    
sympy                     1.5.1                    pypi_0    pypi
tensorboard               2.1.0                    pypi_0    pypi
tensorflow-cpu            2.1.0                    pypi_0    pypi
tensorflow-estimator      2.1.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0    
testpath                  0.4.4                      py_0    
torch                     1.4.0+cpu                pypi_0    pypi
torchvision               0.5.0+cpu                pypi_0    pypi
tornado                   6.0.4            py37he774522_1    
tqdm                      4.44.1                     py_0    
traitlets                 4.3.3                    py37_0    
urllib3                   1.24.3                   pypi_0    pypi
vc                        14.1                 h0510ff6_4    
vs2015_runtime            14.16.27012          hf0eaf9b_1    
...

System information

OS Platform and Distribution : Windows-10
Python version: 3.7.4
anaconda :  virtual enviroment
CUDA/cuDNN version: 10.1

This error occured, it cause a problem I try install tensorboard again but can not use tensorboard and show me a warning : tensorboard ValueError: Duplicate plugins for name projector
I spared no effort to fix it but failed, please help me.
THX with my sincere.

**Comment by psybuzz** [comment]
Thanks for the report.  The "duplicate plugins for name projector" error is commonly found when there is more than one installation of the TensorBoard package, so the fix is to uninstall installations except for one.

Could you please try the conda equivalent of the suggestions found in these comments?
https://github.com/pytorch/pytorch/issues/22676#issuecomment-515662805
https://github.com/pytorch/pytorch/issues/22676#issuecomment-534882021

**Comment by Joe-Wong-scnu** [comment]
I fixed the problem by deleteing a file named "~ensorboard" which maybe uninstalled improperly by me! Thx for everyone paying attention in this problem. Best wish !
