### ISSUE TITLE
What's the relationship between externs.ts and graphlib?

### ISSUE THREAD

**Issue by hexiaoting** [tensorflow/tensorboard#3547]
in file plugins/graph/tf_graph_common/externs.ts。
I found it declare a module graphlib and export class Graph. and this plugin also deps graphlib.core.js  according to file "tensorboard/components/tf_imports/graphlib.html".

I donot understand How does class Graph in externs.ts implement？ what's the relationship between externs.ts and graphlib.core.js?

Now I'm trying to reuse graph plugin's show graph function code in my project, 
I install javascript graphlib.core.js but I donot know how to make externs.ts work.
The error in my project is :
```
src/externs.ts:46:5 - error TS2390: Constructor implementation is missing.

46     constructor(opt?: Object);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/externs.ts:47:5 - error TS2391: Function implementation is missing or not immediately following the declaration.

47     setNode(name: string, value?: N): void;
       ~~~~~~~

src/externs.ts:48:5 - error TS2391: Function implementation is missing or not immediately following the declaration.

48     hasNode(name: string): boolean;
       ~~~~~~~

src/externs.ts:49:5 - error TS2391: Function implementation is missing or not immediately following the declaration.

49     setEdge(fromName: string, toName: string, value?: E): void;
       ~~~~~~~

src/externs.ts:50:5 - error TS2391: Function implementation is missing or not immediately following the declaration.

50     hasEdge(fromName: string, toName: string): boolean;
       ~~~~~~~
......
```

**Comment by gowthamkpr** [comment]
@hexiaoting Please post this question in stackoverflow as github isonlymeany for bug/permonace, build/install, fearure request related issues. Thanks!
