### ISSUE TITLE
PR curve step re-selection broken

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#3551]
Unfortunately, it looks like #3524 breaks PR curves: the initial render
is fine, but when you change the step slider the plot is just replaced
by a series that only shows the last data point. Repro video:
[pr_curve_redraw_broken.webm.zip][vid]

Occurs since 2020-04-23 nightly and on master; can be fixed on master by
reverting 27d0023e728aba79d0129f890e41c6c2c4c436b9.

[vid]: https://github.com/tensorflow/tensorboard/files/4542242/pr_curve_redraw_broken.webm.zip

**Comment by wchargin** [comment]
I’m going to roll back for now. Feel free to roll forward with fix.

**Comment by stephanwlee** [comment]
#3552 has fixed the issue and #3571 fixes the underlying issue.
