### ISSUE TITLE
Early histogram data disappears

### ISSUE THREAD

**Issue by yifr** [tensorflow/tensorboard#3579]
Hi, I'm trying to visualize index collapse in the latent space of a [Vector Quantized Auto-Encoder](https://arxiv.org/pdf/1711.00937.pdf). Here's an example of how that graph should look from [this paper](https://arxiv.org/pdf/1803.03382.pdf):
<img width="383" alt="Screen Shot 2020-05-02 at 11 12 26 AM" src="https://user-images.githubusercontent.com/26826815/80868016-d61c8400-8c65-11ea-812c-6ac10e2d3457.png">

When I check up on my model after 500 training iterations the histogram looks correct (we only have 4,096 discrete latents, which is why the x-axis is smaller than the above plot):
<img width="622" alt="Screen Shot 2020-05-02 at 2 18 06 AM" src="https://user-images.githubusercontent.com/26826815/80868065-17ad2f00-8c66-11ea-9899-c57f0434db69.png">

However, when I run my model for longer (30,000 iterations) the histogram has collapsed to the one dominant bin, and I can no longer see those first iterations where my latents were more distributed (notice how the x-axis has collapsed):

<img width="630" alt="Screen Shot 2020-05-02 at 9 34 46 AM" src="https://user-images.githubusercontent.com/26826815/80868082-475c3700-8c66-11ea-9388-600904f1195d.png">

I tried running 

> tensorboard --logdir runs/ --samples_per_plugin histogram=0 serve

to force tensorboard to use all the samples for my histogram but it doesn't change anything. I checked on the above run (where the early data disappears) at around 2,000 iterations, and it looked fine, which is why I suspect that some early data is getting truncated.

I'm not sure how to solve this and haven't been able to find any answers :(

**Comment by bileschi** [comment]
I think the problem may be that the flag should be `--samples_per_plugin histograms=0` (with an `s`).  Verified that there is no message if a plugin name is misspelled.

Filed #3718 to improve messaging here.

**Comment by bileschi** [comment]
Please close if this address your problem.  Thanks!

**Comment by pindinagesh** [comment]
@yifr 

Could you please move this to closed status as it is resolved. Thanks

**Comment by bileschi** [comment]
Closing old support issue, reopening related issue in user messging.
