### ISSUE TITLE
Tensorboard dev support image display

### ISSUE THREAD

**Issue by xwinxu** [tensorflow/tensorboard#3585]
Currently I am writing gifs to my Tensorboard and am able to write and load them successfully using `tf.summary.experimental.write_raw_pb` (code is essentially from this [issue](https://github.com/tensorflow/tensorboard/issues/39#issuecomment-568917607)) when running Tensorboard locally. However upon trying the `Tensorboard dev`, it will only display my scalars and there is no tab available for images that I would have normally.

**Comment by ericdnielsen** [comment]
At present we only support scalars and graphs in tensorboard.dev.  We are working on adding additional plugins, but we can't provide a detailed estimate of when they will be launched,

**Comment by xwinxu** [comment]
Got it, thanks for the reply!

**Comment by toonday** [comment]
@ericdnielsen @amahendrakar will there be some sort of announcement when this feature is supported?

**Comment by FrankLinxzx** [comment]
same suggest : need  images

**Comment by ericdnielsen** [comment]
Work on the Images plugin has been paused due to performance issues and abuse prevention complications.  We do not currently have an ETA for when it would be supported.
