### ISSUE TITLE
Extract HTML from tensorboard to be able to use within an I-Frame

### ISSUE THREAD

**Issue by punjabdhaputar** [tensorflow/tensorboard#3596]
Is there currently any method of extracting the HTML using to create a tensorboard window so that it can be embedded within an I-Frame?

**Comment by gowthamkpr** [comment]
@punjabdhaputar Please take a look at this [issue](https://github.com/tensorflow/tensorboard/issues/997) and let me know if it helps. Thans!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
