### ISSUE TITLE
Mouse enter/exit hover tooltip incorrect

### ISSUE THREAD

**Issue by joshua-gould** [tensorflow/tensorboard#3607]
Please see attached animated gif for example.
![hover](https://user-images.githubusercontent.com/5237151/81437257-dc64a180-9138-11ea-8687-59f99ed6a64f.gif)

**Comment by pindinagesh** [comment]
@joshua-gould 

Could you please elaborate this issue more clearly and also find this [PR](https://github.com/tensorflow/tensorboard/pull/3347) which is already merged. Thanks

**Comment by joshua-gould** [comment]
In my issue, a tooltip appeared upon mouse leave. PR #3347 seems to fix this as well.
