### ISSUE TITLE
Runs are not shown in order, apparently

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorboard#3622]
## Issue description
I had always thought that runs were shown in alphabetical order, but apparently, but is not the case (any more): see the last entry in this snapshot:

![image](https://user-images.githubusercontent.com/12128514/81641515-740c0d80-9421-11ea-9077-d901a71fd428.png)

Is this expected? What are these ordered by?

**Comment by davidsoergel** [comment]
Sort order is by started time (aka first event time) with empty times sorted last, and then ties are broken by sorting on the run name.

Please see the [implementation](https://github.com/tensorflow/tensorboard/blob/e6a44748eacb4711b343fce3f5dc3f3ec34f18d4/tensorboard/plugins/core/core_plugin.py#L182) for more details.
