### ISSUE TITLE
Tensorflow upgrade

### ISSUE THREAD

**Issue by alan0410** [tensorflow/tensorboard#3667]
I want to upgrade tensorflow from 1.12.0 to the newest version, but when I try it on Anaconda prompt, it doesn't work. 
The message I see is 
![capture](https://user-images.githubusercontent.com/60909846/82629852-ea7feb00-9c2b-11ea-8c01-a7d000747ad7.JPG)

I don't know what to do. How can I install it?

**Comment by stephanwlee** [comment]
Hi there, the error you posted does not really indicate that this is a problem with TensorBoard.

Can you better describe your environment, steps you took, and why you think it is an issue with TensorBoard (not TensorFlow)? If you really think there is an issue with TensorBoard, we will definitely appreciate it if you open a bug by filling out this template <https://github.com/tensorflow/tensorboard/issues/new?template=installation_problem.md>  following the steps in it.
