### ISSUE TITLE
Option to highlight min/max point on curve

### ISSUE THREAD

**Issue by ismael-elatifi** [tensorflow/tensorboard#3668]
We often zoom into the curves to find the highest/lowest value of our metric/loss.
It would be great if we add an option to automatically highlight the best point on a curve.
We could have 2 checkboxes below each curve : one to highlight the minimum point and the other to highlight the maximum point.
"Highlighting" could be simply to show a bigger point with a dedicated color.

**Comment by bmd3k** [comment]
Thanks Ismael for your suggestions,
This is an interesting idea. We discussed briefly as a team and decided to put it on our backlog.

**Comment by nfelt** [comment]
Duplicate of #1030

**Comment by nfelt** [comment]
Closing in favor of #1030 which predates this request by a bit - please follow that issue.
