### ISSUE TITLE
Projector tab does not appear when tensorboard is launched with tensorboard.program

### ISSUE THREAD

**Issue by hvcdrake** [tensorflow/tensorboard#3683]
Hello,
### Running Tensorboard from command line
Launching Tensorboard from the command line works. When i click in the projector opction from the selector i get the hoped result.

Launching line:
_tensorboard --logdir="other_logs" --host="127.0.0.1" --port="6010"_

![image](https://user-images.githubusercontent.com/27180120/83314411-7ae3a000-a1d7-11ea-9ce0-b6072616f3df.png)

### Running Tensorboard from python script
The issue comes when i run tensorboard from a python script. **The projector option does not appear.** Getting _/#projector_ did not work neither. It's that launching tensorboard in different ways is leading to theese results.

![image](https://user-images.githubusercontent.com/27180120/83315014-900dfe00-a1da-11ea-8a5b-77c2e0644044.png)

I tested this with the imdb example from the documentation page (https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin).

Also tested with a custom log directory. All log dirrectories are attached.

[tb_launch_issue.zip](https://github.com/tensorflow/tensorboard/files/4704845/tb_launch_issue.zip)

I know that it could seem trivial but we really need to launch tensorboard on demmand from a python program. Maybe am i doing something wrong?

Thanks in advance.

Python Script
```
from tensorboard import program
import os.path


ld=os.path.abspath("other_logs") # Try with imdb-example or other_logs 
h="127.0.0.1" # Localhost
p="6010" # Port

# Initating an launching tensorboard
tb = program.TensorBoard()
tb.configure(argv=[None, '--logdir', ld, '--host', h, '--port', p])
tb.main()
```
### Enviroment
os: Windows 10
python: 3.6.9
tensorboard: 2.1.0
tensorflow: 2.1.0 // Also tested with tb-nightly

**Comment by wchargin** [comment]
Hi @hvcdrake! Thanks for the report. The projector plugin is loaded a
bit differently from most TensorBoard-bundled plugins, using a “dynamic
plugin” mechanism that finds the plugins to load at runtime. The catch
is that we currently only load dynamic plugins through `tensorboard(1)`,
not through `tensorboard.program`; compare:

https://github.com/tensorflow/tensorboard/blob/cdd02d783aa58be0c1ee7dc5a32770730119a0b5/tensorboard/main.py#L65

https://github.com/tensorflow/tensorboard/blob/cdd02d783aa58be0c1ee7dc5a32770730119a0b5/tensorboard/program.py#L144-L147

I’ll send out a patch for this; thanks!

**Comment by wchargin** [comment]
Also, pro tip—

> ```python
> tb.configure(argv=[None, '--logdir', ld, '--host', h, '--port', p])
> ```

—you can configure these with a nicer kwargs API:

```python
ld = os.path.abspath(...)
h = "127.0.0.1"
p = 6010  # note: a real integer, not "6010"

tb.configure(logdir=ld, host=h, port=p)
```

Then, you don’t have to worry about escaping or flag syntax or anything.

**Comment by hvcdrake** [comment]
> Hi @hvcdrake! Thanks for the report. The projector plugin is loaded a
> bit differently from most TensorBoard-bundled plugins, using a “dynamic
> plugin” mechanism that finds the plugins to load at runtime. The catch
> is that we currently only load dynamic plugins through `tensorboard(1)`,
> not through `tensorboard.program`; compare:
> 
> https://github.com/tensorflow/tensorboard/blob/cdd02d783aa58be0c1ee7dc5a32770730119a0b5/tensorboard/main.py#L65
> 
> https://github.com/tensorflow/tensorboard/blob/cdd02d783aa58be0c1ee7dc5a32770730119a0b5/tensorboard/program.py#L144-L147
> 
> I’ll send out a patch for this; thanks!

Got it! Thanks @wchargin

**Comment by hvcdrake** [comment]
> Also, pro tip—
> 
> > ```python
> > tb.configure(argv=[None, '--logdir', ld, '--host', h, '--port', p])
> > ```
> 
> —you can configure these with a nicer kwargs API:
> 
> ```python
> ld = os.path.abspath(...)
> h = "127.0.0.1"
> p = 6010  # note: a real integer, not "6010"
> 
> tb.configure(logdir=ld, host=h, port=p)
> ```
> 
> Then, you don’t have to worry about escaping or flag syntax or anything.

Cool! Thanks : )
