### ISSUE TITLE
Suggestion: An icon for Tensorboard 

### ISSUE THREAD

**Issue by crystal5fish** [tensorflow/tensorboard#3693]
![image](https://user-images.githubusercontent.com/28918823/83515902-b0a2c480-a508-11ea-9940-d62730fe6e41.png)
HI, we are developing based on jupyterlab, after installed tensorboard, the name in sidebar is a little bit long and weird, would you please set an icon for Tensorboard. Thank you!!

**Comment by wchargin** [comment]
Hi @crystal5fish! Thanks for the request. You should reach out to the
maintainers of JupyterLab—the tab UI that you show there is not part of
TensorBoard itself, and we have no control over it. (TensorBoard itself
does have a favicon; that’s about the only icon that we can provide.) It
looks like they’ve been receptive to such suggestions in the past: e.g.,
<https://github.com/jupyterlab/jupyterlab/pull/5920>. Good luck!

**Comment by crystal5fish** [comment]
> Hi @crystal5fish! Thanks for the request. You should reach out to the
> maintainers of JupyterLab—the tab UI that you show there is not part of
> TensorBoard itself, and we have no control over it. (TensorBoard itself
> does have a favicon; that’s about the only icon that we can provide.) It
> looks like they’ve been receptive to such suggestions in the past: e.g.,
> [jupyterlab/jupyterlab#5920](https://github.com/jupyterlab/jupyterlab/pull/5920). Good luck!

Dear @wchargin , I got it! Thanks very much!
