### ISSUE TITLE
Segfault = docker + tensorboard + pytorch

### ISSUE THREAD

**Issue by francesco-p** [tensorflow/tensorboard#3704]
## Description

Hello,
I have this program:

```python
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()
writer.add_scalar('test', 1)
writer.close()
```
Whenever I try to run it on a cell of a jupyter-lab instance in a docker container, **if it is the first time it crashes the kernel, otherwise it runs forever**. Basically it's unusable.

My suspition was a segfault, since no log appears anywhere while it blocks. Here's  `sudo dmesg` that gives me this everytime i try to run a cell using the writer:

![segfault](https://user-images.githubusercontent.com/5663725/83787119-9a753f80-a693-11ea-84a2-20cc180b1998.png)

## Software versions
```
cython --version
Cython version 0.29.15

tensorflow.__version__
2.2.0

tensorboard --version
2.2.2

torch.__version__
1.5.0

jupyter-lab --version
2.1.4

python --version
Python 3.6.9

docker --version
Docker version 19.03.11, build 42e35e61f3
```
with nvidia docker (dunno how to check the version). The docker image is based on [ufoym/deepo](https://github.com/ufoym/deepo) and the `uname -a` is:
```
Linux e13c9d2cf9a9 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

This is the tensorboard diagnose:
[tboard.log](https://github.com/tensorflow/tensorboard/files/4731264/tboard.log)

**Comment by wchargin** [comment]
Hi @francesco-p! Sorry to hear that you’re running into issues here.
Unfortunately, we don’t maintain the `torch.utils.tensorboard` package
at all or have any visibility into it. I recommend taking this over to
the PyTorch folks, who maintain that code, and getting their help.
Good luck!
