### ISSUE TITLE
ImportError: cannot import name 'api'

### ISSUE THREAD

**Issue by amaa11** [tensorflow/tensorboard#3728]
Dear all,<br>

I want to use tensorboard for parameters tuning 
I first import the library as below
`%load_ext tensorboard.notebook;
!rm -rf ./logs/ 
import tensorflow as tf
from tensorboard.plugins.hparams import api as hp`
But then I got the error below.
`ImportError                               Traceback (most recent call last)
<ipython-input-20-8ac8645a25bb> in <module>
      2 get_ipython().system('rm -rf ./logs/ ')
      3 import tensorflow as tf
----> 4 from tensorboard.plugins.hparams import api as hp
ImportError: cannot import name 'api'`
How this could be fixed?
Thanks in advance
Python version: 3.6.9
tensorflow: 1.14.0

**Comment by bileschi** [comment]
You probably mean 
```
from tensorboard.plugins.hparams import api_pb2 as hp
```

**Comment by bileschi** [comment]
I think the error is probably with the first line.  You may need to 

     %load_ext tensorboard

not

     %load_ext tensorboard.notebook

Can you check which version of tensorboard you have?

```
import tensorboard
tensorboard.__version__
```

**Comment by bileschi** [comment]
You may also be interested in this code lab working through TensorBoard hparams.
https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/hyperparameter_tuning_with_hparams.ipynb#scrollTo=mVtYvbbIWRkV

**Comment by arghyaganguly** [comment]
Closing this as stale.Please feel free to reopen.
