### ISSUE TITLE
Graph: Failed Normalizing Names

### ISSUE THREAD

**Issue by magic-lantern** [tensorflow/tensorboard#375]
I'm here at the KDD 2017 Conference, and really enjoyed the Tensorflow hands on presentation by Josh Gordon and others (forgot their names :( ). Anyway, following one of the example Jupyter notebooks at https://github.com/random-forests/tensorflow-workshop/blob/master/examples/07_structured_data.ipynb resulted in a Tensorboard error that they didn't know how to resolve.

After running the full notebook, opening Tensorboard, I get the error "Graph: Failed Normalizing Names" when I go to the graph tab. 

All the other tabs appear to work correctly, just this one doesn't. I've tried clearing browser cache, restarting Tensorboard, Jupyter, etc., but still get the same error. No errors appear in the command window where I'm running the Tensorboard server.

At their recommendation, I'm posting this issue. Not sure what additional information is needed, so please speak up and I'm happy to provide.

I'm running Python 3.6.1 :: Anaconda custom (x86_64) on macOS 10.12.6, and the just finalized Tensorflow 1.3.0

Any idea how to troubleshoot or resolve this issue?

**Comment by woodshop** [comment]
I'm experiencing the same issue. Ubuntu 16.04; TF 1.3.0.

**Comment by wchargin** [comment]
Thanks for your reports. There should be a stack trace in the JS console—could you please post it?

cc @chihuahua

**Comment by woodshop** [comment]
This is the output of my console using Chrome's developer console. I can "pause on caught exceptions" and provide further detail, if necessary.


```javascript
(index):2748 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):2748
(index):3047 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):3047
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
(index):7130 Reading graph pbtxt : 1 ms
(index):7130 Parsing graph.pbtxt : 3 ms
(index):7011 [Violation] 'load' handler took 156ms
(index):7011 [Violation] 'load' handler took 150ms
(index):7130 TypeError: Cannot read property 'match' of undefined
    at (index):6949
    at d ((index):6962)
    at (index):6962
    at (index):310
    at baseForOwn ((index):283)
    at (index):309
    at Function.<anonymous> ((index):318)
    at a ((index):6962)
    at arrayEach ((index):269)
    at Function.<anonymous> ((index):318)
reportError @ (index):7130
reportError @ (index):7131
(anonymous) @ (index):7131
(index):7131 [Violation] 'setTimeout' handler took 199ms
```

**Comment by magic-lantern** [comment]
Here's the error I get in the Chrome console when attempting to navigate to the "Graphs"

```
(index):2748 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):2748
(index):3047 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ (index):3047
[Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile. It is now effectively no-op, acting as if it were a descendant combinator. You should consider to remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
(index):7130 Reading graph pbtxt : 0 ms
(index):7130 Parsing graph.pbtxt : 2 ms
(index):7130 TypeError: Cannot read property 'name' of undefined
    at a ((index):6961)
    at arrayEach ((index):269)
    at Function.<anonymous> ((index):318)
    at (index):6963
    at Object.b.time ((index):7130)
    at (index):7131
reportError @ (index):7130
reportError @ (index):7131
(anonymous) @ (index):7131
setTimeout (async)
(anonymous) @ (index):7131
b.runAsyncTask @ (index):7131
b.build @ (index):6961
(anonymous) @ (index):10967
Promise resolved (async)
```

**Comment by chihuahua** [comment]
#399 fixes this. Thank you for noticing a corner case I had missed (Functions could lack input arguments). After #399 is submitted, to get this fix out, we must update the pip package.

If it is alright with you, I want to use the attached pbtxt (from 07_structured_data.ipynb) within an internal integration test to prevent this error from resurfacing.

[dnn_with_functions.pbtxt.txt](https://github.com/tensorflow/tensorboard/files/1240274/dnn_with_functions.pbtxt.txt)

**Comment by magic-lantern** [comment]
Thanks for the update. 

As for including the code from https://github.com/random-forests/ - I think that's a great idea. random-forests code is licensed under an Apache 2.0 license (https://github.com/random-forests/tensorflow-workshop/blob/master/LICENSE) and since Tensorboard is also Apache 2.0 licensed, there shouldn't be any problems from a licensing perspective.
