### ISSUE TITLE
Tensorboard dev upload bug 

### ISSUE THREAD

**Issue by ishmeetk** [tensorflow/tensorboard#3751]
Unable to upload my experiment on tensorboard.dev.
**Here is my code :**

tensorboard dev upload --logdir gs://bioasq_clean --name "bioasq accuracy bs"  --description "Simple comparison of
batch sizes gs://bioasq_clean "
**And this is the output with error:** 

Data for the "graphs" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command line ar
gument.
Data for the "histograms" plugin is now uploaded to TensorBoard.dev! Note that uploaded data is public. If you do not want to upload data for this plugin, use the "--plugins" command lin
e argument.
Upload started and will continue reading any new data as it's added
to the logdir. To stop uploading, press Ctrl-C.
View your TensorBoard live at: https://tensorboard.dev/experiment/MLRmwHmOTXCmhNkprCJZPw/
[2020-06-20T18:12:43] Uploader started.
W0620 18:12:47.274621 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 18160588 exceeds limit of 10485760 bytes.
W0620 18:12:49.654345 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 18502392 exceeds limit of 10485760 bytes.
W0620 18:12:56.931489 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 36349153 exceeds limit of 10485760 bytes.
W0620 18:13:02.599462 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 37015585 exceeds limit of 10485760 bytes.
W0620 18:13:06.744498 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 18160588 exceeds limit of 10485760 bytes.
W0620 18:13:09.085675 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 18502392 exceeds limit of 10485760 bytes.
W0620 18:13:15.518504 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 36349153 exceeds limit of 10485760 bytes.
W0620 18:13:20.855475 140588233123648 uploader.py:1074] Blob too large; skipping.  Size 37015585 exceeds limit of 10485760 bytes.
[2020-06-20T18:13:25] Total uploaded: 0 scalars, 0 tensors, 1 binary objects (9.1 MB)
Total skipped: 8 binary objects (209.9 MB)
Listening for new data in logdir...
Done. View your TensorBoard at https://tensorboard.dev/experiment/MLRmwHmOTXCmhNkprCJZPw/
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/program.py", line 290, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader_subcommand.py", line 633, in run
    return _run(flags)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader_subcommand.py", line 140, in _run
    intent.execute(server_info, channel)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader_subcommand.py", line 447, in execute
    uploader.start_uploading()
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 199, in start_uploading
    self._upload_once()
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 219, in _upload_once
    self._request_sender.send_requests(run_to_events)
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 430, in send_requests
    run_name, event, value, metadata
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 989, in add_event
    self.flush()
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 1021, in flush
    blob_sequence_id, seq_index, blob
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/uploader/uploader.py", line 1086, in _send_blob
    for response in self._api.WriteBlob(request_iterator):

**Ran the downloaded the diagnostic script from :** 
https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

**I ran the diagnostic script and got the report as following:**
$ python3 diagnose_tensorboard.py
### Diagnostics
<details>
<summary>Diagnostics output</summary>
``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682
--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='for-tensorboard', release='4.19.0-9-cloud-amd64', version='#1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)', machine='x86_64
')
INFO: sys.getwindowsversion(): N/A
--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None
--- check: installed_packages
INFO: installed: tb-nightly==2.3.0a20200619
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
INFO: installed: tf-estimator-nightly==2.3.0.dev2020062001
--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.3.0a20200619'
--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.3.0-dev20200620'

What should be my next steps to resolve this isssue.
Thank You
Regards
Ishmeet Kaur

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by ishmeetk** [comment]
Tensorflow version is 2.2.  I ran command from n1-standard-1 (1 vCPU, 3.75 GB memory), debian-10-tf-nightly-v20200620. (Google vm instance)

**Comment by bileschi** [comment]
It sounds like the uploader is choking on some very large graphs.  Can you try uploading with just scalars by using the `--plugins scalars` flag?

**Comment by bileschi** [comment]
This issue came up again in a discussion at the tensorboard SIG.   @ishmeetk , can you please tell me what you get when you run `tensorboard --version`
Thanks.

**Comment by ishmeetk** [comment]
Hi! My tensorboard version is 1.14.0

**Comment by ishmeetk** [comment]
But I have ran even on 2.2 before and it had same issues. If required I can recreate the issue step by step for more details.

**Comment by bileschi** [comment]
Hi, are you sure your TensorBoard version is `1.14.0`?  TensorBoard did not support the dev upload feature until `2.0.1`.  Is it possible that your TensorFLOW version is 1.14.0 but your TensorBoard version is something else?

I'm also curious whether this is an issue with older version of some library

can you please retry running the `diagnose_tensorboard` script?  The complete result should look like this:

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='bileschi02.cam.corp.google.com', release='5.2.17-1rodete3-amd64', version='#1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018)', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7'

--- check: installed_packages
INFO: installed: tensorboard==1.14.0
INFO: installed: tensorflow==1.14.0
INFO: installed: tensorflow-estimator==1.14.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.14.0'

--- check: tensorflow_python_version
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
INFO: tensorflow.__version__: '1.14.0'
INFO: tensorflow.__git_version__: 'v1.14.0-rc1-22-gaf24dc9'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'bileschi02.cam.corp.google.com'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=9855873, st_dev=65025, st_nlink=2, st_uid=172478, st_gid=89939, st_size=4096, st_atime=1594654313, st_mtime=1594653727, st_ctime=1594653727)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/usr/local/google/home/bileschi/env/tf-1.14.0--py3.7/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
appdirs==1.4.3
astor==0.8.1
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
gast==0.3.3
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
html5lib==1.0.1
idna==2.8
importlib-metadata==1.7.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
lockfile==0.12.2
Markdown==3.2.2
msgpack==0.6.2
numpy==1.19.0
packaging==20.3
pep517==0.8.2
pip==20.0.2
pkg-resources==0.0.0
progress==1.5
protobuf==3.12.2
pyparsing==2.4.6
pytoml==0.1.21
requests==2.23.0
retrying==1.3.3
setuptools==44.0.0
six==1.14.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
urllib3==1.25.8
webencodings==0.5.1
Werkzeug==1.0.1
wheel==0.34.2
wrapt==1.12.1
zipp==3.1.0

``````

</details>

**Comment by bileschi** [comment]
Resolved this out of band.  Issue was that Google Cloud Storage access required installing Tensor**Flow** as well as Tenor**Board**.

@ishmeetk please re-open if I've closed this prematurely.
