### ISSUE TITLE
TensorBoard hangs for minutes calling GetLogdirSubdirectories

### ISSUE THREAD

**Issue by jz-fb** [tensorflow/tensorboard#3760]
I'm working on a Tensorboard plugin and after some changes that didn't work I reverted to last commit, however it now takes 5 minutes to start up TensorBoard. I've done bazel clean and cleared ~/.cache/bazel/ before rebuilding, however the issue still persists. What other things does tensorboard use that I can clear?

As for the output, I get: 
```
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation. 
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
tensorboard.compat.tf: TendsorFlow was imported from /usr/local/lib64/python3.7/site-packages/tensorflow/init.py
Python version: % 3.7.7 (default, Jun 4 2020, 15:43:14) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] <------ hangs here
```

**Comment by stephanwlee** [comment]
Hi @jz-fb, thanks for the issue. It is a bit unclear what the issue is so I will ask for more clarification.

- How big is the logdir you are pointing at?
- Can you reproduce the issue on the TensorBoard binary (not built from Bazel) that you installed from PIP?

**Comment by jz-fb** [comment]
Looks to be an issue with file size, although I'm a bit surprised as it's supposed to be gradually loaded.

**Comment by stephanwlee** [comment]
@nfelt I don't exactly remember how the event accumulator works. Do we wait for at least single pass of the logdir before we start the server? Also, if there is one large event file (gigs), can the request thread still see the partial accumulation? (I think the answer is yes).

**Comment by nfelt** [comment]
It's not blocking; the server should start up and be responding to HTTP requests without waiting for the first event accumulator traversal, and it also shows partial results.  So the logdir and/or event file size should have no bearing on the server actually starting, only on data showing up in the UI.

To debug this further we would need more details about your setup (as requested in the issue template), and ideally a repro case.  Providing more detailed logs (`--verbosity=1`) would also help narrow down where the hanging is happening.

**Comment by jz-fb** [comment]
[zaatri@zaatri-fedora-PC0TU8E0 FRL-2020-Tensorboard]$ bazel run tensorboard -- --logdir <path to dir> --verbosity=1
INFO: Analyzed target //tensorboard:tensorboard (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorboard:tensorboard up-to-date:
  bazel-bin/tensorboard/tensorboard
INFO: Elapsed time: 0.301s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
tensorboard.compat.tf: TendsorFlow was imported from /usr/local/lib64/python3.7/site-packages/tensorflow/__init__.py
Python version: % 3.7.7 (default, Jun  4 2020, 15:43:14) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
I0625 18:32:37.530832 139852700493504 plugin_event_multiplexer.py:106] Event Multiplexer initializing.
I0625 18:32:37.530974 139852700493504 plugin_event_multiplexer.py:125] Event Multiplexer done initializing
I0625 18:32:37.531093 139852700493504 data_ingester.py:124] Launching reload in a daemon thread
I0625 18:32:37.531351 139852360230656 data_ingester.py:98] TensorBoard reload process beginning
I0625 18:32:37.531523 139852360230656 plugin_event_multiplexer.py:201] Starting AddRunsFromDirectory: <path to dir>   <---------------------pauses here
I0625 18:36:18.528368 139852360230656 io_wrapper.py:227] GetLogdirSubdirectories: Starting to list directories via walking.
I0625 18:36:22.405241 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/02-28_09-51-54/Output
I0625 18:36:22.405531 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/02-28_09-51-54/Output
I0625 18:36:26.975678 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/01-23_17-46-20/Output
I0625 18:36:26.975861 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/01-23_17-46-20/Output
I0625 18:36:31.902739 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/02-26_12-10-16/Output
I0625 18:36:31.903876 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/02-26_12-10-16/Output
I0625 18:36:36.540128 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/05-10_02-13-26/Output
I0625 18:36:36.540530 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/05-10_02-13-26/Output
I0625 18:36:44.223132 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/09-10_18-00-12/Output
I0625 18:36:44.224241 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/09-10_18-00-12/Output
I0625 18:36:49.651440 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/05-01_12-12-54/Output
I0625 18:36:49.651762 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/05-01_12-12-54/Output
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.3.0a0 at http://localhost:6006/ (Press CTRL+C to quit)
I0625 18:36:51.828697 139852402177792 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:51] "GET / HTTP/1.1" 200 -
I0625 18:36:52.299788 139852402177792 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:52] "GET /index.js HTTP/1.1" 200 -
I0625 18:36:53.639226 139852402177792 application.py:403] Plugin listing: is_active() for scalars took 0.000 seconds
I0625 18:36:53.780956 139852402177792 application.py:403] Plugin listing: is_active() for custom_scalars took 0.000 seconds
I0625 18:36:53.950680 139852402177792 application.py:403] Plugin listing: is_active() for images took 0.000 seconds
I0625 18:36:53.957608 139850726864640 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:53] "GET /data/environment HTTP/1.1" 200 -
I0625 18:36:53.958225 139852402177792 application.py:403] Plugin listing: is_active() for audio took 0.000 seconds
I0625 18:36:54.543747 139852402177792 application.py:403] Plugin listing: is_active() for debugger took 0.000 seconds
I0625 18:36:54.639660 139852402177792 application.py:403] Plugin listing: is_active() for graphs took 0.001 seconds
I0625 18:36:54.640321 139852402177792 application.py:403] Plugin listing: is_active() for distributions took 0.000 seconds
I0625 18:36:54.641632 139852402177792 application.py:403] Plugin listing: is_active() for histograms took 0.000 seconds
I0625 18:36:54.642431 139852402177792 application.py:403] Plugin listing: is_active() for text took 0.000 seconds
I0625 18:36:54.643196 139852402177792 application.py:403] Plugin listing: is_active() for pr_curves took 0.000 seconds
I0625 18:36:54.643913 139852402177792 application.py:403] Plugin listing: is_active() for profile_redirect took 0.000 seconds
I0625 18:36:54.645946 139850510497536 event_file_loader.py:82] Opening a tf_record_iterator pointing at <path to dir>/02-28_09-51-54/Output/events.out.tfevents.1582913186.ef0b4b19e20b
I0625 18:36:54.783612 139852402177792 application.py:403] Plugin listing: is_active() for beholder took 0.137 seconds
I0625 18:36:54.880321 139852402177792 application.py:403] Plugin listing: is_active() for hparams took 0.000 seconds
I0625 18:36:54.784358 139850493712128 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:54] "GET /data/experiments HTTP/1.1" 200 -
I0625 18:36:54.881115 139850510497536 event_file_loader.py:138] Loading events from <path to dir>/02-28_09-51-54/Output/events.out.tfevents.1582913186.ef0b4b19e20b
I0625 18:36:55.018036 139852402177792 application.py:403] Plugin listing: is_active() for mesh took 0.000 seconds
I0625 18:36:55.355031 139850726864640 application.py:403] Plugin listing: is_active() for scalars took 0.000 seconds
I0625 18:36:55.592752 139850493712128 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:55] "GET /data/experiments HTTP/1.1" 200 -
I0625 18:36:55.894565 139850502104832 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:55] "GET /data/environment HTTP/1.1" 200 -
I0625 18:36:56.048448 139852402177792 application.py:403] Plugin listing: is_active() for frl_slurm took 0.000 seconds
I0625 18:36:56.311950 139850726864640 application.py:403] Plugin listing: is_active() for custom_scalars took 0.000 seconds
I0625 18:36:56.682393 139852402177792 application.py:403] Plugin listing: is_active() for whatif took 0.000 seconds
I0625 18:36:56.893290 139850726864640 application.py:403] Plugin listing: is_active() for images took 0.000 seconds
I0625 18:36:57.156458 139850726864640 application.py:403] Plugin listing: is_active() for audio took 0.000 seconds
I0625 18:36:57.272142 139850726864640 application.py:403] Plugin listing: is_active() for debugger took 0.000 seconds
I0625 18:36:57.272681 139850726864640 application.py:403] Plugin listing: is_active() for graphs took 0.000 seconds
I0625 18:36:57.272964 139850726864640 application.py:403] Plugin listing: is_active() for distributions took 0.000 seconds
I0625 18:36:57.273322 139850726864640 application.py:403] Plugin listing: is_active() for histograms took 0.000 seconds
I0625 18:36:57.273509 139850726864640 application.py:403] Plugin listing: is_active() for text took 0.000 seconds
I0625 18:36:57.273723 139850726864640 application.py:403] Plugin listing: is_active() for pr_curves took 0.000 seconds
I0625 18:36:57.273896 139850726864640 application.py:403] Plugin listing: is_active() for profile_redirect took 0.000 seconds
I0625 18:36:57.274482 139852402177792 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:57] "GET /data/plugins_listing HTTP/1.1" 200 -
I0625 18:36:57.397578 139850726864640 application.py:403] Plugin listing: is_active() for beholder took 0.123 seconds
I0625 18:36:57.397810 139850726864640 application.py:403] Plugin listing: is_active() for hparams took 0.000 seconds
I0625 18:36:57.507860 139850726864640 application.py:403] Plugin listing: is_active() for mesh took 0.000 seconds
I0625 18:36:57.508049 139850726864640 application.py:403] Plugin listing: is_active() for frl_slurm took 0.000 seconds
I0625 18:36:57.508178 139850726864640 application.py:403] Plugin listing: is_active() for whatif took 0.000 seconds
I0625 18:36:57.508962 139850726864640 _internal.py:113] 127.0.0.1 - - [25/Jun/2020 18:36:57] "GET /data/plugins_listing HTTP/1.1" 200 -
I0625 18:36:57.509607 139852360230656 plugin_event_multiplexer.py:203] Adding run from directory <path to dir>/04-25_13-21-29/Output
I0625 18:36:57.509920 139852360230656 plugin_event_multiplexer.py:159] Constructing EventAccumulator for <path to dir>/04-25_13-21-29/Output
^C[zaatri@zaatri-fedora-PC0TU8E0 FRL-2020-Tensorboard]$

**Comment by nfelt** [comment]
Thanks for the extra logs.  It's surprising to me that it would be hanging at this line; the only code that should be happening between those two log lines is basically a call to `tf.io.gfile.exists(logdir)` and then `tf.io.gfile.isdir(logdir)`.

Is this any kind of unusual filesystem like a network file system?

It's probably going to be hard for us to debug this much further from our end unless there's a way you can trigger the issue with a standard setup, e.g. something we could spin up a VM to replicate.  I'd suggest maybe editing the python files to add extra logging to see if you can pinpoint the slowest line, e.g. in the following function:

https://github.com/tensorflow/tensorboard/blob/365ab1f5fe2d5b76556fe83af322cb5078e3ab01/tensorboard/backend/event_processing/io_wrapper.py#L190

**Comment by jz-fb** [comment]
Looks to be some blocking issue introduced by SSHFS. This wasn't an issue for a while. Size doesn't seem to be the issue here, just SSHFS seems to have the ability to stall things.

**Comment by nfelt** [comment]
Okay great, glad you figured it out and thanks for updating the issue.
