### ISSUE TITLE
Tensorboard not showing complete training summaries

### ISSUE THREAD

**Issue by RishikMani** [tensorflow/tensorboard#3771]
## Environment information (required)

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='march', release='4.20.0-tf1-ll', version='#1 SMP PREEMPT Wed Jan 9 11:57:20 CET 2019', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==1.14.0
INFO: installed: tensorflow==1.14.0
INFO: installed: tensorflow-estimator==1.14.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.14.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '1.14.0'
INFO: tensorflow.__git_version__: 'unknown'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/homes/rmani/miniconda3/envs/MasterThesis/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'march.Compute.TechFak.DE'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/homes/rmani/miniconda3/envs/MasterThesis/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
astor==0.7.1
biwrap==0.1.6
certifi==2019.11.28
colorlog==4.1.0
cycler==0.10.0
gast==0.2.2
google-pasta==0.1.8
grpcio==1.23.0
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==3.1.2
numpy==1.16.4
opencv-python==4.1.2.30
Pillow==7.0.0
pip==19.3.1
progressbar==2.5
protobuf==3.11.2
pyparsing==2.4.6
python-dateutil==2.8.1
scipy==1.4.1
setuptools==44.0.0.post20200102
six==1.13.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-plot==0.3.2
termcolor==1.1.0
Werkzeug==0.16.0
wheel==0.33.6
wrapt==1.11.2

``````

## Issue description

I have my model trained and I save it at every 500th iteration. In my log directory I could see all the different model states. I also verified the checkpoint files whether they are in sync or not. When I ran tensorboard, I could only see partial logging of the summaries. Why after certain number of iterations, the summaries are never saved? It worked sometimes before but now it is the second time that I am losing on summary details.

The output of `tensorboard --inspect --logdir=train_dir` is as follows:
```
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
train_dir/rn-20200626-153759
train_dir/rn-20200628-123108
train_dir/baseline-20200626-165240

These tags are in train_dir/rn-20200626-153759:
audio -
histograms -
images -
scalars
   accuracy_1
   cross_entropy
   optimizer_loss/global_norm/clipped_gradient_norm
   optimizer_loss/global_norm/gradient_norm
   optimizer_loss/loss
tensor -
======================================================================

Event statistics for train_dir/rn-20200626-153759:
audio -
graph -
histograms -
images -
scalars
   first_step           1
   last_step            10985
   max_step             10985
   min_step             1
   num_steps            10985
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

These tags are in train_dir/rn-20200628-123108:
audio -
histograms -
images -
scalars
   accuracy_1
   cross_entropy
   optimizer_loss/global_norm/clipped_gradient_norm
   optimizer_loss/global_norm/gradient_norm
   optimizer_loss/loss
tensor -
======================================================================

Event statistics for train_dir/rn-20200628-123108:
audio -
graph -
histograms -
images -
scalars
   first_step           47001
   last_step            50000
   max_step             50000
   min_step             47001
   num_steps            3000
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

These tags are in train_dir/baseline-20200626-165240:
audio -
histograms -
images -
scalars
   accuracy_1
   cross_entropy
   optimizer_loss/global_norm/clipped_gradient_norm
   optimizer_loss/global_norm/gradient_norm
   optimizer_loss/loss
tensor -
======================================================================

Event statistics for train_dir/baseline-20200626-165240:
audio -
graph -
histograms -
images -
scalars
   first_step           1
   last_step            11460
   max_step             11460
   min_step             1
   num_steps            11460
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```

I also have opened up a question on [stackoverflow](https://stackoverflow.com/questions/62628404/tensorboard-does-not-show-complete-summaries). The model details on stackoverflow are different as it was posted for previous models. Please let me know if any other details are required.

Thanks,
Rishik

**Comment by nfelt** [comment]
Is it possible to provide a minimal reproduction of the training loop code that produces this behavior?  It will be hard to diagnose the issue without knowing what you're doing to write summaries.

Also, it looks like the steps in one of the files (`train_dir/rn-20200628-123108`) do go up to 50,000 (but only start at 47,000).  Do you see those summaries in TensorBoard for that run name?

**Comment by futureisatyourhand** [comment]
> 

Hi, I have the same problem, how did you solve it?
Thanks!

**Comment by futureisatyourhand** [comment]
> Hi, I have the same problem, how did you solve it?
> Thanks!



> ## Environment information (required)
> ```
> --- check: autoidentify
> INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682
> 
> --- check: general
> INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
> INFO: os.name: posix
> INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='march', release='4.20.0-tf1-ll', version='#1 SMP PREEMPT Wed Jan 9 11:57:20 CET 2019', machine='x86_64')
> INFO: sys.getwindowsversion(): N/A
> 
> --- check: package_management
> INFO: has conda-meta: True
> INFO: $VIRTUAL_ENV: None
> 
> --- check: installed_packages
> INFO: installed: tensorboard==1.14.0
> INFO: installed: tensorflow==1.14.0
> INFO: installed: tensorflow-estimator==1.14.0
> 
> --- check: tensorboard_python_version
> INFO: tensorboard.version.VERSION: '1.14.0'
> 
> --- check: tensorflow_python_version
> INFO: tensorflow.__version__: '1.14.0'
> INFO: tensorflow.__git_version__: 'unknown'
> 
> --- check: tensorboard_binary_path
> INFO: which tensorboard: b'/homes/rmani/miniconda3/envs/MasterThesis/bin/tensorboard\n'
> 
> --- check: addrinfos
> socket.has_ipv6 = True
> socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
> socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
> socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
> socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
> Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
> Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
> Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
> Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]
> 
> --- check: readable_fqdn
> INFO: socket.getfqdn(): 'march.Compute.TechFak.DE'
> 
> --- check: stat_tensorboardinfo
> INFO: directory: /tmp/.tensorboard-info
> INFO: .tensorboard-info directory does not exist
> 
> --- check: source_trees_without_genfiles
> INFO: tensorboard_roots (1): ['/homes/rmani/miniconda3/envs/MasterThesis/lib/python3.7/site-packages']; bad_roots (0): []
> 
> --- check: full_pip_freeze
> INFO: pip freeze --all:
> absl-py==0.9.0
> astor==0.7.1
> biwrap==0.1.6
> certifi==2019.11.28
> colorlog==4.1.0
> cycler==0.10.0
> gast==0.2.2
> google-pasta==0.1.8
> grpcio==1.23.0
> h5py==2.10.0
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> kiwisolver==1.1.0
> Markdown==3.1.1
> matplotlib==3.1.2
> numpy==1.16.4
> opencv-python==4.1.2.30
> Pillow==7.0.0
> pip==19.3.1
> progressbar==2.5
> protobuf==3.11.2
> pyparsing==2.4.6
> python-dateutil==2.8.1
> scipy==1.4.1
> setuptools==44.0.0.post20200102
> six==1.13.0
> tensorboard==1.14.0
> tensorflow==1.14.0
> tensorflow-estimator==1.14.0
> tensorflow-plot==0.3.2
> termcolor==1.1.0
> Werkzeug==0.16.0
> wheel==0.33.6
> wrapt==1.11.2
> ```
> 
> ## Issue description
> I have my model trained and I save it at every 500th iteration. In my log directory I could see all the different model states. I also verified the checkpoint files whether they are in sync or not. When I ran tensorboard, I could only see partial logging of the summaries. Why after certain number of iterations, the summaries are never saved? It worked sometimes before but now it is the second time that I am losing on summary details.
> 
> The output of `tensorboard --inspect --logdir=train_dir` is as follows:
> 
> ```
> ======================================================================
> Processing event files... (this can take a few minutes)
> ======================================================================
> 
> Found event files in:
> train_dir/rn-20200626-153759
> train_dir/rn-20200628-123108
> train_dir/baseline-20200626-165240
> 
> These tags are in train_dir/rn-20200626-153759:
> audio -
> histograms -
> images -
> scalars
>    accuracy_1
>    cross_entropy
>    optimizer_loss/global_norm/clipped_gradient_norm
>    optimizer_loss/global_norm/gradient_norm
>    optimizer_loss/loss
> tensor -
> ======================================================================
> 
> Event statistics for train_dir/rn-20200626-153759:
> audio -
> graph -
> histograms -
> images -
> scalars
>    first_step           1
>    last_step            10985
>    max_step             10985
>    min_step             1
>    num_steps            10985
>    outoforder_steps     []
> sessionlog:checkpoint -
> sessionlog:start -
> sessionlog:stop -
> tensor -
> ======================================================================
> 
> These tags are in train_dir/rn-20200628-123108:
> audio -
> histograms -
> images -
> scalars
>    accuracy_1
>    cross_entropy
>    optimizer_loss/global_norm/clipped_gradient_norm
>    optimizer_loss/global_norm/gradient_norm
>    optimizer_loss/loss
> tensor -
> ======================================================================
> 
> Event statistics for train_dir/rn-20200628-123108:
> audio -
> graph -
> histograms -
> images -
> scalars
>    first_step           47001
>    last_step            50000
>    max_step             50000
>    min_step             47001
>    num_steps            3000
>    outoforder_steps     []
> sessionlog:checkpoint -
> sessionlog:start -
> sessionlog:stop -
> tensor -
> ======================================================================
> 
> These tags are in train_dir/baseline-20200626-165240:
> audio -
> histograms -
> images -
> scalars
>    accuracy_1
>    cross_entropy
>    optimizer_loss/global_norm/clipped_gradient_norm
>    optimizer_loss/global_norm/gradient_norm
>    optimizer_loss/loss
> tensor -
> ======================================================================
> 
> Event statistics for train_dir/baseline-20200626-165240:
> audio -
> graph -
> histograms -
> images -
> scalars
>    first_step           1
>    last_step            11460
>    max_step             11460
>    min_step             1
>    num_steps            11460
>    outoforder_steps     []
> sessionlog:checkpoint -
> sessionlog:start -
> sessionlog:stop -
> tensor -
> ======================================================================
> ```
> 
> I also have opened up a question on [stackoverflow](https://stackoverflow.com/questions/62628404/tensorboard-does-not-show-complete-summaries). The model details on stackoverflow are different as it was posted for previous models. Please let me know if any other details are required.
> 
> Thanks, Rishik

Hi, I have the same problem, how did you solve it?
Thanks!

**Comment by RishikMani** [comment]
> > Hi, I have the same problem, how did you solve it?
> > Thanks!
> 
> > ## Environment information (required)
> > ```
> > --- check: autoidentify
> > INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682
> > 
> > --- check: general
> > INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
> > INFO: os.name: posix
> > INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='march', release='4.20.0-tf1-ll', version='#1 SMP PREEMPT Wed Jan 9 11:57:20 CET 2019', machine='x86_64')
> > INFO: sys.getwindowsversion(): N/A
> > 
> > --- check: package_management
> > INFO: has conda-meta: True
> > INFO: $VIRTUAL_ENV: None
> > 
> > --- check: installed_packages
> > INFO: installed: tensorboard==1.14.0
> > INFO: installed: tensorflow==1.14.0
> > INFO: installed: tensorflow-estimator==1.14.0
> > 
> > --- check: tensorboard_python_version
> > INFO: tensorboard.version.VERSION: '1.14.0'
> > 
> > --- check: tensorflow_python_version
> > INFO: tensorflow.__version__: '1.14.0'
> > INFO: tensorflow.__git_version__: 'unknown'
> > 
> > --- check: tensorboard_binary_path
> > INFO: which tensorboard: b'/homes/rmani/miniconda3/envs/MasterThesis/bin/tensorboard\n'
> > 
> > --- check: addrinfos
> > socket.has_ipv6 = True
> > socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
> > socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
> > socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
> > socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
> > Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
> > Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
> > Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
> > Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]
> > 
> > --- check: readable_fqdn
> > INFO: socket.getfqdn(): 'march.Compute.TechFak.DE'
> > 
> > --- check: stat_tensorboardinfo
> > INFO: directory: /tmp/.tensorboard-info
> > INFO: .tensorboard-info directory does not exist
> > 
> > --- check: source_trees_without_genfiles
> > INFO: tensorboard_roots (1): ['/homes/rmani/miniconda3/envs/MasterThesis/lib/python3.7/site-packages']; bad_roots (0): []
> > 
> > --- check: full_pip_freeze
> > INFO: pip freeze --all:
> > absl-py==0.9.0
> > astor==0.7.1
> > biwrap==0.1.6
> > certifi==2019.11.28
> > colorlog==4.1.0
> > cycler==0.10.0
> > gast==0.2.2
> > google-pasta==0.1.8
> > grpcio==1.23.0
> > h5py==2.10.0
> > Keras-Applications==1.0.8
> > Keras-Preprocessing==1.1.0
> > kiwisolver==1.1.0
> > Markdown==3.1.1
> > matplotlib==3.1.2
> > numpy==1.16.4
> > opencv-python==4.1.2.30
> > Pillow==7.0.0
> > pip==19.3.1
> > progressbar==2.5
> > protobuf==3.11.2
> > pyparsing==2.4.6
> > python-dateutil==2.8.1
> > scipy==1.4.1
> > setuptools==44.0.0.post20200102
> > six==1.13.0
> > tensorboard==1.14.0
> > tensorflow==1.14.0
> > tensorflow-estimator==1.14.0
> > tensorflow-plot==0.3.2
> > termcolor==1.1.0
> > Werkzeug==0.16.0
> > wheel==0.33.6
> > wrapt==1.11.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Issue description
> > I have my model trained and I save it at every 500th iteration. In my log directory I could see all the different model states. I also verified the checkpoint files whether they are in sync or not. When I ran tensorboard, I could only see partial logging of the summaries. Why after certain number of iterations, the summaries are never saved? It worked sometimes before but now it is the second time that I am losing on summary details.
> > The output of `tensorboard --inspect --logdir=train_dir` is as follows:
> > ```
> > ======================================================================
> > Processing event files... (this can take a few minutes)
> > ======================================================================
> > 
> > Found event files in:
> > train_dir/rn-20200626-153759
> > train_dir/rn-20200628-123108
> > train_dir/baseline-20200626-165240
> > 
> > These tags are in train_dir/rn-20200626-153759:
> > audio -
> > histograms -
> > images -
> > scalars
> >    accuracy_1
> >    cross_entropy
> >    optimizer_loss/global_norm/clipped_gradient_norm
> >    optimizer_loss/global_norm/gradient_norm
> >    optimizer_loss/loss
> > tensor -
> > ======================================================================
> > 
> > Event statistics for train_dir/rn-20200626-153759:
> > audio -
> > graph -
> > histograms -
> > images -
> > scalars
> >    first_step           1
> >    last_step            10985
> >    max_step             10985
> >    min_step             1
> >    num_steps            10985
> >    outoforder_steps     []
> > sessionlog:checkpoint -
> > sessionlog:start -
> > sessionlog:stop -
> > tensor -
> > ======================================================================
> > 
> > These tags are in train_dir/rn-20200628-123108:
> > audio -
> > histograms -
> > images -
> > scalars
> >    accuracy_1
> >    cross_entropy
> >    optimizer_loss/global_norm/clipped_gradient_norm
> >    optimizer_loss/global_norm/gradient_norm
> >    optimizer_loss/loss
> > tensor -
> > ======================================================================
> > 
> > Event statistics for train_dir/rn-20200628-123108:
> > audio -
> > graph -
> > histograms -
> > images -
> > scalars
> >    first_step           47001
> >    last_step            50000
> >    max_step             50000
> >    min_step             47001
> >    num_steps            3000
> >    outoforder_steps     []
> > sessionlog:checkpoint -
> > sessionlog:start -
> > sessionlog:stop -
> > tensor -
> > ======================================================================
> > 
> > These tags are in train_dir/baseline-20200626-165240:
> > audio -
> > histograms -
> > images -
> > scalars
> >    accuracy_1
> >    cross_entropy
> >    optimizer_loss/global_norm/clipped_gradient_norm
> >    optimizer_loss/global_norm/gradient_norm
> >    optimizer_loss/loss
> > tensor -
> > ======================================================================
> > 
> > Event statistics for train_dir/baseline-20200626-165240:
> > audio -
> > graph -
> > histograms -
> > images -
> > scalars
> >    first_step           1
> >    last_step            11460
> >    max_step             11460
> >    min_step             1
> >    num_steps            11460
> >    outoforder_steps     []
> > sessionlog:checkpoint -
> > sessionlog:start -
> > sessionlog:stop -
> > tensor -
> > ======================================================================
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also have opened up a question on [stackoverflow](https://stackoverflow.com/questions/62628404/tensorboard-does-not-show-complete-summaries). The model details on stackoverflow are different as it was posted for previous models. Please let me know if any other details are required.
> > Thanks, Rishik
> 
> Hi, I have the same problem, how did you solve it? Thanks!

Unfortunately, I wasn't able to solve it. Also I do not remember anymore what other alternatives I tried. :(
