### ISSUE TITLE
TF 1.15 test failure: InteractiveDebuggerPluginTest.testHealthPill

### ISSUE THREAD

**Issue by nfelt** [tensorflow/tensorboard#3775]
We're seeing the following test failure for TF 1.15 - I think this isn't affecting the nightly CI since the test is probably being cached as passing, but I can repro the failure against TensorFlow 1.15.0 in a fresh virtualenv against current HEAD.

```
======================================================================
ERROR: testHealthPill (__main__.InteractiveDebuggerPluginTest)
testHealthPill (__main__.InteractiveDebuggerPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/nickfelt/.cache/bazel/_bazel_nickfelt/3cdf037ab9be95ef9846209ffcda115e/sandbox/linux-sandbox/232/execroot/org_tensorflow_tensorboard/bazel-out/k8-fastbuild/bin/tensorboard/plugins/debugger/interactive_debugger_plugin_test.runfiles/org_tensorflow_tensorboard/tensorboard/plugins/debugger/interactive_debugger_plugin_test.py", line 1038, in testHealthPill
    self.assertAllClose(1.0, tensor_data[0])  # IsInitialized.
TypeError: 'NoneType' object is not subscriptable
```

@caisq mind taking a look?  Long term we can drop 1.15.0 compatibility, but since it's just the one test if there's an easy fix that would be preferable.

**Comment by caisq** [comment]
I'll take a look at that. The test itself or the code it's testing hasn't change recently. So it probably is due to some dependency change.

**Comment by caisq** [comment]
This seems to be due to a numpy version change. In numpy 1.19.0, which was released on 2020-06-20, 
`np.issubdtype(np.float32, np.float)` no longer evaluates to `True`.

**Comment by caisq** [comment]
Never mind. I'm supposed to use `np.floating`, instead of `np.float`. There is a deprecation warning in earlier versions related to this.
