### ISSUE TITLE
Audio thumbnails/summaries in the embedding visualization

### ISSUE THREAD

**Issue by dandelionmane** [tensorflow/tensorboard#38]
Migrated from https://github.com/tensorflow/tensorflow/issues/7106

> We (@pfcm and I) have been working with audio data (bird songs) and would like a way to inspect (via listening) embeddings of small chunks of audio files. The main use would be to help us to validate and explore our data. In our setting we have few labels, so we are especially interested in using it to inspect clusters and validate (with humans) their accuracy/reliability/clusteryness. 
> 
> We would like to know;
> * Are you guys planning on adding this sort of feature to tensorflow? If so, can we help to speed it up? 
> * If we were do it how would you recommend that we implement it so that it is supported in the future?

> We would like audio summaries to work with the embedding visualiser. Much like there are thumbnails of each mnist image (see link), we would like to be able to click on an embedded datapoint; to listen to it (currently we are just using the spectrograms as image thumbnails) and to figure out where it came from (which part of which audio recording).

**Comment by dsmilkov** [comment]
Hi @act65 and @PFCM,

This is a cool idea. Unfortunately, we don't plan on adding this sort of functionality, but I'd be happy to review and accept a contribution if you decide to contribute.

Regarding implementation, it will be a decent-sized change. You will need to encode the sound url/data in [PointMetadata](https://github.com/tensorflow/tensorboard/blob/84b7dd0b2e02aacbbf9f21100c049f4d3d2d48aa/tensorboard/plugins/projector/vz_projector/data.ts#L27). I recommend using a reserved key for this data (e.g. `__AUDIO__`).

Then you need to register a custom `hoverListener` [here](https://github.com/tensorflow/tensorboard/blob/84b7dd0b2e02aacbbf9f21100c049f4d3d2d48aa/tensorboard/plugins/projector/vz_projector/vz-projector.ts#L445) if metadata of type `__AUDIO__` is found in the data. Then on hover you need to render/play the audio using html.

Feel free to re-open this issue when when/if decide on sending us a contribution.

Thanks!

**Comment by dschwertfeger** [comment]
Hi @dsmilkov,

I was looking for how to play audio in the TensorBoard's embeddings tab and found this issue. 

You already provided a few useful hints for implementing this two months ago. I was wondering if anything has changed since then?

If not, I'd give this a shot, following your pointers.

**Comment by dsmilkov** [comment]
Hi! Nothing changed on our side. Feel free to go ahead with implementation. I'd be happy to review!

**Comment by xiaogehh** [comment]
That's cool.I use embedding to visualize phoneme if has a function like this will be very powerful.
Like  this  cool  project!

> https://experiments.withgoogle.com/ai/bird-sounds

**Comment by jonnor** [comment]
https://github.com/kokimame/tensoba is a fork with basic audio playback capabilities. No affiliation, just found it looking for a solution :)
