### ISSUE TITLE
What-if tool in TB Request failed due to the Network Error 404

### ISSUE THREAD

**Issue by yujiawang4** [tensorflow/tensorboard#3842]
Hi team,

Currently I'd like to use what-if tool from TensorBoard, but when I set up the model and data, it get a Request 404 Error:
![Screen Shot 2020-07-13 at 11 13 33 PM](https://user-images.githubusercontent.com/35843384/87578198-b6f49680-c699-11ea-912f-f19fa3f89b91.png)

## Environment information (required)

I run the TensorBoard in HDFS with version 0.2.0, does what-if tool also support for reading data from hdfs?

## Steps to reproduce (required)

This is my settings:
![Screen Shot 2020-07-15 at 12 44 21 PM](https://user-images.githubusercontent.com/35843384/87578095-8b71ac00-c699-11ea-98ae-fef4914f4619.png)

Really appreciate your help!

**Comment by jameswex** [comment]
The What-If Tool supports opening datasets from files accessible to the tf.gfile commands. 
@stephanwlee do you know if tf.gfile supports hdfs paths?

**Comment by stephanwlee** [comment]
According to TensorFlow public doc, hdfs is supposed to be supported: https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile

**Comment by jameswex** [comment]
@yujiawang4 what errors do you see in the terminal running the tensorboard instance when it tries to load the data and gives a 404?

**Comment by yujiawang4** [comment]
Thanks for the quick reply! 

Now the TensorBoard has been integrated with our JupyterHub, and I'm trying to find a way for our users using WIT through Tensorboard directly according to this instruction:  https://www.tensorflow.org/tensorboard/what_if_tool, but it didn't work.
The error message as below:
`Request failed: RequestNetworkError: RequestNetworkError: 404 at /data/plugin/whatif/examples_from_path?examples_path=hdfs%3A%2F%2Fdefault%2Fuser%2Fusername%2Fuci_census%2Fadult.tfrecord&max_examples=1000&sampling_odds=1&sequence_examples=false`

Does that mean I need `pip install witwidget` and enable it for Jupyter and use tf.gfile to read from the HDFS, rather than open data from the Tensorboard UI and setup things through the above dialog?

Thanks for your help!

**Comment by jameswex** [comment]
Ah thanks for the background. To use WIT in jupyter notebooks, please use WIT in standalone mode as opposed to inside of TensorBoard.  In that case, you'll load the data from disk inside your notebook and just pass a list of datapoints to the WitWidget object in the notebook. See https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/

**Comment by yujiawang4** [comment]
Many thanks for the information! I'll try things in that way.
