### ISSUE TITLE
ng_tensorboard shows “No dashboards are active” on invalid dashboard

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#3856]
Compare `localhost:6006/legacy.html#wat` with `localhost:6006/#wat`. The
former shows “There’s no dashboard by the name of “`hmm`””, as desired.
But the latter shows “No dashboards are active for the current data
set”, even if dashboards are active. It also shows the first dashboard
as highlighted in the nav bar; not sure if related.

![Screenshot of “No dashboards are active” even though they clearly
are][ss]

[ss]: https://user-images.githubusercontent.com/4317806/87986227-b12ff400-ca91-11ea-97bd-6fcd5859265e.png

Repro on TensorBoard 2.3.0a20200720.

**Comment by nfelt** [comment]
BTW I think this is b/157271562 internally.
