### ISSUE TITLE
How to change the color of tensorboard?

### ISSUE THREAD

**Issue by fanyuzeng** [tensorflow/tensorboard#3866]
Please describe the problem that you’re facing and the enhancements that
you’d like to see. Feel free to include screenshots or code samples.
..

**Comment by psybuzz** [comment]
Thank you for the report.  Closing this issue since there is a duplicate.  Please follow the other issue for updates
https://github.com/tensorflow/tensorboard/issues/893

**Comment by psybuzz** [comment]
Currently this is not yet available, but given the amount of user requests, we do still plan to implement this in a future release.

**Comment by fanyuzeng** [comment]
This a way to change the color of tensorboard?
The page link:
https://blog.csdn.net/m0_37030242/article/details/108644391

**Comment by stephanwlee** [comment]
If you are okay with using the new feature, our new timeseries dashboard which subsumes scalars allow you to change the color:

![image](https://user-images.githubusercontent.com/2547313/97598808-917b6680-19c4-11eb-97af-809f3ceeacc4.png)

**Comment by fanyuzeng** [comment]
![image](https://user-images.githubusercontent.com/19756145/97600755-5caef400-1a44-11eb-9677-fec0964dfff7.png)
why there is no the new feature of my tensorboard to change its color?

**Comment by stephanwlee** [comment]
Ah, it is currently available in tb-nightly. Sorry for the confusion. If you are up for using the nightly feature, do, 
```
pip uninstall tensorboard
pip install tb-nightly
```

**Comment by fanyuzeng** [comment]
Thank you so much.
