### ISSUE TITLE
AttributeError: 'float' object has no attribute 'item'

### ISSUE THREAD

**Issue by dhanashri88** [tensorflow/tensorboard#3873]
Hi,
I am getting issue AttributeError: 'float' object has no attribute 'item'
while executing call back function callbacks = [checkpointer, earlystopper, lr_reducer, TensorBoardColabCallback(tbc)]
which call /usr/local/lib/python3.6/dist-packages/tensorboardcolab/callbacks.py
I have install install redis==2.10.6 still issue persist.
I am using google colab.

**Comment by wchargin** [comment]
Hi @dhanashri88! Thanks for the report. It looks like you’re talking
about the `tensorboardcolab` PyPI package. This package is actually
unrelated to TensorBoard itself, so unfortunately we can’t provide
support for it. TensorBoard comes with built-in support for Colab and
Jupyter notebooks, which you can read about in our documentation:
<https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks>
