### ISSUE TITLE
🚧 TensorBoard is migrating to Polymer 3 🧼

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#3887]
Due to our difficulty in maintaining infrastructure for our HTML import based Polymer, TensorBoard is migrating to all JS/TS style Polymer.

We expect the migration to take about one full week (2020/07/27-2020/08-03), so we would appreciate if you do not make changes to the Polymer based TensorBoard components. 

Will post updates and revised ETAs.

**Comment by stephanwlee** [comment]
Update to the migration:

We made great progress last week but we are not done yet. We are still waiting to finish below:

- [ ] plugins/distribution
- [ ] plugins/graph (#3932)
- [ ] plugins/histogram
- [ ] plugins/hparams
- [ ] plugins/image
- [ ] plugins/mesh (#3940)
- [ ] plugins/pr_curve
- [ ] plugins/scalars
- [ ] functional tests

Our new estimate is EOW (August 10th). Wish us luck! 🤞

**Comment by stephanwlee** [comment]
@rmothukuru Is there anything wrong with pinning? We would like to tell our contributors that they should not make the changes until the migration is over.

**Comment by rmothukuru** [comment]
@stephanwlee,
I'm sorry. It was accidentally done. Pinned it now. Thanks!

**Comment by stephanwlee** [comment]
Happy to report that the Polymer migration is done. However, we have not finished the cleanup to remove Polymer 2 code. We will definitely appreciate it if you can hold of making contribution until we can reshuffle our directories.

**Comment by stephanwlee** [comment]
Woah, we are finally done with the migration. Now the files are where they should be. There still are few final touch ups remaining but we should be able to take all the contributions.

Sorry about the long wait and thanks for being patient. 🙇
