### ISSUE TITLE
why can't I use tensorboard on the Windows?I have installed tensorflow-gpu 1.3.0 successfully,the enviroment is Win10,Anaconda 4.4.0,Python 3.6.1.When I input "tensorboard --logdir=path",no response.

### ISSUE THREAD

**Issue by sfailsthy** [tensorflow/tensorboard#391]

**Comment by sfailsthy** [comment]
the logs is from [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py)

**Comment by secsilm** [comment]
Same issue. I just upgrade my tensorflow to 1.3 and then tensorboard has no response when I start it. It works when I use tensorflow 1.2.

**Comment by lanpa** [comment]
Same issue here. But it's running instead, just type localhost:6006 in the browser.
![screenshot 4](https://user-images.githubusercontent.com/2005323/29508142-f067cf56-8685-11e7-9018-33bc73cad01b.png)

**Comment by sfailsthy** [comment]
@lanpa Thanks.I tried it just now,and it's running instead.

**Comment by psybuzz** [comment]
Based on the thread, it sounds like this issue has been resolved(?).  Closing the issue, but please feel free to comment if any more bugs arise.
