### ISSUE TITLE
🧹: Upgrade prettier to 2.x 

### ISSUE THREAD

**Issue by stephanwlee** [tensorflow/tensorboard#3989]
Upgrading formatter like prettier often creates unwanted changes. For prettier 2.0, too, configuration + formatting has changed a lot ([changelog](https://prettier.io/blog/2020/03/21/2.0.0.html)).

Now, we are now on TypeScript 3.8 using new JS/TS language features like optional chaining (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) but prettier fails to parse and fails violently. The support for 3.8 features were added at prettier 2.0 and, here, I propose we do another round of massive formatting changes (in ~2w).

**Comment by wchargin** [comment]
FWIW, I quite like the changes in Prettier 2.x. It’s generally a bit
more compact (especially with fluent chains), and in particular they
reduced the prevalence of weird behavior with template tag literals in
favor of just spilling the lines.

On TensorBoard, 74% of the diff consists only of line-internal
whitespace, which is mostly the change from `function() { … }` to
`function () { … }`. The remaining diff is +368/−465. Of course, the
absolute numbers will drop once we clean out the Polymer 3 migration.

We can do this safely and preserving history by temporarily disabling
the lint, checking in one or more reformatting commits to the new
version, then re-enabling the lint at the new version; later, we can add
the pure-reformat commits to [`.git-blame-ignore-revs`][1]. I’ve done
this for the Prettier 2.x upgrade on other projects; it works well:
<https://github.com/sourcecred/sourcecred/pull/1717/commits>

[1]: https://github.com/tensorflow/tensorboard/blob/2.3.0/.git-blame-ignore-revs

**Comment by wchargin** [comment]
I can grab this now that #3887 is done.
