### ISSUE TITLE
TB v1.15 Flask integration help request

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#4008]
Is flask supported within plugins inside TB v1.15?  I'm getting 404 errors.  If it is, can you give an example of an endpoint?  I'm calling `sAjaxSource: './tables/serverside_table',` on the client side.  I'm not sure if this is wrong, or if I'm not setting up TB side correctly.  

Client code
```
     $('#selector').DataTable({
        bProcessing: true,
        bServerSide: true,
        sPaginationType: 'full_numbers',
        lengthMenu: [[10, 25, 50, 100], [10, 25, 50, 100]],
        bjQueryUI: true,
        sAjaxSource: './tables/serverside_table',
        columns: [
          {data: 'Column A'},
          {data: 'Column B'},
          {data: 'Column C'},
          {data: 'Column D'},
```

Partial Server code that defines the endpoint
```
from flask import Blueprint, jsonify, request
from tensorboard_plugin_dlprof import table_builder
from tensorboard_plugin_dlprof import dlprof_flask_name

tables = Blueprint('tables', 'dlprof', url_prefix='/tables')

@tables.route("/serverside_table", methods=['GET'])
def serverside_table_content():
    data = table_builder.collect_data_serverside(request)
    return jsonify(data)
```
Server console
```
W0807  application.py:401] path /data/plugin/dlprof/tables/serverside_table not found, sending 404
```

Requesting help with endpoint designation/definition on TB server so that TB UI plugin can access.

Thanks.

**Comment by bmd3k** [comment]
Hi Chris,

I unfortunately don't have any experience with Flask nor do I have a specific example but hopefully I can point you in the right direction.

Did you already add an entry for your new endpoint in the `get_plugin_apps()` method of your `TBPlugin` implementation?
https://cs.opensource.google/tensorflow/tensorboard/+/1.15:tensorboard/plugins/base_plugin.py;l=66;drc=8d7f94829e3bab2b73f49d132372f264bcf87f5e

You would need an entry with key '/tables/serverside_table'.

The value for the entry needs to be a WSGI application to handle the request.  I believe Flask instances are WSGI applications.  So something like this might work:

```
flaskApp = Flask(__name__)
flaskApp.register_blueprint(tables)
```

And then the entry in get_plugin_apps would be:

```
'/tables/serverside_table': flaskApp
```

You may also need to modify your Blueprint to serve the entire path "/data/plugin/dlprof/tables/serverside_table" and not just "/tables/serverside_table".  It may look something like this:

```
tables = Blueprint('tables', __name__)

@tables.route('/data/plugin/dlprof/tables/serverside_table', methods=['GET'])
def serverside_table_content():
    data = table_builder.collect_data_serverside(request)
    return jsonify(data)
```

Please give these suggestions a try and let me know if you have any success.

**Comment by ceevee830** [comment]
Hi Brian,  thanks for the update....  I'll try this out and let you know shortly.  -Chris

**Comment by ceevee830** [comment]
Success!  Brian, thank you for your suggestions.  I was able to get everything working exactly how I wanted.
Question: Where does the `/data/plugin/dlprof` directory path prefix come from?

**Comment by ceevee830** [comment]
One more thing: From within a flask enpoint, I would like to query my TB plugin for its `_logdir`. 
@bmd3k What's the best way to do that?

**Comment by bmd3k** [comment]
Great!

Re: `/data/plugin/dlprof` path, this is described in the TBPlugin documentation:

- https://cs.opensource.google/tensorflow/tensorboard/+/1.15:tensorboard/plugins/base_plugin.py;l=45;drc=8d7f94829e3bab2b73f49d132372f264bcf87f5e

Re: querying for `_logdir`, implementations of TBPlugin are passed TBContext, which contains a `logdir` variable. Can you pass this value to your Flask app?

- https://cs.opensource.google/tensorflow/tensorboard/+/1.15:tensorboard/plugins/base_plugin.py;l=54;drc=8d7f94829e3bab2b73f49d132372f264bcf87f5e

**Comment by ceevee830** [comment]
Thanks!
