### ISSUE TITLE
Permission denied when capturing profile

### ISSUE THREAD

**Issue by SmartInWhut** [tensorflow/tensorboard#4044]
## Environment information (required)

k8s：1.19
image: tensorflow/serving:2.2.0 、tensorboard_img(python3.6+tensorflow2.2.0+tensorboard-plugin-profile)

## Issue description

i'm follow the guide [tensorboard ](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/tensorboard.md) to analyse my tf model performance in a kubernetes cluster. So i deployed a tfserving deploy and a tensorboard deploy respectively.
the serving pod:
      `containers:
    -
      args:

        - '--port=9000'

        - '--rest_api_port=8080'

        - '--model_name=half-test'

        - '--model_base_path=/path_to_model'

      command:

        - /usr/bin/tensorflow_model_server

      image: 'tensorflow/serving:2.2.0'

 the tensorboard pod
     args:

        - tensorboard

        - '--logdir=/home/'

        - '--path_prefix=/'

        - '--host=0.0.0.0'

       image: tensorboard_img`
when i capture the request as the guide(with the podIP:9000 of the serving pod),  after i send  a http inference request to the seving pod, i get a permission denied error. `Failed to capture profile: /home/plugins; Permission denied`  But the tensorboard pod is runing with root user, i can't figure out how did this happened. the instruct `chmod 777` doesn't work either.
thanks for any reply, this issue can be closed if it is not qualified.

**Comment by wchargin** [comment]
@qiuminxu, mind taking a look?

**Comment by qiuminxu** [comment]
In TF 2.2 profiler, part of the traces from TF model server directly, instead of sending it back to the TensorBoard and saves it. Is /home/ accessible to your model server as well? Can you check the `logdir` are accessible to both TensorBoard and model server? Is it possible to use a network storage such as GCS?

**Comment by SmartInWhut** [comment]
thanks a lot!!
Just as @qiuminxu says, it was my fault that i ran the model server pod with no writting  authority.
close this issue  cause it is solved.
