### ISSUE TITLE
Is  scalar able to resume the visualization of parameters if the training is paused and then resumed?

### ISSUE THREAD

**Issue by YixinKristy** [tensorflow/tensorboard#4055]
Please describe the problem that you’re facing and the enhancements that
you’d like to see. Feel free to include screenshots or code samples.

**Comment by wchargin** [comment]
Hi @YixinKristy! Yes, this is supported. If you create a summary writer
in a directory that already has summary data, your new data will be
appended.

For example, if you have a script like this (artifical example):

```python
import sys
import tensorflow as tf

start_step = int(sys.argv[1])
duration = int(sys.argv[2])

with tf.summary.create_file_writer("train").as_default():
    for step in range(start_step, start_step + duration):
        tf.summary.scalar("loss", 1.0 / (step + 1), step=step)
```

…and you run:

```
$ python test.py 0 5  # runs steps 0 through 4
$ python test.py 5 3  # runs steps 5 through 7
```

…then you’ll see two event files in the output directory:

```
$ ls train
train/events.out.tfevents.1597896827.HOSTNAME.2307936.5.v2
train/events.out.tfevents.1597896820.HOSTNAME.2307872.5.v2
```

…and in TensorBoard you’ll see a chart with 8 points:

![Screenshot of TensorBoard chart of `loss` with 8 continuous
points][ss]

This is handy in case your training job dies, or is killed or preempted.
As long as you can restart from a checkpoint and point to the same log
directories, everything should just work.

Does this answer your question?

[ss]: https://user-images.githubusercontent.com/4317806/90716108-f8f89580-e260-11ea-90d2-fad1982f0840.png

**Comment by wchargin** [comment]
I think that I’ve answered the question in the title, so I’ll go ahead
and close this—please feel free to comment if there’s anything else that
we can do for you. Thanks!
