### ISSUE TITLE
An error when using tensorboard with tensorflow-gpu

### ISSUE THREAD

**Issue by EvenQAQ** [tensorflow/tensorboard#4073]
I have just installed tensorflow-gpu version 2.3.0 with an installation of tensorboard 2.3.0. But it seems that there is something wrong.
![image](https://user-images.githubusercontent.com/29764720/90958444-2b0b3100-e4c7-11ea-9b0b-9e8eb90f6da3.png)

**Comment by rmothukuru** [comment]
@EvenQAQ,
As per this [Github Issue](https://github.com/tensorflow/tensorboard/issues/2968), `Tensorboard` should work fine despite these `warnings`. Please check and let us know if you face couldn't use `Tensorboard`. Thanks!

**Comment by rmothukuru** [comment]
@EvenQAQ,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
