### ISSUE TITLE
Having issue with support for multi-directory

### ISSUE THREAD

**Issue by jz-fb** [tensorflow/tensorboard#4085]
## Issue description

Following [this stackoverflow](https://stackoverflow.com/questions/36182380/how-do-display-different-runs-in-tensorboard) page I realized there was support for adding multiple directories (originally tasked with adding it in) however it doesn't work for me unless I break up the listed paths in data_ingester.py (path.split(',')). However there does seem to be support for it as the left column will list out the reports while the body of remains blank.

* Is this feature deprecated?

### Setup
* Fedora 31
* TB based on GIT from June 17

**Comment by rmothukuru** [comment]
@jz-fb,
Can you please confirm if you have followed the folder structure specified in [Tensorboard Documentation](https://github.com/tensorflow/tensorboard/blob/master/README.md#runs-comparing-different-executions-of-your-model). Thanks!

**Comment by jz-fb** [comment]
Not entirely sure what exactly is meant by specified structure as it's a recursive search from the paths specified by logdir. The events.out.tfevents....   files are present at each run and specifying a parent directory is just fine. The issue I have is as I was debugging the code I didn't see where the comma separated paths were being split before the child folders are iterated through. Going through the code what I see is the combined paths being passed. 

The strange part is there clearly is a point in the code where it does properly split up the paths as the left column is able to list the individual runs. I don't have a firm grasp of the inner workings. I do have a hunch that it might just be a naming scheme issue where the comma separated paths don't get assigned the correct name so nothing get's returned when display information. 

Some things that may help me get to the core of the issue is:
1.  Where does the comma separated paths get split up to there individual paths in code?
2.  In terms of the sequence of events how do things play out between the left column and the data presented? Are the list of runs first fed to the left column and then the page makes a request from that information or are both halves fed at the same time?

**Comment by pindinagesh** [comment]
@jz-fb 

Can you provide a reproducible standalone code to expedite the trouble shooting process? Thanks!

**Comment by bileschi** [comment]
Hi @jz-fb The spec parsing location happens here - which it seems you have already found:

https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/backend/event_processing/data_ingester.py;l=154

the `logdir_spec` format is not supported.  The preferred workaround for this is to create a symlink tree, rooted at `${ROOT}` that contains the logdirs of interest, and then run `tensorboard --logdir ${ROOT}`
