### ISSUE TITLE
[infra] Travis CI build on tf-nightly times out

### ISSUE THREAD

**Issue by psybuzz** [tensorflow/tensorboard#4091]
Several in-progress PRs have had a Travis CI run that failed only on the tf-nightly setup with a timeout error.
Even after removing lots of Polymer 2 code, we are seeing these timeouts.

See
https://travis-ci.org/github/tensorflow/tensorboard/builds/721612298
https://travis-ci.org/github/tensorflow/tensorboard/builds/721662030
https://travis-ci.org/github/tensorflow/tensorboard/builds/721479907

One option is to try re-building the Travis cache.  A current plan is the following modifications to .travis.yml:
- a PR `bazel build`, but disabled tests (now a good build is cached)
- a PR with both `bazel build` and the tests enabled (now a good build and tests are cached)

**Comment by stephanwlee** [comment]
You may actually want to stage this:
1. only have bazel fetch
2. bazel fetch + build
3. bazel fetch + build + test
4. etc...

(1) should be relatively fast and end within 5-10 minutes.
(2) this is expected to take a long time. Given that our cache is growing to 8GB, download and upload alone will take a long time. (and may push to 1:40hrs limit)

**Comment by psybuzz** [comment]
Closing now that the series has landed.

Each CI round currently runs 3 jobs, one per config.  For reference, here is the max running time spent per job, in different PRs:

Fetch = 17:03
Fetch + components_polymer3 = 22:38
Fetch + components_polymer3 + webapp = 39:55
Fetch + tensorboard/... = 50:51
Fetch + tensorboard/... + tests = 16:24
