### ISSUE TITLE
Tensorflow and tensorboard depend on each other

### ISSUE THREAD

**Issue by lspvic** [tensorflow/tensorboard#410]
Currently tensorflow and tensorboard depend on each other:
tensorflow(1.3.0) needs: tensorflow-tensorboard (<0.2.0,>=0.1.0)
tensorflow-tensorboard(0.1.4) needs: tensorflow (>=1.2.0)

And also tensorflow-gpu has a dependency on tensorboard:
tensorflow(1.3.0) needs: tensorflow-tensorboard (<0.2.0,>=0.1.0)

This result a problem:
If I install tensorflow-gpu from ``pip install tensorflow-gpu`` , it will install
tensorboard dependency and then install tensorflow from tensorboard 
inpendency.  And then tensorflow package overrides the gpu package.

Are there any ways to solve this?
Should the mutual dependency be decoupled?

**Comment by chihuahua** [comment]
To clear, the problem here is that the later installation of tensorboard triggers an installation of TensorFlow that overrides `tensorflow-gpu`, so we end up with just the CPU version of TensorFlow?

Thank you for noting this!

**Comment by wchargin** [comment]
Previous discussion on https://github.com/tensorflow/tensorboard/pull/373.

**Comment by chihuahua** [comment]
Thanks for the link to prior discussion. Let me know thoughts about https://github.com/tensorflow/tensorboard/pull/413 which I think fixes this.

**Comment by jart** [comment]
[TensorBoard 0.1.5](https://pypi.python.org/pypi/tensorflow-tensorboard/0.1.5) has been uploaded to PyPi, which removes the cyclic dependency.
