### ISSUE TITLE
Accepting list of lists as an arg for hp.Discrete()

### ISSUE THREAD

**Issue by cwfparsonson** [tensorflow/tensorboard#4105]
I have recently started using tensorboard and have found it super useful. One thing I'd like to be able to do is pass a list of lists as an argument for hp.Discrete when initialising hp.HParam()

For example, I have a model which can take a list of units and use them to generate a model with the specified number of units in each layer, where the number of elements in the list controls the number of layers generated (e.g. num_units = [32, 32, 16] would generate 3 hidden layers with 32, 32, and 16 units respectively). What I'd like to be able to do therefore is something like:

```python
from tensorboard.plugins.hparams import api as hp

HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([[32, 32, 16],[32,32,32],[32,16]])
```
Which would allow me to concisely try out a variety of number of layers & units. However, because I can only pass a list into hp.Discrete, I have to either fix the number of units per layer and make 2 hp.HParam() variables (one for number of layers, one for number of units per layer), or I have to keep defining more/fewer hp.HParam() variables depending on how many layers I'm putting in my model.

If it's possible, accepting a list of lists as an argument to hp.Discrete would be super helpful!

**Comment by cwfparsonson** [comment]
It would also be helpful to be able to accept a list of dictionaries (as well as the above).

**Comment by psybuzz** [comment]
Thanks for the feature request.

I think this raises some questions, including:
- what sort of filtering UI expectations go along with the ability to write a list of lists/dictionaries?
- does your use case require arbitrarily deeply nested lists/dictionaries?

Right now, discrete hparams appear in the UI as a list of checkbox filters, while intervals appear as a pair of input fields (max/min).  The example you gave of a list of units per layer is helpful.

Do you already have an idea of your filtering use case for this nested representation?

If the desired use case is a set of checkboxes for each layer-unit-list, this could be done by serializing each item as a string, before passing the list to hp.Discrete(["[32, 32, 16]", "[32, 32, 32]", '[32, 16]"]).  Does this address your need? e.g.
```
[ x ]  "[32, 32, 16]"
[ x ]  "[32, 32, 32]"
[ x ]  "[32, 16]"
```

**Comment by cwfparsonson** [comment]
@psybuzz Thank you that works perfectly for what I wanted to do particularly w.r.t. dictionaries, where you can also use `json.dumps()` to turn the dict/list etc into a string, put it in `hp.Discrete`, and then convert it back into dict/list etc with `json.loads()`

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!
