### ISSUE TITLE
UMAP visualization of projector plugin is broken (standalone)

### ISSUE THREAD

**Issue by aknoerig** [tensorflow/tensorboard#4154]
## Environment information (required)

I don't have the tensorboard package installed so the diagnostics tool is not producing anything useful, afaict.
I am working on the master branch and built just the projector plugin in standalone mode using bazel 2.1.0 on MacOS.

## Issue description

In the standalone version of the embeddings projector plugin, the UMAP visualization is broken. See console output below.

Steps to recreate:

1. Build the projector plugin using the  standalone target
1. Open in browser and wait for it to load the default dataset
1. Click UMAP tab to switch to UMAP visualization

Console output:

````
Uncaught (in promise) ReferenceError: UMAP is not defined
    at DataSet.<anonymous> (scatterPlotRectangleSelector.mjs:23)
    at Generator.next (<anonymous>)
    at element-mixin.js:108
    at new Promise (<anonymous>)
    at __awaiter (element-mixin.js:104)
    at DataSet.projectUmap (scatterPlotRectangleSelector.mjs:21)
    at HTMLElement.runUmap (projectorScatterPlotAdapter.mjs:339)
    at HTMLElement.showUmap (projectorScatterPlotAdapter.mjs:328)
    at HTMLElement.beginProjection (projectorScatterPlotAdapter.mjs:256)
    at HTMLElement.showTab (projectorScatterPlotAdapter.mjs:240)
````

**Comment by aknoerig** [comment]
I tried to dig deeper into the issue, but as I'm only getting started with TypeScript it's challenging to debug this.

The code seems to break where it is trying to [instantiate a new UMAP](https://github.com/tensorflow/tensorboard/blob/574068af7129db9970184778ed9f479b6c6f8613/tensorboard/plugins/projector/vz_projector/data.ts#L378). I'm surprised that there is no `import` of the UMAP library in `data.ts`, so I'm assuming that's where the problem lies. But then again the inclusion via a `.d.ts` file is still a mystery to me. 

Maybe @cannoneyed can shed some light on this?

**Comment by wchargin** [comment]
Hi @aknoerig! Thanks for the report. I can reproduce this, and it
appears to be broken in TensorBoard, too (i.e., not just in the
standalone version).

I suspect that this is probably related to the polymer3/TypeScript build
system changes recently.

**Comment by cannoneyed** [comment]
I can speak a bit to this - the way that UMAP is being included in the projector bundle is extremely hacky - it's basically just string concatenating the downloaded minified JS onto the bundle, and this had to do with the old polymer build system. If things have changed / gotten more modern it wouldn't surprise me if it no longer works.

@wchargin I might be able to carve out a bit of time to take a look at this next week, but if you wind up figuring out what's going on I'm happy to help with the UMAP side of things (eg exporting the library a different way or whatever)

**Comment by aknoerig** [comment]
Thanks a lot for the quick fix! The pull request works for me.
