### ISSUE TITLE
Using TensorBoard in Notebooks fails on tensorflow:2.3.0-jupyter

### ISSUE THREAD

**Issue by bhlarson** [tensorflow/tensorboard#4169]
Running the "https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks" example using the jupyter server.  It fails to load the tensorboard into the notebook
$ docker run -it -p 8888:8888 -p 6006:6006 tensorflow/tensorflow:2.3.0-jupyter 
"https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks" succeeded in:
$ docker run -it -p 8888:8888 -p 6006:6006 tensorflow/tensorflow:1.15.2-py3-jupyter

This issue has been reported in the past but has not been addressed.

**Comment by rmothukuru** [comment]
@bhlarson,
Can you please refer [Answer 1](https://stackoverflow.com/questions/41523005/how-to-use-tensorboard-in-a-docker-container-on-windows) and [Answer 2](https://stackoverflow.com/questions/33836728/view-tensorboard-on-docker-on-google-cloud/33838211#33838211) and let us know if it helps. Thanks!

**Comment by bhlarson** [comment]
Thank you for your feedback.  I have worked through Answer 1 and Answer 2 and there is no change in behavior.  

- In my tests, the docker image is Ubuntu 18.04 run and tested on an Ubuntu 18.04 computer so the issue is not with windows.
- With tensorflow/tensorflow:1.15.2-py3-jupyter, "curl http://localhost:6006/" retrieves tensorboard from the host os.  Curl is missing from the docker image.  Running curl http://localhost:6006/ from the host os when launched with both of the following is successful: 
docker run -it -p 8887:8888 -p 0.0.0.0:6006:6006 tensorflow/tensorflow:1.15.2-py3-jupyter or 
docker run -it -p 8887:8888 -p 6006:6006 tensorflow/tensorflow:1.15.2-py3-jupyter

- With docker run -it -p 8888:8888 -p 0.0.0.0:6006:6006 tensorflow/tensorflow:2.3.0-jupyter,  curl http://localhost:6006/ returns the tensorboard page from within the container but: "curl: (56) Recv failure: Connection reset by peer" from the host.

The tensorboad sever is certainly running and talking on port 6006.  Although the port is available and mapped, something in the  tensorflow/tensorflow:2.3.0-jupyter container is blocking the communication and preventing Tensorboard from being displayed in Jupyter.

**Comment by manivaradarajan** [comment]
@wchargin may have an idea

**Comment by bhlarson** [comment]
Is there someone that can take a look at this?  It is very easy to reproduce with 100% tensorflow code.  This has been submitted and ignored repeatedly!

**Comment by danielsiwiec** [comment]
I also had this issue. The solution is to add `--bind_all` to tensorboard's arguments. Otherwise, the UI is not accessible from outside docker. The PR above resolves this in the Guide

**Comment by bhlarson** [comment]
Thank you danielsiwiec.  Changing from 
%tensorboard --logdir logs
to
%tensorboard --bind_all --logdir logs
in https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb#scrollTo=KBHp6M_zgjp4

did enable tensorboard embedding in
$ docker run -it -p 8888:8888 -p 6006:6006 tensorflow/tensorflow:2.3.0-jupyter 

I appreciate the new working in https://github.com/tensorflow/tensorboard/pull/4195.
