### ISSUE TITLE
Store basic settings (e.g. reload period and pagination limit) in URL

### ISSUE THREAD

**Issue by gonnet** [tensorflow/tensorboard#4198]
I sometimes have to reload TensorBoard, which makes me lose the settings edited by clicking the gear-shaped icon in the top right corner, i.e.

- Reload data/Reload period settings,
- Pagination limit settings.

This is a subset of what is requested in #4000, but I think it would be easier to start with just these settings.

**Comment by stas00** [comment]
Any chance this issue could get some attention? 

We need to be able to set the number of widgets per page to a higher than 12.

Thank you!

**Comment by stephanwlee** [comment]
I believe this addressed in #5142 and in TensorBoard 2.6.0. Sorry about taking quite long to fix this!
