### ISSUE TITLE
[Windows] TensorBoard doesn't work

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#42]
This issue is migrated from tensorflow/tensorflow#5983.

> I installed the tensorflow for windows with
> pip install --upgrade --ignore-installed https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
> (I added the '--ignore-installed', for the official one didn't work on my pc)
> 
> Then I tried some code and ran tensorboard, however the browser shows nothing
> When running with '--debug' there appears some 404.
> I also tried tensorboard on mac os, it worked well, so the problem is not caused by the .tfevent file
> I've read through a bunch of related issues, and found that maybe the pip install didn't install tensorflow completely. And I searched the tensorflow file and did not found some certain files appears in mac os tensorflow, such as 'paper-toolkit'

**Comment by KapsonLabs** [comment]
Try starting Tensorboard with a short path to your log files...... My path was tensorboard --logdir:C:\tense\log.
This worked just fine. I guess tensorboard has a path character limitation. This should be fixed.
Long paths tend to take tensorboard forever to fetch log data

**Comment by mymultiverse** [comment]
Try without equal or quate 
`tensorboard --logdir path`

**Comment by hgadig** [comment]
I believe this issue no longer exists with the latest Tensorboard version. Closing this. Feel free to add your comments(if this is still an issue) and we will reopen if required. Thanks !
