### ISSUE TITLE
Long event names don't wrap in Tensorboard 61

### ISSUE THREAD

**Issue by langmore** [tensorflow/tensorboard#421]
I have many long event names (they are node names), and Tensorboard 61 doesn't wrap these in the display.  As a result, the names write over each other, and are unreadable.

**Comment by chihuahua** [comment]
Thank you for reporting. Could you please include a screenshot to clarify? Do you mean tag names like these?

![3gcm0ywunpc](https://user-images.githubusercontent.com/4221553/29729497-3fb06a1a-8991-11e7-9efe-b792d850b18b.png)

**Comment by ro3c** [comment]
Here is a sample of summary titles overlapping on page 2 and higher
![image](https://user-images.githubusercontent.com/14815348/30006212-6b0dd896-90c1-11e7-86a8-8b131c77642e.png)
