### ISSUE TITLE
upload with `--one_shot` should never create an empty experiment

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tensorboard#4225]
When uploading a logdir to TensorBoard.dev with `--one_shot` it is not helpful to create an experiment and then upload nothing. The user should instead be notified that there was nothing uploadable in the logdir and offered tips on how to remedy the situation.

Googlers: see internal bug b/170387919

**Comment by wchargin** [comment]
Why?

I agree that it would be nice to warn the user that nothing was
uploaded. But as a user it’s quite frustrating to run into systems that
are “discontinuous at zero”: i.e., do something different in an empty
case, even though there’s something perfectly logical to do.

For instance, imagine a user writes a script that uploads each of their
experiments from a historical directory to TensorBoard.dev and saves the
URLs in a CSV file. This would unnecessarily break their workflow by
refusing to give a URL for experiments that are empty.

`cp` doesn’t complain when I copy an empty file.

**Comment by bileschi** [comment]
While I'm sympathetic to the "discontinuous at zero" argument, I don't find the `cp` analogy compelling, as `cp` *does* complain when you attempt to copy a file that doesn't exist, whereas 

```
tensorboard dev upload --logdir=/dev/null/doesnt_exist --one_shot
``` 

will always create an empty experiment, and is _probably_ not what the user intended.

How about the following:

*  `upload --one_shot` will fail if the directory does not exist.
*  `upload --one_shot` will create an empty experiment if the directory exists, but doesn't contain anything uploadable.  In this case, we will output a large warning about how nothing was uploaded, and suggest a command regarding how to delete the empty experiment.

**Comment by wchargin** [comment]
> * `upload --one_shot` will fail if the directory does not exist.

Yeah, this sounds pretty reasonable to me, since the purpose of allowing
nonexistent paths is that they may be created while the upload is
pending, which is not really the case with `--one-shot`.

> * `upload --one_shot` will create an empty experiment if the directory exists, but doesn't contain anything uploadable.  In this case, we will output a large warning about how nothing was uploaded, and suggest a command regarding how to delete the empty experiment.

Yep, this makes sense to me, too.
