### ISSUE TITLE
bazel build failed

### ISSUE THREAD

**Issue by Boblis** [tensorflow/tensorboard#4232]
# bazel build tensorboard failed
## Environment information (required)
os: CentOS Linux release 7.5.1804 (Core)
bazel version: 2.2.0
Python: 3.6.8

## Steps to reproduce (required)

when i run the command: "bazel build tensorboard:tensorboard" on the terminal 
there is a error:
![image](https://user-images.githubusercontent.com/45844993/95812599-5af8e700-0d48-11eb-8077-0d38e9554edc.png)

**Comment by rmothukuru** [comment]
@Boblis,
Can you please let us know the version of `Tensorflow` and `Tensorboard` you are trying to install. Thanks!

**Comment by Boblis** [comment]
> @Boblis,
> Can you please let us know the version of `Tensorflow` and `Tensorboard` you are trying to install. Thanks!

I use the tf-nightly Version: 2.3.0.dev20200513 and the version of Tensorboard is 2.4.0a0

**Comment by bileschi** [comment]
tf-nightly `2.3.0.dev20200513` is pretty old, https://pypi.org/project/tf-nightly/2.3.0.dev20200513/   It is possible that head TensorBoard will no longer work with the older TensorFlow.  

Can you try updating tf-nightly to a more recent version?   I just built from commit `0f7010a0` using tf-nightly version `2.4.0-dev20201012`, following the instructions in [DEVELOPMENT.md](https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md)

If you are unable to use a more recent tf-nightly, can you please help us understand why?  We can then see if there is a workaround for your use case.

Thanks!

**Comment by Boblis** [comment]
> tf-nightly `2.3.0.dev20200513` is pretty old, https://pypi.org/project/tf-nightly/2.3.0.dev20200513/ It is possible that head TensorBoard will no longer work with the older TensorFlow.
> 
> Can you try updating tf-nightly to a more recent version? I just built from commit `0f7010a0` using tf-nightly version `2.4.0-dev20201012`, following the instructions in [DEVELOPMENT.md](https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md)
> 
> If you are unable to use a more recent tf-nightly, can you please help us understand why? We can then see if there is a workaround for your use case.
> 
> Thanks!

Thank you , I will try it

**Comment by Boblis** [comment]
> tf-nightly `2.3.0.dev20200513` is pretty old, https://pypi.org/project/tf-nightly/2.3.0.dev20200513/ It is possible that head TensorBoard will no longer work with the older TensorFlow.
> 
> Can you try updating tf-nightly to a more recent version? I just built from commit `0f7010a0` using tf-nightly version `2.4.0-dev20201012`, following the instructions in [DEVELOPMENT.md](https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md)
> 
> If you are unable to use a more recent tf-nightly, can you please help us understand why? We can then see if there is a workaround for your use case.
> 
> Thanks!

Thanks! it can work

**Comment by bileschi** [comment]
Great!  Closing this issue. Please re-open if necessary.
Thanks for using TensorBoard!
