### ISSUE TITLE
How to show indented json string with tf.summary.text?

### ISSUE THREAD

**Issue by SunDoge** [tensorflow/tensorboard#4247]
I want to show indented json string in tensorboard, for example,

```json
{
  "batch_size": 64,
  "model": {
    "arch": "resnet50"
  },
  "num_epochs": 200,
  "num_workers": 4
}
```

but all I get is a single line:

![image](https://user-images.githubusercontent.com/16167062/96451162-c14e9f80-1249-11eb-92aa-0f5ce59adf0a.png)

Is there any way I can show the json string in multiline?

**Comment by bileschi** [comment]
Hello @SunDoge,

  Thanks for your interest in TensorBoard!  The text dashboard does not allow for formatted text.  However, from the content of the text itself, it seems like you are trying to store some tree formatted data about the experiment itself.   Can you say more about your use case?  Is it the case you are trying to store enough information to be able to go back and determine which results are associated with what computational / algorithmic settings?   If so, you may be interested in what the hparams dashboard provides.  

  https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams

  If that does not suffice, please respond with what would be better.

Thanks!

**Comment by nfelt** [comment]
Actually the text dashboard does allow formatted text - the text is interpreted as markdown, including support for certain HTML tags.  To get the formatting you want, just wrap your text output in `<pre> </pre>` (as described in https://github.com/tensorflow/tensorboard/issues/830).

**Comment by SunDoge** [comment]
Hi, @bileschi , thanks for your suggestion. I want to check my experimental config and compare config for different experiments using tensorboard. `hparams` is great but my config is nested and I have not yet reached the hyperparameter tuning stage. 

And thank you @nfelt , you have solved my problem.
