### ISSUE TITLE
No edges appear in the graph explorer for Chrome 62.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#425]
![bnojao5eudk](https://user-images.githubusercontent.com/4221553/29738560-3c5699f4-89da-11e7-982e-0c40a784fdfe.png)

The problem is that Chrome 62 no longer supports the native `getPathSegAtLength` method. SVG 2 dropped the method. We should instead [make use of `getTotalLength()` and `getPointAtLength()` on the `SVGGeometryElement` object](https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement).

This issue must be fixed quickly, and then we should release a new pypi package as well as internal version. Otherwise, once Chrome 62 enters stable, no data flow edges will appear in the graph explorer for users (the graph would be very much broken). Chrome 62 has already entered the dev channel.

**Comment by lipond** [comment]
so what's the solution?

**Comment by chihuahua** [comment]
This problem is fixed! Upgrade to the latest tensorboard. Thanks!

**Comment by lipond** [comment]
hi @chihuahua, is there any way to upgrade tensorboard while not upgrading tensorflow?

**Comment by jart** [comment]
It might work if you pip install tb-nightly

**Comment by chihuahua** [comment]
Ah yeah! Per @jart, tb-nightly gives you bleeding edge features of TensorBoard.
