### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [tensorflow/tensorboard#4268]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://www.tensorflow.org/api_docs/python/tf/train/summary_iterator

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by rmothukuru** [comment]
@MrCull,
Thank you for identifying it. We will fix this from our side. We have given a Star to your Repo.
