### ISSUE TITLE
Can't view a graph

### ISSUE THREAD

**Issue by Nirvanabc** [tensorflow/tensorboard#428]
I have the most simply graph from the tutorial:
```
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)
sess = tf.Session()
node3 = tf.add(node1, node2)
sess.run([node1, node2, node3])
writer = tf.summary.FileWriter("output", sess.graph)
```
and give absolute path to tensorboard, but on http://lpt00:6006/#graphs   I see "inactive".
Inspect:
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []

File also exists (find ... | grep tfevents  -> .../output/events.out.tfevents.1503780894.lpt00)

**Comment by chihuahua** [comment]
I think I can view your graph in a jupyter notebook. Here's what I see.

![graphview](https://user-images.githubusercontent.com/4221553/29746052-5e526dd2-8a82-11e7-843a-d81ee6c48d76.png)

Could you please provide the flags you use to start TensorBoard? As well as perhaps the events files themselves in an attachment? Thank you!

**Comment by Nirvanabc** [comment]
tensorboard --logdir=/home/nirvana/python/pybra/output/ 
TensorBoard 0.1.4 at http://lpt00:6006 (Press CTRL+C to quit) 

and the screenshort: 
![2017-08-27-135738_1366x768_scrot](https://user-images.githubusercontent.com/26650540/29749236-2a9dca5c-8b38-11e7-9378-44902113acb9.png)
Thanks!

**Comment by chihuahua** [comment]
I was able to open the events data stored within tmp.txt:

![q3nnlnbswvr](https://user-images.githubusercontent.com/4221553/29802203-ba1b22f6-8c28-11e7-8b2d-5a747fc4cf40.png)

At the outset, what is that browser? I have never seen that UI before (in which the viewport just reads "Inactive" followed by a white box).

When you run `pip freeze` in a shell, do you `tensorflow-tensorboard` (and not just `tensorboard`) among the printed packages? Like this.

```
...
tblib==1.3.2
tensorflow-gpu==1.3.0rc2
tensorflow-tensorboard==0.1.2
terminado==0.6
...
```

**Comment by Nirvanabc** [comment]
I have Mozilla Iceweasel 38.5.0, and addon `Pentadactyl` 
`pip freeze` shows the following: 
`...
tensorflow==1.3.0
tensorflow-tensorboard==0.1.4
...
`

**Comment by chihuahua** [comment]
Interesting ... what happens if you try Chrome or Firefox? I can't install Iceweasel.

Thank you for helping us debug. :)

**Comment by Nirvanabc** [comment]
Oh, really, I've installed Chromium `chromium --version:  57.0.2987.98 Built on 8.7, running on Debian 8.9` and it works!
Thanks you for a good idea. =)
