### ISSUE TITLE
PIP: Don't lock markdown version to 2.2.0

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tensorboard#43]
https://github.com/tensorflow/tensorflow/issues/10744

> This markdown version lock could cause versioning conflict for downstream (e.g. if requirements are compiled and resolved by pip-compile). Wondering If there's a reason to lock this version. And it's already not sync with the CI install script (those --upgrade with locked version also doesn't seem right to me).

**Comment by psybuzz** [comment]
Closing, since this seems to have been addressed by https://github.com/tensorflow/tensorboard/pull/161
