### ISSUE TITLE
Constant time series with small values don't have proper axes

### ISSUE THREAD

**Issue by atishagarwala** [tensorflow/tensorboard#4362]
If I have a time series with a large, constant value f (e.g. 10.0), the y-axis scale reflects the constant value (scale goes from 0 to ~2f). However, if my value f is small (e.g. 0.01), the y-axis goes from -1.0 to 1.0, and does not at all reflect the scale of the constant.

It appears this issue was raised [here](https://github.com/tensorflow/tensorboard/pull/1507#discussion_r226418475) but not changed. I think constant curves should be made consistent - in the code where I noticed it, deviations from the known constant value were informative, and I spent a bunch of time thinking that I had a deviation (value of 0 instead of small but non-zero) due to not understanding how the plot axes were set.

Good:

![image](https://user-images.githubusercontent.com/23422890/99750012-76b48300-2a94-11eb-80f7-807897c35ee9.png)

Bad (real value of 1e-3):

![image](https://user-images.githubusercontent.com/23422890/99749978-64d2e000-2a94-11eb-9a9c-4b24cc564217.png)

**Comment by bmd3k** [comment]
Thanks, i was able to reproduce. I'll see if I can improve things for this case.

**Comment by nfelt** [comment]
@stephanwlee it looks like the domain scaling approach for gpu line chart is a bit different:
https://github.com/tensorflow/tensorboard/blob/ad652dacb11a5793ff7127709604e3842d7aa441/tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts#L114-L131

We probably want to be using a consistent domain "niceification" rule in both places, right?  So if the one for GPU line chart is better, maybe we should just backport that?
