### ISSUE TITLE
Embedding projector forces square aspect ratio

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#44]
Migrated from https://github.com/tensorflow/tensorflow/issues/8610.

@jongchyisu says:

> I tried to use tensorboard embedding visualization with sprite images. 
> It works well except two things:
> 1) Even though I set the image width and height as:
> embedding.sprite.single_image_dim.extend([my_width, my_height])
> and the projector_config.pbtxt file has:
> sprite {
>     image_path: "sprite.png"
>     single_image_dim: my_width
>     single_image_dim: my_height
> }
> Tensorboard **resizes the images to be square**, though it can get correct part from the sprite image, except that:
> 2) Every last image of each row is not correct. This happens when I have lots of images (like 200 images with size 70*100).
> 
> Seems like it only support square images?

@appierys says:

> I can confirm that indeed Tensorboard resizes the images to be square.

**Comment by dsmilkov** [comment]
Hi @jongchyisu,

Your observation is correct. We only support square sprite images and this limitation is imposed by our underlying WebGL texture implementation. Unfortunately, changing that requirement is a significant amount of work. It's much simpler to have the user generate square sprite images.

Note that you can have non-square number of data points by having the last row in the sprite image be partially filled: see the [sprite matrix example](https://www.tensorflow.org/get_started/embedding_viz#images) in the tutorial.

**Comment by canbakiskan** [comment]
If you want non-square sprites, you can fill the rest of the pixels with transparent values. See: #5149
