### ISSUE TITLE
Tensorboard starting problems

### ISSUE THREAD

**Issue by Sunflower4711** [tensorflow/tensorboard#443]
Hello,  I have a problem with tensorboard. I am working with tensorflow and ubuntu, now I also want to use tensorboard. I found this tutorial and tried it out 
http://web.stanford.edu/class/cs20si/lectures/notes_02.pdf
So I added this command into the terminal 
tensorboard-- logdir=./graphs

but it does not work, it get the error message:

"cant assign to operator" or "invalid syntax"

I also tried this 
tensorboard-- logdir="./graphs"
and this 
tensorboard-- logdir=./graphs --host 6006
nothing worked :(

Has anyone here ever worked with tensorboard and can give me a hint how to start it. Thank you very much!

**Comment by wchargin** [comment]
It appears that you wrote `tensorboard-- logdir` instead of `tensorboard --logdir`. The command is `tensorboard`; the argument is `--logdir`.

TensorBoard should work fine if you write `tensorboard --logdir ./graphs` instead. Let us know if this is not the case.

**Comment by Sunflower4711** [comment]
after I also changed the firewall settings, tensorboard started, thanks

**Comment by Gowrisankar97** [comment]
how to change the tensorboard firewall setting i am facing the same issue
