### ISSUE TITLE
There is a steep drop at the beginning of PR curves.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#444]
... at which both precision and recall are very close to 0.

![csq8ynwugjk 1](https://user-images.githubusercontent.com/4221553/29888016-3aac53a8-8d74-11e7-8061-305c3d9ae109.png)

Lets see if we can fix this within the PR curve summary op.

**Comment by chihuahua** [comment]
Here's what's going on around the steep drops.

PR curves, of course, assume a threshold value that increases (non-linearly) from right to left of the chart. Hence, as the threshold increases (We move left along the X axis), we become more stringent about what we deem to be a positive example (We classify fewer examples as positive).

At high enough thresholds, we only have a handful (< 10) of FPs and TPs. Precision is TP / (TP + FP), so a difference of 1 positive classification could change precision a lot. Hence, we generally see more volatility at those regions:

![csq8ynwugjk 1](https://user-images.githubusercontent.com/4221553/30000074-285bd2ee-9014-11e7-9783-1de8a43f7cc5.png)

Eventually, the threshold is so high that TP = 0, and so precision is 0. However, previous summary logic set a minimum of a very tiny value for the numerator,

```python
_TINY_EPISILON = 1e-7
...
precision = tf.maximum(_TINY_EPISILON, tp) / tf.maximum(
        _TINY_EPISILON, tp + fp)
```

and so the tooltip shows a tiny but non-zero value of 1e-7 at the steep drop.
![ezkmbgakvwy](https://user-images.githubusercontent.com/4221553/30000110-fca08270-9014-11e7-8e5a-c57425adcf9b.png)

If we keep increasing the threshold, both TP=0 and FP=0, at which point precision is undefined due to the denominator (TP + FP) being 0. Despite how precision is undefined, the summary logic assigns precision a value of 1 (as the code above shows), and so the precision shown by the visualization spikes up to 1.

**Comment by chihuahua** [comment]
I think we should do 3 things in response.

1. Reveal more info in the tooltips (counts for TP, FP, TN, FP, the specific threshold), so the user can reason through precision/recall calculations upon noticing suspicious areas of the chart. This effort is ongoing (#463).
2. Remove `tf.maximum(_TINY_EPISILON, tp)` from the numerator of the precision calculation (and just use `tp`). Otherwise, the user can see multiples of `_TINY_EPSILON` in the tooltip, and it's hard to decipher where that comes from. This effort is ongoing (#465).
3. On the frontend, after (1) is done (and the frontend has access to counts), we avoid rendering portions of charts for which TP+FP=0 (and precision is thus undefined). This avoids the large spike to 1 near the Y axis. A value of 1 where precision is undefined could mislead because the former implies there is area under the PR curve (but precision's actually undefined). We still render portions for which FP > 0 (and TP = 0), which could still mean a steep drop in precision to 0. If this is visually undesirable and unuseful, we can do away with that drop as well.

**Comment by chihuahua** [comment]
From Waymo folks: "I agree with all three of the actions that you proposed. For the last one, I think it we should render portions where FP > 0, otherwise it may be misleading, and those high scoring false positives would be useful to investigate."

**Comment by ansh-mehta** [comment]
@chihuahua does the explanation mean, it is absolutely fine if your classifiers behaves this way? I am writing a research paper and wanted to confirm once, here is my precision-recall curve

![image](https://user-images.githubusercontent.com/40193797/126340893-acee8b9b-6a04-4225-962c-88bc33ea87c4.png)
