### ISSUE TITLE
tensorboard profile simple matmul

### ISSUE THREAD

**Issue by nishitnshah** [tensorflow/tensorboard#4446]
I have a question rather than bug. I want to profile simple matmul running on GPU. This is not part of any deep learning model. My code looks like 
```
    import tensorflow as tf
    from model_config import ModelConfig
    def main():
        config = ModelConfig()
        config.create_model(B=1, S=4, M=4, C=0, N=0)
        #device = tf.device("/GPU:0")
        with tf.device("/GPU:0"):
            with tf.profiler.experimental.Profile('./'):
                tensor0 = tf.random.uniform((config.B, config.S, config.M))
                tensor1 = tf.random.uniform((config.M, config.M))
                # tensor2 = torch.empty((config.B, config.S, config.M))
                tensor2 = tf.matmul(tensor0, tensor1)
    if(__name__ == '__main__'):
        main()
```
I do see a log dir being created and contents are 

    input_pipeline.pb       
    kernel_stats.pb         
    memory_profile.json.gz  
    overview_page.pb        
    tensorflow_stats.pb     
    trace.json.gz           
    xplane.pb

But I dont see any tfevents file. 

Is it possible to profile simple operations like this? If so can someone help me how?

**Comment by rmothukuru** [comment]
@nishitnshah,
Documentation of [Profiler](https://www.tensorflow.org/guide/profiler) states that:

> Profiling helps you understand the hardware resource consumption (time and memory) of the various TensorFlow operations (ops) in **your model** and resolve performance bottlenecks and ultimately, make the model execute faster.

From that statement, `Tensorboard Profiler` works when we build `Models`. Thanks!

**Comment by nishitnshah** [comment]
Hmm. Then, how can I profile simple ops in tensor flow? Do I have to define arbitrary model with ops I want and run forward pass?

**Comment by rmothukuru** [comment]
@nishitnshah,
May be. Because even the [Tensorflow Blog](https://blog.tensorflow.org/2020/04/introducing-new-tensorflow-profiler.html) states:

> The TensorFlow Profiler (or the Profiler) provides a set of tools that you can use to measure the training performance and resource consumption of your TensorFlow models. 

Refer this [Tutorial](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) for more details. Thanks!

**Comment by rmothukuru** [comment]
@nishitnshah,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
