### ISSUE TITLE
Add descriptions atop PR curves.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#446]
We should pass the summary description stored within SummaryMetadata into the `description` field of `tf-card-heading` within the PR curves dashboard. This is in line with other dashboards and lets the user view rich-text descriptions of each PR curve.

This task will require some reconciling because each PR curve is associated with a tag, and each PR curve can have multiple runs. In turn, each run-tag combination has a description.

The scalars dashboard has logic to address this problem that we should make available to other dashboards.
https://github.com/tensorflow/tensorboard/blob/ba2ef0a2dac5881f37f81a55f17e18b7f9008416/tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html#L295

**Comment by wchargin** [comment]
I'm happy to do this if you like, as I wrote the original code.

**Comment by chihuahua** [comment]
The task is yours.
