### ISSUE TITLE
New color palate makes runs very difficult to distinguish

### ISSUE THREAD

**Issue by kho** [tensorflow/tensorboard#449]
Since Tensorboard 61, there has been a new color palate, where the first run is still orange, but the second run is dark red, and the third run is pink. These colors are really close to each other and as a result really hard to tell apart. See for example:
![image](https://user-images.githubusercontent.com/460372/29895641-e44b807c-8da7-11e7-8032-778fb3d7dca2.png)

**Comment by chihuahua** [comment]
Here is the discussion behind the previous color scale.
https://github.com/tensorflow/tensorboard/pull/288

One thing to note is that the colors should be accessible to color-blind people.

**Comment by Dapid** [comment]
The problem now is that it is equally bad for colour blind and normal vision, specially when the different runs are close.

Just switching the order will help a lot, so the first run is orange, the second teal, and so on.

**Comment by yingusxiaous** [comment]
I agree about the order: in the previous discussion, Paul Toh suggested the order: orange, blue, red, cyan, magenta, teal, grey. Can we default to his suggested order instead of[ orange, red, magenta](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorboard%2Fblob%2Fb24b3ae6a5ab61d2b3e15c1f746a5af13b904875%2Ftensorboard%2Fcomponents%2Ftf_color_scale%2Fpalettes.ts%23L57-L67&sa=D&sntz=1&usg=AFQjCNHFyg2FOuwBihXhIcp-gPa4f6Ltlw)?

**Comment by wchargin** [comment]
I'm not opposed in principle to changing the order of the palette. Any order that lists orange first and grey last is fine with me.

**However,** this is not a robust solution. You want runs that appear nearby _in the plot_ to have different colors; differentiating colors among runs with lexicographically similar _names_ will not accomplish this. For instance, if you have the runs
```
lr=1e-3,conv=1,fc=1
lr=1e-3,conv=1,fc=2
lr=1e-3,conv=2,fc=1
lr=1e-3,conv=2,fc=2
```
and you use the [orange, blue, red, cyan] order, then `conv=1,fc=1` and `conv=2,fc=1` will have similar colors; if those runs have similar curves (which seems plausible), then you'd have the same problem that you see here.

In general, there is **no universal ordering** that will work well on all datasets.

Note also that we are actually using Paul's suggested order: he says,
> I give the colours in order of hue, but if you prefer a 'random' order
> that still looks ordered: orange, blue, red, cyan, magenta, teal, grey.

We list the colors in order of hue, which is his primary suggestion. The order that you listed is his secondary suggestion, not his "suggested order."

**Comment by yingusxiaous** [comment]
I agree that this is not a robust solution -- and to be clear, there is no perfectly robust solution given that we only have 7 colors (4 experiments, with train and eval exceeds that!). 

However, I do think that current color choices are very suboptimal for the most common use cases; I conjecture that 1-2 experiments (with both eval and train) is probably much more common than 3+ experiments.

**Comment by wchargin** [comment]
Your conjecture seems plausible to me; like I said, changing the order is fine with me.

**Comment by nmjohn** [comment]
Just +1ing, I've found the low relative contrast between the colors difficult for someone with relatively full color perception. Given that there are only two or three lines, I think a better ordering of these colors is possible.

**Comment by yingusxiaous** [comment]
Great, preparing PR then.

**Comment by wchargin** [comment]
Closing per #453.
