### ISSUE TITLE
Information regarding the tensorflow.

### ISSUE THREAD

**Issue by likith012** [tensorflow/tensorboard#4499]
When I was trying to compute custom metrics in Keras using a custom Callbacks, Keras isn't allowing to pass the `validation_data`(I am using data generators)  to the `on_epoch_end` method of custom Callbacks. But tensorboard somehow passes the `validation_data` to the tensorboard callback in keras. Can you explain or point me to the code on how it does it ?

**Comment by rmothukuru** [comment]
@likith012,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
