### ISSUE TITLE
Polarized gradient in tensorboard embeddings

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#45]
This issue had been migrated from tensorflow/tensorflow#10105.

> Currently, default tensorboard color gradient goes from light yellow to dark blue (see screenshot), which works great for highlighting positive values (yellow dots become nearly invisible).
> 
> But it doesn't work well for displaying, let's say, sentiment scales (going from -1 to +1). The ability to choose a gradient going from red to blue would be helpful for visualizing polarized scales.

**Comment by dsmilkov** [comment]
Hi @bruchansky,

Thanks for the suggestion. We are happy to accept a contribution and I'd be happy to walk you through the code and review your change.

For now I will close this issue. Feel free to reopen with a PR contribution.
