### ISSUE TITLE
Be able to provide custom labels to edges

### ISSUE THREAD

**Issue by silky** [tensorflow/tensorboard#4518]
Presently, edges can have the label `scalar` or the output shape (the value of the special attribute `_output_shapes`) ( see https://github.com/tensorflow/tensorboard/blob/50e0555f98c14a3aabcef7225ff9c72a0eea4173/tensorboard/plugins/graph/tf_graph_common/edge.ts#L143 )

it would be great if there could be to explicitly set the edge label; for example with a special attribute `__output_edge_label`

```
__output_edge_label: "..."
```

thoughts?

easy enough to add if there is support?

**Comment by psybuzz** [comment]
Thanks for the report!  At the moment, the Graph dashboard does not have a friendly set of extension points for visual features like this.  We can consider this request as we investigate it.

To help us better understand your need, could you please describe what sort of information you intend to add to edge labels?  I'm curious what sort of label you would find meaningful beyond output shape.

**Comment by silky** [comment]
hey @psybuzz - thanks for the response; in reality i was interested in this for a non-tensorflow usecase; so i can actually just fork the repo and hack around myself; no need for it to be a feature here :)

thanks!
