### ISSUE TITLE
Running Tensorboard on M1

### ISSUE THREAD

**Issue by asgeorges** [tensorflow/tensorboard#4519]
Hi!  Currently trying to run a TB session locally on my mac (which is running the new M1).  

>> tensorboard
[1]    21532 illegal hardware instruction  tensorboard

My understanding of the situation is that TB requires AVX to run, whereas the new M1s don't support AVX.  Is all that correct?  Is there a way to currently run TB on the M1s?

**Comment by asgeorges** [comment]
NVM - it seems like this just fits into the broader category of running TF on M1.

**Comment by wchargin** [comment]
Yep! TensorBoard is pure Python, but depends on TensorFlow, which has
native code and may or may not work on new architectures. If all you
need is TensorBoard, you may be able to run it without TensorFlow (just
uninstall `tensorflow` from your virtualenv, or create a new virtualenv
and install just `tensorboard` into it). This has most of the
functionality of TensorBoard, but not all, and may be notably slower.
