### ISSUE TITLE
tensorboard installation

### ISSUE THREAD

**Issue by Vapster** [tensorflow/tensorboard#460]
Someone please tell me how to install tensorboard on windows!!!!!!
I do have docker and tensorflow

**Comment by chihuahua** [comment]
`tensorflow` lists `tensorflow-tensorboard` as a required package:
https://github.com/tensorflow/tensorflow/blob/74ccd0912e9afdf6c1e249096dcad1d2c072bb8b/tensorflow/tools/pip_package/setup.py#L39

Hence, if you installed tensorflow via pip on your docker instance (via [these instructions](https://www.tensorflow.org/install/install_windows)), then you should also be able to start tensorboard via the `tensorboard` command.

**Comment by Vapster** [comment]
thanks for your help! @chihuahua
