### ISSUE TITLE
Add missing docs for the Time Series dashboard

### ISSUE THREAD

**Issue by psybuzz** [tensorflow/tensorboard#4660]
Tracking issue for adding documentation that describes how to use the
Time Series dashboard. While some of its features are new (run color
customization, pinning), it notably does not require any extra setup
beyond what is already required for the Scalars/Histograms/Images
dashboards.

**Comment by pindinagesh** [comment]
@psybuzz 

Could you please look at this [PR](https://github.com/tensorflow/tensorboard/pull/5193) and confirm if this can be closed?

**Comment by psybuzz** [comment]
Thanks for checking in on this.  Seems reasonable to close.
