### ISSUE TITLE
"No checkpoint found" TensorBoard projector

### ISSUE THREAD

**Issue by AnnBkrv** [tensorflow/tensorboard#4673]
I want to load a custom embedding file and a metadata file into tensorboard's projector plugin. I've been following this tutorial mostly: https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin. I get the "no checkpoint found" error in spite of the checkpoint files being present in the folder. I also have used tensorboard's inspect function on the log directory and tensorboard can't find any event files. Here's my code:

`import os
from tensorboard.plugins import projector
import pandas as pd
import tensorflow as tf

weights = pd.read_csv ("test/vectors_test.tsv", sep = '\t')

log_dir = "test/logs/"
weights = tf.Variable(weights)
checkpoint = tf.train.Checkpoint(embedding=weights)
checkpoint.save(os.path.join(log_dir, "embedding.ckpt"))

Set up config
config = projector.ProjectorConfig()
config.model_checkpoint_path = os.path.join(log_dir, "embedding.ckpt")
embedding = config.embeddings.add()
embedding.tensor_name = "embedding/.ATTRIBUTES/VARIABLE_VALUE"
embedding.metadata_path = "test/metadata_test.tsv"
projector.visualize_embeddings(log_dir, config)

%load_ext tensorboard

%tensorboard --logdir test/logs/ --host localhost --port=1003
%tensorboard --inspect --logdir test/logs

**Comment by arghyaganguly** [comment]
@AnnBkrv , could you please provide the custom embedding and the metadata file(or a link to it) to help us expedite this issue?

**Comment by AnnBkrv** [comment]
@arghyaganguly Is there a way to send it to you in DM's?

**Comment by arghyaganguly** [comment]
Sure.Please DM me at arghyag@google.com

**Comment by arghyaganguly** [comment]
@AnnBkrv , the contents of my log directory  :-
1)checkpoint
2)embedding.ckpt-1.data-00000-of-00001
3)embedding..ckpt-1.index
4)projector_config.pbtxt

Contents of stdout:
===============================================
Processing event files.. (this can take a few minutes)
===============================================
No event files found within logdir test/logs

This is due to the absence of an event file.

But I don't see "No checkpoint found" error.

Some questions:
1)What is the current working directory when you try %tensorboard commands?
Are you at the parent directory of "test/logs/"? 
2)Could you please provide the contents of your log directory?
3)Also if your checkpoint file has  name 'checkpoint.txt' , could you please try changing it to 'checkpoint' and let us know the result?

**Comment by AnnBkrv** [comment]
1) My current working directory was the parent directory of test/logs
2) I have the same log directory contents (with the same names too) plus i put the meta_test.tsv in there myself. the meta file doesn't affect anything though
3) my checkpoint file is of type file and has no extension, so i guess i got the same result as you automatically

I see "no checkpoint found" when i switch over to the projector tab in tensorboard.

aren't the contents of the directory supposed to be the event files? A checkpoint should be an event file, shouldn't it?

**Comment by arghyaganguly** [comment]
Refering https://github.com/tensorflow/tensorboard/blob/master/README.md ,fequently asked questions to check event files , you might use :-

 find DIRECTORY_PATH | grep tfevents
 it returns null for me.i believe we need a .tfevents file.

**Comment by AnnBkrv** [comment]
I need to get the checkpoint function to create a .tfevents file?

**Comment by arghyaganguly** [comment]
Please refer [this](https://github.com/tensorflow/tensorboard/issues/2471)

**Comment by arghyaganguly** [comment]
Screenshot of my attempt.
![projector_tfboard](https://user-images.githubusercontent.com/75770622/107748782-9b409400-6d3f-11eb-9285-072ad9d723ca.png)

**Comment by AnnBkrv** [comment]
@arghyaganguly did you add some code? I can't get my projector screen to show anything other than the error message.

**Comment by arghyaganguly** [comment]
@AnnBkrv , i used the exact code which you've mentioned in your first comment.

**Comment by pindinagesh** [comment]
@AnnBkrv 

Could you please answer to (@arghyaganguly) comment. Thanks!

**Comment by pindinagesh** [comment]
@AnnBkrv 

Closing this issue. Please feel free to reopen if this still persists, and also refer this [issue](https://github.com/tensorflow/tensorboard/issues/4673) and [documentation](https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin) .Thanks
