### ISSUE TITLE
Fix link in README - Graph Explorer / Graph Visualiser

### ISSUE THREAD

**Issue by AlexAndrascu** [tensorflow/tensorboard#4702]
The link pointing to the Graph Explorer / Visualiser tutorial is broken:

(https://www.tensorflow.org/get_started/graph_viz)

**Comment by stephanwlee** [comment]
Thanks for raising this. When using `git grep`, there were three hits for `graph_viz`.

```
README.md:graph visualizer tutorial](https://www.tensorflow.org/get_started/graph_viz).
docs/r1/overview.md:graph visualizer tutorial](https://www.tensorflow.org/get_started/graph_viz).
tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts:            <a href="https://www.tensorflow.org/get_started/graph_viz"
```

**Comment by nfelt** [comment]
https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/graph_viz.md is where the original content now lives (the docs from TF 1 are no longer rendered on tensorflow.org, they're only in GitHub).  Might be better to instead replace with https://www.tensorflow.org/tensorboard/graphs which is our newer Colab-based tutorial.
