### ISSUE TITLE
tutorial link in the README usage section is dead.

### ISSUE THREAD

**Issue by sebherbert** [tensorflow/tensorboard#4713]
## Issue description

Hi, 

A very small thing, I just wanted to point out that the tutorial link changed from [old link](https://www.tensorflow.org/get_started/summaries_and_tensorboard) to [new link](https://www.tensorflow.org/tutorials) 
and the link in [usage](https://github.com/tensorflow/tensorboard#usage) is now dead :)

Cheers,
Sebastien

**Comment by arghyaganguly** [comment]
Similar broken tutorial link in usage section :- [the TensorBoard tutorial](https://github.com/tensorflow/tensorboard/blob/master/docs/r1/overview.md)

**Comment by wchargin** [comment]
Link is live again, so all those occurrences should be fixed. Thanks again!
