### ISSUE TITLE
Graph dashboard pixelated after zoom

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#4744]
Help! I need more pixels. Does anybody have more pixels?

![Screenshot of the graphs dashboard. The viewport is zoomed in around
one node. The node is heavily pixelated, by about a factor of 10, and
it’s hard to read the writing. Some other parts of the viewport appear
fine: although the node’s rounded rectangle and its label pixelated, the
arrows connecting nodes are crisp, as are their labels.][ss]

This is in 2021-03-05 nightlies, but isn’t super recent. Will try to
bisect and report back.

[ss]: https://user-images.githubusercontent.com/4317806/110192023-9459ee00-7de0-11eb-991d-4146d88d7293.png

**Comment by wchargin** [comment]
Oh, looks like it’s actually a Chrome thing:

  - Chrome 89: broken all the way back to `tb-nightly==2.5.0a20210217`,
    and I don’t think that we’ve just missed it for that long;
  - Firefox 86: works on today’s `tb-nightly` (and in December, too).

**Comment by wchargin** [comment]
Filed <https://bugs.chromium.org/p/chromium/issues/detail?id=1185435>.

**Comment by psybuzz** [comment]
Just tested with tb-nightly==2.5.0a20210309, Chrome 91, MacOS, and things are no longer pixelated.  Closing for now, but for anyone who may continue to see blurriness, especially on other platforms, please add a comment.

For TensorBoard.dev users, we expect this fix to land in roughly 1 week.
