### ISSUE TITLE
Projector does not show bounding box of selection when night mode is enabled

### ISSUE THREAD

**Issue by bisejdiu** [tensorflow/tensorboard#4747]
When selecting data points using projector in the night mode, the bounding box of the selection is not rendered (or not visible). 

## Reproducing 
Head over to https://projector.tensorflow.org/. Enable night mode and make a selection.

**Comment by bileschi** [comment]
Thanks for filing, @bisejdiu 
I don't a the bounding box when dragging in night *or* day mode.

```
Google Chrome | 89.0.4389.82 (Official Build) (x86_64)
OS | macOS Version 11.2.1 (Build 20D74)
```

**Comment by bisejdiu** [comment]
Interesting. In my local folder that I cloned a few weeks ago, only the selection in the night mode is bugged.

**Comment by arghyaganguly** [comment]
Bug exists both in night and day mode.Browser tested on :- Chrome.

**Comment by arghyaganguly** [comment]
@bisejdiu , i have tried again in both night and day mode.Seems the bounding box is visible now.
Please confirm so that this can be closed.
Thanks.

**Comment by arghyaganguly** [comment]
Closing this based on above comment trace.Please feel free to reopen.Thanks.
