### ISSUE TITLE
Bug: Image Summaries not displayed (E0905 Error on request)

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorboard#477]
I'm using Tensorflow 1.3, and have image summaries in my code that I would like to display in TB. However, when I switch to the "image" tab in the browser I see only empty images:

![screenshot_2017-09-05_17-02-46](https://user-images.githubusercontent.com/3627551/30067796-1ce97584-925c-11e7-9cf6-a2e3a4e2cfb2.png)

The following error appears in the shell where TB has been started:

    tensorboard --logdir . --port 6034
    E0905 16:59:54.859616 Thread-16 _internal.py:87] Error on request:
    Traceback (most recent call last):
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/werkzeug/serving.py", line 209, in run_wsgi
        execute(self.server.app)
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/werkzeug/serving.py", line 197, in execute
        application_iter = app(environ, start_response)
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/tensorboard/backend/application.py", line 239, in __call__
        return self.data_applications[clean_path](environ, start_response)
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/werkzeug/wrappers.py", line 301, in application
        return f(*args[:-2] + (request,))(*args[-2:])
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py", line 105, in _serve_image_metadata
        images = self._multiplexer.Tensors(run, tag)
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 358, in Tensors
        accumulator = self.GetAccumulator(run)
      File "/system/apps/biosoft/python-361/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 434, in GetAccumulator
        return self._accumulators[run]
    KeyError: '170905_1632_gdcgan_ddcgan-big_z32_l1e-05_l2p0e 00_d3_eps1.00_lds1e 00_smry'
    [... snip, the error repeats a lot of times ... ]

As the `KeyError` also indicates, I think this is due to the name of the directory containing the logfile information ("170905_1632_gdcgan_ddcgan-big_z32_l1e-05_l2p0e 00_d3_eps1.00_lds1e 00_smry", because if I start TB inside of this directory, then the images are displayed without problems).

**Comment by chihuahua** [comment]
To be clear, is `170905_1632_gdcgan_ddcgan-big_z32_l1e-05_l2p0e 00_d3_eps1.00_lds1e 00_smry` a single directory (with that name) on your machine? Or 3 separate directories? Thank you for reporting.

**Comment by untom** [comment]
It's one single directory name. There are originally no spaces in that name at all, the + signs seem to have gotten lost in the copy'n'paste, but you can still see them in the screenshot.

**Comment by untom** [comment]
(or maybe the bug itself is that the '+' sign gets lost somewhere within TB?)

**Comment by chihuahua** [comment]
I can repro. The run seen by TensorBoard is indeed `170905_1632_gdcgan_ddcgan-big_z32_l1e-05_l2p0e+00_d3_eps1.00_lds1e+00_smry` (with the plus sign). 

It seems like werkzeug is losing + characters and replacing them with spaces while decoding the GET param. Let me think about what we can do ...

**Comment by chihuahua** [comment]
For now, indeed not using + in directory names will let you circumvent this issue. On our side, we should still fix this issue though because it is unexpected to users.

**Comment by wchargin** [comment]
> let me think about what we should do

The frontend should use `window.encodeURIComponent` on portions of a string that may contain arbitrary text:

```js
encodeURIComponent("a+b")  // "a%2Bb"
```

**Comment by chihuahua** [comment]
Ah, it's a good thing you chimed in. I was thinking over why `encodeURI('a+b')` outputted `a+b` with no replacement, but it seems like `encodeURIComponent` is the way to go.
