### ISSUE TITLE
Hosting tensorboard.dev in GCP

### ISSUE THREAD

**Issue by jackkwok** [tensorflow/tensorboard#4789]
I would like to host something like tensorboard.dev on Google Cloud Platform.  Can the code for tensorboard.dev be made open source?

**Comment by karthikv2k** [comment]
Hi Jack, can we discuss offline about your requirements? we might be able to help you. can you share your contact info with me via https://www.linkedin.com/in/karthikmramasamy/ or https://twitter.com/_cartick (DMs open).
