### ISSUE TITLE
Add ip address to RequestContext 

### ISSUE THREAD

**Issue by karthikv2k** [tensorflow/tensorboard#4820]
Currently RequestContext holds AuthContext that can help data provider get the auth information from the end user. Similarly we need ability to pass IP address of the end user to the data provider that further forward that information to down stream services for security, quota, and fraud checks.

**Comment by wchargin** [comment]
I’m probably okay with this if it’s understood that the IP address is
optional. You may want to consider `X-Forwarded-For` as well.
