### ISSUE TITLE
Images per page command line option

### ISSUE THREAD

**Issue by YusukeSuzuki** [tensorflow/tensorboard#483]
I want to see over 12 images on single view.
So I want --images-per-page=num_images command line option.

**Comment by wchargin** [comment]
This is a reasonable request. The configuration would not be at the command line, but in the frontend. The `tf-pagination-view` component will correctly handle a number of pages that changes dynamically. This would apply to all plugins, not just images.

The question is where in the frontend it should go. Should each plugin expose such an option (hmm…), or should we expose such an option in our "settings" dialog? I lean toward the latter but am open to either of these or new ideas.

cc @chihuahua

**Comment by chihuahua** [comment]
Yeah - maybe we try exposing in Settings? `tf-pagination-view` is used in various places, so 1 central place to set the `cards_per_page` setting seems convenient. I guess a downside might be that some users want different `cards_per_page` values per dashboard, but my hunch at the outset is that 1 `cards_per_page` for all of TensorBoard probably suffices. And then, plugin authors who use `tf-pagination-view` won't have to create a custom widget to alter `cards_per_page`.

**Comment by wchargin** [comment]
I agree with your hunch; we can see where it goes. :-)

**Comment by namhoonlee** [comment]
I wonder if there is a way to display all images in one page rather than only 12 as default (or at least an option). It used to do that in the previous tensorboard. Often times I visualize a sequence of images, which is easily more than 12, and turning pages to see adjacent frames is quite disconnecting..

**Comment by chihuahua** [comment]
Hmm, I see. The user could set `cards_per_page` to some large value, right?
