### ISSUE TITLE
Allow overwriting for same global steps

### ISSUE THREAD

**Issue by timothylimyl** [tensorflow/tensorboard#4840]
Reference to the question: https://stackoverflow.com/questions/66961268/how-to-overwrite-checkpoint-of-same-global-step-for-tensorboard

The current workflow of Tensorboard does not allow you to overwrite plots/images/figures on the same global step. For Deep Learning practitioners, we usually will revert to old epochs to run different hyperparemeters and experiment on it to see whether are there further improvements. 

It will be even better if Tensorboard can figure out how to separate the old plots and new plots, at least make the plots to a different color and do not merge the plots together!

**Comment by ericdnielsen** [comment]
In your workflow are you able to assign a new run name, when you revert to a previous epoch and change the hyper parameters?  In that case you'd have the two versions and be able to compare them, while still being able to tell them apart?

**Comment by timothylimyl** [comment]
Hi @ericdnielsen,

In my current workflow, it is not possible to change the run directory as the experiment name for the Tensorboard (`SummaryWriter`) and the saved weights are the same. This is so that I am clear on which experiment showing in Tensorboard is using which particular saved weights. In my terminal (argument parser), I will just have to call `.....--experiment_name resnet-34-trial1....` and it will automatically create both checkpoints folder with the saved weights and the Tensorboard logging directory under the same name. I can easily then resume (`--resume`) from any epochs that I want and plot it on Tensorboard. The problem arises here when I want go back a few steps (`global_steps`) and resume the plot with some new hyperparameters.

It will be way more convenient if Tensorboard has a feature where it overwrites/continues when the same global step is detected. Maybe something along the lines of `add_figure(.......,global_step=5, overwrite=True)` where overwrite sets True to overwrite the data logged for that particular global step.

**Comment by timothylimyl** [comment]
it is okay.
