### ISSUE TITLE
Analyze Log File Generated by TensorBoard at the Runtime while Executing an TensorFlow Application

### ISSUE THREAD

**Issue by Jiawen1991** [tensorflow/tensorboard#485]
Hi,
I am trying to modify the TensorFlow for the following purpose: 
1. I got a log file by using TensorBoard, but I didn't know how to analyze it. I found out that the https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/summary may be helpful for the log file analysis. How can I analyze this log file generated by TensorBoard (instead of using TensorBoard visualization)?
2. Output the dependency operations/relative variables of a graph of an application written by TensorFlow. I tried to analyze the log file generated by TensorBoard at the runtime to identify the dependency in a graph, and then use these dependencies to do more. Does anyone have any ideas how to implement that?

**Comment by wchargin** [comment]
The `tensorflow.summary` module probably won't be what you're looking for: those ops are for writing summaries, but you already have an event file. There is a `summary_iterator` function in `summary_iterator.py`, but this provides a pretty low-level API.

It sounds like you primarily want to analyze the graph. TensorBoard is well equipped to do this. Use the `tensorboard.backend.event_processing.event_multiplexer` module. Here is an example:

```py
from tensorboard.backend.event_processing import event_multiplexer

LOGDIR = '/home/wchargin/data/scalars_demo/'
RUN_NAME = 'temperature:t0=270,tA=270,kH=0.001'

def main():
  multiplexer = event_multiplexer.EventMultiplexer()
  multiplexer.AddRunsFromDirectory(LOGDIR)
  multiplexer.Reload()

  graph = multiplexer.Graph(RUN_NAME)
  print(len(graph.node))
  print(graph.node[0])

if __name__ == '__main__':
  main()
```

Does this help? Are you looking for something else?

**Comment by Jiawen1991** [comment]
I can use event_multiplexer to analyze the log(events) file now. Thank you, William!

**Comment by wchargin** [comment]
Cool, glad to hear it. Let us know if there's anything else we can do.
