### ISSUE TITLE
Embedding Projector sprite images appear transparent / use "multiply" blendmode

### ISSUE THREAD

**Issue by tyhenry** [tensorflow/tensorboard#4911]
Tensorboard currently uses "multiply" blend-mode to render sprite images in the Embedding Projector.  This causes the images to be weirdly transparent, muddy and hard to read:

![image](https://user-images.githubusercontent.com/8344718/116168268-05769d00-a6d0-11eb-85ae-71a139ec77a8.png)

The cause seems to be
`blending: THREE.MultiplyBlending` on line 227 in /plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts:

https://github.com/tensorflow/tensorboard/blob/ea145a40a0c50092fecdf83d7c934260a3e15c0b/tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts#L227

Changing that line to 
```
blending: THREE.NormalBlending,
``` 
fixes the issue for me, rendering the sprites with normal opacity:

![image](https://user-images.githubusercontent.com/8344718/116168815-4a4f0380-a6d1-11eb-8f9a-d20b4dbb1d55.png)

Could this be updated?  Can submit a PR if needed.

**Comment by wchargin** [comment]
Hi @tyhenry—thanks for the detailed report! That does seem strange to
me, and I’d be inclined to agree with the change that you suggest.
This blend mode change dates back to 2016; I’ve pinged the author
internally to see if there’s any more information that we should have
(Googlers, ref. <http://cl/126913512>).

I’d suggest opening a PR, as you propose; I’ll let you know if we hear
back from the original author, or just approve+merge after a day or so
if we don’t.

**Comment by wchargin** [comment]
edit: Original author says okay to use normal blending.
