### ISSUE TITLE
using profiling option for custom training loop

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorboard#4945]
I am starting to use tensorboard to track down performance bottleneck. I copied/pasted a simple custom training loop from TF website. Below is my notebook:
https://github.com/llodds/HPC_demos/blob/master/test_tensorboard_for_custom_training/test-tensorboard.ipynb

However, when I tried to do this on my terminal
> tensorboard --logdir=./logdir --port=6006
and then go to http://localhost:6006

I got the following error on the tensorboard page
"No dashboards are active for the current data set."

Anyone has any idea on what's wrong here? 

Thanks

**Comment by arghyaganguly** [comment]
@llodds , please check once with :- 
1) cd {path_to_logdir}
2)check whether logs are available
3)tensorboard --logdir ./ --port=6006
or 
tensorboard --logdir=./ --port=6006

**Comment by llodds** [comment]
@arghyaganguly 

Could you try to test it on google colab? The profiler seems doesn't collect anything. 

files in logdir/

```bash
events.out.tfevents.1620394301.e542dfde1d00.58.100.v2      plugins/
events.out.tfevents.1620394306.e542dfde1d00.profile-empty
```


%tensorboard --inspect --logdir=./

```bash
The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
ERROR: Failed to launch TensorBoard (exited with 0).
Contents of stderr:
2021-05-07 13:33:05.695782: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Contents of stdout:
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
./

These tags are in ./:
audio -
histograms -
images -
scalars -
tensor -
======================================================================

Event statistics for ./:
audio -
graph -
histograms -
images -
scalars -
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```
I believe I probably didn't add the right profiler function or missing function. It should be an easy fix.

**Comment by arghyaganguly** [comment]
@llodds, I was able to reproduce this in colab.Please find the colab [link](https://colab.research.google.com/drive/1IQahkBmJ7y7srA0zGgcAL9NwwVXcarUf#scrollTo=l0wlJgioKDHN)

**Comment by llodds** [comment]
Any update on this?

**Comment by llodds** [comment]
Hi, anyone looking into this? I don't think this is a bug in TF board code. It should be a simple configuration issue in my code.

**Comment by yisitu** [comment]
Hi,
I was able to get a profile successfully.  

> @llodds, I was able to reproduce this in colab.Please find the colab [gist.](https://colab.research.google.com/gist/arghyaganguly/83a1bad18314d496b3a7b3387c7baae7/4945.ipynb)

The tensorboard was pointed to the wrong logdir:
```diff
-%tensorboard --logdir logs
+%tensorboard --logdir logdir
```

After that I could get a profile. PTAL:
https://colab.research.google.com/gist/arghyaganguly/83a1bad18314d496b3a7b3387c7baae7/4945.ipynb

**Comment by llodds** [comment]
@yisitu Thanks! I got it now.
