### ISSUE TITLE
PR curve sliders can get out of sync with actual data

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#496]
Steps to reproduce:
 0. Disable auto-reload; it might interrupt testing.
 1. Open the PR curve dashboard.
 2. Set the run filter query to `pr_curve`. Set the first slider to `1`
    and the second slider to `9`.
 3. _Paste_ into the run filter: `mask_every_other_prediction`.

Expected behavior: The lone slider reads “step: 9” and is at the right.
Actual behavior: The slider reads “step: 9” and is at the left.

Problem: The change event for the tag does not trigger `_updateSliders`.

**Comment by wchargin** [comment]
( @chihuahua want to make a label `plugin:pr-curves`?)

**Comment by chihuahua** [comment]
I will get to this. I lack permissions to make labels. @jart, want to hook us up?
