### ISSUE TITLE
Profile plugin does not work with subdirectories

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#500]
Steps to reproduce:
 1. `bazel run tensorboard/plugins/profile:profile_demo`
 2. `mkdir /tmp/sub; mv /tmp/profile_demo/ /tmp/sub/profile_demo`
 3. Run tensorboard with `--logdir /tmp/sub/profile_demo`.
 4. Run tensorboard with `--logdir /tmp/sub`.

Expected behavior: (3) and (4) have similar effects; each shows profile data, one for run `foo` and one for run `profile_demo/foo`.

Actual behavior: the profile plugin does not work with (4); it says "No profile data was found. The dashboard is internal only; coming soon!"

All TensorBoard plugins should support recurring to arbitrary subdirectories, so that runs can be organized.

**Comment by wchargin** [comment]
@ioeric can you reproduce this?

**Comment by wchargin** [comment]
@chihuahua mind adding a `plugin:profile` label, too? thanks!

**Comment by Baschdl** [comment]
I have the same issue with the projector.
1. `python3 train.py` which writes only variables into `~/tensorboard/subdir/`
2.1. Run tensorboard with `--logdir ~/tensorboard/subdir/` works.
2.2. Run tensorboard with `--logdir ~/tensorboard/` doesn't work.
