### ISSUE TITLE
Can I link through a transit machine to connect tensorboard

### ISSUE THREAD

**Issue by yeshenyong** [tensorflow/tensorboard#5027]
First of all, I have three machines, because the security permissions of the machine running tensorboard are not accessible, but I can set up a VIP machine (shell) to access the machine of tensorboard. Can I access this VIP machine to obtain the data of tensorboard

**Comment by arghyaganguly** [comment]
Closing this there was no update.Please feel free to reopen with insights/information based on above comment.Thanks.
