### ISSUE TITLE
TensorBoard predictions do not match the local 

### ISSUE THREAD

**Issue by Kebudi** [tensorflow/tensorboard#5033]
I have trained a model in the server using a GPU. The results on tensorboard are amazing, and very accurate. I have the ground truth next to the predictions and the bounding boxes are very accurate.

However when I download the model locally and ran it to make an inference on the same TEST data set as TensorBoard uses, the predictions are completely wrong.

What could be causing this difference in model performances? Who’s is TensorBoard making its predictions? I am using the same model and same data. Anything helps! Thank you!

**Comment by arghyaganguly** [comment]
@Kebudi ,   thanks for reporting this issue.
1)What are the versions in use for TensorFlow and Tensorboard?
2)Please provide some more information about the model e.g(an associated code snippet,colab link, gist) to reproduce the issue or other details or screenshots to help us understand this more clearly.

**Comment by bileschi** [comment]
@Kebudi are you still having this issue?  If so, can you please share enough information that we could reproduce it on our end?  Please feel free to re-open the issue.  Thanks!
