### ISSUE TITLE
[Docs] Wrong clip_by_value in debugger_v2 doc

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/tensorboard#5057]
Existing URLs containing the issue:

|https://www.tensorflow.org/tensorboard/debugger_v2

Description of issue (what needs changing):
`tf.clip_by_value` should by applied on probs other than `tf.math.log(probs)`

Existing:
```
diff = -(labels *
           tf.clip_by_value(tf.math.log(probs), 1e-6, 1.))
```
```
diff = -(labels *
           tf.math.log(tf.clip_by_value(probs), 1e-6, 1.))
```           
           
--------------
From: b/190620772

**Comment by ericdnielsen** [comment]
Thank you MarkDaoust  for the report, and thank you arghyaganguly for the PR.
