### ISSUE TITLE
Which Python versions are currently supported?

### ISSUE THREAD

**Issue by busunkim96** [tensorflow/tensorboard#5069]
Hi,

I'm one of the maintainers for [google-auth](https://pypi.org/project/google-auth/). We're planning on officially removing 2.7 support soon (requiring python >= 3.6). In preparation for that, I looked for packages that declare direct dependencies on `google-auth` and have 2.7 in the trove classifiers.

I noticed that the `setup.py` lists 2.7, 3.4, 3.5, and 3.6 and the `python_requires` is more permissive:

https://github.com/tensorflow/tensorboard/blob/13c6ecf76443e3bae084a4d6e3de8254b0e39ab3/tensorboard/pip_package/setup.py#L76-L81

https://github.com/tensorflow/tensorboard/blob/13c6ecf76443e3bae084a4d6e3de8254b0e39ab3/tensorboard/pip_package/setup.py#L65-L66

The pyproject.toml has 3.6, 3.7, and 3.8.

https://github.com/tensorflow/tensorboard/blob/13c6ecf76443e3bae084a4d6e3de8254b0e39ab3/pyproject.toml#L1-L3

Could someone clarify which Python versions are currently supported? If 2.7 is currently supported, what is the timeline for removing support?

Thanks!

**Comment by stephanwlee** [comment]
Thanks for raising that. TensorBoard has dropped support for Python 2.7 and 3.5. It was our oversight in not updating setup.py which we can update very soon.

Related changes: #3094, 7ed23cda232874f2acd3baba45f5f2bf31fff903.

**Comment by busunkim96** [comment]
That's great to hear, thank you for the quick response!
