### ISSUE TITLE
can I use an already save tensorboard file with tensorboard.dev?

### ISSUE THREAD

**Issue by seyeeet** [tensorflow/tensorboard#5107]
I already have a couple of tb files, is there a way to display them publicly via tensorboard-dev?

**Comment by arghyaganguly** [comment]
@seyeeet , i believe if you have the log data from previous runs, you can upload it as shown in [link.](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tbdev_getting_started.ipynb.)
Do your tb files constitute the log data from previous runs?

**Comment by bileschi** [comment]
@arghyaganguly is correct.  You can upload them to tensorboard.dev with the following command:

```
$ tensorboard dev upload --logdir logs \
    --name "(optional) My latest experiment" \
    --description "(optional) Simple comparison of several hyperparameters"
```

**Comment by bileschi** [comment]
I hope this answers your question.  I'm going to close the issue, but please feel free to re-open if there is a problem with TensorBoard or the documentation.  Thanks!

**Comment by seyeeet** [comment]
@bileschi Thanks for your help, it kinda did, I got the error of `localhost' scheme not supported in proxy URI`, not sure what that means.
is there any tutorial for that?

**Comment by bileschi** [comment]
Are you using some sort of web proxy?

**Comment by seyeeet** [comment]
yes, im using a cluster and proxy is needed usually

**Comment by bileschi** [comment]
Ok, I don't know much about how to configure proxies, but my superficial internet search suggests you will probably need to configure your web proxy to handle requests against localhost.  I'm not sure there is anything we can do to fix this in TensorBoard itself?

**Comment by seyeeet** [comment]
I am not sure either, I guess it is complicated. I will post it here if I figure that out
