### ISSUE TITLE
how to use launch tensorboard in tensorflow1.3  platform on windows7

### ISSUE THREAD

**Issue by ranjiewwen** [tensorflow/tensorboard#512]
i'm meet this problem ; the  offical method:

> To run TensorBoard, use the following command (alternatively python -m tensorflow.tensorboard)
- tensorboard --logdir=path/to/log-directory 

when use tensorflow1.1 ,i can run normal;but i use tensorflow1.3 it failed;  i fond that tensorboard is not a package in thensorflow ,can't use tensorflow.tensorboard ; so anyone can help solve this problem?

**Comment by ranjiewwen** [comment]
solve this problem :+1: 
- use :tensorboard.main --logdir=log
![qq 20170911211729](https://user-images.githubusercontent.com/9885492/30276298-f129146a-9736-11e7-9368-f86e6cd20dd9.png)

**Comment by chihuahua** [comment]
SG! I think you ran into https://github.com/tensorflow/tensorboard/issues/392
