### ISSUE TITLE
missing a chunk of data in the plot

### ISSUE THREAD

**Issue by jingxixu** [tensorflow/tensorboard#5133]
I am missing a bit chunk of logged data and I am wondering if this is a bug? You can see from the image below that several millions of data in between is gone. Initially, the plot looks all right but as it gets trained for longer (data gets larger) then this happens.

![Screenshot from 2021-07-15 15-12-55](https://user-images.githubusercontent.com/15113241/125844709-db425aa9-1b3f-43ff-8561-e723a604e2a8.png)

**Comment by yatbear** [comment]
Hi jingxixu,

Can you please provide the log data (or at least some samples) for us to troubleshoot? Thank you!

**Comment by arghyaganguly** [comment]
@jingxixu , any update on the log data?

**Comment by arghyaganguly** [comment]
@jingxixu ,closing this as there has been no update for some time now.Please feel free to reopen with the log data information.Thanks.
