### ISSUE TITLE
Add a custom summary op for PR curves that takes raw precision, recall, TP, FP, TN, FN.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#515]
An internal team has a custom way of computing PR curves. For their use case, true positives are rare, so  the current PR curves plots produced by TensorBoard are noisy for them.

To solve this problem, they made a streaming metric that accumulates weighted (TP, FP, TN, FN) counts across a certain window of recent steps, which has a smoothing effect and makes the PR curves jump less from step to step.

To accommodate that, I am thinking about adding a raw_precision_recall_op method to the summary.py file for PR curves. I started this issue to get everyone's input on that.

@wchargin @jart @dandelionmane

**Comment by wchargin** [comment]
Sounds good to me.

You might consider whether the existing `op` function should end by calling out to your `raw_metrics_op` (i.e., compose around it).
