### ISSUE TITLE
Multiple errors occur when building tensorboard from source.

### ISSUE THREAD

**Issue by rgkannan676** [tensorflow/tensorboard#5157]
Hi All,

I am trying to build tensorboard from source(https://github.com/tensorflow/tensorboard.git) with steps as mentioned in https://github.com/tensorflow/tensorboard using bazel(bazel 3.7.2) in Windows 10. But I am facing multiple issues. 

->bazel build tensorboard:tensorboard
```
INFO: From Compiling com_google_protobuf/python/google/protobuf/pyext/unknown_fields.cc:
external/com_google_protobuf/src\google/protobuf/message.h(127): warning C4005: 'GOOGLE_PROTOBUF_HAS_ONEOF': macro redefinition
external/com_google_protobuf/python/google/protobuf/pyext/unknown_fields.cc: note: see previous definition of 'GOOGLE_PROTOBUF_HAS_ONEOF'
INFO: From Linking external/com_google_protobuf/python/google/protobuf/pyext/_message.so:
   Creating library bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_protobuf/python/google/protobuf/pyext/python/google/protobuf/pyext/_message.so.if.lib and object bazel-out/x64_windows-opt-exec-50AE0418/bin/external/com_google_protobuf/python/google/protobuf/pyext/python/google/protobuf/pyext/_message.so.if.exp
ERROR: D:/tensorboard/tensorboard/webapp/BUILD:202:8: Executing genrule //tensorboard/webapp:gen_index_polymer3.html failed (Exit 1): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
stat: cannot stat 'C:\Users\User\_bazel_user\6thpos4r\execroot\org_tensorflow_tensorboard\bazel-out\host\bin\tensorboard\logo\inline_favicon.runfiles/org_tensorflow_tensorboard/tensorboard/logo/favicon.png': No such file or directory
Target //tensorboard:tensorboard failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 430.972s, Critical Path: 115.08s
INFO: 2071 processes: 1044 internal, 497 local, 530 worker.
FAILED: Build did NOT complete successfully
```
"/logo/favicon.png': No such file or directory". To fix this issue, I removed the following entry causing the issue from tensorboard/tensorboard/webapp/BUILD file
```
genrule(
    name = "gen_index_polymer3.html",
    srcs = ["index_polymer3.uninlined.html"],
    outs = ["index_polymer3.inlined.html"],
    cmd = "$(execpath //tensorboard/logo:inline_favicon) $< >$@",
    tools = ["//tensorboard/logo:inline_favicon"],
)

```
After cleaning(>bazel clean --expunge) I ran the build again. This time new issue occurred. 

```
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tensorboard:tensorboard (676 packages loaded, 33435 targets configured).
INFO: Found 1 target...
ERROR: D:/tensorboard/tensorboard/webapp/BUILD:204:15: //tensorboard/webapp:tensorboard-webapp: missing input file '//tensorboard/webapp:index_polymer3.inlined.html'
Target //tensorboard:tensorboard failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: D:/tensorboard/tensorboard/webapp/BUILD:220:16 1 input file(s) do not exist
INFO: Elapsed time: 158.753s, Critical Path: 9.58s
INFO: 383 processes: 308 internal, 9 local, 66 worker.
FAILED: Build did NOT complete successfully
```
Error suggests another missing file.
I tried using old versions of source code, but faced multiple issues including Circular dependencies. Please advise how to resolve the issues.

**Comment by japie1235813** [comment]
The second missing is because you remove the `genrule`  `gen_index_polymer3.html` which generates the file `index_polymer3.inlined.html` as the source. Why you do not have that genrule executed correctly is what you want to look into.

1. Could you verify in your sourcecode, whether `tensorboard/logo` folder exists and what is the folder structure? (Is `favicon.png` there?)
(https://github.com/tensorflow/tensorboard/tree/master/tensorboard/logo)

2. Could you try run that `genrule`
`bazel build tensorboard/webapp:gen_index_polymer3.html`
and check if any error and if you have `index_polymer3.uninlined.html` generated?

**Comment by japie1235813** [comment]
To add to the above comment, building TensorBoard from sources in windows is not well supported. TensorBoard pip package    is supported in Windows at our "best effort". Not all features work on Windows (e.g. rustboard) and we try to fix any raised issues case by case when something is broken and reported.

Close this issue. Feel free to reopen if you have more questions.

**Comment by rgkannan676** [comment]
Hi,
Thank you for the response. 

1)```favicon.png``` is present in the folder ```tensorboard\tensorboard\logo```

2)I tried to run the ```genrule``` as suggested. But got error the following error. 

```
D:\tensorboard>bazel build tensorboard/webapp:gen_index_polymer3.html
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tensorboard/webapp:gen_index_polymer3.html (11 packages loaded, 32 targets configured).
INFO: Found 1 target...
ERROR: D:/tensorboard/tensorboard/webapp/BUILD:202:8: Executing genrule //tensorboard/webapp:gen_index_polymer3.html failed (Exit 1): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
stat: cannot stat 'C:\Users\User\_bazel_user\6thpos4r\execroot\org_tensorflow_tensorboard\bazel-out\host\bin\tensorboard\logo\inline_favicon.runfilesorg_tensorflow_tensorboard/tensorboard/logo/favicon.png': No such file or directory
Target //tensorboard/webapp:gen_index_polymer3.html failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.379s, Critical Path: 0.42s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

- I have one more doubt. I am trying to make some changes and deploy the ```tensorboard embedding projector```. Can you please suggest if I can build and use only that functionality. I tried to run ```bazel run tensorboard/plugins/projector/vz_projector:standalone``` as suggested in https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/projector. But got the following error. 
```
D:\tensorboard>bazel run tensorboard/plugins/projector/vz_projector:standalone
ERROR: Cannot run target //tensorboard/plugins/projector/vz_projector:standalone: Not executable
INFO: Elapsed time: 0.161s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```
Please advise.

**Comment by rgkannan676** [comment]
I tried building in Ubuntu(Ubuntu 18.04.5) using Windows Subsystem For Linux([WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)) . But received a similar error

```
ERROR: /mnt/d/tensorboard/tensorboard/webapp/BUILD:202:8: Executing genrule //tensorboard/webapp:gen_index_polymer3.html failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
stat: cannot stat 'bazel-out/host/bin/tensorboard/logo/inline_favicon.runfilesorg_tensorflow_tensorboard/tensorboard/logo/favicon.png': No such file or directory
Target //tensorboard:tensorboard failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 55.215s, Critical Path: 12.05s
INFO: 618 processes: 200 internal, 400 linux-sandbox, 18 worker.
```

**Comment by rgkannan676** [comment]
Hi @japie1235813 @arghyaganguly . Can you please reopen the issue. Thanks

**Comment by japie1235813** [comment]
We can re-open the issue, but can't provide much further assistance here since the windows build for TensorBoard has never been officially supported (including WSL).
If you identify patches that would get things working, we're happy to review them.

Also, while I'm glad you're excited about the projector visualization, we also don't explicitly support the standalone mode - you're welcome to try to get it working but I would not suggest relying on it long term.


As for the error message you provided, there is a missing slash, it might be something to do with how Windows (or WSL) compose the filepath. 
(It shows `...logo/inline_favicon.runfilesorg_tensorflow_tensorboard/tensorboard/logo/favicon.png` but we expect something
`...logo/inline_favicon.runfiles/org_tensorflow_tensorboard/tensorboard/logo/favicon.png`
Again we will not look into the details.

**Comment by rgkannan676** [comment]
Hi @japie1235813 ,

Thank you for looking into the issue. I was able to build successfully in Ubuntu 20.04.2.0.

Projector visualization is a very cool feature. I have an ER, will it be possible to allow the user to see their 3-Dimensional data without applying any dimensionality reduction techniques. This will allow the user to experiment with other techniques than the offered ones. 

I will close the issue. Thank you for the support.

**Comment by nfelt** [comment]
> Projector visualization is a very cool feature. I have an ER, will it be possible to allow the user to see their 3-Dimensional data without applying any dimensionality reduction techniques. This will allow the user to experiment with other techniques than the offered ones.

Yes, we have a longstanding feature request for this: https://github.com/tensorflow/tensorboard/issues/1192 (and also somewhat https://github.com/tensorflow/tensorboard/issues/1204)

I agree it would be useful, but we haven't had bandwidth to look into this area.
