### ISSUE TITLE
Support fsspec for reading remote directories

### ISSUE THREAD

**Issue by f4hy** [tensorflow/tensorboard#5165]
A common gotcha on my team is using `hdfs` or other remote storage systems as the location to store the tensorboard logs. If `tensorflow>2.0` is installed this works just fine, but if tf is not installed at all then writing the output works only for local or s3 locations.

When using tensorboard to write logs installing tensorflow just to get remote directory access is a pretty heavy dependency to add.  Would the team be open to replacing the remote file access with something like `fsspec` (what pandas uses for remote file support) instead of gfile? If so I would be happy to take on the project.

**Comment by stephanwlee** [comment]
Hi @f4hy, sorry for a late reply. 

I would like to understand your set up a little bit more. TensorBoard today does not let you write any summaries without TensorFlow. Are you asking for a possibility where you can emit logs without dependency on TensorFlow? If so, have you ever looked into [tensorboardX](https://github.com/lanpa/tensorboardX) (not our project)? tensorboardX does not support hdfs but if that's what you are using today, I would ask you to file an issue against them instead.

Above, you were explicitly asking about the writer parts of TensorBoard but are you at all hindered by the read path? Without TensorFlow installed, both rustboard and our TF shims do not support hdfs.
- https://github.com/tensorflow/tensorboard/blob/b6e8baf0e334e9e16c7157503a704cca511029b2/tensorboard/data/server/cli/dynamic_logdir.rs#L29-L32
- https://github.com/tensorflow/tensorboard/blob/b6e8baf0e334e9e16c7157503a704cca511029b2/tensorboard/compat/tensorflow_stub/io/gfile.py#L404-L406

**Comment by f4hy** [comment]
I am writing to tensorboard through pytorch, https://pytorch.org/docs/stable/tensorboard.html 
This works perfectly fine to write summaries without tensorflow installed. However without tensorflow it goes thorugh https://github.com/tensorflow/tensorboard/blob/9bb887b334902e6b638ea3620d8203e05b700b78/tensorboard/compat/tensorflow_stub/io/gfile.py#L15 to emulate the tensorflow filesystem api.  This works just fine for the [LocalFilesystem ](https://github.com/tensorflow/tensorboard/blob/9bb887b334902e6b638ea3620d8203e05b700b78/tensorboard/compat/tensorflow_stub/io/gfile.py#L81) and [S3Filesystem](https://github.com/tensorflow/tensorboard/blob/9bb887b334902e6b638ea3620d8203e05b700b78/tensorboard/compat/tensorflow_stub/io/gfile.py#L204) defined in that file. 

My proposal would be to remove these implementations of LocalFilesystem and S3filesystem in the compat/tensorflow_stub/io/gfile.py and instead use the package `fsspec` to implement a generic filesystem API which would support local/s3/gcs/hdfs/etc. If tensorflow was installed, it continue to use the tensorflow api, but when using the compat.tensorflow_stub implemented in tensorboard we can support more filesystems.

**Comment by d4l3k** [comment]
It would be really nice to have tensorboard compat fallback to using fsspec. There's a lot more file systems available through fsspec and is used by a number of major projects such as pytorch lightning https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/cloud_io.py#L41

Here's where pytorch currently integrates in with tensorboard https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/writer.py#L9

@stephanwlee if there's interested in adding support I'd be happy to send a PR

It shouldn't be too hard to add optional fsspec support that only runs if you have the dependency installed

**Comment by d4l3k** [comment]
I'm going to write up a initial stab at providing a gfile interface for fsspec. I'm not 100% sure about file watching interfaces or how this might work with rustboard but the core functionality should be feasible

**Comment by nfelt** [comment]
Fixed by #5248.

There are some lingering issues here still (e.g. it's not possible for users who already do have TensorFlow installed to fall back to fsspec, which has a wider array of filesystems available). But those are wrapped up in larger refactoring concerns which are addressed at length in https://github.com/tensorflow/tensorboard/issues/5286.
