### ISSUE TITLE
Content Security Policy error when giving external URL's as image source.

### ISSUE THREAD

**Issue by rgkannan676** [tensorflow/tensorboard#5173]
Hi All,

I have 2 doubts. Please advise.

1) I build the tensorboard from source code and is trying to access image URL's hosted outside the tensorboard hosted server, but this is restricted with an error message

``` Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:8080/crab/n0198127600000002.jpg  ```

I tried with both https and http(locally hosted images) and resulted in the same error.

I was able to access the image hosted by the tensorboard server ( http://localhost:6006/data/plugin/projector/sprite_image?run=.&name=embedding/.ATTRIBUTES/VARIABLE_VALUE )

How can I remove this restriction? 

2) How can I host a local folder in the same server where tensorboard is running? This will help me to avoid the restriction while accessing the images. 

Thanks

**Comment by bmd3k** [comment]
Could you say a little more about your use case? In what circumstances are you trying to access images from a different server/path? It may help us better advise you.

That said, if you're building from source then a quick unsupported hack to get this to work could be to modify one of the CSP-related lists. From what you've described it may be sufficient to add `https://localhost:8080/` to this list:

https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/backend/http_util.py;l=40;drc=3442430b2487adac9b0107662107f0631564f394

As for hosting an additional folder on the server that runs TensorBoard, you may want to wrap the TensorBoard WSGI app in a larger web app and have that larger web app also serve your additional content. There is an example using Flask here:

https://github.com/tensorflow/tensorboard/issues/3709

**Comment by rgkannan676** [comment]
Hi @bmd3k,
Thank you for the response. 
I am trying to replace the images shown in the 'Nearest points in the original space' with the original images to improve the image quality in [tensorboard embedding projector](https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin). Currently, the small images present in the sprite image is displayed. I need to replace it with the  original images present in my local directory. Please advise.

**Comment by rgkannan676** [comment]
I added ``` _CSP_IMG_DOMAINS_WHITELIST = ["http://localhost:8000/"] ``` as suggested and was able to load the image.

I also tried to access the image without hosting the folder, by using file:///  ```_CSP_IMG_DOMAINS_WHITELIST = ["http://localhost:8000/","file:///"] ```, but it gave an error
```Security Error: Content at http://localhost:6006/data/plugin/projector/projector_binary.html may not load or link to file:///home/Desktop/sample.jpg. ```
