### ISSUE TITLE
Can I specify a "Run" by url?

### ISSUE THREAD

**Issue by HisiFish** [tensorflow/tensorboard#518]
I have several tf-event files like this:

        top/alexnet/events.out.tfevents.1501743760.ai
        top/cifarnet/events.out.tfevents.1501745971.ai
        top/lenet/events.out.tfevents.1501795840.ai

Then I use the command "tensorboard --logdir=top --port=6006". 

When I visit "http://host_ip:6006/#graphs", I can get different graphs by select "Run".

But whenever I visit http://host_ip:6006/#graphs, the default graph is alexnet. Can I specify another one by use a specific url?

**Comment by chihuahua** [comment]
Does `http://host_ip:6006/?run=yourDesiredGraph#graphs` work?

You can obtain that URL by selecting a run in the graph dashboard. The URL should automatically change to reflect the run, and revisiting that URL should load the graph for the run.

**Comment by HisiFish** [comment]
@chihuahua Thanks for your reply. I tried `http://host_ip:6006/?run=lenet#graphs` but it does not work. 

And for whatever I chose for "Run", the URL keeps the same ( like `http://host_ip:6006/#graphs` ).

**Comment by chihuahua** [comment]
Oh, you know what? https://github.com/tensorflow/tensorboard/pull/505 is not yet available to users who install via pip. If you start TensorBoard at HEAD (Clone this repo and then [`bazel run` TensorBoard](https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md)), you should be able to link to runs in the graph dashboard.

**Comment by HisiFish** [comment]
Thanks, That's just what I want!

**Comment by andyljones** [comment]
Five years on - d'you expect the `?run=` syntax to still work? Eyeballing [the code that seems to correspond to](https://github.com/tensorflow/tensorboard/blob/c9183bf6b32d646457aa7aa5d4cc08921c6f2a49/tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts#L363) #505 the logic's still there, but it doesn't work on my TensorBoard instance as of today.
