### ISSUE TITLE
How to install under Windows 10 for Tensorflow.JS?

### ISSUE THREAD

**Issue by vitaly-t** [tensorflow/tensorboard#5189]
Spent hours trying to figure out how to install and run tensorboard under the combination of Windows 10 + [Tensorflow.JS](https://github.com/tensorflow/tfjs).

Any tips, please?

I also raised [this question on StackOverflow](https://stackoverflow.com/questions/68655419/tensorboard-for-tensorflow-js-under-windows-10).

---

#### Environment:

* Windows 10 64-bit
* Node.JS v14.17.3
* Python v3.8.9
* Tensorflow v2.5.0
* Tensorflow.JS v3.8.0

**Comment by bmd3k** [comment]
Hi @vitaly-t ,

Do you recall how you installed TensorFlow.js? With some methods of installation you should get TensorBoard installed automatically.

If it's not already installed then you can install TensorBoard using pip:
`pip install tensorboard`
https://pypi.org/project/tensorboard/

And then you point your tensorboard at whichever directory your TensorFlow.js process outputs its event files.
`tensorboard --logdir <your_directory>

If you are experiencing some other error, please provide more detail. 

If `pip install tensorboard` was indeed the missing step for you, please let me know and we will try to improve the documentation (I've noticed today that this option is not very clear).

**Comment by vitaly-t** [comment]
@bmd3k I understand `pip` commands are all for Linux, and I am using Windows. The same goes for most of the Tensorflow.JS instructions. Having to figure out how to get it all done under Windows + Tensorflow.JS, that's the challenge.

I know that many instructions for Windows are based on Anaconda, to create a namespace and run commands from there. However, all I could find were for Python, which I do not use.

**Comment by bmd3k** [comment]
As far as I know, pip is the only installation method TensorBoard supports. I have gotten it to work on Windows using python, venv, and pip.

Will close but if you find any other means of installing or need any other help, please let us know.

**Comment by vitaly-t** [comment]
So you're saying that tensorboard doesn't support Windows + Tensorflow.JS setup, and that's it?

I don't see how this is conclusive to just close the issue.

**Comment by stephanwlee** [comment]
TensorBoard does support Windows. `pip` is not something unique to an OS but is just a Python package manager that default installation _often_ includes. If you have Python on your system, Windows, it is likely that you have `pip` (or `pip3`), and you should be able to use TensorBoard easily using PowerShell or WSL.

Now, I am not even sure if TensorFlow.js supports Summary or emitting event files that TensorBoard requires and consumes.

**Comment by stephanwlee** [comment]
I just spent 5 minutes to install Python on Windows, `pip install tensorboard`, then `tensorboard.exe --logdir ~/data` then got this. 

![image](https://user-images.githubusercontent.com/2547313/128571226-6ac1d17f-fc60-43e5-a0a8-ba656d1455f9.png)

Few things to note are:
- on PowerShell, when I executed `python` without any Python installed, it opened up Microsoft Store and was able to install Python 3.9 quickly and easily just by clicking on "Install"
- Depending on how you installed our Python and `pip`, binaries `pip` installs may appear in an odd place. For me, it appeared under `$HOME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_[somehash]\LocalCache\local-packages\Python39\Scripts` which I did not put on my PATH variable so I had to manually find the binary/executable under that directory.

**Comment by vitaly-t** [comment]
I finally got it working...

* Removed all Python installations that Windows was doing through its Windows Store. Those were installing into weird locations that you wouldn't properly refer from the environment variables.
* Install Python 3.8.x manually (via MSI file). I put it into `C:\Python38`
* Added `C:\Python38\` and `C:\Python38\Scripts` into the path, and set environment variable `PYTHON=C:\Python38`
* Install `pip`, by going into folder `C:\Python38`, and running first `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`, and then `python get-pip.py`.
* Created `logs` sub-folder for my Tensorflow.JS project
* In the code, created Tensoboard callback:
```js
const d = new Date();
const log_dir = `logs/fit/${d.getFullYear()}-${d.getMonth()}-${d.getDay()}_${d.getHours()}-${d.getMinutes()}-${d.getSeconds()}`;
const tensorboard_callback = new TensorBoardCallback(log_dir);
```
* Added the callback into the model training:
```js
model.fit(xs, ys, {callbacks: [tensorboard_callback], epochs: 10}).then(() => {
    model.predict(tf.tensor2d([5], [1, 1])).print();
});
```
* Open git-bash command line inside the project root, and execute `tensorboard --logdir ./logs`, and then navigate to `http://localhost:6006`, where I can see the following after several training sessions:

![image](https://user-images.githubusercontent.com/5108906/128581927-a0df536c-3af5-4487-a503-99de753c0eb9.png)

However, In the console for tensorboard, I am getting `TensorFlow installation not found - running with reduced feature set.` Now trying to figure out why that is...

**Comment by stephanwlee** [comment]
Glad you got it to work.

> However, In the console for tensorboard, I am getting TensorFlow installation not found - running with reduced feature set. Now trying to figure out why that is...

That's just a warning. If you do `pip install tensorflow`, more plugins _may get_ enabled and that's all. Nothing changes functionally.

**Comment by vitaly-t** [comment]
> If you do `pip install tensorflow`, more plugins may get enabled and that's all.

Such command does not work on Windows, it produces:

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by stephanwlee** [comment]
Are you happening to use Python 3.9? If you see https://pypi.org/project/tensorflow/, you will note that it only supplies Python 3.8 which is likely to get fixed very soon (they are preparing a new release).

![image](https://user-images.githubusercontent.com/2547313/128582486-dbc54cb7-ecd3-41d5-bd26-04ccc3111827.png)

**Comment by vitaly-t** [comment]
No, as I stated earlier, I am using Python 3.8.9:

![image](https://user-images.githubusercontent.com/5108906/128582530-d2a5a6bf-fd02-40b6-a471-d555abddf157.png)

**Comment by stephanwlee** [comment]
Ah, since you said you have reinstalled Python, I was not sure whether the version has changed.

Anyways, TensorFlow does supply Windows package so I do not know why pip would fail to find the compatible version. Regardless, it is an optional package from TensorBoard's perspective.

**Comment by vitaly-t** [comment]
When you said...

> more plugins may get enabled and that's all. Nothing changes functionally.

I thought maybe I would get something like automatic broweser refresh during training, like some live feed. For now I have to do F5 after each training finished. I thought the UI would offer live feed of some sort... 

Also, memory + GPU profiling - I do not see any of those...am I missing something else? How am I to analyze the load produced by my training model on my graphics card?

**Comment by stephanwlee** [comment]
Reload on the dashboard might be disabled so please take a look at the settings.

![image](https://user-images.githubusercontent.com/2547313/128582969-5a75a4f5-4f8d-41e2-ba97-4595c56b6f15.png)

For other features, please use the "Inactive" dropdown to find plugins and see their instructions. Most instructions are geared towards TensorFlow users, not TF.js users.
![image](https://user-images.githubusercontent.com/2547313/128583337-3864214e-7df4-40d0-ab49-e5c68667cd9c.png)

For TF.js, I think it is more standard to use their own tooling for performance tracking. https://github.com/tensorflow/tfjs/tree/master/tfjs-vis
