### ISSUE TITLE
TensorBoard doesn't respect drive names on Windows

### ISSUE THREAD

**Issue by dandelionmane** [tensorflow/tensorboard#52]
Migrated from https://github.com/tensorflow/tensorflow/issues/7856

@enpasos 

> OS: Windows 10 (64 bit)
> TensorFlow Version: 1.0.0
> CUDA: 8.0
> GPU: yes
> 
> Problem: 
> **C**:>tensorboard --logdir=**E**:\tmp\tensorflow\mnist\logs
> => tensorboard starts without loading data (not working and difficult to detect reason)
> 
> **E**:>tensorboard --logdir=**E**:\tmp\tensorflow\mnist\logs
> => tensorboard starts with loading data (works perfectly) 

@mrry

> Unfortunately TensorBoard [uses a colon](https://github.com/tensorflow/tensorflow/blob/27a98083a6c16f263d668271889863596efbeb84/tensorflow/tensorboard/backend/application.py#L581) as the separator between the optional "run name" and the path in the `--logdir` flag. That means that `--logdir=E:\tmp\tensorflow\mnist\logs` is interpreted as a run named `E` with path `\tmp\tensorflow\mnist\logs`, which explains why it's sensitive to the current working directory.
> 
> As a quick workaround, you could avoid this problem by always specifying an explicit run name as part of the `--logdir` flag, e.g.:
> 
> ```
> tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs
> ```
> 
> (Reassigning to @dandelionmane, who shows up on the blame for the relevant code.)

**Comment by nfelt** [comment]
Fixed by #266

**Comment by msqrt** [comment]
While a fix for this specific case, this seems to completely break multiple logdirs (as in, tensorboard --logdir=name1:dir1,name2:dir2). Naming even a single logdir (tensorboard --logdir=name:dir) seems to cause tensorboard to interpret it as a drive letter (both for local and global paths) instead of a logdir name.

**Comment by wchargin** [comment]
@msqrt: The magic `name1:path1,name2:path2` syntax is deprecated as of
TensorBoard 2.0; setting `--logdir VAR` will now always select a single
logdir, `VAR`, without special treatment for colons or commas. The old
“magic” behavior is still available as `--logdir_spec`, but often you
can avoid this entirely by pointing TensorBoard at a parent directory.
Please see #2615 for context and details.
