### ISSUE TITLE
"New style" UI missing

### ISSUE THREAD

**Issue by Threynaud** [tensorflow/tensorboard#521]
Hello,

I am using tensorboard 0.1.6 and it appears that I still get the old UI version (cf picture):
![capture d ecran 2017-09-13 a 14 13 34](https://user-images.githubusercontent.com/13488732/30376782-d07d5a7a-988d-11e7-81ca-5728bb3ff4c4.png)

The "inactive" tab is missing and there is not that dashboard with all the scalars...

I have upgraded tensorflow-tensorboard with a `pip install -U`.

All my colleagues seem to have the "new" version without doing something special, even with version 0.1.4. What am I missing?

**Comment by chihuahua** [comment]
Could you please double-check the version with `pip freeze | grep tensorboard`?

**Comment by Threynaud** [comment]
Alright I found the problem. I was launching tensorboard from a virtualenv but for some reason it was using the old version that was installed outside my venvs..
Should have checked that earlier, my bad...

**Comment by chihuahua** [comment]
Cool. Thanks!
