### ISSUE TITLE
How to use DLProf plugin with Tensorboard?

### ISSUE THREAD

**Issue by za13** [tensorflow/tensorboard#5226]
I'm using Ubuntu 18 and Tensorflow 2.5.0

I want to be able to see a visualization of the GPU utilization, Tensor Core Kernel efficiency, etc. For example, to see Figures 5-11 like in https://developer.nvidia.com/blog/profiling-and-optimizing-deep-neural-networks-with-dlprof-and-pyprof/, and slides 18 and 24 in https://tigress-web.princeton.edu/~jdh4/how_to_profile_with_dlprof_may_2021.pdf

I followed the steps in this tutorial: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

However, I don't see the "DLProf" option anywhere in Tensorboard

It's because I need to install DLprof, right?

I tried

    pip3 install nvidia-pyindex
    pip3 install nvidia-dlprof
    docker pull nvcr.io/nvidia/tensorflow:21.07-tf2-py3

But then when I try

     docker run --gpus all -it --rm --network=host -v $PWD:/workspace/tf2 nvcr.io/nvidia/tensorflow:21.07-tf2-py3

I get an error that says

    ERROR: This container was built for NVIDIA Driver Release 470.42 or later, but version 455.32.00 was detected and compatibility mode is UNAVAILABLE

If I try `dlprof` like on slide 16 of that tigress-web.princeton.edu link

    dlprof --mode=tensorflow2 --key_node=sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits --iter_start=100 --iter_stop=200 python3 myPython.py

it is able to generate `.sqlite` and `.qdrep` files, but when I try `dlprofviewer nsys_profile.sqlite`, I get an error saying

    the DLProf database is version 'UNKNOWN` BUT DLProf is version '1.3.0'. Please downgrade DLProf to match the database version

can anyone help?

**Comment by stephanwlee** [comment]
DLProf is not related to TensorFlow or TensorBoard organization but rather is NVIDIA's. I do know that @cvinson830 was maintaining it.

@cvinson830  Could you take a look, Chris?

**Comment by ceevee830** [comment]
Thanks Stephan for '@'ing me.

Hi za13, 

Instead of specifying the NSYS database here `dlprofviewer nsys_profile.sqlite`, specify the DLProf database like this `dlprofviewer dlprof_dldb.sqlite`

**Comment by UsharaniPagadala** [comment]
@za13 
Could you please respond on @ceevee830 's comment and  please confirm if this issue can be closed.Thanks
