### ISSUE TITLE
Collect internal per-dashboard stats.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#524]
Currently, we only use Analytics to collect visit counts for TensorBoard in general. We should use [Analytics events](https://support.google.com/analytics/answer/1033068?hl=en) to collect per-dashboard stats.

Plugin authors will want to gauge the impact of their plugins. One such measure is how many internal users use their dashboards.

**Comment by wchargin** [comment]
We need to ensure that all occurrences of analytics are opt-in _only_, starting with the projector plugin, where this is currently not the case.

**Comment by chihuahua** [comment]
I think we can track internal uses, which might be fine ... and ignore external uses.

**Comment by wchargin** [comment]
@chihuahua By "internal" and "external", I assume that you mean "uses within Google" and "uses by people outside of Google."

Could you please point me to the part of the projector code that makes this distinction? It looks to me like
  * the `AnalyticsLogger` class logs whenever its `eventLogging`/`pageViewLogging` fields are set ([link to code](https://github.com/tensorflow/tensorboard/blob/866bb01b014f786c83462eed807587f3dd39de03/tensorboard/plugins/projector/vz_projector/analyticsLogger.ts#L39-L55));
  * an `AnalyticsLogger` is created by `<vz-projector>`, initializing `eventLogging`/`pageViewLogging` to the Polymer component values of the same name ([link to code](https://github.com/tensorflow/tensorboard/blob/3a8559932a3eaa7ba75af89deb3f3ae10a1594cf/tensorboard/plugins/projector/vz_projector/vz-projector.ts#L104-L106)); and
  * a `<vz-projector>` is created by the `<vz-projector-dashboard>`, which has these two properties hard-coded to `true` ([link to code](https://github.com/tensorflow/tensorboard/blob/3a8559932a3eaa7ba75af89deb3f3ae10a1594cf/tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.html#L54-L60)).

Finally, `vz-projector-dashboard` is indeed the top-level component included in `default-plugins.ts`.

Thus, including any instance of Google Analytics as a `<script>` tag in the open-source TensorBoard will cause the projector plugin to log for all users. The only reason that it does not do so currently is that the only inclusion of Google Analytics is in `vz-projector-app`, which the open-source TensorBoard does not use.

**Comment by chihuahua** [comment]
Ah! We scrub the analytics JS from GitHub:
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/analytics.html

Internally, some JS supplants the TODO. One way we could implement this is to define a global variable in that internal logic within analytics.html and only log events if that global is defined.

**Comment by wchargin** [comment]
> define a global variable and only log events if that global is defined

Right. My original point was that we will have to be careful here with the projector plugin, because it will always log analytics if Google analytics is loaded at all.
