### ISSUE TITLE
Tensorboard op graph: Clarifications

### ISSUE THREAD

**Issue by shahjaidev** [tensorflow/tensorboard#5257]
Hello!

A few questions:

i) Is the op graph provided by Tensorboard dependent on whether the model was trained on a CPU vs GPU? In other words, does the computational graph differ across both?

ii) More of a confirmation question: If I'm using tensorboard during training ( model.fit() or tf.gradientTape() ), does the op graph visualization take into account operators invoked during backpropagation as well?

**Comment by UsharaniPagadala** [comment]
@shahjaidev 

Could you please refer these [model.fit](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_keras_modelfit) and [GradientTape](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_other_methods), and let us if it helps.Thanks

**Comment by stephanwlee** [comment]
> i) Is the op graph provided by Tensorboard dependent on whether the model was trained on a CPU vs GPU? In other words, does the computational graph differ across both?

No, it does not. TensorBoard currently only consumes the GraphDef created by TensorFlow (or anything that can create GraphDef). Now, depending on where the GraphDef is being emitted, it may have device specific optimizations applied in which case you will see differences. All in all, it largely depends on where you get the GraphDef and write the summaries.

ii) More of a confirmation question: If I'm using tensorboard during training ( model.fit() or tf.gradientTape() ), does the op graph visualization take into account operators invoked during backpropagation as well?

Similar to the first answer. TensorBoard only visualizes GraphDef and it depends on how/where you emit the GraphDef. If you get `ConcreteFunction.FuncGraph` from autograph, you will not see the backprops but if you somehow get a reference to the Graph that contains backprops, you will see them in TensorBoard (at the moment, I forget whether `tf.summary.trace` contains backprops).

I hope this helps.

**Comment by UsharaniPagadala** [comment]
@shahjaidev 

Please update on  @stephanwlee  comment.Thanks

**Comment by shahjaidev** [comment]
Thanks for the answer!
