### ISSUE TITLE
Not able to export CSV/JSON only SVG

### ISSUE THREAD

**Issue by AnishKumarNayak** [tensorflow/tensorboard#5267]
Hi, I'm currently using tensorflow to train a neural network and upon completion of all the steps I'm using the command tensorboard --logdir log which takes the event file and opens it up on a localhost address.
Upon clicking on the data download link option present on the site, it only gives me an option to export the data as an SVG file, without the step count etc.
I have seen previously that the tensorboard data can exported in the form of CSV and JSON files as well, however in this case it is not observed
Could someone please let me know what the solution for this would be?

Thanks 
<img width="1137" alt="Screenshot 2021-08-24 at 4 45 31 PM" src="https://user-images.githubusercontent.com/84912343/130607388-da0d9b2d-052d-4cfb-92bd-30eb94dab491.png">

**Comment by AnishKumarNayak** [comment]
I would also like to note that I'm using anaconda3 to run tensorflow, though not sure if this is relevant or not

**Comment by bileschi** [comment]
Hi, can please include the environment information?

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

Also, can you indicate which affordance you are clicking where you expect to see CSV & JSON  links?

**Comment by bileschi** [comment]
Would also be helpful if you can share your logdir, if possible.

**Comment by AnishKumarNayak** [comment]
> Would also be helpful if you can share your logdir, if possible.

Hi, I would like to update the situation as of now, upon running tensorflow in a different set up with the tensorboard command,  it does display JSON and CSV option as shown below 
<img width="1425" alt="Screenshot 2021-08-25 at 10 30 10 AM" src="https://user-images.githubusercontent.com/84912343/130729434-4b596572-23d6-408f-bb32-065259995fb8.png">
Now however, upon downloading the JSON file and opening it in the textedit it gives the error as below
<img width="694" alt="Screenshot 2021-08-25 at 10 33 00 AM" src="https://user-images.githubusercontent.com/84912343/130729639-78bb5d8b-3027-48eb-9d77-339ab838ac8c.png">
For some reason I'm unable to upload the event log here (not sure if the format is not supported or something)

**Comment by stephanwlee** [comment]
Experience is wonky but you need to choose a run to download in the dropdown first then click on the CSV or JSON. 

![image](https://user-images.githubusercontent.com/2547313/130822320-84d66bbb-9efc-4eb1-ad08-2560a2b939c3.png)

I believe newer version of TensorBoard "fixes" this by hiding the CSV button when you have not chosen any run.

**Comment by AnishKumarNayak** [comment]
Hi, thanks for the reply
I did try that however this is what shows up (on clicking the run to download)
<img width="400" alt="Screenshot 2021-08-25 at 9 48 47 PM" src="https://user-images.githubusercontent.com/84912343/130827801-8d292039-497e-4829-9b05-cbea27ba20ad.png">

**Comment by stephanwlee** [comment]
Hi there. Could you say what is odd about it? "." is a legal name of a run in TensorBoard. In fact, you should have "." on the run selector on the left.

**Comment by AnishKumarNayak** [comment]
Oh, my bad I got a bit confused by it. I was under the assumption that it was referring to an error of some sort. Thanks a lot (I've noted that an output is present for the same)

**Comment by stephanwlee** [comment]
Cool, glad that helped. For my information, would you mind sharing version of TensorBoard you are using?

**Comment by AnishKumarNayak** [comment]
Sure, tensorboard --version
2.0.0
