### ISSUE TITLE
Tensorboard Projector TSNE Not Working in Chrome

### ISSUE THREAD

**Issue by HarryBaker** [tensorflow/tensorboard#528]
Hello,

A few days ago, the TSNE clustering in the tensorboard projector (http://projector.tensorflow.org/) stopped working for me. Vectors that had previously formed clusters no longer were, and would instead clump into an indistinct single cluster.

Interestingly, this is only true for Chrome. In firefox the website behaves normally. 

I can't attach the data I'm using this because it's protected, but I'm wondering if anyone else has noticed this.

**Comment by chihuahua** [comment]
Interesting. Do you see error messages in the [Chrome console](https://developers.google.com/web/tools/chrome-devtools/console/)?

**Comment by HarryBaker** [comment]
No, I don't

**Comment by bileschi** [comment]
Please reopen if this is still an issue. Thanks :)
