### ISSUE TITLE
Links are unreadable in the dark theme

### ISSUE THREAD

**Issue by LyzhinIvan** [tensorflow/tensorboard#5309]
<img width="827" alt="Screen Shot 2021-09-13 at 8 29 22 AM" src="https://user-images.githubusercontent.com/6265308/133028889-a7c358a9-9971-4f1a-8704-2219281ea426.png">
I suggest to make them more contrast relative to dark background - it will be good to make them white like all text.

**Comment by bmd3k** [comment]
Thanks for the report.  Would be good to fix this.

There are some error screens where we do a bit better. This one for example still uses a blue (#42a5f5) and a purple (#ba68c8) for unvisited links and visited links but looks much better:

![image](https://user-images.githubusercontent.com/17152369/133493426-f8ae44a0-31cc-4e8b-a723-a2b5d5c794e4.png)

**Comment by UsharaniPagadala** [comment]
@LyzhinIvan 

Could you please have a look at @bmd3k  comment and move this issue to closed status  if it resolved.Thanks

**Comment by bmd3k** [comment]
This should be fixed now in the nightlies.
