### ISSUE TITLE
README link is antiquated in docs

### ISSUE THREAD

**Issue by erichiller** [tensorflow/tensorboard#532]
Quick fix:

The link to the tensorboard README is referencing the tensorboard repo
<https://www.tensorflow.org/get_started/summaries_and_tensorboard>

2nd paragraph:
```
This tutorial is intended to get you started with simple TensorBoard usage. There are other resources available as well! The TensorBoard README has a lot more information on TensorBoard usage, including tips & tricks, and debugging information.
```

**Comment by chihuahua** [comment]
The docs source code is fixed. That page must be updated though. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/get_started/summaries_and_tensorboard.md

**Comment by bileschi** [comment]
Obsolete :)
