### ISSUE TITLE
Tensorboard cannot distinguish image/histogram summaries

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tensorboard#5322]
## Issue description

When using the [TensorBoard callback](https://github.com/keras-team/keras/blob/90887569b979a687e6af4249ce12be1a70f75179/keras/callbacks.py#L2034) with `write_images=True` a [histogram](https://github.com/keras-team/keras/blob/90887569b979a687e6af4249ce12be1a70f75179/keras/callbacks.py#L2536) and an [image](https://github.com/keras-team/keras/blob/90887569b979a687e6af4249ce12be1a70f75179/keras/callbacks.py#L2563) summary are written with the same name. When using TensorBoard to view the histogram/distributions corresponding to the weights an error is thrown for all of the weights which have an image summary written. This occurs when the histogram_impl reads the image summary when it is expecting a histogram summary. This seems to happen as the [ReadTensorRequest](https://github.com/tensorflow/tensorboard/blob/a060de9136ca67681161a964bde27f3735a82747/tensorboard/data/proto/data_provider.proto#L236-L247) makes no distinction between different types of summaries.

This seems to be a bug with TensorBoard, because the TensorFlow documentation states:

> All the __image__ collections with the same name constitute a time series of image collections.

> All the __histograms__ with the same name constitute a time series of histograms.

... and I cannot find any documentation to indicate that names must be unique across all different types of summary. 

Alternatively if the summary names are expected to be unique, then the Keras callback should be updated so that the image & histogram names add some identifier which distinguishes them.

**Comment by pindinagesh** [comment]
@peteboothroyd 

Thanks for pointing that out, please find these [link1](https://github.com/keras-team/keras/issues/3358) and [link2](https://stackoverflow.com/questions/42112260/how-do-i-use-the-tensorboard-callback-of-keras) for your reference, let us know if it helps. Thanks

**Comment by peteboothroyd** [comment]
@pindinagesh thanks for the quick response, but neither of those links are relevant for the problem I've reported.

**Comment by yatbear** [comment]
Hi @peteboothroyd,

Apologies for the delay! We recently fixed this collision at: https://github.com/keras-team/keras/pull/16468/commits/0b4dceee025d64b4b70bd1a060e13e07a5185954

The fix is now included in Keras nightly, please try installing `tf-nightly` and `keras-nightly` to verify the behavior. Thank you!

**Comment by peteboothroyd** [comment]
awesome, thanks!
