### ISSUE TITLE
Having no hparams data should return 200 instead of 400

### ISSUE THREAD

**Issue by yatbear** [tensorflow/tensorboard#5347]
Redefine following endpoints:
- `hparams/experiment`
- `hparams/session_groups`
- `hparams/download_data`

So that having no hparams data is still a 200 OK response, and just returns either A) an entirely empty response `{}` or B) a placeholder response for an empty experiment (with no hparams or metrics, and placeholder values for the name, description, etc).

Googlers, see b/156776593 for more context.

**Comment by pindinagesh** [comment]
@yatbear 

The [PR](https://github.com/tensorflow/tensorboard/pull/5357) is already created which fixes this issue once it got merged. Thanks
