### ISSUE TITLE
HDFS and S3 support of `tf.io.gfile` with `tensorflow-io`

### ISSUE THREAD

**Issue by y-tag** [tensorflow/tensorboard#5359]
Since TensorFlow 2.6, the HDFS and S3 support of `tf.io.gfile` have moved to `tensorflow-io` package (tensorflow/tensorflow#51583).
Therefore, TensorBoard with TensorFlow 2.6 can not read files in the HDFS or S3 as it is.

Explicitly importing `tensorflow_io` module before running TensorBoard is helpful for me.
```
python -c 'import tensorflow_io,tensorboard.main; tensorboard.main.run_main()' --port 6066 --logdir hdfs://path/to/dir
```

However, it might be better to import `tensorflow_io` automatically in TensorBoard if the package is installed.

**Comment by japie1235813** [comment]
Thanks for the feedback. We will look into this and conditionally import tensorflow_io in TB

**Comment by spolloni** [comment]
@y-tag why was this closed?

**Comment by y-tag** [comment]
Oh, it's just mistake... :sweat:
