### ISSUE TITLE
Tensorboard options reuse_port and path_prefix not workiing together

### ISSUE THREAD

**Issue by lfvillavicencio** [tensorflow/tensorboard#5368]
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

Diagnostics:

```
### Diagnostics

<details>
<summary>Diagnostics output</summary>


--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='ip-192-168-0-140.us-east-2.compute.internal', release='5.4.129-63.229.amzn2.x86_64', version='#1 SMP Tue Jul 20 21:22:08 UTC 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.6.0
INFO: installed: tensorflow==2.1.0
INFO: installed: tensorflow-estimator==2.1.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.6.0'

--- check: tensorflow_python_version
2021-10-09 00:00:37.825076: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-10-09 00:00:37.825186: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-10-09 00:00:37.825199: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
INFO: tensorflow.__version__: '2.1.0'
INFO: tensorflow.__git_version__: 'v2.1.0-rc2-17-ge5bf8de'

--- check: tensorboard_data_server_version
INFO: data server binary: '/home/ec2-user/.local/lib/python3.7/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/ec2-user/.local/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'ip-192-168-0-140.us-east-2.compute.internal'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=13792819, st_dev=66305, st_nlink=2, st_uid=1000, st_gid=1000, st_size=48, st_atime=1633734297, st_mtime=1633737565, st_ctime=1633737565)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/ec2-user/.local/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.14.1
astor==0.8.1
aws-cfn-bootstrap==2.0
cached-property==1.5.2
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.6
docutils==0.14
gast==0.2.2
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.41.0
h5py==3.4.0
idna==3.2
importlib-metadata==4.8.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
lockfile==0.11.0
Markdown==3.3.4
numpy==1.21.2
oauthlib==3.1.1
opt-einsum==3.3.0
pip @ file:///builddir/build/BUILD/pip-20.2.2/dist/pip-20.2.2-py2.py3-none-any.whl
protobuf==3.18.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pystache==0.5.4
python-daemon==2.2.3
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
scipy==1.4.1
setuptools @ file:///builddir/build/BUILD/setuptools-49.1.3/dist/setuptools-49.1.3-py3-none-any.whl
simplejson==3.2.0
six==1.16.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
typing-extensions==3.10.0.2
urllib3==1.26.7
Werkzeug==2.0.2
wheel==0.37.0
wrapt==1.13.1
zipp==3.6.0


### Next steps
```

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140): Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (64-bit)
  - Image: 
![image](https://user-images.githubusercontent.com/89262839/136636331-01e0ff58-d92e-4f14-8a6c-a8a14f5fdf41.png)

## Issue description

When I try to run multiple tensorboard visualizations on the same port using the command ```reuse_port``` and ```path_prefix```, sometimes only 1 visualization gets active on the browser or sometimes none of them.

Steps: 

 1. download any 3 tensorboard logs and place them on the correct directory. suppose they are ```modelA```, ```modelB```, and ```modelC```
 2.  Run the following commands in order to show then on the same port and different context:
 
```
tensorboard --logdir=/path/to/modelA --port 8090 --bind_all --reuse_port true --path_prefix='/tensorboard/modelA'
tensorboard --logdir=/path/to/modelB --port 8090 --bind_all --reuse_port true --path_prefix='/tensorboard/modelB'
tensorboard --logdir=/path/to/modelC --port 8090 --bind_all --reuse_port true --path_prefix='/tensorboard/modelC'
```

**Comment by lfvillavicencio** [comment]
(Continuing with steps)
3. You can see that all of those 3 commands doens-t show an error. They say that they are running (I used 3 different consoles for this example)
4.  Go to the website: ```localhost:8090/tensorboard/modelA``` or  ```localhost:8090/tensorboard/modelB```  or ```localhost:8090/tensorboard/modelC```. If you have luck, only one of them will be displayig data.

**Comment by lfvillavicencio** [comment]
any news of any way to help?

**Comment by lfvillavicencio** [comment]
My case is even worse. I have an application running inside a Kubernetes Pod. There is a Tornado Server listening on port 8000 for example, and when it hears a database change , it starts a tensorboard visualization for some logdir on the port 9090. I want to expose that tensorboard visualization. I have a ingress-controller exposing port 9090 with prefix tensorboard, so any visualization is started with ```--path_prefix='\tensorboard\visuaization_id'```. If my parent process starts the tornado server on port 8090 with ```reuse_port``` option, then the tensorboard visualizations on 9090 with ```reuse_port``` will work fine? I dont know how to tell nginx to listen visualizations that are not created. Those visualizations will be created on the way

**Comment by nfelt** [comment]
This really has nothing to do with either of those flags.  It's not that they "don't work" - they are not intended for the purposes you're trying to use them for, but that's not a bug or a flaw in TensorBoard.

**Comment by Xiuchen519** [comment]
> My spected usage is on Kubernetes: One Pod listens for a call of TB visualization. When the Call is received, this api changes the atribute "status" on a document on Document Db. My tensorboard pod hears that change on the MongoDB and looks for the path of the requested TB visualization, then runs : `tensorboard --log_dir=log_dir_from_db --port=9000 --reuse_port true --path_prefix=/tensorboard/TB_ID_from_db --bind_all`
> 
> Then, my first Pod api returns `domainname/tensorboard/TB_ID_from_db` because the visualization will start in paralel in this route. This is why i need reuse port and path prefix. I cant be setting a new port on each requests

I have almost the same needs as you. Do you have a way to solve this problem now? What other tools do I need to help me achieve this goal?

**Comment by lfvillavicencio** [comment]
> > My spected usage is on Kubernetes: One Pod listens for a call of TB visualization. When the Call is received, this api changes the atribute "status" on a document on Document Db. My tensorboard pod hears that change on the MongoDB and looks for the path of the requested TB visualization, then runs : `tensorboard --log_dir=log_dir_from_db --port=9000 --reuse_port true --path_prefix=/tensorboard/TB_ID_from_db --bind_all`
> > Then, my first Pod api returns `domainname/tensorboard/TB_ID_from_db` because the visualization will start in paralel in this route. This is why i need reuse port and path prefix. I cant be setting a new port on each requests
> 
> I have almost the same needs as you. Do you have a way to solve this problem now? What other tools do I need to help me achieve this goal?

Yeah. 
Let you application use (for example), the port 8000 for requests and let be the port 8100 for tensorboard (or even the set of ports 8100, 8200,8300 as many as you need aditional tensorbaord visualizations). Then in your dockerfile expose the ports 8000 and 8100 (or 8000, 8100, 8200, 8300 using the EXPOSE command (one per port) ).
Later, for your kubernetes create a deployment indicating all the ports that you use. You will need to create as many services as ports. So you have one Service for you application (on port 8000) and another Service for you tensorboard (on port 8100) (or many other Services for each port you need).  The final step is to create a ingress-controller for mapping your tensorboard services to a different path. (for example YOUR_HOST/tensorboard/graph_1 for service on 8100, then YOUR_HOST/tensorboard/graph_2 for srevice in port 8200, ..... Dont forget exposing your main service on port 8000

**Comment by Xiuchen519** [comment]
> 
Thank you for your reply😊. In this way, we can create multiple tensorboard instances and access them through one port 8080. But just like the problem you encountered, in my application scenario, there will be multiple requests (hundreds, thousands or more) that want to create their own tensorboard instance at the same time, but I cannot set a port for each of them.  With this method, can I support thousands of requests without using too many ports?
