### ISSUE TITLE
Time series scalar smoothing range differs from Scalars

### ISSUE THREAD

**Issue by javirk** [tensorflow/tensorboard#5370]
## Issue description

The maximum of the smoothing parameter in "Time series" mode is set to 1, so moving the slider all the way to the right results in all curves going to 0. I think the right behavior is that of "Scalars", where the maximum is 0.999. While this is not a very important issue, I think having a coherent behavior is helpful.

I add two images showing the difference:

![Time_series](https://user-images.githubusercontent.com/3169791/136771176-8a6cc52e-c740-4197-90bf-3067db4ed1bb.png)
![Scalars](https://user-images.githubusercontent.com/3169791/136771182-4b084b28-7fe0-488d-9526-69f483c114df.png)

**Comment by UsharaniPagadala** [comment]
@javirk 
Could you please refer this [smoothing-parameter](https://stackoverflow.com/questions/42281844/what-is-the-mathematics-behind-the-smoothing-parameter-in-tensorboards-scalar) similar issue,hope it helps.Thanks

**Comment by javirk** [comment]
Yes, I understand perfectly how it works, I just say that having 1 in EMA doesn't make sense. In that link they say:
`last = last * smoothingWeight + (1 - smoothingWeight) * nextVal`
If smoothingWeight = 1, then last=last, which is useless. I think the range should be 0 - 0.999, as it is in the Scalars tab.

**Comment by bileschi** [comment]
Hello @javirk , Thanks for the feedback and sorry for the trouble.  This issue was fixed in https://github.com/tensorflow/tensorboard/pull/4372 and will be in the next release.

To have this behavior right now if you build from head.

Please re-open if there are any issues.
