### ISSUE TITLE
access tensorboard profiler data through API

### ISSUE THREAD

**Issue by kevint324** [tensorflow/tensorboard#5411]
https://www.tensorflow.org/guide/profiler#tensorflow_stats

tf + tensorboard is a great tool for performance profiling
It would be much better to enable users to collect the stats data(performance, memory, etc.) through api so we could monitor the stats in our CI.

Thanks

**Comment by ericdnielsen** [comment]
While such an API would be useful, it is pretty far down our priority list at the present time.  

You might be able to find or request an API in the profiler's repo: https://github.com/tensorflow/profiler
