### ISSUE TITLE
Selecting values for Hparams: consider the best value instead of the last value

### ISSUE THREAD

**Issue by chrisn-pik** [tensorflow/tensorboard#5418]
Hey there,

when using HParams, the result might be confusing, because models are evaluated based on their final values. In case of fluctuations the final value might not be very meaningful. It would be great if one could also select the best value for example.

I am trying to implement this for myself using a small stupid script, where I simply replace the last values by the max/min values of all epochs. I am using ray for parallelization. When changing progress.csv or results.json the scalar plots and Hparams do not change. What files are considered by Tensorboard?

**Comment by stephanwlee** [comment]
Thanks for the feedback. I think the notion of "best" can differ for different folks so, ideally, we should let user manually choose from extemum, last, avg_last_100_steps, etc...

We will keep this in mind. Thanks.

**Comment by chrisn-pik** [comment]
@stephanwlee @nfelt  Thank you very much for your fast replies! Yes, my issue is basically a duplicate of #4630 .

However, I am still wondering on how to accomplish a dirty solution.

What files are considered by hparams? Manually changing values in progress.csv or results.json did not change anything (neither hparams, nor scalar plots). Any ideas?

**Comment by stephanwlee** [comment]
The value comes from the file where are, event files. They do not get logged to a CSV or JSON. 

Hparam API specific read scalars value from a scalars summary with a tag that you specify in the hparams API and it picks the last value. 

If you truly want something dirty, please try to modify the lines here:
https://github.com/tensorflow/tensorboard/blob/8b80303afbf047e939626ae06af0eabc6cc8f0e1/tensorboard/plugins/hparams/list_session_groups.py#L102-L108

**Comment by chrisn-pik** [comment]
@stephanwlee Thanks for your reply! I was hoping for an easy way to do this without dealing with event files, so perhaps I will wait until the feature might come available at some point.

Closing, duplicate of #4630
