### ISSUE TITLE
TensorBoard: Infer first argument

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tensorboard#543]
It would be nice if 
`tensorboard /some/directory` 
would be correctly translated to 
`tensorboard --logdir=/some/directory`

We would need to be forwards-compatible with respect to "db" becoming the dominant mode of turning on TensorBoard (check if we are pointing to a db or to a directory?)

**Comment by lucasb-eyer** [comment]
Not sure if related implementation-wise or not, but definitely related usage-wise, so sorry for [repeating myself](https://github.com/tensorflow/tensorboard/issues/179#issuecomment-347006910): it would be nice if that wasn't just for the first argument, but for any "free arguments" such that `tensorboard /some/dir1 /some/dir2 /some/other/dir` would get translated to `tensorboard --logdir /some/dir1:/some/dir1,/some/dir2:/some/dir2,/some/other/dir:/some/other/dir`.

**Comment by wchargin** [comment]
We probably don’t want to take bare positional arguments, as they’re
incompatible with Abseil, but as of #1409 it may be possible to set
`nargs="+"` on `--logdir` to support @lucasb-eyer’s suggestion. May be
worth looking into.

**Comment by nfelt** [comment]
I thought Abseil only rejected unknown args that started with `-`, not any positional argument at all?  The canonical example here shows `argv` passing through the "non-flag" arguments:

https://abseil.io/docs/python/guides/flags

At any rate, now that we're using the argparse subparsers for subcommands, we already have a CLI API that diverges from bog-standard Abseil flag parsing, so diverging further to relax the requirement of passing `--logdir` and allow e.g. `tensorboard serve ~/mylogs` seems reasonable.

My main concern with omitting the flag enitrely is whether we would want to still have some mechanism to specify the type of data source, for forwards-compatibility with a future expansion of allowed sources.  I suppose scheme-style prefixing (like the experimental DB support) is an option, but given the poor user experience history of interpreting special characters in `--logdir` prior to the 2.0 change to factor that into `--logdir_spec` I'm a little nervous about relying on that.

**Comment by bileschi** [comment]
Closing this FR, as we need the positional argument at this point to specify, e.g., secondary subcommands like `tensorboard upload` or `tensorboard serve`
