### ISSUE TITLE
Dumping the embeddings nearest neighbours results

### ISSUE THREAD

**Issue by alleboudy** [tensorflow/tensorboard#546]
Hello, thank you so much for the magnificent work [big fan :D ] 
Please, would it be possible to dump the embeddings nearest neighbours results to the disk?
If not, would appreciate any advice regarding generating the same results of tensorboard, perhaps with just python. like what should be the steps to perform? [obviously, naively getting the NN per word from the embeddings vectors takes forever and the results aren't as good as the tensorboard's ]
[I did try gensim as well, the results are good and really quick to acquire, however, not as good as  tensorboard's ]
Thank you!

**Comment by bileschi** [comment]
This is really a request for tensorflow code, not tensorboard.  Please re-open if mis-categorized.  Thanks!
