### ISSUE TITLE
Set a default tag search query for tensorboard besides .*

### ISSUE THREAD

**Issue by kempy** [tensorflow/tensorboard#547]
I'd like to be able to set a default tag search for tensorboard so that when I open tensorboard I get the search that I want without having to type a long regex repeatedly. I have a ton of metrics for various slices of data, but two that I primarily care about and always want to see first

For example, I'd like to replace the default **.\*** search with **.\*Classification.Accuracy.\***

**Comment by chihuahua** [comment]
How about we store the latest regex for each dashboard within local storage? And then, when the user revisits the dashboard later, we just load the latest regex that the user had inputted.

**Comment by kempy** [comment]
That works for my use case, but it might also be nice to have the option to have it be something like a url parameter, so that you can give someone else a link to a dashboard with a pre-filled search. Thanks!

**Comment by chihuahua** [comment]
This was fixed by #643, which set the default to empty, ie the search category is empty by default.

**Comment by chihuahua** [comment]
Actually, this is really fixed by #787, which lets the user load TensorBoard with a custom tagFilter GET parameter.
