### ISSUE TITLE
Plugin path is incorrect when `--path_prefix` was configured.

### ISSUE THREAD

**Issue by hsinhoyeh** [tensorflow/tensorboard#5472]
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='viewer-a4e50b4f89b636c7e2d12bebd3da533901b3ea8a-deploymentrscj6', release='5.11.0-1023-gcp', version='#25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.7.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
INFO: installed: tensorflow-estimator==2.7.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.7.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.7.0'
INFO: tensorflow.__git_version__: 'v2.7.0-rc1-69-gc256c071bb2'

--- check: tensorboard_data_server_version
INFO: data server binary: '/usr/local/lib/python3.8/dist-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'viewer-a4e50b4f89b636c7e2d12bebd3da533901b3ea8a-deploymentrscj6'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=8533631, st_dev=7340069, st_nlink=2, st_uid=0, st_gid=0, st_size=4096, st_atime=1640073401, st_mtime=1640073312, st_ctime=1640073312)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/usr/local/lib/python3.8/dist-packages']; bad_roots (0): []

--- check: full_pip_freeze

h5py==3.5.0
idna==3.3
keras==2.7.0
Keras-Preprocessing==1.1.2
libclang==12.0.0
Markdown==3.3.4
numpy==1.21.3
oauthlib==3.1.1
opt-einsum==3.3.0
pip==20.2.4
protobuf==3.19.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
setuptools==58.5.2
six==1.16.0
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-cpu==2.7.0
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.21.0
termcolor==1.1.0
typing-extensions==3.10.0.2
urllib3==1.26.7
Werkzeug==2.0.2
wheel==0.34.2
wrapt==1.13.3

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

For browser-related issues, please additionally specify: NOT A BROWSER ISSUE

## Issue description

Hi there, I was running tensorboard with [kubeflow](https://github.com/kubeflow/kubeflow) with v1.4.
When I launch the tensorboard, the following running command is used:
```
   viewer-a4e50b4f89b636c7e2d12bebd3da533901b3ea8a-pod:
    Image:      tensorflow/tensorflow:2.7.0
    Port:       6006/TCP
    Host Port:  0/TCP
    Args:
      tensorboard
      --logdir=/tensorboard-dataxx
      --path_prefix=/tensorboard/viewer-a4e50b4f89b636c7e2d12bebd3da533901b3ea8a/
      --bind_all
```
where the `path_prefix`was configured. so I was able to access tensorboard ui though `http://<my-host>:<myport>/tensorboard/viewer-a4e50b4f89b636c7e2d12bebd3da533901b3ea8a/`

However, when I go to plugin and try to configure some parameters (in my scenario, I use `what-if-tool` plugin)
the requests send to tensorboard were not correct (eg: `http://<my-host>:<myport>/data/plugin/whatif/examples_from_path?examples_path=%2Ftensorboard-dataxx%2Fuci_census%2Fadult.tfrecord&max_examples=1000&sampling_odds=1&sequence_examples=false`), I believed the path_prefix was missed there.

[The codebase](https://github.com/tensorflow/tensorboard/blob/29cfcec9d15c47d1bf54b15df24e65bc38c188e6/tensorboard/backend/application.py#L282) also conforms to this where the path was constructed by 
```
                    path = (
                        DATA_PREFIX
                        + PLUGIN_PREFIX
                        + "/"
                        + plugin.plugin_name
                        + route
                    )
```

I believe `path_prefix` should be included in the plugin path, isn't it? Thanks.
Once I removed `path_prefix` or sent it to empty, the plugin works.

**Comment by bileschi** [comment]
Thankyou for the report : routing this to the parties responsible for 'what if tool'

**Comment by hsinhoyeh** [comment]
> Thankyou for the report : routing this to the parties responsible for 'what if tool'

No, it is not.

plugin implemented the interface `base_plugin.TBPlugin`, with the method `get_plugin_apps` returning the plugin's routes and handlers, as you could see here https://github.com/PAIR-code/what-if-tool/blob/master/tensorboard_plugin_wit/wit_plugin.py#L105
```
return {
        '/index.js': self._serve_js,
        '/wit_tb_bin.html': self._serve_wit,
        '/wit_tb_bin.js': self._serve_wit_js,
        '/infer': self._infer,
        '/update_example': self._update_example,
        '/examples_from_path': self._examples_from_path_handler,
        '/sprite': self._serve_sprite,
        '/duplicate_example': self._duplicate_example,
        '/delete_example': self._delete_example,
        '/infer_mutants': self._infer_mutants_handler,
        '/eligible_features': self._eligible_features_from_example_handler,
        '/sort_eligible_features': self._sort_eligible_features_handler,
    }
```
In this case, the plugin's examples_from_path_handler should be served under the path `${path_prefix}/${DATA_PREFIX}/${PLUGIN_PREFIX}/examples_from_path`, where `${path_prefix}/${DATA_PREFIX}/${PLUGIN_PREFIX}/` is handled by the tensorboard in https://github.com/tensorflow/tensorboard/blob/29cfcec9d15c47d1bf54b15df24e65bc38c188e6/tensorboard/backend/application.py#L258.

**Comment by jameswex** [comment]
@hsinhoyeh are you saying the issue is in the TB application and plugin architecture and not in the what-if-tool itself? Sounds like this would be a problem for any plugin in that case. Do you know if that is true?

**Comment by hsinhoyeh** [comment]
@jameswex @bileschi 

sorry for my previous misleading finding, it didn't explain why other plugins works but only wit didn't.
> @hsinhoyeh are you saying the issue is in the TB application and plugin architecture and not in the what-if-tool itself? Sounds like this would be a problem for any plugin in that case. Do you know if that is true?


It seems What-if Tool didn't use tf-backend's pluginRoute (https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/tf_backend/router.ts#L56)
```
    pluginRoute: (
      pluginName: string,
      route: string,
      params?: URLSearchParams
    ): string => {
      return createDataPath(
        dataDir + '/plugin',
        `/${pluginName}${route}`,
        params
      );
    },
```
but instead use static path for requests (here is one of the examples, there are many others https://github.com/PAIR-code/what-if-tool/blob/5042800f03faada531d0d3bf23ef95cd3e8fe7fa/wit_dashboard/wit-dashboard.html#L8064)

```
var url = this.makeUrl_('/data/plugin/whatif/update_example', null);
```

@jameswex would you mind confirming this issue? thanks

**Comment by jameswex** [comment]
Thanks @hsinhoyeh , that clears things up for me! I created https://github.com/PAIR-code/what-if-tool/issues/190 in the WIT codebase to track this issue (linking back to this bug). I can fix it in the WIT codebase and release a new version of the tensorboard-plugin-wit pip package which will contain the fix.

**Comment by jameswex** [comment]
[tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip](https://github.com/tensorflow/tensorboard/files/7810490/tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip)

@hsinhoyeh Can you try installing the updated tensorboard_plugin_wit pip package in this zip file in your environment, then re-launching WIT and testing it with your use-case? Hopefully this version works both with and without a path_prefix in your TesnorBoard instance.

**Comment by hsinhoyeh** [comment]
> [tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip](https://github.com/tensorflow/tensorboard/files/7810490/tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip)
> 
> @hsinhoyeh Can you try installing the updated tensorboard_plugin_wit pip package in this zip file in your environment, then re-launching WIT and testing it with your use-case? Hopefully this version works both with and without a path_prefix in your TesnorBoard instance.

@jameswex thanks for the fix, but, unfortunately, it seems not to work for me.
I created a repo for wrapping up this fix with the existing tensorboard image, please confirm my wrap is correct https://github.com/footprintai/tensorboardd

here is pip3 freeze from the container

```
pip3 freeze
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit @ file:///tensorboard_plugin_wit-1.8.1-py3-none-any.whl
```
do you mind creating a branch so I could install it directly from the source code?

**Comment by jameswex** [comment]
I pushed the WIT changes under test to the WIT repo to the branch "route_fit". See https://github.com/PAIR-code/what-if-tool/tree/route_fix. I just made a fix and tested locally that WIT works with and without a path prefix in my local setup with this change. I attached an updated pip package for you to try again. Let me know if this new version solves the issue.

[tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip](https://github.com/tensorflow/tensorboard/files/7815350/tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip)


If you ever want to build your own version of the WIT plugin pip package, see setup instructions for building WIT at https://github.com/PAIR-code/what-if-tool/blob/route_fix/DEVELOPMENT.md and then run `bazel run tensorboard_plugin_wit/pip_package:build_pip_package` and find the package created in `/tmp/wit-pip/release/dist` directory.

**Comment by hsinhoyeh** [comment]
> I pushed the WIT changes under test to the WIT repo to the branch "route_fit". See https://github.com/PAIR-code/what-if-tool/tree/route_fix. I just made a fix and tested locally that WIT works with and without a path prefix in my local setup with this change. I attached an updated pip package for you to try again. Let me know if this new version solves the issue.
> 
> [tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip](https://github.com/tensorflow/tensorboard/files/7815350/tensorboard_plugin_wit-1.8.1-py3-none-any.whl.zip)
> 
> If you ever want to build your own version of the WIT plugin pip package, see setup instructions for building WIT at https://github.com/PAIR-code/what-if-tool/blob/route_fix/DEVELOPMENT.md and then run `bazel run tensorboard_plugin_wit/pip_package:build_pip_package` and find the package created in `/tmp/wit-pip/release/dist` directory.

@jameswex thanks for the prompt reply, now I have confirmed that this version works for me. Thanks.

**Comment by jameswex** [comment]
Thanks @hsinhoyeh ! I have released new package version https://pypi.org/project/tensorboard-plugin-wit/1.8.1/ so you should be able to install that from pypi and see the fix without my temporary pip package I included in this bug.
