### ISSUE TITLE
Scalars dashboard should hide tags with no selected runs

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#55]
MIgrated from https://github.com/tensorflow/tensorflow/issues/7720.

@cancan101 says:

> The list of metrics for for plotting on the scalars tab is cluttered with a number of metrics that don't exist for the selected runs. Why not [hide] these rather than taking up real estate?

**Comment by phisad** [comment]
This would be a really helpful feature! In the meantime, is there a workaround regex to have this done?

**Comment by nfelt** [comment]
Duplicate of #170

**Comment by nfelt** [comment]
I don't believe there's any regex-based workaround, but this issue is something we're actively investigating.

Also, I'm closing this as a duplicate of #170 since they are the same issue, and while this one was filed first, #170 has more overall discussion and context at this point.
