### ISSUE TITLE
Image step slider shows outdated data

### ISSUE THREAD

**Issue by dandelionmane** [tensorflow/tensorboard#550]
If you press "reload" in the TensorBoard UI, the image will reload but the step counter will stay the same, resulting in an inaccurate step count being displayed.

Reproduction:
Run a job that outputs image summaries at a fast rate.
Load the image tab, when a certain step is present (e.g. 1000).
Wait half a minute. Press reload. The image loader will show a new image (e.g. for step 2000). However, the slider will erroneously still display 1000. Dragging the slider to a different step and then back will cause it to correctly display 2000.

**Comment by chihuahua** [comment]
The audio dashboard interestingly does not exhibit this problem because `_currentDatum` depends on both `_steps` and `_stepIndex`.
https://github.com/tensorflow/tensorboard/blob/693c07c25f1498853e9f7a5b39402ff357babe98/tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html#L194
