### ISSUE TITLE
Invalid Argument Error on the second time model is fitted

### ISSUE THREAD

**Issue by DagonArises** [tensorflow/tensorboard#5540]
I have used a Tensorboard callback in fitting a model consisting of one embedding layer and one SimpleRNN layer. The model performs binary sentiment classification for 9600 input text sequences. They have been tokenised and padded in advance.
```
# 1. Remove previous logs
!rm -rf ./logs/
# 2. Change to Py_file_dir
os.chdir(...)

# input_dim = 43489 (size of tokenizer word dictionary); output_dim = 100 (GloVe 100d embeddings); input_length = 1403 (length of longest text sequence).
# xtr_pad is padded, tokenised text sequences. nrow = 9600, ncol = input_length = 1403. 

model= Sequential()
model.add(Embedding(input_dim, output_dim, input_length= input_length, 
                       weights= [Embedding_matrix], trainable= False))
model.add(SimpleRNN(200))
model.add(Dense(1, activation= 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer= 'adam', metrics=['accuracy'])
tb = TensorBoard(histogram_freq=1, log_dir= 'tbcallback_prac')
tr_results= model.fit(xtr_pad, ytr, epochs= 2, batch_size= 64, verbose= 1, 
                      validation_split= 0.2, callbacks= [tb])

# In command prompt enter: tensorboard --logdir tbcallback_prac
# Model summary:
Layer (type)                 Output Shape              Param #   
=================================================================
embedding_1 (Embedding)      (None, 1403, 100)         4348900   
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 200)               60200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
=================================================================
```
I have run this on Jupyterlab and on the first time the model trained without issue. I was also able to view the Tensorboard plots and histograms on a local host.
However when I run this same code to fit this model a second time, it completed the first epoch of training, but returned this error before the 2nd epoch begins.
```
Train on 7680 samples, validate on 1920 samples

Epoch 1/2
7680/7680 [==============================] - ETA: 0s - loss: 0.2919 - accuracy: 0.9004
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-a1cde9b5b1f4> in <module>()
      7 tb = TensorBoard(histogram_freq=1, log_dir= 'tbcallback_prac')
      8 tr_results= model.fit(xtr_pad, ytr, epochs= 2, batch_size= 64, verbose= 1, 
----> 9                       validation_split= 0.2, callbacks= [tb])

...
InvalidArgumentError: You must feed a value for placeholder tensor 'embedding_input' with dtype float and shape [?,1403]
     [[{{node embedding_input}}]]
```
The error points to the embedding layer input on the 2nd epoch. If I'm not wrong it refers to the embedding matrix of shape (43489, 1403). It has already been supplied in the 'weights' argument, what does it mean by 'must feed a value for placeholder tensor'?

I am able to train the model repeatedly when I remove the Tensorboard callback, as well as using other custom callbacks. 
This issue with Tensorboard callback persists when I fit feedforward NNs. 
Thanks in advance for any help.

**Comment by DagonArises** [comment]
Just want to add on a suspicion regarding my Jupyter kernel. The error occurred when the model fitting code with TB callback was run the second time on the same kernel. But if I restart the kernel it will again work for once, then raise the error on the second time.

The reason I mention Jupyter kernel is that, when I launch Jupyter Notebook from Anaconda on MacOS, it will open the command prompt automatically and display the following:
```
[I 11:55:56.638 NotebookApp] JupyterLab beta preview extension loaded from /Users/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 11:55:56.638 NotebookApp] JupyterLab application directory is /Users/anaconda3/share/jupyter/lab
[I 11:55:56.653 NotebookApp] Serving notebooks from local directory: /Users
[I 11:55:56.653 NotebookApp] 0 active kernels
[I 11:55:56.654 NotebookApp] The Jupyter Notebook is running at:
[I 11:55:56.654 NotebookApp] http://localhost:8889/?token=1c5345a63bc932e4ea79dba5ef599864f40c6b3ca71e632c
[I 11:55:56.654 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:55:56.655 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=1c5345a63bc932e4ea79dba5ef599864f40c6b3ca71e632c&token=1c5345a63bc932e4ea79dba5ef599864f40c6b3ca71e632c
[I 11:55:56.884 NotebookApp] Accepting one-time-token-authenticated connection from ::1
```
In the last line the command prompt is running the whole time, and I cannot pass and execute any command. Every time I have finished with my notebook I will need to manually terminate the command prompt. Due to this strange state of command prompt I cannot use Jupyter Notebook when using TB callback: I cannot execute the command to view the TB plots at all.

With Jupyterlab I am able to train with TB once, and execute the command to view TB results on localhost.

**Comment by japie1235813** [comment]
Overall I don't quite sure about the exact steps and states of your model training process vs running TB and Jupyter.  

From a higher level,  `tensorboard --logdir tbcallback_prac` command is used to run the TB and it reads the log located in `tbcallback_prac`. The model training continues writing log to the folder during the training progress and TB reads it to show the web visualization. 
On the other hand, Jupyter server is used to provide proxy, so more rational usage of it is not terminating it (or put it in background) and then after authorizing (access the token page) you should be able to see `http://localhost:8889/proxy/6006/` (or similar path depends which port you run your TB) (See [notebook tutorial](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks#setup))

Please provide info from the diagnose_tensorboard script but for this specific use and usage of TF1 we might not be able to spend time debugging it. We might also not be able to debug and reproduce this bug without a self-contained environment.

**Comment by DagonArises** [comment]
> Overall I don't quite sure about the exact steps and states of your model training process vs running TB and Jupyter.
> 
> From a higher level, `tensorboard --logdir tbcallback_prac` command is used to run the TB and it reads the log located in `tbcallback_prac`. The model training continues writing log to the folder during the training progress and TB reads it to show the web visualization. On the other hand, Jupyter server is used to provide proxy, so more rational usage of it is not terminating it (or put it in background) and then after authorizing (access the token page) you should be able to see `http://localhost:8889/proxy/6006/` (or similar path depends which port you run your TB) (See [notebook tutorial](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks#setup))
> 
> Please provide info from the diagnose_tensorboard script but for this specific use and usage of TF1 we might not be able to spend time debugging it. We might also not be able to debug and reproduce this bug without a self-contained environment.

```
from __future__ import print_function
import numpy as np
from numpy import array, asarray, zeros
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import tensorflow as tf
from keras import Input, Model
from keras.models import Sequential
from keras.layers.recurrent import LSTM, GRU,SimpleRNN
from keras.layers.core import Dense, Activation, Dropout, Flatten
from keras.layers.embeddings import Embedding
from tensorflow.keras.layers import BatchNormalization, PReLU
from keras.utils import np_utils
from sklearn import preprocessing, decomposition, model_selection, metrics, pipeline
from keras.layers import GlobalMaxPooling1D, Conv1D, MaxPooling1D, Flatten, Bidirectional, SpatialDropout1D
from keras.preprocessing import sequence, text
from keras.callbacks import EarlyStopping, LambdaCallback, TensorBoard

# Hyperas for hyperparameter selection
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from plotly import graph_objs as go
import plotly.express as px
import plotly.figure_factory as ff

from keras import backend as k
tf.compat.v1.disable_eager_execution()
import os 


def data_pp():
    train= pd.read_csv('/Users/jigsaw-toxic-comment-train.csv')
    train.drop(['severe_toxic','obscene','threat','insult','identity_hate'],axis=1,inplace=True)
    train= train.iloc[:12000,:]
    xtr, xte, ytr, yte= train_test_split(train['comment_text'].values, 
                                        train['toxic'].values,
                                        stratify= train['toxic'].values,
                                        random_state= 42, test_size= 0.2, shuffle= True)
    
    # Tokenise data
    tok= text.Tokenizer(num_words= None)
    tok.fit_on_texts(list(xtr)+ list(xte))
    input_dim= len(tok.word_index)+1
    input_length= train['comment_text'].apply(lambda x: len(str(x).split())).max()
    xtr_seq= tok.texts_to_sequences(xtr); xte_seq= tok.texts_to_sequences(xte)
    xtr_pad= sequence.pad_sequences(xtr_seq, maxlen= input_length)
    xte_pad= sequence.pad_sequences(xte_seq, maxlen= input_length)
    print('Shape of tokenised training input:', xtr_pad.shape)
    return xtr_pad, ytr, xte_pad, yte, input_dim, input_length, tok
    
xtr_pad, ytr, xte_pad, yte, input_dim, input_length, tok= data_pp()

def embed_mat(input_dim, output_dim, tok):
    '''By default output_dim = 100 for GloVe 100d embeddings'''
    embedding_dict=dict()
    f= open('/Users/GloVe/glove.6B.100d.txt')
    for line in f:
        values= line.split()
        word= values[0]; coefs= asarray(values[1:], dtype= 'float32')
        embedding_dict[word]= coefs
    f.close()
    Emat= zeros((input_dim, output_dim))
    for word, i in tok.word_index.items():
        embedding_vector= embedding_dict.get(word)
        if embedding_vector is not None:
            Emat[i]= embedding_vector
    print('Embedding weight matrix has shape:', Emat.shape)
    return Emat
output_dim = 100
Emat= embed_mat(input_dim, output_dim, took)

!rm -rf ./logs/
model= Sequential()
model.add(Embedding(input_dim, output_dim, input_length= input_length, 
                       weights= [Emat], trainable= False))
model.add(SimpleRNN(200))
model.add(Dense(1, activation= 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer= 'adam', metrics=['accuracy'])
tb = TensorBoard(histogram_freq=1, log_dir= 'tbcallback_prac')
tr_results= model.fit(xtr_pad, ytr, epochs= 2, batch_size= 64, verbose= 1, 
                      validation_split= 0.2, callbacks= [tb])


```

**Comment by DagonArises** [comment]
@japie1235813
It works when I remove this line: ```tf.compat.v1.disable_eager_execution()```
This issue has been raised here: https://github.com/tensorflow/tensorflow/issues/30094

**Comment by bileschi** [comment]
Looks like https://github.com/tensorflow/tensorflow/issues/30094 has been resolved.  Is this issue also resolved?  Please re-open if not.  Thanks!
