### ISSUE TITLE
Package license file

### ISSUE THREAD

**Issue by jakirkham** [tensorflow/tensorboard#556]
Please include the license file in the PyPI releases. This helps downstream distributors who need to pass the license file along to their users. Thanks.

**Comment by jart** [comment]
@jakirkham TensorBoard on [PyPi](https://pypi.python.org/pypi/tensorflow-tensorboard/0.1.8) now has license metadata, as of the [TensorBoard 0.1.8](https://github.com/tensorflow/tensorboard/releases/tag/0.1.8) issued today. There were a couple other issues I noticed with the pip package, which have also been addressed. You should be good to go now!
