### ISSUE TITLE
No `/device: TPU:x` When Runing TensorBoard

### ISSUE THREAD

**Issue by Danc2050** [tensorflow/tensorboard#5590]
## Environment information (required)
[diagnose_tensorboard.txt](https://github.com/tensorflow/tensorboard/files/8158602/diagnose_tensorboard.txt)
Chrome  Version: 98.0.4758.102

## Issue description

TensorBoard does not seem to show any TPU device, unlike it does with a GPU. Is this not supported? I ran this on my own code as well as a [public notebook](https://colab.research.google.com/github/google/jax/blob/main/docs/notebooks/quickstart.ipynb#scrollTo=xVgZlO10lBPc) with JAX (just adding in the JAX code to trace).

- Screenshot of issue:
![image](https://user-images.githubusercontent.com/32185616/156101096-533a4818-0de8-4a1e-b940-6107c339a622.png)

## Minimal Code Example
```
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()

key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

size = 3000

jax.profiler.start_trace("/tmp/tensorboard")
x = random.normal(key, (size, size), dtype=jnp.float32)
%timeit jnp.dot(x, x.T).block_until_ready()  # runs on the GPU, but I also think would use TPU as it's a matrix multiply

jax.profiler.stop_trace()

!pip3 install tensorflow tbp-nightly

# # Load the TensorBoard notebook extension.
%load_ext tensorboard

# Launch TensorBoard and navigate to the Profile tab to view performance profile
%tensorboard --logdir=/tmp/tensorboard
```

**Comment by yatbear** [comment]
Hi @Danc2050,

The profiler plugin is maintained by @tensorflow/profiler-team. Can you post an issue under https://github.com/tensorflow/profiler/issues? Thanks!

**Comment by Danc2050** [comment]
Hi @yatbear , I am sorry I was on the wrong tab. Thank you!
