### ISSUE TITLE
Tensorboard Graph vizualisation crashes with Chrome/Safari

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tensorboard#56]
Migrating https://github.com/tensorflow/tensorflow/issues/9681

> ### Describe the problem
> I'm running Tensorboard on a server and visualizing the graph on my local machine.
> 
> With the attached file that I generated using a custom script, Tensorboard crashes after a while of just moving the graph around or when I try to remove some modules from the main graph (100% crash after 4 modules removed).
> 
> More specifically:
> - In Safari only the browser freezes but I can still close it.
> - In Chrome the browser freezes and then the whole OS, I don't even have haptic feedback anymore. On the otherhand Tensorboard is still running on the server and the Tensorboard webpage can be accessed by other computers.
> 
> 
> ### Source code / logs
> Here is the log-file containing just the graph that reproduces this issue 100% time on my end.
> [events.out.tfevents.1493971052.c941b31be93a.zip](https://github.com/tensorflow/tensorflow/files/978532/events.out.tfevents.1493971052.c941b31be93a.zip)
>

**Comment by stephanwlee** [comment]
Just tried it with TB 1.11 and I couldn't reproduce this on:
- Chrome: 69.0.3497.100 
- Safari: 12.0
- Firefox: 60
