### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by YantingHuang** [tensorflow/tensorboard#563]
I cannot see anything although I found the following information in the inspection mode.
<img width="915" alt="screen shot 2017-09-24 at 10 29 59 pm" src="https://user-images.githubusercontent.com/22687901/30790114-01684058-a178-11e7-95a0-253ae5eb01f6.png">

Attached are two events files.
[train.zip](https://github.com/tensorflow/tensorboard/files/1328074/train.zip)

Thanks!

**Comment by chihuahua** [comment]
I can see your data after starting TensorBoard with `tensorboard --logdir ~/Downloads/train`.

![3ttmp35jvsf](https://user-images.githubusercontent.com/4221553/30790788-20e6afa6-a17c-11e7-831d-1cd3c7caf994.png)

What is your logdir argument? If you try `ls [logdir]`, are the files listed?

**Comment by chihuahua** [comment]
Yeah, I see the histograms as well ...

![1ydcoos8flj](https://user-images.githubusercontent.com/4221553/30790818-6868024e-a17c-11e7-8314-e53f1fa8ae6b.png)

**Comment by YantingHuang** [comment]
Sorry I did not upload the exact directory structure I have, please help me debug this one:
[run-Lupus Erythematosus, Systemic.zip](https://github.com/tensorflow/tensorboard/files/1330206/run-Lupus.Erythematosus.Systemic.zip)

The command I run tensorboard is:
<img width="749" alt="screen shot 2017-09-25 at 12 52 51 pm" src="https://user-images.githubusercontent.com/22687901/30820637-7ee99964-a1f0-11e7-876a-974976342a09.png">

When I use inspect mode again:
<img width="883" alt="screen shot 2017-09-25 at 12 54 36 pm" src="https://user-images.githubusercontent.com/22687901/30820699-b5f2a77a-a1f0-11e7-932c-99d37ccbeeb5.png">

When I open the event file using tensorboard, I see:
<img width="1269" alt="screen shot 2017-09-25 at 12 55 21 pm" src="https://user-images.githubusercontent.com/22687901/30820733-cfb4b16c-a1f0-11e7-9369-6e6b0a33c2fa.png">

Thanks again for helping me.

Yanting

**Comment by chihuahua** [comment]
If I `cd` into the directory and run `tensorboard --logdir .`, I can start TensorBoard and see the data. However, running `tensorboard --logdir run-Lupus\ Erythematosus,\ Systemic` from the parent directory does not work.

**Comment by YantingHuang** [comment]
Thanks. But is tensorboard supposed to walk through the recursive directory structure to find event files?

**Comment by chihuahua** [comment]
Commas in the `logdir` flag value separate different specifications for TensorBoard: 
https://github.com/tensorflow/tensorboard/blob/d130cff3f26551fd0a9e91a3e05b81b203833c7c/tensorboard/backend/application.py#L284

so TensorBoard's reading your logdir as 2 different specs:
`/Users/chizeng/Downloads/run-Lupus Erythematosus` and `Systemic/`

Could you perchance avoid using the comma?

**Comment by YantingHuang** [comment]
Thank for the help so much. 
I will avoid use comma in the future.
