### ISSUE TITLE
TensorBoard Dev doesn't update upon delete operation

### ISSUE THREAD

**Issue by de-gozaru** [tensorflow/tensorboard#5635]
## Issue description
Hi,

I'm using TensorBoard dev to log my training metrics. My TensorBoard version is `2.8.0`.

I log my data using the command
```bash
tensorboard dev upload --logdir=my/dir/of/logs
```

However, I noticed that once a version is created, and is apparent on TensorBoard dev, even if I delete it locally, it still exist on the online version. This behavior doesn't happen with local TensorBoard.

Is this behavior expected? is there a way to correct this?

Thank you in advance.

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='chris1', release='4.18.0-305.40.2.el8_4.x86_64', version='#1 SMP Tue Mar 8 14:29:54 EST 2022', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.8.0
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.8.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "pathh/diagnose_tensorboard.py", line 522, in main
    suggestions.extend(check())
  File "pathh/diagnose_tensorboard.py", line 75, in wrapper
    result = fn()
  File "pathh/diagnose_tensorboard.py", line 278, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: '/my_path/pytorch-gpu-1.10.1+py3.9.7/lib/python3.9/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/my_path/pytorch-gpu-1.10.1+py3.9.7/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'url'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/my_path/pytorch-gpu-1.10.1+py3.9.7/lib/python3.9/site-packages']; bad_roots (0): []



</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

**Comment by bileschi** [comment]
TensorBoard.dev uploads your data to a remote service.  In order to delete from the remote service you should use the tensorboard dev delete command.

`tensorboard dev delete --experiment_id EXPERIMENT_ID`

**Comment by de-gozaru** [comment]
Hi @bileschi 

Thank for your response.

So if I understand correctly, this cannot be done automatically, I should manually stop listening to my log directory, then use the command to delete experiment, and then start listening again, which will open Tensorboard in a new URL, is this correct?

**Comment by bileschi** [comment]
Perhaps I don't understand your workflow.   I thought you were looking to delete the entire experiment.  Are you looking instead to delete / replace individual runs within the experiment?

If so, yes, TensorBoard.dev does not support the deletion of individual sub-artifacts within an experiment.

**Comment by de-gozaru** [comment]
Hi @bileschi 

Yes, my workflow is the following. I'm doing multiple experiments, and I put artifacts of each experiment in a separate folder. Sometimes, some experiments fail but their respective folder is created and it appears on tensorboard dev, even if it doesn't contain important information. So what I do is that I just remove these folders locally, and I want this change to be reflected on tensorboard dev, as it is the case now for local server tensorboard.

I hope I explained myself clearly.

**Comment by bileschi** [comment]
Yes, unfortunately TensorBoard.dev does not support the deletion of individual subfolders from within a logdir.

The only supported delete operations are to delete the full logdir ("Experiment" in TB terminology), or the user, which will trigger the deletion of all of the users's experiments in cascade.

https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/uploader/proto/write_service.proto;l=88?ss=tensorflow%2Ftensorboard&q=delete

**Comment by de-gozaru** [comment]
Hi @bileschi 

Thanks for your response.

Should I consider this issue cannot be solved and close the issue?

**Comment by bileschi** [comment]
Lets close this issue and open a Feature Request for deletion within an experiment.  Sound good?  Should I open the FR or would you like to?

**Comment by bileschi** [comment]
I'll open it and link to here:
PTAL https://github.com/tensorflow/tensorboard/issues/5643
