### ISSUE TITLE
TensorBoard.dev does not support the deletion of individual runs within an experiment.

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tensorboard#5643]
As a user, sometimes I add provisional directories under my logdir.  Sometimes those provisional explorations don't work out, for one reason or another.  When I navigate to TensorBoard.dev, I those unwanted runs clutter my view and it is annoying or distracting.   I would like some way to suppress or delete those runs.

**Comment by mluerig** [comment]
have there been any updates on this request?

**Comment by bileschi** [comment]
This bug is against TensorBoard.dev - it should probably be closed.  Is your question about OSS standalone TensorBoard?

**Comment by mluerig** [comment]
standalone yes

**Comment by bileschi** [comment]
For standalone TB, can you use the advice here instead?
https://github.com/tensorflow/tensorboard/issues/5438

**Comment by bileschi** [comment]
Closing this bug as TensorBoard.dev focused.
