### ISSUE TITLE
How to change the tensorboard UI colors

### ISSUE THREAD

**Issue by JihadAlAKl** [tensorflow/tensorboard#5645]
Hi, 
Is it possible to change the UI colors of the tensorboard from orange to other colors by changing some config file or parameter?

**Comment by ericdnielsen** [comment]
If you're building from source you an set the colors here: tensorboard/webapp/theme/_variable.scss

**Comment by JihadAlAKl** [comment]
> tensorboard/webapp/theme/_variable.scss

Can I change colors without building the project? (without modifying source code)

**Comment by bmd3k** [comment]
unfortunately you can't change colors without modifying the source. It's not something we plan to support.
