### ISSUE TITLE
Tensorboard dev for open3d 

### ISSUE THREAD

**Issue by chucktang98** [tensorflow/tensorboard#5646]
Would be super cool if we could add support for open3d tensorboard modules in tensorboard dev. http://www.open3d.org/html/tutorial/visualization/tensorboard_plugin.html Would love to upload some 3D plots from open3d through tensorboard dev

**Comment by ericdnielsen** [comment]
We're not currently adding new plugins to TensorBoard.dev, but that's definitely a cool plugin.

**Comment by chucktang98** [comment]
Thanks :-)
