### ISSUE TITLE
Performance of tensorboard summary writer with s3 path

### ISSUE THREAD

**Issue by ThyrixYang** [tensorflow/tensorboard#5655]
Hi,

I'm trying to use tensorboard with Minio Object storage (with a s3 path).
And I noticed that at the beginning it worked fine.
However, as the epochs go on, the summary writer begins to slow down and I notice that the network bandwidth usage becomes higher and higher (at the beginning only 2Mb, after 12 hours the bandwidth usage became 500Mb, which reaches the limit of my network (1000Mb) and training became much slower).

I guess tensorboard is pulling down the object, modifying it, then pushing up to the s3 server, so that the bandwidth usage increases as the file size increase?
Is there any better way to avoid this?

**Comment by ericdnielsen** [comment]
After a big more digging: quadratic behavior is expected and unavoidable for append-only filesystems, which most cloud filesystems (including S3 and GCS) are

well, unavoidable in the context of "writing to a single file many times and wanting intermediate results to appear"
