### ISSUE TITLE
why not set DEFAULT_TENSOR_SIZE_GUIDANCE bigger by defalut?

### ISSUE THREAD

**Issue by Owen-Fish** [tensorflow/tensorboard#5707]
When I use tensorboard to display expriment result. I found only **ten images** show through all my logs. I kown this can be changed by specified --samples_per_plugin. I just wondering why set "DEFAULT_TENSOR_SIZE_GUIDANCE.image_metadata.PLUGIN_NAME: 10".
 I guess for the reason of memory cost? @bmd3k

**Comment by nfelt** [comment]
The tradeoff is memory usage, like you said. We need to strike a balance between trying to show some useful data, but not buffering so much data in RAM that memory usage is prohibitive for users with very high numbers of image time series.

Long term we might be able to do something more dynamic (like sample more images if there aren't very many overall time series of images) or that avoids as much memory usage (like fetching images from disk when needed for display without buffering them in RAM), but that behavior would also be more complicated.

Our recommendation for now is just to set `--samples_per_plugin`, so closing this for now. If you have a specific feature request (e.g. for one of the above behaviors), you could open a new issue or we can edit and re-open this one.
