### ISSUE TITLE
Can I upload tensorboard log files to my server just like tensorboard.dev?

### ISSUE THREAD

**Issue by unanan** [tensorflow/tensorboard#5753]
Hi, all!
Can I upload the log files to my server just like tensorboard.dev ?
I found there are some features implemented are not in the official docs.

https://github.com/tensorflow/tensorboard/tree/master/tensorboard/uploader

**Comment by bmd3k** [comment]
Hello. As you discovered, the uploader code is for uploading to TensorBoard.dev. We don't offer a generic "upload" utility.
