### ISSUE TITLE
GitHub: Please "create TAG 2.9.1" to match the released version of 2.9.1 available on PyPi and ....

### ISSUE THREAD

**Issue by scottc21** [tensorflow/tensorboard#5756]
## GitHub source labeling issue --- Please "create TAG 2.9.1" to match the released version of 2.9.1 available on PyPi and ....

The TensorBoard 2.9.1 build has been released and is currently available on PyPi at the URL below for a few days.
ISSUE/Fix:    Please add a "2.9.1" label to the git repo to correspond to the released version of TensorBoard 2.9.1  

- Released   TensorBoard 2.9.1 PyPi  url  -----   https://pypi.org/project/tensorboard/2.9.1/    (  Date:  Released: Jun 8, 2022  )
- TensorBoard 2.9 branch url  ----   https://github.com/tensorflow/tensorboard/tree/2.9    ( no 2.9.1 label found -- anywhere or on this 2.9 branch)

Thanks for your efforts on this project.  Much appreciated ....

**Comment by bmd3k** [comment]
Thanks for the reminder. Done now.

https://github.com/tensorflow/tensorboard/releases/tag/2.9.1
