### ISSUE TITLE
LICENSE != LICENSE.tensorflow

### ISSUE THREAD

**Issue by Anselmoo** [tensorflow/tensorboard#5810]
According to:
https://github.com/tensorflow/tensorboard/tree/2ad71eabe995758221897301104a271aea3b0d59/tensorboard/pip_package

the `LICENSE` file is named  `LICENSE.tensorflow`

https://github.com/tensorflow/tensorboard/blob/2ad71eabe995758221897301104a271aea3b0d59/tensorboard/pip_package/build_pip_package.sh#L75

This might be to check?

**Comment by bileschi** [comment]
Hello @Anselmoo .  Thanks for your contribution, but `LICENSE` is a different file, built from `LICENSE.tensorflow` as part of the build process.  You can see that in https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/pip_package/BUILD;l=28 the `build_pip_package` target has a data dependency on `LICENSE`, which is a named output of the genrule target `license`.  That target constructs `LICENSE` from `LICENSE.tensorflow` and a number of other sources.

https://docs.bazel.build/versions/main/be/shell.html#sh_library for more information on the Bazel build system.  Closing this bug and the associated PR.
