### ISSUE TITLE
license_file should become  license_files instead

### ISSUE THREAD

**Issue by Anselmoo** [tensorflow/tensorboard#5812]
https://github.com/tensorflow/tensorboard/blob/2ad71eabe995758221897301104a271aea3b0d59/tensorboard/pip_package/setup.cfg#L3

**Comment by Anselmoo** [comment]
> Sorry - can you explain _why_ `license_file` should be `license_files`
> 
> It appears that `license_file` [is a supported alias](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html). Is there a compelling reason to move? Is this likely to break at some future point?
> 
> Thanks!

@bileschi thx for your feedback.

So, it looks like that `license_file ` will be removed in the future. 
First, I saw it if I locally installed it. According to the latest version of `setupcfg.py`, it's also mentioned. Consequently, I thought it make sense to consider changing it for maintenance reasons.

https://github.com/pypa/setuptools/blob/main/setuptools/config/setupcfg.py

<img width="678" alt="image" src="https://user-images.githubusercontent.com/13209783/180061285-fc417523-740e-4a3f-b454-94924ee3f3c7.png">

**Comment by bileschi** [comment]
Seems reasonable to me.  Triggering CI on #5813
