### ISSUE TITLE
tensorboard read data from gs with application default credentials

### ISSUE THREAD

**Issue by osayes** [tensorflow/tensorboard#5819]
tensorbaord with version 2.3 2.4, work correctly
start from version 2.5, it doesn't seem to use the application default credentials, and warning:

WARN  rustboard_core::gcs::auth] GCS authentication failed: error sending request for url (https://www.googleapis.com/oauth2/v3/token): operation timed out
...

 when add --load_fast=false, it seems to work again

platform: ubuntu 20.04
tensorflow: 2.9.1
python: 3.9.7

**Comment by qihach64** [comment]
Hi Osayes, 

[tensorboard 2.5.0](https://github.com/tensorflow/tensorboard/releases/tag/2.5.0) is when we turned on "rustboard" by default. This is the super fast data loader written in rust. It looks like application default credentials failed for rustboard but succeeded when that's disabled.

The [feedback bug](https://github.com/tensorflow/tensorboard/issues/4784), however, mentioned that

> GCS logdirs are supported. Private GCS logdirs are supported if you
authenticate via an OAuth refresh token, as generated by
gcloud auth application-default login. Authentication via service
account keys may not work.

so application default login should work for rustboard 🤔 ...

Would you mind running [diagnose_tensorboard.py](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/tools/diagnose_tensorboard.py) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output in this issue for further diagnose ? Also could you send the command that you were running that triggers the auth failure issue and perhaps share access to the gcs bucket with us so we can try reproduce the failure ? thx!

**Comment by osayes** [comment]
thanks for your answer, and I'm sorry I can't run the diganose code now because of my disconnect to gcp
maybe somday in the future I'll go on

**Comment by bmd3k** [comment]
Thanks @osayes for the report. Feel free to reopen if you have the opportunity to collect more information for us.

**Comment by soichisumi** [comment]
Hello. I am also facing this problem and will try to gather information if possible.
Do I just run the tensorboard binary and diagnosis.py on the same environment?

**Comment by soichisumi** [comment]
I created a new Issue because I did not have permission to Reopen it
