### ISSUE TITLE
Tooltip sorting by "nearest" is broken in Time Series dashboard

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorboard#5854]
Moving the cursor to the top region of the plot should show all methods sorted from highest score to lowest score. Similartly, moving the cursor to the bottom should sort them from lowest to highest. For some X positions of the mouse cursor, this works but for most positions the tooltip is sorted incorrectly (or not sorted at all?). On the other hand, it works perfectly in the Scalars dashboard. This is using the newest internal version of TensorBoard running on Borg.

![image](https://user-images.githubusercontent.com/2111293/183722869-1e728fa2-18f2-4950-b6e8-3ae77848c1e8.png)

**Comment by danijar** [comment]
Another example, where the first two largest values are on top but the other ones are incorrectly sorted:

![image](https://user-images.githubusercontent.com/2111293/183724091-fbfa2df2-c89a-4782-a0ff-6a1a94cb8cee.png)

**Comment by yatbear** [comment]
Hi @danijar,

The nearest sorting sorts the runs by the Euclidean distance to the cursor which in this case would be the squared root of `(run.step - cursor.x)^2 + (run.value - cursor.y)^2`. Given the step is quite large (in this case the `x`), I can see how this skews the results, at the first glance for the first screenshot you attached, it looked like the cursor is around (510k, 990), and if we roughly compare the distance of this cursor to the first (navy) point p1 (665824, 4), and the fourth (orange) point p2 (668456, 741.1):
```
dist_p1 = ((665824 - 510000)**2 + (4 - 990)**2)**0.5 = 155827
dist_p2 = ((668456 - 510000)**2 + (741.1 - 990)**2)**0.5 = 158456
```
The navy point is considered closer to the cursor than the orange point.

If you want to sort solely by `y` value (or `score` in your experiment), you can use the `Ascending` and `Descending` sorting methods instead.

**Comment by bileschi** [comment]
Hi @danijar  -  in your opinion would it be better if "Nearest" only took into account the y-axis differential and ignored the x-axis differential?

**Comment by bileschi** [comment]
@yatbear points to this as being the responsible line: https://source.corp.google.com/piper///depot/google3/third_party/tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts;l=190

**Comment by bileschi** [comment]
@yatbear points to this being the culprit line: 

https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts;l=190;drc=985e3abdbed492faf23b982d1bcaedd636957ec1

**Comment by danijar** [comment]
Good catch! Yes, going only by X-axis would be better and resolve this issue. It could also go by Euclidean distance on the rendered graph (i.e. pixel distance) but I don't think that's necessary.

The problem with the ascending and descending sorting methods is that you have to keep switching between them depending on which plot you look at (for some metrics higher is better, for others lower) and how you want to read it (see the best or worst runs). So in practice I find "Nearest" to be the only useful setting.

**Comment by yatbear** [comment]
Thanks @danijar for the feedback!

**Comment by danijar** [comment]
Hi TB team, could you please prioritize this issue?

I think computing distance only based on the Y axis might not work if different runs report scores at different X values. Instead, I think the solution is to compute visual euclidean distance. In other words, rescale X and Y values based on the chart's xlim and ylim before computing euclidean distance.

**Comment by danijar** [comment]
I think there is possibly a second bug in the tooltip sorting. In this example here, it should effectively only go based on the y-distance because the x-distance is very large by comparison. Yet, it doesn't show the three largest numbers at the top:

![image](https://user-images.githubusercontent.com/2111293/202773826-9653eb87-76c5-4c68-8794-c9ac571ee303.png)

**Comment by yatbear** [comment]
Hi @danijar 

The `Nearest` (now renamed to `Nearest Pixel`) sorting method is now fixed based on pixel distance, and a new method `Nearest Y` is added. Thanks @rileyajones for the feature!

**Comment by danijar** [comment]
Awesome, thanks!
