### ISSUE TITLE
Exporting Embeddings (PCA/tSNE) projections as 3D model files

### ISSUE THREAD

**Issue by demiahmed** [tensorflow/tensorboard#5960]
Hi I'm wondering if its possible to export the tSNE visualisation embedding in tensorboard UI into a 3D model format (with image sprites).

From simple inspection I noticed it was an html ```canvas``` element with pan and zoom for the images but is there a way where I can export the entire scene as a model?

Any leads would be appreciated
Thanks

**Comment by bmd3k** [comment]
Hi @demiahmed. Unfortunately I do not believe we have a systematic way of exporting to a 3D model format.
