### ISSUE TITLE
Change the name of each trial

### ISSUE THREAD

**Issue by VladimirVisnovsky** [tensorflow/tensorboard#5980]
Hi, I can't find any information about the possibility of changing the specific name for each trial. What I get is "00/execution0", "01/execution0" etc. As I am using the TensorBoard for the tuning of hyperparameters, I think it would be useful to have parameters as a tag for each run.

For example: "00/bs256_lay3_neur50" for 0th trial with batch size 256, 3 layers and 50 neurons in each layer. Or maybe is there some other prettier way of doing such naming?
![image](https://user-images.githubusercontent.com/80093856/196010282-2c9664e8-00cd-4463-a210-068928685a6c.png)

**Comment by nfelt** [comment]
Hi - these names come directly from the directory structure of the log directory on disk (which itself comes from how the summary writer that created the event files was configured). To achieve what you described, you'd want to name the directory using the desired trial name.

**Comment by groszewn** [comment]
Closing this issue. Feel free to reopen if you have any follow ups!
