### ISSUE TITLE
localhost if may be supported>>>

### ISSUE THREAD

**Issue by 1kaiser** [tensorflow/tensorboard#5996]
(https://github.com/1kaiser/nerfstudio_GoogleColab/blob/main/nerfstudio.ipynb) >>> reequirelocal host availiability >>> is therealternative to docker installation rather usimg browser tpo pass localhost  for visualization >>>

**Comment by yatbear** [comment]
Hi @1kaiser,

We recently added a Dockerfile to better support development using docker, please follow the instructions here: https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md#development-using-docker
