### ISSUE TITLE
[TensorBoard] Charts in TensorBoard in Safari don't display correctly

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#60]
Scalars charts in TensorBoard do not work for macOS Sierra, latest Safari (Version 10.0.1).

This issue had been migrated from tensorflow/tensorflow#6108.

**Comment by episodeyang** [comment]
@chihuahua is this still an issue? I think now this is fixed.

**Comment by psybuzz** [comment]
Closing as the issue is no longer reproducible.
Manually opened https://tensorboard.dev/experiment/EDZb7XgKSBKo6Gznh3i8hg/#scalars in Safari 14.0.2 on Mac OS 11.1.
