### ISSUE TITLE
--samples_per_plugin==audios=20 is not working

### ISSUE THREAD

**Issue by mraj96** [tensorflow/tensorboard#6062]
## Environment information (required)

it is  a GPU system with 64 GB RAM

## Issue description
I was saving output audio to tensorboard for 100 steps. i want to output audio at 20 intervals. I tried the below command, but not working. for audio, it is only showing 10 intervals of audio. 

`--samples_per_plugin==audios=20` is not working

Could you please help with this?

Thanks

**Comment by bmd3k** [comment]
I notice you are specifying 'audios' instead of 'audio'. I verified with TensorBoard 2.11.0 that 
`--samples_per_plugin=audio=20` works.
