### ISSUE TITLE
Error! is not UTF-8

### ISSUE THREAD

**Issue by jayboynana** [tensorflow/tensorboard#6148]
[](url)
![image](https://user-images.githubusercontent.com/87591547/212533760-222495dd-ad20-45f7-817b-4b4fde3d923d.png)
![image](https://user-images.githubusercontent.com/87591547/212533877-e8dd73ba-9d0c-4675-bee3-5ddf3b049536.png)

i am new.
I finished the training,but before i want to use tensorboard, the log is error in code.
Can it change automatically to UTF-8 everytime？

**Comment by groszewn** [comment]
Can you clarify if this error is happening when writing the event file or reading from it (I'm assuming the latter).

Can you also share your event file so I can try and reproduce on my end.
