### ISSUE TITLE
Mesh plugin - _serve_mesh_metadata returns json_config of step 0 for all steps

### ISSUE THREAD

**Issue by grialx** [tensorflow/tensorboard#6149]
The response of meshes?tag=tag&run=run&sample=0 is a list of jsons, one json for each step.
It contains among other things "config". The problem is that it is the same for all steps. It is the config of step 0.

**Comment by groszewn** [comment]
Hi there, thanks for raising this.

This is actually working as intended as only the first instance of metadata for a given tag is retained (see [here](https://github.com/tensorflow/tensorboard/blob/cd25871160d78e1034d87587fcb09875eb0e14d8/tensorboard/backend/event_processing/plugin_event_accumulator.py#L417-L422)). This isn't well documented right now, so I'll try and find a place in our documentation to make this more clear.

The mesh plugin documentation calls this out in the [Scene Configuration section](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/mesh#scene-configuration)
> Keep in mind that scene configuration is not a trainable variable (i.e., it is a static attribute) and is fixed at summary-creation time.

**Comment by grialx** [comment]
Ok, thanks for the quick response. I see, it is an intended behaviour. IMHO  is still a bit counterintuitive that you can write the summary including config at every step, but at the end only the first one is retained.

**Comment by groszewn** [comment]
Agreed that this can be a bit counterintuitive. It seems like what you're looking for would be "per-step metadata" (since the current SummaryMetadata effectively gets stored per-tag instead), which does not currently exist in TensorBoard. Feel free to open a feature request for such a thing so we can track the request appropriately.

**Comment by grialx** [comment]
Not sure how to open a feature request. Would it be just another issue, where I state the requested features?

**Comment by groszewn** [comment]
Yes, you can use [this link](https://github.com/tensorflow/tensorboard/issues/new?assignees=&labels=&template=feature_request.md&title=) which should use our feature request template.
