### ISSUE TITLE
Installing tensorboard with tensorflow 2.11

### ISSUE THREAD

**Issue by iago-pssjd** [tensorflow/tensorboard#6177]
I have installed tensorflow2.11 and I am trying to install tensorboard, but I have a problem with dependencies, since
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
tensorflow-cpu 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
tensorboard 2.11.2 requires protobuf<4,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
```
I know this was solved in commit https://github.com/tensorflow/tensorboard/commit/78f97c28273f3909a69c0b9f36ffcc2d0130ca48, but while a new version is not released, how may I do?
I tried installing `protobuf==3.19.6` and then
```
pip install git+https://github.com/tensorflow/tensorboard.git#egg=tensorboard
```
but I obtain
```
error: Multiple top-level packages discovered in a flat-layout: ['patches', 'third_party', 'tensorboard'].
```
so, how should I install the dev version from github, or which other alternative I have? (I also saw, the last tensorboard version which allows protobuf 3.19.6 is tensorboard 2.8, in that case should I downgrade tensorflow other packages to version 2.8?)

Thanks!

**Comment by bileschi** [comment]
A few options:

Is it possible to work with the nightly pip release version (https://pypi.org/project/tb-nightly/#history) ?

Is it possible to build TensorBoard from head and work from that?

Is it possible to let TensorBoard live in a separate virtual env from your TensorFlow install?  As you've noticed we've had a tricky dependency juggle recently over protobuf, and it's hard to categorize which versions of TensorBoard will work with which versions of TensorFlow.

**Comment by iago-pssjd** [comment]
> Is it possible to work with the nightly pip release version (https://pypi.org/project/tb-nightly/#history) ?

Thanks! I tried, but it seems it will end installing version 2.8 and old versions of different packages and ...

> As you've noticed we've had a tricky dependency juggle recently over protobuf, and it's hard to categorize which versions of TensorBoard will work with which versions of TensorFlow.

Yes, but not only you, the whole pip-Python ecosystem... Now, I got my final goal avoiding new pip installations, so I will close this issue, as it's just a question. I hope a future TF12+ will allow a consistent installation at least of the TF-related packages.

Thanks again!
