### ISSUE TITLE
Upgrade rsa to 4.7

### ISSUE THREAD

**Issue by kshama-msft** [tensorflow/tensorboard#6179]
Google-auth has rsa as a dependency. Python-rsa is vulnerable to Bleichenbacher timing attacks. Is it possible to upgrade rsa from 4.5 to 4.7 to handle this security vulnerability?

**Comment by arcra** [comment]
Hi,

I don't think we have any direct dependency on rsa library (see our [pip dependencies](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/pip_package/requirements.txt)).

As you can see there, we also support `google-auth` versions < 3, and their most recent version is [2.16.0](https://pypi.org/project/google-auth/).

`google-auth` also seems to have a [version restriction allowing `rsa` versions < 5](https://github.com/googleapis/google-auth-library-python/blob/main/setup.py#L28) (assuming you're using python >= 3.6).

So I believe you should be able to upgrade your own environment, probably with a command like `pip install --upgrade rsa`.

You could consider opening an issue with `google-auth` maintainers, to restrict the version to be higher than the vulnerable version, but that's outside of our scope.
