### ISSUE TITLE
TwinY plot using TensorBoard

### ISSUE THREAD

**Issue by aheba** [tensorflow/tensorboard#6214]
Hello,
I would like to know if there is a solution to have a solution like https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.twinx.html#matplotlib.axes.Axes.twinx
in tensorboard;

The idea is to have multiple axis X for the same plot, something like `num_samples` and `Nb_Hours` for the same fig.

**Comment by bmd3k** [comment]
Hi @aheba . Unfortunately there is not any way to have multiple x or y axes on the same plot.
