### ISSUE TITLE
Performance issue in tensorboard/plugins/graph/graphs_demo.py

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/tensorboard#6219]
Hello! Our static bug checker has found a performance issue in tensorboard/plugins/graph/graphs_demo.py:  Python type argument  [`step`](https://github.com/tensorflow/tensorboard/blob/dad5f12098fa4766b9196a61bccf33700f07f089/tensorboard/plugins/graph/graphs_demo.py#L129) is passed to tf.function decorated function [`f`](https://github.com/tensorflow/tensorboard/blob/dad5f12098fa4766b9196a61bccf33700f07f089/tensorboard/plugins/graph/graphs_demo.py#L117) instead of tensors. As there is a [for loop](https://github.com/tensorflow/tensorboard/blob/dad5f12098fa4766b9196a61bccf33700f07f089/tensorboard/plugins/graph/graphs_demo.py#L125), every time the value changes, a new graph will be generated, and that can trigger tf.function retracing warning.

The same with [`g(step)`](https://github.com/tensorflow/tensorboard/blob/dad5f12098fa4766b9196a61bccf33700f07f089/tensorboard/plugins/graph/graphs_demo.py#L135).

Here is [the tensorflow document](https://tensorflow.google.cn/guide/function#pass_tensors_instead_of_python_literals) to support it.

Looking forward to your reply.

**Comment by DLPerf** [comment]
Since your `step` only ranges from 0 to 3, it should not matter much. Just in case it gets larger :)

**Comment by groszewn** [comment]
Thanks for the report. It's unlikely we'd update the demo code to make this an actual issue, but probably best to adhere to best practices nevertheless. I've drafted #6220 to resolve this.
