### ISSUE TITLE
Loading event files from `gs://` consumes too much RAM

### ISSUE THREAD

**Issue by Corwinpro** [tensorflow/tensorboard#6248]
## Environment information (required)

This issue is not related to python and can be reproduced without `tensorflow` installation. This is only related to the `rustboard`.

I am running this on Ubuntu 20.04, 16Gb RAM machine, latest `apt` updates installed.

## Issue description

Summary: running `rustboard` on a google cloud storage `logdir` (`gs://...`) with a large number of tf events files consumes an unreasonable amount of memory (around 2Gb of RAM for <0.1Mb of events files). Running the same command for the same data stored locally behaves as expected (barely uses any RAM).

Prepare everything to run `rustboard`:
- Get the latest master,
- `cargo build`
- `RUST_LOG=debug cargo run -- --logdir PATH_TO_LOGS` should be running fine (see about `PATH_TO_LOGS` below)

Prepare dummy event files:

- I created a large number of dummy `events.out.tfevents` files. The problem was initially observed in a production scenario with a large number of real event files, but I reckon the actual data is not relevant, as I can reproduce the problem even with tiny events files.
- I attach the dummy files I used to reproduce the problem below

[tb-load-gcs-debug.zip](https://github.com/tensorflow/tensorboard/files/11008946/tb-load-gcs-debug.zip)

Reproducing the issue

- **baseline**: run `RUST_LOG=debug cargo run -- --logdir PATH_TO_LOGS` with `PATH_TO_LOGS` being a _local_ path to the folder with all event files. The memory consumption of this is tiny, as expected.
- **problem**: run `RUST_LOG=debug cargo run -- --logdir PATH_TO_LOGS` with `PATH_TO_LOGS` being a `gs://` location of the same event files but uploaded to the Google Cloud Storage. The memory footprint of this action for the files that I attach is ~2Gb!

### Notes

This is related to the behaviour discussed in https://github.com/tensorflow/tensorboard/issues/5958#issuecomment-1284771435 (and the solution proposed by the tensorboard team)

I could not reproduce this by running `rustboard` against the dev benchmarks, such as `gs://tensorboard-bench-logs`. How many tf event files are there? Not that many I guess.

**Comment by Corwinpro** [comment]
Investigation:

1. I checked if it is the reading from the google storage that is the problem. I replaced this

https://github.com/tensorflow/tensorboard/blob/1a2937ceac53b3ba2f36d264a6201f3d6d310e1e/tensorboard/data/server/gcs/logdir.rs#L60-L61

with

```rust
fn read(...) -> ... {
    return Ok(0);
}
```

but the problem still appears.

**Comment by yatbear** [comment]
Looking at the blame history of this file - https://github.com/tensorflow/tensorboard/pull/4646#discussion_r573151504, another option is to make this a tunable env var like `GCS_READ_CACHE_BLOCK_SIZE_MB` for TensorFlow (suggested by @nfelt).

**Comment by yatbear** [comment]
Hi @Corwinpro,

Thanks for checking with us! I think adding the `evn var` is fine, especially since this would be consistent with how TF manages the buffer. To your first question - yes that is my understanding as well, in this case having two rustboard related flags with one depending on the other (ignore buffer capacity when load_fast isn't on) can be a bit confusing for users, therefore the second approach is more straightforward.

**Comment by yatbear** [comment]
Thanks @Corwinpro for the PR and @groszewn for the review! Closing this issue, please reopen if you have any questions.
