### ISSUE TITLE
Optimize the /data/plugins_listing response.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#625]
TensorBoard only renders dashboards after it determines which ones are active. To do the latter, TensorBoard issues a request to the `/data/plugins_listing` endpoint.
https://github.com/tensorflow/tensorboard/blob/bb57d4c22abc487c281d688c23d39b6f2c4f4ce5/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L717

Hence, the `/data/plugins_listing` endpoint must return quickly - any time we shave off of the response time maps directly to time reduced for loading TensorBoard.

The server logic for that endpoint serially calls the `is_active` method for all plugins (active or not):
https://github.com/tensorflow/tensorboard/blob/bb57d4c22abc487c281d688c23d39b6f2c4f4ce5/tensorboard/backend/application.py#L227

In the past, optimizing the `is_active` method for plugins has made the difference between say a 1s load vs a 30s load ... vs a frontend that fails to load due to outlandish response times.

### Some Action Items

1. `is_active` methods that check for presence of data should short-circuit when any data is found. See #621 for example.
2. `is_active` methods that read from disk should consider not only short-circuiting, but also (1) computing on a separate thread and (2) caching after the plugin is found to be active. See #326 for example. Peruse the profile and text dashboards for potential optimizations.

**Comment by nfelt** [comment]
I think we can mark this done; we moved the expensive `is_active()` calls into background threads.  This introduces new problems as described in #2102 (plugins don't load initially and seem like they're just absent) but we can track that there.
