### ISSUE TITLE
TensorBoard.dev upload error 400: "The out-of-band (OOB) flow has been blocked"

### ISSUE THREAD

**Issue by hdiamond-foundationstack** [tensorflow/tensorboard#6268]
I have installed TensorBoard and updated it multiple times just to be sure that the problem is definitely non-local. Everything works on localhost, but today I tried to upload my scalars to TensorBoard.dev and had no success.

I started with a regular tensorboard dev upload --logdir=runs command in my work folder and there is definitely a folder named runs which contains logs from my runs. The command prompted a Google auth link after a simple license agreement, and I clicked it. It led to a Google form which said:

`error 400: invalid_request The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method. Request parameters: redirect_uri=urn:ietf:wg:oauth:2.0:oob`

I have no idea how to proceed, as I am not familiar with this problem. Any help would be greatly appreciated.

**Comment by yatbear** [comment]
Hi @hdiamond-foundationstack,

We recently migrate to a new method of authentication and you will need to upgrade to the latest version of TensorBoard.

**Comment by yatbear** [comment]
Hi @hdiamond-foundationstack,

What tensorboard version are you using?

**Comment by ksaluja15** [comment]
I was on tensorboard 2.10 and ran into this bug. Upgrading tensorboard to 2.13 resolved this issue.
