### ISSUE TITLE
Useless dependency on wheel

### ISSUE THREAD

**Issue by SpecLad** [tensorflow/tensorboard#6297]
## Environment information (required)

Not relevant (you don't even need to run Tensorboard to observe this).

## Issue description

Inspecting the tensorboard wheel reveals that it depends on the `wheel` package:

```console
$ bsdtar -xOf tensorboard-2.12.1-py3-none-any.whl tensorboard-2.12.1.dist-info/METADATA | grep wheel
Requires-Dist: wheel (>=0.26)
```

There seems to be no reason for this. I checked the source code, and I couldn't find any runtime usages of `wheel`. `wheel` doesn't even have an API, so it seems unlikely to be needed.

I would suggest removing it so that Tensorboard doesn't pull unnecessary packages into the environment.

**Comment by bileschi** [comment]
Indeed `wheel` is included as a runtime dependency in our runtime requirements.

https://github.com/tensorflow/tensorboard/blob/963afb7be883c15373c121c96c9039828e3fb728/tensorboard/pip_package/requirements.txt#L35

Looks like we discussed removing `wheel` here - perhaps was a py2 vs. py3 thing.  Apparently `wheel` is included in python3 now by default?

https://github.com/tensorflow/tensorboard/pull/5071#discussion_r653128617

**Comment by SpecLad** [comment]
`wheel` is not included by default, but that shouldn't be relevant, because you shouldn't require it regardless.

**Comment by groszewn** [comment]
The `wheel` dependency was removed as of [2.14.1](https://github.com/tensorflow/tensorboard/releases/tag/2.14.1).
