### ISSUE TITLE
Embedding Projector: show vector labels on custom projection view

### ISSUE THREAD

**Issue by dandelionmane** [tensorflow/tensorboard#63]
Migrated from https://github.com/tensorflow/tensorflow/issues/6327

> A feature request for the Embedding Projector: show vector labels as plot axis labels on custom projection view
> 
> minimal example, mocked up on a screenshot:
> <img width="317" alt="screen shot 2016-12-14 at 11 30 40 pm" src="https://cloud.githubusercontent.com/assets/2119400/21215544/ae2c994e-c256-11e6-9a8a-5501b4592695.png">
> <img width="1311" alt="custom-projection-blocks" src="https://cloud.githubusercontent.com/assets/2119400/21215550/b7a945ee-c256-11e6-9667-1ca8052c9483.png">
>

**Comment by dsmilkov** [comment]
Hi @micahstubbs,

Thanks for the suggestion! We are happy to accept a contribution and I'd be happy to walk you through the code and review your change.

For now I will close this issue. Feel free to reopen with a PR contribution.
