### ISSUE TITLE
Can TensorBoard group the data by subdirectory ?

### ISSUE THREAD

**Issue by doveppp** [tensorflow/tensorboard#6315]
Can TensorBoard group the data by model?

such as group by "TransformerModel" and "Xpresso":
![image](https://user-images.githubusercontent.com/54977106/231757694-7e5e42d5-25dd-42d7-9c2e-ad00df6a0aee.png)

the directory structure as follows:
![image](https://user-images.githubusercontent.com/54977106/231758066-7b42aeb7-ba37-4dfe-95e6-ec39dd218f75.png)

**Comment by bileschi** [comment]
Unfortunately not.  TensorBoard views subdirectories as synonymous with runs.  If you would like to group them you can move the events files into the same subdirectory.

https://docs.google.com/drawings/d/1ISKsRd8PX72hj9BD7Vg2z7JgWnXFJh_LvwFA29oKBLM/edit?resourcekey=0-7mxrh2JCOnjC9mBmUBuJDQ

**Comment by doveppp** [comment]
> Unfortunately not. TensorBoard views subdirectories as synonymous with runs. If you would like to group them you can move the events files into the same subdirectory.
> 
> https://docs.google.com/drawings/d/1ISKsRd8PX72hj9BD7Vg2z7JgWnXFJh_LvwFA29oKBLM/edit?resourcekey=0-7mxrh2JCOnjC9mBmUBuJDQ
It seems that this will treat different events files as a single curve.
By the way, i don't have access to this link.

**Comment by doveppp** [comment]
> Unfortunately not. TensorBoard views subdirectories as synonymous with runs. If you would like to group them you can move the events files into the same subdirectory.
> 
> https://docs.google.com/drawings/d/1ISKsRd8PX72hj9BD7Vg2z7JgWnXFJh_LvwFA29oKBLM/edit?resourcekey=0-7mxrh2JCOnjC9mBmUBuJDQ

It seems that this will treat different events files as a single curve.
By the way, i don't have access to this link.

**Comment by bileschi** [comment]
Sorry - posted a Google internal link by mistake.
