### ISSUE TITLE
Tensorboard Embedding Visualization using own data images for Inception V3

### ISSUE THREAD

**Issue by Prarthana1116** [tensorflow/tensorboard#634]
Hi,
Using tensorflow for poets (Inception V3 network), I trained my own data.
Currently, my data consists of  6 classes with 100  images in each class.

Now I am working on embedding visualization using these datasets.
How do I visualize my data in tensorboard?

How do I save the features from the second layers of Inception V3 so that I could save that file as features.txt file and use this file for visualization?
Please help me to solve out my problem.

**Comment by chihuahua** [comment]
Hi. Does these docs help? https://www.tensorflow.org/programmers_guide/embedding

Basically, you want to obtain your variable ... which *probably* looks like this.

```py
# Obtain the weights.
logits_weights = graph.get_tensor_by_name(
    'InceptionV3/Logits/Conv2d_1c_1x1/weights/ExponentialMovingAverage:0')
# Flatten the filters of the CNN if the tensor is 4D.
classes = logits_weights.shape_as_list()[-1]
logits_weights_flattened = tf.reshape(logits_weights, [-1, classes])
# [emb_size, classes] -> [classes, emb_size]
embeddings = tf.transpose(logits_weights_flattened)
embeddings_var = tf.get_variable(
    'embeddings',
    embeddings.shape_as_list(),
    trainable=False,
    # Prevent errors while computing PCA in the projector towards the start
    # of training.
    initializer=tf.random_normal_initializer())
```

Then, you want to configure a file with metadata ... something like this:

```py
metadata_file = os.path.join(self.output_dir, 'some_metadata.txt')
config = projector.ProjectorConfig()
emb_proj = config.embeddings.add()
emb_proj.tensor_name = embeddings_var.op.name
emb_proj.metadata_path = metadata_file
summary_writer = tf.summary.FileWriter(self.output_dir)
projector.visualize_embeddings(summary_writer, config)
```

**Comment by Pokharaa** [comment]
Dear chihuahua,
Thank you so much for your help.
But my question is how do I create this 'some_metadata.txt' file?

**Comment by Pokharaa** [comment]
Can anyone help me to solve my issue??

**Comment by bileschi** [comment]
Closing as this is a support issue over 2 years old.  @Prarthana1116 sorry you were left hanging here.  Please re-open if this is still an ongoing issue.
