### ISSUE TITLE
Add default selected hparams in UI

### ISSUE THREAD

**Issue by prateekjjw001** [tensorflow/tensorboard#6348]
Currently tensorboard only shows 4 default hparams. I have 50 hparams using lgbm, I want to select 15 hparams which should be selected everytime I start tensorboard, otherwise I need to manually select them. I want the same for metrics as well. How can I do this? If someone can point to the code where I can soecify this (inside tensorboard package) I am happy to do it just for myself in my local copy.

**Comment by bmd3k** [comment]
Hi, unfortunately the UI doesn't provide a way to configure this.

If you are willing to modify the code, I believe you need to modify the kNumHParamsToDisplayByDefault constant here:
https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts;l=578;drc=586a787e76c81e40cef8f8d16853ea1c74aca07b

For metrics, you would modify the kNumMetricsToDisplayByDefault constant here:
https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts;l=629;drc=586a787e76c81e40cef8f8d16853ea1c74aca07b
