### ISSUE TITLE
Hair detection err

### ISSUE THREAD

**Issue by creativeinnovator-dev** [tensorflow/tensorboard#6381]
I am going to detect hair part of image using tensorflow node module but it didn't work.

**Comment by naturalspirit-dev** [comment]
I think you would be better using python model.

**Comment by creativeinnovator-dev** [comment]
Thanks it works well.

**Comment by creativeinnovator-dev** [comment]
w

> I think you would be better using python model.

Do I have to convert python model using visual studio?

**Comment by naturalspirit-dev** [comment]
It is converting automatically
