### ISSUE TITLE
tensorflow suitable version

### ISSUE THREAD

**Issue by creativeinnovator-dev** [tensorflow/tensorboard#6382]
which python version is most suitable to detect hair?

**Comment by naturalspirit-dev** [comment]
Please install 3.78.
It is stable version.

**Comment by creativeinnovator-dev** [comment]
It works wonderful.

**Comment by creativeinnovator-dev** [comment]
> Please install 3.78. It is stable version.

how about 3.37

**Comment by naturalspirit-dev** [comment]
> > Please install 3.78. It is stable version.
> 
> how about 3.37

Latest stable version is 3.78

**Comment by creativeinnovator-dev** [comment]
> > > Please install 3.78. It is stable version.
> > 
> > 
> > how about 3.37
> 
> Latest stable version is 3.78

Really helped.
