### ISSUE TITLE
zsh:killed Terminal on Mac M1

### ISSUE THREAD

**Issue by pb1200** [tensorflow/tensorboard#6415]
Hello, 

I've got a problem with running a command in the Terminal. I want to open a html file, write down 'open concplot.html' (screenshot below) and then get 'zsh:killed'. I've tried to restart Mac, update os and homebrew, but no changes happened.. I'd be grateful for any advise 
<img width="602" alt="image" src="https://github.com/tensorflow/tensorboard/assets/124291468/a00c854f-6650-4e33-ad06-ee3374658cff">

**Comment by groszewn** [comment]
Hi there. This is not related to TensorBoard, so we cannot help you out here.
