### ISSUE TITLE
custom scalars not showing up in remote tensorboard.dev

### ISSUE THREAD

**Issue by Geoffreyvd1** [tensorflow/tensorboard#6423]
## Issue description

when launching a remote tensorboard.dev session, the custom scalars tab doesnt show up (while locally it does).

**Comment by groszewn** [comment]
Hi there, the https://tensorboard.dev homepage mentions in the FAQ (under `What TensorBoard functionality is available?`):

> In this Preview, the Scalars, Graphs, Histograms, Distributions, and HParams dashboards are currently available. Additional TensorBoard dashboards will be added over time.

Custom scalars are not supported at this time.

**Comment by Geoffreyvd1** [comment]
Ah sorry missed that, thank you for your response! 
Perhaps its already in development under a non-released version?

**Comment by groszewn** [comment]
We are not actively working on adding additional dashboards to TensorBoard.dev at this time.

**Comment by Geoffreyvd1** [comment]
oke thx
