### ISSUE TITLE
tensorboard_profiling_keras.ipynb doc fails to profile correctly

### ISSUE THREAD

**Issue by asynap** [tensorflow/tensorboard#6475]
## Environment information (required)

Please run https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb

As shown in https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

## Issue description

There is no profiler tab as expected and noted in the tensorboard documentation

**Comment by levinlan** [comment]
Yes Agree, I have Also tried the same didn't work for me.
i have tried with latest version of TensorFlow but still **tab didn't show up.**
i checked the log files and it has the PB file that include all the Profiling data.

**Comment by bmd3k** [comment]
Thanks. I agree it does not seem to be working.

The profile plugin is actually maintained separately from the rest of TensorBoard. Would you mind reopening this issue in their repo? https://github.com/tensorflow/profiler
