### ISSUE TITLE
how to split the log tensorboard into small files

### ISSUE THREAD

**Issue by KeyKy** [tensorflow/tensorboard#6509]
I am logging videoGIF and images and my log file is too large to be transferred. How to split the log file into small pieces.

**Comment by yatbear** [comment]
Hi @KeyKy,

Please see the example in this issue for splitting one event file into several: https://github.com/tensorflow/tensorboard/issues/6388#issuecomment-1551291218.

Note that the the library `RawEventFileLoader` is not intended to be public user-facing and is subject to internal changes, please avoid directly using this util as a stable and long term dependency in your checked-in code.

An alternative is to regenerate the logs and save them in multiple event files.

**Comment by nfelt** [comment]
You can close the SummaryWriter, then reopen a new one, and that will create a new file.
