### ISSUE TITLE
Very high s3 costs when using s3 bucket as log dir

### ISSUE THREAD

**Issue by sharan21** [tensorflow/tensorboard#6564]
## Environment information (required)
I created a simple docker file that imports from python 3.8 base image and installs the following deps:
```
boto3==1.20.26
botocore==1.23.26
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.7.0
tensorflow-estimator==2.7.0
tensorflow-io==0.23.1
tensorflow-io-gcs-filesystem==0.23.1
```
As the entrypoint to the docker command, i provide the s3 log dir path as follows:
```
tensorboard --logdir s3://path_to_log_dir --host 0.0.0.0 --port 6006
```
I tested this locally on cli, on docker and deployed it on k8 as an ingress and am successfully able visualise plots from event objects in the s3 log dir. I have 5 replicas/pods running continuously and about 100 objects in my s3 log dir. **The cost comes to around $200 a day which is extremely high.** This is the cost just to keep tensorboard on standby (without manually refreshing the UI or enabling reload data on the UI).

## Issue description

**The cost comes to around $200 a day which is extremely high.** This is the cost just to keep tensorboard on standby (without manually refreshing the UI or enabling reload data on the UI). What I have tried:
- I used the --reload_interval flag in the docker entry point and set it to 48 hrs. This has no effect and the cost in still $200 dollars a day
- I deleted all the objects in the s3 log dir and observed the cost the next day, and this was negligible. Which narrows me down to the fact that tensorboard server is somewhere refreshing or updating from s3 constantly and its not any other external entity thats causing this.
- Opening the networking tab in chroms debugger to see where the calls are going to. Unless I hit the refresh button, tensorboard seems to not be making any calls at all. 

My understanding is that somewhere, tensorboard is still making calls to s3 to refresh the events. I do not know why, when or from where these calls are happening. The reload interval flag does nothing. Its costing a lot of money and we appreciate some help at the earliest to trouble shoot this.

**Comment by JamesHollyer** [comment]
I did some digging into the logic which pings the log server to get updates. I found this logic that seems to reload the data on an interval which can be set by a flag(https://github.com/tensorflow/tensorboard/blob/eaab3eb56bad6d9fb4122e8119d3616944cca24d/tensorboard/backend/event_processing/data_ingester.py#L77). I am not sure this will solve your problem but maybe try running TensorBoard with --reload_interval 0.  Again I am not certain this will work but it is worth a shot.

Let me know if this helps. I hope I can find time in the future to dive in or talk with a colleague who would know this stuff better than me when he returns.

**Comment by sharan21** [comment]
Hey, thanks for the reply. So it might be the case that our reload_interval was not properly deployed in production and therefore it defaulted to 5 seconds. On some early testing we can see that after properly applying this it brings down the costs completely. So its all good for now, will get back to this thread incase it still remains unresolved.

Thanks

**Comment by JamesHollyer** [comment]
So glad to hear this helped. Good luck with your research! Feel free to reopen this if the problem persists.
