### ISSUE TITLE
Remove wheel from the requirements in setup.py

### ISSUE THREAD

**Issue by AnandInguva** [tensorflow/tensorboard#6567]
Can we remove the wheel requirement from the requirements.txt at https://github.com/tensorflow/tensorboard/blob/eaab3eb56bad6d9fb4122e8119d3616944cca24d/tensorboard/pip_package/requirements.txt#L36.

`pip install` will automatically install it and for projects depending on `pyproject.toml`, it can be included as part of build-time dependency. 

In Apache Beam, we generate our dependencies requirements file and we have tensorflow as a dependency, which has tensorboard as dependency. So we generate our requirements file by installing all the requirements in the virtual env and then doing a pip list. In this way, wheel won't included as part of `pip list`. Right now Apache beam supports only `setup.py` installation and we are planning to move to `PEP 517, 518` -> `pyproject.toml` build process.

if someone install from that generated requirements file in a fresh env and do a `pip check`, they would get an error  saying `tensorboard 2.13.0 requires wheel, which is not installed.`

**Comment by JamesHollyer** [comment]
This seems like a good idea. I will remove it.

**Comment by groszewn** [comment]
This dependency should no longer be included as of [2.14.1](https://github.com/tensorflow/tensorboard/releases/tag/2.14.1).
