### ISSUE TITLE
Store a mapping between plugin name to instance in the context magic container.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#658]
The backends of some new plugins would like to reference instances of other plugins.

Today, the distributions plugins constructs a histograms plugin from scratch:
https://github.com/tensorflow/tensorboard/blob/f48b15939ce237fc3692489a31c911ad98b1eae8/tensorboard/plugins/distribution/distributions_plugin.py#L50

but that differs a bit from the issue proposed here because some plugins actually need the exact instance of the other plugins.

We can resolve this issue by making the context magic container store a dictionary mapping plugin name to plugin instance. And then adding a `get_plugin_instance` method. That mapping is needed because TensorBoard currently just accepts the constructors of plugins upon startup:
https://github.com/tensorflow/tensorboard/blob/f48b15939ce237fc3692489a31c911ad98b1eae8/tensorboard/backend/application.py#L87

**Comment by jart** [comment]
If we're already doing this plugin depending on a plugin thing in our codebase, then I don't see the harm in adding an instance map.

**Comment by chihuahua** [comment]
Good point. We might as well offer access to the actual instance.
