### ISSUE TITLE
cannot import name event_file_inspector

### ISSUE THREAD

**Issue by JannaShen** [tensorflow/tensorboard#660]
when i run tensorboard /usr/local/tensorflow-gpu-1.0/bin/python2.7 /usr/local/tensorflow-gpu-1.0/lib/python2.7/site-packages/tensorflow/tensorboard/tensorboard.py --logdir=/home/jishen/SR/deeply-recursive-cnn-tf-master/tf_log ,it generates an error
Traceback (most recent call last):
  File "/usr/local/tensorflow-gpu-1.0/lib/python2.7/site-packages/tensorflow/tensorboard/tensorboard.py", line 32, in <module>
    from tensorflow.python.summary import event_file_inspector as efi
ImportError: cannot import name event_file_inspector

**Comment by JannaShen** [comment]
While i find the event_file_inspector.py file in /usr/local/tensorflow-gpu-1.0/lib/python2.7/site-packages/tensorflow/python/summary

**Comment by chihuahua** [comment]
Could you instead try

```python
from tensorboard.backend.event_processing import event_file_inspector as efi
```
?
