### ISSUE TITLE
Eliminate dependency on google-auth

### ISSUE THREAD

**Issue by jeblackburnvmw** [tensorflow/tensorboard#6603]
Could we remove the GCP-related stuff from core Tensorflow? Put it in a separate project? I'm currently facing an intractable version conflict between Tensorflow --> google-auth --> urllib3 v >=2.0.5 and boto3 --> botocore --> urllib3 v <1.27. 

Or relax the dependency on google-auth somehow?

```
The user requested urllib3==2.0.5
requests 2.31.0 depends on urllib3<3 and >=1.21.1
botocore 1.24.22 depends on urllib3<1.27 and >=1.25.4

...

error: urllib3 1.26.16 is installed but urllib3>=2.0.5 is required by {'google-auth'}
```

**Comment by arcra** [comment]
Tensorboard depends on the `google-auth` package only for some functionality related to our hosted service at http://tensorboard.dev, which is now in the process of being shut down, scheduled to be entirely removed by the end of the year. So we would be able to remove this dependency sometime next year after that happens.
