### ISSUE TITLE
official: "Tensorboard in notebooks" recipe no longer works

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorboard#6669]
Running all the cells in the Colab/Tensorboard integration [notebook](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb) displays 403 error instead of TensorBoard ([my copy of notebook](https://colab.research.google.com/drive/1rDsZpxqfAhx2YTN9zDZqV6-dcxZ5XuT7) )

<img width="1008" alt="Screenshot 2023-10-29 at 4 48 12 PM" src="https://github.com/tensorflow/tensorboard/assets/23068/33dbd0a8-442b-4e40-8f84-222c8925778f">

**Comment by bmd3k** [comment]
Hello. It seems like you are running into a known issue that the colab team is investigating: https://github.com/googlecolab/colabtools/issues/3990.

We expect them to post updates there.

In the meantime, it seems like the workaround is to use any browser other than Chrome.

**Comment by yaroslavvb** [comment]
@bmd3k perhaps the official notebook should be updated with a note that it doesn't work in chrome?
