### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by zji1233345** [tensorflow/tensorboard#6715]
Graph visualization failed.
Error:Malformed GraphDef.This can sometimes be caused by
a bad network connection or difficulty reconciling multiple
GraphDefs

**Comment by qihach64** [comment]
Hi, 

Could you provide more context (e.g. the code that trains the model, log the data and launch TensorBoard) in addition to the error message for further troubleshooting? You could also refer to the official doc https://www.tensorflow.org/tensorboard/graphs for how to log and examine your model graph.
