### ISSUE TITLE
Feature Request: Visualize raw data in Projector

### ISSUE THREAD

**Issue by ahoereth** [tensorflow/tensorboard#676]
Currently the projector always applies dimensionality reduction (through pca or t-sne), even if the visualized data originally is only 3 dimensional. It would be awesome to directly visualize such low dimensional data. If a feature like this would be welcome by the core team, I would be open to start working on a PR.

Another request: Integrate the projector more tightly to the normal tf.summary API and thereby enable one to visualize layer activations directly, without the need to write them to a variable and checkpoint.

**Comment by chihuahua** [comment]
@ahoereth, directly visualizing data seems like a useful feature. I admittedly lack the time to implement the feature now. Feel free to start a PR, and we can keep in touch about it.

Looping in @dsmilkov and @nsthorat.

**Comment by dsmilkov** [comment]
We'll be happy to review your contribution. A simple check: `if dimensionality == 3, then don't do projection` would suffice.

**Comment by ahoereth** [comment]
Great! So would you expect there to be another option like "raw" next to pca/tsne/custom when the data is <=3d?

Regarding my other request: Can I somewhere read about or can you give me a quick heads up about the reasoning behind not providing something like `tf.summary.projection()`? As far as I can see, the projector is the only part of tensor board which reads data from checkpoints and not from summaries.

**Comment by ahoereth** [comment]
Okay sorry, discard my original feature request for now. Appears like the pca tab currently already gives the correct representation for low dimensional data. Nevertheless, my other question still stands.

**Comment by jart** [comment]
@ahoereth I'm going to close this issue out then. You're welcome to file a second issue regarding your request for tighter projector <-> tf.summary integration. Please include some fake example code of what you'd like to see happen, if possible.
