### ISSUE TITLE
[Potential improvement] Reduce binary size of rust data server

### ISSUE THREAD

**Issue by Corwinpro** [tensorflow/tensorboard#6766]
I think there might be an easy win to reduce the size of the rustboard binary, by about 30%. We could just strip some debug symbols and stuff from the release build, as you can see here: https://github.com/tensorflow/tensorboard/pull/6765

FWIW on my M1 machine, the build went down from 14Mb to 9.5Mb.

Also, please let me know if the build process is different from the one I assumed (`cargo build --release`), and that change is not relevant.

**Comment by bileschi** [comment]
Fixed via #6765.  Thanks!
