### ISSUE TITLE
unable to build tensorflow using bazel

### ISSUE THREAD

**Issue by sudhir-behani** [tensorflow/tensorboard#678]
I am building tensorflow version 1.3.1 in AWS P2.large instance.
**git branch
* (HEAD detached at v1.3.1)
  master**

/tensorflow$ bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

WARNING: ignoring http_proxy in environment.
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 0.042s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by chihuahua** [comment]
Could you please file this issue under TensorFlow? Here: https://github.com/tensorflow/tensorflow/issues

TensorBoard's analog to this issue had been resolved already: #585.

**Comment by keshavunni** [comment]
Did you find a solution? @sudhir-behani
