### ISSUE TITLE
TensorBoard demo server doesn't work

### ISSUE THREAD

**Issue by taion** [tensorflow/tensorboard#68]
I'm trying:

```
bazel run tensorboard/components/tf_tensorboard:demo
```

adapted from DEVELOPMENT.md.

This loads up the dev server, but paths like:

http://localhost:6006/tf-tensorboard/demo.html

don't actually work – looks like the JS isn't transpiled, as I get console errors on unrecognized `import` statements.

**Comment by wchargin** [comment]
Hi @taion—that info was out of date. I've removed it in #58.

You can run `bazel run //tensorboard -- --logdir /tmp/mylogs` to launch TensorBoard on some data that you have lying around. If you don't have any data, you can run `bazel run //tensorboard/plugins/scalars:scalars_demo` to generate some data in `/tmp/scalars_demo`. We don't currently have a fake-data devserver.

Feel free to reopen if this doesn't solve your problem. Thanks!
