### ISSUE TITLE
Can tensorboard adjust the display window in IMAGE tab?

### ISSUE THREAD

**Issue by zcz004** [tensorflow/tensorboard#680]
I was wondering if I can adjust the greyscale of the image shown in the IMAGE tab of tensorboard for better visualization. Say adjust the window from greyscale [0 1] to [0.3 0.7]... If there's not such a feature, is it possible to be added?

**Comment by wchargin** [comment]
Hi. It sounds like you're saying that you want to be able to apply a color map to your images while viewing them on the image dashboard. Is this correct?

The dashboard doesn't currently support this; we emit the images exactly as you output them from the image summaries. This is theoretically possible; we could apply `filter: constrast(x)` to images, where `x` is controlled by a slider.

**Comment by chihuahua** [comment]
What does adjusting from greyscale [0 1] to [0.3 0.7] mean? For instance, given original pixel values

```
200 100 42
```

would my new pixel values be

```
156.5 116.5 93.3
```

? I just mapped from a scale of `[0, 255]` to `[255 * 0.3, 255 * 0.7]`.

Also, what is the use case for this feature? If it's useful enough, we (or an open-source contributor) can add the feature.

**Comment by zcz004** [comment]
@chihuahua @wchargin Thanks for addressing this issue. As for @chihuahua 's concern, the pixel value remains unchanged. Adjusting the widow scale allows different contrast of images for better visualization. This might be important for medical imaging applications for instance, where image details do matter a lot.

**Comment by nfelt** [comment]
Assigning to @zcz004 just for tracking purposes, since the PR is in review.
