### ISSUE TITLE
When will the new version be released on pypi?

### ISSUE THREAD

**Issue by HisiFish** [tensorflow/tensorboard#684]
It's difficult to compile it locally for me. 

The newest version on pypi is still 1.0.0a6 @ 2017-3-15.

So, When will the new version be released on pypi? Is there any plan?

**Comment by mdraw** [comment]
The current PyPI package doesn't actually contain the "real" tensorboard whose issue tracker you see here, but a different project that was given the exact same name...
See https://github.com/dmlc/tensorboard/issues/50.

**Comment by mdraw** [comment]
The official package is currently called `tensorflow-tensorboard`: https://pypi.python.org/pypi/tensorflow-tensorboard/0.4.0rc1

**Comment by HisiFish** [comment]
@mdraw Thanks very much. This is just what I want.
