### ISSUE TITLE
tensorboard title

### ISSUE THREAD

**Issue by bonseong11** [tensorflow/tensorboard#6849]
![스크린샷 2024-05-08 14-02-03](https://github.com/tensorflow/tensorboard/assets/80501715/50b4d03e-922f-4ce5-b891-ef16ff529dcc)
Can you change the TensorBoard text shown in the screenshot? I want to change the name or make it usable. Is it possible?

**Comment by arcra** [comment]
Hello,

I'm not sure I understand the request. That label at the top-left is the name of the tool, and we don't have support for changing it.

Can you share more details on how you would like to change it or "make it usable"?

**Comment by bonseong11** [comment]
I don't know how to solve this problem other than this problem... The actual label and the sprite image, that is, the image that appears when I press the isolation selection button, and the label are different. How do I solve this????
![스크린샷 2024-05-17 14-14-24](https://github.com/tensorflow/tensorboard/assets/80501715/dda8cf47-432c-4e6d-aa53-f9f9052206bb)

**Comment by arcra** [comment]
This seems specifically an issue with your model and/or data set, do you have a reason to believe this is a bug in the tool?

I'm afraid we don't have bandwidth to help troubleshoot issues other than bugs and features in the tool itself. I would encourage you to try other forums like stackoverflow.

If you think this is a bug in the tool we would need a way to reproduce (ideally a minimal example), so we can investigate.

I'll close this for now under the assumption that this is not actually an issue with the tool, but feel free to re-open it and provide more information if you think this is wrong.
