### ISSUE TITLE
why no graph show?

### ISSUE THREAD

**Issue by wengqi123** [tensorflow/tensorboard#686]
my tensorboard log file in /home/weng/tensorboard/log
and i cd : /home/wang/tensorboard
command: tensorboard --logdir = log/
and not error show,and open the url , not graph shows?

**Comment by chihuahua** [comment]
Could you remove the equals sign and just use 
```
tensorboard --logdir log
```
? Does that work?

**Comment by wengqi123** [comment]
it work! thanks

**Comment by jart** [comment]
Glad the problem was resolved. I'm going to close this one out now.
