### ISSUE TITLE
Capture profile successfully, After refresh the tensorboard  show No profile data was found.

### ISSUE THREAD

**Issue by xiaobai5150** [tensorflow/tensorboard#6889]
tensorboard start as below
#tensorboard --host 0.0.0.0 --logdir /repo/.tensorboard-info --port 2345

then I type the remote tensorserving grpc server ip and port to capture the profile
![image](https://github.com/user-attachments/assets/bccb82e1-0cbc-48ae-b3ed-779205d85b30)

after the capture deadline ,show Capture Successfully,Please refresh .
![image](https://github.com/user-attachments/assets/4ec409f1-3fb3-4a7e-9425-257ba50a7d32)

**When refresh tensorboard on  browser**
![image](https://github.com/user-attachments/assets/e1043d2d-267d-4c68-9bdd-49a56dd68221)

**the tensorboard logs show no erorr**
![image](https://github.com/user-attachments/assets/1960c0ef-3a66-4144-af18-28b1fcf6ab16)

**and the logdir file only can see pid info and no events file generate .**
![image](https://github.com/user-attachments/assets/a5d0ce4d-5527-4b04-9572-950e08b3bea0)

**can  Tensorboard  support capture the remote tensorserving grpc ?**

**Comment by arcra** [comment]
This seems to be an issue for the [tensorflow/profiler](https://github.com/tensorflow/profiler) repo. Can you file an issue to them, please? Feel free to re-open this if this is an issue with the base TB tool.
