### ISSUE TITLE
fail to create whl

### ISSUE THREAD

**Issue by DannyAtal** [tensorflow/tensorboard#6895]
Hey Guys Im trying to export a whl file with python3.12 via this command with no luck:
sudo bazel run //tensorboard/pip_package:extract_pip_package -- /tmp/tb_pips

it always fails building with setup.py is deprecated or something similar, the question is how can I build it with the latest python? also how can we make it compitable with latest numpy and is there will be an official pypi package soon?

**Comment by groszewn** [comment]
Updating `virtualenv` on my machine made these issues go away, and I've updated the dev dependencies in #6897. The `2.17.1` patch release is now out, which includes Numpy 2.0 compatibility. Please feel free to reopen if a newer install of`virtualenv` does not resolve the issue.
