### ISSUE TITLE
tensorboard server: base_url support

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#69]
This issue had been migrated from tensorflow/tensorflow#2602.

> ### What have you tried?
> 
> Running the tensorboard service through a proxy server, which does map a subdirectory to the tensorboard server' root.
> ### Desired outcome
> 
> By providing a way to specify a `base_url`, the server would understand how to treat incoming requests in such a situation. e.g. `://server/subdir/tensorboard/` → `://server/`
>

**Comment by haraldschilly** [comment]
I think we can close this issue in favor of #30 ? (someone should check if I'm correct, though)

**Comment by chihuahua** [comment]
That makes sense to me. #30 also directly deals with adding a `base_url` flag. The motivation behind #30 is slightly different (We want to handle requests at a different URL location.), but it might behove us to move discussion to #30 given how @pbanavara has actually made efforts toward solving it. I will leave it to you, @haraldschilly, but yes, lets tentatively move discussion to #30.

**Comment by hidrargyro** [comment]
More than a year, but, did you resolve the problem with the prefix path for the font? I have the same issue @Joe136
