### ISSUE TITLE
Tensorboard profiler tutorial broken

### ISSUE THREAD

**Issue by armanschwarz** [tensorflow/tensorboard#6957]
I went to this page: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras

Then I click on [Run in Google Colab](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb). Then I click Runtime -> Run all.

Then on the tensorboard page I don't see any "profile" tab. And if I select "Profile" from the dropdown on the right I get to a page that says "No profile data was found":

![image](https://github.com/user-attachments/assets/bccc766b-f7db-438e-b9c6-1983dd3d579e)

I thought maybe this was an issue with "tensorboard_plugin_profile" not being available in the kernel after installation, so I tried "Restart session and run all" but had the same result. I also tried running the tutorial on my own device. In that case I got some profiling information, but the main summary page has no step markers:

![image](https://github.com/user-attachments/assets/b994c753-55d2-4bc0-b343-c1bd9946ec69)

Not really sure what to do from here, as I don't understand enough about the profiler to diagnose the problem (I was hoping the tutorial would give me a working starting point).

**Comment by arcra** [comment]
This plugin is maintained in a separate repo, could you please file an issue with them? https://github.com/tensorflow/profiler

Sorry I can't be of help.
