### ISSUE TITLE
Tensorboard report "Graph: Failed Normalizing names when using data.Dataset" when using tf.decode_raw.

### ISSUE THREAD

**Issue by Hong-Xiang** [tensorflow/tensorboard#702]
Code to reproduce this bug:
```
import tensorflow as tf
from tensorflow.contrib.data import Dataset
dummy_bytes = tf.constant(np.zeros([128, 128]).tostring())
dataset = Dataset.from_tensors(dummy_bytes)
dataset = dataset.map(lambda x: tf.decode_raw(x, tf.uint8))
with tf.Session() as sess:
    tf.summary.FileWriter('./summary', sess.graph)
```
when using tensorboard for this summary file, the graph tag shows "Graph: Failed Normalizing names".

tensorflow version: 1.3
system:
  tensorflow/tensorboard runing on ubuntu-mate 16.04
  view tensorboard from chrome on Win10

**Comment by davharris** [comment]
Upgrading to 1.4 fixed this for me.

**Comment by nfelt** [comment]
@Hong-Xiang does upgrading to 1.4 fix this for you as well?  I wasn't able to reproduce this at 1.3.

**Comment by Hong-Xiang** [comment]
@nfelt Upgrading to 1.4 fixed it for me too.

**Comment by nfelt** [comment]
Great.  I'm going to go ahead and close this out then.
