### ISSUE TITLE
Safari 404: web-animations-next-lite.min.js.map & weblas.map.json

### ISSUE THREAD

**Issue by francoisluus** [tensorflow/tensorboard#703]
### Path not found (404): web-animations-next-lite.min.js.map and weblas.map.json
Safari browser access error with TensorBoard server which displays blank page, after building the TensorBoard github source on a standard Debian VM. This bug has been described many times before and I've tried various fixes unsuccessfully, so it may be something peculiar with my Safari as there is no problem with Chrome/Firefox.

I simplified the setup so the conditions can be recreated independently. My hope is that someone can confirm whether TensorBoard is accessible on their Safari with the below setup.

### System config:
Google Cloud Platform - Compute Engine - VM Instance
Standard 1 vCPU
Debian GNU/Linux 9 (stretch)
Firewall: Allow HTTP/HTTPS traffic
Network: tcp:6010 allow

### Install Git, Bazel, pip and tensorflow:
```bash
sudo apt-get update && sudo apt-get install -y git openjdk-8-jdk python-pip
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y bazel
sudo apt-get upgrade -y bazel
pip install tensorflow
```

### Clone TensorBoard and Bazel run server:
```bash
git clone https://github.com/tensorflow/tensorboard.git
cd tensorboard
bazel run tensorboard -- --logdir /home/emnist-2000 --host 0.0.0.0 --port 6010
```

### Server output:
When accessing the server with client-side Safari browser, the following server messages appear:
```
TensorBoard 0.4.0a0 at http://0.0.0.0:6010 (Press CTRL+C to quit)
W1104 15:20:57.933438 Thread-2 application.py:268] path /web-animations-next-lite.min.js.map not found, sending 404
W1104 15:20:58.725778 Thread-3 application.py:268] path /weblas.map.json not found, sending 404
```

### Safari error:
Safari (Version 10.0.3 (12602.4.8)) on macOS Sierra (10.12.3), several soft and hard reloads, empty cache, disable cache, restarted.
```
/web-animations-next-lite.min.js.map - Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/weblas.map.json - Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

Dataset for tensorboard: [emnist-2000.zip](https://github.com/tensorflow/tensorboard/files/1443323/emnist-2000.zip)

**Comment by nfelt** [comment]
@francoisluus - Thanks for your detailed reproduction instructions.  I've done my best to replicate this, and I'm able to get the 404 messages to show up when loading via Chrome but *not* Safari (yes, strangely enough) with 0.4.0-rc1, but neither browser generates the 404 requests for current master (2670430ff3c85a98a50efddd9ba8581710fd111d).

I'm going to close this optimistically hoping that it's fixed at master, but please re-open if you see this again.
