### ISSUE TITLE
How should I understand the histograms in tensorboard?

### ISSUE THREAD

**Issue by github-qianxunlin** [tensorflow/tensorboard#713]
![image](https://user-images.githubusercontent.com/29731333/32584063-8ea5b0ae-c531-11e7-907e-eafff03a48b1.png)
As shown in figure,how should i understand the meaning of axis1 and axis2?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by github-qianxunlin** [comment]
Thanks in advance
