### ISSUE TITLE
Document events file format

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorboard#72]
https://github.com/tensorflow/tensorflow/issues/4181

@malmaud says:

> Hello,
> In the documentation for Tensorboard, I can't find a description for the format of the events file beyond that it contains Event protobufs. Is it recordio? Are there any tools for writing event files for 3rd-party Tensorflow clients that aren't using the Python API?

**Comment by jart** [comment]
I'm going to be doing a lot of work on event ingestion in the near future, refactoring the backend, so I can probably write excellent documentation for what's going on with events during that time.

For example, plugins are most likely going to have access to raw event streams in real time. We want them to know what they can do with these protos.

**Comment by elmarhaussmann** [comment]
Is there any progress or update on this? Having access to events in real time would be extremely helpful for us.

**Comment by jart** [comment]
Might I ask what you're working on? How real time do you need it to be?

As you know, TensorBoard currently polls the event log files, which can be written by multiple hosts in a distributed training. We want to improve our latency. The thing that would help us most right now is to collect requirements from the community.

@malmaud The format of the event logs file is it's a "records file" where each record is a binary encoded [`tf.Event`](https://github.com/tensorflow/tensorflow/blob/e6fee141e3bdde3bac5741b2aadfdd41bd2a7b24/tensorflow/core/util/event.proto#L13) protocol buffer, which contains [`tf.summary.Summary`](https://github.com/tensorflow/tensorflow/blob/e6fee141e3bdde3bac5741b2aadfdd41bd2a7b24/tensorflow/core/framework/summary.proto#L68) protos. You can Google how to serialize protobufs in any language. The record file format is described by [record_writer.cc](https://github.com/tensorflow/tensorflow/blob/e6fee141e3bdde3bac5741b2aadfdd41bd2a7b24/tensorflow/core/lib/io/record_writer.cc) and @zihaolucky wrote a really excellent pure Python [implementation](https://github.com/dmlc/tensorboard/blob/master/python/tensorboard/record_writer.py) of the same thing. In essence:

```cc
  // Format of a single record:
  //  uint64    length
  //  uint32    masked crc of length
  //  byte      data[length]
  //  uint32    masked crc of data
```

**Comment by malmaud** [comment]
Long delay, but thanks!

**Comment by manivaradarajan** [comment]
jart's comment above appears to have addressed the original request:

https://github.com/tensorflow/tensorboard/issues/72#issuecomment-319839210
