### ISSUE TITLE
How to increase the data points using Embedding Projector?

### ISSUE THREAD

**Issue by xiaogehh** [tensorflow/tensorboard#725]
The embedding have a tip that the datasize(459753) is too large

![image](https://user-images.githubusercontent.com/7589403/32707471-05dac35a-c85f-11e7-81cf-1f48e24c2f7e.png)

I notice the datasize of `Word2Vec All` have 71291 values,can we increase the datasize to 10K?

**Comment by xiaogehh** [comment]
I know the tsv should be like this:
![image](https://user-images.githubusercontent.com/7589403/32712491-e56d9e96-c87f-11e7-991f-08e16ce6a87e.png)

**Comment by jart** [comment]
Not without significant work, which we unfortunately don't have the resources to do at the moment.
