### ISSUE TITLE
Missing release notes for 0.4

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorboard#726]
The 0.4 branch is missing the release notes, but promises "will be published shortly."

This is so they are not forgotten.

**Comment by jart** [comment]
Thank you for the reminder. They will be published in due time and this issue will be closed when that happens.

**Comment by jart** [comment]
Here are the [0.4.0 release notes](https://github.com/tensorflow/tensorboard/releases/tag/0.4.0) courtesy of @nfelt.
