### ISSUE TITLE
family argument not expected for tf.summary.image

### ISSUE THREAD

**Issue by SpikingNeurons** [tensorflow/tensorboard#740]
![image](https://user-images.githubusercontent.com/2289914/32852252-9d0d17da-ca37-11e7-9134-1553c0dc2e4a.png)
When used family argument I got the error
```
TypeError: image() got an unexpected keyword argument 'family'
```

**Comment by jart** [comment]
FYI @wchargin

**Comment by wchargin** [comment]
I cannot reproduce this:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.VERSION
'1.3.0'
>>> tf.summary.image(
...     name='input',
...     tensor=[[[0, 1, 2]]],
...     max_outputs=10,
...     collections=None,
...     family=None)
<tf.Tensor 'input:0' shape=() dtype=string>
```

There are two summary APIs: the old `tf.summary.image` and the new `tensorboard.summary.image`. It looks like you're using the old API (which is totally fine), but this result is therefore surprising to me: while we did intentionally drop the `family` parameter from all the new summary APIs, we did not change the old API, and you can see that [TensorFlow master currently accepts a `family` parameter for `tf.summary.image`.](https://github.com/tensorflow/tensorflow/blob/31b79e42b9e1643b3bcdc9df992eb3ce216804c5/tensorflow/python/summary/summary.py#L105)

What versions of TensorFlow and TensorBoard are you using?

Could you add the line `print(tf.summary.image.__module__)` immediately before the line causing the error, and report its result? (I expect to see `tensorflow.python.summary.summary`; if we instead see `tensorboard.plugins.image.summary` then we will know where the problem is coming from.)

It might also be helpful to `import inspect` and then `print(inspect.getsource(tf.summary.image))`, to definitively see the definition of the function that's being executed.

**Comment by SpikingNeurons** [comment]
I was using tensorflow-1.2 and was facing the error. I just updated to 1.4 and the error is gone.
Can you check with tensorflow-1.2?

On a sidenote, should we avoid to use old API
I was following the official [tutorial](https://www.tensorflow.org/get_started/summaries_and_tensorboard) and it seems to use old API i.e. `tf.summary.image`. Will it be deprecated?

**Comment by SpikingNeurons** [comment]
Just for your reference, I downgraded tensorflow to version 1.2 and I got the error.

Code:
```python
import inspect
import tensorflow as tf
print("tensorflow_version", tf.VERSION)
print("************************************ inspect.getsource(tf.summary.image)")
print(inspect.getsource(tf.summary.image))
print("************************************ tf.summary.image.__module__")
print(tf.summary.image.__module__)
print("************************************ Buggy code")
with tf.name_scope('input_reshape'):
    image_shaped_input = tf.reshape(x, [-1, 28, 28, 1])
    tf.summary.image(
        name='input', 
        tensor=image_shaped_input, 
        max_outputs=10, 
        collections=None,
        family=None
    )
```
Console Output:
```txt
tensorflow_version 1.2.0
************************************ inspect.getsource(tf.summary.image)
def image(name, tensor, max_outputs=3, collections=None):
  """Outputs a `Summary` protocol buffer with images.

  The summary has up to `max_outputs` summary values containing images. The
  images are built from `tensor` which must be 4-D with shape `[batch_size,
  height, width, channels]` and where `channels` can be:

  *  1: `tensor` is interpreted as Grayscale.
  *  3: `tensor` is interpreted as RGB.
  *  4: `tensor` is interpreted as RGBA.

  The images have the same number of channels as the input tensor. For float
  input, the values are normalized one image at a time to fit in the range
  `[0, 255]`.  `uint8` values are unchanged.  The op uses two different
  normalization algorithms:

  *  If the input values are all positive, they are rescaled so the largest one
     is 255.

  *  If any input value is negative, the values are shifted so input value 0.0
     is at 127.  They are then rescaled so that either the smallest value is 0,
     or the largest one is 255.

  The `tag` in the outputted Summary.Value protobufs is generated based on the
  name, with a suffix depending on the max_outputs setting:

  *  If `max_outputs` is 1, the summary value tag is '*name*/image'.
  *  If `max_outputs` is greater than 1, the summary value tags are
     generated sequentially as '*name*/image/0', '*name*/image/1', etc.

  Args:
    name: A name for the generated node. Will also serve as a series name in
      TensorBoard.
    tensor: A 4-D `uint8` or `float32` `Tensor` of shape `[batch_size, height,
      width, channels]` where `channels` is 1, 3, or 4.
    max_outputs: Max number of batch elements to generate images for.
    collections: Optional list of ops.GraphKeys.  The collections to add the
      summary to.  Defaults to [_ops.GraphKeys.SUMMARIES]

  Returns:
    A scalar `Tensor` of type `string`. The serialized `Summary` protocol
    buffer.
  """
  name = _clean_tag(name)
  with _ops.name_scope(name, None, [tensor]) as scope:
    # pylint: disable=protected-access
    val = _gen_logging_ops._image_summary(
        tag=scope.rstrip('/'),
        tensor=tensor,
        max_images=max_outputs,
        name=scope)
    _collect(val, collections, [_ops.GraphKeys.SUMMARIES])
  return val

************************************ tf.summary.image.__module__
tensorflow.python.summary.summary
************************************ Buggy code
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a95656a52b91> in <module>()
     13         max_outputs=10,
     14         collections=None,
---> 15         family=None
     16     )

TypeError: image() got an unexpected keyword argument 'family'
```

**Comment by wchargin** [comment]
Right, okay, that makes sense: [The `family` parameter just hadn't been introduced by TF1.2.](https://github.com/tensorflow/tensorflow/blob/f4c0b3a08c5fab478c437c4f8765f8a440494e5f/tensorflow/python/summary/summary.py#L134)

I think this issue can be closed, then?

> On a sidenote, should we avoid to use old API? […] Will it be deprecated?

We don't currently plan to deprecate the old API; you should feel free to use it. The newer APIs have additional functionality that you may find useful (e.g., you can add descriptions and display names to summaries to make your TensorBoard clearer), but we transparently migrate data generated by old summaries, so there is no harm at all in using the old APIs.
