### ISSUE TITLE
datatype is not readable tensorflow::ops::MatchingFiles

### ISSUE THREAD

**Issue by cuevas1208** [tensorflow/tensorboard#746]
I am trying to use tensorflow::ops::MatchingFiles to get a list of all the files in a directory. This is how my images value looks after running it:

`images{filenames={op_={inputs_={ size=1 } node_=0x00000157e4358830 {id_=3 cost_id_=3 class_=NC_OTHER (19) ...} } ...} }
`

How do you get the list of files using MatchingFiles tensor output? 

environment:
C++
VS15
Python 1.3

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
