### ISSUE TITLE
Tensorboard pip package doesn't launch tensorboard on RHEL 7-ppc64le

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorboard#748]
System:
Red Hat Enterprise Linux Server release 7.4 (Maipo), ppc64le

Tensorboard:
Built from source tag 0.4.0-rc3

Bazel: 
0.5.4

Build Steps:
bazel build //tensorboard/pip_package:build_pip_package
bazel-bin/tensorboard/pip_package/build_pip_package /tmp

Issue:
The wheel file created when installed, doesn't copy the bazel-bin/tensorboard/tensorboard executable. And obviously, whatever is needed by this executable like tensorboard.runfiles is also not copied. Also the external pre-requisites like protobuf, html5lib, werkzeug, paper-*, iron-* are not copied into the wheel file. 
On x86, I tried installing two packages tensorboard and tensorflow-tensorboard using pip. And 1st one provides complete package including all the dependencies. It looks like it comes from https://github.com/dmlc/tensorboard while the 2nd one is similar to what I see on ppc64le which came from https://github.com/tensorflow/tensorboard. 
So, not sure if this is the bug in tensorflow-tensorboard package or the package is still evolving.

Meanwhile I tried modifying build_pip_package.sh to copy all the external dependencies and it worked.

**Comment by nfelt** [comment]
Can you provide a little more detail on exactly what you're expecting to work?  E.g. what did you do to install the freshly built pip package, and then how were you trying to execute the `tensorboard` command?

As far as I'm aware, the pip package building script isn't supposed to bundle the bazel-bin/tensorboard/tensorboard executable or the external dependencies into the wheel file (it did used to include some external sources prior to https://github.com/tensorflow/tensorboard/pull/591 but that was intentionally removed).  The wheel file should pretty much just be the python source code plus compiled versions of our HTML/JS.  When you `pip install` the wheel file, it's pip's job to

1) fetch all the dependent pip packages you're describing like protobuf which are listed in install_requires:
https://github.com/tensorflow/tensorboard/blob/c59b24f19384644208311fe075bf00da4d667e30/tensorboard/pip_package/setup.py#L25

2) create a "console script" called "tensorboard" that just runs our main function:
https://github.com/tensorflow/tensorboard/blob/c59b24f19384644208311fe075bf00da4d667e30/tensorboard/pip_package/setup.py#L62

FWIW, the DMLC tensorboard is a derivative project that's not actually affiliated with us (yes, even though they're `tensorboard` on PyPI), so I can't speak to what they might be doing.

**Comment by bileschi** [comment]
Closing as a support issue over 1 year old.  Please re-open if this is still an issue.
