### ISSUE TITLE
tensorboard support AWS s3 file system for logdir

### ISSUE THREAD

**Issue by srikumar-b** [tensorflow/tensorboard#767]
I see tensorflow support AWS s3 file system (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/platform/s3) but I dont see it working for tensorboard. I am creating this issue to request for support in tensorboard

ex: `tensorboard --logdir=s3://bucket/path`

**Comment by jart** [comment]
`--logdir` uses TensorFlow's file system API under the hood, so I'm not sure why it wouldn't work. Could you please provide TF / TB versions, platform info, error messages, etc. etc.?

**Comment by srikumar-b** [comment]
Ah good to know. Thanks for the reply.

I tried using tf-nightly and tb-nightly builds but still i could not get access it...

Do you know if there is a document explaining the syntax of commandline arg? Is there a flag to enable detailed logging/debug info?

**Comment by srikumar-b** [comment]
tensorflow version: 1.5.0-dev20171121
TensorBoard 1.5.0a20171121
platform: Tried on both macOS and ubuntu

No error message is shown. When i download the same content to localdisk and load it, It works fine.

**Comment by srikumar-b** [comment]
And it looks like s3 is enabled by default from configure script `Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]:`

BTW, Is there a way to debug? `--debug` option seems to be invalid

**Comment by jart** [comment]
Can you try:

```pycon
>>> import tensorflow as tf
>>> tf.gfile.Stat('s3://bucket/path')
```

**Comment by srikumar-b** [comment]
I am able to make it work by externally passing S3_REGION environment variable. I don't see default regio read from AWS config `~/.aws/config` or whatever. Is it suppose to work without passing S3_REGION? If not, may be it could be good to document somewhere

**Comment by jart** [comment]
I recommend reaching out to the folks on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for questions like that. I'm an HTML programmer and I don't have very much experience with S3.

**Comment by austinmw** [comment]
@srikumar-b How did you pass S3_REGION?

**Comment by harusametime** [comment]
Just put `AWS_REGION=<region_name>` before `tensoraboard`

```
AWS_REGION=us-west-1 tensorboard --logdir s3://s3://bucket/path
```
