### ISSUE TITLE
tensorboard出现问题

### ISSUE THREAD

**Issue by jiqixuexiaihaozhe** [tensorflow/tensorboard#770]
出来了地址，然后复制粘贴到Google - Chrome上面，结果显示错误页面是怎么回事呀【哭】
好不容易到这一步了。。。还有错。。。

**Comment by jart** [comment]
除了正在显示的特定错误消息之外，能否请您提供有关您使用的TensorFlow和TensorBoard版本的信息？

**Comment by jiqixuexiaihaozhe** [comment]
谢谢啦( •̀∀•́ )，问题已经解决了！

**Comment by jart** [comment]
极好(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by jiqixuexiaihaozhe** [comment]
还以为不会有人回呢！没想到真的有人来解决问题！谢谢你啦( •̀∀•́ )！！！
