### ISSUE TITLE
How to use TENSORBOARD in the newest version 1.5？

### ISSUE THREAD

**Issue by Ericonaldo** [tensorflow/tensorboard#774]
Can not use tensorboard in my command line, and just find tensorboard in tf/contrib, without tensorboard.py. After I download the tensorboard1.5 in its own git and command with "python3 main.py", it comes with an error like "ImportError: cannot import name 'plugin_data_pb2'"..............

**Comment by jart** [comment]
Try running `pip install tensorflow-tensorboard` or `pip install tb-nightly` or `bazel run //tensorboard -- --logdir=foo`.

**Comment by Ericonaldo** [comment]
Sorry...I missed this answer...THANKS A LOT
