### ISSUE TITLE
TensorBoard 0.4.0rc3 on Windows ignores logical drive specified in logdir argument

### ISSUE THREAD

**Issue by antonsoch** [tensorflow/tensorboard#789]
TensorBoard 0.4.0rc3 on Windows always replaces logical drive in a path from logdir argument with the one   it was launched from.

**Comment by nfelt** [comment]
Duplicate of #52

**Comment by nfelt** [comment]
I believe your issue should be resolved at HEAD: https://github.com/tensorflow/tensorboard/issues/52#issuecomment-349521326

If you're able to, give that a try, otherwise hopefully the next release will resolve this.
