### ISSUE TITLE
Embedding Projector: some metadata unsearchable

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tensorboard#79]
Migrated from https://github.com/tensorflow/tensorflow/issues/8177

There's a lot of additional conversation there.

> ### Potential Bug
> I'm using Tensorboard's embedding projector to perform PCA/t-SNE on a dataset of features I've extracted from ~4K MIDI files. I've created a metadata TSV and pointed my Tensorflow application to it as instructed in [the documentation](https://www.tensorflow.org/get_started/embedding_viz). The metadata parses correctly in Tensorboard, however, when I use the inspector on the right-most panel, many of the fields seem to be unsearchable, or at least yield zero results for any valid query. Searching the first 13 fields (columns) works correctly, however 3 of the last fields are unsearchable, specifically `artist_terms`, `artist_mbtags`,  and `artist_location` in `embedding_logdir/metadata.tsv`.
> 
> I'm finding this to be the case independent of whether regex mode is enabled or disabled. I can also confirm that these fields are being parsed correctly as I can select a data point and view the values for these problematic fields. I've also tried creating a metadata file with only those three problematic fieldnames and they continue to misbehave in this test as well.
> 
> ### Reproducing
> 
> I've attached my logdir complete with a checkpoint and metadata.tsv. To reproduce my results, extract the folder and launch Tensorboard from inside `embedding_logdir`'s parent directory like so:
> 
> ```
> tensorboard --logdir embedding_logdir
> ``` 
> 
> Tensorboard must be run from the parent directory of `embedding_logdir` to maintain the correct filepath I specified for the `metadata.tsv` file in my TF program. 
>  
> [embedding_logdir.tar.gz](https://github.com/tensorflow/tensorflow/files/825381/embedding_logdir.tar.gz)
>

**Comment by yunshangyue71** [comment]
when i open the tensoboard ,the page is printing "fetching sprite image..."
I don‘t known how to sovle the problem.

**Comment by yuqingqing** [comment]
I met the same problem as you

**Comment by yuqingqing** [comment]
> when i open the tensoboard ,the page is printing "fetching sprite image..."
> I don‘t known how to sovle the problem.

I known the reason for me, the path of my "sprite image" was setted wrong
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/16297907/68537943-7379b800-03a7-11ea-85bb-965d43569669.png">

**Comment by sanatmpa1** [comment]
@decentralion,

Can you please take a look at this [comment](https://stackoverflow.com/a/45462663/11530462) from a similar SO issue and also the above comment from @yuqingqing? Can you try setting the right path for the sprite image and let us know if it helps in resolving your issue? Thanks!
