### ISSUE TITLE
Debugger plugin initial dialog locks down entire page

### ISSUE THREAD

**Issue by nfelt** [tensorflow/tensorboard#793]
The initial dialog for the not-yet-active debugger plugin locks down the entire page.  Meaning that there's no way to navigate away from the debugger plugin short of editing the URL hash manually, since the dialog prevents you from clicking on anything else on the page, and offers no dismiss button.

Note that this applies to both versions, whether it's saying "ERROR: debugger is not enabled in this TensorBoard instance" or the further-along "Waiting for first Session.run() to connect..."

I'm guessing we want to bring this in line with the inactive messages used by the various other plugins when they aren't active and yet you select them anyway, where it shows up as text embedded within the page.  I actually kind of like how the dialog effect emphasizes that it's a transitory, non-default state of operation (and you can even see the UI structure of the plugin behind it, which sort of gives you a "taste" of what it will look like when you activate it, compared to the other inactive plugins which feel more "dead") but it does make it confusing to navigate to other plugins.

Maybe there's some way that we could make the inactive messages appear as kind of "in-between" dialogs with a z-index above the plugin-specific part of the page but below the navbar?  E.g. if we dim the lower page and leave the navbar undimmed, to hint that it's still accessible?

**Comment by nfelt** [comment]
@caisq FYI, don't seem to be able to assign this to you so I made Chi the victim for now.  I can also take a look at this, just not very familiar with the debugger plugin yet.

**Comment by caisq** [comment]
@nfelt, sorry about the inconvenience. Can you share what command I can use to reproduce this problem?  Did run tensorboard from `bazel run` or from a pip package?

Also, does it make sense to add me as a member, so bugs related to the debugger plugin can be assigned to me in the future?

**Comment by caisq** [comment]
Ah, I think I got it. I can reproduce this issue by doing the following:
1. `bazel run tensorboard ...`
2. Use the dropdown to navigate to the debugger tab.

So this bug isn't triggered if you don't click debugger. Is that what you see as well, @nfelt ?

**Comment by nfelt** [comment]
No problem! Mostly was using this as a place to also ask the larger question of how we want to keep this consistent across plugins, since as I said I actually like the dialog effect visually :)

Yeah, that's what I see - I just did `bazel run` from HEAD and then visited the debugger tab.

**Comment by nfelt** [comment]
Oh and re: adding you as a member, that makes sense to me.  @jart @chihuahua thoughts?

**Comment by jart** [comment]
Removing the dialog is something @caisq and I discussed earlier. Hopefully this can happen soon.
