### ISSUE TITLE
Event Purging no longer works

### ISSUE THREAD

**Issue by bigeagle** [tensorflow/tensorboard#803]
Hi there,

I restarted on of my training jobs and found my curves got messed up that my new training log did not override the old one. 

Then I found this old feature is removed due to the API upgrade. 
https://github.com/tensorflow/tensorboard/blob/f5dec9c1beaaaea4a03d42289f211a52f26cc346/tensorboard/backend/event_processing/plugin_event_accumulator_test.py#L284

I'm wondering if this `TODO` is still in someone's plan? Currently I have to use Jupyter and Plotly with the old `event_accumulator` API instead.

Cheers,

**Comment by jart** [comment]
It can continue to use the old event_accumulator API for the time being. However both of these are going to be replaced in the near future.

**Comment by nfelt** [comment]
This was affecting another user (#652) and was pretty easy to implement, so I have PR #807 out to address this.
