### ISSUE TITLE
Why my tensorboard opened on chrome appear the problem which has no dataflow

### ISSUE THREAD

**Issue by cgpeter96** [tensorflow/tensorboard#808]
when I opened in Edge ,it show the dataflow.But the arrow is in the wrong direction.
In chrome ,these is no dataflow.

![img](https://note.youdao.com/yws/api/personal/file/3923E61915AA40CC90D0616E7A5C7983?method=download&shareKey=d629538aec77e7dd97b9f0b7d9330d75)

i also updated my chrome .

**Comment by moonyoung430** [comment]
I have the same problem,Have you solved it?

**Comment by nfelt** [comment]
I'm guessing you are affected by https://github.com/tensorflow/tensorboard/issues/788.  Can you try updating to a version of TensorBoard 0.4.0+?  If that doesn't fix it, please let us know the exact version of TensorBoard you're using (it should print it out upon startup).

**Comment by moonyoung430** [comment]
@nfelt Thank you , and I have seen some issues just now , I'm tring to update tb.

**Comment by cgpeter96** [comment]
@nfelt   Thanks^_^ ,  I sloved the problem .
`pip install -U tensorflow-board==0.4.0rc3`  can slove it

**Comment by moonyoung430** [comment]
请问你更新tensorboard是在windows下吗？用那个命令？需要翻墙吗？


| |
杨玥
|
|
邮箱：yangvic@126.com
|

签名由 网易邮箱大师 定制

On 12/12/2017 10:39, Peter_chan wrote:

@nfelt Thanks^_^ , I sloved the problem .
pip install -U tensorflow-board==0.4.0rc3 can slove it
