### ISSUE TITLE
[docs] FAQ mentions non-existent `--debug` flag

### ISSUE THREAD

**Issue by jmw992** [tensorflow/tensorboard#815]
Tensor Board is not loading data properly.  I am trying to follow the debug instructions given below. 

[(https://github.com/tensorflow/tensorboard/blob/master/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong)]

 At the first step of running the debugger on logdirectory path I get the following output.

(tensorflow) C:\Users\jw\Documents\tfpractice>tensorboard --logdir DIRECTORY_PATH --debug
usage: tensorboard.exe [-h]
                       [--debugger_data_server_grpc_port DEBUGGER_DATA_SERVER_GRPC_PORT]
                       [--logdir LOGDIR] [--host HOST] [--port PORT]
                       [--purge_orphaned_data [PURGE_ORPHANED_DATA]]
                       [--nopurge_orphaned_data]
                       [--reload_interval RELOAD_INTERVAL] [--db DB]
                       [--inspect [INSPECT]] [--noinspect] [--tag TAG]
                       [--event_file EVENT_FILE] [--path_prefix PATH_PREFIX]
tensorboard.exe: error: argument --debugger_data_server_grpc_port: expected one argument`

I haven't been able to find information on this particular error, would love some help on it.  I am using tensor flow version 1.4 and running it with anaconda version 123 on windows 1.6.5

**Comment by jmw992** [comment]
I solved my own problem.  I was just copying pasting `tensorboard --logdir=path/to/log-directory` where path/to/log/directory should have been my actual path.  All you do is put your actual path there which in the case of the example code looks like.
`tensorboard --logdir=C:\tmp\tensorflow\mnist\logs\mnist_with_summaries\train`

**Comment by nfelt** [comment]
Good to hear you were able to solve it.

**Comment by jmw992** [comment]
Yeah, you actually have to put the your file path in the --logdir
Directory_Path.  So you have to find the correct file path for that
tensorflow folder on your computer.

**Comment by jmw992** [comment]
Unfortunate, sorry it started working for me after I did that.  Best of
luck figuring it out
