### ISSUE TITLE
Really wacky graphs

### ISSUE THREAD

**Issue by atav32** [tensorflow/tensorboard#828]
Maybe related to https://github.com/tensorflow/tensorboard/issues/652 and https://github.com/tensorflow/tensorboard/issues/803?

<img width="1251" alt="screen shot 2017-12-18 at 10 16 01 pm" src="https://user-images.githubusercontent.com/622185/34143419-77b63434-e441-11e7-81c9-787ca30d23ee.png">

**Comment by chihuahua** [comment]
@atav32, indeed, at the outset, this seems related to those issues resolved by #807. One way to confirm is to switch to wall time or relative and observe if the back-and-forth behavior is gone.

**Comment by gahrb** [comment]
Not sure, if #807 did resolve this issue, but I have a similar looking one:
![image](https://user-images.githubusercontent.com/6310891/50723901-7602e580-10e4-11e9-94cd-5987afc8a0ee.png)
This is independent of the wall time, relative or step selection:
![image](https://user-images.githubusercontent.com/6310891/50723907-95017780-10e4-11e9-9881-a3da3584f048.png)

This happens quite often, when tensorboard is loading existing datasets. If tensorboard is started before the scalars are written to the logdir the graphs look normal.

I run tensorboard on ubuntu 16.04 (server) and 18.04 (laptop).

[proposed Label] bug/performance

**Comment by bileschi** [comment]
Assuming this issue is resolved.  Please re-open if it still exists. Thanks!
