### ISSUE TITLE
pr_curve_streaming_op showing curves for individual batches but not the enitire dataset

### ISSUE THREAD

**Issue by hkhatod** [tensorflow/tensorboard#840]
According to the documentation in README:  

pr_curve_streaming_op

Perhaps the most prevalent way of collecting data during TensorFlow runs is via the pr_curve_streaming_op method. **This streaming op accumulates true/false positive and true/false negative counts _across batches_.**.

My curves are also showing results for each individual batch. Am I wrong in expecting it to aggregate over all the batches towards the end ?

How do I go about curves for entire dataset ?. I am calling this op after each batch.  I can slide though and see data for intermittent batches but not the combined for entire dataset.

  ```
with tf.name_scope("pr-curves"):
	  for i in range(num_classes):
		with tf.name_scope('%s' % self.text_labels[i]):
			_, self.update_op = summary_lib.pr_curve_streaming_op('pr_curve', predictions=self.probabilities[:,i], labels=tf.cast(self.input_y,tf.bool)[:,i], num_thresholds=50)```

**Comment by chihuahua** [comment]
The update op accumulates data across batches - and then custom logic can determine the frequency with which to write data.

For instance, in this example, we update counts at each step but only write cumulative PR curve data to disk every 5 steps:

```python
writer = tf.summary.FileWriter(log_dir, graph)
for i in xrange(NUM_STEPS):
  summary, _ = sess.run([merged_summary_op, update_op])
  if i % 5 == 0:
    writer.add_summary(summary, i)
```

Let me know if that makes sense. Thanks!

**Comment by hkhatod** [comment]
Thanks!!!
