### ISSUE TITLE
All my cpu is eaten by tensorflow

### ISSUE THREAD

**Issue by Nirvanabc** [tensorflow/tensorboard#841]
Sometimes I run tensorflow with neural network, but I have to work at the same time. So how can I say tensorflow to
use only some of my CPUs? I've found some functions for GPU, [1], I want something like this for CPU.

[1]: https://www.tensorflow.org/tutorials/using_gpu

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
