### ISSUE TITLE
More information in tensorboard.

### ISSUE THREAD

**Issue by nikitxskv** [tensorflow/tensorboard#842]
Hello!

Do you plan to add to tensorboard information about the iteration with the best score and training remaining time?

**Comment by jart** [comment]
It might be possible for us to offer that type of functionality, but we'd need to have heuristics or some type of configuration language that allows you to define what it means, for example, for a run to the best. That type of analysis might be better served by writing a Python script that uses our `EventAccumulator` class, which would allow you to analyze your data yourself and make that sort of determination in an automated fashion.
