### ISSUE TITLE
tf.summary.FileWriter doesn't flush events because event file has disappeared

### ISSUE THREAD

**Issue by AlePag** [tensorflow/tensorboard#845]
I use Tensorflow 1.4 with TensorBoard 0.4.0-rc3 on Windows 10. The event file is correctly create but file writer can't flush events, maybe some windows process delete temporarly this file and it doesn't find it.
![immagine](https://user-images.githubusercontent.com/34540362/34453686-990c9796-ed5a-11e7-889a-01591e6841f8.png)

Error in event_writer implementation:

![immagine](https://user-images.githubusercontent.com/34540362/34453711-361bf3e2-ed5b-11e7-9196-458bd16569da.png)
![immagine](https://user-images.githubusercontent.com/34540362/34453717-50dfba88-ed5b-11e7-8f02-eae78f51f62f.png)

**Comment by chihuahua** [comment]
Indeed, flushing fails if the events file being written to is removed. I think the question is ... what could be deleting the file in your case? First off, do you observe that happening? As in, can you confirm that the events file is gone via your file system browser?

**Comment by AlePag** [comment]
File was temporarly hidden by OneDrive. Project was in a OneDrive directory. I resolved with a local project.

**Comment by chihuahua** [comment]
Thank you for reporting back!
