### ISSUE TITLE
ContextualVersionConflict html5lib 1.0.1

### ISSUE THREAD

**Issue by pfc** [tensorflow/tensorboard#854]
tensorboard doesn't seem to recognize html5lib after an update
This is on arch.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (tensorflow-tensorboard 0.4.0rc2 (/usr/lib/python3.6/site-packages), Requirement.parse('tensorflow-tensorboard==0.4.0rc1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (html5lib 1.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999'), {'bleach'})
```

**Comment by nfelt** [comment]
What command were you running to do the update, exactly?  Do you know where you're getting the pinned `tensorflow-tensorboard==0.4.0rc1` requirement from?

**Comment by pfc** [comment]
I uninstalled and installed from the tensorboard package.  No clue where that requirement comes from, the 0.4.0rc1 is the version installed, no clue where it is being checked from.  I get that error any time I call tensorboard.

**Comment by nfelt** [comment]
Do you have the exact command line command you ran to do the uninstall and install?

If you can provide the results of `pip list` maybe there's something that's causing the conflict.

**Comment by pfc** [comment]
I tried removing html5lib from requires.txt however this caused further errors
```
pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
bleach (1.5.0)
Brlapi (0.6.6)
canlib (1.1.23)
canmatrix (0.5)
canopen (0.4.0)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
cupshelpers (1.0)
cycler (0.10.0)
Cython (0.27.3)
decorator (4.1.2)
Django (1.11.2)
docutils (0.14)
enum34 (1.1.6)
gufw (17.10.0)
html5lib (1.0.1)
idna (2.6)
isc (2.0)
louis (3.4.0)
Markdown (2.6.9)
matplotlib (2.1.1)
numpy (1.13.3)
olefile (0.44)
opencv (1.0.1)
openhmd (1.0)
packaging (16.8)
Pillow (4.3.0)
pip (9.0.1)
protobuf (3.5.0)
psutil (5.4.1)
pycairo (1.15.4)
pycuda (2017.1.1)
pycups (1.9.73)
pycurl (7.43.0.1)
pydbus (0.6.0)
pygame (1.9.3)
pygobject (3.26.1)
pyparsing (2.2.0)
pyserial (3.4)
pysmbc (1.0.15.8)
python-can (1.5.2)
python-dateutil (2.6.1)
python-sane (2.8.3)
pytools (2017.6)
pytz (2017.3)
pyxdg (0.25)
requests (2.18.4)
setuptools (38.2.5)
simplejson (3.13.2)
six (1.11.0)
smbus (1.1)
team (1.0)
tensorflow (1.4.1)
tensorflow-tensorboard (0.4.0rc1)
termcolor (1.1.0)
urllib3 (1.22)
webencodings (0.5.1)
Werkzeug (0.13)
wheel (0.30.0)
```

**Comment by nfelt** [comment]
Can you downgrade your html5lib to 0.9999999 (seven 9's) to satisfy the bleach requirements?

If not, I'm not sure what to suggest other than maybe installing tensorflow and tensorboard instead a virtualenv where you only have their dependencies as pip packages and nothing else that might conflict.

**Comment by pfc** [comment]
pip install seemed to install 1.0.0a6 instead of latest tensorboard (I believe 1.5.0?) so I'm not sure how to install tensorboard "properly" even if in a virtualenv which i was trying to avoid

**Comment by nfelt** [comment]
You probably did `pip install tensorboard` which is an unaffiliated derivative of TensorBoard: https://pypi.python.org/pypi/tensorboard  The official TensorBoard pip package is `tensorflow-tensorboard`.  You can either install it directly, or you can install TensorFlow following the standard instructions which include using a virtualenv and it will also install TensorBoard as a dependency.

**Comment by pfc** [comment]
`pip install tensorflow-tensorboard` fixed my problem
The naming convention is... not very helpful.

**Comment by nfelt** [comment]
Yes, it's confusing.  The developer who decided to claim `tensorboard` as their own pip package name didn't exactly ask us first, and we've been trying to persuade them to rename it.

**Comment by nbro** [comment]
> `pip install tensorflow-tensorboard` fixed my problem
> The naming convention is... not very helpful.

I tried to do this, but now I am getting the error 

> AttributeError: module 'tensorboard.lazy' has no attribute 'lazy_load'

with TF 2.1.

**Comment by rithiksachdev** [comment]
Hi @nbro, Releases prior to 1.6.0 were published under the tensorflow-tensorboard name and may be found at https://pypi.python.org/pypi/tensorflow-tensorboard - [Source of text](https://pypi.org/project/tensorboard/). You can refer #1862 and #1907. If the problem still persists, please run diagnostics and create a new issue in the provided format.

**Comment by nbro** [comment]
@rithiksachdev https://github.com/tensorflow/tensorboard/issues/1862#issuecomment-521874990 did the trick, but I don't know why. Another comment there says that `tensorflow-tensorboard` is no longer needed. I installed TensorFlow  2.1 and it automatically installed `tensorboard` (at least, according to `pip list`), but then I don't understand why I was getting that error `pkg_resources.ContextualVersionConflict`.

**Comment by rithiksachdev** [comment]
@nbro, from my past experience I can say that there could be an old version of a dependency that was installed.
