### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory on deep Q learning model

### ISSUE THREAD

**Issue by AlienSmith** [tensorflow/tensorboard#869]
I was having fun with the Deep Q learning model, which came from https://github.com/dennybritz/reinforcement-learning/blob/master/DQN. Then after 750 episodes this error popped up. 
![7](https://user-images.githubusercontent.com/20869223/34823300-da6cc144-f704-11e7-8046-9b3b85a958c2.png)
![1](https://user-images.githubusercontent.com/20869223/34823246-abb78032-f704-11e7-9360-1fa63c3c4d8d.png)
![2](https://user-images.githubusercontent.com/20869223/34823248-ac0a4ace-f704-11e7-9bd9-378916f6c0ea.png)
![3](https://user-images.githubusercontent.com/20869223/34823249-ac3aff84-f704-11e7-908f-61d1db283bf2.png)
![4](https://user-images.githubusercontent.com/20869223/34823250-ac6fa4dc-f704-11e7-8505-7b77b68eea54.png)
![5](https://user-images.githubusercontent.com/20869223/34823256-b1225236-f704-11e7-836e-8f13ad5993b3.png)
![6](https://user-images.githubusercontent.com/20869223/34823257-b17a07ec-f704-11e7-9211-13a26b568010.png)

I was running this code on Ubuntu 14.04 with a 8G graphic card(GTX 1070). I have had libav-tools installed before I ran the code.
I will try to reduce the batch size to see whether similar error will pop up again.
Please help me solve this problem.

**Comment by chihuahua** [comment]
Could you please file this issue under TensorFlow? https://github.com/tensorflow/tensorflow/issues

TensorFlow folks more likely have the relevant knowledge to help you here. Thank you!
