### ISSUE TITLE
Tensorboard does not display connections in graph

### ISSUE THREAD

**Issue by nanoix9** [tensorflow/tensorboard#876]
I run the example `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py` and then open tensorboard with `tensorboard --logdir /tmp/tensorflow/mnist/logs/mnist_with_summaries/`. However, the connections are not displayed, only the nodes are shown. I cannot paste image here so please refer to <https://stackoverflow.com/questions/48248143/tensorboard-does-not-display-connections-in-graph>

**Comment by jart** [comment]
Probably a duplicate of https://github.com/tensorflow/tensorboard/issues/425. Try `pip install tb-nightly`.

**Comment by nanoix9** [comment]
@jart It works, thanks!
