### ISSUE TITLE
Graph PNGs for large graphs are too small to be useful.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#88]
PNGs downloaded from the graph dashboard are too small to be useful. To repro, try loading the attached graph (pb.txt file) into an instance of TensorBoard and downloading a PNG. The resulting PNG is 300x150 (way too blurry when expanded):

![graph](https://user-images.githubusercontent.com/4221553/27245602-6e41f5f0-52a1-11e7-9e67-f3f48d2d4f18.png)

[graph.pb.txt](https://github.com/tensorflow/tensorboard/files/1081997/graph.pb.txt)
(The files normally end in .pbtxt, but GitHub only supports txt files.)

**Comment by wchargin** [comment]
Looking into this now. Appears to be a simple issue with the d3v4 migration. Will report back shortly.

**Comment by wchargin** [comment]
This is still fixed, right? Or did it regress?

**Comment by chihuahua** [comment]
Ah yeah, this is fixed. No need for action. I was just organizing my list of issues.
