### ISSUE TITLE
Overlapping PR curves to compare different models

### ISSUE THREAD

**Issue by eisenjulian** [tensorflow/tensorboard#894]
Not sure if a feature request or bug, please correct me accordingly. I'm using the version 0.4.0 of TensorBoard although I noticed the latest version of the plugin has some differences

I'm using the new estimators API for text binary classification task and I'd like to generate a PR curve for each model (or checkpoint). I'm able to do so with something the following snippet:

```
import tensorflow as tf
from tensorboard import summary as summary_lib

classifier = tf.estimator.LinearClassifier(...
classifier.train(...
eval_predictions = np.array([p['logistic'][0] for p in classifier.predict(input_fn=eval_input_fn)])
pr = summary_lib.pr_curve('', predictions=eval_predictions, labels=eval_labels, num_thresholds=21, display_name='pr')
with tf.Session() as sess:
    writer = tf.summary.FileWriter(classifier.model_dir, sess.graph)
    writer.add_summary(sess.run(pr), global_step=0)
    writer.close()
```

If I run this for each model I get a different event file created in each of the model directories. The problem is that I cannot find a way to get these curves to be displayed on the same plot to be able to easily compare them, they display side by side. There's a `tag` argument in the pr_curve op function that I've played with but couldn't make work.

Thanks for your help!

**Comment by chihuahua** [comment]
To compare PR curves in the same plot, make sure all curves share the same tag (Tag is also affected by various levels of scope.). TensorBoard associates each individual directory containing events files with a single run. Each plot contains curves with the same tag and different runs.

Could you try starting TensorBoard pointed at a high level directory containing all the model directories? And then make sure that all PR curve summaries are tagged correctly? You probably don't need to alter the display name.

**Comment by eisenjulian** [comment]
Thanks for replying so quickly @chihuahua . I'm running Tensorboard as you suggested, from the parent directory of all the models. I suspected the same thing you mentioned about the tags, the strange thing is that even though I am setting the `tag` (first param of the `pr_curve` method) to be that same thing for all models as you said, when I see it in Tensorboard it's adding underscores with increasing integers to each of the tags, so the first one will be tagged correcly, the next one will be tagged `..._1`, the next one `..._2` and so on . Is there some hidden counter that I should reset on the tags before writing the next summary? I've noticed that it does work as intended if I restart the python kernel between each model run.

**Comment by chihuahua** [comment]
Thank you for the screenshot. I believe that issue https://github.com/tensorflow/tensorflow/issues/6007 is related. When `tf.name_scope` is called twice with the same string parameter, TensorFlow creates uniquely named scopes by appending indices, thus producing different tags. Restarting the python kernel forces TensorFlow to start with a new graph and thus a new set of scopes.

I wonder if we have control over scoping via the `tf.estimator.LinearClassifier` API. In between the classifiers being constructed, could you try calling `tf.reset_default_graph()`?

**Comment by eisenjulian** [comment]
That worked! Thanks a lot @chihuahua

**Comment by chihuahua** [comment]
Good to know! Thanks for getting back.

**Comment by datlife** [comment]
Thanks @chihuahua for the tip and @eisenjulian for raising the question. I was able to plot with multiple PR curves. I think it is also necessary to show the code for those who might need later:

```python
summary.op(
        tag='pr_curve',
        labels=tf.cast(labels, tf.bool),
        predictions=tf.cast(scores, tf.float32),
        num_thresholds=num_thresholds,
        display_name='Precision - Recall',
)
merged_op = tf.summary.merge_all()

event_dir = os.path.join(logdir, run_name)
writer = tf.summary.FileWriter(event_dir)

with tf.Session() as session:
    writer.add_summary(session.run(merged_op), global_step=step)

# *** This line would allow to multiple pr curves in one plot
tf.reset_default_graph()
writer.close()

```

![screenshot from 2018-02-05 15-44-18](https://user-images.githubusercontent.com/13214917/35834641-8e7716dc-0a8b-11e8-98f3-162165865eb3.png)
