### ISSUE TITLE
Distorted scalar charts on Firefox after toggling expand and log scale

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tensorboard#90]
Migration of https://github.com/tensorflow/tensorflow/issues/8199

### Environment info
Operating System: 16.04 LTS
Firefox: 51.0.1 (64-bit)
TF: 1.0 (installed via pip)

> ### Steps to reproduce (Firefox only)
> 1. On the 'Scalars' tab for tensorboard, view the graph of a scalar summary (eg _cost_ or _accuracy_) by **expanding the tab**. ![tensorboard - mozilla firefox_027](https://cloud.githubusercontent.com/assets/252960/23708510/0bcd8b5a-040e-11e7-8a19-e2eb7ee208af.png)
> 2. **Click on the expand icon** ![tensorboard - mozilla firefox_028](https://cloud.githubusercontent.com/assets/252960/23708524/1227e784-040e-11e7-9c5c-e8f466df5581.png)
> 3. **Enable** log scale of y-axis ![tensorboard - mozilla firefox_029](https://cloud.githubusercontent.com/assets/252960/23708530/162e403a-040e-11e7-8628-fbd04ae05642.png)
> 4. **Disable** log scale of y-axis (note the bug happens regardless of whether you do this) ![tensorboard - mozilla firefox_028](https://cloud.githubusercontent.com/assets/252960/23708524/1227e784-040e-11e7-9c5c-e8f466df5581.png)
> 5. **Click on expand icon** to shrink the graph.
> 
> The graph is now overflowing: ![tensorboard - mozilla firefox_030](https://cloud.githubusercontent.com/assets/252960/23708531/18f031a2-040e-11e7-9e22-8c76415ddb14.png)
> 
> ### What other attempted solutions have you tried?
> Tried to reproduce in Chromium 55.0.2883.87 but unable to.
> 
> 
>

**Comment by stephanwlee** [comment]
Could not reproduce this on Firefox Quantum (60.0)
