### ISSUE TITLE
tensorboard audio tab has wrong readme link

### ISSUE THREAD

**Issue by NightFantomJ2** [tensorflow/tensorboard#910]
(probably goes for other tabs too, but I noticed it there)
it says:

"
No audio data was found.
Probable causes:

You haven't written any audio data to your event files.
TensorBoard can't find your event files.
If you're new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial .

If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub.
"

and both readme links link to [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md), which is a 404, probably since tensorboard got split off of the tensorflow repository.

**Comment by nfelt** [comment]
I think you just need to update your version of TensorBoard, this should have been fixed by #127 several versions ago.  Please re-open if that doesn't fix it.

**Comment by NightFantomJ2** [comment]
I installed tensorboard through pip, and apparently that isn't the official one, my bad.
