### ISSUE TITLE
The "upload" button doesn't work in the online embedding projector

### ISSUE THREAD

**Issue by Fanchao-Qi** [tensorflow/tensorboard#911]
I find that the "upload bookmark file" button doesn't work in the [projector.tensorflow.org](projector.tensorflow.org). 
I can download the bookmark file but I can't upload it.

**Comment by MarkDaoust** [comment]
This is a duplicate of #835

**Comment by nfelt** [comment]
Duplicate of #835

**Comment by nfelt** [comment]
Thanks @MarkDaoust for pointing that out!  There is some further discussion on #835.
