### ISSUE TITLE
Productionize TensorBoard

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorboard#92]
**Note: This information is somewhat of date. New information will be shared shortly.**

We have just begun working on making TensorBoard capable of running as a multitenant production service. This issue will be tracking progress and commits relating to this effort. 

## Prerequisites

- [x] Refactor plugin API to support DB https://github.com/tensorflow/tensorboard/commit/832248cc178ea6149e6066a2fb3b5d115a6eb02f
- [ ] Refactor EventAccumulator into plugins
- [ ] SQL templatization

## Features

- [ ] Persistent storage
- [ ] Multiple experiments
- [ ] Experiment listing page
- [ ] Experiment comparison
- [ ] Experiment search
- [ ] Event log ingestion service
- [ ] Event log uploader
- [ ] User identities

## Database Support

- [ ] SQLite
- [ ] Cloud Spanner
- [ ] PostgreSQL
- [ ] MySQL

## Cache Support

- [ ] Redis
- [ ] Memcached
- [ ] Cloud Memcache
- [ ] Amazon ElastiCache

## Productionization

- [ ] Kubernetes + Docker
- [ ] Scripts to deploy to GCE
- [ ] Scripts to deploy to AWS

## Monitoring

- [ ] Stackdriver configuration

## Security

- [ ] Group ACLs for experiments

Please note that the list above contains both things: a) we intend to write; and b) *would be nice* to write. We may not necessarily have time to implement all of the above. If any of these checkboxes are of particular importance to you, or you'd like to see some added, or would like to contribute to their development, then please let us know.

**Comment by weberxie** [comment]
Hi, @jart this issue looks like a vast project, whether there is a design document to describe what you want to make? It is convenient for us to take part in.

**Comment by jlewi** [comment]
@jart How will non Tensor summaries be stored in the database? Will they be converted into Tensors and stored in the [Tensors table](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/db.py)?

**Comment by bhack** [comment]
Any news on this? Can you expose a Roadmap related to TB versions?

**Comment by jart** [comment]
Still working on getting some functionality off the ground. I plan to communicate as this happens.

**Comment by cwbeitel** [comment]
Experiment listing, comparison, and search are awesome features.

**Comment by jart** [comment]
I'm closing this issue out because a lot of the things we listed earlier are too ambitious and potentially overlap with the work other folks are doing. We'll need to think more about how we want to approach this topic delicately, in a way that dovetails with the efforts of other teams and companies.

**Comment by thinxer** [comment]
Hi @jart , would you please share some stories about what other teams are doing on this topic? Maybe the community can work out a pluggable interface for multi-tenant usages.

**Comment by alexattia** [comment]
Do you plan to add security (password login for instance) to TensorBoard?

**Comment by guhur** [comment]
> Do you plan to add security (password login for instance) to TensorBoard?

@alexattia an [alternative solution](https://stackoverflow.com/questions/51693983/has-anybody-found-a-way-to-make-tensorboard-password-protected) consists in using TensorBoard behind a web server and adding an authentication on the web server.
