### ISSUE TITLE
Tensorboard should have a --help flag

### ISSUE THREAD

**Issue by jankukacka** [tensorflow/tensorboard#936]
Running the tensorboard from command line with `--help` flag throws and error:

> `tensorboard --help`
> `Traceback (most recent call last):`
> `  File "/usr/local/bin/tensorboard", line 11, in <module>`
> `    sys.exit(main())s` 
> `  File "/usr/local/lib/python2.7/dist-packages/tensorboard/main.py", line 44, in main return program.main(default.get_plugins(),`
> `  File "/usr/local/lib/python2.7/dist-packages/tensorboard/default.py", line 71, in get_plugins debugger = debugger_plugin_loader.get_debugger_plugin()`
> `  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/debugger/debugger_plugin_loader.py", line 46, in get_debugger_plugin`
> `    if FLAGS.debugger_data_server_grpc_port is None:`
> `  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__`
> `    wrapped(_sys.argv)`
> `  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 630, in __call__ name, value, suggestions=suggestions)`
> `absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'help'`

**Comment by nfelt** [comment]
Well, it throws an error because --help is not a valid flag for TensorBoard.  I'll reframe this slightly as a feature request for such a flag to exist.

**Comment by jankukacka** [comment]
Hmmm, then why does TensorBoard write the following:

`ValueError: A logdir must be specified when db is not specified. Run tensorboard --help for details and examples.`

if you run it without any arguments? Damn confusing 😕 But thanks for response anyways!

**Comment by nfelt** [comment]
Ah, okay - that is reasonable confusion!  I think we used to use a different flag handling library that probably supported `--help`.  Thanks for bringing that to our attention, we'll either add a `--help` flag or change that message.

FYI, when it says "a logdir must be specified" that just means you should run `tensorboard --logdir /path/to/your/tensorflow/log/directory`.  See here for slightly more detail: https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard#launching_tensorboard

**Comment by sakaia** [comment]
I am executing tensorboard on Windows 7 with following package.
> pip list
snip
tensorflow-tensorboard (1.5.0)
snip

and execute as follows
===
> C:\Users\sakaia\work\tensorflow>tensorboard --help

       USAGE: C:\Program Files\Python35\Scripts\tensorboard [flags]

Try --helpfull to get a list of all flags.
===

The output code should be follows.
  https://github.com/tensorflow/tensorflow/blame/v1.5.0/tensorflow/python/platform/app.py#L77

In my opinion, it should be upgrade tensorflow and tensorboard first.

**Comment by nfelt** [comment]
Yeah, now that I test this out it looks like the `--help` flag does work as @sakaia mentions.  @jankukacka could you try upgrading to tensorflow/tensorboard 1.5.0+?  I'll close this out for now but if you still see the issue with 1.5.0+ please re-open.
