### ISSUE TITLE
Scalar summaries X-axis range not always adjusted on update

### ISSUE THREAD

**Issue by gonnet** [tensorflow/tensorboard#937]
When TensorBoard reloads data, sometimes the X-axis of the scalar summaries is adjusted to accommodate the new data, and sometimes it is not.

This does not depend on whether the plot is expanded or not, or whether the "Fit domain to data" button had been hit previously or not.

Different plots on the same page will behave differently, and some plots may change their behaviour randomly.

**Comment by nfelt** [comment]
Thanks for the report.  Is there any chance you can help us reproduce this, e.g. with a small example TF job that will show this behavior?  Or perhaps at least a screenshot of a page with some plots adjusted and some not?

Also, what version of TensorBoard are you using?

**Comment by benvanik** [comment]
Unfortunately I can't share a TF job, but I can confirm I'm seeing the same issue. I'm using TensorBoard 0.4.0a0.

Here's some shots showing it; I've fully refreshed the page and expanded a single scalar value.

Immediately after expanding the scalar, fitting it to view, and clicking the fit domain to data button:
![image](https://user-images.githubusercontent.com/75337/36229738-221eedb2-118d-11e8-9ea8-c41cc09a437b.png)

30 sec later:
![image](https://user-images.githubusercontent.com/75337/36229754-2e9db438-118d-11e8-8b77-a6bf9e72d488.png)

30 sec later:
![image](https://user-images.githubusercontent.com/75337/36229830-599b7bf2-118d-11e8-844b-56ceae47136c.png)

Bug makes it hard to use tensorboard as a nifty training dashboard :(

**Comment by NKUCodingCat** [comment]
Why not make tensorboard auto click fit in domain when updating data
I am suffering same issue and I dont have any knowledge about frontend...

**Comment by bileschi** [comment]
There have been many performance updates since this post.  Please re-open if this is still an issue.

**Comment by Linusnie** [comment]
afaik this is still a problem. I find myself often having to click "fit domain to data" on every plot individually whenever new data comes in which is not ideal. Any way around that?

**Comment by bileschi** [comment]
Hi @Linusnie , can you share your version information?  Specifically, 

## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):

Thanks!
