### ISSUE TITLE
Load data button on projector

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorboard#94]
@qwertymj in https://github.com/tensorflow/tensorflow/issues/9621 asked for the load data button on projector:

> At http://projector.tensorflow.org/  we can choose a data file from our own computer by the `Load data` button(see the red rectangle below) and visualize the high-dimensional data
> ![image](https://cloud.githubusercontent.com/assets/7208819/25652477/fbc9675e-301a-11e7-931f-c7bb22fbdea2.png)
> ![image](https://cloud.githubusercontent.com/assets/7208819/25652234/ce6c2158-3019-11e7-9c10-47fe2a1e2224.png)
>
> But when I tried to using Tensorboard embedding on my own computer (follow the instruction at https://www.tensorflow.org/get_started/embedding_viz and start a server on localhost:6006 by command `tensorboard --logdir=LOG_DIR` )
> I just find the `Load data` button doesn't exist (see below)
>
> ![image](https://cloud.githubusercontent.com/assets/7208819/25652904/0f4ff566-301d-11e7-9a1e-4d097d108349.png)
>
> So I want to ask when I run Tensorboard on localhost, how can I enable the load data button like http://projector.tensorflow.org/ does, thus I can visualize the high-dimensional data by uploading my file rather than writing code ?
>
> thanks a lot :)

**Comment by jart** [comment]
The GUI he's referring to is a closed source HTML file that wraps vz-projector-app and sets serving-mode to demo. The code seems to be there in the TensorBoard codebase already, if someone wants to flip the flag.

However @dsmilkov probably disabled the load data feature in TensorBoard for a reason. I'm assigning to him for comment.

**Comment by dsmilkov** [comment]
We disabled the load data button in TensorBoard since in TensorBoard the use case is for the embeddings to come from the TF checkpoint file.

If you have your embeddings in a tsv file, then projector.tensorflow.org should work. Note that projector.tensorflow.org is a static js/html page so your data doesn't leave your computer.

Hope this helps!

**Comment by ybdesire** [comment]
+1 , Really need this feature.

**Comment by jkbcm** [comment]
+1 This feature would be really useful.  As others have found, replicating the outputs of word2vec in TensorFlow can be non-trivial.

**Comment by thegrims** [comment]
@dsmilkov @jart I'm working on customizing the standalone embeddings projector, could you point to where the serving-mode is set to demo vs server or proto? I dug around a while in the codebase but wasn't able to find anything.

**Comment by dsmilkov** [comment]
See this pull request for the relevant files: https://github.com/tensorflow/tensorboard/pull/1784 for how to launch it in standalone mode.

The actual setting of serving-mode is done in https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/vz_projector/standalone.html
