### ISSUE TITLE
tensorflow does not write protobuf summaries for eval operations in python3

### ISSUE THREAD

**Issue by alienczf** [tensorflow/tensorboard#966]
This issue is discovered when i tried to add statistics from pr_curve_streaming_ops to the dict of eval_metric_ops in tf.estimator.EstimatorSpec.

Running evaluate causes the following warning to be displayed. But I am able to retrieve the eval output directly from tf.Estimator.evaluate and it appears that the protobuf serialization is working.
```python
res = model.evaluate(...)
summary_pb2.Summary.FromString(res['PR_0'])
# output
WARNING:tensorflow:Skipping summary for PR_0, must be a float, np.float32, np.int64, np.int32 or int or a serialized string of Summary.
value {
  tag: "PR_0/pr_curves"
  tensor {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 6
      }
      dim {
        size: 201
      }
    }
...
}
```

Checking the content of the file and tensorboard shows that the protobuf data is missing:
```python
from tensorboard.backend.event_processing.event_file_loader import EventFileLoader
eval_loader = EventFileLoader('/tmp/nkm/resPool003551/eval/events.out.tfevents.1518280897.dev15-wslpt')
eval_events = list(eval_loader.Load())
eval_events[3]
# output
wall_time: 1518280897.7904496
step: 3923
summary {
  value {
    tag: "eval_mean_accuracy"
    simple_value: 0.2056954801082611
  }
  value {
    tag: "loss"
    simple_value: 911411.1875
  }
}
```
![image](https://user-images.githubusercontent.com/17044118/36063759-17181570-0ebc-11e8-99f2-693381cab81c.png)

After some further digging, it appears that the culprit lies in the string type check in tf.estimator.estimator._write_dict_to_summary: https://github.com/tensorflow/tensorflow/blob/16fabd1fc3408252d816bf53698df8f05c9ee304/tensorflow/python/estimator/estimator.py#L1106

protobuf.SerializeToString in python 3 returns bytes instead of string. As such, the type check will cause all protobuf serialized stats to fail during estimator.evaluate for python3. To have a version compatible fix, we will probably need a `if (py2 and isinstance(data, str)) or (py3 and isinstance(data, bytes))` check instead, six can't save us here =(

I'm new to this github but do let me know if this issue should be moved over to tensorflow instead.

**Comment by chihuahua** [comment]
This looks fixed at TensorFlow head: https://github.com/tensorflow/tensorflow/blob/e3d63c81f15f962c0841b3a6f97b7df93b0343cf/tensorflow/python/estimator/estimator.py#L1115

Closing. Thank you for reporting!
