### ISSUE TITLE
Custom scalar not auto updating graph

### ISSUE THREAD

**Issue by aforslow** [tensorflow/tensorboard#971]
I have started using the custom scalar plugin and have realized that the graphs made from this plugin don't auto update. When I switch to the scalars tab, this does auto update as expected, so there doesn't seem to be any problems with the auto updating functionality. When I manually update the page, the custom scalar graphs also update, so they can be updated. I have tried running tensorboard in the nightly build in hopes of this issue already having been solved, but it doesn't work even here.

**Comment by chihuahua** [comment]
Thank you for reporting. I am trying to reproduce the issue. I have tried running the custom scalars demo and then simulating new runs being generated by creating new sub-directories within the log directory.

In 30 seconds, the custom scalars dashboard auto-reloads and seems to pick up the new runs as expected: 

![image](https://user-images.githubusercontent.com/4221553/36237768-dcabc61c-11b2-11e8-9292-04d6172f2d9e.png)

Do you see any errors in the Chrome developer console?

**Comment by wchargin** [comment]
Fixed by #2150.
