### ISSUE TITLE
F1 max calculation wrong in the pr_curve plugin documentation

### ISSUE THREAD

**Issue by tbrieden** [tensorflow/tensorboard#980]
I just found a minor issue in the README.md (tensorboard/tensorboard/plugins/pr_curve/README.md) of the pr_curve plugin. Currently, F1 max is calculated like this:

```
# We can also compute metrics such as F1 max to be shown in the scalar
# dashboard.
summary_lib.scalar(
    'f1_max',
    tf.reduce_max(
        2.0 * data.precision * data.precision / tf.maximum(
            data.precision + data.recall, 1e-7)))
```

However, the correct calculation should be:

```
    tf.reduce_max(
        2.0 * data.precision * data.recall / tf.maximum(
            data.precision + data.recall, 1e-7)))
```

Note the change from data.precision to data.recall in the numerator.

**Comment by nfelt** [comment]
Indeed you're right, that isn't the correct formula.  Thanks for pointing this out!
