### ISSUE TITLE
No Module named tensorflow while using tensorboard

### ISSUE THREAD

**Issue by mvashishth** [tensorflow/tensorboard#981]
Tried using Tensorboard

> tensorboard  --logdir=/media/xaiphron/Mayur/demo/

but it throws
> Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/main.py", line 28, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

Then I tried 
> python3 main.py --logdr=/media/xaiphron/Mayur/demo/

It gives

> 2018-02-17 16:52:53.731335: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
/home/xaiphron/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    run_main()
  File "main.py", line 36, in run_main
    tf.app.run(main)
  File "/home/xaiphron/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/home/xaiphron/.local/lib/python3.6/site-packages/tensorboard/program.py", line 165, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/home/xaiphron/.local/lib/python3.6/site-packages/tensorboard/program.py", line 189, in create_tb_app
    raise ValueError('A logdir must be specified when db is not specified. '
ValueError: A logdir must be specified when db is not specified. Run `tensorboard --help` for details and examples.

Tried changing syntax by removing "=" but nothing changes
I am able to import tensorflow in jupyter-notebook and in python terminal.
Thanks.

**Comment by nfelt** [comment]
It looks like you have a typo in your second use of the `--logdir` flag, you have `logdr` (missing an `i`) so that's why you got the `ValueError` there.

As to your original first error, do you have TensorFlow installed?  I.e. can you run `python3 -c 'import tensorflow'` and have it succeed?  TensorBoard currently requires TensorFlow to be importable.

**Comment by gowtham-kp** [comment]
Closing this issue due to the lack of recent activity. Please add additional comments and we can reopen this issue again. Thanks!
