### ISSUE TITLE
Tensorboard does not start to produce a proper link

### ISSUE THREAD

**Issue by cjiang18** [tensorflow/tensorboard#993]
When I run tensorboard on my PC , whatever I try, there is only one line generated 

TensorBoard 1.6.0 at http://DESKTOP-KPL14KQ:6006 (Press CTRL+C to quit)

I have been searching for solutions for a few hours, yet no discovery.
Hope someone could help me.
Thanks in advance.

**Comment by chihuahua** [comment]
What do you see when you visit http://DESKTOP-KPL14KQ:6006 in a web browser on your machine? Is TensorBoard running on your local machine? If so, does visiting http://localhost:6006 work?

**Comment by cjiang18** [comment]
After reinstalling tensorflow and searching further, this problem is solved. But it only works if I use 

python -m tensorboard.main --logdir="path/to/my/logs"

Thanks for your help anyway.
