### ISSUE TITLE
Tensorboard not show my event file

### ISSUE THREAD

**Issue by keishatsai** [tensorflow/tensorboard#996]
Hi, I am new to Tensorboard.
I would like to see the result of my event file. but there is no result after I point to the file directory.
Does anyone can help me? thank you.
my command:
`tensorboard --logdir=/monodepth-tmp/model20180214_indoor_extreme2/model20180214preCity2IndoorExtreme2`
and my filename under directory:
`events.out.tfevents.1518594248.TV01011570UP`
![screenshot from 2018-02-23 10-44-07](https://user-images.githubusercontent.com/8175070/36575573-993dc832-1886-11e8-9356-abb057c9a0fb.png)

**Comment by nfelt** [comment]
Hmm, are you sure you're writing summary data within that events file?  You can try running `tensorboard --inspect --logdir=<logdir>` and let us know what that output is.

Also, can you provide your TensorBoard version number (printed out when it starts up) and your OS platform and version number?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorboard) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
